### ISSUE TITLE
Added 64x64 option for panels in FPP

### ISSUE THREAD

**Issue by lassauce** [FalconChristmas/fpp#1000]
Hello, is it possible to add the 64x64 option in the management of the type of panel.  I want to use 64x64 P3 panels and they are not supported in FPP 4.6-2

**Comment by darylc** [comment]
@lassauce  Please stop opening multiple issues for this.

**Comment by lassauce** [comment]
can you tell me how we do it thanks

**Comment by ghormann** [comment]
Duplicate. of #1001  Closing.
