### ISSUE TITLE
Added 64x64 option for panels in FPP

### ISSUE THREAD

**Issue by lassauce** [FalconChristmas/fpp#1001]
Hello, is it possible to add the 64x64 option in the management of the type of panel.  I want to use 64x64 P3 panels and they are not supported in FPP

**Comment by ghormann** [comment]
A possible fix has been added to master.   Thanks @darylc !

**Comment by lassauce** [comment]
hello you have put 128/64 will it be possible to meter 64/64

**Comment by darylc** [comment]
@lassauce Assuming you are running a Pi, and you update to the latest version of master you will see 64x64

**Comment by lassauce** [comment]
![received_540358480293126](https://user-images.githubusercontent.com/47104854/121248396-af3a7380-c8a3-11eb-8f21-360313144b3e.jpeg)
Here is what it looks like on panels 64 64 do you want to see the Marigold

**Comment by dkulp** [comment]
I'm pretty sure none of the common hats/capes that we use have the "E" line that would be required for the other half of the panel to work.   It's quite likely that the 64x64 panels will require a colorlight.

**Comment by lassauce** [comment]
justilise a pi with dragon hat and the cables supplied with

**Comment by darylc** [comment]
I don't think it makes sense to add 64x64 as an option for non colorlight options as Dan said above.

@lassauce the workaround if you are using a hat that does support the E line, then you can try manually editing the config file as I suggested in one of your other duplicate issues.  It's the ~fpp/media/config/channeloutputs.json file - just tune the values to match your panels.

I think we should close this issue.

**Comment by darylc** [comment]
@ghormann Can you close this one please?
