### ISSUE TITLE
backup.php displays json in browser vs downloading

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1013]
**FPP Version and Hardware**: 
FPP 5.0-Alpha running on Pi

**Describe the bug and Steps to reproduce**: 
1. Go to backup.hp
2. Click on `Download Configuration`
4. JSONdisplays in browser.

**Expected behavior**: 
Should download the JSON file

**Comment by jaredb7** [comment]
Hi Greg,

I can't get this to happen on 5.x-master-230 via Docker, Tried via Chrome, FireFox and Edge and end up with the download dialogue or download automatically 

Can you try it again then check the Apache log -> apache2-error.log, any errors reported by the setting backup side is prefixed "
BACKUP:  " so should stand out if any.
Also look for any errors relating to setting headers, the script sets a few headers to tell the browser we're downloading a JSON file then basically reads the data out

If there isn't anything in the logs, do you have any special characters in the hostname?

**Comment by jaredb7** [comment]
Whoops, didn't want to actually close this.

Could you test this out now @ghormann ? If it's still occurring refer to me comment above to try get more info.

Cheers,

**Comment by darylc** [comment]
@jaredb7  I don't want to update to pull your patches in just yet as it will overwrite my patches, however running master before your changes produces the following log errors after pressing the download configuration button:

[Sun Jun 06 21:12:12.577596 2021] [php7:notice] [pid 10851] [client 192.168.34.153:58882] PHP Notice:  Undefined index: currentHeaderSensor in /opt/fpp/www/menu.inc on line 91
[Sun Jun 06 21:12:12.592005 2021] [php7:warn] [pid 10851] [client 192.168.34.153:58882] PHP Warning:  Invalid argument supplied for foreach() in /opt/fpp/www/menu.inc on line 240
[Sun Jun 06 21:12:17.174885 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  file_get_contents(/home/fpp/media/config/proxies): failed to open stream: No such file or directory in /opt/fpp/www/backup.php on line 183, referer: http://192.168.34.200/backup.php
[Sun Jun 06 21:12:17.175880 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  file_get_contents(/home/fpp/media/config/interface.wlan0): failed to open stream: No such file or directory in /opt/fpp/www/backup.php on line 183, referer: http://192.168.34.200/backup.php
[Sun Jun 06 21:12:17.177385 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/fpp/www/config.php:540) in /opt/fpp/www/backup.php on line 1257, referer: http://192.168.34.200/backup.php
[Sun Jun 06 21:12:17.177511 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/fpp/www/config.php:540) in /opt/fpp/www/backup.php on line 1258, referer: http://192.168.34.200/backup.php
[Sun Jun 06 21:12:17.177609 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/fpp/www/config.php:540) in /opt/fpp/www/backup.php on line 1259, referer: http://192.168.34.200/backup.php
[Sun Jun 06 21:12:17.177666 2021] [php7:warn] [pid 20971] [client 192.168.34.153:58883] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/fpp/www/config.php:540) in /opt/fpp/www/backup.php on line 1260, referer: http://192.168.34.200/backup.php

**Comment by jaredb7** [comment]
@darylc  Ah, awesome! thanks for that snippet. The change I made will fix this then, there section in config.php that outputs a a script tag, previously I think this was disabled in fppjson.php and I didn't need $skipJSsettings in my own.

**Comment by ghormann** [comment]
@darylc  @jaredb7   Thanks for assist on this.    I made adjustment to the patch to only set the variable in POST mode.   This fixes the menu on the page.        Appreciate any additional testing before closing.

I'll work the `currentHeaderSensor in /opt/fpp/www/menu.inc` issue.  It is unrelated.

**Comment by ghormann** [comment]
Closing.   Seems stable.
