### ISSUE TITLE
New UI reports Audio Device as DUMMY  choosing a USB stick doesn't actually save and survive a reboot

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1018]
# Please answer the following:
**FPP Version and Hardware**: 
Latest Master as of 6/6/2021
BeagleBone Green with F8-B cape and USB audio Dongle
Chrome browser

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Setup a playlist with Audio file.
Configure audio for USB device, and restart fppd
Load play list
Click play
I hear the file playing but the UI is throwing an error.  Outputting Audio to Dummy Device
See attached
![image](https://user-images.githubusercontent.com/8147459/120929901-843bfe00-c6b0-11eb-884e-a5c62eefbc27.png)
![image](https://user-images.githubusercontent.com/8147459/120929906-8900b200-c6b0-11eb-84d3-71617bd17bce.png)

Also note: As a test I rebooted the BBG, when it cam back, the audio setting was back on Dummy. I don't this we are correctly saving that setting.  I tried a 2nd reboot and it's not saving the audio setting.

**Expected behavior**: 
There should be no error

**Comment by darylc** [comment]
so I'm not seeing this on Pi using a USB audio device

**Comment by thekev** [comment]
Check for corrupted `~/media/settings` file. I experienced this on a 5.5 master that had been running since last season. Settings weren’t being read at boot.

**Comment by darylc** [comment]
@patdelaney is this still an issue?

**Comment by dkulp** [comment]
This was almost certainly a boot delay issue with the USB taking too long to enumerate so it reverts to dummy at boot as the soundblaster is unavailable.
