### ISSUE TITLE
NTP is on by default but the UI doesn't reflect that

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1020]
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.x Alpha image on Pi 4  no clock chip
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
I've noticed this before and may have mentioned it, I believe that NTP is on by default but the UI doesn't reflect that on a fresh install.  I just loaded the 5.x alpha image on a Piv4 with no clock chip. When the web UI came up for the initial config setup. The date and time were correct even though when I go to the Time tab Enable NTP is not selected.

**Expected behavior**: 
If NTP is really on by default, then fix the UI to reflect that.

**Additional context**: 

**Additional Attachments**
![image](https://user-images.githubusercontent.com/8147459/122684763-1245d780-d1cd-11eb-8593-9aecf9bd464f.png)

**Comment by ghormann** [comment]
After discussions among the core developers, we agreed that  ditching the setting is the correct choice.  NTP will be enabled by default. The user can still choose the upstream ntp server via settings.  Will also clarify that if the field is blank, the system will use the debian ntp pool.
