### ISSUE TITLE
Channel Inputs Status screen

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1028]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 

FPP v5.x-master-306-g39a4319b (master branch)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

When Live Update Stats is selected, there is a constant flicker (refresh maybe?) of the screen. This doesn't happen with the Live Update Stats on the MultiSync Packets section.

Also, there is no reset button on the Channel Inputs section like there is for the MultiSync

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by ghormann** [comment]
@Poporacer : I'm not able to reproduce.   Can you provide more details on how to reproduce? 
Test video: https://youtu.be/NClbcQNAHNU

**Comment by Poporacer** [comment]
Here is a video of the issue. To reproduce, all I do is select the Live Update Stats.
My test video https://youtu.be/DvOgKhZVH5Q let me know what else you need.

**Comment by ghormann** [comment]
@Poporacer    Thanks for the video.   I'm struggling to reproduce this.   I increased the number of input channels and it still doesn't flicker like that.

Few questions
-  What browser (and what version) are you using? 
- Can you send your configuration files? Easiest way to do that is this process which will send both logs and configuration: 
    1. Open the FPP UI
    1. Open the the File Manager (Content Setup->File Manager),
    1. Select the "Logs" tab
    1. Click "zip" button.
    1. Attach to this ticket.

**Comment by ghormann** [comment]
Actually, I just reproduced it.   The device must be in Remote mode this this problem occurs.   I'll work on a patch

**Comment by Poporacer** [comment]
Sorry I didn't get back sooner, but looks like you found the issue!

**Comment by ghormann** [comment]
@Poporacer  No worries!  Took me a bit to figure out what was different.   

I also just added a button that allows the stats to be reset via dd33ea6.
