### ISSUE TITLE
[BUG][UI] Backup Page doesn't display correctly on touch screen.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1030]
Version 5.0 - Master

If the backup.php change is in F12 mode on Chrome or if  using a portal device, there is a large amount of whitespace between the tabs and the content of the page.  

![image](https://user-images.githubusercontent.com/24968726/124401039-e0686100-dcf4-11eb-8ea6-71789a0f2988.png)

It may be related to this css where a div isn't correctly positioned.  I've not had enough time to figure it out.
![image](https://user-images.githubusercontent.com/24968726/124401096-8d42de00-dcf5-11eb-902e-eec11ef66b41.png)

**Comment by jaredb7** [comment]
I've been up and done the structure of the backup page and basically what we have on the settings page with the layered div's,  I did end up moving a few things around which didn't have any impact.

I ended up changing height: 100% to min-height: 36px (36.7px is the computed height of the navbar), even removing the height property allows it to show normally but it's there for a reason so settled on min-height so the navbar stays visible.

There doesn't seem to be any negative impact on other pages like settings so I figure it should be ok

**Comment by ghormann** [comment]
While maybe not 100% correct, the fix seems to be holding.    I'm not seeing any obvious issues.

closing.

**Comment by jaredb7** [comment]
Yeah it doesn't feel that fix was the 100% correct one but it worked. I have an theory why it's doing it but couldn't put my finger on it to prove it.

I'll revisit this in the near future and see if I can't figure it out.
