### ISSUE TITLE
Current proxy configuration will not work with devices that only support gzipped content

### ISSUE THREAD

**Issue by keithsw1111** [FalconChristmas/fpp#1031]
The current proxy settings in the apache configuration file strips off the Accept-Encoding tag which should force proxied sites to return uncompressed content which FPP then passes back to the client.

This is an unnecessary restriction as using an Output Filter apache can inflate any such requests before making proxy related updates to the content.

So removing the line

RequestHeader unset Accept-Encoding

within the <Directory /opt/fpp/www/proxy> section

and replacing it with

SetOutputFilter INFLATE

would remove this restriction.

While websites should not require the client to support gzipped content the size of uncompressed content can be an issue and as every browser does support gzipped content offering both ideally would not be an absolute requirement for a memory constrained IOT device.

**Comment by darylc** [comment]
Pull request https://github.com/FalconChristmas/fpp/pull/1033
