### ISSUE TITLE
FPP Backup doesn't backup Arcade Games plugin data

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1032]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP Master Branch  5.x

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
I have the FPP arcade plugin configured.
I went to backup settings, I selected Plugin settings and clicked download. It errored out.  See screenshot

**Expected behavior**: 
It should backup the plugin data for the arcade plugin

**Additional Attachments**
![image](https://user-images.githubusercontent.com/8147459/125374699-2654a300-e34d-11eb-946b-ca64a6fd9a94.png)
![image](https://user-images.githubusercontent.com/8147459/125374726-37051900-e34d-11eb-8716-b390d8280ff3.png)
![image](https://user-images.githubusercontent.com/8147459/125374806-6582f400-e34d-11eb-84cb-fd38098c7b51.png)

The joysticks.json file is located in FPP\config directory  is the backup looking there?
here is the file as a zip
[joysticks.zip](https://github.com/FalconChristmas/fpp/files/6805235/joysticks.zip)

**Comment by jaredb7** [comment]
I had a play around with this and the reason for the error is that as far as the setting backup system is concerned there are no plugin config files to backup (there are but the system isn't aware of what joysticks belongs to)

The settings backup basically looks for files in /config that contain the word "plugin." at the start of the filename and adds it to a list of files it knows about, the plugin name to associate with that file is extracted from the setting filename eg. plugin.fpp-arcade.json (which it writes when setting the type of game to display under Content Setup)
Hopefully that makes sense....

It's probably a rare occurrence that plugins have more than one config file for their settings, which is fine but normally they're all in one file. I'll work on making that work though.

**Comment by jaredb7** [comment]
Could you give this a quick test? Do a backup of the plugin config, delete/modify the Arcade joysticks configuration and then restore the backup to confirm everything comes back?

Fairly sure it should be all ok, I have tested via Docker and plugin configuration comes back for Big Buttons and Arcade

**Comment by ghormann** [comment]
@patdelaney  Can this be closed now?

**Comment by patdelaney** [comment]
I need to check

**Comment by ghormann** [comment]
@patdelaney  Did you get a chance to test?

**Comment by patdelaney** [comment]
No forgot, I'll get to it this weekend

**Comment by patdelaney** [comment]
It no longer crashes, but is doesn't backup the Arcade Plugin. The Arcade plugin actually installs 2 plugins, under content Setup you will see Arcade Games, and under input/output you will see FPP Arcade Joysticks. For my use case I only want the Joystick plugin so I can use the buttons on the joystick as GPIO trigger. The Joystick plugin is not detected in the FPP backup when you select just the plugin to back up.
I did find a work-around.
Add any one of the Arcade Games, save and restart fppd.
Delete the Arcade game you just created, restart fppd

That creates the json file that we need for the backup and the Joystick settings are in that file.

**Comment by jaredb7** [comment]
I'll revisit this, I did notice that there were 2 config files, one is joysticks.json and the other plugin.FPP-Arcade.json (something along those lines). And I made a some changes so we can get both as considered to belong to the 'FPP Arcade' plugin.

I was doing the All Settings backup and and verifying both were being backed up, but just noticed you're just choosing Plugin backup so maybe there's something going on there.
The logic is pretty much the same but maybe I've overlooked something when the user is choosing a specific section/setting to backup

**Comment by jaredb7** [comment]
Hi @patdelaney  are you checking the JSON backup file to see if it has the contents of joysticks.json?

while i can't configure controllers (I gather I need a Controller/HID device plugged in) I have manually thrown stuff into joysticks.json and can see it in the backup.
![image](https://user-images.githubusercontent.com/799998/135068752-e8ebc8eb-dfb8-45fa-9266-7b6429bc670a.png)

The backup system is being told to get that file if it's determined the fpp-arcade plugin is configured (basically through detection of plugin.fpp-arcade.json)
![image](https://user-images.githubusercontent.com/799998/135069061-05c1645c-a84a-4739-80bb-d3439601a7e0.png)

**Comment by dkulp** [comment]
Question: is there a reason we don't just grab every .json file in config?  Seems like that would be the most reliable way to get all the json config files.   The property list files are another matter, but the json stuff seems like it should be simple.

**Comment by jaredb7** [comment]
There's no valid reason that it's not done that way or changed to do that, initially it worked out that all the known config files were mapped to their respective areas and nothing was stored outside of those.
This plugin was a good example though why I need to, and in a more dynamic way than my lame workaround

I've built in that functionality just need to sort out the restore side of things.

I'll probably do the same for the network interfaces too
