### ISSUE TITLE
Trigger Remote Audio

### ISSUE THREAD

**Issue by Nic53188** [FalconChristmas/fpp#1039]
I'd like for my master Pi to trigger another FPP instance like a K8 to play audio from the K8 as well as the master Pi.  If the audio files live on the K8, I'm using the K8 in remote mode, it's on a wired show network, and I'm using a sound blaster, I would think there shouldn't be any lag.  I'd love to play music down by the street where I'm having a dance zone (theme).  I'm trying to get a speaker feed out to that area without blasting audio from where the master Pi is in my attic.

**Comment by dkulp** [comment]
This is already there.... If the remote has audio files that match the master, they will automatically start when the master does and stay pretty much in sync.   That said, if it does need to adjust speed for any reason, you may hear a pop or pause or something in the audio as the adjustments are made.

**Comment by ghormann** [comment]
Closing as already implemented.   If we are not understanding the requirements, let us know.
