### ISSUE TITLE
newui branch is still listed in FPP branch list

### ISSUE THREAD

**Issue by bjhiltbrand** [FalconChristmas/fpp#1040]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: FPP 4.6 running on BBB
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
As a user under a "Developer" User Interface level:
1. Go to the developer tab
2. Click on the git branch dropdown.
3. See that the 'newui' branch still exists.

**Expected behavior**: 
In the VCS presentation linked here: https://www.youtube.com/watch?v=8Cmy6-haWlo It was stated that the 'newui' branch is behind the v5 master branch, and needs to be removed to avoid confusion.

**Comment by darylc** [comment]
@bjhiltbrand The newui branch will disappear once you reimage with FPP version 5 images.

**Comment by ghormann** [comment]
I'm going to close this. Just confirmed even in 5.0-alpha os image "newui" is removed.
