### ISSUE TITLE
Enlarge the FPP Host name

### ISSUE THREAD

**Issue by chuckackerman** [FalconChristmas/fpp#1044]
[](url)I have several FPP 5.x devices and sometimes I find myself on the wrong one.  The name on the top of the screen is a little small for my ageing eyes.  Is it possible to have the name of the FPP in LARGE letters across the top banner?  This little thing (I hope it's little) would be a big deal for me.

Thanks.

**Comment by MarkA75160** [comment]
![EFA8B12F-257E-4234-8F15-CDAC10224A2F](https://user-images.githubusercontent.com/57245161/126726685-3e63a0f0-adbc-42bc-92f9-1bde4920bad7.jpeg)

**Comment by patdelaney** [comment]
For grins In the browser I resized the window and the hostname disappears, The same thing happens on my Android phone in Chrome.
![image](https://user-images.githubusercontent.com/8147459/126736959-706c4042-511f-4bf1-9b5e-974d80296bf0.png)

**Comment by patdelaney** [comment]
![Screenshot_20210722-232030_Chrome](https://user-images.githubusercontent.com/8147459/126737064-11bbb349-ff47-4ec0-92ee-ec1a7dc10084.jpg)

**Comment by ghormann** [comment]
I pushed this change .  It works very well for me at all sizes because my hostnames are small.  Not yet promising it will stay this way. :-)   Lets see what feedback is received.

**Comment by MarkA75160** [comment]
The new, bigger hostname seems to only appear on the main Status page, but not all the other pages (Network, Multisync, File Manager, etc.)
![image](https://user-images.githubusercontent.com/57245161/126774240-7c0a1754-b72f-41c1-987d-b571f4bad473.png)
![image](https://user-images.githubusercontent.com/57245161/126774309-5b026d12-34aa-4487-9d52-6faed1b0781f.png)

**Comment by MarkA75160** [comment]
I don't know the difficulty, but wouldn't it be better to put the Hostname here where the generic "FPP" name is displayed in the banner?  I think that would then carry over to every page.
![image](https://user-images.githubusercontent.com/57245161/126774638-8e20c643-f5bf-4df6-abd4-eb859f8ae5d9.png)

**Comment by ghormann** [comment]
Yes.   That was on purpose.  This is needed on the others?

**Comment by MarkA75160** [comment]
"Yes.   That was on purpose. "

Were you replying to me or Pat? :) 

I do think it should be more visible on the other pages besides just the Status page, but understand it might be intentionally different/smaller for mobile screens

**Comment by chuckackerman** [comment]
First of all, thanks for working on this so quickly.  I agree with MarkA that the large name should be visible on all pages.  I spend most of my time on non-status pages.  

As an explanation:  I have all of my FPP devices open all the time, each with their own tab in Chrome.  I click on the one I want to work on when needed. But I have maybe 50 tabs open in Chrome where only 4 of them are FPP.  All of the tabs for FPP look identical so I may have to click on more than one before finding the one I want to work on.  When I click on an FPP tab, the last page I used is shown and it's generally not the Status page.   Any quick way to identify the page without having to go back to the status page would be helpful.

Thanks for your efforts.

**Comment by ghormann** [comment]
Dan implemented a change to enlarge the hostname on the header, and I push pushed some fixes for mobile.
