### ISSUE TITLE
Multisync page: Add option to export data.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1048]
# Is your feature request related to a problem? Please describe.
When managing a large number of remotes, it would be nice to have an option for exporting that data to CSV. 

# Describe the solution you'd like
The Multisync page should have an option that exports most of the visible data (source api/system/status?ip[]=) to a csv file

# Describe alternatives you've considered
Just saving the Json file.

**Comment by ghormann** [comment]
Just committed a porotype implementation.  Feedback welcome. 

@jnealand  fyi.

**Comment by jnealand** [comment]
Finally got updated and a couple of units powered up   Looks like a table dump which is a start, but not really useful for show documtentation purposes.  One problem is the variable names are so long that you really have to expand every column to see what the data is in that column.  I copied the column names and pasted them transposed to a vertical list.  Takes a 37.5 column width to see all the column names.  There are a lot of fields that are not meaningful from a documentation status although I'm sure they are needed while running a show.  And a lot that info is not displayed on the multisync screeen.   I will go thru the fields and let you know the ones that IMHO would be good to have, at least that I would want.  I have no idea how you would create a skinner export.  I have attached list in excel and plan to add a column that I will use as desirable for an export.
[export field names.txt](https://github.com/FalconChristmas/fpp/files/6988907/export.field.names.txt)

**Comment by ghormann** [comment]
Thanks Jim.

**Comment by darylc** [comment]
@ghormann do you have more plans here or are we done?

**Comment by ghormann** [comment]
@darylc Honestly.  No additional plans...
