### ISSUE TITLE
Move UPTIME display field to different column on multisync page so its visible without having to hover

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#1050]
**Is your feature request related to a problem? Please describe.**
A recent FPP update moved the UPTIME display field to a popup window which requires hovering the mouse to see it.  Previously, UPTIME was always visible and all FPP instances could be seen at the same time.

**Describe the solution you'd like**
Move the UPTIME display field to another column so its always visible for all instances without needing to hover one-by-one.  The Hostname column seems like a good candidate, or possibly under the OS field in the Version column.  

**Describe alternatives you've considered**
An alternative would be to swap the UPTIME and MEM% fields under the Utilization column, making UPTIME always visible and MEM% show in the hover/popup since MEM% rarely changes and is not commonly monitored

**Additional context**
![image](https://user-images.githubusercontent.com/57245161/127198923-6061e646-16a6-410c-a595-716782f529f4.png)

**Comment by ghormann** [comment]
@MarkA75160 What if we add an "icon" for the over and restore Uptime.   I *think*  we can still fit a small icon in that cell without going to 4 lines.  I'll put this on my todo list, but it may be a few weeks.

**Comment by MarkA75160** [comment]
@ghormann not sure I understand your question.  Are you saying you could put Uptime back where it was originally and then add a small icon for the "More..." part?     That would be fine by me.  If more space is needed I still think  you could move the Mem% into the popup.  It rarely changes and is not a number that gets monitored very often.

**Comment by ghormann** [comment]
> Are you saying you could put Uptime back where it was originally and then add a small icon for the "More..." part? That would be fine by me. 

That is my plan.  See if I can get all three to fit.  If not, then hide mem.

**Comment by ghormann** [comment]
Here is the current "more" concept.  Didn't get awasomefonts figured out yet, but this seems reasonable. 
![image](https://user-images.githubusercontent.com/24968726/127771011-4ff7744a-06a4-431a-bfcc-6a7129a81e4d.png)

**Comment by MarkA75160** [comment]
Looks good, but you can probably remove Uptime from the 'more' popup window now (redundant)
![image](https://user-images.githubusercontent.com/57245161/127906482-159decad-17e5-443a-bb43-a6f7f11e456d.png)
