### ISSUE TITLE
FPP Backup-Restore from USB showing system files

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1053]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP Master 398

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
When using the Restore from USB function in the FPP Backups section, the System files on the USB drive are showing as a backup path.

**Expected behavior**: 
A user should only see the valid backup paths

**Additional context**: 

**( Enhancement request)** The copy and restore routines use the older method where the process would navigate away from the FPP webpage and then the user had to click on a return button at the end, It would take then to the Status page. The newer method of a pop-up progress window should be incorporated.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by cpinkham** [comment]
Can you check this out now after c200f4a3691 and see if we can close this ticket?
