### ISSUE TITLE
Allow Boot Delay to accept wider range of values beyond 1-30 seconds

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#1054]
**Is your feature request related to a problem? Please describe.**
Some users have network equipment that need more than 30 seconds to reboot after power outage.   The FPP Boot Delay setting currently has maximum of 30 seconds.

**Describe the solution you'd like**
Would like to be able to set Boot Delay up to 3 minutes or longer

**Describe alternatives you've considered**
Can probably do this with the optional UserCallbackHook script, but adding to the Web UI settings would be nicer and easier for less advanced users

**Additional context**
![image](https://user-images.githubusercontent.com/57245161/127765783-299212e3-5a69-480e-a91d-096f2b611929.png)

**Comment by ghormann** [comment]
@MarkA75160 Fixed this, before I realized you assigned it to yourself. Sorry about that.

 Curious.... What is the purpose for the longer delay?

**Comment by MarkA75160** [comment]
It was requested in the Falcon FPP forum
https://falconchristmas.com/forum/index.php/topic,14291.msg119404.html#msg119404

"Some users have network equipment that need more than 30 seconds to reboot after power outage"
