### ISSUE TITLE
Output Komby wireless to an nRF directly connected to Pi's SPI port

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#106]
If somebody's not using the SPI port for something like the FPD, we can output directly to an nRF using Komby's protocol.  I'm familiar with that code and Greg has done some initial work getting an nRF transmitting from a Pi.

**Comment by cpinkham** [comment]
Closing this ticket since this was added to master already.  Any issues can be covered under another ticket.
