### ISSUE TITLE
Hour calculation not correct for 12:00 or 12:30 if using AM/PM time format setting

### ISSUE THREAD

**Issue by dmjpixel** [FalconChristmas/fpp#1060]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
*FPP 5.x-master-419-gae10a0b6 running on PI 3*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Must be using AM/PM hour format to see this issue (set in the UI section on FPP Settings screen)
2. Go to Content Setup then select Scheduler
3. Click Add and then select 12:30 PM for Start Time and 3:00 PM for End Time, select a playlist and then click save
4. Click Preview and it will show the schedule starts at 12:30 AM and ends at 3:00 PM
5. Click Status/Control then Status Page and it will show the next start time is 12:30 AM
5. Click Add and select 12:00 AM for Start Time and 12:30 PM for End Time, select a playlist and then click save
6. Click Preview and it will show the schedule starts at 12:00 PM and ends at 12:30 AM

**Expected behavior**: 
Selecting 12:00 AM or 12:30 AM should appear as AM (same for 12:00 PM or 12:30 PM - should appear as PM) in the schedule preview screen but more importantly the schedule itself.  Looking at the status screen can confirm the next scheduled time is incorrect.

**Additional context**: 
In looking at how the time is stored in schedule.json 12:00 PM is stored as 24:00 and 12:30 PM is stored at 24:30; 12:00 AM is stored as 12:00 AM and 12:00 PM is stored as 12:00PM.

In looking at "function Convert24HToUIFormat(tm)" in fpp.js (line 459), the code at lines 486-490 set the AMPM flag to PM if hour >=12.  12:00 or 12:30 AM will trigger the IF statement and change the ampm flag to PM.  

var ampm = 'AM';
    var h12 = h;
    if (h >= 12) {
        ampm = 'PM';
        h12 -= 12;

Still trying to understand how the 12:00 PM and 12:30 PM is changing to AM...thought I saw it but must be getting tired because I am not seeing that now.

I think changing line 488 to the below snip would fix the issue (?)
if (h > 12) {

Hope this is helpful...I could be way off!  :)

Thanks-Dave

**Comment by dmjpixel** [comment]
In looking with less tired eyes today I think this spans more than the one function I originally mentioned.  Going to continue to study and see if I can come up with fix.  If I am treading into someone else's work efforts just let me know.

**Comment by dkulp** [comment]
Fixed in 9ae1a1e2b37bf6c71c3d7a1be1f22239cb03d27f
