### ISSUE TITLE
Add NAT Option for FPP to Allow Show Network Full Internet Access

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1067]
**Is your feature request related to a problem? Please describe.**
Internet access doesn't completely work on "show" networks.  Things that do work

- NTP (via FPP gateway)
- Updates (via FPP gateway) 

Things that don't work
- Plugin manager
- Things that don't fit directly to what's been developed inside FPP

**Describe the solution you'd like**
The option to enable NAT (iptables called it masquerading) in addition to the "routing between networks" option.  These can work hand in hand.  This could result in some confusion though as there is another networking option.  I could see there being 4  options
- Both routing and nat disabled. 
-- Works like it does out of the box today
- Routing enabled and NAT disabled
-- Works like it does today (L3 lookups in the routing table and traffic is allowed to forward)
- Routing disable and NAT enabled
-- All traffic from show network to home network would be NATed.  Nothing would be routed though.  
-- Impact would be devices on the home network could NOT communicate with show network unless using a proxy but all devices on the show network that have a proper default gateway would have internet access
- Routing enabled and NAT enabled
-- Devices on the home network would be able to reach show network
-- Devices on the show network would ROUTE to the home network and not be NATed
-- Devices on the show network would NAT to the internet and NOT be routed.

In order for this to work I believe there would need to be a formal concept of a show and home network (or name it whatever) so that the masquerading rules would be assigned properly.  Could be implemented much easier if using ufw or firewall-cmd as both of these hide most of the iptables complications.

**Describe alternatives you've considered**
Use built in features for FPP (proxies for github/ntp) and routing.  The issue with the routing option is many home routers don't have the ability to add static routes.  Double NATing, although ugly, will remedy this issue.

I'm sure there could be other devices on the show network that having internet access would be useful for too that won't work out of the box.

**Additional context**
None

**Comment by darylc** [comment]
Ideally #118 would be done before/with this one to make this more useful.

**Comment by MrPaulAR** [comment]
I think these can be separate.  This request assumes networking is already configured.

I do think both are valid and I'm happy to provide whatever systems level support/configs the developers may need for either of these.

**Comment by MrPaulAR** [comment]
Possibly being fixed in https://github.com/FalconChristmas/fpp/commit/e5bb658817e51cfb3b85dfe300a21a519f132e90

**Comment by cpinkham** [comment]
I believe this can be closed with Dan's recent additions.
