### ISSUE TITLE
FPP 5.0 UI displays 2 network icons even though there is only one on UDOO SBC

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1070]
**FPP Version and Hardware**: 
Example: *FPP 5.x running on UDOO*
https://www.udoo.org/discover-udoo-x86-ii/

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
The logic to display the ip address seems to pull in a second IP address
![image](https://user-images.githubusercontent.com/8147459/128800140-391c78a3-8ff1-4d0d-b87f-862493bf384e.png)

**Expected behavior**: 
Only 1 address should be displayed

**Additional context**: 
I have one of these boards because S4Lights uses these boards as FPP controllers for their customer installations.

**Additional Attachments**
Also note that the temperature setting even though in the settings I said use F.  It looks like the UI is not displaying the C, instead 
 it's displaying an F in either case if you toggle.

![image](https://user-images.githubusercontent.com/8147459/128800838-fbe59b21-73c6-4614-a8ef-da3f12c6f51b.png)

[tshoot.txt](https://github.com/FalconChristmas/fpp/files/6958655/tshoot.txt)

**Comment by patdelaney** [comment]
So I am working with Stephen Morgan on this issue. He said that he went through the syslogs and said the following:
```
"...from the syslogs, it looks like the install script installed a redundant dhcp service called connmand.
this lead to the getting of two IP addresses.
I have removed the installation of connman from the local script and rerun the installation, and I now have only one IP address."
```
we installed a stock debian 10.0 ISO image with no GUI interface.

**Comment by shmorgan** [comment]
This seems to be a conflict with Debian 10.10.0 and the installation script. As part of the base install, Debian already sets up DHCP, the installation script them installs connman, which sets up another DHCP requester. This leads to a Primary and Secondary Interface being setup with two DHCP addresses, weird!! I removed connman from the apt install sections, and the second IP address is no longer being setup. I see other references to connman in the install script, so not sure what this might break. More testing to do.

**Comment by dkulp** [comment]
When you ran FPP_Install.sh, did you run with the -img flag to denote that this is not a desktop system?    In general, we WANT connman installed and would prefer to disable/remove the other one.   connman is what is used on the Pi and BBB systems so if this is an "image" type of install, then it definitely should be using connman.

**Comment by patdelaney** [comment]
We did not run with the -img. But we are installing on hardware, not a debian VM.

**Comment by ghormann** [comment]
I'm marking this as "invalid" as this is not a "bug" that BBB and PI users would experience.

**Comment by darylc** [comment]
@ghormann shall we close this issue then?
