### ISSUE TITLE
FPP_Install.sh additions for Non PI or BBB hardware

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1074]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
While testing FPP on the UDOO, I have some installer script suggestions. These could hopefully normalize the base O/S so it's something we are all familiar with. This would be for a debian based system

- check for the existence of wget, if there OK, if not install it
- check for the existence of O/S installed DHCP client, if there remove it in favor of Conman (apt-get remove isc-dhcp-client)
- edit /etc/default/grub and replace this line:
GRUB_CMDLINE_LINUX_DEFAULT="quiet"  with
GRUB_CMDLINE_LINUX_DEFAULT="quiet net.ifnames=0"
then run update-grub

note after running current install root account is NOT disabled. the root account does have a password.

**Comment by darylc** [comment]
@dkulp Should we consider UDOO a supported platform and accept requests like this, or close them?
