### ISSUE TITLE
FPP 5.1 won't load from FPP-v5.1-Pi.img.zip on RPi 4 B

### ISSUE THREAD

**Issue by chrispoch** [FalconChristmas/fpp#1076]
**FPP Version and Hardware**: 
FPP 5.1 using the FPP-v5.1-Pi.img.zip from the 5.1 release section
RPi 4 B 4GB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Download FPP-v5.1-Pi.img.zip from releases page
2. Flash on 32gb microSD card
3. Insert in RPi 4 B and power on
4. FPPd fails to start with this error in the console output: [FAILED] Failed to start FPPd. See 'systemctl status fppd.service' for details.
5. Visiting http://fpp.local loads a completely blank webpage but it has the FPP favicon in the tab

The error message details are:
fpp@FPP: $ systemctl status fppd.service
fppd.service - FPPd
Loaded: loaded (/lib/systend/system/fppd.service: enabled: vendor preset: enabled) Active: activating (start-post) (Result: exit-code) since Fri 2021-08-20 18:36:33 BST: 1s ago
Process: 13603 ExecStartPre=/opt/fpp/scripts/fppd_boot_pre (code=exited, status=0/SUCCESS) Process: 13619 ExecStart-/opt/fpp/src/fppd -f (code-exited, status-203/EXEC) Main PID: 13619 (code-exited, status-203/EXEC); Control PID: 13620 (fppd_boot_post)
Tasks: 2 (limit: 4212)
CGroup: /system.slice/fppd.service
13620 /bin/bash /opt/fpp/scripts/fppd_boot_post L13630 sleep 2
Aug 20 18:36:33 FPP systemd[1]: Starting FPPd...
Aug 20 18:36:33 FPP fppd_boot_pre[136031: Setup channel outputs
Aug 20 18:36:33 FPP fppd_boot_pre[136031: Running pre-start scripts
Aug 20 18:36:33 FPP fppd_boot_pre[136031: FPP Turning OFF screen blanking
Aug 20 18:36:33 FPP systemd[136191: fppd.service: Failed to execute command: Exec format error
Aug 20 18:36:33 FPP systend [13619]1: fppd.service: Failed at step EXEC spauning /opt/fpp/src/fppd: Exec 
Aug 20 18:36:33 FPP systemd[1]: fppd.service: Main process exited, code=exited, status=203/EXEC 
fpp@FPP: $

**Expected behavior**: 
Initial run that is completely clean. Expected FPPd to load. 

**Additional context**: 
Flashed again with the same issue. Downloaded 5.0.1 and it loads fine.

**Additional Attachments**
See image of the startup screen with issues. ![PXL_20210820_173718377](https://user-images.githubusercontent.com/13859222/130274375-f6f1878e-fe93-4813-bd24-814a638fcdec.jpg)

**Comment by dkulp** [comment]
Somethings definitely wrong with the image... not sure what.   Looks like it may have gotten truncated or something.   In anycase, I'm uploading a new image for the Pi now.   Should be all set in a few minutes.
