### ISSUE TITLE
Wi-Fi Adapter with AP always showing AP in header and AP address in OLED

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1078]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
FPP Master-466 on both a Pocket Beagle and BeagleBone Black

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Install an EDUP Wi-Fi adapter like this one https://kulplights.com/product/1200mbs-antenna-wifi/
2. Configure a wireless network
3. Reboot or power cycle your FPP device
4. Connecting to the Wi-Fi network is many times not successful and the AP is broadcast and requires a power cycle or reboot for it to connect. 
5. When it does connect to the proper Wi-Fi network, the oled display shows it connected via Wi-Fi to 192.168.8.1 on 2 wlan0 interfaces, and the header in FPP shows it connected to the AP interface and the wlan0 interface. The FPP device is NOT broadcasting the AP when it connects to the proper Wi-Fi

**Expected behavior**: 
The oled display and the FPP header should display the network that it is actually connected to.
![image](https://user-images.githubusercontent.com/46263877/130374556-3a74bf19-5412-4c39-908a-3f567e4673f6.png)

**Additional context**: 
It also seems like connectivity to a Wi-Fi network is sporadic with this adapter. The other adapters seem to connect consistently.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by darylc** [comment]
@Poporacer is this still relevant?
