### ISSUE TITLE
Apostrophe in song or video titles causes uploaded files to disappear in file manager

### ISSUE THREAD

**Issue by MDickson00** [FalconChristmas/fpp#1080]
Helped a person in Zoom today that was unable to find uploaded sequences. 
When he uploaded sequences via FPP connect, the sequences showed to visibly showed to upload but we were unable to locate them in content manager.  We noticed that both the sequence and the song had an apostrophe (Sant's coming to town) we removed them and re-uploaded, this time the sequence and the music showed up in content manager.

We were able to recreate the issue with one other sequence. Sadly I ddin't get any screen grabs this time around.

**Comment by thisim** [comment]
This problem has been present since the first versions of fpp.  The problem also arises with letters with accents (é è à ....)

**Comment by MDickson00** [comment]
I know that around 4.5 or 4.6 the issue of special characters was worked on but never competely fixed, in those cases the special characters would stop schedules from running or stop FPPD from running. This issue now makes sequences disappear. If it is in fact the same issue, you would think 5.0 would have addressed it.

**Comment by ghormann** [comment]
I'm unable to reproduce this.  If I upload a file using 5.2 with an Apostrophe in the name, the apostrophe just gets removed.  Here is the cod that does it. 

https://github.com/FalconChristmas/fpp/blob/bccb9d95702dd00fcb871f9e1b849c09320f34b8/www/common.php#L2020-L2027

**Comment by ghormann** [comment]
Originally, I missed the "fpp connect" part in the original post.     FPPConnect still uses the old fppxml.php API where as UI uses the new rest APIs this is why it can't be reproduced in the UI.
