### ISSUE TITLE
Add Panel Size Scan Rates for P4 ColorLight card Panels

### ISSUE THREAD

**Issue by bendudz** [FalconChristmas/fpp#1081]
**Is your feature request related to a problem? Please describe.**
Greg Macaree of https://panelsrus.co.uk has requested support for P4 panels for a particular size & scan rate.

**Describe the solution you'd like**
An option of 80x40x10 & 80x40x20 single panel sizes when a colorlight card is selected on the LED Panels tab.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by darylc** [comment]
Greg also said he would send a pull request for this, so I am a little confused as to why you've logged this as an issue?

**Comment by bendudz** [comment]
> Greg also said he would send a pull request for this, so I am a little confused as to why you've logged this as an issue?

Sorry - I'd spoken to Greg about this & he was happy for me to add the functionality. I've raised a PR https://github.com/FalconChristmas/fpp/pull/1082 to add this.

**Comment by darylc** [comment]
ok lets close this issue now that the PR is accepted
