### ISSUE TITLE
Sequence Lengths Incorrecty Reported on Status Page

### ISSUE THREAD

**Issue by jasonash** [FalconChristmas/fpp#1083]
Sequence lengths are not reported correctly on the main status page.

For example, here is a sequence that is ten minutes long playing:

<img width="799" alt="Screen Shot 2021-09-01 at 8 22 14 AM" src="https://user-images.githubusercontent.com/7904402/131680172-fc428681-9b7b-4f24-804b-84852c5debe3.png">

The length reported in the green bar of the playing sequence is 03:00, but the real length of this sequence is 10:00. The elapsed time and remaining time reported for the main playlist seem to be correct.

Here is my system info:

<img width="423" alt="Screen Shot 2021-09-01 at 8 24 09 AM" src="https://user-images.githubusercontent.com/7904402/131680194-d9134fa2-3289-4da8-ae47-295c2eb6c10e.png">

**Comment by ghormann** [comment]
I'm unable to reproduce.   here is what I did.
1) Create a sequence that is over 10minutes
2) Upload to fpp
3) Create a playlist using "sequence only"
4) Play the playlist.
![chrome_fpE4Kr8yfx](https://user-images.githubusercontent.com/24968726/132929929-9850b54e-3633-4a6f-a4d6-b3415ef4ea2e.png)

**Comment by ghormann** [comment]
Will need more information to reproduce this.  
1) Sequence version (V1 or v2)
2) the playlist.json file
3) Maybe even the sequence file.

**Comment by ghormann** [comment]
closing due to lack of response from requester
