### ISSUE TITLE
Setting playlist start time of 12:00/12:30AM sets to PM 5.0

### ISSUE THREAD

**Issue by relhak1** [FalconChristmas/fpp#1089]
FPP 5.0 on Pi4 4gb

In the scheduler, setting a start or end time of 12:00 or 12:30 AM (and save) gets reset to PM when I reload the page.   I'm limited to ending my show at 11:30PM or 1:00AM.  

This was a very confusing problem while trying to set up my FPP and bench test shortly after midnight, but probably not a problem most of the time.  It would be helpful to just have a 'run continuously' option.  I normally turn off my differential receivers with an AC timer, and leave my controllers on.

**Comment by dkulp** [comment]
This was fixed in 5.1.   Please upgrade.
