### ISSUE TITLE
Feature:	User assignable macro buttons

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#109]
As a FPP user I would like the ability to assign Scripts or Events to a button on the Web UI so that I can trigger and event at any time.

Use case: I have created a script that will be launched from the master pi playlist. The script remotely starts video’s that are playing on 2 other pi’s. (fpp –p <playlist>)  If I choose to stop the playlist on the master pi, I will have to go to the Web UI of each remote and stop the playlists manually. 

Solution: Enable macro buttons on Web UI Status page that can be user assignable to scripts. 

For example:  To automate that shutdown of playlists on those remote Pi’s. (fpp –d)

**Comment by cpinkham** [comment]
I'm going to close this ticket as this functionality is handled by the "Big Buttons" plugin which allows assigning user scripts to UI buttons.
