### ISSUE TITLE
Feature Request - Switch to disable Audio Out

### ISSUE THREAD

**Issue by neowolfwitch** [FalconChristmas/fpp#1092]
I was working on a script that needs pull media (MP3) information from FPP so it can retrieve song information. In order to do this, the media has to be playing with the sequence, but I don't necessarily want the media to actually be outputting audio. In fact, I was running it on a PocketBeagle without any audio. On devices without sound output- this results in an error message: "Abnormal Conditions - May Cause Poor Performance. Outputting Audio to Dummy device."

This may just be an annoying message that actually just means "Hey- you might have audio configured wrong!", but if there really are other performance issues caused by this- it would be great to have some kind of an option to simply turn audio output off. Perhaps as an Advanced UI option, or even in the audio-out drop-down. This may also be handy for testing sequences and for those of us using video as-well, as we might not want the audio to play out of them. I know last year I had a few issues with audio playing out of my projector when I didn't want it too, so this would have helped that.

**Comment by ghormann** [comment]
If all you are attempting to do is extract the meta metadata, why not use the REST API? 
 GET /api/media/Christmas Every Day.mp3/meta

It returns a lot of information, including any tags like artist, album, and title. 
![image](https://user-images.githubusercontent.com/24968726/134486606-a43caf0b-8502-4f7c-9cc0-b079d2d7250f.png)

Also, if you don't want audio to play out of a device (like a projector) , wouldn't setting the Volume to 0 (via API or UI) work?

**Comment by neowolfwitch** [comment]
Thank you for this. I didnt dig that far into the API. I still need to be able to determine what media is playing as part of an active sequence though, so this API call just saves me from using ffmpeg directly. It does streamline things a bit to just use the API for this.

I had asked about whether or not the warning about a Dummy Audio Device would actually cause any problems in the FPP FB page. Nobody really gave me a yes or no, and someone else suggested a feature request to just turn off audio playback. If the only impact is on audio, it doesn't really matter. It would at least be nice to be able to turn off the rather large red error banner though.

Wolf
