### ISSUE TITLE
FPP needs a command added that can programmatically stop media that is started using the "Play Media" command

### ISSUE THREAD

**Issue by HeyRay2** [FalconChristmas/fpp#1095]
**Is your feature request related to a problem? Please describe.**
The "Play Media" command allows for a media file to be started in the background. However, there does not appear to be a way to stop this media file after it has been started, outside of letting the media file play the number of loops defined when the "Play Media" command is first executed, which makes it very difficult to get proper timing between the execution of background media and show sequences running on the same FPP instance.

**Describe the solution you'd like**
I would like to have a "Stop Media" command that would stop any background media that is currently playing, similar to the "Stop Now" command that can be used to stop a sequence or media file that is running in the foreground.

**Describe alternatives you've considered**
Another alternative would be for documentation to be provided on how the "Play Media" command executes the background media file, the process that runs this background media file after it is executed, and how this process can be located and stopped.

**Additional context**
![image](https://user-images.githubusercontent.com/21136720/134846957-68a5daad-1fe9-4ed0-9195-a59b62d50bdd.png)

**Comment by HeyRay2** [comment]
From my review of the FPP documentation it appears that media is played using VLC, but I've tried to locate any VLC (and CVLC) processes while media is playing in the background to no avail, so I'm assuming background media playback is being managed in some other way?

**Comment by ghormann** [comment]
Reopening.  I've disabled this as the solution wasn't stable.   I have an idea on the correct solution but need to time to code and test it.

**Comment by darylc** [comment]
The FPP development team met and discussed this issue.  Decision was made to stop trying to implement this with VLC.  They noted that there is research/consideration related to replacing VLC with something else (for other reasons).  Should this happen, then a stop button would aim to be implemented at that time.
