### ISSUE TITLE
Sparse check in V2NoneCompressionHandler::getFrame()

### ISSUE THREAD

**Issue by forkineye** [FalconChristmas/fpp#1100]
Isn't this check backwards?
https://github.com/FalconChristmas/fpp/blob/825a1f4bddc15937dd7f1362e9ba33c406020d0c/src/fseq/FSEQFile.cpp#L791

**Comment by dkulp** [comment]
I don't think so.   In this case, the file is NOT a sparse file (so all the channels are there), but the fseq reader is configured to only read a subset of the of the channels.   For example, if you have a full v2 sequence for the entire show, but the FPP instance only needs to display 300 channels, we can read just the 300 channels and not the entire frame.
