### ISSUE TITLE
FPP on Raspberry PI Zero W will not join Wifi due to wpa_supplicant errors, possibly broadcom driver

### ISSUE THREAD

**Issue by taylorbird** [FalconChristmas/fpp#1101]
# Please answer the following:
**FPP Version and Hardware**: 
FPP 4.6.1 and 5.2 on Raspberry PI Zero W

**Describe the bug and Steps to reproduce**: 
Out of the box, neither FPP image was able to successfully join WiFi, either defaulting to tethering due to failed connect or simply not connecting (if tethering was disabled post-install).  

Scouring logs produced this error after seeing wpa_supplicant attempting to connect
 CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16

After a few repeated messages, tethering would take over and FPP network will reappear.  Loggin into UI via tether confirms wifi settings persisted correctly.

Oddly `rmmod brcmfmac` would cause it to hop immediately on wifi for a few minutes, but will drop after a cycle.   

Loaded clean Raspian image onto same Pi to rule out hardware and it loaded just fine directly off boot.

**Expected behavior**: 
Expecting FPP to boot from fresh image into tethering mode (it does), and then user logs into UI on FPP network and reconfigures wifi.  Upon, reboot wifi settings are used by wpa_supplicant to join correct wifi.

** This occurs on Raspbian source images, just not FPP **

**Additional context**: 
Nothing odd about this Pi outside of ordered via Amazon in a Canakit box, shows 2017 on the board.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

** I had to leave this project for an issue, will come back and add logs **

**Comment by darylc** [comment]
no response from OP
