### ISSUE TITLE
FPP Connect doesn't update fseq file when parsing special characters

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1103]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  FPP ver 5.2 on Pi 3B+, BBB and PB

**Describe the bug and Steps to reproduce**: 

1. Create a sequence that has an audio file with an apostrophe in the name
2. Use FPP Connect and upload the sequence and media
3. Play the sequence directly from the status page
4. You get an error stating that the fseq file cannot find the audio file and states the audio file with the apostrophe in the name. 

If FPP is parsing special characters from a file name, then the fseq file should have the audio source file name parsed the same as well.

**Expected behavior**: 
When playing an fseq file from the status page, it should play correctly without an error message.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by ghormann** [comment]
I know the problem.  On my list of things to try and fix this weekend, though as a general rule we would recommend against special characters in file names. :-)
