### ISSUE TITLE
Issue with PCA9685 issues

### ISSUE THREAD

**Issue by mchaos** [FalconChristmas/fpp#1106]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:  RPI2 Latest, PCA9685, 8 channel solid state relay board x2
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Set up PCA9685. Connected correct pins to Pi. Pi is communicating with PCA9685. Set up GPIO Outputs, Other, added PCA9685 and all channels.  When testing or running a sequence, lights oscillate, and do not dim. I have run through nearly every frequency in the output settings up to 500hz.  The lights either flash like it's trying to PWM, but the lights never go steady, and do not dim. Checked all connections. Tried all channels. Same thing. It's like its modulating too slow. does the same thing with Incandescent or LED.

**Expected behavior**: 
Lights should be steady and dim with called to dim.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
I am at work. I will do this when I get  home... Getting the ball rolling.

I'll make a video later and supply it.

**Comment by dkulp** [comment]
Did you set the minimum for each port to 0 and the max to 4095 to allow use of the full range?   By default, the PCA9685 output is setup for servo use as that's the more common use of the PCA9685 (and also helps prevent damage to the servos).   The ranges the servos can use is much more limited.

**Comment by mchaos** [comment]
I have not tried this. I had played with the range, however I did  not go to 0.  I did 1000  3000 5000 as well as the default. However what you say makes sense. Fingers crossed, I'll try it later. I will let you know.

Thanks,
