### ISSUE TITLE
FPP 5.2 Wireless not detected on Pi 2b

### ISSUE THREAD

**Issue by marx1** [FalconChristmas/fpp#1108]
**FPP Version and Hardware**:  FPP 5.2 on Pi model 2b

**Describe the bug and Steps to reproduce**: 
Wireless devices are not detected on fresh install:
dmesg output (in logs):
[  275.122342] usb 1-1.4: new high-speed USB device number 4 using dwc2
[  275.254539] usb 1-1.4: New USB device found, idVendor=7392, idProduct=7811, bcdDevice= 2.00
[  275.254576] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  275.254608] usb 1-1.4: Product: 802.11n WLAN Adapter
[  275.254626] usb 1-1.4: Manufacturer: Realtek
[  275.254645] usb 1-1.4: SerialNumber: 00e04c000001
fpp@FPP-TuneTo:~ $ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

usb0      no wireless extensions.

fpp@FPP-TuneTo:~ $ lsusb
Bus 001 Device 004: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
fpp@FPP-TuneTo:~ $

**Expected behavior**: 
Wireless to detect....

**Additional context**: 
[10.101.100.114_10-05-2021-202055.log](https://github.com/FalconChristmas/fpp/files/7290883/10.101.100.114_10-05-2021-202055.log)

[FPP_Logs_20211006.0450.zip](https://github.com/FalconChristmas/fpp/files/7290873/FPP_Logs_20211006.0450.zip)
Installing 5.2 fresh  insted of upgrading a 4.2 install, tried diffrent SD cards to verify it's not a card failing. If I take the SD card and put it in a Pi 3b+ it finds the onboard wifi and usb EDI adapter. Also fails with a TPlink (Atheros based) controller.

Tried rebuild of wireless drivers that resulted in many errors (see attached putty log) as well as updating packages via apt. Based on what I'm seeing it looks like the kernel for the 2b might be messed up.

**Comment by darylc** [comment]
@marx1 per above, did you test on 6.x?  Ideally 6.3 if you are going to test as a result of this notification.

**Comment by ghormann** [comment]
Closing as no reply from OP.  Also, this is a very old version of FPP.
