### ISSUE TITLE
/boot/config.txt files are not the same between Pi B and Pi B+

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#111]
The /boot/config.txt files are not the same for the B and the B+ image, that may or may not be by design, in the B+ image look at the bottom of the file and this section is repeated 4 times:

# NOOBS Auto-generated Settings:
hdmi_force_hotplug=1
config_hdmi_boost=4
overscan_left=24
overscan_right=24
overscan_top=16
overscan_bottom=16
disable_overscan=0

It should be reduced to 1 time 

Pat

**Comment by cpinkham** [comment]
Closing this since it looks like our FPP v2.0 images won't be using NOOBs.
