### ISSUE TITLE
update UI to prevent user from creating UDP outputs back to itself

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#1110]
**Is your feature request related to a problem? Please describe.**
It is currently possible to create E1.31/DDP/Artnet outputs with the destination the same as current device (sending channel data to itself).  This serves no known purpose and can cause performance issues if the user configures it by mistake.

**Describe the solution you'd like**
Update the UI to disallow the user from entering a destination IP the same as one of the current device IP's.  

**Describe alternatives you've considered**
Possibly just make it warning but still allow it if the user is willing to ignore the warning.

**Additional context**
Probably also need to check for a similar misconfiguration when the configuration is pushed to FPP from XLights

**Comment by darylc** [comment]
@MarkA75160  I'd suggest logging this against the xlights project, 99% of the time this problem occurs because xlights did it.

**Comment by MarkA75160** [comment]
Good point.  I agree its probably most often caused by xLights updating the UDP Outs.  And it would be good to have xLights stop sending this type of configuration.   However, I still believe that the FPP code should have checks to protect or limit this from happening, or at the very least, have it show up in the "Warning, may cause poor performance" Banner.

**Comment by ghormann** [comment]
It looks to me like there was already a check for this.  It disables the output, but didn't add a message to the MessageHandler.   That is an easy fix.
![image](https://user-images.githubusercontent.com/24968726/149631418-3b732afc-3f1f-435a-b60a-13fbce94ecfd.png)

**Comment by ghormann** [comment]
Warning added via 79ffaa62925d1ba6074b41a914406677a32ad899
