### ISSUE TITLE
"Error loading list of playlists"

### ISSUE THREAD

**Issue by Tom-Neverwinter** [FalconChristmas/fpp#1113]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

Version Info |  
-- | --
FPP Version: | 5.2
Platform: | Raspberry Pi (Pi 3 Model B+)
FPP OS Build: | v5.0
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 00000000215547e0
Kernel Version: | 5.10.52-v7+
System Boot Time: | 2021-10-10 20:32:57
fppd Uptime: | 00:58
Local Git Version: | 5fcc196 ChangeLog
Remote Git Version: | 5fcc196

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

1. Download all the Atmosfx you can afford
2. convert to 720P
3. upload all the "horizontal" "window" files
4. add all of them to a "randomized" playlist
5. "Error loading list of playlists"
6. profit?

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

Load video files.

set video files to playlist.

schedule to play on x/y/z day

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by ghormann** [comment]
So, using the file manager, you were uploading multiple files at once and it crashed?    Or you mean you mean you put multiple files in a playlist, and then went to save the playlist and that was the error received?    At the moment, I'm not even clear which page you were on when that error came in. :-)

**Comment by ghormann** [comment]
Per Dan's comment in https://github.com/smeighan/xLights/issues/2881 closing...
