### ISSUE TITLE
Lights flash on boot up in Player Mode

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1114]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
4.6, 5.1, 5.2 and 5 master 509
When a K8-B in Player Mode is booting up it will momentarily flash the lights and appears that they are flashing at 100% brightness for a moment. This has caused a couple people to blow fuses on boot up. It doesn't happen when the device is set to Remote Mode

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Set device to Player
2. Disconnect power 
3. Power up
4. Right about the point that the OLED screen goes from "No Network" to the IP address, the lights flash.

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by Darzoom** [comment]
FYI this issue also occurs on the K16.


[FPP_Logs_20211012.1115 (1).zip](https://github.com/FalconChristmas/fpp/files/7329411/FPP_Logs_20211012.1115.1.zip)
