### ISSUE TITLE
Pixels Flicker in Test Mode

### ISSUE THREAD

**Issue by diamondcrescent** [FalconChristmas/fpp#1116]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP 5.2 Running on BBB installed on F16-B and outputting to F16-V1 Pixelnet controllers**: 

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. I hook up my F16-B to an F16-V1 using one of the F16-B's output ports.
2. I plug in a sample pixel string into one of the outputs on each controller.
3. I go into Display Testing and turn on the Enable Test Mode Check Box
4. I can choose other a Chase Pattern or Solid Color Test Pattern, and while the pixel strings on the F16-B follow the  set pattern or stay solid, the strings on the F16-V1 controllers flicker anywhere between every second or 10 seconds or so.

**Expected behavior**: 
On FPP 3.3, the flicker does not occur.

**Additional context**: 
The flickering seems to happen only with testing. Running a sequence SEEEMS fine, but I haven't tested it extensively.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by patdelaney** [comment]
I ran the same test, with F16-B controlling a F16v3, and it works fine. I don't have a F16v1 (blue board). I tried that same test with a F16v2 (red board) and it works as expected. 

The issue sounds very much like you have another FPP instance or xLights configured to output the the F16v1 board at the same time.

Please check.

**Comment by diamondcrescent** [comment]
Yeah, but I'd hate to spend $1000+ dollars on new controllers which are overkill for what I do and the size of my display. I don't think I'll ever be adding anything as big as a Rosa Wreath, LOL! I'm pretty sure that CaptainMurdoch who lives relatively close to me used to (and maybe still does) use PixelNet equipment, and he's worked on FPP code in the past so maybe he'd have some insight?

**Comment by cpinkham** [comment]
I tested this with both an original F16-B and a K8-B running FPP v5.3 (or so) and didn't see any flashing on my test F16v1.  I tested both outputs on the F16-BI was sending 4 full universes of Pixelnet  but only has a few pixels connected to the controller.  Are all pixels flickering or just some of them?  Maybe I don't have enough connected to the F16v1 to see the issue.  I will try to do some more testing later by connecting my two production F16v1 units to the F16-B and K8-B to see if any issues show up on those.

**Comment by diamondcrescent** [comment]
In my testing, I basically had a few "scraps" of pixels hooked up to the outputs of my controllers. Now that everything is set up in the yard, I noticed that all my pixels are affected, though. Thankfully, there isn't no flickering/stumbling/limping of the pixels when playing FSEQ files. I don't know how important it is to fix because it's only happening in test mode. I can send you a quick video later so you can see what I'm talking about.

________________________________
