### ISSUE TITLE
FeatureRequest: Mobile UI

### ISSUE THREAD

**Issue by twoolums** [FalconChristmas/fpp#112]
Would love to see a mobile UI for the basics, currently not the cleanest as seen in a screenshot (ios 7,chrome,iphone 4s)
- Player Status
- Start/Stop what is playing/not playing
- Reboot/Shutdown the PI
  ![photo](https://cloud.githubusercontent.com/assets/7130783/4380053/6792ac9c-4366-11e4-95fb-f4689b919e08.png)

**Comment by cpinkham** [comment]
FPP v2.0 should have a new UI with a responsive web design.

**Comment by ghormann** [comment]
I believe this should be closed.   The current UI is mobile friendly on most screens.  There is also the minimal UI.
