### ISSUE TITLE
File Manager not uploading

### ISSUE THREAD

**Issue by scsa10** [FalconChristmas/fpp#1126]
Attempting to upload audio and sequences results in an error after 3-4 minutes. Progress bar never moves. Uploading from xlights does not work either although program says complete but no files are in FPP. 
[FPP_Logs_20211021.2053.zip](https://github.com/FalconChristmas/fpp/files/7392775/FPP_Logs_20211021.2053.zip)

**Comment by ghormann** [comment]
I don't have much information to go on.    Might be best to get some help in the zoom room.

Apache is throwing a Signal 11 and I can't think of any reason that would happen on a health install.   You *might* need to back up the configuration and reimage the device.   I'd also reimage as 5.3 which has better support for special characters. 

[Thu Oct 21 16:44:37.622843 2021] [core:notice] [pid 1056] AH00052: child pid 1145 exit signal Segmentation fault (11)
[Thu Oct 21 16:44:37.623161 2021] [core:notice] [pid 1056] AH00052: child pid 1146 exit signal Segmentation fault (11)
[Thu Oct 21 16:44:37.886680 2021] [core:notice] [pid 1056] AH00052: child pid 1485 exit signal Segmentation fault (11)
