### ISSUE TITLE
Output Processing Issues On Boot

### ISSUE THREAD

**Issue by jholmes09** [FalconChristmas/fpp#1127]
For reference:
Universe 1 = DMX Flood Lights
Universes 2-8 = Pixels

I have attached a JSON for reference. Using the latest build of FPP (5.3), I created a series of "blackout" output processes that set the level of specific pixels to zero. This affects universes 2-8.

However, on boot and first playback, all pixels are dark.
I have to restart FPPD manually to get the pixels to respond, after which everything works fine.

[FPP_all-backup_v4_unprotected_20211022010752_broken.zip](https://github.com/FalconChristmas/fpp/files/7400990/FPP_all-backup_v4_unprotected_20211022010752_broken.zip)

**Comment by darylc** [comment]
@jholmes09 is this still a problem in FPP 6.3?

**Comment by jholmes09** [comment]
> @jholmes09 is this still a problem in FPP 6.3?

Sorry, I don’t know. I don’t use Falcon anymore.

**Comment by Poporacer** [comment]
Since this cannot be replicated and based on v5.3, closing the issue since it is likely resolved in newer versions.
