### ISSUE TITLE
P10 outdoor 1/2 Scan. 

### ISSUE THREAD

**Issue by KimberlyThorn** [FalconChristmas/fpp#1129]
Is it possible to add the 1/2 scan outdoor p10 to the fpp rpie? I have bought a few of these and would like to use fpp to run them. I have an octoscroller and a colorlight 5A-75B. I could use a plug in for either the pi or the beagle bone black rev C. The outdoor p 10 scan rate of 1/4 is on the pi and the bbb. Not sure how much harder it would be to add this to the options.

**Comment by darylc** [comment]
I assume you mean 32x16 size panels.

32x16 x 1/2 scan is there for BBB, and I've just added it for colorlight/PI
