### ISSUE TITLE
Harden FPP Image (including shellshock fix)

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#113]
I checked and the current image that we are using is vulnerable for shellshock. Raspbian has it fixed we will just need it updated on our image.

http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=87812

for now you can update your pi with this:

sudo apt-get update && sudo apt-get -y dist-upgrade
...
The following packages will be upgraded:
bash libnss3

**Comment by cpinkham** [comment]
We are running Raspbian/Debian Stretch now, so can close this ticket.  We do plan on being more up to date on the OS version in the future.
