### ISSUE TITLE
Led panel setup issue

### ISSUE THREAD

**Issue by bcarriveau** [FalconChristmas/fpp#1135]
5.3.1 BBB

led panel issue, anything over 1 wide causes this.

![2021-10-27 20_27_16-FPP - FPP-k8](https://user-images.githubusercontent.com/60801063/139170558-6f7994c3-5f95-458a-97ea-1c21c8f6ed47.jpg)
![2021-10-27 20_27_25-FPP - FPP-k8](https://user-images.githubusercontent.com/60801063/139170559-e47918db-c7e6-4add-afef-ee15e3de0e13.jpg)

**Comment by ghormann** [comment]
I'm not following.  What's the problem? That there is no arrow in the upper left hand corner? I'm not able to reproduce this in Master.

**Comment by bcarriveau** [comment]
Closing,Will revisit if issue comes up in 6.x.
