### ISSUE TITLE
Intermittent network accessibility

### ISSUE THREAD

**Issue by lrhorer** [FalconChristmas/fpp#1138]
# Please answer the following:
**FPP Version and Hardware**: 

Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v5.0
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 000000003ae36fa7
Kernel Version: | 5.10.52-v7+

**Describe the bug and Steps to reproduce**: 
Routing and network connectivity both to local LAN and to internet appear and disappear intermittently with no particular changes to the system.

![FPP Status](https://user-images.githubusercontent.com/44038449/139277513-bde93c50-6c28-4e8f-a104-27fea31808ef.PNG)

![Ping Gateway](https://user-images.githubusercontent.com/44038449/139279526-b866fe9d-5bac-4cb9-b1e7-7e3ab72d93c0.PNG)

![Ping DNS](https://user-images.githubusercontent.com/44038449/139279618-dc1fa9ee-30c0-4f48-b0f4-f8e5d886b11f.PNG)

![resolv conf](https://user-images.githubusercontent.com/44038449/139279707-38980233-6c6a-4877-8632-771c88c1efc7.PNG)

[FPP_Logs_20211028.1156.zip](https://github.com/FalconChristmas/fpp/files/7435181/FPP_Logs_20211028.1156.zip)

![Command Line](https://user-images.githubusercontent.com/44038449/139280688-6c341e0d-a990-4b3e-b267-a8b0ec7586ab.PNG)

**Comment by lrhorer** [comment]
I changed to a .10 subnet, and it still shows "unknown".

**Comment by ghormann** [comment]
Do a traceroute 8.8.8.8.  Lets at least see where it is getting hung up.   This may be *WAY* faster to find someone in the zoom room.

**Comment by lrhorer** [comment]
It goes nowhere.  It can't even reach the first hop at 192.168.1.1

**Comment by darylc** [comment]
Please troubleshoot this via zoom and re-open if it can't be sorted out there.
