### ISSUE TITLE
Add Player w/multisync as a mode on the multisync page

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1142]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When troubleshooting in the zoom room, it would be very helpful if the Multisync page would display "player w/ multisync" if multisync is enabled.  Right now it just displays player or remote mode.  We have to select on the settings button to see if multisync is enabled or not.  Having this text display give a quick one page review of currently mode settings when having multiple FPP devices. 

**Describe alternatives you've considered**
Just have to show the users where to select the settings button to see if multisync is enabled or not.  alternatively, we can use fpp connect in xlights to view the 3 different mode settings for discovered fpp devices. 

**Additional context**
When using FPP connect in xlights, it already has this distinction.  it will show player for "standalone", player w/multisync, or remote. Just looking to mimic this output on the actualy fpp multisync page.

**Comment by ghormann** [comment]
Self assigning, but it will be a few weeks before I can really look into it. 

Also, I should look at the spacing of the multisync page while there...

**Comment by bloojoop** [comment]
Thanks @ghormann, no rush, just would be helpful.. .thanks for all your work!

**Comment by ghormann** [comment]
Finally Implemented 
![image](https://user-images.githubusercontent.com/24968726/155860549-e698aff3-b03d-4a1c-83a5-890a76ef70aa.png)
