### ISSUE TITLE
Add an option to gpio trigger commands of "start one random sequence from playlist"

### ISSUE THREAD

**Issue by Pauls07** [FalconChristmas/fpp#1144]
It would be great if there was an option added to the gpio commands of "play one random sequence from playlist" so a button can be added and when pressed it will play one random sequence from the defined playlist then stop. 

**Describe the solution you'd like**
An option added to the gpio drop down menu of commands 

**Describe alternatives you've considered**
Tried start playlist from random sequence and then put an all stop command between each sequence in the playlist but this makes the button hit and miss as sometimes it selects the stop all command so has to be pressed a few times to start a sequence.

**Comment by adamcoulombe** [comment]
There is a script called **"CycleRandomSequences.sh"** under Content Setup> Script Repository that already does exactly what you are describing.

Install that script, then, from the File manager page edit it to your needs, for example:

Simply comment out ( add `#` at start of line ) this line, like so:
``` #SEQUENCES=(*) ``` 
then remove the comment (`#`) from the  start of this line and replace sequence filenames with yours, like so:
```PLAYLISTS=("Playlist1.json" "Playlist3.json" "Playlist4.json" "Playlist 5.json")```

Each time you run the script (eg. **Run Command** button >  Run Script) it plays a different sequence each time.

**Comment by darylc** [comment]
@Pauls07 You can use the new "Insert Random Item From Playlist" command to do this in newer versions.
