### ISSUE TITLE
GPIO Inputs page not recognizing media

### ISSUE THREAD

**Issue by bensam2319** [FalconChristmas/fpp#1146]
Hi All,

I'm working with a Pi4 and F16v3 with FPP 5.0 and I've run into an issue with the GPIO input page. Haven't seen any posts about it so it's possible it's user error but I thought I would make a post and see. First, the GPIO page is taking forever to load. Chrome notifies me the page has become unresponsive once or twice before it actually loads. (Note: I haven't used GPIO before so I'm not sure if this is normal or not) Second, when I create a GPIO to start a playlist, it will recognize there is media until I set it to multicast to my falcon. Then the media disappears and it won't show any playlists or effects. 

To replicate: 

Open GPIO Inputs
Create an Input
Command: Start Playlist/FSEQ Start
Select Playlist/FSEQ file
Enable Multicast
Select controller being Multicast to

If it is a bug and not user error is 5.1 more stable? I cant go to 5.3 because of the Wifi connectivity bug. 

Cheers!

![Screenshot 2021-11-09 013554](https://user-images.githubusercontent.com/93059003/140890742-287be703-508c-4955-94ed-ce751fb747ee.png)
![Screenshot 2021-11-09 013616](https://user-images.githubusercontent.com/93059003/140890760-86ae145b-d781-4631-8d46-ee0e70d5e63d.png)
![Screenshot 2021-11-09 012811](https://user-images.githubusercontent.com/93059003/140890776-d5971872-4b29-4ecb-9ab5-acba28be3edb.png)
![Screenshot 2021-11-09 013813](https://user-images.githubusercontent.com/93059003/140890859-ef794586-e76e-4fd3-a22a-1095b0a825f4.png)
![Screenshot 2021-11-09 013832](https://user-images.githubusercontent.com/93059003/140890896-8a5da92e-7ebe-406d-b9db-02af1917bd88.png)
![Screenshot 2021-11-09 012842](https://user-images.githubusercontent.com/93059003/140890909-4d98ca31-774c-44e0-a286-ba88879456ca.png)
![Screenshot 2021-11-09 012722](https://user-images.githubusercontent.com/93059003/140891215-a50109b7-2f7f-4aec-9981-b227c65dabfe.png)
[FPP_Logs_20211109.0820.zip](https://github.com/FalconChristmas/fpp/files/7503132/FPP_Logs_20211109.0820.zip)

**Comment by dkulp** [comment]
I cannot reproduce this.   Are you sure FPPD is fully up and running on both the Pi you are configuring this on and the one at IP 192.168.2.220?    It sounds like it's trying to get the list of media files, but fppd isn't running.

**Comment by bensam2319** [comment]
> I cannot reproduce this. Are you sure FPPD is fully up and running on both the Pi you are configuring this on and the one at IP 192.168.2.220? It sounds like it's trying to get the list of media files, but fppd isn't running.

That could very well be my issue. I'll double check when I get in tomorrow.

**Comment by darylc** [comment]
How did you go @bensam2319 ?

**Comment by ghormann** [comment]
Closing due to lack of response from OP.
