### ISSUE TITLE
Incorporate automatic backups

### ISSUE THREAD

**Issue by chuckackerman** [FalconChristmas/fpp#1148]
My SD card was fried today and I was saved because I had a current backup.  But others may not have current backups or even know that backups are possible.  I suggest making an automatic backup after changes are made.  The backups are essentially tiny and would be very helpful during crunch time when they are most needed. 

An added feature would be to delete older backups, say 90 days, to conserve space if needed.

**Comment by darylc** [comment]
@chuckackerman Where do you propose to store these automated backups?

**Comment by chuckackerman** [comment]
@darylc   I wouldn't presume to know the application.  But I would presume that if FPP was being accessed on a PC or Mac a pre-determined folder can be used to store backups.

**Comment by darylc** [comment]
@chuckackerman This is not possible.  FPP cannot save things to your PC without you clicking a backup link.

**Comment by chuckackerman** [comment]
Then might I suggest a backup button on every page or at least on the status page.

**Comment by MarkA75160** [comment]
how about leveraging the existing FPP "Backup to USB" function?   The capability is already there, it just needs an option to run automatically on some periodic basis

**Comment by chuckackerman** [comment]
I'd gladly add a thumb drive to use as backup.

**Comment by darylc** [comment]
perhaps we could add the fpp backup to the API then people could add it to a playlist & schedule it.

**Comment by darylc** [comment]
@jaredb7 Any thoughts?

**Comment by jaredb7** [comment]
> perhaps we could add the fpp backup to the API then people could add it to a playlist & schedule it.

Yep having a API that we can call to do the setting backup will be needed, instead of adding a entry into the playlist we could make a modification to WriteSettingToFile & DeleteSettingFromFile in common.php that will call that API endpoint each time a setting change is made.

This would get us most of the way having a a backup after each setting change.

Would also need some sort of interface to browse the backups & download them since the user doesn't get a chance to download those like they would if they manually did them

I'll investigate what was done on the file copy page in regards to saving to USB and incorporate that into the JSON Backup page or leverage that code as [MarkA75160](https://github.com/MarkA75160) mentioned

That should cover what we need I think.

**Comment by chuckackerman** [comment]
> > perhaps we could add the fpp backup to the API then people could add it to a playlist & schedule it.
> 
> Yep having a API that we can call to do the setting backup may be needed, instead of adding a entry into the playlist we could make a modification to WriteSettingToFile & DeleteSettingFromFile in common.php that will call that API endpoint each time a setting change is made.
> 
> This would get us most of the way having a a backup after each setting change.
> 
> Would also need some sort of interface to browse the backups & download them since the user doesn't get a chance to download those like they would if they manually did them. Optional but some users may want to do this perodically.
> 
> I'll investigate what was done on the file copy page in regards to saving to USB and incorporate that into the JSON Backup page or leverage that code as [MarkA75160](https://github.com/MarkA75160) mentioned
> 
> That should cover what we need I think.

What you describe is replication, not backup.  A backup is a snapshot in time to which you can revert should you screw something up.  Replication is an exact copy and doesn't permit this.  

Don't get me wrong, any kind of copy is better than none and I like your idea of replication to insure that there's a copy of the information should an SD card.  I can do a backup using my PC's backup software from that replication to create a point in time copy.

I think your solution is an elegant and possibly the simplest solution for the developers.

**Comment by jaredb7** [comment]
Just to clarify, you're just wanting automatic setting backups to take place as you're making changes to the system? Or that and also data like sequences/audio/video etc?

The automatic setting backup option is something I wanted to do one day as it's useful and also provides a bit of a audit trail as to what changed once it's been running for a while.

The current implementation (inspired by another system I use) makes a backup after the setting change is made, for e.g in the below screenshot... to undo my change to the the StaticOn script, I'd jump back to the backup before where playlist test2 has been changed and ScriptOn was backed up before my change.

Users can remove backups if they don't need them, download backups which they want to keep (and should be doing this regularly)

Restores are done by undo/restore button in the restore configuration section.

Open to comments/suggestion on whether how it functions (e.g backup after setting change) is expected and whether the below areas are enough. I did go through each page and change setting to see where I needed to hook into.

Areas Covered 
**Settings**
- Any Setting Changes
- Schedule Updated

**Playlist Changes**
- Playlist Created
- Playlist Updated
- Playlist Deleted
- Playlist Content Modified

**Input / Output Setup**
- Output Configuration Change (Channel Input / Output)
- Output Processors change
- Pixelnet DMX Configuration Change
- Config File Uploaded (Proxies, GPIO, Pixel Overlay changes)

**System Changes**
- Email Configuration Changed
- DNS Configuration changed
- Script Installed
- Script Modified

![image](https://user-images.githubusercontent.com/799998/212474014-be990ebf-2454-4078-bdb1-6db82f659a0c.png)
![image](https://user-images.githubusercontent.com/799998/212474034-563811db-a39e-4d71-b2c8-49cc99154ca0.png)

**Comment by chuckackerman** [comment]
Personally I don't consider it a valuable backup if it resides on the SD card. I only want to protect myself from SD card failure. That's what I'd like to automate.

**Comment by jaredb7** [comment]
Agreed, I've implemented most of that now for copying the JSON settings backup to a specified USB after setting changes (does a setting backup and clones them to USB).

The user does need specify the additional USB device to use as a backup to the backups via the FPP Backup page, The copy  leverage's dkulp's work with the File Copy section to copy the backups to the specified device - works well.

If the SD card becomes corrupt, reflash it, go through the first startup / initial setup, then you can go to the FPP Backups page, select the USB device the JSON Backups are on & restore the required settings backup. Push all the show data back from xlights/Vixen 3.
At least... that's the theory.

![image](https://user-images.githubusercontent.com/799998/212670249-c020bc97-5a57-4f7d-88de-c6f9f041a11b.png)

**Comment by jaredb7** [comment]
Submitted the PR for this, going to sit on it for a few days in case something comes up but it's all implemented. Also tested re-flashing & restoring (SD got corrupted lol, believe it's dodgy anyway) & restoring a backup from USB - Worked well

**Comment by darylc** [comment]
@jaredb7 I merged your code.  We're still missing a bit of glue though, its only possible to schedule FPP Commands  in playlists, not general API commands.  I'm not sure if you have any thoughts on this.

**Comment by jaredb7** [comment]
Do we need that if setting backups are being made when a setting is changed and sent to USB (if set)? 

I understand if it wasn't happening automatically, then you could schedule a settings backup as required to capture any changes but at the moment I feel a lot of those would end up being the same and you'd end up possibly huge list of backups that are essentially identical.

Apologies if I'm misunderstanding the purpose calling the API command from a schedule.

**Comment by darylc** [comment]
@jaredb7 thanks for the explanation, we should be good then.
