### ISSUE TITLE
FPP 5.3 Matrix Message log shows No name found when virtual matrix is configured for HDMI display

### ISSUE THREAD

**Issue by christaylor99** [FalconChristmas/fpp#1149]
Possible bug or large HDMI matrix causes display or plugin problem.  HDMI display blanks but does not display message.
2021-11-09 01:06:04 PM:  : [] /home/fpp/media/plugins/fpp-matrixtools/scripts/matrixtools EXISTS: Enabling
2021-11-09 03:48:04 PM:  : [1135] ==1135== Lock acquired, processing the job...
2021-11-09 03:48:04 PM:  : [1135] FPP version: v5.3
2021-11-09 03:48:04 PM:  : [1135] FPP version: 5.3
2021-11-09 03:48:04 PM:  : [1135] No Matrix name is  configured for output: exiting
2021-11-09 03:48:04 PM:  : [1135] ==1135== Releasing lock...
2021-11-09 03:57:43 PM:  : [] /home/fpp/media/plugins/fpp-matrixtools/scripts/matrixtools EXISTS: Enabling

[FPP_Logs_20211110.0004.zip](https://github.com/FalconChristmas/fpp/files/7508961/FPP_Logs_20211110.0004.zip)
<img width="712" alt="Screen Shot 2021-11-09 at 1 05 32 PM" src="https://user-images.githubusercontent.com/3443298/141029572-6c8c47d5-f22e-4477-8cc7-a50f35c5696a.png">
<img width="793" alt="Screen Shot 2021-11-09 at 3 48 43 PM" src="https://user-images.githubusercontent.com/3443298/141029577-a2620d90-0d2f-45f0-9b05-954dd04ea34c.png">
<img width="1233" alt="Screen Shot 2021-11-09 at 3 49 10 PM" src="https://user-images.githubusercontent.com/3443298/141029582-abf94c5d-f79f-48be-ad0a-2a5cd50ff117.png">
<img width="1235" alt="Screen Shot 2021-11-09 at 3 51 27 PM" src="https://user-images.githubusercontent.com/3443298/141029588-8f20302d-bd5b-458d-a57b-80eae51ae19e.png">
<img width="882" alt="Screen Shot 2021-11-09 at 3 51 50 PM" src="https://user-images.githubusercontent.com/3443298/141029590-c84d476c-e129-4776-93c9-0e07dd981737.png">
<img width="1010" alt="Screen Shot 2021-11-09 at 3 52 50 PM" src="https://user-images.githubusercontent.com/3443298/141029594-454bbc5d-c720-47f9-b700-8aa0b9bf1139.png">
<img width="1191" alt="Screen Shot 2021-11-09 at 3 53 20 PM" src="https://user-images.githubusercontent.com/3443298/141029595-802a315e-2e8d-4c7a-b409-85f4d6c01130.png">
<img width="560" alt="Screen Shot 2021-11-09 at 3 56 49 PM" src="https://user-images.githubusercontent.com/3443298/141029597-b3703701-ec92-4bf2-a3fe-db659220185a.png">
<img width="590" alt="Screen Shot 2021-11-09 at 3 57 30 PM" src="https://user-images.githubusercontent.com/3443298/141029598-4dea1c15-df2e-473c-a08a-05ab642905db.png">
<img width="432" alt="Screen Shot 2021-11-09 at 3 57 48 PM" src="https://user-images.githubusercontent.com/3443298/141029599-3b366a11-910f-40d2-9d12-fdd2086e8fa1.png">
<img width="1178" alt="Screen Shot 2021-11-09 at 3 58 28 PM" src="https://user-images.githubusercontent.com/3443298/141029602-8c90b0a3-007f-40c0-a665-c9f1cfa887ae.png">
<img width="629" alt="Screen Shot 2021-11-09 at 3 59 03 PM" src="https://user-images.githubusercontent.com/3443298/141029605-c587a7de-8340-45d2-832f-f231cdcf7fb7.png">
<img width="595" alt="Screen Shot 2021-11-09 at 3 59 48 PM" src="https://user-images.githubusercontent.com/3443298/141029608-293a76b2-ba1e-4225-afd7-33223e51ddae.png">
m.

**Comment by Poporacer** [comment]
I don't know if the scripts work in 5.0 there are FPP Commands for it now.

**Comment by darylc** [comment]
@Poporacer Shall we delete the plugin then?

**Comment by dkulp** [comment]
I'm pretty sure it works with FPP 6 as the twillio plugin uses it to push messages.   There are a bunch of plugins that don't work well with 5.x.   Please upgrade to 6.3 and re-test.

**Comment by Poporacer** [comment]
The Plugins were updated to use FPP Command and not the scripts. Plugin works in v5.x using the FPP Commands
