### ISSUE TITLE
Scheduled playlist no longer starts on boot

### ISSUE THREAD

**Issue by domisjustanumber** [FalconChristmas/fpp#1150]
It seems like this fix https://github.com/FalconChristmas/fpp/issues/11 got broken somewhere in v5.

To test:
FPP v5.3 on a Pi 3
Create a schedule that starts at 00:00 and ends at 24:00 every day.
Reboot FPPD

The playlist does not auto-start on boot - the status page says it is _**going**_ to start at 00:00.

On a fresh v4.6.1 install, the playlist auto-plays on boot.

**Comment by ghormann** [comment]
@domisjustanumber If you use 23:59 as the end time, does it work?

**Comment by Poporacer** [comment]
It is working for me as designed on both 5.3 and 5.3.1 using 0:00:00 as start time and 24:00:00 end time

**Comment by domisjustanumber** [comment]
Well I have no idea what was going on yesterday - I deleted and re-made the schedule and rebooted a bunch of times and it didn't work... but went back and tried again today and it works in both 5.3 and 5.3.1.

Thank you for trying it out and letting me know!
