### ISSUE TITLE
[Minor] UI Bug - Pi OLED

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1152]
PI-OLED title and 'Enable' checkbox on the LED Panels config screen.  Happens if  Pi OLED cape installed, which is possible with Colorlight LED panels since FPP uses ethernet to talk to the Colorlight

![image](https://user-images.githubusercontent.com/24968726/141205833-b6d76ed2-8a46-42b7-9163-fa756b644c1b.png)

**Comment by dkulp** [comment]
For both the Pixel string and LED Panel pages, the cape name should only be used if the "provides" includes string/panels.

**Comment by darylc** [comment]
It turns out that this only happens when the "Display all hardware options/settings" option is selected.
