### ISSUE TITLE
UI: playlist branch item edit form missing and extraneous fields

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1153]
FPP 5.3.1 on Pi 3

Observed on Edge browser

Playlist branch item edit:
Edit playlist branch entry (for existing playlist originally created in 4.x master)
No fields available to enter or edit time, or  offset or index values.  Listbox appears to select condition type, or index or offset type, but no place to enter the values.

![image](https://user-images.githubusercontent.com/5841728/141385736-6ef49fff-1995-4741-b72b-46843517abf3.png)

Using Chrome browser:
extraneous fields exist for given selection
![image](https://user-images.githubusercontent.com/5841728/141385911-1008d88e-e580-40a9-9b0d-06f0eea8e4c6.png)
![image](https://user-images.githubusercontent.com/5841728/141385958-7b856b35-b233-4aef-b936-6b34d3c6b7e2.png)

**Comment by darylc** [comment]
I cannot replicate this in 6.3/master on edge

**Comment by darylc** [comment]
@Jchuchla Is this still a problem in more recent versions?

**Comment by Jchuchla** [comment]
I think I saw this was resolved in 6.3 but I haven’t tested. Let me double check tonight and make sure it’s good.

—Jon Chuchla—

Sent from my iPhone

On Jan 24, 2023, at 4:23 AM, darylc ***@***.***> wrote:

﻿

@Jchuchla<https://github.com/Jchuchla> Is this still a problem in more recent versions?

**Comment by Jchuchla** [comment]
Yes it looks like this is fixed in 6.3.  At least for the branch playlist type.
