### ISSUE TITLE
test mode is enabling itself !!! - from time to time

### ISSUE THREAD

**Issue by KuhnDaniel** [FalconChristmas/fpp#1155]
FPP Version: | 5.3.1
-- | --
Platform: | BeagleBone Black (PocketBeagle)
FPP OS Build: | v5.3
OS Version: | Debian GNU/Linux 10 (buster)
Hardware Serial Number: | 1740GPB30348
Kernel Version: | 5.4.106fpp

enable test mode ON - from time to time

[FPP_Logs_20211113.1446.zip](https://github.com/FalconChristmas/fpp/files/7532259/FPP_Logs_20211113.1446.zip)

**Comment by ghormann** [comment]
Can you provide a little more background? Is this an enhancement request where you want to have test mode enabled via schedule?    Is this a bug report where you're saying test mode is enabling itself?

**Comment by KuhnDaniel** [comment]
precisely - test mode is enabling itself !!!
there is no pattern of activation - from time to time

**Comment by KuhnDaniel** [comment]
I have integrated the HA as the only plug-in. there is no sequence, scheduler, playlists active

**Comment by ghormann** [comment]
This is something I've never seen nor am I able to reproduce.   I quickly scanned the logs and don't see anything obvious.   The first thing I would try is disabling  fpp-ArtNetAdv plugin.    

Is it *possible* you have the fpptest window open on another computer / phone and it is periodically refreshing the paging and triggering it?/

**Comment by KuhnDaniel** [comment]
First of all, thank you for your support. I took a close look at everything and your idea that a client (tablet / mobile phone) could cause this situation is also a good indication. I can currently rule that out. I was wondering if there is a command to control test mode? So by command! I use MQTT to control from Home Assistant. I also monitored all communication and found no clues. I have been using the technology with BeagleBone Black (PocketBeagle) for 3 years and have never had anything like it. I currently have version 5.3.1 on all controllers. Lets see what happens. Best regards, Daniel

**Comment by KuhnDaniel** [comment]
![grafik](https://user-images.githubusercontent.com/36757260/141662580-1279419c-d156-40ac-bc70-9ee7c8aa20a1.png)

**Comment by ghormann** [comment]
I'd suggest going to Settings->Logging and setting the following to Debug level  "Command", "HTTP", "Control".     Once it occurs again, check fppd.log and it may give you a clue as  to the source. 

Once done, be sure to set back to info because these will cause very large log files.

**Comment by KuhnDaniel** [comment]
Hello Ghomann
Found a mistake:
I had set myself a LedFX Rspberry ns network. The setting E1.31 / Artnet Input activated on the FPP master to control the LEDs. Since I deactivated the setting on the FPP Master, there have been no uncontrolled activation of the test option for 4 days.
![grafik](https://user-images.githubusercontent.com/36757260/142678375-29ac83b6-4c3b-4712-9bc0-3e96bae08fe8.png)
