### ISSUE TITLE
trying to connect to a fpp that was used the year prior. 

### ISSUE THREAD

**Issue by rfjcn** [FalconChristmas/fpp#1156]
Im in a different location than where the fpp was used last and using a different router. do I need to reflash the microsd? or configure my router to a different subnet? I'm not sure at all, I'm using a raspberry pi 4b

**Comment by ghormann** [comment]
It depends on what changes were made to your networking settings.   If using DHCP, it *should* just get a new IP address from the new router.    If you don't want to reimage you can try using the usb tethering.

**Comment by cpinkham** [comment]
Closing ticket as tickets are not for general support questions.  Questions are better suited for the forums or FaceBook group.
