### ISSUE TITLE
FPP does not take into account the use of a single channel for a subject on pixels strings

### ISSUE THREAD

**Issue by thisim** [FalconChristmas/fpp#1158]
FPP 5.3 running on BBB

Hello, there is a problem with uploading output from xlights to fpp.
I have an rgb48F controller and I am using relays that use only one channel. 
FPP does not take into account the use of a single channel for a subject.
Last year with FPP version 4. I didn't have this problem.

[FPP_Logs_20190217.1640.zip](https://github.com/FalconChristmas/fpp/files/7534715/FPP_Logs_20190217.1640.zip)
![Capture d’écran 2021-11-14 221347](https://user-images.githubusercontent.com/31959517/141699405-ec07afa0-027a-4291-842b-d2a2d034f032.jpg)
![Capture d’écran 2021-11-14 221458](https://user-images.githubusercontent.com/31959517/141699406-5d627cc1-099c-4d43-ac45-a4ccaecb5d00.jpg)
![Capture d’écran 2021-11-14 221656](https://user-images.githubusercontent.com/31959517/141699407-3d2c4bbc-44b0-42a3-af28-1ae70ae03c32.jpg)
![Capture d’écran 2021-11-14 221758](https://user-images.githubusercontent.com/31959517/141699408-617e9389-c5ed-4879-a67d-33f6f29636c5.jpg)
![Capture d’écran 2021-11-14 221916](https://user-images.githubusercontent.com/31959517/141699411-0c773d10-bc51-40a6-b435-a5e452e206d7.jpg)

**Comment by darylc** [comment]
To me this looks like an upload from xlights problem.  I suggest reporting it to the xlights project.  I don't think the FPP UI would let you configure it like this.
