### ISSUE TITLE
ESEQ Triggered via Command Preset is Shorter in Duration

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1163]
**FPP Version and Hardware**: 
5.3.1 on BBB

**Describe the bug and Steps to reproduce**: 
Created a eseq and uploaded it to his bbb.
If we play it manually via Status Control > Effects it plays as expected
If we play it via manually triggering a command preset it works as expected
If we play it via the control channel the effect is always shortened.  We tried 30s, 60s, and several other duration effects.  The effect is a n on effect with 1s fade up to 255 and 1s fade off.
I don't recall the absolute control channel number but we did use preset slot id 1.
The effect was being triggered via a dmx effect on a 1 channel channel block with both output to lights and rendered in a fseq file.
We could reliably trigger this inside the sequence.  There aren't any other command presets defined so we were not commanding this off.

**Additional context**: 
I'm submitting this on behalf of a zoom user who I helped set this up so unfortunately this is all the detail I can provide.  If you cannot duplicate the issue then just go ahead and close it.

**Comment by cpinkham** [comment]
Shortened how much?  If he is using different frame rate sequences, that could cause an issue.  Effects played while a sequence is playing will run at the same frame rate as the main fseq sequence being played.  If you play a 25ms timing fseq file and start a 50ms eseq, the eseq will run twice as fast

**Comment by MrPaulAR** [comment]
That could be the issue.  The fseq I helped him with was 20fps but I don't
know the rate of the fseq that was playing ... probably 40fps.

I thought that FPP would honor the header of the eseq file but I just tried
to parse one with fsequtils and now I see that there doesn't seem to be
that info on the eseq file.

Thanks for the details.
