### ISSUE TITLE
Feature:  Force 2.4Ghz and/or 5Ghz for WLAN

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#1166]
**Is your feature request related to a problem? Please describe.**
I have multiple FPP's that are wireless.   I have both 5Ghz and 2.4Ghz wireless networks.  Some FPP's are close enough to run 5Ghz without any issue while others are just far enough that they connect 5Ghz but the connection is not very good.   A way to force a FPP client to use 2.4Ghz would be nice.   Yes, I can create multiple SSID's to do this, but cleaner with a single SSID.

**Describe the solution you'd like**
Add an option or options to force FPP to only use 2.4 GHZ and/or 5Ghz

**Describe alternatives you've considered**
Seperate SSID's

**Comment by darylc** [comment]
I had a look at this today.  I don't think we can do it with 6.x (debian buster which uses wpa_supplicant).  In theory you can add things like  freq_list=2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 to wpa_supplicant, in practice they don't work on raspi and googling around this is a common problem with no fix that I could find,

**Comment by chrkov** [comment]
OK.   Thanks for looking at it.   I found that upgrading all my AP's to WIFI 6 helped a lot with this issue.   Seems WIFI 6 handles it better.
