### ISSUE TITLE
FPP 5.4.1 Crashes

### ISSUE THREAD

**Issue by brennja** [FalconChristmas/fpp#1167]
FPP 5.4.1 running Pi 3B

Scheduler starts Sequence and keeps crashing after 10 mins or so.
Worked okay with 5.3, upgraded to 5.4.1 today.
After crash, can't start any sequences.
Have to Restart FPP.
Crashes again after few minutes.

[Control] /opt/fpp/src/mqtt.cpp:386: Error running mosquitto_publish: 4

[FPP_Logs_20211126.0317.zip](https://github.com/FalconChristmas/fpp/files/7606078/FPP_Logs_20211126.0317.zip)

**Comment by ghormann** [comment]
If you disable mqtt does the problem go away? 
If you uncheck the Active flag for the outputs that don't exists does it the problem go away? 
How does it "Crash"   per the logs, I don't see any calls to the crash handler.

**Comment by brennja** [comment]
Sequence stops. Play controls are all greyed out on Status Page.
It happened during testing again this morning.
I have rolled back to 5.3 and no problems on my Master.
My Remotes are still 5.4.1, I will see if they have problems tonight.

**Comment by darylc** [comment]
did you try the things suggested by Greg?  Eg disable mqtt etc.

**Comment by brennja** [comment]
Yes I disabled mqtt and active was already unchecked for unused controllers.
No problems since I rolled back, I will try again now that main season has finished.

**Comment by cpinkham** [comment]
Closing this as multiple crash-causing bugs were fixed during and after the holidays and early days of FPP v6 development.  If you can reproduce on the FPP v6 beta image or with a released FPP v6 version, we can reopen the ticket or create a new one with more details.
