### ISSUE TITLE
FPP OS UI triggered upgrade not working

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1168]
**FPP Version and Hardware**: 
FPP 5.4.1 running on PI 4*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to about page
2. Click on upgrade OS
3. File correctly downloads to PI but the OS version does not increase at the end of the update routine and rebooting the pi makes no difference
4. I have run the 5.4.1 OS upgrade but OS version stuck on 5.3

**Expected behavior**: 
OS version to increase after running OS upgrade and reboot

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20211126.0829.zip](https://github.com/FalconChristmas/fpp/files/7607328/FPP_Logs_20211126.0829.zip)

**Comment by ghormann** [comment]
Thanks for reporting. There were no OS changes between 5.3 and 5.4.1 just changed to fpp code.    Thus running 5.4 or 5.4.1 will report an OS of 5.3
