### ISSUE TITLE
Handle special characters in wireless configuration

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#117]
The wireless PSK and SSID need to be escaped when passing through to fppxml.php.  There are probably a lot of other places this makes sense as well, but that aren't as visible as a PSK using non-alpha, non-numeric characters.

**Comment by vult2000** [comment]
I confirm this issue still exists is 2.1

**Comment by jaredb7** [comment]
I've fixed this in the front end, characters like $ and & should work now. I tested with a key containing a & and $ and everything gets saved correctly

**Comment by cpinkham** [comment]
The only known character that can't be in the config now is the double quote since the setting value itself is stored in double quotes in the config file.  Closing ticket.
