### ISSUE TITLE
Remember filters on multisync page

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1172]
**Is your feature request related to a problem? Please describe.**
I have a ton of devices that show up in the multisync page.  But most of them are ESPixelSticks.  I'm constantly filtering the page to show just the FPP instances, or show them at the top.

**Describe the solution you'd like**
Remember last filters so that every time you enter the multisync page, it looks the way you last left it.

**Comment by Jchuchla** [comment]
Do you love easy fixes!

**Comment by cpinkham** [comment]
1-line or even 2-line (as in #1173) enhancement or fixes are always great.
