### ISSUE TITLE
FPP 5.4.1 VLC Audio Playback Error When Playlist Repeats

### ISSUE THREAD

**Issue by mmarkulik** [FalconChristmas/fpp#1174]
FPP 5.4.1 on RPi 3B+

Running a 14 sequence long playlist with all MP4 files as the audio source.  When the playlist starts the audio playback behaves as expected and the logs show no errors but when the playlist finishes and starts again on repeat the audio is no longer output and the following error occurs:

[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: MMAL error 2 "ENOSPC"

Restarting FPPD causes the audio playback to resume as normal but will have the same error when the playlist repeats after finishing the first time.  

Running the same playlist and same MP4 files does not have this issue in FPP 5.3.

All MP4 files are formatted the same as generated in Adobe Media Encoder. Format as follows:

{
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Carol Of The Bells 2021.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2021-11-27T17:09:07.000000Z
  Duration: 00:04:02.05, start: 0.000000, bitrate: 9990 kb/s
  Stream #0:0(eng): Video: h264 (High 10) (avc1 / 0x31637661), yuv420p10le(tv, bt709), 1920x1080, 9670 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2021-11-27T17:09:07.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2021-11-27T17:09:07.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
    "format": {
        "filename": "Carol Of The Bells 2021.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "242.048000",
        "size": "302282460",
        "bit_rate": "9990826",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "mp42mp41",
            "creation_time": "2021-11-27T17:09:07.000000Z"
        }
    }
}
[fppd.log](https://github.com/FalconChristmas/fpp/files/7613651/fppd.log)

**Comment by patdelaney** [comment]
Do you have any plugins or mqtt running?
Are you using on-board audio or USB sound blaster? 
Are you on a Pi or BBB?

I've been running 5.4.1 on Pi since the show went live on Thursday with no issues

**Comment by mmarkulik** [comment]
Only plugin that is installed is Remtoe Falcon but hasnt been used.  I am using the ALSA onboard audio.  Per original bug report running on RPi 3B+ with 5.4.1. I have reverted to 5.3 in order to run reliably. 

Are you running MP4 or just an audio container? 
What Audio codec are  you running? 
Are you running in a Player/Remote setup like I am? 

There could be a ton of configuration and/or media encoding differences between you and I, I dont think how long you have been running really has any bearing on the issue unless our configurations are identical.

**Comment by patdelaney** [comment]
I'm running MP3 for Christmas... you can zip the files up and attach here or send me a private message on FB and transfer them that way and I can try and reproduce the problem

**Comment by mmarkulik** [comment]
I did some quick testing this morning before rolling back to 5.3 and it didnt seem to matter how long the playlist was so in the link below you can download two of the sequences I use.  

Since they use 1080p video files for audio they are to large to upload to FB messenger or github directly.

https://drive.google.com/file/d/1Iv8hKh6CnwGwjKJ2nf0Y9PV8imt4MirF/view?usp=sharing

**Comment by patdelaney** [comment]
ty  I'll tyr it out

**Comment by patdelaney** [comment]
@mmarkulik are you around tonight?

**Comment by patdelaney** [comment]
Do you know that on the tail end of Carol of the Bells MP$ there is about 1:30 of nothing.... no audio and no video?  By any chance was this the last event in the play list and you didn't wait for it to finish playing nothing?  on v5.3.1-2-gca58ca90 (v5.3 branch) I'm playing a simple audio playlist, your 2 mp4 files and it loops, with no issues aside from the 1:30ish of nothing on the end of the file.  I'll upgrade to the latest greatest and see what happens

**Comment by patdelaney** [comment]
I'm not seeing any errors on v5.4.1 (v5.4 branch) either.  Again I'm only testing audio playback and it's working.

**Comment by mmarkulik** [comment]
I am aware that there is deadspace at the end of that MP4 file. and it is the final song in the playlist.  
Since the issue arises when playlist finishes and starts again on repeat it obviously isnt me not waiting for the final sequence to finish as the next song has already started. Also if the issue was me not waiting that wouldnt explain the VLOCOut errors in the log (is attached to the bug description):

[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: cannot recover playback stream: Input/output error
[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: MMAL error 2 "ENOSPC" 
[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: MMAL error reported by ctrl
[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: cannot estimate delay: Broken pipe

As stated I have no issues after reverting back to 5.3. 

Since you have not been able to repeat the issue yet we can actually look at the logs and disect the VLCOut errors (usually the best place to start in Root Cause Analysis) where we get a few but one notably of concern:

--[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: cannot recover playback stream: Input/output error

This error typically occurs when the ALSA (on-board audio PCM audio) cannot be accessed, maybe because it is busy or locked by another PID? I have not dug into how FPPD handles the playlist repeat option but if it just starts a new process when the current playlist is complete this could mean that FPPD hasnt completed the previous playlist and cleanly ended all tasks associated with it.  This of course is speculation as I have looked at the code.  

--[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: MMAL error 2 "ENOSPC"  
--[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: MMAL error reported by ctrl

These are typically an mmal decoding issue, possibly a configuratio issue with the VLC build? I could look at reencodig the videos in another codec.

--[MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: cannot estimate delay: Broken pipe

Likely caused by the above errors and vlc cannot estimate timing because teh ALSA driver isnt supplying latency information.

I can see if I can dig up another RPi and try testing again with the full playlist and do some root cause analysis this weekend.

**Comment by patdelaney** [comment]
Again my quick test was just an audio playlist with the 2 files you provided. I let it loop for 1/2 while I was working on other things and it ran fine. I would backup the config, pop out the disk and flash a new one with the latest release and try again. 
What debug settings are you using? 
Is your media on the pi SD card or thumb drive or "shared drive"?

Just trying to make sure my testing is the same

**Comment by jchotiner** [comment]
I am experiencing this on 5.5, and 6.1.1 on a pi zero w

**Comment by jchotiner** [comment]
I did a little more experimentation, and it seems as though VLC has a memory leak when looping/repeating a video.

I updated the gpu_mem setting to 128MB from 64MB  on a pi zero w and was able to get it to loop longer before crashing.
Updating to 256MB allowed for even more loops.  I monitored memory usage using: while looping and you could see memory slowly get used up.  Even with a short 3 second 1080p video it would leak memory and crash

`vcgencmd get_mem malloc; vcgencmd get_mem reloc; vcgencmd get_mem reloc_total; vcgencmd get_mem malloc_total; vcgencmd get_mem gpu`


Steps to reproduce
On a raspberry Pi Zero W  with gpu_mem set to 64MB, create a playlist with a single video (3 sec mp4) set to repeat and play.  Let run (for a while), it will eventually crash VLC with MMAL error

Workarounds
I thought that if I made a playlist of playlists it may force a "restart" of some kind for VLC,  I didn't seem to help, until I inserted a pause for 1 sec in the child playlist.  But so far so good.

Another possible workaround I have not yet tested would be one longer video file that loops less often.
