### ISSUE TITLE
Wifi signal strength reported as positive number

### ISSUE THREAD

**Issue by sslupsky** [FalconChristmas/fpp#1176]
# Please answer the following:
FPP 5.4 running on BBB

**Describe the bug and Steps to reproduce**: 
WiFi signal strength is reported as positive numbers.  See screenshots below.

**Expected behavior**: 
The WiFi signal strength should be reported as a negative number.

![Screen Shot 2021-11-28 at 11 18 23 AM](https://user-images.githubusercontent.com/16888734/143780901-e15780f9-9948-4703-abc8-aa19cc23ad6d.png)

![Screen Shot 2021-11-28 at 11 18 37 AM](https://user-images.githubusercontent.com/16888734/143780903-8242c149-fd2a-4776-8a52-e6bdf732e3f4.png)

![Screen Shot 2021-11-28 at 11 23 17 AM](https://user-images.githubusercontent.com/16888734/143782110-44bb4d9c-7c1b-4ffc-995f-5e6bc827ea13.png)

**Comment by nmiller0113** [comment]
I'm running a fresh install of 5.4.1 on a Pi and I'm seeing it reporting properly. I wondering if it's just on the BBB platform.

**Comment by sslupsky** [comment]
@nmiller0113 That could be ... I don't currently have a PI running FPP to do a comparison.  I did install a different WiFi adapter and the result is the same.  Though, both WiFi adapters I have tried use the Realtek 8812 chipset so I expect the same driver is used.

**Comment by dkulp** [comment]
I believe the code needs to be updated to not report as dBm if that's now how the driver is reporting it.   The 88x2bu doesn't seem to report it that way instead it uses a "Signal Level" of up to 100:
```
wlan0     IEEE 802.11AC  ESSID:"KULPYARD"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:5.18 GHz  Access Point: 26:5A:4C:1B:78:55
          Bit Rate:867 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=87/100  Signal level=36/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
The proc interface also reports it that way:
```
fpp@FPPGarden:~$ cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
 wlan0: 0000   78.   37.    0.       0      0      0      0      0        0
```

**Comment by MarkA75160** [comment]
FPP is simply displaying whatever numeric value the linux driver is reporting for signal strength.  Some drivers report it as a negative number and other drivers report it as a positive number.    I believe the ones that report negative numbers are using the dBm scale and the ones that report positive numbers are using a 1-100 scale.  So I don't think we should simply display all values as negative.  Like Dan said, it probably should not display the "dBm" label if the driver is not using the dBm scale

**Comment by dkulp** [comment]
Fixed by https://github.com/FalconChristmas/fpp/commit/28c9be787aeb471eaf26d68f0faade668fe2eb98
