### ISSUE TITLE
FPP Crash - Wifi

### ISSUE THREAD

**Issue by PhatAdam** [FalconChristmas/fpp#1177]
Symptoms appear when 3 or more controllers are connected to the network in master/remote configuration. 

When the controller crashes, everything is going offline, the OLED screen shuts off, and all 4 user LEDs are off.  (power led is still on.)

I have the physically disconnect the power, and press the power button to restore functionality to that specific controller.  However, as soon as that controller comes online, another drops off.  random as to which. (right now only the master has never turned off.)

this activity is pretty universal - k32,k16, and k8 - all doing it - even between 12v, and 5v.

I am uploading the syslog logs etc, i am happy to upload anything else.

[logs.zip](https://github.com/FalconChristmas/fpp/files/7614278/logs.zip)

**Comment by PhatAdam** [comment]
I have now tried 4.6 - same symptoms

**Comment by PhatAdam** [comment]
Starting to investigate network.  Unifi dream machines pro Unifi 6 AP's LR

**Comment by PhatAdam** [comment]
I have tried to run the controllers as standalone - the network/controller still locks up.

**Comment by PhatAdam** [comment]
issue has now disappeared once i removed the equip usb wifi adapters - ethernet doesn't have the issue

**Comment by PhatAdam** [comment]
could be an issue with unifi 6 access points I suppose. (UniFi with Dream Machine Pro, and Pro PoE 24 Switch.)

**Comment by ghormann** [comment]
You may get a faster response  in the forms, Facebook, or zoom room for this very weird issue. 

> When the controller crashes, everything is going offline, the OLED screen shuts off, and all 4 user LEDs are off. (power led is still on.).   

This sounds like a hard OS crash.   How are you powering the BBB? Though the Kulp board or externally?  Removing the network card would reduce the power draw on the BBB....

**Comment by PhatAdam** [comment]
Bb through the Kulp.

**Comment by MrPaulAR** [comment]
I did spend some time with Adam on both discord and zoom.  There was nothing in the fppd logs beyond a start (no crash or any other indicator of fppd stopping).  There was some very minor info in /var/log/syslog for some of the stops but nothing that was enough to give any indicator of the problem itself (you don't know me but I'm a >20year linux admin).

**Comment by ghormann** [comment]
Was the OS crashing or just fpp?  The way it sounds with the lights I would
think the OS would crash too..

Greg

**Comment by MrPaulAR** [comment]
I believe it was the OS crashing and not FPPd.  Since the BBB weren't
reimaged I bet he can scp some of the logs off the sd card if you are
interested in looking at them.

**Comment by PhatAdam** [comment]
Literally, nothing on the controller works, the BBB is not accessible
either.  Not even the power on/off/test/menu nothing - the oled display is
literally off.  the only thing that works is to disconnect power and plug
back in.  (which then causes another controller to go offline.)

**Comment by jackal2477** [comment]
I was also having the same issue. Also running Unifi gear. Reverting to 5.3 solved the issue.

**Comment by darylc** [comment]
not much to go on here.  @jackal2477 @PhatAdam do either of you still have this problem?  Can you upload full logs (both /var/log/* and /home/fpp/media/logs/*)

**Comment by jackal2477** [comment]
I am no longer having the problem. I believe it may have been the fact that I had multiple wifi access points transmitting the same ssid and it was trying to jump from one to another. Once I put each access point on its own ssid, the problem stopped

**Comment by darylc** [comment]
There is nothing directly actionable here and FPP has changed a lot since 4.6 to 6.x so probably time we closed this.  If there are ongoing problems with wifi on FPP lets open a new ticket and hook up a keyboard/monitor while it's in the state and grab debugging info so we can see whats actually happening to help us fix it.
