### ISSUE TITLE
Can no longer use hostname when defining UDP outputs. 

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1179]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
every FPP version since 5.x-master-549-g5a124725 including 5.4.1
Raspberry PI 3b+
Kulp K8-B

**Describe the bug and Steps to reproduce**: 
Goto the e1.31/ddp channel output tab. Add a output, set to e1.31 unicast or DDP.  Set a hostname for the IP address.  Click Save.  Error message "Validation Failed" with a title of "Save E1.31 Universes" appears. 

**Expected behavior**: 
It would be expected that the output would save, then restart fppd and then be to send data. 

**Additional context**: 
I have been using hostnames for my controllers for years.  If I configure via xlights and use fpp connect and set upd out to all, it will configure the outputs with hostnames with no issue.  However if I try to manually add an output, or change an output, they all get highlighted in red and the error message for validation failed occurs. This behavior started with the version listed above which is titled "Fix the ipaddress validator code".  If I roll back to the build just before, everything works as expected. 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

If applicable, add screenshots to help explain your problem
[FPP_Logs_20211201.0916hostnames.zip](https://github.com/FalconChristmas/fpp/files/7632497/FPP_Logs_20211201.0916hostnames.zip)
.

**Comment by bloojoop** [comment]
@ghormann , Looks like I can no longer use hostnames since the validation cleanup last month.  I have not had to change any outputs for a bit but needed to the other day and found this out :(.  If I push from xlights via fpp connect, I can use hostnames but not if I try via the web ui.

**Comment by darylc** [comment]
Personally I think we are better off forcing validation to ensure IP addresses are entered correctly than allowing hostnames.

**Comment by bloojoop** [comment]
Any reason we shouldn’t be able to do both?  Many many other systems do. If text, validate legal host name, if starts with numeric, validate legal ip.

**Comment by dkulp** [comment]
Use of hostnames needs to be fixed.   I have no idea what the IP address of anything is on my network.  Use DHCP + hostnames for everything.
