### ISSUE TITLE
DNS and DHCP Server Support (Feature Request)

### ISSUE THREAD

**Issue by damon-atkins** [FalconChristmas/fpp#118]
Feature Request add DNS Masq Support.
This lets one program (dnsmasq) be the DNS and DHCP Server then people do not need to use Static IP address, devices will appear in DNS, you do not need a ADSL router to be a DHCP Server.

Suggestion for Version 1 interface allow you to enter
Domain:   e.g. myshow.lan
The network configuration must be the current network eth0 is on. 
It assume the DHCP Range when enable is eth0 + 3 IP to the end of the IP Address Range.
(be later when its working add more configuration options)

Have a report page which lists the leases and names given by the DHCP Clients.

Software to use:
dnsmasq : A lightweight DHCP/caching DNS server
dnsmasq-utils : Utilities for manipulating DHCP server leases

**Comment by jcochran** [comment]
My network patch once pulled in will add support for dnsmasq with a configurable dynamic range for any available network interfaces.

**Comment by damon-atkins** [comment]
Did this happen in the end

**Comment by cpinkham** [comment]
Not yet.

Chris

**Comment by cybercop23** [comment]
@darylc how can we push this up the list to get this implemented?
The Zoom room spends lots of time helping people configure Falcons/proxy that can easily be handled by this request. 
I have provided full setup steps in #1068  Hoping we can push this through and make it happen.

**Comment by darylc** [comment]
@cybercop23 There isn't any such list.  Generally volunteers work on the features they feel would be interesting to implement or they need for their show.  I don't disagree for the need for it, the challenge is finding a volunteer to write the code and send a pull request especially at this time of year.  I'm not in a position personally to spend anymore time on FPP until next year as I'm busy getting my show finished.

**Comment by cybercop23** [comment]
Understood. I've been looking to see if I can do something in FPP or create a plug-in that would do that.

**Comment by cpinkham** [comment]
FPP v6 should satisfy this reqeust based on current code in the master branch.
