### ISSUE TITLE
FPP continuously asking the default gateway (router) for NTP information.

### ISSUE THREAD

**Issue by cbuxton5200** [FalconChristmas/fpp#1185]
[ntperrors.csv](https://github.com/FalconChristmas/fpp/files/7655066/ntperrors.csv)
[FPP_Logs_20211205.0201.zip](https://github.com/FalconChristmas/fpp/files/7655067/FPP_Logs_20211205.0201.zip)

# Please answer the following:
**FPP Version and Hardware**: FPP 5.4.1 running on Raspberry Pi 4

**Describe the bug and Steps to reproduce**: 
I have segmented my network to restrict traffic to and from my show network.  In the process of logging and watching traffic I noticed the FPP device (192.168.2.100 in my case) querying the default gateway (192.168.2.1) for NTP almost constantly.  Thereby filling up logs and also generating an unneeded stream of traffic from a device where every CPU cycle is critical.  I had not set any NTP server in the FPP settings page, so I assume that the query was a default thing.  I went ahead and set pool.ntp as my server address and ensured it was allowed in my firewall and rebooted.  After reboot, the constant NTP queries continued.

**Expected behavior**: 
I would expect that once NTP servers are set in the FPP settings, that it would no longer ask the router for NTP time.

**Comment by nmiller0113** [comment]
It does have default NTP servers, but they aren’t your router. I believe they are the default Debian ones…I’m not in front of my FPP at the moment, but if you highlight the icon to the right of the setting it tells you.

Are you sure that’s not the DNS query hitting your router? That would be more likely.
