### ISSUE TITLE
MQTT playlist/name reporting incorrect playlist

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1186]
FPP 5.4.1 on a Pi 3
Remote Falcon Plugin

**Describe the bug and Steps to reproduce**: 
Remote Falcon switches playlist to "Remote Falcon" playlist to play songs in queue.
Queue completes and RF switches back to scheduled playlist.
MQTT playlist/name topic still shows "Remote Falcon"  (should show "Christmas 2021")

**Expected behavior**: 
Playlist topic should always (and immediately) show currently playlist.

Initially observed via my home automation system (homeseer with mqtt plugin)
Verified incorrect topic state with MQTT Explorer utility.

[FPP_Logs_20211206.0053.zip](https://github.com/FalconChristmas/fpp/files/7657189/FPP_Logs_20211206.0053.zip)

**Comment by ghormann** [comment]
I'm no longer able to reproduce this in 6.0-current.   
1) Setup Idle30 in the schedule
2) Ran "Insert Immediate" which changed to idle5
3) Once Idle5 finished, MQTT started showing Idle30 again

![image](https://user-images.githubusercontent.com/24968726/155859628-8c0fa0f9-195c-42a9-adb1-28e3a06afb75.png)
