### ISSUE TITLE
Start on a Second for a playlist

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [FalconChristmas/fpp#1187]
**Is your feature request related to a problem? Please describe.**
Right now I can only start a playlist at a specific minute and not down to the second

**Describe the solution you'd like**
I have New Years Eve Sequence, that starts with a 10 Second Countdown, I would like to start this at 11:59:50 PM so that when the 10 seconds is done it is midnight and says "Happy New Year"

**Describe alternatives you've considered**
I could make the Sequence a lot longer and just have a lot of blank space but I feel that is somewhat un-needed.

**Comment by dkulp** [comment]
This is already implemented.   In the settings, go to the UI tab and turn on Advanced settings.  Then go to the system tab and there is a setting to turn on the Granular Scheduling.
