### ISSUE TITLE
Status Page Slow to load (20+ seconds sometimes)

### ISSUE THREAD

**Issue by lakerimff** [FalconChristmas/fpp#1188]
When accessing my FPP from iOS Safari or Google Chrome on PC the site is greyed out (Disabled mostly) and takes sometimes up to 20 or more seconds to fully load. This is on 5.4.1 but i've noticed this since the begging of halloween.

**Comment by nmiller0113** [comment]
Does this happen all the time, or only while your show is playing?

**Comment by ghormann** [comment]
Is this a BBB or PI?   if you swap out the SD card with a new new one does the problem go away?   I've seen this when a SD card is going bad...

**Comment by nmiller0113** [comment]
> > Does this happen all the time, or only while your show is playing?
> 
> Everytime the show is running regardless of browser/device.

Sounds like you're streaming E1.31 over multicast and trying to manage the device over the same network/broadcast domain. Could you please elaborate on your setup...most specifically your network design? Thanks!

**Comment by lakerimff** [comment]
My show runs on a 192.168.50.xxx subnet; home runs on 192.168.1.xxx subnet, router has static routes with VLANs to allow access between them

**Comment by nmiller0113** [comment]
@lakerimff are you running multicast or unicast? Sounds like it's multicast and it's hitting both interfaces. It would be good to have a better understanding of your network topology and all parts involved.

**Comment by nmiller0113** [comment]
@lakerimff, to add some more detail, you're stating VLAN's to allow access between them...which doesn't make sense. You don't need VLAN's to provide paths between the two networks in your router, routing would suffice. VLAN's would only be required for logical separation. I'm concerned you may have created a logical bridge somewhere with the VLAN configuration, and this is causing your issue. This is why I wanted to know both the physical and logical topology with a bit more clarity. Thanks!

**Comment by lakerimff** [comment]
The phone accessing the show is on the same subnet as the pi's wireless. Show runs in unicast

**Comment by darylc** [comment]
did you try swapping out your SD card (yes I saw you said it was new, but that doesn't mean it's not faulty)

**Comment by ghormann** [comment]
@lakerimff Did you try swapping out the SD card?  The devs have been unable to reproduce this on known working hardware.  It has been observed with either poor quality or faulty SD cards only.

**Comment by ghormann** [comment]
Closing. Unable to reproduce and no response from OP
