### ISSUE TITLE
When Renaming Audio Files With Special Characters Correct the FSEQ Headers Too

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1190]
**Is your feature request related to a problem? Please describe.**
This may be a xLights issue but I think FPP is doing the cleanup since FPP (not linux) struggles with some special characters.  With that out of the way...

When FPP renames the MP3 file during the POST (or WebUI upload) it would be good to attempt to correlate that with other uploads so that the FSEQ file header can also be updated to point to the right MP3.  This shouldn't require reading/writing the entire FSEQ file to the sdcard.

Some ways that may work are as follows.
- Since the MP3 is uploaded first maybe there is a way to look at the next FSEQ file uploaded.
- After each FSEQ is uploaded check the 'mf' header for a filename that would match invalid characters.  Regardless of if a media file is uploaded apply the same logic that would be used for the mv command that renames the file.

**Describe alternatives you've considered**
- Manually linking FSEQ & Audio on the schedules
- Fixing it in xlights so that the special characters aren't used and the sequence uses the right audio.

**Comment by ghormann** [comment]
@MrPaulAR 
With cfbe8479b984cc8aa433f457e443d724118f0e53 sanitizeMediaName() was added.   When attempting to play a sequence it preformance the same special character checks as was preformed during upload.  Thus, there is no need to rewrite the FSEQ header.

Is there a test case you can provide where the existing functionality doesn't work?

**Comment by MrPaulAR** [comment]
I'll duplicate the specific case tomorrow but what I recall was the follwing order of operations.

Create a new playlist
Add a sequence with a matching audio file in the headers (one that didn't have the audo renamed)
Add another sequence but one that had renamed audio file and the UI didn't choose the new audio

**Comment by MrPaulAR** [comment]
Below are the steps used to duplicate the issue.

Created these new sequences with dummy effects.

1. commas in both the sequence name and mp3 name.
2. comma only in fseq name
3. comma only in mp3 name
4. no commaas

![image](https://user-images.githubusercontent.com/3765696/145436521-4cc0d7cf-c5a6-445f-afaa-c7998c00b170.png)

Added first song without any special characters.
![image](https://user-images.githubusercontent.com/3765696/145436818-edf0d07c-31e0-47b9-b999-c5156823a88a.png)

Added 2nd song with properly named FSEQ but commas in audio
![image](https://user-images.githubusercontent.com/3765696/145436962-413de285-5ee7-4f0c-9c7a-96089fd4afb4.png)

Added with commas in FSEQ only.
![image](https://user-images.githubusercontent.com/3765696/145437074-07d48152-8dc5-4f8c-a8df-53214215d3b0.png)

Added with comma in both FSEQ and audio
![image](https://user-images.githubusercontent.com/3765696/145437179-cfdfc178-a3c6-4561-8ad9-36ee2f14b3a3.png)

This is working now.  Whatever the issue I previously had seems to be good and it could have been a different character.  Not sure I'll personally run into this again as I'm more diligent about naming but if so I'll open a ticket with specific examples.
