### ISSUE TITLE
Raspberry pi4b - error could not open audio device -ALSA invalid argument

### ISSUE THREAD

**Issue by ve3sjk** [FalconChristmas/fpp#1191]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 

FPP 5.x running on Raspberry Pi 4B

Note: FPP was installed on existing system with the install script contained in the GitHub files

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to 'State'
2. Click on 'fseq in the list'
3. Scroll down to 'hit play'
4. See error ***Could not open audio device - ALSA: Couldn't open audio device: Invalid argument

**Expected behavior**: 
play sequence with mp3 file
[FPP_Logs_20211209.0019.zip](https://github.com/FalconChristmas/fpp/files/7681290/FPP_Logs_20211209.0019.zip)

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by patdelaney** [comment]
I'm unclear as to what this means:  Note: **FPP was installed on existing system with the install script contained in the GitHub files**

Did you mean you added it to a pi that had a stock version as Raspian or Debian and then ran then download the install script from github?

**Comment by ve3sjk** [comment]
Yes i did the following from a sub directory within my home directory.

wget -O ./FPP_Install.sh https://raw.githubusercontent.com/FalconChristmas/fpp/master/SD/FPP_Install.sh
chmod 700 ./FPP_Install.sh
su
./FPP_Install.sh


The system works, i can log into FPP and send outputs to my E682 controller it just fails to play audio files on the pi4b output to the headphone jack, this pi has a headless version of ubuntu server on it.

daqsrv9:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal



@daqsrv9:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 3/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3


root@daqsrv9:~# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
dmixer
pcmdev
default
sysdefault:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
dmix:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample mixing device
dsnoop:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample snooping device
hw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct hardware device without any conversions
plughw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Hardware device with all software conversions
usbstream:CARD=b1
    bcm2835 HDMI 1
    USB Stream Output
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output

**Comment by ve3sjk** [comment]
I don't think the problem is with FPP i get the same issue with any sound settings. Looks like a raspberry Pi4b issue with ubuntu 20 and no audio, can't find a fix for it so far , i am wondering if anyone else has run in to this issue on the same hardware. Might have to try a usb external sound card to feed the fm transmitter i just purchased.

**Comment by darylc** [comment]
@ve3sjk FPP is intended to be run as an appliance.  Please use the FPP images rather than trying to install on top of Ubuntu.

**Comment by ve3sjk** [comment]
Don't have the luxury of dedicating the pi to FPP the pi is doing other things already that need to be done. I thought what i did was install a development system as per the description in the install file. I will fork it so i can continue to work on the audio issues with the Pi4b otherwise, FPP itself is working perfectly under this install method, its scheduling and displaying my playlists as expected feeding a San devices E682 controller. The audio issues are a Raspberry Pi issue completely i am sure when i resolve that FPP will be happy to send my audio as well.
