### ISSUE TITLE
Volume control not working? CD002 

### ISSUE THREAD

**Issue by cathelest** [FalconChristmas/fpp#1195]
May not be a bug, but should the volume slider work on one of the cheap fm transmitter boards from ebay connected via usb?

FPP5.4.1 OS5.3 GIT a4ea8d3
 Pi3b
USB fm transmitter ebay cheap little board,
Shows as CD002 in audio settings

**Describe the bug and Steps to reproduce**: 
I have a pi3b in master player with a pixel hat running 2 outputs of pixels,

I am using a cd002 fm transmitter, one of the cheap ebay ones, connected via usb,
Volume doesnt seem to change volume at all

**Expected behavior**: 
Volume changing.

**Comment by cpinkham** [comment]
Did you select the necessary "Audio Output Mixer Device" on the Audio/Video tab of the FPP Settings page?

**Comment by cathelest** [comment]
Only has PCM as an option.

![fppaudio](https://user-images.githubusercontent.com/52036639/145974087-d2415f09-ace2-4e05-80d5-ee898948971c.png)
,

**Comment by darylc** [comment]
None of us have a CD002 so not sure we can help here.
