### ISSUE TITLE
Overscan Settings for Projectors

### ISSUE THREAD

**Issue by datcomputerguy** [FalconChristmas/fpp#1199]
**Is your feature request related to a problem? Please describe.**
When doing  virtual matrix display I have found it very useful to use the /boot/config.txt file on my RPis to edit the overscan settings to get my images lined just right when dealing with fixed focal length projectors.
When doing an FPP OS Upgrade these settings are lost, so first it would be nice to save the HDMI and overscan settings as part of a backup and as part of an FPP OS upgrade.

**Describe the solution you'd like**
1. As part of the backup process or at minimum part of the FPP OS upgrade process: Save the config.txt overscan and other hdmi settings and apply them after the changes have been completed.  Currently they are wiped each time you do an FPP OS upgrade (via web browser, About > Upgrade OS: > Upgrade OS Button)
2. Additional settings on the Status/Control > FPP Settings > System near the HDMI settings: That would include the overscan parameters for Top, Bottom, Left, and Right.

**Describe alternatives you've considered**
Currently I have a script that I have put on each of my projector RPis that can pull and put those values into the config.txt file.  Saves the values in the home folder for FPP since those are not wiped during an Upgrade OS action.

**Additional context**
No additional context.  It would be nice to have this as part of the OS Upgrade process.  But if you are going to do that, you might as well make the options editable as well.  I am still learning the FPP system, eventually I hope to be able to help code these solutions.  Let me know if I can help at all on this feature request!

**Comment by darylc** [comment]
whilst I'm not sure it's mainstream enough to add this specific feature to the UI, it would be nice to to have some generic features in FPP.  This would assist people who are doing non standard stuff avoid the need to redo it after every upgrade:
append, replace or remove lines in /boot/config.txt
install additional packages beyond those that fpp base install has
run a script at bootup

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this as a feature in the UI.
