### ISSUE TITLE
Error changing modes in iPhone Safari

### ISSUE THREAD

**Issue by NWF-Geek** [FalconChristmas/fpp#1201]
**FPP Version and Hardware**: 
*FPP 5.3.1 running on RPi* (HOWEVER, fairly sure this problem is not hardware-specific)

Have detected a bug on FPP when trying to change FPP mode when using Apple Safari on an iPhone.

Specific steps to repeat:
1. Access FPP instance on an iPhone, using Safari, holding the device in PORTRAIT mode
2. Go to 'Status Control' then 'Status Page'
3. At the bottom, click 'FPP Mode:' and select a different mode than the current one.
4. FPP does not respond to the change request.
5. Hold the phone so the browser changes to LANDSCAPE mode
6. Repeat steps 2 & 3.  FPP changes mode correctly.

**Expected behavior**: 
Well, I expect the mode to change as requested, without regard to whether I'm looking at the browser in Portrait mode or Landscape mode.

**Additional context**: 
The mode change works fine on a PC browser, and on the Safari browser when in Landscape mode.  The only problem I have had was when my phone was in Portrait mode.

**Additional Attachments**
N/A

**Comment by cpinkham** [comment]
This has something to do with the Player/Remote popup overlapping the FPP Command button.  If you click the left side of the items in the popup, it works, but if you click the middle (overtop the FPP Command button), the popup disappears and the change is canceled.  When in landscape mode, the FPP Command and Mode buttons are side by side so there is no overlap of the popup with another button.  Hopefully one of the guys more familiar with UI code will know what is causing this issue.

**Comment by adamcoulombe** [comment]
This was a interaction conflict with the tooltips, since touch devices try and open a tooltip on the first tap. Solution is to not initialize tooltips on dropdown items for touch devices. a08a138
