### ISSUE TITLE
Add button to start the next scheduled playlist now as a scheduled playlist.

### ISSUE THREAD

**Issue by MikeSoukup** [FalconChristmas/fpp#1205]
**FPP Version and Hardware**: 
FPP 5.3 on RPi

**Describe the bug and Steps to reproduce**: 
I'm not sure if it's a bug or a request or a question.

A mini bus showed up today 10 minutes before my show started so I manually started the playlist from the main screen.  At 5pm (normal show start time) the current song stopped and my show started over from the beginning.  I would prefer that it finished running the manually started playlist until it completed, then continued with the schedule.  It should be treated as the highest priority item, but it seems like it's the lowest.  Is there a way to do this?

**Expected behavior**: 
Expected manually started playlist to run to completion.  I think this was the behavior in 4.x.

**Comment by cpinkham** [comment]
This would have to be a setting, the scheduler has always had priority and stopped a manually started playlist to play a scheduled one.  One option we might explore would be to just add a way to start a scheduled playlist early.

**Comment by cpinkham** [comment]
Adding this to the FPP v6.0 list.  I think we can add a "Start the next scheduled playlist now" button on the main status page and it will fix this use case and let people start scheduled playlists early just like we can end them early or late.
