### ISSUE TITLE
Start Playlist Command with Repeat option crashes FPP when used as a Run Command item in a playlist

### ISSUE THREAD

**Issue by adamcoulombe** [FalconChristmas/fpp#1209]
FPP on 5.4.1 Raspberry Pi 3b+ (Also observed on 5.3)

**Steps to reproduce**: 

1. Create 2 Playlists.
2. The first playlist can have any sequence (although not necessary), and also a **Run Command > Start Playlist** (this should start the second playlist). Make sure "**Repeat**" Checkbox is enabled for this command .
3. The second playlist can have any sequence.
4. Start the first playlist and let it play through until it starts the second playlist.
5. When the second playlist plays, it crashes FPP. (Sometimes this will take a moment, or maybe not until the second playlist tries to repeat? )

**Expected behavior**: 

The second playlist should play on repeat without crashing the system

FPPD Log attached showing error trace that occurs when it crashes
[fppd.log](https://github.com/FalconChristmas/fpp/files/7729409/fppd.log)

**Comment by burnt-past** [comment]
This seems to still be happening on 6.2
