### ISSUE TITLE
BBB: NTP settings don't appear to stick when you leave the time settings page.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#121]
I am trying to configure NTP and I click enable and save, but the settings don't stick. This happens on Both my BBB.  Although one of them has the correct time.

**Comment by cpinkham** [comment]
I believe this is working now, ntpd wasn't installed as part of FPP_Install.sh previously and now it is.  I can enable/disable NTP through the UI on my BBB systems and it starts and stops ntpd properly.
