### ISSUE TITLE
Known issue with Pi4? Can't upgrade OS, complains/reboots

### ISSUE THREAD

**Issue by tmblue** [FalconChristmas/fpp#1212]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.4.1 Running on PI4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to  about.php
2. Click on Upgrade OS
3. Scroll down to PI-5.4.1.fppos
4. See error;   FPP OS Upgrade
Image: Pi-5.4.1.fppos
==========================================================================
Upgrading OS:
Checking for previous /home/fpp/media/tmp/upgradeOS-part1.sh
**Image of '' does no match 'Raspberry Pi'**
==========================================================================
Rebooting.....Close this window and refresh the screen. It might take a minute or so for FPP to reboot

**Expected behavior**: 
I believe it should be downloading the latest PI Kernel image and then doing the upgrade. If you look at the error Image of "" is missing

**Additional context**: 
Just a note that it's on a newer model PI 4

**Additional Attachments**

Don't see a UI log and looking at the fppd and the fppd update logs, I see nothing relating to this issue. not capturing it? Also seems to reboot after this failure.

![Screen Shot 2021-12-18 at 2 15 15 PM](https://user-images.githubusercontent.com/16458601/146656914-b6081f94-6d9f-41b0-8579-cb194ff6a6f6.png)
![Screen Shot 2021-12-18 at 2 14 59 PM](https://user-images.githubusercontent.com/16458601/146656917-714e91db-e68b-420c-aa7d-7c4f1f4160b7.png)

**Comment by tmblue** [comment]
OH, so 5.2 works, can you not jump straight from 5.0 to 5.4?? i tried 5.3 I thought and got the same error. Maybe, this just needs the OS walked up to the current version?

**Comment by tmblue** [comment]
oops that was a mistake, it downgraded to 5.2, I guess I was being an idiot, thinking that would update the kernel version, soooooo nope!!: ) hahahaha

**Comment by dkulp** [comment]
Sounds like the fppos file got corrupt on download and is thus not matching correctly.  Go to the File manager, uploads tab, and delete all the fppos files that are there and try again.

**Comment by tmblue** [comment]
Yep they had a byte count of 0.... so def caused the issue, thanks Daniel!!
