### ISSUE TITLE
Audio and FPP locking up

### ISSUE THREAD

**Issue by MHempell** [FalconChristmas/fpp#1216]
**FPP Version and Hardware**: 
FPP Version: | 5.4.1
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v5.3
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 10000000ab52b487
Kernel Version: | 5.10.63-v7l+
System Boot Time: | 2021-12-17 14:25:12
fppd Uptime: | 1 day, 01:58:23
Local Git Version: | a4ea8d3 ChangeLog
Remote Git Version: | a4ea8d3

**Describe the bug and Steps to reproduce**: 
I can't reproduce. It happens randomly at different times on different sequences.

**Expected behavior**: 
Audio cuts out for about 5 sec. and the frame rate to all 5 Falcon controllers drop to about 2 FPS for 5 sec. 

**Additional context**: 
Attached are the logs. It happened 3 times last night within 30 min, starting at 2021-12-19 18:06:24.386. Audio is hooked up to amplifiers from a SoundBlaster3 (USB)

**Additional Attachments**
Attached

[FPP_Logs_20211221.0224.zip](https://github.com/FalconChristmas/fpp/files/7749119/FPP_Logs_20211221.0224.zip)

Thanks,
Markus Hempell
MHempell@me.com
971-280-0969

**Comment by MarkA75160** [comment]
Please provide more details regarding your topology.   How many FPP's?  How are they configured (player, remote, etc)?   Are you sending e1.31 to the Falcons controller from a single FPP player or are your using multiple FPP remotes to front-end each controller?  How are  you playing audio?  Soundblaster or other?  etc. etc. etc.

I picture or sketch of your network would be a big plus

**Comment by ghormann** [comment]
Closing due to lack of response from OP.
