### ISSUE TITLE
Floating Controls for Mobile (Play, Stop, Next, etc)

### ISSUE THREAD

**Issue by cabrower** [FalconChristmas/fpp#1217]
When using FPP on a mobile device, if you have a large playlist on the status screen you must scroll all the way down the screen select the item you wish to play from the currently playing playlist and then scroll back to the top to hit Play, Stop, Next, Adjust Volume, etc

**Describe the solution you'd like**
It would be helpful if as you scrolled the controls minimized and floated down the screen with you instead of remaining at the top of the page in mobile mode.

**Comment by TechTurtleTube** [comment]
Would be a nice enhancement

**Comment by adamcoulombe** [comment]
I had this behaviour working earlier this year on a local branch. Just had a bit of formatting to touch up if I recall.

**Comment by adamcoulombe** [comment]
Latest commit has floating player controls. Please take a look and let me know what you think.

**Comment by cabrower** [comment]
Thats exactly what I was thinking! Great work!
