### ISSUE TITLE
Scheduling Calendar Widget

### ISSUE THREAD

**Issue by robbiet76** [FalconChristmas/fpp#1218]
Having flexibility in scheduling has been great but can sometimes lead to many rows in the scheduler when accounting for different shows with different hours depending on things like day of the week, holidays, and other customizations.

It would be great to have a calendar widget where we could pick custom show hours by date all in one place.  This would look similar to what you see when you look up hours for an amusement park (See attcahed).

I'm not sure if this is possible and it would represent a big change in how the scheduler would work.  Obviously not critical and an enhancement for the future, but wanted to put the idea out there.

![2020_Park_Hours](https://user-images.githubusercontent.com/63306703/146985736-0a2d7991-aa86-44a8-836c-1adc4761f492.png)

**Comment by cpinkham** [comment]
I like the concept as an option and have tossed around a few ideas in the past concerning similar functionality.  There are a couple ways we could accomplish this one would be to just hide the current complexity from the user via UI code.  The playlist/calendar based UI would let the user pick a playlist along with dates and times and the 'save' would write out the complex scheduler config file to use the existing backend code.  The other method would require mods on both the frontend UI and the backend to allow the backend to take a list of startdate/enddate/startime/endtime arrays and internally it could handle or convert those as needed.

The multi-date picker here seems like it might help:
https://dubrox.github.io/Multiple-Dates-Picker-for-jQuery-UI/#demo-full-year

This one looks like it might have some nice options as well:
https://demo.mobiscroll.com/jquery/calendar/multiple-select#

I'll give it some thought.  I know it would probably help simplify my schedule a little as I have 20 entries in my schedule currently for different days/times/playlists.

**Comment by darylc** [comment]
FPP team decided not to implement this
