### ISSUE TITLE
Playlist management - show if sequence already exists in current playlist when adding.

### ISSUE THREAD

**Issue by kevinsaucier** [FalconChristmas/fpp#1222]
When adding a sequence to a playlist, it would be a huge help to know if that sequence already exists in the playlist.  When trying to add  70 sequences to a playlist, just some visual indicator that I've already added it would be great. 

A related request would be to allow 'Add All' sequences to a playlist.  More work but a better option would be to check off a bunch of sequences and add in bulk.

Thanks!

**Comment by MarkA75160** [comment]
Have you tried the FPP Connect tool in xLights to add sequences to an FPP playlist?  It doesn't check for duplicates (your 1st request) but it does support bulk add (your 2nd request)

**Comment by kevinsaucier** [comment]
Yes, I have used FPP Connect to add to the playlist.  To be honest, I don't remember what issue I had with it that stopped me from using it, but there was something I didn't like about it.  🤔  Off the top of my head, I'm thinking it's only really useful for the initial upload of a sequence so you couldn't use it to populate a 2nd playlist (Remote Falcon, for instance) without using FPP Connect to upload all of the sequences again (I think).

**Comment by MarkA75160** [comment]
FPP Connect has smarts to not upload sequences that already exist and are unchanged.   So even if you have the sequences selected in FPP Connect and do the upload, it won't copy them if there is no changes.  But it will still add them to the playlist if you have that option selected.  That way, you can upload/add them to one playlist the 1st time, then run it again and add them to a different (e.g. Remote_Falcon) playlist without it re-copying all the fseq files.

**Comment by kevinsaucier** [comment]
Well, that's good to go know, at least.  That'll help a bit.  Thanks.  

Now......about that first request (which is the one that drives me far more nuts).....  😂

**Comment by adamcoulombe** [comment]
Just to note, some people add the same sequence to a playlist multiple times. It might be a fine request to see perhaps the number of times the selected sequence shows up already in the current playlist.

I do have questions about the scope of this enhancement request though.

1. A playlist can have more than just sequences. It can be commands, media, another playlist, Sequence+Media, etc etc. IMHO it seems a bit extraneous to be checking all these things to see whether a matching entry is already in the playlist.
2. A playlist has a lead in and lead out, in addition to the main playlist.  Would such a feature check the lead in/out as well? Would it need to differentiate such matches when displaying this information back to the user.

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this as a feature in the UI.
