### ISSUE TITLE
Network Scanner Plug in

### ISSUE THREAD

**Issue by davidspalding** [FalconChristmas/fpp#1223]
Have had a commercial display that had controllers default to DHCP. spoke with David pits and network scanner in FPPwould allow us to reprogram remotely without having to drive hundreds of miles to reprogram controllers

Have an FPP plug in that would allow you to scan the wired side of FPP to find IP;s of controllers that may have defaulted to DHCP

I have requested controller manufactures to create a generic host name similar to (fpp.local) to be able to hit controllers that defaulted

After working with several commercial displays remotely and helping in Xlights zoom room i see this would benefit the community to be able to see what's on the bridged network.

**Comment by cpinkham** [comment]
FPP already has the built-in ability to scan your network looking for network based controllers and it can differentiate between discovered Falcon, San Devices, ESPixelStick, AlphaPix, HinksPix, DIYLED, and WLED controllers.  On the FPP MultiSync config page, scroll to the bottom of the page and hit the settings button and it will show some additional settings.  In the "HTTP Discovery IPs and subnets" setting, add the subnet you would like to scan, such as "192.168.1.0/24" and FPP will perform a HTTP based scan of that subnet when fppd starts.  Discovered controllers will be listed on the MultiSync page.  fppd does not currently do periodic rescans via HTTP, but you could restart fppd on a standalone FPP instance or a remote and have it discover if you don't want to stop the show to restart fppd on the master.  fppd will periodically re-ping known hosts over HTTP to see if they go away, but it will not discover new IPs such as when a controller switches IPs.
