### ISSUE TITLE
Controlling WS2811/12 via the GPIO outputs on Raspi 4b?

### ISSUE THREAD

**Issue by glenc2004** [FalconChristmas/fpp#1224]
Hello all! I am new to the FPP Player and for next year I'd like to get into this hobby. One question I have is can I just use the GPIO output pins directly in FPP? I'm able to controller ws2811/12 lights using neopixels interface from raspi, but I don't see how to do this from within FPP. I'm building my own interface to use some of the GPIO pins such as 18 and 12. But I'm looking to do as much as possible on my own building the connections.

It works great using python and neopixels, but I want to do a show with FPP and xLights. I just don't see how to configure this within FPP as such using GPIO pin 12 and 100 lights as a test.

If someone could point to a sample I could copy that would be great. I've looked at so many youtubes in the last month but nothing using straight connections to raspi.

Thanks!

Glen

**Comment by adamcoulombe** [comment]
You can still drive 2 pixel strings from GPIO18 and GPIO19 using cape type "**PiHat**". This is the equivalent of selecting RPIWS281x on earlier versions of FPP (there is a bit more information when you press f1/Help on the Channel Output Page) 
![image](https://user-images.githubusercontent.com/469038/147938366-495a5976-8c29-42fb-a054-fdb168f6622a.png)

**Comment by MarkA75160** [comment]
Doesn't matter if its a Pi Zero, 1, 2, 3, or 4  it works the same way for all of them.  You can drive pixels directly off the GPIO pins and a PiHat is not physically required.  However, you need to configure FPP as if a PiHat was connected.  Enabling that cape type in FPP is what tells it to activate those GPIOs for driving pixels and it allows you to configure the two different strings as needed (pixel count, grouping, RGB order, etc.)

**Comment by glenc2004** [comment]
Thanks for all the information! Will there be anytime in the future FPP will support GPIO pins other than 18 and 19? I broke my pin 18 so it cannot be used. Is there a reason to only support those 2 pins? I'm new to Raspi so I'm not sure if there is a technical issue or not for only supporting two pins.

Thanks!

Glen

**Comment by MarkA75160** [comment]
Its not an FPP restriction.  Its a Raspberry Pi restriction.  Those are the only two pins that can do the PWM signaling that ws2811 needs.    Thats why the Beaglbone is used for the bigger controllers, its processor is not as fast, but it has a ton more GPIO capability with PRU's to offload that work from the CPU.    

So the answer is, YES, FPP already supports more GPIO pins .... on the BeagleBone :)

**Comment by ghormann** [comment]
18 and 19 selected because of the 2 PWM outputs.... When technically there are 4 PWM pins on the Raspberry Pi, but each pair of the 4 pins is sharing one PWM resource. GPIO12 and GPIO 18 are sharing one PWM channel while GPIO 13 and GPIO 19 are sharing on the other one. This means that there are only 2 unique/controllable PWM channels on the pi.

**Comment by MarkA75160** [comment]
can  you solder a wire to where the pin broke off?   I drive pixels directly off the GPIO's on Pi Zeros which don't come with and pins.  I solder directly to the pad.

**Comment by glenc2004** [comment]
Gotcha! Thanks for the hardware info. As for pin12(GPIO18) I fried the pin itself. I cannot get a signal high in the pin. It' always low. And when I put the gpiotest script on the hardware and run it ping 18 came back saying there was an error on that pin and one other. I don't remember the exact error. The other pin works just fine. I probably shorted it to 5v accidently. I have a pi on order anyway to replace it. Just going to take a while. :-)

Thank again for all the assistance.

Glen

**Comment by adamcoulombe** [comment]
Your wiring needs to look like this. (You may not need the resistor)
![image](https://user-images.githubusercontent.com/469038/148218322-e04bdb9a-2469-4ddc-b8e9-be675b9a5787.png)

Then, simply enable pixel strings with cape type “PiHat” on the Input/Outputs page

Then, on the same page, you need to configure the number of pixels you are trying to light up on the respective output (gpio18=1, gpio19=2).

Once you do this and save your configuration,  go to status/control>display testing and enable test mode with all channels.

Your pixels should light up.

**Comment by MarkA75160** [comment]
" (You may not need the resistor)"

Thats not a resistor, its a diode.  Its used for reverse polarity protection and is not needed unless you're bad about keeping +/- polarity straight. 😉

They also drop the supply voltage around 0.5-1.0 volts so they may be assuming a 6v power supply in that example

**Comment by glenc2004** [comment]
I have it working on the other gpio port using the circuit with the Quad Level-Shifter but swapped it out for the IIC I2C Logic Level Converter Bi-Directional Module 3.3V to 5V Shifter. And yes, I do use a resistor to protect the output pin. I just made the dumb move of hosing pwm0. :-(

Glen
