### ISSUE TITLE
Docker container feature request Virtual matrix add to Input/OutputSetup>Output channels>Other

### ISSUE THREAD

**Issue by bsmith76s** [FalconChristmas/fpp#1226]
I was happy to see the arm64 docker image for FPP. When I created a container and ran it I noticed I could not setup a virtual matrix on the FPP container. I see there is no option at Input/OutputSetup>Output channels>Other. I was hoping to use a virtual matrix for a projector. Am I just missing something?

**Describe the solution you'd like**
I would like to see the virtual matrix feature be added to docker image.

**Comment by darylc** [comment]
did you give your fpp container a video card or similar?

**Comment by dkulp** [comment]
By default, docker doesn't allow containers to access much of the hardware, including the framebuffer device.  You would need to give it access to /dev/fb0 ( I think it's --device=/dev/fb0 ).   If fpp detects the fb0 device, the virtual matrix option should automatically appear.

**Comment by bsmith76s** [comment]
> did you give your fpp container a video card or similar? 

I did add /dev/fb0 to devices in docker-compose.yaml and the virtual matrix option is there now. But I can not get it to output to monitor.
 running on pi4 RPI OS arm64
