### ISSUE TITLE
Question on output for PCA9685

### ISSUE THREAD

**Issue by glenc2004** [FalconChristmas/fpp#1227]
Hello all. Sorry if this is the wrong place to post these questions. I'm having issues trying to get an account on falconchristmas.com to be able to post to the forums to ask questions.

I just picked up a PCA9685 and I would like to configure it in FPP. I cannot find any docs on how to configure the interface in FPP. Did a few google and youtube searches and no one goes into specific details how to get this to work. Anyone have any info on this?

By the way...this is for controller WS2811 RGB's.

Thanks!

Glen

**Comment by darylc** [comment]
The PCA9685 support in FPP is for servos as far as I am aware, so I doubt you can use WS2811's with it.  You add it as a channel output.  Input/Output setup->Channel outputs->Other->Add->PCA9685

By the way, we would prefer you don't open github issues for general support.

**Comment by dkulp** [comment]
As @darylc states, the PCA9685 cannot be used to drive WS2811.   You need to use the PiHat configs on the Pixel Strings page for those and wire to the appropriate pin.   The PCA9685 is primarily used for Servos, but it can also be used to drive/dim normal "dumb" stings/leds.  The configuration on the "Other" tab for the PCA9685 defaults to common configurations for Servos, but it can be easily changed to use a full 100% pulse and such that would be good for dumb RGB.
