### ISSUE TITLE
Error thrown when video has spaces in file name

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1228]
Looks like this particular call doesnt like spaces in the file name?

[MediaOut] /opt/fpp/src/mediadetails.cpp:64: Unable to find /home/fpp/media/videos/White Winter Hymnal.mp4 media file to parse meta data

**Comment by derwin12** [comment]
I think it is even more than this .. I changed the file names to a simple abc.mp4 and get the same error.
The code seems to prefix with FPP_DIR_VIDEO *and* mediaFilename which is full qualified, resulting in a file not found.
?

**Comment by cpinkham** [comment]
Where are you seeing this error?  That function should not be called with a fully pathed filename, it should only be given a base filename and then it searches in both the music and video directories.  Are you using the API and passing in the full path to a file or are you passing in just the base filename?

**Comment by derwin12** [comment]
I guess I left out some of the important parts .. sorry about that.
So I created a playlist, with one step. 
Type: Media Only
File Mode:  Random Video
Save that
Go to Status Page and Play that playlist

If it chooses a file with spaces, it throws the error..
2022-02-06 11:32:21.391 (1307) [MediaOut] /opt/fpp/src/mediadetails.cpp:64: Unable to find /home/fpp/media/videos/All I Want For Christmas Is You (edit).mp4 media file to parse meta data
