### ISSUE TITLE
Edit Playlist entry doesnt change the UI to allow file name to be entered.

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1229]
5.4.1
Entry was Media Only, Random Video -- Add.
Now edit that entry and change it to Single File. You cant enter the file name.

Daryl.

**Comment by adamcoulombe** [comment]
PR #1230 Should likely fix this, someone else should double check that logic just to make sure it wont conflict with some other behavior

**Comment by ghormann** [comment]
Seems to work in my testing.
