### ISSUE TITLE
WLED With scheduler 

### ISSUE THREAD

**Issue by yellow5851** [FalconChristmas/fpp#1231]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[fppd.log](https://github.com/FalconChristmas/fpp/files/7836850/fppd.log)

Version: FPP 5.4.1 running on Kulp k8 with BBB

The bug that I have located seems to be when I have  Command Overlay effect WLED, set as a playlist or command push with a schedule, the effect will not launch.  All my pixels will stay dark.  Now if I manually run the command everything runs as intended      
![Screenshot 2022-01-09 205722](https://user-images.githubusercontent.com/26759457/148720096-7026fd0b-533e-4d55-af98-8315169de96c.png)

![Screenshot 2022-01-09 205924](https://user-images.githubusercontent.com/26759457/148720199-ea886d92-5a4e-4091-87e7-81a311c82b70.png)
 
I have resorted to pushing a fpp command "overlay effect WLED" that starts per the scheduler. 
![Screenshot 2022-01-09 210203](https://user-images.githubusercontent.com/26759457/148720335-c64e1e72-8054-44b9-a351-97de0269fb08.png)
 
If I reboot after the designated command start time, the command will not be sent again and my pixels will stay dark until I manually run the command.   

I would like to run a command or playlist daily that starts every day at 5:30pm and ends at 11:30pm and runs a WLED Overlay effect. If i reboot i would like the command to run again if between the time window.  
[FPP_Logs_20220110.0507.zip](https://github.com/FalconChristmas/fpp/files/7836884/FPP_Logs_20220110.0507.zip)

Thank you for your help on this!!!  Much appreciated.

**Comment by adamcoulombe** [comment]
@yellow5851 You will probably need to post a log with a more granular log level. Just prior to the scheduled command executing, you will want to set logging levels to "Excessive"  under Status/Control>Settings>Logging>Bulk Change Log Level>Excessive

Note that you don't want to leave it on this setting once you've captured the necessary logs.

**Comment by cpinkham** [comment]
If you want to do this, add a 5 or 10 minute pause to your playlist and then you can schedule it to repeat.  The reason it has an issue now is that it repeats immediately and just restarts the effect over and over continuously.  If you put in a pause, it will let the effect play for 5-10 minutes, then start again, which will allow you to schedule the playlist as a repeating playlist without constantly restarting the effect.  Other than that, I don't see any way around this currently.  FPP will only re-run a scheduled playlist after a reboot if the playlist is set to repeat.  I don't currently see us adding any "run this scheduled item once and again if fppd restarts during this start/end time frame" kind of logic to the scheduler.
