### ISSUE TITLE
RPi4 Wi-Fi Problems & Solution - FPP

### ISSUE THREAD

**Issue by b0nafide** [FalconChristmas/fpp#1232]
**Is your feature request related to a problem? Please describe.**

Hey guys, first off... thank you for FPP and all of your hard work. You guys are wicked smart and FPP is awesome. 

This year (after 4 years), I upgraded my RPi from a 3B to a 4. What I didn't understand is the RPi4 apparently has problems with WiFi and switching/turning off between 2.4 GHz and 5 Ghz. This has been documented throughout the RPi community... go ahead and search it up. Essentially the wlan0 freezes out and does not reconnect. Doesn't matter what version of FPP this year - the RPi4 WiFi failed all year long.

I noticed the problem this season after about 24 hours of FPP being up and running. I was unable to connect to my FPP, so I checked my router and found that it was disconnected - I was unable to ping it either. If I went outside and powered it off and back on again, it would work. But 24 hrs (or so) later... disconnected from my network. Despite being disconnected, FPP was still running as my show continued on as scheduled. Along with all of the normal yearly troubleshooting.. I got sick of messing around with it and left it until now. 

Now that the holidays are done.. I'm trying to troubleshoot it now. See additional context for a solution that seemed to have worked.

**Describe the solution you'd like**

I realize the problem does not exist with FPP but somehow with the RPi4... but perhaps you guys could come up with a solution to automatically reconnect wlan0 if it drops?

If FPP detects a RPi4 board, then it pings the router every 5-10 mins or something. If no response is received, then it restarts wlan0?

**Describe alternatives you've considered**

I really don't have any alternates as I was hoping, you guys would have a better idea what to do?

**Additional context**

See https://falconchristmas.com/forum/index.php/topic,15137.0.html for the solution I implemented to fix it on my own.

Essentially, I made a script to auto run that pings my router every 5 minutes. If the ping returns a value, carry on... if the ping is 0, then it restarts wlan0. 

(Checkwifi.sh)
----------------
ping -c4 10.0.0.1 > dev/null
                                                                             
if [ $? != 0 ]
then
                                                                             
echo "No network connection, restarting wlan0"
/sbin/ifdown "wlan0"
sleep 5                                                                      
/sbin/ifup --force 'wlan0'
fi

-----------------

Then I added this to "crontab" or "nano".. or something.. I can't remember

-----------------

Sudo -H checkwifi.sh >> /dev/null 2>&1

-----------------

I don't know if dev/null actually exists or if anything actually gets written there.. but I don't know anything about this stuff and kinda jimmy rigged this solution after reading a bunch of stuff on the internet. 

I actually don't really know how often the Wifi drops.. all I can report is that my FPP has been connected now for four days (new record) and seems speedy as ever. 

Anyways... thanks for the consideration. Appreciate your efforts. 

Once again - you guys are awesome.

**Comment by b0nafide** [comment]
Ok, the above "solution" didn't work.. after five days the Wifi dropped.

**Comment by adamcoulombe** [comment]
it might be helpful to provide a link to the documented issue with pi 4 in general.

Don't most routers have the ability to broadcast ssid's with dedicated bands? I would think this to be a simple way to avoid making the pi switch bands and freezing the wifi.

**Comment by MarkA75160** [comment]
> Don't most routers have the ability to broadcast ssid's with dedicated bands? I would think this to be a simple way to avoid making the pi switch bands and freezing the wifi.

The theory was this had to do with band switching.... and it may somehow be related.   BUT, the problem still happens even with single-band WiFi adapters.   And its not limited to the Pi4.   I've had it happen on the BB and PB controllers with single-band WiFi dongles.

The difficulty is trying to make it happen.  Many users have reported it, but no clear pattern or know way to make it happen.   The WiFi just drops offline and FPP reports "no network" until reset or reboot the network adapter.

**Comment by darylc** [comment]
There is nothing directly actionable here and FPP has changed a lot since 5.x to 6.x so probably time we closed this.  If there are ongoing problems with wifi on FPP lets open a new ticket and hook up a keyboard/monitor while it's in the state and grab debugging info so we can see whats actually happening to help us fix it.
