### ISSUE TITLE
Pihat option not available in Pixel String configuration

### ISSUE THREAD

**Issue by creature7** [FalconChristmas/fpp#1233]
Have a BBB running latest 5.41, and can't figure out how to control a WS2812b led pixel string using a GPIO output pin. The FPP Manual says to select the 'PiHat' cape option for Pixel Strings, but that option does not exist(!) Is there a new way to accomplish this, or is the manual wrong?

**Comment by adamcoulombe** [comment]
Do you have a cape on your beagle? PiHats are only for raspberry pi, not beaglebone.

**Comment by adamcoulombe** [comment]
If you just want to control pixels straight off the bbb gpio, refer to the cape config files for the pinouts: https://github.com/FalconChristmas/fpp/tree/master/capes/bbb/strings

simply select a corresponding cape and refer to the json file so you can know which pins correspond to that cape’s outputs

**Comment by creature7** [comment]
Not cape (on my dog). I get your suggestion. Sure seems like my use case is not something that Falcon Player is meant for. The manual (5.0) seems a bit misleading too, since there is no PiHat as mentioned. Just saying.

Thanks for the suggestion.

**Comment by adamcoulombe** [comment]
It’s not that fpp isn’t made to do it, in fact I run multiple bbb’s without capes, but I will grant you that aspect isn’t documented as thoroughly, being that it’s a less common use case with the majority of people using capes

**Comment by creature7** [comment]
Is it because of the difficulty of interfacing 3.3V to a 5V strip?

**Comment by adamcoulombe** [comment]
Someone who uses capes would be better qualified to comment than me, but I believe that is part of it. A large number of people who use fpp just want to set up their Christmas lights and don't want to screw around with wiring more than they have to.
