### ISSUE TITLE
Buttons and status/navigation menu UI glitches if no network interface

### ISSUE THREAD

**Issue by kurtlamm** [FalconChristmas/fpp#1238]
*FPP Version 5.5 on PocketBeagle*

**Describe the bug and Steps to reproduce**: 
Image SD card and boot up on Pocketbeagle as normal. Use USB tethering via micro USB port on PocketBeagle.
If no ethernet or wifi network interfaces are plugged into the PocketBeagle several UI glitches occur (see below).

There is also some weird behaviour with "FPPD not running" notifications showing up more often. For example, if "Restart FPPD" is pressed, the UI shows the "Abnormal Conditions - May Cause Poor Performance  FPPD Daemon is not running" warning and won't go away until the page is refreshed. 

**Expected behaviour**: 
The start and stop FPPD button (beside restart FPPD) is small and has no text in it. Expected behaviour: button works as normal

The top status/navigation menu is missing items; only hostname and BeagleBone logo appears. Expected behaviour: status/navigation menu is populated as normal; FPPD status icon exists, CPU temp icon exists, date/time info exists.

**Additional context**: 
I understand that currently, not many people use the PocketBeagle without a network interface. However, I am using several as a standalone device to control lights and other outputs when triggered via one of the GPIOs for Halloween and escape room displays. As people in these industries see the immense value of FPP I expect more people to be using PocketBeagles in a standalone mode so it would be nice to have these UI glitches fixed. 

**Additional Attachments**
Nothing too important in the log files; starts up and works as normal. However, in "fpp_init.log" there are the following notes that I think are part of the problem:
ls: cannot access '/home/fpp/media/config/interface.w*': No such file or directory
ls: cannot access '/home/fpp/media/config/interface.e*': No such file or directory

[FPP_Logs_No_Network_Interface.zip](https://github.com/FalconChristmas/fpp/files/7998063/FPP_Logs_No_Network_Interface.zip)
![PocketBeagle FPPD Glitch](https://user-images.githubusercontent.com/47014079/152425372-28ae1620-c4d6-4a69-ad10-02aeb313f232.png)
![PocketBeagle FPPD Glitch Circled](https://user-images.githubusercontent.com/47014079/152425379-ba0cc169-eff9-4aea-a39a-913fa92965ca.png)

**Comment by ghormann** [comment]
Oddly enough, I've reproduced this on an early buster build.    The problem I'm seeing is with the `/api/system/status` API.   If the PI boots without a network a proper JSON message is not returned.  Intead we get some php errors. 
```html
<br />
<b>Notice</b>:  Undefined index: channelRanges in <b>/opt/fpp/www/api/controllers/system.php</b> on line <b>378</b><br />
<br />
<b>Notice</b>:  Undefined index: majorVersion in <b>/opt/fpp/www/api/controllers/system.php</b> on line <b>379</b><br />
<br />
<b>Notice</b>:  Undefined index: minorVersion in <b>/opt/fpp/www/api/controllers/system.php</b> on line <b>380</b><br />
<br />
<b>Notice</b>:  Undefined index: typeId in <b>/opt/fpp/www/api/controllers/system.php</b> on line <b>381</b><br /
```
