### ISSUE TITLE
Video capture in FPP

### ISSUE THREAD

**Issue by jlarsonomaha** [FalconChristmas/fpp#1240]
Hello, In Xschedule one of the options I use is a button activated feature for the visitors. In xschedule when a button is pressed the software will pull up a web page and display the part of that web page that I have defined and place it on a P5 panel so people can see a live view of themself in the display. In FPP I can see how to do this off a camera connected to the PI but I am using a web camera. If you need more info you can reach me at larsonj@cox.net.

Thank You,

John

**Comment by dkulp** [comment]
The video capture plugin likely would require some updated to allow configuring IP based cameras.  Currently, if v4l2 can see the camera (there is a /dev/video* device for it), then it work, but there currently isn't a way to easily create that device for ip cameras.    A script that does stuff from:

https://www.linux-projects.org/uv4l/tutorials/turn-mjpeg-stream-into-camera/

to start the camera and create the device may work.   Not really sure.

**Comment by darylc** [comment]
video capture plugin was updated by Dan in April 2022 for this.
