### ISSUE TITLE
Provision wlan0 before wlan0 exists

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1241]
**Describe the solution you'd like**
The ability to provision wlan0 before /dev/wlan0 exists.  

**Additional context**
Many of the BBB green based controllers only have 1 USB port and getting WLAN devices that support tethering are hit and miss.  What I typically end up doing is grabbing a powered USB hub so I can connect a wireless dongle and ethernet dongle.  This allows me to get the device on the network and then provision the wlan0 interface.

I'm asking for the ability to add wlan0 to the list so that I can eliminate the usb hub and just configure it via this manner. 

This would also be useful when configuring via USB tether and not having enough amps via this method to power the cape too.

**Comment by darylc** [comment]
When in Advanced UI mode, we will now show interfaces that have config files that are not detected in the list of interfaces.  You can create new interfaces that don't exist on the local system (empty interface config files) using the Add Interface button

![image](https://user-images.githubusercontent.com/7511887/216946087-b13a5458-7862-45c0-b63a-7740e2991505.png)

**Comment by dartunder** [comment]
@darylc 
So how does one remove an interface if not needed?
