### ISSUE TITLE
httpvirtualdisplay crashing

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1252]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP Version 5.5 and Master a6ea112

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Upload Model data and Sequence from xLights to FPP
2. Create a httpVirtualDisplay in the Channel outputs
3. Start a sequence.
4. The song will play as expected until the HttpVirtualDisplay webpage is opened and then fpp will crash

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 
The beginning of the log shows:

2022-02-15 17:17:04.783 (2420) [General] /opt/fpp/src/fppd.cpp:226: Crash handler called:  11
2022-02-15 17:17:09.361 (2421) [MediaOut] /opt/fpp/src/mediaoutput/VLCOut.cpp:109: ES_OUT_SET_(GROUP_)PCR  is called 2831 ms late (pts_delay increased to 1000 ms)
2022-02-15 17:17:09.724 (2420) [General] /opt/fpp/src/fppd.cpp:210: Stack: 
[New LWP 2001]
[New LWP 2016]
[FPP log.txt](https://github.com/FalconChristmas/fpp/files/8075841/FPP.log.txt)

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by cpinkham** [comment]
We are likely going to need the files which caused this issue as there isn't much in the logs other than it looks like it died in HTTPVirtualDisplay::PrepData().  I just tested the HTTP Virtual Display on my system running the latest master and it is still workign correctly, so something in the user's config or data is triggering an issue.

**Comment by Poporacer** [comment]
I am not sure what the issue was, but because I made several changes, I had to reinstall FPP and HTTP Virtual matrix worked properly. The previous issue was tested using a fresh install of FPP. Closing since I cannot replicate the issue.
