### ISSUE TITLE
Add support for a MultiSync fallback sequence if .fseq being played does not exist

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#1253]
Add support for a remote to play a fallback sequence .fseq file if the master is playing a .fseq file which does not exist on the remote.

**Comment by msimmons78** [comment]
Further this functionality to run fallback sequence if remote looses connection to master and if sequence should loop or not until master re establishes connection.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chris Pinkham ***@***.***>
Sent: Wednesday, February 23, 2022 10:21:28 AM
To: FalconChristmas/fpp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FalconChristmas/fpp] Add support for a MultiSync fallback sequence if .fseq being played does not exist (Issue #1253)


Add support for a remote to play a fallback sequence .fseq file if the master is playing a .fseq file which does not exist on the remote.

**Comment by darylc** [comment]
The way the master/remote protocol works, the remote can't really tell the difference between the master not wanting to play anything and the master disappearing.

**Comment by darylc** [comment]
@Poporacer One for the documentation, remotes will play fallback.fseq if it exists and the sequence the player is asking it to play is missing.

**Comment by dkulp** [comment]
FYI: I'm not sure this was necessary. We already look for a "background.eseq" (which can really be an fseq file just renamed) as well as a "background_HOSTNAME.eseq". I've used this for years for my tuneto on halloween night. The other option is you can schedule a background effect to start at the beginning of the show and then stop it at the end. Thoughts?
