### ISSUE TITLE
unable to initialize RPIWS281x output hardware c03115

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1254]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP version 5.5-17-g381bfa6b and 6.x-master-62-gcdfaca38
Pi 4 GB rev 1.5 4GB.. .cpuinfo in attached file.

**Describe the bug and Steps to reproduce**: 
Enable any pihat that uses the rpiws281x library (pi hat, rPi-28D+ tested). Save then restart fppd.  Then go go the status page and will get the abnormal condition error that it cannot initialize the output type. 

**Expected behavior**: 
After enabling the hat the output should be initialized and work. 

**Additional context**: 
I know this was fixed in e561ff20 about a week ago for the 2gb model that is revision b03115 but the 4gb model c03115 and the 8gb model d03115 was not included so this issues still exists on these other 2 rev 1.5 boards. 

**Additional Attachments**
Please include the log files. To create the file:

![FPP cpu info](https://user-images.githubusercontent.com/88390168/155826033-3ebb60ff-9696-47ba-9711-37db8fe266b9.JPG)

**Comment by cpinkham** [comment]
Once the library maintainer pulls in a couple pull requests they have, this will be fixed upstream and we can update our setup to pull in the updated rpi_ws281x code.

**Comment by bloojoop** [comment]
@cpinkham , FYI,  If I'm reading it right, looks like the pull requests were merged yesterday 3/1/2022 in rpi_ws281x project.

**Comment by cpinkham** [comment]
Fixed by Dan in b779d5a8f
