### ISSUE TITLE
Error with v6.x-master-150-g3f1aaa3e (master branch) 

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#1261]
Error with v6.x-master-150-g3f1aaa3e (master branch)  on all Platforms
[FPP_Logs_20220325.1956.zip](https://github.com/FalconChristmas/fpp/files/8353501/FPP_Logs_20220325.1956.zip)

**Comment by ghormann** [comment]
@JerryPlak  If you want a Dev to look at this, please provide a more detailed description
1) Exact error you receive
2) Steps to reproduce

**Comment by JerryPlak** [comment]
1.Exact error you receive... After up dating to 150-g3f1aaa3e  the FFPD don't run and it need to be rebuild..
2. just try dating to on any Platforms aka Pi BBB or Debian  
3. look at the  git_pull.log   found this   /opt/fpp/src/FrameBuffer.cpp: In member function ‘void FrameBuffer::DrawLoop()’:
/opt/fpp/src/FrameBuffer.cpp:795:13: error: ‘SyncLoopX11’ was not declared in this scope; did you mean ‘SyncLoopFB’?
  795 |             SyncLoopX11();
      |             ^~~~~~~~~~~
      |             SyncLoopFB
make: *** [Makefile:84: FrameBuffer.o] Error 1
make: *** Waiting for unfinished jobs....

4. it's looks it can't finished the jobs....
5. I did an Change Log back to 02ce609 to get back up and runny

**Comment by JerryPlak** [comment]
Thanks it's looks Build Fix 5036193  took care of the issue
