### ISSUE TITLE
rPi-28D+ output initialization error

### ISSUE THREAD

**Issue by ffux** [FalconChristmas/fpp#1263]
FPP Version: | 5.5
Platform: | Raspberry Pi 4GB ram
FPP OS Build: | v5.3
Hat: rPI-28D+

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Channel Outputs, Pixel Strings
2. Click on Enable String Cape, with Cape Type rPi-28D+
3. Save and restart FPPD
4. On the Status Page, the following error is encountered:
Abnormal Conditions - May Cause Poor Performance
Could not initialize output type RPIWS281X. Check logs for details.

Appears to be the same behavior as https://github.com/FalconChristmas/fpp/issues/1254

**Expected behavior**: 
The output is initialized

[FPP_Logs_20220327.0734.zip](https://github.com/FalconChristmas/fpp/files/8357127/FPP_Logs_20220327.0734.zip)

**Comment by cpinkham** [comment]
Your system is not up to date.  You need to go to either the About page or the MultiSync page and pull in the latest updates for the v5.5 branch and that should update the rpi_ws281x library to a version which knows about your new Pi.
