### ISSUE TITLE
Feature Request : allow multiple control channels for command preset's 

### ISSUE THREAD

**Issue by SmAsH-jl** [FalconChristmas/fpp#1267]
**Is your feature request related to a problem? Please describe.**

Only able to trigger one command preset simultaneously from a sequence because FPP only accepts one control channel for command preset triggering.  So if I send 2 values to the same channel at the same time, FPP only triggers the 1 command preset. 

**Describe the solution you'd like**

Multiple control channels or a control channel definable per command preset would be amazing. 

**Describe alternatives you've considered**

Creating command presets of the type "trigger multiple command preset slots" to group multiple slots together and then triggering that preset but it get's messy. 

**Additional context**

![image](https://user-images.githubusercontent.com/3165913/162847314-4523b4ab-2da2-4dc6-b2b6-d9ca27b117a5.png)

![image](https://user-images.githubusercontent.com/3165913/162847404-90105d6b-8715-4043-b4e6-967e3b3cb895.png)

**Comment by darylc** [comment]
@SmAsH-jl how many do you realistically think we should support?  Is one additional control channel enough or do you desire more?

**Comment by cpinkham** [comment]
Is there any reason you can't fire the two presets in series?  I can't see much benefit to firing them in parallel to save 25ms or 50ms.  The response time of a lot of the presets would be much longer than 50ms although some are shorter.  What kind of things are you trying accomplish firing multiple presets at the same exact millisecond in time?

**Comment by darylc** [comment]
The FPP development team met and decided not to add more control channels.  There was discussion about potentially providing new functionality in xlights to make it easier to trigger effects and command presets in FPP though.

**Comment by darylc** [comment]
@SmAsH-jl FYI something similar to what you wanted is being implemented in issue #1468

**Comment by dkulp** [comment]
Issue #1469  may work even better as we implement that.

**Comment by SmAsH-jl** [comment]
Yes I was testing with Dan yesterday. Amazing thankyou.
