### ISSUE TITLE
GPIO inputs appear to be broke in V6.x master branch

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1271]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP V6.x Master Branch on Pi V3**: 

**Describe the bug and Steps to reproduce**: 
Is it possible the GPIO inputs are broken in 6.x master? I have 2 configured, but when I restart fppd with logging turned up, they don't appear to be enabled.

**Expected behavior**: 
It should list GPIO as enabled
![image](https://user-images.githubusercontent.com/8147459/163731993-ef8a4281-64a4-48ca-be41-94cf208ddc40.png)
![image](https://user-images.githubusercontent.com/8147459/163731998-e725a2bc-226a-4aed-ad72-0fc15982b20d.png)

**Comment by dkulp** [comment]
Fixed
