### ISSUE TITLE
MQTT User and Password

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1273]
It would be great to interact between FPP and my home automation (to trigger sequences on detection of movement etc) however my MQTT broker is set up to expect a username and password. So could this MQTT facility be added as an option to MQTT setup in FPP ?

FYI I use Node Red for home automation and Mosquitto as a MQTT broker however it is very common to set the broker up to expect/need a user and password to establish connection.

Regards & thanks

**Comment by ghormann** [comment]
Where are you seeing the gap?   MQTT allows for the specification of a Username and a Password.

![Screenshot_20220424-153718](https://user-images.githubusercontent.com/24968726/164993682-27cd1037-6ba4-4455-be96-def7cf4b5897.png)

**Comment by bakelitephone** [comment]
Hi, please see attached screen shot. I wonder if this is a problem because I am running fpp as a docker container ?

![1019C47F-A644-42ED-B301-5B160E6F813A](https://user-images.githubusercontent.com/69304144/164997701-95273100-a8ff-415a-817e-34d4a2d36059.jpeg)

**Comment by ghormann** [comment]
Type in the hostname and hit Tab.   Then all the other fields will appear.

**Comment by bakelitephone** [comment]
> Type in the hostname and hit Tab. Then all the other fields will appear.

Perfect! Sorry about that user error, I should have read the manual :-)

Apologies & many thanks
