### ISSUE TITLE
Update Platform filter in Multisync page to reflect Armbian and MacOS

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1274]
**Is your feature request related to a problem? Please describe.**
Update Platform filter in Multisync page to reflect Armbian and MacOS

**Describe the solution you'd like**
An updated Platform filter in Multisync page to reflect Armbian and MacOS
![image](https://user-images.githubusercontent.com/8147459/165004783-5023a812-783f-4175-89f6-9ae41e5f5a88.png)
![image](https://user-images.githubusercontent.com/8147459/165004790-fe5f8680-dba5-438b-9699-95a3abd59843.png)

**Comment by dkulp** [comment]
Fixed
