### ISSUE TITLE
Volume control doesn't work when running on Libre ALL-H3-CC (Tritium) 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1276]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *v6.x-master-233-g9e2c9102 (master branch)*

**Describe the bug and Steps to reproduce**: 
I uploaded audio files to FPP and created an Audio only play list.
Clicked play and nothing happened.
Checked FPP audio settings, fpp sees the following:
![image](https://user-images.githubusercontent.com/8147459/165394085-0795cd72-e21b-4828-9005-faf8a35483fc.png)
Selection Line out doesn't seem to make a difference
I changed it to Line Out Source still nothing.

I ssh'd into the Libre and ran alsamixer. I increased the line out level to 84 and exited.
![image](https://user-images.githubusercontent.com/8147459/165394548-19720af7-d96b-40e2-9456-162da56dbd3c.png)

I started the audio playlist and it played out the onboard mini jack. The FPP UI volume controls had no effect on the audio level

misc commands
```
fpp@FPP-Libre2:~/media/music$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Codec [H3 Audio Codec], device 0: CDC PCM Codec-0 [CDC PCM Codec-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
```
fpp@FPP-Libre2:~/media/music$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
hw:CARD=Codec,DEV=0
    H3 Audio Codec, CDC PCM Codec-0
    Direct hardware device without any conversions
plughw:CARD=Codec,DEV=0
    H3 Audio Codec, CDC PCM Codec-0
    Hardware device with all software conversions
default:CARD=Codec
    H3 Audio Codec, CDC PCM Codec-0
    Default Audio Device
sysdefault:CARD=Codec
    H3 Audio Codec, CDC PCM Codec-0
    Default Audio Device
dmix:CARD=Codec,DEV=0
    H3 Audio Codec, CDC PCM Codec-0
    Direct sample mixing device
fpp@FPP-Libre2:~/media/music$
```

**Comment by patdelaney** [comment]
The good news if I connect USB SoundBlaster dongle select that as audio Output device, reboot.  Play audio playlist audio comes out SoundBlaster and FPP volume controls work. :-)

**Comment by dkulp** [comment]
Fixed.
