### ISSUE TITLE
Docker images missing .asoundrc file in /root

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1278]
Docker images for [v5.x-master-661-g79ffaa62 (master branch)] and [v5.5] are both missing the Alsa configuration file **.asoundrc** in the /root directory. This is the same for both Intel and ARM, I suspect this may be missing in all the previous Docker image versions/ TAG's

I believe this default Alsa file is needed by fpp's PHP code to swap sound card devices, if it is missing the PHP element of FPP fails to swap the sound card giving the error:
 _[php7:notice] [pid 101] [client 192.168.1.34:59289] **Failed to set audio to card 1!**, referer: http://192.168.1.159/settings.php_

FYI: This file is not provided by **apt install alsa-utils** etc as this config file is designed to be a user generated file. 

**/root/.asoundrc**  does already exists in all the "none Docker" installs I have tested, I presume this was manually created in those build environments in the past etc.

The temp fix is to create a default **/root/.asoundrc** file inside the docker image with the following contents:

pcm.!default {
	type hw
	card 0
}

ctl.!default {
	type hw
	card 0
}

Unfortunately this temporary fix is not persistent when I update the containers etc so please could this /root/.asoundrc file be added to your Dockerfile build process or possibly to the standard SD/FPP_Install.sh used in Dockerfile ?

If found this because I was using 2 Docker containers that needed access to 2 seperate sound cards so I could have an individual sound card dedicated to each container and this error stopped it working. It now works fine with the temp fix above.

PS Apart from this your Docker images work brilliantly (on both Intel and Arm) even with dedicated IP addresses for several containers. 

Truly Amazing work please keep it up.

**Comment by ghormann** [comment]
Waiting to confirm after 734d780 before closing.

**Comment by bakelitephone** [comment]
> Waiting to confirm after [734d780](https://github.com/FalconChristmas/fpp/commit/734d7801c3d61d073b7c51430763d557f36a6de1) before closing.

**Wow** that was fast !!
Please let me know and I would be happy to help test any updated Docker Images (just tell me the TAGs) that this is implemented on here as I have both ARM and INTEL docker (Portainer) setups with multiple containers and multiple sound cards etc :-)

**Comment by ghormann** [comment]
@bakelitephone  All the builds finished (master only) if you want to verify.

**Comment by bakelitephone** [comment]
I can verify the change works fine in both "master" and "latest" TAGs both [v6.x-master-242-g734d7801 (master branch)].

FYI: For testing I used one container with a static of 192.168.1.59 and the other with an IP of 192.168.1.60, both worked fine (see below).
Obviously as you mentioned it does not yet work in any other TAG such as v5.5 (my 192.168.1.161) :-)
![E41C13C0-19A9-4E1D-B663-CFD28F2EF357](https://user-images.githubusercontent.com/69304144/166142850-7c6ddeab-7c3b-4d8e-9074-6cbae3bbc594.jpeg)

FYI: To actually get the system to successfully swap sound cards I also needed to tweak the Docker Compose file to allow the FPP containers access to the hosts dbus (/run/dbus/:/run/dbus/) as follows:

services:
  fpp1:
    container_name: fpp1
    image: falconchristmas/fpp:latest
    restart: unless-stopped
    **privileged: true**
    hostname: fpp1-docker

    devices:
      - /dev/snd:/dev/snd  # Maps all hardware sound cards regardless of hardware architecture 
      - /dev/usb:/dev/usb  # Maps all USB sound cards regardless of hardware architecture 
      - /run/dbus/:/run/dbus/ # Allows FPP to use dbus to control ALSA sound cards, needs "privileged: true"
      
      
As far as I can tell to map dbus as a device (last line above) the container needs to run as privileged (see above), however I am sure we all trust your code :-)

As this is only a Docker Compose tweak do you want me to raise this as a bug or consideration for enhancements to the devices section of the default docker compose file (for tracking), or is this thread enough to get consideration of any change ??

Regards & thanks again for all your hard work Con Blackett (European ELF)

**Comment by ghormann** [comment]
the docker-compose file is intended to be a template that is modified as needed.  I've updated it with some comments that include your learnings....

**Comment by bakelitephone** [comment]
> the docker-compose file is intended to be a template that is modified as needed. I've updated it with some comments that include your learnings....

Excellent,  I did find the template very helpful (especially the comments) when I built my own FPP compose file.

I like Docker as once I got my head around it I found it much easier than I thought it would be and it should be useful in maintaining/upgrading my own light show FPP infrastructure etc:-)

I now have loads of other containers (as well as FPP) such as Node Red, Mosquitto, NGINX reverse proxy, Dashy, Omada, FreePBX, Motioneye, InfluxDB  etc. In the past they would have all needed separate physical hardware(9 PC's) and now they all run 24*7 on one small power efficient Intel NUC :-) 

Plus if the worst happens I can rebuild the whole lot on different hardware with just a few Portainer Stacks (Docker compose)..
