### ISSUE TITLE
Update/compile fails on multi-core Pi with 512mb Ram

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#1279]
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

FPP v6 on Pi 3A+ and Pi Zero 2.   
And possibly other SBC’s with multi-core and < 1gb Ram

**Describe the bug and Steps to reproduce**: 
Some updates fail when running multi-threaded with only 512mb RAM.   Currently, the update script tries to use all cores to speed up the compile times.  But this causes some updates to fail on low memory models

**Expected behavior**: 
Updates should complete successfully on all supported models

**Additional context**: 
solution:  update the script to check if the system has < 1gb RAM and compile with only 1 core (make -j 1) instead of using multi-core

**Comment by cpinkham** [comment]
This should have been fixed in abe237482 and 9a99fd6c5.  Can this ticket be closed?

**Comment by cpinkham** [comment]
Closing as fixed since we now run fewer parallel jobs in make on systems with low memory.
