### ISSUE TITLE
FPP 6.0 Alph 4 image Hotspot teather is on even though you configued WiFi and PiZerow is handing out IPs on my home network

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1280]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP6.0 Alpha 4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Boot FPP from Alpha 4 image
Connect usb to ethernet dongle
When Pi boots up log into FPP
Configure WLAN to house network -> Save settings
Reboot
FPP comes up with Ethernet IP and Tether IP and PiZero is handing out IP addresses on 192.168.8.x network

**Expected behavior**: 
If ethernet is connected Tether should not be active
If WLAN0 is configure Tether should not be active.

**Additional context**: 
Even if I disconnect the ethernet cable, the PI is associated with the House SSID and it's handing out IPs in the 192.168.8.x range.  If you home router/dhcp server answers first you'll never notice the issue

**Additional Attachments**
![image](https://user-images.githubusercontent.com/8147459/166609690-25c27c71-7cb7-4c1a-90d6-e8bb2a83b45d.png)

**Comment by patdelaney** [comment]
Even if you disable tethering, it's still active:
![image](https://user-images.githubusercontent.com/8147459/166610227-e6a05d2c-2017-4cd9-a7d6-5bba00ba1a82.png)

**Comment by cybercop23** [comment]
@patdelaney should we be able to use dhcp server in alpha4/v6 yet? we were playing with it in the zooroom and can't seem to get it to "hand" out IPs. really curious how you set it up and how you were able to issue IPs.

**Comment by patdelaney** [comment]
@cybercop23 I believe we still need to do some more work on it, it's not done yet

**Comment by darylc** [comment]
@patdelaney What is the status of this one?

**Comment by Poporacer** [comment]
@patdelaney I haven't been able to duplicate this on 6.3 or Master. I wasn't able to test the USB to Ethernet adapter since I don't have one.
