### ISSUE TITLE
Enhancement: FPP V.6  File Copy Backup enhancements

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1283]
**Is your feature request related to a problem? Please describe.**
This is the first time I'm trying out File Copy Backup -> Backup to USB, but I have some questions about what should the expected behavior be, and then possible enhancements.

- When you stick the USB in FPP and then select backup to USB, the backup path is blank.  If you click copy you get an error "no path specified".  Should we allow no path or should we add the / by default. (note if you enter \ then try to run the backup, it fails with invalid path. So we should fix that.

- Should the Backup Path text box be a dropdown list that reads the usb and allows you to select a folder or perhaps create one.

- Unless I'm missing something, there is no way to view the contents if the USB from the FPP web ui

If Backup Path has \ then you get errors:
![image](https://user-images.githubusercontent.com/8147459/170166414-e82094f5-57c9-406f-be91-32cb82eb5888.png)

**Comment by patdelaney** [comment]
If you use the \ bit breaks fppd, but if you do another backup with a full name like the name of the fpp, after the backup fppd works again.. Weird

**Comment by cpinkham** [comment]
Browsing the USB stick would be a bit more work.  This is probably better done by plugging the stick in to the user's main computer unless we can find a simple pre-packaged solution we can add to the UI.  This commit does make the text input into a dropdown using a datalist so it shows what directories are on the USB stick.  The recommendation is to just leave the path set to the hostname of the system and that will put each system into its own directory automatically and is simple to follow and would work wherever it was plugged in without having to configure each system independently.
