### ISSUE TITLE
Add Label to Unable to Ping Output Error

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1284]
**Describe the solution you'd like**
In the error message that reads something like "Unable to ping DDP output 192.16.1.10" it would be good to also have the name included in that error if it is named.

Original: Unable to ping output 192.168.1.1
Suggestion: Unable to ping output 192.168.1.1 (WLED)
* The wording is by memory of a zoom guest I was helping.

**Comment by darylc** [comment]
Now displays like:
Cannot Ping e1.31 Channel Data Target 192.168.33.51 Bedroom
