### ISSUE TITLE
FPP 6.0 Beta 1:  Initial Wifi configuration needs reboots to make it work

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1285]
**FPP 6.0 Beta 1  PiZero-W**: 

*Pi Zero-W Test with a Monitor and keyboard attached*

Boot from imaged Fpp 6.0 Beta 1
Wait Several minutes,
Start scanning for FPP SSID with tablet,  try to connect, but we don’t get an IP
FPP Linux console appears but no IP (AP) appears on the screen
Reboot
FPP SSID appears on the tablet, and we can now connect via the tablet
Linux console UI shows 192.168.8.1 as the IP
Configure FPP from the Tablet to join home Wifi
Enter SSID and password 
Click update interface
Click Restart Network
FPP SSID disappears and is no longer broadcasting
Linux Console displays 127.0.1.1 as the connect to IP
Wait … nothing changes
Reboot
Reboot takes a long time, but PiZero W eventually connects to home Wifi and gets an IP and you can connect to it

I will test on Wifi enabled Pi3 and Pi4

**Comment by darylc** [comment]
@patdelaney these are very old v6 beta bug reports are they still valid?
