### ISSUE TITLE
Beta1: Upgrading Sometimes Reverts to 5.x

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1286]
**FPP Version and Hardware**: 
Example: FPP6 Beta1 (fppos or image) on Pi 3B

**Describe the bug and Steps to reproduce**: 
After I click up upgrade button to pull in the newest commits I've had the FPP version fall back to 5.x.  

I first ran into this on a 5.5-{current_version} that I upgraded via FPPOS then clicked update.
I've also run into this on alpha4 etch then clicking update
Currently I'm on a beta1 etch then clicked update.  Note, it did not happen the first time I did an update as I was able to get to b0cdea9 but when I upgraded to 3d801f5 it reverted to the current state.  I don't think this is related to any of these commits however.

This is what I'm currently seeing on the about page.  Note the kernel & OS version as compared to the FPP version.
![image](https://user-images.githubusercontent.com/3765696/170798472-d751338c-507f-442a-9e8a-cca94c9b4559.png)

I didn't change anything on the developer tab but I do have the developer UI enabled.

**Comment by cpinkham** [comment]
The 5.x-master is just a tag on the source repository.  The fppos images include the /opt/fpp source directory, so when you upgrade the OS via a fppos image, you can actually be downgrading FPP itself because you are installing the version of FPP which is inside the fppos image.  After upgrading via a fppos image, you should them pull in FPP updates again using the "Upgrade FPP" button.

**Comment by MrPaulAR** [comment]
That's what I did.

Today I just duplicated with the FPP-v6.0-beta1-Pi.img.zip from github.  The steps I performed.
* Reimaged a sd card
* Turn off stats, click finish setup
* Clicked version number then clicked upgrade
* This worked as after I went back to the main page I was prompted for the passwords
* Today there were more patches in 6.x so I went back on the about page and clicked upgrade again.
* Noticed the build failed this time and as expected I'm being prompted to rebuild.

This is an older Pi 3 and I haven't tried this on a 3B+ or 4.

Build log is attached
[FPP Build Log.txt.txt](https://github.com/FalconChristmas/fpp/files/8935927/FPP.Build.Log.txt.txt)
.

**Comment by MrPaulAR** [comment]
For closure the root cause of this issue has been identified.

I had the upgrade source set as another FPP instance which I was unaware of.  That other FPP instance is running 5.5 release.

This resulted in this FPP instance building based on the 5.5 release instead of the 6.x release.  Ron R noticed this when I was demoing the issue.
