### ISSUE TITLE
FPP 6.0 Beta 1: BeagleBone Green Gateway is broadcasting a SSID called BeagleBone-6F15

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1287]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 6 Beta 1 running on BBGW*

**Describe the bug and Steps to reproduce**: 
Insert fresh 6.0Beta 1 disk into BBGW and boot up.
Use a Wifi scanner app and you can see that after BBGW boots there is a new SSID that starts wit BeagleBone-xxxx
When you tried to connect to it with "Christmas" as the password it doesn't connect.

But this doesn't appear to happen on the other BBGW I have.

This may be a place holder for more information to be gathered
![image](https://user-images.githubusercontent.com/8147459/171013094-ed00710a-3919-4e58-8f72-966c1ca4d4b2.png)

**Comment by darylc** [comment]
@patdelaney these are very old v6 beta bug reports are they still valid?
