### ISSUE TITLE
FPP 6.0 Beta 1: Install of BBB Beta 1 image on BeagleBone Gateway shows  BeagleBone-6F15 on each BBGW

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1289]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
v6.x-master-335-gea212372 (master branch) on BeagleBone Gateway

**Describe the bug and Steps to reproduce**: 
Install the FPP 6.0-Beta 1 or upgrade to from 5.x with fppos
Open a device that can scan for WiFi and you can see a SSID called BeagleBone-6F15. You will see the same SSID for each BBGW that you have running.

When you try and connect and Type Christmas as the password, it does not connect.

**Expected behavior**: 
we should se an FPP ssid and be able to connect

**Additional context**: 
![image](https://user-images.githubusercontent.com/8147459/172713848-c35164a7-f78a-4c33-b64c-c895a4acfa25.png)

**Comment by darylc** [comment]
@patdelaney these are very old v6 beta bug reports are they still valid?
