### ISSUE TITLE
v6 in remote mode displays only hours

### ISSUE THREAD

**Issue by Strawberry1997** [FalconChristmas/fpp#1291]
FPP Version: | 6.x-master-335-gea212372
Platform: | BeagleBone Black
FPP OS Build: | v2022-05
OS Version: | Debian GNU/Linux 11 (bullseye)
Kernel Version: | 5.10.109-fpp

Using a second BBBv5 in player mode

The BBB is in remote mode
 In the status page the "Last Rcvd" is only in hours, it typically displays date and time
![fpp prob](https://user-images.githubusercontent.com/78796480/173710279-c2ab3cc0-ac0d-4d79-87d7-8af8ca4f2ac9.JPG)

**Comment by cpinkham** [comment]
Are those FPP instances or other E1.31 controllers?

**Comment by Strawberry1997** [comment]
These are FPP instances 
-------- Original message --------From: Chris Pinkham ***@***.***> Date: 6/16/22  9:31 PM  (GMT-05:00) To: FalconChristmas/fpp ***@***.***> Cc: Strawberry1997 ***@***.***>, Author ***@***.***> Subject: Re: [FalconChristmas/fpp] v6 in remote mode displays only hours (Issue #1291) 
Are those FPP instances or other E1.31 controllers?

**Comment by cpinkham** [comment]
Sorry, I editted that post but not sure you got the new question.  What version of FPP are they running?  That string comes from fppd which should be formatting the field.

**Comment by Strawberry1997** [comment]
![fpp prob2](https://user-images.githubusercontent.com/78796480/174449996-adb254fd-1b7e-48ed-828d-5779a5d9e8fc.JPG)

The *.201 status page is the one in question with the hours.
The other *.119 and *.113 are viewed as expected with date and time.

**Comment by cpinkham** [comment]
I did more digging. We originally showed the date/time there, but since that was less useful than the time since the last packet received, we started showing the time since in that field.  If you mouse over the hours field, you should see a tooltip pop up that has the date and time of the last packet in it.
