### ISSUE TITLE
output-UI setting

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#1296]
![FPP-SERVOFPP-output UI-Basic](https://user-images.githubusercontent.com/7828324/175059257-89508036-58da-4bd1-99e3-427ef0c5c367.jpg)
![FPP-SERVOFPP-output-UI advanced](https://user-images.githubusercontent.com/7828324/175059302-0cf9190a-01ca-4fa6-8dd3-65ae87b2bc39.jpg)

**Describe the bug and Steps to reproduce**:   Channel Output tab
in the UI Basic mode the E1.31/Artnet/DDP/Kinet don't show but if I switch to the UI advanced mode the E1.31/Artnet/DDP/Kinet tab up.
? is this normal ?
JerryPlak

**Comment by dkulp** [comment]
Yes it's normal.   It is "not normal" for users to be configuring e1.31/DDP outputs if there is a Hat installed.   Thus, it's hidden.

**Comment by JerryPlak** [comment]
Good to know....Thanks
