### ISSUE TITLE
Protections/Warnings When Attempting to Downgrade from v6 to v5

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1299]
**Is your feature request related to a problem? Please describe.**
I had one of my FPP instances configured to use another FPP instance for it's repo source (unintentional I think).  After I used FPPOS (and clean install with restore) the device would downgrade itself to v5 and fail to compile and I've been troubleshooting it since just before I opened https://github.com/FalconChristmas/fpp/issues/1286

**Describe the solution you'd like**
Few suggestions and any of them would work.

- Filter the dropdown list to prevent showing invalid sources (don't show v5 FPP on an instance running v6)
- Additional warnings informing the user they are doing a downgrade between major releases as it may not work at all

**Comment by darylc** [comment]
FPP team decided not to implement this.
