### ISSUE TITLE
FPP 6.0 Beta :  Armbian/Libre Blank Screen on Startup setting is not available 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1300]
**Is your feature request related to a problem? Please describe.**
When configuring the Libre SBC after installing Armbian and run fpp_install.sh. In the settings there is no option for Blank Screen on start up

**Describe the solution you'd like**
Is is possible to add that setting since we can probably tell it's a libre sbc
![image](https://user-images.githubusercontent.com/8147459/177416635-f7320d8c-a4e4-4f7a-b41c-f202ead03aad.png)

**Additional context**

**Comment by cpinkham** [comment]
We currently only show this setting on the Pi platform.  We might want to modify settings.json to show the setting if /dev/fb0 exists.

**Comment by darylc** [comment]
@patdelaney Does /dev/fb0 exist on libre sbc?
