### ISSUE TITLE
g++: internal compiler error: Bus error signal terminated program cc1plus

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#1301]
This from a DPLATFORM_DEBIAN  it's happens with some of the Pi and BBB!! 
g++: internal compiler error: Bus error signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make: *** [/opt/fpp/src//makefiles/fppd.mk:23: fppd.o] Error 4
make: *** Waiting for unfinished jobs....
shasum fpp-pch.h.gch > fpp-pch.h.gch.sum
----------------------
[FPP_Logs_20220710.1848.zip](https://github.com/FalconChristmas/fpp/files/9079665/FPP_Logs_20220710.1848.zip)

**Comment by JerryPlak** [comment]
this a Log from P
[FPP_Logs_20220710.1902.zip](https://github.com/FalconChristmas/fpp/files/9079685/FPP_Logs_20220710.1902.zip)
I

**Comment by andyaz** [comment]
Same error on Pi3 B this morning while running the update from the master FPP multisync page on a remote. Re-ran the upgrade from the FPP instance directly and it did not have the failure. This is one of 5 remotes that had the issue.

Sun Jul 10 14:21:38 PDT 2022
Upgrading git revision from branch master
From https://github.com/FalconChristmas/fpp
   92276fa9..7fef4225  master     -> origin/master
Updating 92276fa9..7fef4225
Fast-forward
 docs/FPP-with-vs-code.md | 8 ++++++--
 src/MultiSync.cpp        | 1 +
 2 files changed, 7 insertions(+), 2 deletions(-)
Synchronizing submodule url for 'external/RF24'
Synchronizing submodule url for 'external/rpi-rgb-led-matrix'
Synchronizing submodule url for 'external/rpi_ws281x'
Synchronizing submodule url for 'external/spixels'
Submodule path 'external/rpi-rgb-led-matrix': checked out '5e3fb5f9fdc3d1f41e21dd4f46fa6bff0218d13a'
Submodule path 'external/rpi_ws281x': checked out '1ba8e385708fb7802b09c0177a7ea4293948e25c'
Submodule path 'external/rpi-rgb-led-matrix': checked out 'a56338db0f003d5236f2ce98c73a591d64a70852'
Submodule path 'external/rpi_ws281x': checked out '9be313f77aa494036e2dc205b6ec2860e7ee988c'
Checking config version
FPP Version: 202205
Config Version: 71
Up to date at config version 71
in Clean stage
Building FPP on 'Raspberry Pi' platform
make[1]: Entering directory '/opt/fpp/external/spixels/lib'
rm -f libspixels.a ft-gpio.o dma-multi-spi.o rpi-dma.o mailbox.o direct-multi-spi.o led-strip.o
make[1]: Leaving directory '/opt/fpp/external/spixels/lib'
make[1]: Entering directory '/opt/fpp/external/RF24'
rm -rf *.o librf24-bcm.*
make[1]: Leaving directory '/opt/fpp/external/RF24'
make[1]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix'
make -C lib clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
rm -f gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o librgbmatrix.a librgbmatrix.so.1
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
make -C utils clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/utils'
rm -f led-image-viewer.o text-scroller.o led-image-viewer text-scroller video-viewer.o video-viewer
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/utils'
make -C examples-api-use clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/examples-api-use'
rm -f demo-main.o minimal-example.o c-example.o text-example.o scrolling-text-example.o clock.o ledcat.o input-example.o pixel-mover.o demo minimal-example c-example text-example scrolling-text-example clock ledcat input-example pixel-mover
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/bindings/python'
python setup.py clean --all
running clean
'build/lib.linux-armv7l-3.9' does not exist -- can't clean it
'build/bdist.linux-armv7l' does not exist -- can't clean it
'build/scripts-3.9' does not exist -- can't clean it
find ./rgbmatrix -type f -name \*.so -delete
find . -type f -name \*.pyc -delete
rm -f build-* install-* test-*
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/bindings/python'
make[1]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix'
rm -f fppversion.c fppversion_defines.h fpp.o common.o log.o fppversion.o channeloutput/ChannelOutput.o channeloutput/ThreadedChannelOutput.o channeloutput/ChannelOutputSetup.o channeloutput/channeloutputthread.o channeloutput/ColorOrder.o channeloutput/FPD.o channeloutput/Matrix.o channeloutput/PanelMatrix.o channeloutput/PixelString.o channeloutput/serialutil.o channeloutput/VirtualDisplayBase.o channeloutput/processors/OutputProcessor.o channeloutput/processors/RemapOutputProcessor.o channeloutput/processors/HoldValueOutputProcessor.o channeloutput/processors/SetValueOutputProcessor.o channeloutput/processors/BrightnessOutputProcessor.o channeloutput/processors/ColorOrderOutputProcessor.o channeloutput/processors/ThreeToFourOutputProcessor.o channeloutput/processors/OverrideZeroOutputProcessor.o channeltester/ChannelTester.o channeltester/OutputTester.o channeltester/TestPatternBase.o channeltester/RGBChase.o channeltester/RGBCycle.o channeltester/RGBFill.o channeltester/SingleChase.o command.o commands/Commands.o commands/PlaylistCommands.o commands/EventCommands.o commands/MediaCommands.o common.o e131bridge.o effects.o falcon.o fppversion.o FrameBuffer.o fseq/FSEQFile.o gpio.o httpAPI.o log.o FPPLocale.o MultiSync.o mediadetails.o mediaoutput/MediaOutputBase.o mediaoutput/mediaoutput.o mediaoutput/SDLOut.o mediaoutput/VLCOut.o mqtt.o NetworkController.o NetworkMonitor.o ping.o Player.o overlays/PixelOverlay.o overlays/PixelOverlayEffects.o overlays/PixelOverlayModel.o overlays/PixelOverlayModelFB.o overlays/PixelOverlayModelSub.o overlays/WLEDEffects.o overlays/wled/FX.o overlays/wled/FX_fcn.o overlays/wled/colorpalettes.o overlays/wled/colorutils.o overlays/wled/noise.o overlays/wled/hsv2rgb.o playlist/Playlist.o playlist/PlaylistEntryBase.o playlist/PlaylistEntryBoth.o playlist/PlaylistEntryBranch.o playlist/PlaylistEntryCommand.o playlist/PlaylistEntryDynamic.o playlist/PlaylistEntryEffect.o playlist/PlaylistEntryImage.o playlist/PlaylistEntryMedia.o playlist/PlaylistEntryPause.o playlist/PlaylistEntryPlaylist.o playlist/PlaylistEntryPlugin.o playlist/PlaylistEntryRemap.o playlist/PlaylistEntryScript.o playlist/PlaylistEntrySequence.o playlist/PlaylistEntryURL.o Plugins.o Scheduler.o ScheduleEntry.o scripts.o sensors/Sensors.o Sequence.o settings.o SunRise.o Warnings.o util/GPIOUtils.o util/I2CUtils.o util/SPIUtils.o util/tinyexpr.o util/ExpressionProcessor.o util/TmpFileGPIO.o  non-gpl/CapeUtils/fppcapedetect.o non-gpl/CapeUtils/CapeUtils.o fppd.o common.o log.o fppmm.o fppversion.o util/SPIUtils.o common.o log.o settings.o fppversion.o oled/I2C.o oled/SSD1306_OLED.o oled/FPPOLEDUtils.o oled/OLEDPages.o oled/FPPStatusOLEDPage.o oled/NetworkOLEDPage.o oled/FPPMainMenu.o oled/fppoled.o oled/SSD1306DisplayDriver.o oled/I2C1602_2004_DisplayDriver.o util/GPIOUtils.o util/TmpFileGPIO.o  common.o fppversion.o log.o Warnings.o fseq/FSEQUtils.o fseq/FSEQFile.o channeloutput/ColorLight-5a-75.o non-gpl/DPIPixels/DPIPixels.o channeloutput/DebugOutput.o channeloutput/FBMatrix.o channeloutput/GPIO595.o channeloutput/GPIO.o channeloutput/GenericSPI.o channeloutput/GenericSerial.o channeloutput/GenericUDPOutput.o channeloutput/HTTPVirtualDisplay.o channeloutput/ILI9488.o channeloutput/LOR.o channeloutput/LOREnhanced.o channeloutput/Linsn-RV9.o channeloutput/MAX7219Matrix.o channeloutput/MCP23017.o channeloutput/MQTTOutput.o channeloutput/ModelPixelStrings.o channeloutput/PCA9685.o channeloutput/RGBMatrix.o channeloutput/rpi_ws281x.o channeloutput/USBRenard.o channeloutput/SPInRF24L01.o channeloutput/SPIws2801.o channeloutput/USBDMX.o channeloutput/USBPixelnet.o channeloutput/USBRelay.o channeloutput/VirtualDisplay.o channeloutput/X11Matrix.o channeloutput/X11PanelMatrix.o channeloutput/spixels.o channeloutput/UDPOutput.o  channeloutput/DDP.o channeloutput/E131.o channeloutput/ArtNet.o channeloutput/KiNet.o channeloutput/Twinkly.o util/PiGPIOUtils.o util/PiFaceUtils.o util/MCP23x17Utils.o util/bcm2835.o fpp libfpp.so fppcapedetect libfpp_capeutils.so fppd fppmm fppoled fsequtils libfpp-co-matrix-ColorLight5a75.so libfpp-co-DPIPixels.so libfpp-co-Debug.so libfpp-co-FBMatrix.so libfpp-co-GPIO-595.so libfpp-co-GPIO.so libfpp-co-GenericSPI.so libfpp-co-GenericSerial.so libfpp-co-GenericUDP.so libfpp-co-HTTPVirtualDisplay.so libfpp-co-ILI9488.so libfpp-co-LOR.so libfpp-co-LOREnhanced.so libfpp-co-matrix-LinsnRV9.so libfpp-co-MAX7219Matrix.so libfpp-co-MCP23017.so libfpp-co-MQTTOutput.so libfpp-co-ModelPixelStrings.so libfpp-co-PCA9685.so libfpp-co-matrix-RGBMatrix.so libfpp-co-RPIWS281X.so libfpp-co-Renard.so libfpp-co-SPI-nRF24L01.so libfpp-co-SPIws2801.so libfpp-co-USBDMX.so libfpp-co-USBPixelnet.so libfpp-co-USBRelay.so libfpp-co-VirtualDisplay.so libfpp-co-X11Matrix.so libfpp-co-matrix-X11PanelMatrix.so libfpp-co-spixels.so libfpp-co-UDPOutput.so libfpp-pi-gpio.so ../www/fppversion.php ../www/fppdefines.php fpp-pch.h.gch fpp-pch.h.gch.sum
Set cache size limit to 350.0 MB
Building FPP on 'Raspberry Pi' platform
make[1]: Entering directory '/opt/fpp/external/RF24'
rm -rf *.o librf24-bcm.*
make[1]: Leaving directory '/opt/fpp/external/RF24'
make[1]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix'
make -C lib clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
rm -f gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o librgbmatrix.a librgbmatrix.so.1
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
make -C utils clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/utils'
rm -f led-image-viewer.o text-scroller.o led-image-viewer text-scroller video-viewer.o video-viewer
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/utils'
make -C examples-api-use clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/examples-api-use'
rm -f demo-main.o minimal-example.o c-example.o text-example.o scrolling-text-example.o clock.o ledcat.o input-example.o pixel-mover.o demo minimal-example c-example text-example scrolling-text-example clock ledcat input-example pixel-mover
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python clean
make[2]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/bindings/python'
python setup.py clean --all
running clean
'build/lib.linux-armv7l-3.9' does not exist -- can't clean it
'build/bdist.linux-armv7l' does not exist -- can't clean it
'build/scripts-3.9' does not exist -- can't clean it
find ./rgbmatrix -type f -name \*.so -delete
find . -type f -name \*.pyc -delete
rm -f build-* install-* test-*
make[2]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/bindings/python'
make[1]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix'
rm -f fppversion.c fppversion_defines.h non-gpl/CapeUtils/fppcapedetect.o non-gpl/CapeUtils/CapeUtils.o fppd.o fpp.o common.o log.o fppversion.o common.o log.o fppmm.o fppversion.o util/SPIUtils.o common.o log.o settings.o fppversion.o oled/I2C.o oled/SSD1306_OLED.o oled/FPPOLEDUtils.o oled/OLEDPages.o oled/FPPStatusOLEDPage.o oled/NetworkOLEDPage.o oled/FPPMainMenu.o oled/fppoled.o oled/SSD1306DisplayDriver.o oled/I2C1602_2004_DisplayDriver.o util/GPIOUtils.o util/TmpFileGPIO.o  channeloutput/ChannelOutput.o channeloutput/ThreadedChannelOutput.o channeloutput/ChannelOutputSetup.o channeloutput/channeloutputthread.o channeloutput/ColorOrder.o channeloutput/FPD.o channeloutput/Matrix.o channeloutput/PanelMatrix.o channeloutput/PixelString.o channeloutput/serialutil.o channeloutput/VirtualDisplayBase.o channeloutput/processors/OutputProcessor.o channeloutput/processors/RemapOutputProcessor.o channeloutput/processors/HoldValueOutputProcessor.o channeloutput/processors/SetValueOutputProcessor.o channeloutput/processors/BrightnessOutputProcessor.o channeloutput/processors/ColorOrderOutputProcessor.o channeloutput/processors/ThreeToFourOutputProcessor.o channeloutput/processors/OverrideZeroOutputProcessor.o channeltester/ChannelTester.o channeltester/OutputTester.o channeltester/TestPatternBase.o channeltester/RGBChase.o channeltester/RGBCycle.o channeltester/RGBFill.o channeltester/SingleChase.o command.o commands/Commands.o commands/PlaylistCommands.o commands/EventCommands.o commands/MediaCommands.o common.o e131bridge.o effects.o falcon.o fppversion.o FrameBuffer.o fseq/FSEQFile.o gpio.o httpAPI.o log.o FPPLocale.o MultiSync.o mediadetails.o mediaoutput/MediaOutputBase.o mediaoutput/mediaoutput.o mediaoutput/SDLOut.o mediaoutput/VLCOut.o mqtt.o NetworkController.o NetworkMonitor.o ping.o Player.o overlays/PixelOverlay.o overlays/PixelOverlayEffects.o overlays/PixelOverlayModel.o overlays/PixelOverlayModelFB.o overlays/PixelOverlayModelSub.o overlays/WLEDEffects.o overlays/wled/FX.o overlays/wled/FX_fcn.o overlays/wled/colorpalettes.o overlays/wled/colorutils.o overlays/wled/noise.o overlays/wled/hsv2rgb.o playlist/Playlist.o playlist/PlaylistEntryBase.o playlist/PlaylistEntryBoth.o playlist/PlaylistEntryBranch.o playlist/PlaylistEntryCommand.o playlist/PlaylistEntryDynamic.o playlist/PlaylistEntryEffect.o playlist/PlaylistEntryImage.o playlist/PlaylistEntryMedia.o playlist/PlaylistEntryPause.o playlist/PlaylistEntryPlaylist.o playlist/PlaylistEntryPlugin.o playlist/PlaylistEntryRemap.o playlist/PlaylistEntryScript.o playlist/PlaylistEntrySequence.o playlist/PlaylistEntryURL.o Plugins.o Scheduler.o ScheduleEntry.o scripts.o sensors/Sensors.o Sequence.o settings.o SunRise.o Warnings.o util/GPIOUtils.o util/I2CUtils.o util/SPIUtils.o util/tinyexpr.o util/ExpressionProcessor.o util/TmpFileGPIO.o  common.o fppversion.o log.o Warnings.o fseq/FSEQUtils.o fseq/FSEQFile.o channeloutput/ColorLight-5a-75.o channeloutput/DebugOutput.o non-gpl/DPIPixels/DPIPixels.o channeloutput/FBMatrix.o channeloutput/GenericSerial.o channeloutput/GenericSPI.o channeloutput/GenericUDPOutput.o channeloutput/GPIO595.o channeloutput/GPIO.o channeloutput/HTTPVirtualDisplay.o channeloutput/ILI9488.o channeloutput/Linsn-RV9.o channeloutput/LOREnhanced.o channeloutput/LOR.o channeloutput/MAX7219Matrix.o channeloutput/MCP23017.o channeloutput/ModelPixelStrings.o channeloutput/MQTTOutput.o channeloutput/PCA9685.o channeloutput/USBRenard.o channeloutput/RGBMatrix.o channeloutput/rpi_ws281x.o channeloutput/SPInRF24L01.o channeloutput/SPIws2801.o channeloutput/spixels.o channeloutput/UDPOutput.o  channeloutput/DDP.o channeloutput/E131.o channeloutput/ArtNet.o channeloutput/KiNet.o channeloutput/Twinkly.o channeloutput/USBDMX.o channeloutput/USBPixelnet.o channeloutput/USBRelay.o channeloutput/VirtualDisplay.o channeloutput/X11Matrix.o channeloutput/X11PanelMatrix.o util/PiGPIOUtils.o util/PiFaceUtils.o util/MCP23x17Utils.o util/bcm2835.o fppcapedetect libfpp_capeutils.so fppd fpp fppmm fppoled libfpp.so fsequtils libfpp-co-matrix-ColorLight5a75.so libfpp-co-Debug.so libfpp-co-DPIPixels.so libfpp-co-FBMatrix.so libfpp-co-GenericSerial.so libfpp-co-GenericSPI.so libfpp-co-GenericUDP.so libfpp-co-GPIO-595.so libfpp-co-GPIO.so libfpp-co-HTTPVirtualDisplay.so libfpp-co-ILI9488.so libfpp-co-matrix-LinsnRV9.so libfpp-co-LOREnhanced.so libfpp-co-LOR.so libfpp-co-MAX7219Matrix.so libfpp-co-MCP23017.so libfpp-co-ModelPixelStrings.so libfpp-co-MQTTOutput.so libfpp-co-PCA9685.so libfpp-co-Renard.so libfpp-co-matrix-RGBMatrix.so libfpp-co-RPIWS281X.so libfpp-co-SPI-nRF24L01.so libfpp-co-SPIws2801.so libfpp-co-spixels.so libfpp-co-UDPOutput.so libfpp-co-USBDMX.so libfpp-co-USBPixelnet.so libfpp-co-USBRelay.so libfpp-co-VirtualDisplay.so libfpp-co-X11Matrix.so libfpp-co-matrix-X11PanelMatrix.so libfpp-pi-gpio.so ../www/fppversion.php ../www/fppdefines.php fpp-pch.h.gch fpp-pch.h.gch.sum
Building FPP on 'Raspberry Pi' platform
CCACHE_NOHARDLINK=true CCACHE_COMPRESS=true ccache g++ -fpch-preprocess -O3 -Wno-psabi -pipe -I /opt/fpp/src/ -fpic -DPLATFORM_PI -std=gnu++2a  -c /opt/fpp/src/fpp-pch.h -o fpp-pch.h.gch
sh /opt/fpp/src/fppversion.sh /opt/fpp/src
Building rpi-rgb-led-matrix library
make[1]: Entering directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o gpio.o gpio.cc
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix.o led-matrix.cc
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o options-initialize.o options-initialize.cc
Synchronizing submodule url for 'external/RF24'
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o framebuffer.o framebuffer.cc
php fppdefines.php > ../www/fppdefines.php
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o thread.o thread.cc
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o bdf-font.o bdf-font.cc
Synchronizing submodule url for 'external/rpi-rgb-led-matrix'
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o graphics.o graphics.cc
chmod 664 ../www/fppdefines.php
Building libws2811
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix-c.o led-matrix-c.cc
Synchronizing submodule url for 'external/rpi_ws281x'
ccache gcc  -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -c -o hardware-mapping.o hardware-mapping.c
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o pixel-mapper.o pixel-mapper.cc
Synchronizing submodule url for 'external/spixels'
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o multiplex-mappers.o multiplex-mappers.cc
ccache g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o content-streamer.o content-streamer.cc
Entering 'external/RF24'
ar rcs librgbmatrix.a gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o
make[1]: Leaving directory '/opt/fpp/external/rpi-rgb-led-matrix/lib'
Building RF24 library
make[1]: Entering directory '/opt/fpp/external/RF24'
ccache g++ -Wall -fPIC -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -c RF24.cpp
RF24.cpp: In member function ‘bool RF24::isAckPayloadAvailable()’:
RF24.cpp:1379:10: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
 1379 |   return ! read_register(FIFO_STATUS) & _BV(RX_EMPTY);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
ccache gcc -Wall -fPIC -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -c RPi/bcm2835.c
RPi/bcm2835.c: In function ‘bcm2835_peri_read’:
RPi/bcm2835.c:119:2: warning: statement with no effect [-Wunused-value]
  119 |  *paddr; // Read without assigneing to an unused variable
      |  ^~~~~~
RPi/bcm2835.c: In function ‘bcm2835_init’:
RPi/bcm2835.c:1288:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 1288 |     if (!ok)
      |     ^~
RPi/bcm2835.c:1291:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 1291 |  gettimeofday (&tv, NULL) ;
      |  ^~~~~~~~~~~~
ccache g++ -shared -Wl,-soname,librf24-bcm.so.1 -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -o librf24-bcm.so.1.0 RF24.o bcm2835.o
make[1]: Leaving directory '/opt/fpp/external/RF24'
Building spixels library
make[1]: Entering directory '/opt/fpp/external/spixels/lib'
ccache g++ -Wall -O3 -I../include -I.  -I../include -I. -c -o ft-gpio.o ft-gpio.cc
ccache g++ -Wall -O3 -I../include -I.  -I../include -I. -c -o dma-multi-spi.o dma-multi-spi.cc
ccache gcc -Wall -O3 -I../include -I.  -c -o rpi-dma.o rpi-dma.c
ccache gcc -Wall -O3 -I../include -I.  -c -o mailbox.o mailbox.c
ccache g++ -Wall -O3 -I../include -I.  -I../include -I. -c -o direct-multi-spi.o direct-multi-spi.cc
ccache g++ -Wall -O3 -I../include -I.  -I../include -I. -c -o led-strip.o led-strip.cc
ar rcs libspixels.a ft-gpio.o dma-multi-spi.o rpi-dma.o mailbox.o direct-multi-spi.o led-strip.o
make[1]: Leaving directory '/opt/fpp/external/spixels/lib'
ccache g++ -fpch-preprocess -O3 -Wno-psabi -pipe -I /opt/fpp/src/ -fpic -DPLATFORM_PI -std=gnu++2a  -DGPIOD_CHIPS=3 -c /opt/fpp/src/fppd.cpp -o fppd.o
Entering 'external/rpi-rgb-led-matrix'

g++: internal compiler error: Bus error signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make: *** [/opt/fpp/src//makefiles/fppd.mk:23: fppd.o] Error 4
make: *** Waiting for unfinished jobs....
shasum fpp-pch.h.gch > fpp-pch.h.gch.sum
Entering 'external/rpi_ws281x'
Entering 'external/spixels'

**Comment by andyaz** [comment]
Saw this again today on all 5 FPP instances when updating. Had to reboot and then rebuild to get FPPD back again. Logs from my master FPP attached.
Version Info
FPP Version: | 6.x-master-476-gdf5b17c3
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v2022-05
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 0000000090a476ea
Kernel Version: | 5.15.32-v7+

Mon Jul 11 22:30:17 PDT 2022
Upgrading git revision from branch master
Updating 7fef4225..df5b17c3
...
ccache g++ -fpch-preprocess -O3 -Wno-psabi -pipe -I /opt/fpp/src/ -fpic -DPLATFORM_PI -std=gnu++2a  -DGPIOD_CHIPS=3 -c /opt/fpp/src/fppd.cpp -o fppd.o

g++: internal compiler error: Bus error signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make: *** [/opt/fpp/src//makefiles/fppd.mk:23: fppd.o] Error 4
make: *** Waiting for unfinished jobs....
[FPP_Logs_20220712.0548.zip](https://github.com/FalconChristmas/fpp/files/9089844/FPP_Logs_20220712.0548.zip)
.

**Comment by andyaz** [comment]
Happened again on 476 to 480 today. Master I tried to do upgrade and it had the error. rebooted and rebuilt FPPD to recover successfully. On the other 4 I rebooted first, then upgraded and they all worked properly.

**Comment by JerryPlak** [comment]
Adding to the comments..
Did some testing today and found out if I revert back to Local Git Version:075049e
there is no error on the pi or BBB device was able to do today's update accept one Pi.

On the Debian device I am suck at Version:075049e without error.

Yesterday I did a Debian & FPP_Install.sh  install was able to update it to Version df5b17c3 Last Night last night, I have not tried any updates today!!

**Comment by cpinkham** [comment]
Are you running the latest Beta1 release of the SD image or are you on an older version?  Dan added some logic to configure zramswap which should have fixed that issue.  I was able to reproduce the issue on an older SD image, but not on a system with zramswap configured.  FPP's build scripts normally run one job per CPU core.  The quad-core 1GB systems can run out of memory while compiling 4 jobs at once, but using zramswap seems to have fixed the issue.

**Comment by andyaz** [comment]
I did an fppos upgrade to 6.0 beta 1 on all the fpps and update from git. I updated today after a reboot. I will see with the next update what happens. I agree the gcc error is a memory or swap issue from my research.

Andy Hansis

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andyaz** [comment]
Updated today from 490 to 497 with no compile errors on all 5 FPP without having to reboot.

**Comment by JerryPlak** [comment]
I've been keeping low key lately.

On Monday I prepared another debinan computer and was able to run the FPP Install Script and updates without any issues.

On Tuesday I tried doing the FPP updates everything was fine for the BBB & PB, pi2b & Pi4  but on a Pi3B I ended up having to reimage then it's updates..

on one debinan computer I ended up deleting the falcon profile and all of his data than reinstall FPP Install Script and updates 

Everything  is back up and running 	v6.x-master-497-gb3027120 Git Version:  b302712 at this time...


Going to leave it up to the destruction of the programmers if they want to close this case

Thanks for the hard work

**Comment by andyaz** [comment]
Updated again today with no issues. I believe this is resolved.
