### ISSUE TITLE
Changes to ./FPP_Install.sh (master)

### ISSUE THREAD

**Issue by corfoto4** [FalconChristmas/fpp#1302]
After installing Ubuntu onto a fresh system, some terminal packages that were needed by the script _./FPP_Install.sh_ were not already installed.

Improvement suggestion:
Add these commands to the script under the title "Pre-Processing":
`apt update`
`apt install git`
`apt install apache2`
`apt install ccache`
`apt install zlib1g`
`apt install gettext`
`apt install flex`
`apt install make`
`apt install bison`
`apt install zlib1g-dev`
`apt install gettext libgettextpo-dev`
`apt install build-essential`
`apt install autopoint`
`apt install mosquitto`
`apt install autoconf`
`apt install libtool`
`apt install php`
`apt install livemedia-utils`
`apt install libarchive-tools`

`git config --global user.name "FIRST_NAME LAST_NAME"`
`git config --global user.email "MY_NAME@example.com"`

**Comment by dkulp** [comment]
Most likely all that needs to be done is line 348 of FPP_Install.sh needs updating for whatever string is found in /etc/os-release . Can you copy the contents of  /etc/os-release here so I can see what it should be?

**Comment by corfoto4** [comment]
I do apologise, this issue can be closed. I was attempting to run this software on Ubuntu instead of a Debian release.

If possible, could this please be added to the README or in the comments part of the script to make it more clear?
Thanks.
