### ISSUE TITLE
FPP configuration backup json file empty

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1304]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
[v6.x-master-475-g7c7c77c4 (master branch)](http://testpi2/about.php)
PI 3b+

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
goto fpp backup.. On the configuration back tab, select all for the backup area, and select download configuration.  Save the json file that get's downloaded.  Observe the json file and it is zero bytes and an empty file.   Then select a specific backup area such as channel ouputs and download that configuration.  the file contains the data that it should.. Just the "All" selection downloads an empty file. 

**Expected behavior**: 
I would expect a complete json file with all the selected setting information contained in it. 

**Additional Attachments**

![image](https://user-images.githubusercontent.com/88390168/178386481-048dcf45-b448-44d3-accb-6f3b294602a0.png)
[FPP_Logs_20220712.0106.zip](https://github.com/FalconChristmas/fpp/files/9088553/FPP_Logs_20220712.0106.zip)

**Comment by cpinkham** [comment]
This was fixed in df5b17c37 about a half hour after the ticket was opened.
