### ISSUE TITLE
Submit FPP for inclusion in Raspberry Pi rpi-imager OS list

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#1308]
Details in the following:

https://falconchristmas.com/forum/index.php?topic=15179.msg126100#msg126100

https://github.com/raspberrypi/rpi-imager/issues/462
https://github.com/raspberrypi/rpi-imager/issues/461
https://github.com/raspberrypi/rpi-imager/issues?q=is%3Aissue+label%3A%22OS+request%22

We'll need to provide some JSON for the main list entry, our own JSON file with list of version images and their details, and the actual SD images in .img.xz form.

Possibly add an entry in the JSON for latest FPP v5.x entry as well.

**Comment by cpinkham** [comment]
Once we've given the released SD images a little longer to burn in, I'll look at submitting for inclusion.

**Comment by cybercop23** [comment]
Hi Chris. As we're getting closer to show times, this would be invaluable.
Since RPiImager can also burn BBB images we should also include that (but maybe after the initial review of the Json file in case the developers have beef with that).

**Comment by darylc** [comment]
submitted for inclusion, hopefully they will accept it.

**Comment by darylc** [comment]
It's been submitted, they aren't asking us any questions but are also not hurrying to add it, nothing more to be done at our end.

**Comment by darylc** [comment]
https://github.com/FalconChristmas/fpp/issues/ 1308

**Comment by darylc** [comment]
https://github.com/raspberrypi/rpi-imager/issues/ 548

**Comment by cybercop23** [comment]
Arggg.. that's right.. you do it by switching branch in GUI. With the new K8s and need-ing master.... is it worth having a weekly or monthly image available to make the install easier and then users can upgrade in-place to the latest?

**Comment by dkulp** [comment]
There are a couple more things we kind of need to do and then I hope to have "alpha" images created.   Not sure exactly when yet.

**Comment by darylc** [comment]
IMHO only release versions should show in the imager, I do intend to add Beaglebone images though.
