### ISSUE TITLE
Compile Errors on Pi3b & Pi3b+

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1309]
**FPP Version and Hardware**: 
Example: Pi3b running FPP 6.x-485 (earlier builds too)

**Describe the bug and Steps to reproduce**: 
I'm getting compilation errors fairly routinely on 2 Pis (3b & 3b+) when upgrading via multisync on the master.  Sometimes I can just click the rebuild FPP button and after a few tries it self remedies.  The last 2 times I was able to recover by applying the fppos and then upgrading.

The steps to trigger the issue have been as follow
From the master FPP instance use multicsync to upgrade all my devices.

- Status/control > Multisync
- Check all instances (Pi & BB based)
- Action > Upgrade FPP
- Run

**Additional Attachments**
[FPP_Logs_20220720.1448.zip](https://github.com/FalconChristmas/fpp/files/9150899/FPP_Logs_20220720.1448.zip)

**Comment by cpinkham** [comment]
Are you running the latest Beta1 release of the SD image or are you on an older version?  Dan added some logic to configure zramswap which should have fixed that issue.  I was able to reproduce the issue on an older SD image, but not on a system with zramswap configured.  FPP's build scripts normally run one job per CPU core.  The quad-core 1GB systems can run out of memory while compiling 4 jobs at once, but using zramswap seems to have fixed the issue.

**Comment by MrPaulAR** [comment]
I thought I was on the 2nd beta1 image. Can I look at a makefile, some
environmental variables, or somewhere else to see the build flags?

**Comment by cpinkham** [comment]
I believe this issue was fixed by an update to the build process prior to the v6.0 release.  If this is no longer an issue, can you please close the ticket.

**Comment by MrPaulAR** [comment]
Haven't had any compile issues since I opened the ticket.
