### ISSUE TITLE
Include vendor logo on EEPROM so non net-connected devices can display

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1312]
**Is your feature request related to a problem? Please describe.**
If a fpp instance isn't connected to internet it can't get the vendor image to display in top right of UI

**Describe the solution you'd like**
Be able to store logo on the cape EEPROM (or at least cache the logo from when device last had a net connection) so vendor logo for installed Cape is always displayed

**Comment by cpinkham** [comment]
A 32KB EEPROM isn't big enough to hold much of an image.  We can look at caching the file locally.

**Comment by OnlineDynamic** [comment]
Agree that's probably the best option... I actually use bigger eeproms but guess others will have more of a space issue

**Comment by dkulp** [comment]
It really doesn't matter what size you use, we mount the eeprom as a 24c256 which would limit it to reading only the first 32K.
