### ISSUE TITLE
Raspberry Pi Zero 2 not included in platform filter on Multisync page.

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1315]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP [v6.x-master-507-g7737c52c (master branch)] running on Raspberry pi zero2w. 

**Describe the bug and Steps to reproduce**: 
When on the multisync page, and using the platform filter for FPP (Raspberry PI), the pi zero2 w is not included in the results.   The model description under /sys/firmware/devicetree/base/model is " Raspberry Pi Zero 2 W Rev 1.0 ". 

**Expected behavior**: 
I would expect the filtered list to contain all PI model types including Pi Zero2 w

**Comment by computergeek1507** [comment]
fixed with fc4b300e8f23789bbe57305a59a43d2e13e38525
