### ISSUE TITLE
Display testing issues

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1316]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 

FPP 6.0 master-507

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

2 Issues related to Display Testing

The FPP Command for Display Testing has a dropdown for "Channel Range/Model:" but it doesn't populate with the Pixel Overlay models saved on the device (Manually and Automatic entries).

From the Display Testing page in FPP, if you select the Multisync option, the Remotes don't test. (Running an FPP Command from the same FPP works)

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by computergeek1507** [comment]
the model dropdown work as expected for me
![image](https://user-images.githubusercontent.com/2293065/181129819-63b721fd-3a00-4fce-b9c7-9cee755a1733.png)

**Comment by Poporacer** [comment]
@computergeek1507 The first issue references the FPP Command for Testing
![image](https://user-images.githubusercontent.com/46263877/181130647-de1a9d0e-c92b-4718-b712-669e02bcaca7.png)

**Comment by yxeGithub** [comment]
I have the same issue as the original poster - here are the details:

If I delete a model from my outputs (via xlights in my configuration) it removes it from the outputs for my k32A/B.
When I go to Status Control / Display Testing - the model still shows in the drop down list.

So either have a way to clear the Display Model history (if it is cached) or have it reload the display models to show only what is in the outputs section.

Outputs does not have the 4ft tree in it, but display testing still shows it.
![4ftTree](https://user-images.githubusercontent.com/20427930/208716648-1100c8d3-b3a8-4b1f-87be-3ec22722f94a.jpg)
![4fttreemissing](https://user-images.githubusercontent.com/20427930/208717208-a1d20c87-cc88-4314-b261-c0eb35db8efc.jpg)
[FPP_Logs_20221220.1629.zip](https://github.com/FalconChristmas/fpp/files/10270289/FPP_Logs_20221220.1629.zip)

**Comment by darylc** [comment]
@yxeGithub That is because you still have it configured in your pixel overlay models.  Input/Output Setup->Pixel Overlay Models

xLights automatically populates that if you tell it to in fpp connect.

**Comment by yxeGithub** [comment]
> @yxeGithub That is because you still have it configured in your pixel overlay models. Input/Output Setup->Pixel Overlay Models
> 
> xLights automatically populates that if you tell it to in fpp connect.

You are 100% correct - I need to learn about these overlay models - this has been bugging me for a while - thanks you so much.

**Comment by darylc** [comment]
@Poporacer Took many hours and the change is ridiculously simple, but I sorted out #1.

Do you know if #2 "From the Display Testing page in FPP, if you select the Multisync option, the Remotes don't test. (Running an FPP Command from the same FPP works)" is still broken?

**Comment by Poporacer** [comment]
#2 was fixed a while ago! Thanks
