### ISSUE TITLE
K8-B Scroller not outputting to lights after fresh 6.0 install

### ISSUE THREAD

**Issue by MDickson00** [FalconChristmas/fpp#1318]
FPP 6.01 on Kulp K8-B Scroller

We encoutered this issue in the Zoom Room today.

K8-B Scroller would not output to lights via test mode, or via output to lights from xlights. User stated that lights worked fine prior to upgrading from 5.5. User upgraded to 6.0 via a fresh install from an etched SD card.

Troubleshooting steps taken:
Tested lights with portable pixel tester, all test fine. Had user swap ports, cloned strings to include 50 pixels on all ports, tested from display testing, tested from the new pattern testing button, also played sequence from status page, and tried output to lights from xlights.

Resolution:
User used a spare SD card to etch and re-install 5.5, all lights test and work as expected now.

We had the user set his logs to debug and zip them for us, I will include this zip file in this post, user also kept the SD card with the 6.0 install should any more testing be recommended.

Additional notes:
This did not appear to be an eeprom issue as it recognized the cape.

[FPP_Logs_20220729.1908.zip](https://github.com/FalconChristmas/fpp/files/9222876/FPP_Logs_20220729.1908.zip)

**Comment by cpinkham** [comment]
The LED Panel output is not enabled according to the config/channeloutputs.json file included in the attached zip file.  Try enabling the LED Panel output on the Channel Outputs config page.

**Comment by MDickson00** [comment]
Chris I should have been more particular, it would not output to the pixel
ports. There was not an LED screen attached.

**Comment by cpinkham** [comment]
OK, thanks, I'll take another look.

**Comment by TheOneCalledScott** [comment]
Thanks Chris.  I moved back to 5.5 but have saved the 6.0 SD card so we can
do some live troubleshooting if needed.

**Comment by darylc** [comment]
@TheOneCalledScott Is still a problem in FPP 6.3?

**Comment by TheOneCalledScott** [comment]
@darylc, sorry, I neglected to close the loop on this one.  When 6.2 came out I did a fresh install with that and it worked.  Not sure if something between 6.0 and 6.2 fixed it or maybe it was unquiet to me, but I ran with 6.2 all Christmas without issue.  Things are packed away now but if 6.2 worked I'd assume 6.3 would be fine.

Thanks for following up.
