### ISSUE TITLE
Audio/Video Settings tab no outputs listed

### ISSUE THREAD

**Issue by MartyW-1** [FalconChristmas/fpp#1319]
Under FPP settings, and the Audio/Video tab, it has all blank boxes for the output devices.  I have a Soundblaster 3 and its not coming up nor are any of the usual default features. I have attached a screenshot.  This was a brand new install oin a brand new SD card
![Capture](https://user-images.githubusercontent.com/78752614/182036533-abfd36cb-768f-4f47-a25e-aadf2b1f8f87.PNG)
.

**Comment by dkulp** [comment]
I'd be interested to know what "aplay -L" and "aplay -l" output.

**Comment by MartyW-1** [comment]
How do I get those for you ?

**Comment by MartyW-1** [comment]
Hi Daniel 

 

Here you go, I cant see aplay-L in the output list

 

Sound Cards:    sudo aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 4/4

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835

IEC958/HDMI1]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 1: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]

  Subdevices: 3/3

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

card 2: S3 [Sound Blaster Play! 3], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

**Comment by MartyW-1** [comment]
I done the 6.0.1 upgrade and rebooted it and its working now

**Comment by bakelitephone** [comment]
I have exactly the same issue on all versions of v6. It appears to be related to UI password. Basically if you have UI password **enabled** you get blank Audio/Visual options (as already mentioned) (see screenshot below)

![D0B935B2-CE72-4542-9A46-420452E27C63_1_105_c](https://user-images.githubusercontent.com/69304144/183264454-394f63a8-2fac-4ea1-a4da-68637f6dc43c.jpeg)

If you then disable UI Password in FPP settings > UI : (the options magically reappear)

![4DBDA6F2-2A69-4B9E-8A0F-11047D5CDF7E_1_105_c](https://user-images.githubusercontent.com/69304144/183264544-51556e02-5972-491c-81f7-76faad33ec9c.jpeg)

You can repeat this by enabling and disabling UI Password as often as you want.

It is the same problem in all v6 releases (v6.0-beta1, v6.0, v6.0.1 and v6.0.2) both on Raspberry PI & in Docker containers

Hope this helps the developers find this, or the work around is OK for other people who have this problem
