### ISSUE TITLE
Create SSD copy script to take a running FPP image and copy to /dev/sda

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#1321]
FPP can easily run off a USB attached SSD drive on a Pi after modifying only 2 files: /boot/cmdline.txt to change the root= setting and /etc/fstab to change the device entries for / and /boot.  I'd like to create a script for the Pi to move a running FPP instance from the SD to SSD and modify the two files in the process.  In conjunction, we could also modify FPP_Install.sh to update our Pi SD images to use PARTUUID= instead of /dev/mmcblk0p* for /boot and / in /etc/fstab and add a simple .bat file which the user could run from within Windows to update the cmdline.txt file to use /dev/sda2 instead of /dev/mmcblk0p2.

**Comment by darylc** [comment]
done in https://github.com/FalconChristmas/fpp/commit/642fcf023bf00d28acc53e3ea36a6116d65595ab
