### ISSUE TITLE
FPPD crash after Upload Output from XLights

### ISSUE THREAD

**Issue by lloydpick** [FalconChristmas/fpp#1323]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP Version:	6.0.1
Platform:	Raspberry Pi (Pi 4)
FPP OS Build:	v2022-07
OS Version:	Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number:	100000001ebf2733
Kernel Version:	5.15.32-v7l+
Local Git Version:	12cebb7 ChangeLog
Remote Git Version:	12cebb7

**Cape**:
Name:	PiHat
Version:	1.0
Serial Number:	FPP-INTERNAL
Licensed Outputs:	None, cape EEPROM is not signed.
Output Driver:	DPIPixels
EEPROM Location:	File

**Describe the bug and Steps to reproduce**: 
* Flashed a brand new SD card with FPP-v6.0-Pi.img
* Finished initial setup
* Expanded SD Card
* Rebooted
* Upgraded FPP
* Rebooted
* Went into XLights, pressed "Upload Output" for this new controller
* FPP becomes unresponsive/slow and crashes
* FPP UI becomes unreachable
* Hard power off after like 5minutes
* Power back on
* FPP says there are crash reports available

**Additional context**: 
It seems to be really strange and unreliable about outputs being updated, FPPD crashes about 50% or more of the time, and then has no ability to restart it, I have to power cycle it. Even then, when it comes back sometimes FPPD refuses to start.

Crash reports attached.

[fpp-Pi-6.0.1-2022-08-01_22-32-16.zip](https://github.com/FalconChristmas/fpp/files/9238675/fpp-Pi-6.0.1-2022-08-01_22-32-16.zip)
[fpp-Pi-6.0.1-2022-08-01_22-36-57.zip](https://github.com/FalconChristmas/fpp/files/9238676/fpp-Pi-6.0.1-2022-08-01_22-36-57.zip)

**Comment by darylc** [comment]
@lloydpick Does this still happen in fpp 6.3?

**Comment by darylc** [comment]
Also from your logfile, you aren't using DPIPixels, you are using RPIWS281X

**Comment by ghormann** [comment]
Closing. No response from OP.
