### ISSUE TITLE
Add support for 4-channel pixels to RPIWS281x and DPIPixels Channel Outputs on Raspberry Pi.

### ISSUE THREAD

**Issue by lloydpick** [FalconChristmas/fpp#1331]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP Version: 6.x-master-540-g3218c759
Platform: Raspberry Pi (Pi 4)
FPP OS Build: v2022-07
OS Version: Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: 100000001ebf2733
Kernel Version: 5.15.32-v7l+
Local Git Version: 3218c75 ChangeLog
Remote Git Version: 3218c75

Name: PiHat
Version: 1.0
Serial Number: FPP-INTERNAL
Licensed Outputs: None, cape EEPROM is not signed.
Output Driver: DPIPixels

**Describe the bug and Steps to reproduce**: 
I have a string of 4 RGBW floods from Wallys. They are configured as a chain of 4 on Port 1 of the PiCap. Through the FPP testing panel, all the colours work correctly on all the floods, apart from blue on the last flood (nothing happens). I went through this issue on the Zoom meeting with people and we did manage to get it working, the fix was to add another fake flood to the end of the chain (so there are 5), and then the blue on the last (4th) flood started working.

**Expected behavior**: 
Blue channel to work on the last flood in the chain.

**Additional context**: 
I went through this with people on the Zoom meeting, and they suggested I make a bug report here.

**Comment by cpinkham** [comment]
In v6.0.2 and prior, neither the old RPIWS281x or new DPIPixels code support 4-channel pixels.  Scott has been working on updating the old RPIWS281x channel output in the development code branch and I am looking at adding 4-channel support in DPIPixels as part of some other changes.  Currently the Channel Outputs configuration UI only allows configuring 3-channel pixels, so this is more of a known limitation than a bug.  I'm leaving the ticket open for now and we can close it once we have 4-channel support fully added.
