### ISSUE TITLE
More FPP Settings blank (v6.0.2)

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1332]
On all v6 releases (6.0-beta1 -> 6.0.2) In both Docker & Native Raspberry PI

Note: This relates to previous bug report  #1319
If UI password is enabled (with default or own password) various FPP settings are shown as blank (the already reported Audio/Video) but also in System "Real Time Clock" and TimeZone" (see screenshot 1)

![5FEB6349-EB18-410C-BE79-07D1BD076DCE_1_105_c](https://user-images.githubusercontent.com/69304144/183305804-8912cbff-2cbd-4567-9d5c-b90e34fc5a84.jpeg)

If UI password is disabled in FPP settings > UI they all appear fine (screenshot 2).

![D164EA35-87AC-4047-B5FF-3F9C26610E41_1_105_c](https://user-images.githubusercontent.com/69304144/183305832-1d22c8d9-58b6-4f51-b2df-b8115d726c3b.jpeg)

I assume these are all caused by the same issue (just reported for completeness).

**Comment by bakelitephone** [comment]
Many thanks

**Comment by camrun91** [comment]
I am seeing this same thing on 7.1
