### ISSUE TITLE
Rpi3b+ ethernet assignments don't stick when setting up Colorlight with usb gigabit adapter in FPP 6

### ISSUE THREAD

**Issue by DonMc33** [FalconChristmas/fpp#1335]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP v6.0.2-2ga4eeb9cf (v6.0 branch) on Rpi 3b+, with Cable Creation Gigabit usb adapter that connects to a 5A-75B Colorlight board.  Rpi does have the small Falcon OLED cape mounted on it.

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Downloaded and etched a fresh sd card with the Rpi version of FPP 6.0.  Loaded it into the Rpi 3b+, with only the ethernet cable connected to the onboard ethernet port booted the pi up.  Did the initial setup and expanded the storage.  Did a restore from a previous backup and rebooted.
2. Pi came back up with the the ethernet connected to eth0, IP address 192.168.0.80, which came from the json backup file.   I'm attaching it in the file section below.  Note... had to change it to plain text to be able to attach.
3. Went to About>Upgrade FPP to get latest FPP version v6.0.2-2ga4eeb9cf (v6.0 branch).
4. Once complete, plugged in usb gigabit ethernet dongle that was connected to the Colorlight 5A-75B board, which was powered up.  Went to network settings were eth0, eth1 and wlan0 all showed up.  Eth0 set as static 192.168.0.80, eth1 dhcp, and wlan0 dhcp.  Clicked on Update interface>restart and then Create Persistant Names.
5. Rebooted - Ethernet connected to eth0, usb gigabit adapter and colorlight connected to eth1.  Rpi came back online connected to eth0 192.168.0.80.  Was able to connect via the web interface, however, eth1 never assigned an ip to the usb gigabit/Colorlight.
6. Rebooted - Ethernet connected to eth0, usb gigabit adapter and colorlight connected to eth1. Rpi came up, however now showing wlan0 192.168.8.1.   
7. Swapped ethernet connection to usb ethernet dongle, and colorlight card to onboard ethernet connector.  Rebooted, came up on 
wlan0 192.168.8.1.   
8.  Swapped cable connections, Ethernet connected to eth0, usb gigabit adapter and colorlight connected to eth1.  Rebooted and came up on wlan0 192.168.8.1. 

**Expected behavior**: 
On FPP 5.5 and earlier versions, after installing FPP and booting up with only the ethernet cable connected to the onboard RPI 3b+, then plugging in the usb gigabit ethernet connector with colorlight board attached and clicking on update interface and create persistant names, eth0 stays assigned for the ethernet and the usb ethernet adapter on eth1, ultimately assigning an IP address to the usb eth connection to the Colorlight board.  Sorry, long sentence.
When the pi is rebooted, it always comes back up on eth0 and the assigned IP address,  I attempted the upgrade to FPP 6.0 on 9 of my rpi 3b+, all acted the same as was described above.  

As a note, I installed FPP 6.0 and updated as described above on a rpi 4b and it works correctly, so this issue appears to be some anomaly with the 3b+.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
3. Open the the File Manager (Content Setup->File Manager), 
4. Select the "Logs" tab
5. Click "zip" button.
8. Attach to this ticket.

[FPP_Logs_20220327.0547.zip](https://github.com/FalconChristmas/fpp/files/9295477/FPP_Logs_20220327.0547.zip)
[MatrixPole1_all-backup_v5_unprotected_20220727211735.txt](https://github.com/FalconChristmas/fpp/files/9295530/MatrixPole1_all-backup_v5_unprotected_20220727211735.txt)

**Comment by markphelan** [comment]
I have also been having issues with a USB ethernet adaptor on 6.0.2 on a Pi 3B+. When connected after boot, eth1 appears in the list of adaptors available to configure. Following a reboot, neither eth0 or eth1 are reachable. Tethered WLAN works intermittently, but when operational the two wired interfaces show as DOWN in `ip addr show` from the shell, despite having link LEDs lit on the connectors.

**Comment by darylc** [comment]
Well I managed to replicate this on a pi 3b+, although I have no idea to fix it.  Systemd gets upset when there are .link files generated for ethernet.  If you remove either one of them, it works ok.

Error from systemd-networkd:
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth1: New device has no master, continuing without
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth1: Flags change: +MULTICAST +BROADCAST
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth1: Link 4 added
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth1: Interface is being renamed, pending initialization.
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth1: Saved original MTU: 1500
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth0: New device has no master, continuing without
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth0: Flags change: +MULTICAST +BROADCAST
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth0: Link 3 added
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth0: Interface is being renamed, pending initialization.
Sep 12 22:01:40 FPP systemd-networkd[1907]: eth0: Saved original MTU: 1500

**Comment by dkulp** [comment]
With the newer Linux kernels probing USB devices in parallel, there isn't a way to keep the eth# persistent.   For 7.0, when the "Create Persistent" button is pressed, it will flip the USB ethernet adapters over to using the enx######## naming convention (which is persistent by definition).   We may make that the default, but we'll need to figure out migration path for fppos upgrades for that.

**Comment by DonMc33** [comment]
Tested using FPP 7.0 Alpha 1 release, ethernet assignments now stay as assigned using the persistent feature.  ETH 0 and ETH1 now show up as enxb827eb37eafa and enxa0ec82fc9cf after "Create Persistent Names" is selected in Network Configuration and the pi restarted.  Awesome work!!  Thanks for fixing this bug for the pi 3B+ users!
![New ETH0 Name](https://user-images.githubusercontent.com/53984565/233755262-5279d680-0c41-4d66-9868-fba03aac635a.jpg)
![New ETH1 (USB GIGABIT ADAPTER) name](https://user-images.githubusercontent.com/53984565/233755264-7f4ea80a-2c4e-4c95-956f-9b1f79893c44.jpg)
