### ISSUE TITLE
Pi 6.0.0 and 6.0.2 Channel Output screen shows PiHat and Other tabs only

### ISSUE THREAD

**Issue by ahallber** [FalconChristmas/fpp#1338]
We downloaded the Pi 6.0.0 image and the 6.0.2 image onto both a Pi3 Model B and Pi4. When viewing the Channel Output Setup screen on both our Mac (Safari) and our PC (with both Chrome and Firefox on the PC), only the PiHat and Other tabs were visible. The E.131 and LED Panels tabs were not visible

We viewed the Channel Output Setup screen on our Iphone 12 phones (Safari), and all 4 tabs were visible (the E.131, LED Panels, PiHat, and Other tabs),

**Comment by ahallber** [comment]
[FPP_Logs_20220816.0526(1).zip](https://github.com/FalconChristmas/fpp/files/9348061/FPP_Logs_20220816.0526.1.zip)
[FPP_Logs_20220816.0526.zip](https://github.com/FalconChristmas/fpp/files/9348062/FPP_Logs_20220816.0526.zip)
[FPP_Logs_20220816.0526(1).zip](https://github.com/FalconChristmas/fpp/files/9348065/FPP_Logs_20220816.0526.1.zip)
[FPP_Logs_20220816.0526.zip](https://github.com/FalconChristmas/fpp/files/9348066/FPP_Logs_20220816.0526.zip)

**Comment by darylc** [comment]
@ahallber Is this still a problem on v6.3?

**Comment by ahallber** [comment]
It appears to be working. I just downloaded a new 6.3 image onto a Pi4 and all the tabs are there.

Thank you very much!  Happy new year!
Allen


[cid:99d04837-bd83-4502-b77c-259a9498e73b]
________________________________
