### ISSUE TITLE
FPPD Restart does not run plugin stop and start scripts

### ISSUE THREAD

**Issue by koolsb** [FalconChristmas/fpp#1339]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: FPP 6.0.2 running in Raspberry Pi 4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Click "Restart FPPD" Button on any page
2. Plugin stop/start scripts are not called

**Expected behavior**: 
If I execute a Stop FPPD followed by a Start FPPD, the plugin start and stop scripts are called with each respective button push. When I click Restart FPPD, I would expect it to run the stop and then start plugin scripts but it doesn't not.

**Additional context**: 
Upon reviewing the [FPPD Restart script](https://raw.githubusercontent.com/FalconChristmas/fpp/123cdf2eb11062766da333a7a4d85bc0bf620e47/scripts/fppd_restart), if FPPD is running in a docker environment it runs the fppd stop and then start scripts which also call the plugin scripts, however, if running natively in linux which most Pi and BBB instances are, it uses the systemctl function to restart fppd. The fppd.service file in /lib/systemd/system/ only runs the fppd boot scripts, not any of the plugin scripts.

**Additional Attachments**
Please include the log files. To create the file:

**Comment by cpinkham** [comment]
Most FPPD restarts are "quick" restarts where fppd just respawns itself.  This feature was added a few years ago to allow quicker fppd restarts to minimize downtime.  The quick restart also has support for not blanking pixels and restarting an in-progress playlist to further minimize the effect of a restart.  If a change is made that requires a restart, this allows users to wait until a sequence ends, hit the restart button, and a second or so later fppd is back up and running on the next item in the playlist.  In this use case, the plugin stop/start scripts are not re-run.  If you want to re-run the scripts, a full stop and start is needed.

This isn't a bug, the quick restart is working exactly as intended.
