### ISSUE TITLE
6.02 install - always says "Remote Git Version:Unknown

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1340]
**FPP Version and Hardware**: 
*FPP 6.0.2 running on PI*

**Describe the bug and Steps to reproduce**: 
Daryl C noted that he can ping [github.com](http://github.com/) from other parts of the world (different IP address). He suspects we're going to have to move away from pinging [github.com](http://github.com/) as a way of detecting if we have Intenet? eg in checkTimeAgainstUSNO()

This apparently only happens on his side of the globe, but perhaps Github will be plugging pings in the future.

This is not happening in the US.

Submitted on his behalf.

**Comment by mjunek** [comment]
Can also confirm that this is occurring from Sydney AU.
ICMP appears to be blocked to Github. 
![image](https://user-images.githubusercontent.com/55641392/188256353-296b4761-4ccf-4d48-bab8-19729f3256f6.png)

As an idea - a way for an internet connectivity test would be to use the shop.falconplayer.com URL as this is controlled by members of the project, and a simple script could be stood up to return details to FPP about the connection (public IP, etc, if required)
