### ISSUE TITLE
Network adapter no longer works on FPP 6

### ISSUE THREAD

**Issue by rsather70** [FalconChristmas/fpp#1346]
Network issues with FPP 6.

I use the following network adapter in my controllers (Kulp K4's and K8's) - https://www.tp-link.com/us/home-networking/usb-adapter/tl-wn725n/

These adapters work great up through 5.5 but will not work in v6.  I've tried switching from External to Kernel drivers with no luck.  The wifi adapter is recognized by the OS as I get wlan0 on the network page, however when I complete configuration and boot without tethering I get no network on the OLED display and the device does not connect to my network.  I have tried a newer adapter and that works which also confirms that the wifi SSIS and passcode are correct.  The underlying OS seems to recognize the adapter just fine but something isn't allowing the it to work.  Looking for ideas on this issue.

![300776330_10229244969851707_1790159773219704069_n](https://user-images.githubusercontent.com/37515819/187225125-14a903d5-724b-4e0d-94ec-8eed3e49012a.jpg)

**Comment by dkulp** [comment]
This will be fixed in the next OS image.   If you want to try the fix, you can run:
```
sudo     sed -i -e "s@^ExecStart.*@ExecStart=/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -Dnl80211,wext -i%I@" "/lib/systemd/system/wpa_supplicant@.service"
```

to enable the legacy (wext) wifi driver api.
