### ISSUE TITLE
Storage tab is missing from FPP settings

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1351]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
6.02 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
- Perform initial setup.
- Do **not** click on "Expand Storage".
- Go to "Status/Control", "FPP Settings" menu, there is no storage tab.
- Click on "Status/Control", "Status Page", "expand storage" warning re-appears.
- Click on "Expand storage", auto-navigated to "Status/Control", "FPP Settings", but now there is a "Storage" setting tab.

**Expected behavior**: 
Consistent menu navigation, always show storage tab.

**Additional context**: 

**Additional Attachments**

![image](https://user-images.githubusercontent.com/2061579/187796667-eb999b8f-8d08-4eb9-8bf0-b0e3829d883e.png)
![image](https://user-images.githubusercontent.com/2061579/187796706-f95d22ef-fa50-4640-ad7c-744d1ddea99e.png)
![image](https://user-images.githubusercontent.com/2061579/187796751-7b1636a7-fcae-4b41-850f-70405c8d44a7.png)

**Comment by dkulp** [comment]
With 6.1, the storage tab will remain visible if the SD card still needs expanding.  Setting storage settings is not something that a normal person should be dealing with (once the SD card is expanded) and thus the tab should be hidden unless in Advanced mode.
