### ISSUE TITLE
Channel outputs test pattern first pixel is always white

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1352]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
6.0.2 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
- Connect 60 x WS2811's to channel 1 on K4-PB.
- Enter "Input/Output Setups", "Channel Outputs"
- Configure pixel count 60.
- Save, restart FPPD.
- Click "test pattern"
- First pixel remains white, other pixels change RGB.
- Click "Stop"
- Go to "Status/Control", "Display Testing".
- Select "String-1", and enable test mode.
- All pixels are cycling as expected.

**Expected behavior**: 
Expect "test pattern" in "channel output" to test all pixels, same as when using "display testing".

**Additional context**: 

**Additional Attachments**

![image](https://user-images.githubusercontent.com/2061579/187800090-c8ee5aa7-51dc-4132-b3f3-59f61ca81654.png)
![image](https://user-images.githubusercontent.com/2061579/187800125-6437b9a6-d9ce-4c2f-981b-6d6717ee3492.png)

**Comment by darylc** [comment]
This is the expected behavior per the manual.  See page 116 https://falconchristmas.github.io/FPP_Manual(6.0).pdf

**Comment by ptr727** [comment]
I see:  
"Test Pattern- This will output a pattern to identify what port each string is connected to.
The first number of pixels in each string will correspond to the port that it is connected
FPP Manual- Version 6.0 Page 116"

I thought my pixels were not working, until I used the similarly named feature in display testing.

User experience improvement opportunity, maybe call it what it does, e.g. port identification?

**Comment by darylc** [comment]
Feel free to send a pull request

**Comment by dkulp** [comment]
This is working as designed.  The "Test Pattern" buttons on the output pages (LED Panel has a similar button) is not to help test the pixels/lights.   The purpose is to make sure things are configured and wired correctly.   For the LED panels, it more complex and shows a specific pattern on each panel along with the panel output and position in the chain to help there.   For the pixel strings, it tries to help you make sure the pixels were connected to the port you actually think they are connect to.
