### ISSUE TITLE
FPP Daemon fails after config restore

### ISSUE THREAD

**Issue by tomhammond** [FalconChristmas/fpp#1355]
Hi Dan,

I had FPP v5.5 on BBB eMMC and did a config backup.  I imaged an SD card with 6.02, then booted with BBB with it.  Then I copied it to eMMC via the FPP UI Storage menu.  After reboot, it came up fine and the daemon was fine.

When I restored my config file, I received "Abnormal Conditions - May Cause Poor Performance, FPPD Daemon is not running."  I could not start/restart the daemon, even after rebooting.

As a work around, I reinstalled a clean 6.02 onto the eMMC again, then manually entered my config settings (I did not use the restore file).  The daemon is stable then.

As an aside, I have an RGB123C cape.  When I restored the config file to cause the daemon problem earlier, I did not yet activate the license for this cape.  Did not activating the cape have something to do with the daemon failure since my config file had the cape and its output ports assigned to it (and >50 pixels on each port)?

Thanks,
Tom Hammond

**Comment by cpinkham** [comment]
Did you install the virtual EEPROM for the RGB123 cape?

**Comment by dkulp** [comment]
Not installing the eeprom should cause fppd to not start.  It should just display a warning about not being able to create the BBB48String output.   If possible, I'd like to see the config backup so I can try applying it to an fpp instance to see if I can reproduce it.

**Comment by tomhammond** [comment]
Hi Dan,

 

Sorry about forgetting the config file; I meant to include that for troubleshooting.

 

I didn’t receive a message about the BBB48String.  It just said the daemon wasn’t running and I could not start it manually.

 

Attached is the config file if you want to reproduce it.

 

My workaround was not to restore the config file.  Instead, I did a clean install of FPP 6.02 then manually made the changes that I had from 5.5.  I just thought you would be interested in the potential daemon problem after restoring the config.

 

Thanks for all of the work that you  & Chris put into FPP.

Tom

**Comment by tomhammond** [comment]
Hi Dan,

 

FYI, when I made a backup of the config in v6.02, it puts “v5” in the json filename.

 

Tom

 

 

 

From: Tom Hammond ***@***.***> 
Sent: Monday, September 5, 2022 8:16 PM
To: 'FalconChristmas/fpp' ***@***.***>
Subject: RE: [FalconChristmas/fpp] FPP Daemon fails after config restore (Issue #1355)

 

Hi Dan,

 

Sorry about forgetting the config file; I meant to include that for troubleshooting.

 

I didn’t receive a message about the BBB48String.  It just said the daemon wasn’t running and I could not start it manually.

 

Attached is the config file if you want to reproduce it.

 

My workaround was not to restore the config file.  Instead, I did a clean install of FPP 6.02 then manually made the changes that I had from 5.5.  I just thought you would be interested in the potential daemon problem after restoring the config.

 

Thanks for all of the work that you  & Chris put into FPP.

Tom

**Comment by tomhammond** [comment]
I did not install the virtual EEPROM before doing the restore.  Do you think that is what caused the daemon to mess up?

 

Thanks!

Tom

**Comment by darylc** [comment]
@jaredb7 Do you have any ability to test this issue?

**Comment by jaredb7** [comment]
Sorry, not really. Logs and the backup file (it didn't attach in OP's reply) would've been good. I'm thinking maybe output data that was backed in v5 was wasn't 100% compatible with v6 or something was not right with it?

Though our issues could very well be unrelated.
I had something similar with my rPI28D cape, coming from something like a early v5 into v6. The setting page looked fine but I had to toggle channels active on/off and fill out a description for the remaining DMX output for things to work.

**Comment by patdelaney** [comment]
closed  no response in over a year
