### ISSUE TITLE
6.0.2 Audio issues with Kulp/Vast FM transmitter 

### ISSUE THREAD

**Issue by kevinsaucier** [FalconChristmas/fpp#1357]
This is more or less a duplicate of https://github.com/FalconChristmas/fpp/issues/1341 but the other specifically states SB3 and I wanted to ensure the issue is raised for the Kulp/Vast transmitter as well, since I and others are seeing this issue as well as the card coming up as 'Dummy' after a reboot.  If it's already being worked on on the other ticket, please cancel this one.

I attached logs to my response on the other ticket but here is the text again:

Edit - Just to add a little more info, I just put the old card back in and downgraded to 5.5 and, though the songs seem to be playing with less volume than on 6.0.2 (volume is set to 70), they are playing with no static through both the audio jack and the FM transmitter.

I know this issue names the SB3 specifically but a comment above says they heard the same issue with the onboard audio so figured I'd throw my hat in the ring here. I've had bad static since upgrading. Also have an ongoing issue where the Audio Output/Device will go to 'Dummy' after a restart. The davinci card is in the list, but it defaults to Dummy. I can switch it, then reboot, and then it holds davinci while running, but another restart or power off typically causes it to go back to Dummy.

I just built a new SD card from the downloaded 6.0.2 image, then jumped over to Master on my K32 using the (Vast/Kulp add on board) and it's fully up to date but I'm still getting a ton of static, both locally as well as across the FM transmitter. Also, the song that's playing keeps slowing down and speeding back up, like it's overloaded and struggling to keep up. 

Just looked at the LCD on the board and it's bouncing between showing the sequence that's playing and showing the 'Kulp Lights' logo screen with a line that says FPPD is not running (even though it obviously is as the sequence continues playing).

6.x-master-561-g17af020f

Thanks!

**Comment by thekev** [comment]
Same problem on K16 with the Si4713 and Raspberry Pi 3 with USB Sound Blaster Play 3, both in remote mode. I first noticed crackles on the RPi that runs my press for music button, then while testing the K16 I noticed the crackles were possibly identical. Downgraded both to 5.5 and it fixed them both.

**Comment by kevinsaucier** [comment]
6.1.1 seems to have helped.  Now I have some static, but not as bad.

**Comment by thekev** [comment]
6.1.1 is fine on the master fwiw. On the remote it was not super bad, but it was there and bothered me enough to reinstall.

**Comment by nmiller0113** [comment]
Is this resolved now? I'm just curious as I have something similar when playing a stream via VLC, but not when playing a local audio file. I also don't have the problem with mpd, but always vlc. This is likely unrelated to my issue https://github.com/FalconChristmas/fpp/issues/1393 but I have to ask since I've not had any replies to my reported issue.

**Comment by darylc** [comment]
is this still a problem in 6.3 @kevinsaucier @thekev?

**Comment by kevinsaucier** [comment]
@darylc Not sure.  I moved to a standalone FPP while testing issues with Remote Falcon and had to use my normal FM transmitter.  Once it was working, I never went back to the K32 with the add on FM board.  I'll try to test it out again during teardown.

**Comment by thekev** [comment]
I rolled back remote audio players to 5.5 for the season. Now that it's over, I'll give 6.3 a try. I noticed a changelog entry that seems related.
