### ISSUE TITLE
6.1: Volume Slider & Si4713/Vast V-FMT212R 

### ISSUE THREAD

**Issue by Patato12** [FalconChristmas/fpp#1358]
Kulp K16A-B Running 6.1 + Latest BBB

FM transmitter (Si4713) is putting out garbage audio (High Static + Significant Quality drop during loud portions of a song)
In v6.1 the audio slider found on the status page does not seem to work properly thus leaving it stuck at 100% Audio. 

When I reverted to v4.4 the audio slider worked correctly and I was able to replicate the exact same issue by maxing out the volume slider.

I am able to continue using 6.1 by editing the audio file to be extremely quiet however this is obviously not a great solution.
As a temporary stop-gap I would recommend default audio on a fresh install of 6.1 be set to 60% volume 
@dkulp

**Comment by dkulp** [comment]
This should be fixed in 6.1.1
