### ISSUE TITLE
FPP 6.1 Fresh install or fppos upgrade will kernel Panic on Pi Zeros W or regular

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1360]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.1 fresh install or FPPOS upgrade

**Describe the bug and Steps to reproduce**: 
A fresh install if 6.1 or fppos upgrade will panic PiZero and PiZero WI.  It does work on Pi V3 and Pi V4  but will show an error on initial boot screen if HDMI output is connected.

**Expected behavior**: 
It should not Panic

**Additional context**: 
To test it's good to have an hdmi monitor attached to see the errors.

**Additional Attachments**
This is the Kernel Panic on Pi's
![image](https://user-images.githubusercontent.com/8147459/190924287-40d657b8-a524-48f0-a23a-734e84f76d54.png)

This image below is PiV4
![image](https://user-images.githubusercontent.com/8147459/190924314-f0a5ecea-0dbc-4e39-82c8-fa3f68e1d992.png)

**Comment by sicklydog** [comment]
Had same problem. Installed older  version and it worked.

**Comment by cbuxton5200** [comment]
I can confirm the same issue on both of my Pi Zero W

**Comment by dkulp** [comment]
Fixed in 6.1.1 images
