### ISSUE TITLE
Interface Routing Button Missing 

### ISSUE THREAD

**Issue by Jacalynmal** [FalconChristmas/fpp#1361]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

Raspberry Pi 4
FPP: | 6.1
OS: | v2022-07
Local: | 9febee3
Remote: | 9febee3
Branch: | v6.1

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1.   Lost connection with F16V3 controller
2.  Under Network Configuration noticed Interface Routing button missing
3.  Cannot verify if interface routing is still turned on as the Interface Routing button is missing from the Interface Settings tab under Network Configuration 

**Expected behavior**: 
Be able to open gui interface to F16V3 with Interface Routing feature - button is missing to verify it is still active

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
4. Open the the File Manager (Content Setup->File Manager), 
5. Select the "Logs" tab
6. Click "zip" button.
7. Attach to this ticket.

[FPP_Logs_20220918.2135.zip](https://github.com/FalconChristmas/fpp/files/9595278/FPP_Logs_20220918.2135.zip)

**Comment by Jacalynmal** [comment]
Also - I can ping Falcon from the Player however xlights cannot see it now can I access with the ip address from the gui.  this all worked just fine until I upgraded to 6.1.

![image](https://user-images.githubusercontent.com/54683818/191062449-71d1588f-d7ad-4ab2-b7f4-10c85cd2602d.png)

**Comment by darylc** [comment]
I'm not entirely clear what you are trying to do but perhaps try the IP Forwarding setting?

**Comment by Jacalynmal** [comment]
My FPP Player is no longer acting as a bridge to my Controller.  The button for Interface Routing is missing.  It was there for 5.5 and 6.0.  When I upgraded to 6.1 I was no longer able to reach my Controller through my FPP Player.  I can ping it from the output tab but it is no longer communicating through my FPP Player.  Was the Interface Routing button replaced in 6.1.  I do not know what IP Forwarding does.

**Comment by dkulp** [comment]
I'm 99.9% sure it was NOT there for 6.0.   It was removed as part of 6.0 development cycle as the IP Forwarding replaces it as it's a superset of the routing capabilities.

**Comment by Jacalynmal** [comment]
Okay so that is what happened.  I just enabled IP Forwarding and it started working again.  Sorry about that.  Appreciate your response!
