### ISSUE TITLE
color light standalone player for custom model live preview 

### ISSUE THREAD

**Issue by trinityworld** [FalconChristmas/fpp#1362]
I'm trying FPP in **Armbian OS TX3mini** to get output from ethernet to drive led matrix
![image](https://user-images.githubusercontent.com/93513180/191019687-a24b481c-63c9-480d-b08d-1f743cf372b6.png)

for those who also want to try 
[Tutorial](https://www.youtube.com/watch?v=n54aEMdXj7I&ab_channel=i12bretro)

[Here i posted](https://pastebin.com/06aU8GSA) custom .cpp file to check running led pattern

5A-75B's output is correct but not acceptable (minor glitches) , I tried same with led vision from PC (works perfect, No glitches)

i also verify with 

1. Wireshark 
2. [Dart](https://github.com/haraldkubota/l2-ethernet/blob/main/example/colorlight.dart)
3. [FPP color light](https://github.com/FalconChristmas/fpp/blob/ebb93b13abb9b1c456cc9ace38316fb8e22d53f9/src/channeloutput/ColorLight-5a-75.cpp)

I have little concern about delay between packets

apart from this script, how do I run standalone test .CPP file which is included in FPP image file ?

**Comment by darylc** [comment]
https://pastebin.com/06aU8GSA does not exist

**Comment by cpinkham** [comment]
You should be able to install FPP on Armbian using the FPP_Install.sh script.  Are you trying to do that or are you just trying to use the .cpp file from FPP in some other code?

**Comment by darylc** [comment]
hello @trinityworld?
