### ISSUE TITLE
Playing mp4 rather than fseq for virtual matrix - pauses/skips/stalls

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1363]
Seems like the only way to make this work v5.5 or v6.1 is to ignore multisync timing packets. Should this perhaps be defaulted when an mp4/avi is called to be played on a virtual matrix?

Was this the default in v4.x ? as my setup worked fine last year :-)

**Comment by dkulp** [comment]
I'm not able to reproduce this with 6.1 if using FPP for both master and remote.

**Comment by davidslowik** [comment]
I see this problem in my virtual matrix as well on every video I've tried. I've tried various 5.5/6.1 combinations. I've also swapped out Pi's and SD cards. The only thing that I've got to work is to turn on the option to ignore multisync timing. I did do a test that may help and have attached the log.

In this test I did a master (5.5-26) and remote (6.1.1) and turned on excessive logging on the remote Pi. Once I hit play, I watched my virtual matrix and started noticing issues after about 3-4 seconds and they get worse quickly.
Looking at the log, at 3 seconds it starts logging messages "picture is too late to be displayed" with very small ms numbers.
By 4.088 seconds, it is up to 1500 ms and stays in that range until I stopped the sequence at about 8 seconds.

[fppd.log zipped](https://github.com/FalconChristmas/fpp/files/9694038/fppd.zip)

**Comment by patdelaney** [comment]
@derwin12 please supply the video file.  I can't reproduce this either

**Comment by patdelaney** [comment]
Since there wasn't a lot of info on the scenerio, I will outline the test I did.
1 mp4 video in a playlist on the Master (Piv4)
2 PiV4's as remotes
1 PiV4 configured as a virtual matrix.
The MP4 is on all the 3 remotes.
Launch the playlist and all 3 remotes start and end together no choppy playback.
![image](https://user-images.githubusercontent.com/8147459/194191197-6cc19a4a-84a5-4f0b-bfaf-9062c2894ea4.png)

**Comment by davidslowik** [comment]
I shortened a sequence and verified that the problem was happening with the attached video as well.
Here was my configuration.
Pi3 is the player.
Pi4 is the VM.
mp4 is on Pi4,

![image](https://user-images.githubusercontent.com/56902524/194192119-9aa40905-4bb0-4261-aeb8-d877279cd2c7.png)

https://user-images.githubusercontent.com/56902524/194191635-089072ec-cdb2-4c05-9929-46f6c46282ee.mp4

**Comment by patdelaney** [comment]
It's the file and the way it is encoded. I can't give you the exact reason yet. But here is one of the files I test with and it doesn't display the issue. 

https://user-images.githubusercontent.com/8147459/194195354-4784e4ba-687e-4775-80b8-59ae76e7d1c4.mp4

Is this the original file or did you re-encode it? If you re-encoded it what tool did you use?

**Comment by patdelaney** [comment]
That seems like a very high frame rate:
![image](https://user-images.githubusercontent.com/8147459/194195701-3c6484d7-fd44-4aff-8029-1ea9360ade39.png)

**Comment by davidslowik** [comment]
My video was encoded in Xlights via the Model | Render and Export using the default option of uncompressed mp4.
![image](https://user-images.githubusercontent.com/56902524/194201056-61654110-fad6-46bb-a04d-b4b086032c7e.png)

I downloaded your video and it does play fine.

**Comment by derwin12** [comment]
And my videos were created using the same method .. ie Render and Export to an mp4.

**Comment by derwin12** [comment]
I guess that is no coincidence that the video is 40fps - as that is what we would have set when we create the sequence. The video is created by xlights by taking a "screenshot" for each frame in the sequence.

**Comment by dkulp** [comment]
If the effects and such are rendered in xLights, it would be MUCH better quality to keep them in the fseq and have the output via the normal Virtual Matrix stuff.   Not sure why you would export to mp4 and play the mp4 as opposed to the fseq.  That said, you could try the compressed mp4.   Particularly on the Pi4 the hardware decoder has a bunch of older codecs stripped out which may be causing some issue.   You can also try turning off the hardware decoder entirely (advanced setting).

**Comment by derwin12** [comment]
I crank up the vm resolution -- render and export. Way too many channels to create the fseq imho.

**Comment by davidslowik** [comment]
I also plan to run at a pretty high resolution. I tried exporting compressed and uncompressed mp4's and also an uncompressed avi. All acted the same by pausing and stopping in fpp. I then ran one of the mp4's through handbrake using the default options. The handbrake-converted video works fine. I will try some other videos this weekend to verify that workaround. Below is codec info from the pre and post handbrake conversion.

Handbrake info
![image](https://user-images.githubusercontent.com/56902524/194721617-03f3c36b-6094-43b6-81d2-c50b06806fdb.png)

xLights info
![image](https://user-images.githubusercontent.com/56902524/194721661-23438877-37e1-49de-8aa5-ea6ce0c9d691.png)

**Comment by davidslowik** [comment]
I tested quite a few sequences this weekend. I found that it didn't matter if the xLights generated mp4 was 20 or 40 fps. The problem could occur with either. Most of my videos, but not all, had the issue.

Every video I ran through handbrake did work correctly afterwards.

Handbrake did automatically change the videos that were 40 fps to ~29.97 and the videos that were 20 fps were left at 20. I'm not sure what other changes Handbrake made.

**Comment by derwin12** [comment]
We had another on zoom today .. it didnt work for his pi4 but worked on pi3 with no issues. To make a video work on the pi4 we enabled the ignore timing packets AND disabled the hardware decoding. Worked fine during initial testing.. and he will continue to test.

**Comment by darylc** [comment]
@derwin12 Can you please supply a sample file that has this problem?  I understand you wish us to  "Render and Export to an mp4." however I have tried this and I can't for the life of my actually get xlights to save anything to disk and I can't replicate this issue with other mp4 files I have.

**Comment by derwin12** [comment]
Seems the fix .. and we seem to recommend to everyone is to ignore timing packets in the advanced ui.
