### ISSUE TITLE
add "all" option to "Channel Range/Model" on gpio triggers

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1365]
**Is your feature request related to a problem? Please describe.**
The Test sequence action on the gpio triggers allows you to select individual models but doesn't allow for a "All Channels" or "All Local Channels" like the drop down in the "Display Testing" UI

I would like the ability to have these as options so they can be built into default settings for GPIO's on eeprom - so test buttons can work out the box without having to know the model config on any particular controller

**Describe the solution you'd like**
Include "All Channels" and "All Local Channels" on dropdown of "Channel Range/Model" on test sequence action in the GPIO section of fpp UI

**Comment by darylc** [comment]
I wonder if we should just auto create an overlay model that covers all configured channels in FPP

**Comment by darylc** [comment]
You could take the same approach as the oled test functionality - call /api/testmode with something like:
{
  "mode": "RGBChase",
  "subMode": "RGBChase-RGB",
  "cycleMS": 1000,
  "colorPattern": "FF000000FF000000FF",
  "enabled": 1,
  "channelSet": "1-1048576",
  "channelSetType": "channelRange"
}

**Comment by darylc** [comment]
The dropdown for "Test Start" now contains an item containing the range of channels that this FPP is aware of.  Eg (this test FPP knows just 8 channels & 1 model):

![image](https://user-images.githubusercontent.com/7511887/216790429-b2260436-096c-47bf-a57b-fc47a4064d41.png)
