### ISSUE TITLE
Monitoring options not "sticking"

### ISSUE THREAD

**Issue by mikegcoleman** [FalconChristmas/fpp#1367]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Pi 4+ w/ FPP 6.1.1

**Describe the bug and Steps to reproduce**: 
I go into the Output Interface and disable monitoring. After a random period of time (usually less than 24 hours the FPP will re-enable monitoring it on it's own). 

* Go into channel outputs
* Uncheck monitoring on all my controllers
* Wait for my controller to lock up (AlphPix apparently has an issue w/ FPP monitoring) 
* Check the channel output settings and see that the monitoring option has been reenabled by itself

**Expected behavior**: 
I expect that I disable monitoring it will stay disabled until I explicitly reenable it or the system is restored to its default configuration. 

**Additional context**: 
None

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20220930.0512.zip](https://github.com/FalconChristmas/fpp/files/9680931/FPP_Logs_20220930.0512.zip)
[FPP_Logs_20220930.0512.zip](https://github.com/FalconChristmas/fpp/files/9680934/FPP_Logs_20220930.0512.zip)

**Comment by darylc** [comment]
Is there any change something else (eg xlights) is reconfiguring this?

**Comment by dkulp** [comment]
Are you sure you hit "Save" after turning off the monitoring AND then restarted FPPD?   Both would be required.

**Comment by mikegcoleman** [comment]
> Are you sure you hit "Save" after turning off the monitoring AND then restarted FPPD? Both would be required.

@dkulp Yep. Every time. 


> Is there any change something else (eg xlights) is reconfiguring this?

@darylc That could be possible, although I am not sure where in xLights this would come from. I'll experiment later today and see if there is any connection between this and using FPP Connect to upload sequences.

**Comment by darylc** [comment]
@mikegcoleman How did you go with that testing?

**Comment by ghormann** [comment]
Closing. No response from OP.
