### ISSUE TITLE
Compile for Le Potato

### ISSUE THREAD

**Issue by f3rr311** [FalconChristmas/fpp#1368]
Please delete if already addressed

**Is your feature request related to a problem? Please describe.**
The problem is getting our hands on Pi's or BB devices 

**Describe the solution you'd like**
Is there a way to have FPP compiled to run natively on Bare Metal / PC based Hardware so that small PC's and laptops can be leveraged in place of Pi's and BB as they are somewhat hard to find or outrageously priced

**Comment by dkulp** [comment]
It already can be installed on any Debian 11 based Linux system.   Pretty much download the FPP_Install.sh and run it.   Optionally pass --img flag if you want it to fully run like the Pi/BBB version (take over networking, display, etc...).

**Comment by f3rr311** [comment]
Was this .sh only published in a past version? I do not see that anywhere besides the MAC OSX script.

That's really cool that this was already a thing. 100 raspberry pi's are killing me

**Comment by f3rr311** [comment]
@dkulp Would it be at all possible to get this ported to https://libre.computer/products/s905x/   I would gladly try and build it from source if you have any documentation on that somewhere (I looked but I am not sure how to not run it as a docker)

The Le Potato is currently $45 USD on Amazon and has GPIO (They said something about hardware overlays I am not familiar with)  https://docs.google.com/spreadsheets/d/1U3z0Gb8HUEfCIMkvqzmhMpJfzRqjPXq7mFLC-hvbKlE/edit#gid=0

**Comment by dkulp** [comment]
It should aready work on that.  I had an earlier version of 6.0 running on one.  Its also possible to get running off an eMMC installed on one, but that is much more tricky to do.     See:  https://github.com/FalconChristmas/fpp/blob/master/SD/README.Armbian

Pay attention to the cpufreq thing in there though.   My Potatoe overheated a bit while trying go get it installed.

**Comment by f3rr311** [comment]
Your a GOD Thanks ;)
