### ISSUE TITLE
EEPROM Upgrade for Pi-OLED to Support DPIPixels

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1372]
**Is your feature request related to a problem? Please describe.**
A user came into the zoom room today that has purchased a DPIPixel license to use with his standalone wings and use the GPIO PINs directly to drive pixels.   After he installed the Pi-OLED the hardware eeprom took priority and invalidated his DPIPixel license.

**Describe the solution you'd like**
A mechanism to allow the Pi-OLED screen to be used and any remaining GPIO PINs to be available for DPIPixel outputs.  I understand this may require an eeprom upgrade for the Pi-OLED cape.

**Describe alternatives you've considered**
Removed the Pi-OLED cape.

**Comment by MrPaulAR** [comment]
Had a 2nd user with Pi-OLED cape and not being able to use the pixel output on their Experience Lights In & Out board with the Pi-OLED cape.

**Comment by darylc** [comment]
Dan has advised that FPP does not and will not support stacked capes.
