### ISSUE TITLE
Pi Zero video stops playing after ~10min due to out of video memory

### ISSUE THREAD

**Issue by gleeds** [FalconChristmas/fpp#1375]
**FPP Version and Hardware**: 
Example: *FPP 6.1.1 running on Pi Zero W*

**Describe the bug and Steps to reproduce**: 
1. Start with a clean install of FPP
2. Upload a 2 minute 720p 30fps video
3. Create a playlist with said video
4. Run playlist with repeat enabled
5. Let video loop for 10-15minutes 
6. Eventually the video stops playing and HDMI output returns to login prompt,  Web UI indicates video is continuing to play.  Sometimes restarting FPPD through the UI/API will allow for video to play for another 10-15 minutes, other times the web UI becomes unresponsive and a restart of the pi is required.

**Expected behavior**: 
Video Loops Indefinitely

**Relevant Log Message**
```
Oct 06 12:56:55 projector1 fppd[1495]: mmal: mmal_port_event_get: vc.ril.video_decode(1:0) port 0xa737e9e0, no event buffer left for ERRO
Oct 06 12:56:55 projector1 fppd[1495]: mmalipc: mmal_vc_handle_event_msg: no event buffer available to receive event (2)
```

**Suggested Fix**
This error seems to be related to the Pi Zero running out of video memory.  I found a similar issue here:
https://forums.raspberrypi.com/viewtopic.php?t=313554

After running `raspi-config` and updating the GPU Video Memory to 256MB the video has successfully looped for the last 4 hours in my testing so far.  Can this setting be baked into the image somehow?

**Comment by darylc** [comment]
The Pi Zero W has so little memory (512MB) that assigning 256MB by default would be detrimental to most FPP end-users.  FPP assigns 64MB of GPU memory in pi zero by default, if you need more than that then you will need to change this yourself, as you have done.
