### ISSUE TITLE
Email not working in OS 2022.09

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1380]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
multiple pi.  Any Pi with OS 2022.09

**Describe the bug and Steps to reproduce**: 
After upgrading to OS 2022.09, When selecting on 'send test email' from the email configuration page, we get a message saying sh: 1 : mail: not found.  When on 2022.07, this worked fine.  I even upgraded to 6.1.1 on OS 2022.07 and it worked as expected, but once I upgraded to OS 2022.09, mail could no longer be found. 

**Expected behavior**: 
I would exptect not get the error but instead get a notification that the test email was sent. 

**Additional Attachments**
![image](https://user-images.githubusercontent.com/88390168/195475803-e8d812bf-c539-43f7-b26b-1de23b65ffc7.png)

**Comment by nmiller0113** [comment]
@bloojoop FPP doesn't run version 2022.09. That's not even the version numbering structure. Are you sure you opened this in the right place?

**Comment by bloojoop** [comment]
@nmiller0113 absolutely sure.. I'm referring to the OS version number and for fpp 6.x  the OS is versioned this way. 
![image](https://user-images.githubusercontent.com/88390168/200439478-63591a5c-a9db-4d5b-b703-e3170d3bc3ae.png)

In this case, the OS is version v2022.09b

**Comment by nmiller0113** [comment]
@bloojoop I never had seen that build numbering before. I apologize. It looked like xlights version numbers so I thought I'd ask :) Learned something new today!

**Comment by dkulp** [comment]
I believe this was fixed in 2022.11 (6.2 images)
