### ISSUE TITLE
PLAYLIST_START_TMINUS_600 Not Firing MQTT Command

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1381]
**FPP Version and Hardware**: 
Pi4 tried 6.1.1 ~~& v5.5-26-gf21fd7a5~~
* Correction.  v5.5-26-gf21fd7a5 works fine.

**Describe the bug and Steps to reproduce**: 
Configure MQTT and verify functionality.
Setup a command preset selecting PLAYLIST_START_TMINUS_600 from the dropdown
![image](https://user-images.githubusercontent.com/3765696/196061797-1170f3b0-8a92-46bf-abcf-f50b3955db30.png)

**Expected behavior**: 
10 Minutes before the scheduele starts the playlist the MQTT command is fired.

**Additional context**: 
I can click the "run now" next to this command preset and it does work as expected.

**Comment by darylc** [comment]
Can you please provide log files with schedule debugging turned on?

**Comment by MrPaulAR** [comment]
As I've rolled back to 5.5 I cannot provide any more detail.  If you're
unable to duplicate this feel free to close it.

**Comment by darylc** [comment]
@MrPaulAR I have no ability to test MQTT, but I did test in the latest master, that configured events are running at T minus 10 minutes.  Did you try anything other than MQTT?

**Comment by darylc** [comment]
2023-01-01 14:34:00.010 (2272) [Schedule] /opt/fpp/src/Scheduler.cpp:447: Scheduled Item running in 600 seconds:
2023-01-01 14:34:00.011 (2272) [Effect] /opt/fpp/src/effects.cpp:163: Starting effect deer1 at channel 1
