### ISSUE TITLE
fppos upgrade does not check free space - can corrupt system

### ISSUE THREAD

**Issue by thekev** [FalconChristmas/fpp#1382]
If there’s insufficient space to complete the fppos image download, the upgrade will fail. If there is enough space for the download but not enough for the unpack, a full volume will abort at some point leaving the system in a varying state of broken. 

In the former, some cleanup may free enough space to download the image, but one must also remove the corrupt image from ~/media/uploads to get a fresh download. In the latter it may bork the system in any number of ways, some which may include an inability to use sudo, which is fatal when root has no password. 

To reproduce: install 5.x on the 4GB eMMC of a beagle. Then upgrade to 6.x fppos image.

**Comment by MrPaulAR** [comment]
This has been addressed already in the latest 5.x and 6.

**Comment by thekev** [comment]
> This has been addressed already in the latest 5.x and 6.

Oh? I was on a year-old 5.4. I’ll close this and try repro on fresh install.
