### ISSUE TITLE
F8-PB Not properly uploading configuration From Xlights to FPP

### ISSUE THREAD

**Issue by focusedonsound** [FalconChristmas/fpp#1383]
**FPP Version and Hardware**: 
FPP - 6.1.1  On Kulp Lights F8-PB
Xlights v.2022.20

**Describe the bug and Steps to reproduce**: 
Currently in Xlights under Controller Vendor KulpLights, Model F8-PB is NOT an option, however as I understand this was the predecessor of the K8-PB.

If you select K8-PB Xlights uploads work however fails to configure the controller properly causing a configuration error 

Please see the attached screen shots.
Configuration in Xlights
![f8-configured-in-xlights](https://user-images.githubusercontent.com/59902216/197042776-8832322d-6e92-42fc-adbe-c49ce2058246.jpg)

After uploading outputs
![fpp_K8_error](https://user-images.githubusercontent.com/59902216/197042778-eab934b5-9078-4fec-ad73-fadd095379b5.jpg)

How the cape is configured under channel outputs
![switching_cape_config](https://user-images.githubusercontent.com/59902216/197042780-af0a9075-bba7-4a11-96e6-5c9fabe29d22.jpg)

Changing Cape Config to below, everything starts functioning properly
![switching_cape_config2](https://user-images.githubusercontent.com/59902216/197042782-86a3b9ff-45fb-4917-82df-bb87683f2a55.jpg)

**Comment by dkulp** [comment]
With the old F8's, the F8-B and F8-PB were treated the same internally to both FPP and xLights.  Set it to F8-B in xLights and it should upload correctly.

**Comment by focusedonsound** [comment]
Great thanks for the help!
