### ISSUE TITLE
Remote FPP hosts with UI passwords show up as "Protected" on MultiSync page

### ISSUE THREAD

**Issue by jaydonoghue** [FalconChristmas/fpp#1387]
Hi - I use UI passwords for all my FPP instances. For remote devices, the Multisync page shows these players with an unknown/protected status. Is it possible to specify the name + password for the basic auth on these players so the detail shows up?

Example from my set up:
10.11.25.25 = FPP (page currently being browsed)
10.11.25.27 = remote FPP with UI password
10.11.25.29 = remote FPP with UI password removed
![image](https://user-images.githubusercontent.com/17279178/197572159-b9c33808-149d-4c17-9521-54195123d9fa.png)

**Comment by KeithSieman** [comment]
Noticed this over the Summer as well when we added a second controller to our setup.  Assumed that it was only a cosmetic bug for showing the status of the opposite player, however, learned today that it caused an issue with communication between the player and the remote and somebody disabled the password on the outdoors remote unit two weeks ago in order to fix it.

The cause of this issue appears to be 595a21bca00e8ba9b6d7412c4d58b965292e7e94 from my prior research on it.

**Comment by dkulp** [comment]
It should only be "cosmetic" as it cannot grab the status from the remote.    It should have no impact at all on normal player/remote playing of actual sequences.

**Comment by KeithSieman** [comment]
Yeah, I put it back and it seemed to be fine for the show last night.  Not sure if something got refreshed coincidentally that caused things to appear fixed at the time they tried removing it.  Odd.

**Comment by Poporacer** [comment]
Just a FYI, setting a UI password doesn't provide any security and is not typically recommended. It is like putting a lock on your fridge in case someone breaks into your house.

**Comment by KeithSieman** [comment]
> Just a FYI, setting a UI password doesn't provide any security and is not typically recommended. It is like putting a lock on your fridge in case someone breaks into your house.

That's gonna be a hard disagree from me.  Security in depth is a real thing.  If FPP ever had a known security vulnerability somewhere within the UI, a password prevents someone scanning the network from accessing it and using it as an attack vector in some way, shape or form.  Granted, someone who is competent in network security should segregate fpp to its own vlan and implement appropriate rules.  But your average user does not understand firewalls, vlans, routing tables, etc.  Even then, though, if FPP is being used on a business or educational network for whatever reason, then the suggestion that passwords are irrelevant in any application in general is an e-mail that's deleted on arrival.

Now, of course, the lack of https does support the argument that it's just a "feel good" measure in its current form.  If you're strictly saying that the current implementation of passwords within fpp isn't as secure as it could be, I'd be unable to disagree much with you there.  But even a weak implementation is better than no implementation.

There is also, of course, the argument that the SSH password is left as default most of the time, anyways.  But still, a UI password is better than nothing at all.

**Comment by Poporacer** [comment]
My point is, that if they have already gained access to your network, keeping them out of FPP isn't going to prevent much. But your points are valid

**Comment by darylc** [comment]
Duplicate of #718
