### ISSUE TITLE
Dataplicity access ignores UI credentials

### ISSUE THREAD

**Issue by snerd9334** [FalconChristmas/fpp#1388]
I have set a password in FPP via the UI settings, which works as expected when accessing FPP locally (192.168.x.x). When using the dataplicity URL it just logs straight in without a prompt for the username/password. I have tried restarting the pi after setting the ui password and have also tried a 'private' browsing window for the dataplicity URL with the same result. Logs attached.

v6.1.1 (v6.1 branch) on 3B+ with rPi-MFC

@bendudz believes this is a regression in the apache config, see here: https://github.com/FalconChristmas/fpp/commit/96f5403d0845d411a6a1e719a723d87ca368e675?fbclid=IwAR3Unmz__lOIOPEghqNGFGl5AQEKHnLM8uRvZNjnRxp-gkWEyBvDXtYH0Fc

[FPP_Logs_20221024.1614.zip](https://github.com/FalconChristmas/fpp/files/9853256/FPP_Logs_20221024.1614.zip)

**Comment by snerd9334** [comment]
@cpinkham FYI

**Comment by darylc** [comment]
I believe this is expected. Processes running on the fpp device have full access to FPP via the network without authentication.  When you run things like dataplicity on fpp this extends to dataplicity as FPP cannot tell the difference between it.
