### ISSUE TITLE
Ability to Set Effect Start Channel to That of a Model

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1389]
**Is your feature request related to a problem? Please describe.**
Over time the start channel of [FSEQ] Effects will drift resulting in additional manual steps to update the start channel when an effect is being run.  I'm lazy.

**Describe the solution you'd like**
The ability to tie an effect to the start channel of a model similar as to how shadow models are set in xLights.  This would eliminate the need to set the start channel if you move prior models around as you can tie the effect, fpp command, command preset, or even API call to have FPP do a secondary internal lookup to determine the start channel of a model based on the pixel overlay model name. 
 If it doesn't exist then don't start the effect and log the error.

The key "start channel" seems to be optional.  Add a second optional key called "model start channel" and have it support something like "Model_Name:Channel" like "Tune-To:1" which would return the first channel of the tune-to pixel overlay model.

If a user inputs both raise an error and tell them they dumb.

**Comment by darylc** [comment]
yeah I'd like this too

**Comment by darylc** [comment]
I added this.

You can select a pixel overlay model as the last parameter which it will use as the start channel for the effect.  You can offset within that overlay model by incrementing the start channel past 1.

Eg play myeffectsequence on mymodel's start channel
http://192.168.34.236/api/command/Effect%20Start/myeffectsequence/1/true/false/false/mymodel

Eg play myeffectsequence on the 10th channel of mymodel
http://192.168.34.236/api/command/Effect%20Start/myeffectsequence/10/true/false/false/mymodel

**Comment by dkulp** [comment]
FYI:  I'm not sure this was necessary.   We already look for a "background.eseq" (which can really be an fseq file just renamed) as well as a "background_HOSTNAME.eseq".     I've used this for years for my tuneto on halloween night.     The other option is you can schedule a background effect to start at the beginning of the show and then stop it at the end.     Thoughts?

**Comment by MrPaulAR** [comment]
The issue rises when the models start channel changes. Sure, a user can
update the command they fires the effect but it's another step that is
often forgot.

Also, I have about 5 models with eseq (some more than one) which results in
slot of chasing.

I agree that a solution exists I'm just suggesting an enhancement.

**Comment by dkulp** [comment]
Sorry... my comment was for #1253 .   Too many browser tabs open.  :)
