### ISSUE TITLE
No IP forwarding option

### ISSUE THREAD

**Issue by cvenet30980** [FalconChristmas/fpp#1390]
FPP 6.1.1 running on rpi 3
1. Go to 'network settings'
2. Choose wlan0 interface
3. Don't have network routing options like IP forwarding 

My home network 192.168.1.x
My gateway 192.168.1.1
My fpp wlan0 192.168.1.2
My fpp eth0 192.168.2.1
My controller ipv4 192.168.2.2.

From my computer (192.168.1.178) with add route 192.168.2.0 to 192.168.1.2, i Can ping my fpp (192.168.2.1) but not my controller (192.168.2.2)

From my fpp (192.169.1.2/192.168.2.1), i Can ping my controller (192.168.2.2)

**Comment by darylc** [comment]
Did you turn on the UI advanced mode in settings?

**Comment by cvenet30980** [comment]
No i don't

I don't see/know this option

I try this evening

**Comment by cvenet30980** [comment]
I try and you're right

I'm a poor lonesome man 😱

I have to learn to read documentation

Thks
