### ISSUE TITLE
Default Output Configuration Inconsistency

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1392]
I'm running this from a Mac (the latest Monterey version), the most recent version of Chrome, and FPP updated to the latest 6.1.1 version on a BBB running the K128.

**Describe the bug and Steps to reproduce**: 
The default configuration for the K128 outputs shows 50 pixels, 30% brightness, and 2.2 gamma. When I add smart receivers to the count via the drop-down, the new outputs (a,b,c,d,e,f) created all show a completely different default...0 pixels, 100% brightness, and 1.0 gamma.

**Expected behavior**: 
I would assume all outputs should default to the same values. I'm not sure which gamma setting is correct. I'm not so concerned about the other default values, but gamma I'm not sure of as I've never tuned that on any controller...always just left it at default. Regardless, I would assume that default values should be consistent for all outputs.

**Additional context**: 
Pic Attached
<img width="1414" alt="Screen Shot 2022-10-23 at 11 39 18 PM" src="https://user-images.githubusercontent.com/1048868/197904672-25713fd6-f5c3-4062-901f-1b8cb401a9fd.png">

**Comment by dkulp** [comment]
There's really nothing that can be done.   There isn't any such thing as a default string configuration for "new strings".   When FPP adds strings to the configuration, it uses it's default of 100%/1.0.     

On capes with eeproms (or virtual eeproms), the cape can provide a default configuration.  That's what you are seeing is the default config provided for the 128 ports on the K128.   Thus, the only "fix" would be to change the firmware on the K128 to use 100%/1.0, but even updating the firmware wouldn't change your case as that default is only read the very first time the board is booted up.   If there is a configuration already, it's not looked at again.

Anyway, this is pretty much working as expected at this point.

**Comment by nmiller0113** [comment]
Thanks @dkulp, makes sense now! One question, though, is what should gamma be set to by default? I understand what gamma does, but I don't know what 1.0 is vs 2.2...and whether that's relative to the controller type or not. I've never tuned gamma before, so I'd much rather take the default "standard" or zero, as in zero effect modification. In other words, does 1.0 == 0 gamma change, or does 2.2 == 0 gamma change on the K128.

I hope my question makes sense.

**Comment by nmiller0113** [comment]
@dkulp, just following up on my last note before I this before I close it. Should I be setting the default for all my ports on the K128D-B to 2.2, or 1.0? Is the proper default 2.2?

**Comment by dkulp** [comment]
Gamma is completely a personal preference.  I generally use 2.2 for most of my strings, but others prefer 2.0 and many others prefer leaving it at 1.0 except for things like P5 panels displaying videos.

**Comment by nmiller0113** [comment]
Thanks, @dkulp! I completely understand the personal preference part, I just assumed the controller had some influence on it so that a baseline would vary from controller to controller. Regardless, I've set mine to 2.2 based on what was defaulted with the K128, and everything seems to look good. Thanks again!
