### ISSUE TITLE
Channel Outputs for LED panels orientation arrows not changing panel direction v6

### ISSUE THREAD

**Issue by bcstuff** [FalconChristmas/fpp#1395]
Channel Outputs for LED panels orientation arrows not changing panel direction
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 6.1.1 running on RPi 4 2GB*
and
*FPP 6.0 running on RPi 4 2GB*

*Rpi 4 has ethernet out to a Colorlight 5A-75B v8 Panel Controller for P5 panels*

**Describe the bug and Steps to reproduce**: 
1. Go to 'Settings > Channel Outputs > LED panels '
2. Click on 'Panel Orientation arrows to change the direction the panel is facing'

**Expected behavior**: 
Changing the arrow direction should change the panels orientation, so a panel installed with the arrow down should be able to be displayed right side up.

**Additional context**: 
This happens in FPP 6.1.1 and 6.0, I installed at 5.5 and the panel orientation arrows work as expected.

**Comment by darylc** [comment]
I tested this on the latest master, when I change the UI the underlying config file is changing correctly.  Can you please provide more information?

**Comment by Poporacer** [comment]
This is working correctly on 6.3 and Master. I can change the panel orientation in FPP and the panels will display per the orientation defined. Can you follow up?

**Comment by ghormann** [comment]
Closing as in Need Info state for 6 months
