### ISSUE TITLE
Limit default port brightness setting to prevent blowing fuses

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1397]
**Is your feature request related to a problem? Please describe.**
It has happened several times that I blow the fuses the first time I send a model from xLights to a new controller or prop ... because I forgot to lower the brightness in xLights.

**Describe the solution you'd like**
I would like the controller to automatically limit the current to less than the fused value.
In the absence of current monitoring, estimate the current based on node count * node current, and limit when the current exceeds fused value.
Or a simpler alternative is to allow me to configure a brightness value that is not to be exceeded even when xLights pushed config.

**Describe alternatives you've considered**
Blow fuses, fix fuses, kick myself for not remembering to lower the brightness, repeat. 

**Additional context**
I [asked](https://github.com/smeighan/xLights/issues/3491) xLights to lower the initial default value, request met with strong resistance.

**Comment by darylc** [comment]
@ptr727 I'd petition your cape manufacturer, they provide the default brightness values and FPP honors those.
