### ISSUE TITLE
DRM Frame buffers not working

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1398]
Hi, would it be possible for future development of the Virtual Matrix code to be based on the standard PI frame buffer vc4drmfb (V3D Direct Rendering Manager DRM driver) rather than the older BCM2708 frame buffer ?

I noticed this when I installed FPP manually on top of a standard Rasberian build , basically the virtual matrix did not work (see picture below) even though FPP played mp4 videos fine as part of a sequence (I presume that part of the code is based on VLC code that is compatible with the newer DRM frame buffers). 

I have tested this on v5.5 through to v6.1.1 and they all currently appear to need the older BCM2708 frame buffer for the virtual matrix to work. As mentioned the MP4 video playback on all these versions via the DRM frame buffer in FPP works fine.

FYI: It is the same results if I install in manually on a standard build or use Docker containers on both PI4 or Intel NUCs

I am also hoping that the use of DRM frame buffer driver will increase the hardware compatibility of the virtual matrix code so that it will work on other hardware platform such as Intel PC's (i915drmfb) without the need to use "software scaling" that in turn will fix the ongoing issue I raised here https://github.com/FalconChristmas/fpp/issues/1328

Note: The video playback as part of a sequence currently works fine on both the standard PI vc4drmfb and on the intel frame buffer i915drmfb

Testing results: (Virtual Matrix not displaying)

On a standard /default raspbian build
sudo fbset -i

mode "1920x1080"
geometry 1920 1080 1920 1080 16
timings 0 0 0 0 0 0 0
accel true
rgba 5/11,6/5,5/0,0/0
endmode

Frame buffer device information:
Name : **vc4drmfb**
Address : 0
Size : 4147200
Type : PACKED PIXELS
Visual : TRUECOLOR
XPanStep : 1
YPanStep : 1
YWrapStep : 0
LineLength : 3840
Accelerator : No

![4F80FF5B-625A-4417-BEAA-CD387D4705CC_1_105_c](https://user-images.githubusercontent.com/69304144/199701334-cf300805-b648-40a9-a3e5-ba6947404c36.jpeg)

However if I altered the standard /boot/config.txt and commented out #dtoverlay=vc4-kms-v3d the base Docker O/S changes the frame buffer to BCM2708 FB and at that point the virtual matrix functionality works.

sudo fbset -i

mode "1920x1080"
geometry 1920 1080 1920 1080 16
timings 0 0 0 0 0 0 0
accel true
rgba 5/11,6/5,5/0,0/0
endmode

Frame buffer device information:
Name : **BCM2708 FB**
Address : 0
Size : 4147200
Type : PACKED PIXELS
Visual : TRUECOLOR
XPanStep : 1
YPanStep : 1
YWrapStep : 0
LineLength : 3840
Accelerator : No

At that point the Raspberry Pi 4 virtual matrix works exactly as expected (same as the distributed FPP build) however obviously this does not work for intel PC's :-( 

![1101B305-92E7-4BDD-B430-159340B793BD_1_105_c](https://user-images.githubusercontent.com/69304144/199701534-c17c8b2e-0d7b-49e1-a2b9-ed7206068e11.jpeg)

If you need any further information please let me know
Regards & thanks

**Comment by dkulp** [comment]
master branch now has the ability to use DRM API's.   Please test if possible.

Note: the reason for using the old framebuffer code on the Pi is specifically for the "hardware scaling".  With the DRM code, at this point, we have to set the resolution for the framebuffer to one that the monitor supports and then use the software scaling (pixel size).   That was one of the reasons for using the older BCM2708 framebuffer.    I haven't had any luck getting vlc to play a video with the newer DRM stuff though.
