### ISSUE TITLE
Enhancement Request: Global remap of RGB for P10 Panels in Display testing

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#140]
When use the display testing mode in BBB, when I select R I get red out put, but when I select G I get blue and B I get green. I had the same issue  with I did direct connect to pi without BBB.

Can we add a way to allow the user to define a panel type?
R-G-B
R-B-G
....

If not then the use just has to be aware of it and compensate when they build the models in xLights.

**Comment by JonB256** [comment]
Pat, on the Channel Outputs / BBB config screen, in that long list of String Outputs, will changing RGB order there fix this?

**Comment by JonB256** [comment]
Pat, playing with the Test Mode page, my P10 panels do not match the RGB sliders.

But, EVERYWHERE else, they are correct. If I draw on the Grid, the colors are right. My xLights output is correct. Scrolling text is correct. 

So, there is "something" goofy but it only seems to involve those sliders.

**Comment by cpinkham** [comment]
The color order on the testing page is tied to the raw channel numbers:

1 - R
2 - G
3 - B
4 - R
5 - G
6 - B
etc..

If you start a display item on channel 3 then the 'RGB' on the test screen won't match the device.

Pat, is this possibly your issue and your panels are in fact really RGB order?

**Comment by patdelaney** [comment]
When we started testing these panels, I have always had this issue. It's
the same via direct attached to Pi via Chris's header or the adafruit
Header, or even breadboard wiring. As a test I put the BBB into Bridge mode.
I configured xLights to push to that panel. I went to the Test tab of
xLight and selected all nodes.. I went to the RGB tab and Selected
background only and raised the RGB sliders one at a time. The Color order
off ALL 40 boards I have is RBG. I can get around the issue in xLights by
defining the panel model as RBG.

It's not a huge deal as long as people are aware that the color order on
some boards is not "standard".

Pat

**Comment by cpinkham** [comment]
I pushed the color order setting for LED Panels but need to test it a bit further to make sure that I got the various bits of right since I wrote it on a plane.  If not, it's just a few 'if' statement corrections.  Closing ticket for now since testing is on my 'must have before release' TODO list.

**Comment by patdelaney** [comment]
I can test it, because I have the goofy panels. what area should I be
testing?
