### ISSUE TITLE
Testing Sequences from FPP in Remote Mode (P5s)

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1402]
**FPP Version and Hardware**: 
Example: FPP 6.2 on Pi4

**Describe the bug and Steps to reproduce**: 
Clean install of FPP with the P5 (colorlight) matrix defined.
Set to Remote
Create a sequence in xLights with bars, rendor, save, FPP connect
Status/Control > Display testing then click sequence button
Play the sequence
The panels are blank.  Note, this did play 1 time.

Change from Remote to Player
Play the sequence in the test window.  Plays fine
Play the sequence in the status page.  Plays fine.

Change back to remote
Play the sequence from test page.  Blank output.

**Comment by darylc** [comment]
The intent is that all ways to play sequences are disabled when in remote mode as they will not work.  There was already code to do this inside the file manager etc.  I've updated the code to ensure this one is hidden as well.
