### ISSUE TITLE
OS upgrade UX is confusing, display version does not match dropdown version

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1406]
**Is your feature request related to a problem? Please describe.**
When looking at the About UI, the user is presented with a mixture of status and versions:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/2061579/201146998-7d38ff03-6831-466b-bfb0-73a28f3e3586.png">

In a categorized UI one may have expected versions and status to be grouped together, e.g.:
![image](https://user-images.githubusercontent.com/2061579/201149794-fdfd8321-37a7-4040-bb86-3a2fe6a55854.png)

A non-git-aware user has no idea what the git hashes means, as such the current semver and available semver is arguably more important to most users. Stated differently, what do I do with the hash printed in the UI, other than compare the hashes for the purpose of have vs. what is available?

In the current UI there is no indication of what the currently available released version number is, i.e. should I perform an upgrade, and if I were to upgrade, what version should I expect?

If there is a need for git branch vs. git release use, then an alternate common method may be to use channel releases, e.g. release, beta, nightly, or current.

The primary problem with the reported and available version is that there is no correlation between the reported OS version, and available OS versions.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/2061579/201151485-9df85531-b307-4015-8b35-1e583f2b416a.png">
![image](https://user-images.githubusercontent.com/2061579/201153208-de4c4f67-470f-4003-ae3a-78c3a7ed7b6c.png)

How am I supposed to know if I need to upgrade when the dropdown does not list the OS version that I will be getting?

**Describe the solution you'd like**
- Use logical information grouping, i.e. FPP versions in one group, OS versions in a group, hardware information in a group, system status in a group, etc., do not information in unrelated groups.
- Report logical version availability, other than current vs. available, hashes serve little purpose in a UI, specifically report the current FPP version, and the available FPP version.
- If there is strong user demand for git based deployments vs. released/tagged/semver CICD style deployments, use branch/channels, e.g. main, develop, v7, etc.
- For OS upgrades report both the included FPP version and the OS build version.
- For OS upgrades make sure that the FPP version reported, and the OS build version reported, matches the resulting FPP and OS build version after performing the upgrade.

**Describe alternatives you've considered**
Hit upgrade and see what happens ;)

**Additional context**
Related to a [similar](https://github.com/FalconChristmas/fpp/issues/1169) issue that just changed the version schema, and did not really address the ambiguity.

**Comment by Poporacer** [comment]
This is similar to #1303  and 1303 has been tagged as a ToDo in the 7.0 project so it on task to be implemented.
