### ISSUE TITLE
FPP offline after OS upgrade

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1407]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP 6.2 on BBB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to About and Click "Upgrade FPP".
2. Close the multiple windows that pop up (UX can improve).
3. Click the "Upgrade FPP to 6.2" banner that pops up.
4. Close the UI, click reboot (UX can improve to put reboot step in upgrade flow)
5. Go back to About and click BBB-6.2 OS in dropdown, and click Upgrade OS.
6. Go and do something while the upgrade happens.
7. Come back, FPP is not on the network.
8. Look at OLED, reports no network, ffpd not started.
9. Power cycle BBB, FPP back on the network.

**Expected behavior**: 
After a FPP or OS upgrade I expect the device to come back on the network, and no manual user interaction should be required.
In my case I upgraded two Kulp boards, one a test board that I could easily reach and power cycle, one I need to get a ladder to go and power cycle today.

**Additional context**: 
Problem initially reported on FB, other users report experiencing similar behaviors.

**Additional Attachments**
[FPP_Logs_20221110.1709.zip](https://github.com/FalconChristmas/fpp/files/9983159/FPP_Logs_20221110.1709.zip)

**Comment by ptr727** [comment]
I remote power cycled the non-test unit, it came back up, but it did NOT update the OS, so presumable something went wrong during the update.
This unit, unlike the other one, did respond to pings, but did not accept SSH or HTTP requests.
Logs attached.
[FPP_Logs_20221111.0018.zip](https://github.com/FalconChristmas/fpp/files/9985458/FPP_Logs_20221111.0018.zip)

**Comment by darylc** [comment]
We believe we have fixed this in issue #1449  The next fppos release should work correctly and not require a power cycle.
