### ISSUE TITLE
USB-FTDI Adapter not working on Pi Zero W

### ISSUE THREAD

**Issue by lxgenie** [FalconChristmas/fpp#1410]
I am unable to get a USB-FTDI DMX adapter to work on a Raspberry Pi Zero W, it's not recognised at all and doesn't show at all when using lsusb.

I believe this issue is related to USB tethering on the Pi Zero as I have exactly the same adapter working without issue on a Raspberry Pi 3.

Also running with a clean install of Raspbian, on the Pi Zero W, the adapter is detected without an issues.

I've also asked this question on the Falcon Christmas Forum and it was suggested that I try removing the USB files from /etc/systemd/network. I've removed usb0.network and usb1.network and whilst this does stop the USB tethering interface from being created, the adapter is still not found in lsusb.

I've also attempted to remove the section in /opt/fpp/scripts/functions that relates to creating the USB tethering interface (discovered from issue #574). This again prevents the interface being created but the adapter is again not found. I've just tried applying both of these 'hack' simultaneously but again to no avail.

Is there anything else that can be done to make this work? I don't mind if it's a bit of a hack that will get broken when updating, I'm just really keen to get this working. In the supported hardware platforms on the wiki, it says USB Serial Adapters are compatible with Pi Zero so I don't feel like I'm doing anything out of the ordinary!

Any assistance greatly appreciated.

[FPP_Logs_20220913.0214.zip](https://github.com/FalconChristmas/fpp/files/9989902/FPP_Logs_20220913.0214.zip)
[FPP_Logs_20220913.0214.zip](https://github.com/FalconChristmas/fpp/files/9989909/FPP_Logs_20220913.0214.zip)

**Comment by darylc** [comment]
no sign of it in the syslog/messages file.  Can you send the output from an 'lsusb -a' command?

**Comment by ghormann** [comment]
>  Can you send the output from an 'lsusb -a' command?
@darylc  Did you mean lsusb -a or lsusb -v?  I didn't think `-a` was a valid option.  

In the trouble shooting output I see the following which is interesting.

```text
===================================================================
Title  : USB Device Tree
Command: sudo lsusb -t
-----------------------------------
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc2/1p, 480M

===================================================================
Title  : USB Devices
Command: sudo lsusb -v
-----------------------------------
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
```

My suggestion would be to
1) Unplug the FTDI 
2) reboot the PI
3) Log into the console of the PI
4) run "dmesg" -- Note the last entry. 
5) Plug in the FTDI device
6) run "dmesg" -- and look to see if any new log entries were added. 

If there is a kernel module issue, it will probably show up here...

**Comment by ghormann** [comment]
Closing. No response from OP.
