### ISSUE TITLE
Reading cape type to prevent accidental application

### ISSUE THREAD

**Issue by algerdes** [FalconChristmas/fpp#1412]
I have two Kulp 40 output cards.  A K40PB and a F40PB.  Application of the wrong one from within xLights caused errors on both of them.  I use one as the backup for the other, therefore need to manually change when I have to replace one for whatever reason.

Is there a way to read the cape information (available in help -> cape information) and send a warning to the user that he/she has set it wrong when trying to upload to fpp from xLights? 

I am registering this here because fpp is the location of the cape information.

**Comment by OnlineDynamic** [comment]
Think this is probably a change on the xlights side required - the fpp api makes the cape details available:
e.g.
http://<fpp cape ip address>/api/cape
(need to replace IP address your fpp address)

**Comment by darylc** [comment]
xlights shows an error to warn about this these days
