### ISSUE TITLE
6.2 + master .. remote video is lagging and freezing

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1418]
Seeing a couple of folks in zoom room with the same issue. Suggested turning off hardware decoding, suggesting to turn off the timing packet sync option. Was that option removed in master - didnt see it when set to developer UI.
Anything to suggest as a fix / workaround for this (6.2 was on a pi, master was for a BB)
Both were the usual remote setups driven from a master pi.

(I personally had to ignore timing packets for my vm to work - rolled back to 6.1 as well)

![image](https://user-images.githubusercontent.com/4643499/204096152-98c8a364-0c99-405b-b81e-0e74cc54fb09.png)
![image](https://user-images.githubusercontent.com/4643499/204096155-ce4077b0-35d5-4628-8518-b46ccc0c5e4f.png)

**Comment by derwin12** [comment]
Another case reported...

![image](https://user-images.githubusercontent.com/4643499/204106443-f2d2b482-69ff-4310-91ec-f78102ab3244.png)

**Comment by patdelaney** [comment]
Can you unload the video file that you are using? What type of Pi?

**Comment by ghormann** [comment]
@derwin12  Can you use Content Setup -> File manager and then on the Logs tab click "Zip' to create zip file and upload those logs to this Issue?  It would also be helpful to have some information on the video file.  (dimensions, length, frame rate).

**Comment by derwin12** [comment]
The videos are created via the Model->Render and Export .. compressed mp4

**Comment by derwin12** [comment]
I rolled back to 5.5 for my show .. so those logs are long gone.

**Comment by ghormann** [comment]
Without logs, this will be difficult to diagnose.  Closing
