### ISSUE TITLE
If you enable BBB output, fppd won't restart

### ISSUE THREAD

**Issue by darylc** [FalconChristmas/fpp#142]

**Comment by darylc** [comment]
Found a workaround:
When fpp boots, ssh in, cd /opt/fpp/external/LEDscape;bin/f​ire strips.config press ctrl-c then press start fppd in web interface

**Comment by JonB256** [comment]
Darylc, I have this problem, too. Followed the steps up to the ctrl-c but "start" in the web interface did nothing.

am I missing a step?  will just do bridge mode for now.  Jon Back

**Comment by JonB256** [comment]
fpp@JON1_BBB:/opt/fpp/external/LEDscape$ bin/fire strips.config
read 6 bytes 'ws2812'
read 6 bytes '240,32'
strips: 240,32
Segmentation fault

**Comment by JonB256** [comment]
Darryl, if I uncheck the "enable BBB String Cape" box, it the FPP will start and work.

**Comment by JonB256** [comment]
Now, I'm trying to run an F4-B Cape, so I need that box checked.
When checked, the FPP will NOT start.

**Comment by darylc** [comment]
All I can really say at this point is the F4-B works for me when following
the instructions I posted above.

**Comment by JonB256** [comment]
I ssh in and enter the following 2 commands. No problems. 

cd /opt/fpp/external/LEDscape
bin/f​ire strips.config 

It is this one that I don't follow. 
press ctrl-c then press start fppd in web interface

**Comment by darylc** [comment]
you have to press control and c key to stop fire running

then you need to start fppd via the start button in the web interface

**Comment by JonB256** [comment]
It stops itself with an error message about a segmentation fault. 

fpp@JON1_BBB:/opt/fpp/external/LEDscape$ bin/fire strips.config
read 6 bytes 'ws2812'
read 6 bytes '240,32'
strips: 240,32
Segmentation fault
fpp@JON1_BBB:/opt/fpp/external/LEDscape$ ^C

I guess I'll wait for a patch

**Comment by darylc** [comment]
Segmentation fault is bad, I don't get that.

**Comment by cpinkham** [comment]
Can you guys make sure you are on the latest code?  I committed a change to the master branch on Monday of last week that should have fixed this.  I am running the latest code (hash 2106a2b) on my BBB connected to a F16-B and can boot from power-off and fppd starts up fine and I can control lights on the F16-B using FPP.  If you are looking at the version string in the header, it will have a 'g' prepended to the git hash.

**Comment by JonB256** [comment]
I installed this BBB yesterday morning from scratch. New SD card.
It shows the correct version across the top.
Version: v0.3.0-727-g2106a2b (master branch)  Host: JON1_BBB

I tried telling it to be an "F16-B" also with no luck. I only have the F4-B.

**Comment by cpinkham** [comment]
The model number only affects the number of outputs it tries to drive, so that shouldn't change the outcome much.

I will see if I can get you guys a copy of the eMMC image to test with.  I have a few things to clean up on it, but could manually make those to give you a preview image to test with before I get the scripting part done.

**Comment by JonB256** [comment]
Thanks, Chris.  I'm willing to try most anything this far ahead of Christmas. :)

**Comment by JonB256** [comment]
From Chris (in the Falcon forum F4-B posting) - if you ssh into the Pi and run the following:

cd /opt/fpp/src/pru
sudo make release

Then the fppd will restart

**Comment by cpinkham** [comment]
This should be fixed in master and stage now.  fppd will try to load PRU .bin files from fpp/src/pru/ if fppd is run from fpp/src
