### ISSUE TITLE
K128D-B Channel Output Screen Slowness

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1420]
**FPP Version and Hardware**: FPP 6.2 running on BBB

**Describe the bug and Steps to reproduce**: 
On a fresh install of 6.2:
1. Go to the Channel Outputs section
2. Notice all of the Start Channels are overlapping by default (this is what I believe to be the problem)
3. On the same page, go to modify the Pixel Count on Port 1...It will change, but the delay is ~8-10 seconds

**Expected behavior**: 
Channels do not overlap to start so that there are no delays in the UI

**Additional context**: 
I've worked around this by doing a clone string and changing everything so it doesn't overlap, but it probably shouldn't default to requiring this.

**Additional Attachments**
I can include logs and/or screenshots, but I doubt this will be required since it is so easily reproducible.

**Comment by darylc** [comment]
Can you please provide screenshots or a video more information?  None of us have a K128D so we have can't understand your bug report.

**Comment by nmiller0113** [comment]
@darylc, I created a video showing how I reproduce it. It has audio explaining everything as I go through it. Here is the link  (https://drive.google.com/file/d/1jYLcZ2mr1f6qcRfv7-YpSEVOPZpN7P7y/view?usp=share_link)to the video as it was too large to upload to Git directly.

You'll also see that I discovered another bug during the video. I filed another bug report on it (https://github.com/FalconChristmas/fpp/issues/1454)

**Comment by darylc** [comment]
sorry can't replicate this and I don't have a K128D, I think Dan is the only FPP dev with a K128D

**Comment by nmiller0113** [comment]
I hope @dkulp will be able to find the time to give it a look in the future :)

**Comment by dkulp** [comment]
Pushed a change, can you please do some testing to make sure all the overlap verifications and such still work?

**Comment by nmiller0113** [comment]
@dkulp, definitely. I assume I need to change to master for this, or did you push to the standard updates?

**Comment by dkulp** [comment]
You'll need to flip to master.    Also, I sold my last K128 so I cannot test any of the BBShiftString things right now, but can you try the new Test pattern things on the same page?   I have a few more I hope to get added tonight.

**Comment by dkulp** [comment]
Note:  before flipping to the master branch, you MAY want to ssh in and cd to /opt/fpp and run:
'''ccache --set-config secondary_storage='http://kulplights.com/ccache|layout=flat|read-only=true''''

That should make flipping to master branch quite a bit faster.

**Comment by darylc** [comment]
@nmiller0113 How did you go?

**Comment by nmiller0113** [comment]
@darylc @dkulp, apologies for not getting back to you sooner on this. I've been out of town, and just getting back this afternoon. I'll test this out over the weekend!

@dkulp, as far as testing other things, I'm more than happy to! Just let me know what you need. Also, I hope you're getting more K128's in the future as I always want to have a backup handy :)

**Comment by nmiller0113** [comment]
@dkulp @darylc I tested the fix in master and it no longer has any slowness/delay, even when all the channels overlap.

@dkulp, I'm not familiar with the issue you mentioned "BBShiftString things right now, but can you try the new Test pattern things on the same page?". What should I be looking for, or what did your fixes correct for the issue you mentioned? I'm happy to test whatever you'd like!

**Comment by darylc** [comment]
@nmiller0113 Thanks.  Re Test Dan would be talking about the test button (I don't remember exactly what its called on the Pixel outputs page for your K128).
