### ISSUE TITLE
K128D-B Flashes Restart FPPD Twice

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1421]
**FPP Version and Hardware**: FPP 6.2 running on BBB

**Describe the bug and Steps to reproduce**: 
I'm not sure if this is a bug or just a UI issue. This is not impacting the performance of the device.
1. Go to the Channel Outputs section
2. Make any changes and hit save (actually, you can just hit save once w/o changes)
3. The restart FFPD required notice will pop up
4. Click the Restart FPPD button
5. The restart FFPD required notice will disappear and then pop back up a split second later, and it will show FPPD Stopped for a second...then the restart notice will disappear all by itself.

One thing to note is that I am running a Vast FM Transmitter, so I have FPPD start delayed 10s, but I thought that was only for boot, so I'm assuming it has nothing to do with this. I first noticed this issue while making changes noted in https://github.com/FalconChristmas/fpp/issues/1420.

**Expected behavior**: 
The FPPD restart notice doesn't flash twice.

**Additional context**: 
I can include logs and/or screenshots, but I doubt this will be required since it is so easily reproducible.

**Comment by darylc** [comment]
Does this only happen on a K128D or does it happen on your other controllers too?

**Comment by nmiller0113** [comment]
I don't have any controller but the K128D, so I cannot comment on others. Here is a video capture of it.

https://user-images.githubusercontent.com/1048868/211452998-8f34dbe3-d470-4d7c-9f12-7ec769bae9fb.mp4

**Comment by darylc** [comment]
sorry can't replicate this and I don't have a K128D, I think Dan is the only FPP dev with a K128D

**Comment by nmiller0113** [comment]
@darylc I saw an update earlier this week, but it's not showing in the case...which is strange. Either way, I saw that you mentioned you don't have a K128 to replicate this, so I hopefully @dkulp will get a chance to test it out. Thanks!

**Comment by nmiller0113** [comment]
@dkulp @darylc when testing other fixes in master I noticed that this no longer happens. Closing it out now.
