### ISSUE TITLE
Audio Test 

### ISSUE THREAD

**Issue by thekameleon** [FalconChristmas/fpp#1422]
So we have the ability to test the displays. In my scenario, I have multiple audio outputs, such as outdoor speakers and FM radio transmitters. It would be helpful for setting levels to have an audio test feature where it would play audio and allow an individual to properly set their other audio devices. Yes, technically you could create a sequence. With that mindset, I could create a sequence to test my display, but there are test features built-in for testing ports and pixels.

**Comment by darylc** [comment]
I've added a feature in the latest master that allows you to play audio files straight from the status page without having to create a playlist.  I'd suggest uploading an audio file, and playing it on repeat would be a reasonable solution to this rather than a dedicated test functionality.

**Comment by thekameleon** [comment]
I was hoping for a cleaner solution. Something that includes an audio track that is known to work by the developer. If issues arise it could be related to issues that may work in one environment but not another environment. I'm thinking of this from a unit test point of view. It's your choice though

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 3, 2023 at 6:06, ***@***.***> wrote:   


Closed #1422 as completed.

**Comment by darylc** [comment]
I think the entire point is for the end-user to provide their audio track when trying to set their audio configuration/levels because their audio tracks likely have different volume levels to anything FPP could provide by default.
