### ISSUE TITLE
Remote Video either not starting or continuing to restart over and over..

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1423]
We have been seeing this issue multiple times in Zoom... Not quite same as issue #1418 (but similar) so starting a new issue. 

Two raspberry Pi.  Master started out at 5.3 and remote started out as 6.0.2.  When playing a remote video media, the video seems to try to start, it shows playing in multisync page but the time never progresses.  It appears to try to start and maybe restart and restart.  Logs show messages about " picture is too late to be displayed (missing 98 ms)". We upgraded the remote to 6.2 with fppos and has same issues... We then upgraded the master to 6.2 as well.. .We told the remote to "ignore media sync packets" and no change... This user DK that we were helping also mentioned that when she stopped the master player then the video would play on the remote.  Almost like the master player was causing interference with the remote actually starting the video.   We can play the video directly on the remote pi just fine.   I have one of her videos as well if you would like it. 

[FPP_Logs_20221129.zip](https://github.com/FalconChristmas/fpp/files/10111002/FPP_Logs_20221129.zip)

**Comment by darylc** [comment]
Ideally need video file, and also log file with multisync debugging

**Comment by darylc** [comment]
I contacted user DK, got the actual files in question, and I can't replicate this issue :(

This is very frustrating as I saw this issue happen first hand to a couple of users through the season.

**Comment by ghormann** [comment]
Closing as Unable to replicate.
