### ISSUE TITLE
Checking DeDup on entries using DDP created huge lag and missing data

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#1424]
The FPP Manual (v5.5) discusses DeDup as a way to reduce network bandwidth.
Seems to work on E1.31 outputs but not on DDP outputs (Raw). It created tremendous lagging and glitches on matrices. Immediately went away when unchecked the option. 

Would suggest graying out that option on Outputs using DDP. (or just ignore it)

**Comment by darylc** [comment]
From testing I did last night, I actually think dedup isn't working properly on e1.31 either, it seems to miss sending frames that did change.

**Comment by dkulp** [comment]
This is fixed in 7.4
