### ISSUE TITLE
Not able to set time zone, reboots set time to UTC default time zone.

### ISSUE THREAD

**Issue by 82280zx** [FalconChristmas/fpp#1426]
**FPP Version and Hardware**:  6.2 Raspberry Pi 4

1. Go to Status/Control
2. Click on  Settings then select Time
3. Drop down menus are blank.
4. See attached Snip.

**Expected behavior**: 
To be able to select time zone.

**Additional context**: 
Time is showing 5:53am and a day ahead... 12/2/22 the utc time is correct but my local time is 10:55pm and 12/1/22.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20221202.0556.zip](https://github.com/FalconChristmas/fpp/files/10138460/FPP_Logs_20221202.0556.zip)

![image](https://user-images.githubusercontent.com/10771468/205224898-fbd3a409-7284-43d2-ad4f-6bbeafcece93.png)
![image](https://user-images.githubusercontent.com/10771468/205225408-f859319a-a045-4a48-af9d-e78620e9faaf.png)

**Comment by diceman3807** [comment]
I have a related issue. I cannot set the date/time. My date stays at Sept 13 and and hour and a half off.

I tested ssh to the FPP and running 'sudo raspi-config' and that did not fix the issue
timedatectl status shows:
               Local time: Mon 2022-09-12 22:09:34 EDT
           Universal time: Tue 2022-09-13 02:09:34 UTC
                 RTC time: n/a
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no

<img width="1867" alt="FPP TIme" src="https://user-images.githubusercontent.com/85205939/206625104-108dbf04-d67a-452e-b7ae-6bd560f9d0b4.PNG">

**Comment by diceman3807** [comment]
I just powered off the system to move it outside, and when i powered it back up it appears to have reset to the same time as yesterday....
<img width="344" alt="FPP TImev2" src="https://user-images.githubusercontent.com/85205939/206765373-3cce4ec3-acc6-4065-bea9-63ba47700b36.PNG">

**Comment by nmiller0113** [comment]
@diceman3807, your problem sounds different. Is your device able to reach the internet to sync its time?

**Comment by 82280zx** [comment]
I ended up reimaging our raspberry pi after taking a backup and it seemed to have fixed ours, the upgrade seemed to have caused us the grief =/

**Comment by nmiller0113** [comment]
That makes sense @82280zx for your specific issue. What @diceman3807's issue sounds like is it's not reaching a time sync source.

**Comment by diceman3807** [comment]
I should have done another test...I tried pinging the IP address of 8.8.8.8 and that worked, and i was taking my DNS from my DHCP server that serves the rest of my network, which works for all my windows systems, but for some reason didn't work for FPP. I tested by pinging some sites by name and they failed, so i changed my DNS to 8.8.8.8, rebooted and it worked. Sorry for the bad info.

**Comment by nmiller0113** [comment]
@diceman3807 if you don't have a real-time clock on board with a good battery, it will never remember the time. You can always buy one of these and add the RTC option. That's what I use.

**Comment by diceman3807** [comment]
Thanks for the info!
