### ISSUE TITLE
MP3StreamerStart.sh script doesn't behave correctly unless run as an FPP Command

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1427]
**FPP Version and Hardware**:  FPP 6.2 running on BBB

**Describe the bug and Steps to reproduce**
I'm experiencing the issue mentioned using the MP3Streamer scripts from the Script Repo. The MP3StreamerStart.sh script seems to work fine when run from the file manager or called from a playlist using the standard script option (Not the FPP Command run script option). When I run the MP3StreamerStop.sh from the file manager or called from a playlist using the standard script option (Not the FPP Command), it starts to fade the volume as intended, but before it completes its fade, it kicks back to full volume and never completes stopping the stream. If I run that same script MP3StreamerStop.sh from the FPP Command run script option, it always stops.

1. Load the MP3Streamer scripts from the FPP Script Repo
2. Edit the MP3StreamerStart.sh script to add your station (mine is http://stream.themillerhome.org:8000/lights)
3. Run the MP3StreamerStart.sh script from the FPP File Manager
4. Run the MP3StreamerStop.sh script from the FPP File Manager
5. It will start to fade the volume, then kick back to full volume, and the stream will never stop

**Expected behavior**
The script should complete its intended behavior from the file manager or called from a playlist using the standard script option, similar to how it behaves when run from the FPP Command run script option.

**Logs Attached**
[FPP_Logs_20221202.1844.zip](https://github.com/FalconChristmas/fpp/files/10143617/FPP_Logs_20221202.1844.zip)

**Comment by SpudGunMan** [comment]
Reviewing the script I am not sure the kill command going to work without a sudo? 

And ideally something to the effect of, 

sudo killall -9 cvlc 

As other scrips use.

**Comment by nmiller0113** [comment]
@SpudGunMan I should have also mentioned that this worked in version 5.x without issue and the script works via the FPP Command "run script", so why would it work in 5.x as well as the FPP command w/o sudo?

**Comment by darylc** [comment]
cvlc is no longer used in fpp, so that kill will do nothing.

**Comment by SpudGunMan** [comment]
Used in that script it appears - could be why it's extra wonky!

**Comment by SpudGunMan** [comment]
> @SpudGunMan I should have also mentioned that this worked in version 5.x without issue and the script works via the FPP Command "run script", so why would it work in 5.x as well as the FPP command w/o sudo?

I don't know as I don't dig that far, I use the after hours audio plugin because this one didn't work.

**Comment by nmiller0113** [comment]
> cvlc is no longer used in fpp, so that kill will do nothing.

@darylc cvlc is still available to use and works to start the stream. My problem is stopping the stream :) The script is from the FPP script repo. Here is the output of calling cvlc from the CLI...it must symlink to vlc I assume, I've not checked:

fpp@fppmain:~$ cvlc
VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-20176-gc83387aca2)
[0172e7a0] dummy interface: using the dummy interface module...

**Comment by nmiller0113** [comment]
> > @SpudGunMan I should have also mentioned that this worked in version 5.x without issue and the script works via the FPP Command "run script", so why would it work in 5.x as well as the FPP command w/o sudo?
> 
> I don't know as I don't dig that far, I use the after hours audio plugin because this one didn't work.

I've used the after hours plugin as well, but I'd rather not if I didn't have to just because it loads mpd which is not monitored or maintained by the FPP project or any of its updates...so I'd have to manually update. I just prefer to keep the services limited to those included in the appliance...hence the reason I'd prefer to use only the script to run the stream via vlc

**Comment by SpudGunMan** [comment]
You try changing the kill command I don't think it's gonna work I think it's killing a useless pid from the glance I took. 

Change your kill command

**Comment by darylc** [comment]
@nmiller0113 How did you go changing your kill command as SpudGunMan suggested?

**Comment by nmiller0113** [comment]
@darylc @SpudGunMan, I hadn't had a chance to mess with this during my show season. Now that it's over, I see what happened and why it wasn't working. If you look at the script, the kill command is calling for an ID to be killed, not cvlc...though cvlc absolutely still exists:
```
fpp@fppmain:/usr/local/bin$ ls -la
total 84
drwxr-xr-x  2 root root  4096 Nov  3 13:54 .
drwxr-xr-x 11 root root  4096 Nov  3 13:54 ..
-rwxr-xr-x  1 root root    51 Nov  3 13:54 cvlc
-rwxr-xr-x  1 root root    48 Nov  3 13:54 rvlc
-rwxr-xr-x  1 root root 38020 Nov  3 13:54 vlc
-rwxr-xr-x  1 root root 27020 Nov  3 13:54 vlc-wrapper
```
I'm not attaching the two scripts as they come from the script repo in FPP, but here is what is used to start the script:
```
# Edit this line to hold the URL of the stream:port in quotes
STREAMURL="http://stream.themillerhome.org:8000/lights"

# Edit this line to hold any options required in quotes
STREAMOPTIONS="-q --no-video-title-show"

cvlc ${STREAMOPTIONS} ${STREAMURL} &
echo $! >/tmp/mp3streamer.pid
```
Here is what is used to stop the script:
```
# stop mpg123
kill -9 $(cat /tmp/mp3streamer.pid)
```

Here is the pid:
```
fpp@fppmain:/tmp$ ps aux |grep vlc
fpp       5713  6.5  4.7 138400 23052 pts/0    SLl  14:35   0:15 /usr/local/bin/vlc -I dummy -q --no-video-title-show http://stream.themillerhome.org:8000/lights
```
And here is the temp pid file that is being called in the kill:
```
fpp@fppmain:/usr/local/bin$ cat /tmp/mp3streamer.pid
5713
```
So you can see that the kill command is _not_ the problem. The problem is actually in the start script. The start script is not working as intended, as the echo command never creates the /tmp/mp3streamer.pid file...and this is why the kill doesn't work, as the file doesn't exist.

The script still starts the music stream and creates a PID which I need to "sudo kill" manually since it's not in the file. I'm not sure what happened between 5.x and 6.x but for some reason, the echo command isn't completing now. If I ssh into the FPP instance and call the start and stop script, everything works perfectly as expected (no sudo required)...so this is only happening when called from within FPP.

It seems this is also somewhat related to the audio artifacts I reported here (https://github.com/FalconChristmas/fpp/issues/1393), as I do not get the audio artifacts when ssh into the FPP instance and call the start and stop script. It's almost like something isn't completed in the script (stuck in some loop) and acting as the source of the audio artifacts issue. @patdelaney @dkulp, you may be interested in learning about that finding regarding the audio issue.

I hope that all of this info was helpful to someone better at this than I am :) All I know is that the audio artifacts don't exist, and the script executes perfectly from the ssh cli, but when I run it from FPP directly the audio artifacts emerge and the start script doesn't execute fully which causes the stop script to also fail.

**Comment by nmiller0113** [comment]
I also just realized my explanation above may cause some confusion. When I showed the /tmp/mp3streamer.pid file and the ps aux, it was from when I ran it from the cli without issue. You can tell the difference as the user is fpp in the working example called from the ssh session:
```
fpp      12171 14.6  3.6 138400 17648 pts/0    SLl  15:42   0:00 /usr/local/bin/vlc -I dummy -q --no-video-title-show http://stream.themillerhome.org:8000/lights
```

and it's root when not working and called from within FPP:
```
root     12122  8.7  3.5 133648 17292 ?        SLl  15:40   0:01 /usr/local/bin/vlc -I dummy -q --no-video-title-show http://stream.themillerhome.org:8000/lights
```

**Comment by darylc** [comment]
Fixed the scripts, please download new versions.

**Comment by nmiller0113** [comment]
Thanks @darylc, you fixed the issue reported here. I know this is outside the scope of this case but I was just curious if you have any thoughts regarding why I get audio artifacts when triggering this script via FPP but when I run `cvlc -q --no-video-title-show http://stream.themillerhome.org:8000/lights & echo $! >/var/run/mp3streamer.pid` the audio is perfect? I was speaking with @dkulp and @patdelaney regarding this in issue https://github.com/FalconChristmas/fpp/issues/1393, and they even pushed this https://github.com/FalconChristmas/fpp/commit/14b8ff7f593b0c2ee9bfca4e9e35a79bb9312de7 to see if that would solve the issue, but considering that I've now narrowed it down further during the testing to fix this issue, I thought I'd mention it here as well. It seems that even without the buffer change (as I'm still running 6.2 and haven't received the update), I can prevent the audio clipping from happening by running this script from the CLI...it only happens when called from within FPP itself....like there is something else happening.
