### ISSUE TITLE
FPP scheduler crashing during playlist

### ISSUE THREAD

**Issue by SarahDods** [FalconChristmas/fpp#1429]
FPP is crashing running a scheduled playlist with tracks.  It runs OK for playlists with no music, which I run on non-show nights.

Apache base 2 error log is as follows:
[Sun Dec 04 19:17:10.358560 2022] [mpm_prefork:notice] [pid 1084] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Sun Dec 04 19:17:10.360475 2022] [core:notice] [pid 1084] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 04 20:31:11.712925 2022] [core:notice] [pid 1084] AH00052: child pid 2020 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.714924 2022] [core:notice] [pid 1084] AH00052: child pid 5603 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977521 2022] [core:notice] [pid 1084] AH00052: child pid 2081 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977676 2022] [core:notice] [pid 1084] AH00052: child pid 5496 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977735 2022] [core:notice] [pid 1084] AH00052: child pid 5497 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977808 2022] [core:notice] [pid 1084] AH00052: child pid 5529 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977862 2022] [core:notice] [pid 1084] AH00052: child pid 4210 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.977916 2022] [core:notice] [pid 1084] AH00052: child pid 1346 exit signal Segmentation fault (11)
[Sun Dec 04 20:31:11.978224 2022] [mpm_prefork:notice] [pid 1084] AH00169: caught SIGTERM, shutting down
[Sun Dec 04 20:31:25.271972 2022] [mpm_prefork:notice] [pid 1081] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Sun Dec 04 20:31:25.273871 2022] [core:notice] [pid 1081] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 04 20:31:25.395335 2022] [mpm_prefork:notice] [pid 1083] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Sun Dec 04 20:31:25.397426 2022] [core:notice] [pid 1083] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 04 21:17:12.017651 2022] [mpm_prefork:notice] [pid 1079] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Sun Dec 04 21:17:12.020645 2022] [core:notice] [pid 1079] AH00094: Command line: '/usr/sbin/apache2'
ping: github.com: Temporary failure in name resolution
[Sun Dec 04 23:17:10.959906 2022] [mpm_prefork:notice] [pid 1080] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Sun Dec 04 23:17:10.961276 2022] [core:notice] [pid 1080] AH00094: Command line: '/usr/sbin/apache2'

**Details**
On show nights, problem occurs on all playlists with songs.  I thought crashing was due to switching between high and lower priority playlists, so now have a single brute force playlist for the night.  In both the kids and main shows, on track 4 or 5 (eg items 9 & 13 in kids show), the lights sequence runs with no music playing, and everything stops at the end of the silent track. All comms with the pi is lost during the silent track.  Hard power reboot required to get it back up and running.

Playlist and schedule structures
![image](https://user-images.githubusercontent.com/109121211/205577129-15514ee4-7dc3-4ffb-8458-a3dc5260030d.png)
![image](https://user-images.githubusercontent.com/109121211/205576336-5ac9946a-4c41-40fd-9359-6cd515309477.png)
![image](https://user-images.githubusercontent.com/109121211/205576639-4f9e0556-6ceb-4b4c-b44d-21fecc5b3711.png)

FPP version details are attached
![image](https://user-images.githubusercontent.com/109121211/205574284-e34d194d-1c18-478a-a846-657ede840bc2.png)

**Comment by ghormann** [comment]
@SarahDods  Nobody will be able to do very much with out some log files.  You can use Content Setup -> File Manager and then on the logs tab, click the "Zip" button.

**Comment by SarahDods** [comment]
@ghormann Apologies. I thought I closed this out. Problem turned out to be the preamp attached to the usb port pulling too much power from the Pi. Solution was to connect a powered usb hub. 

Someone had reported the same problem a few years back and the powered hub was the suggestion solution but not verified. I’ve verified it on that thread but neglected to come back here as well. 

Essentially too much power drawn by usb caused the pi to eventually shut down services, including sound failing and then the pi freezing. 

I don’t know if a bigger power supply would also have fixed it, but the official pi power supply didn’t.
