### ISSUE TITLE
Add an FPPD command to randomize a playlist

### ISSUE THREAD

**Issue by danjamescrosby** [FalconChristmas/fpp#1431]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great to be able to randomize a playlist on-demand using the API in scripts or FPPD commands through the UI. The API could look something like `/api/playlist/:PlaylistName/randomize`. The FPPD command could be something like "Randomize playlist: {playlist name}"

**Describe alternatives you've considered**
The current options for randomize settings on a playlist of "Once per load" and "Every iteration" but I'd like more control over when the randomize happens.

**Additional context**
I could see this being useful to randomize on a schedule (e.g. once per day) or using a script (e.g. cycling through sequences on button press, reach end, randomize)

**Comment by darylc** [comment]
@danjamescrosby 
Can you use the "Insert Random Item From Playlist" API call to achieve what you want? eg http://x.y.z.a/api/command/Insert%20Random%20Item%20From%20Playlist/playlistname
