### ISSUE TITLE
Video file "not found"

### ISSUE THREAD

**Issue by ChasingTraction** [FalconChristmas/fpp#1432]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:  6.2 on pi3
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to '...'  uploded mp4 file (h.264) and can play the file from file manager / videos
2. Click on '....' add file to a playlsit as media only - error appears ERROR: Media File "windowvideo.mp4" Not Found
3. Scroll down to '....' play playlist and the video output works fine, fpp locks up within a minute.

**Expected behavior**: 
expected not to see the error and ERROR: Media File "windowvideo.mp4" Not Found when the media is actually there.

**Additional context**: 
video plays fine in web browser from the file manager

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
![Screenshot 2022-12-08 145609](https://user-images.githubusercontent.com/19608066/206360263-f1b673b6-2fc1-47f4-957f-82dcb1832cf6.jpg)
![Screenshot 2022-12-08 145701](https://user-images.githubusercontent.com/19608066/206360271-a937d111-ce90-4471-84d2-3e08e4303521.jpg)
![Screenshot 2022-12-08 145630](https://user-images.githubusercontent.com/19608066/206360273-745033c3-1869-47dc-b751-5d21cff3007d.jpg)

[FPP_Logs_20221208.0451.zip](https://github.com/FalconChristmas/fpp/files/10182218/FPP_Logs_20221208.0451.zip)

**Comment by ghormann** [comment]
@ChasingTraction : Can you paste the results of the following?   (Change the hostname to match your IP address)

* http://fppdev/api/media 
* http://fppdev/api/files/videos

**Comment by ghormann** [comment]
Closing. No response from OP.
