### ISSUE TITLE
K128 - Fade in is jumping/stepping rather than smooth on multiple sequences

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1433]
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 6.2 running on BBB*
In case it's relevant, xlights for Mac 2022.24

I'm not sure what is causing the issue, I'm only about 99% sure this wasn't happening last year on my F48v4. On my K128, fade in is jumping/stepping rather than smooth on multiple sequences. I'm not entirely sold that this fade-in issue isn't related to xlights, but when I play the sequence in xlights the fade in is smooth.

I've attached the logs as well as the sequence (40fps) I'm using. The sequence has a 15s fade to start. [Here is a link to the video capturing the fade in issue](https://drive.google.com/file/d/12OO1eXLrlxgyNLuyv-tV1-sx8TtAldyG/view?usp=sharing).

**Expected behavior**: 
Fade should look smooth like it does in xlights.

Thank you!
[Staticin.xsq.zip](https://github.com/FalconChristmas/fpp/files/10183097/Staticin.xsq.zip)
[FPP_Logs_20221208.0728.zip](https://github.com/FalconChristmas/fpp/files/10183103/FPP_Logs_20221208.0728.zip)

**Comment by nmiller0113** [comment]
I also ran another test using the brightness plugin to fade, rather than the sequence and it does the same thing. So is the problem in FPP or with the K128? I feel like may rule xlights out.

**Comment by nmiller0113** [comment]
@patdelaney @dkulp my apologies. The formatting was messed up when I added the second attachment and it didn’t show the first one. I corrected it.

You can use any model in the sequence to reproduce it, I showed the mega tree in my video, so I know that works, but honestly it was impacting all models. This fade is across all models in the sequence.

Thanks again for your help!

**Comment by dkulp** [comment]
I likely won't have time to look at this for a few days, but my get feeling is that it's a Brightness/Gamma issue and not something specific to the K128.   I've attached an Excel spreadsheet that you can play around with to see what I mean, but the graph for your 30% brightness and gamma of 2.2 looks like this for a 12 second fade in at 40fps:
<img width="758" alt="Screenshot 2022-12-08 at 9 35 27 PM" src="https://user-images.githubusercontent.com/91569/206611216-4a5a933b-334b-47c1-b69b-7b940ca3c83c.png">

The top line would be the value xLights calculated for the time.  It's linear from 0 to 255.    The next line would be the 30% brightness.   I believe that's what you ran last year.   Again, linear with constant changes about every 3 frames.   The bottom is with gamma of 2.2 applied.   There you can see that it doesn't even hit value of 1 (turn on) until frame 59, almost 1.5seconds in.   It will stay at 1 for until frame 99, one second, value of 2 until 2.5 seconds, etc...    At the low end of gamma curves, there is not a lot of values so the stepping appears very noticeable.     Anyway, it would be great if you could set the gamma to 1.0 and repeat the fade to see what that looks like.  

[BrightnessGamma.xlsx](https://github.com/FalconChristmas/fpp/files/10191311/BrightnessGamma.xlsx)

**Comment by nmiller0113** [comment]
Hi @dkulp, thank you for the detailed response. You are correct that I usually run at 30%, but in this case, I'm running the brightness plugin at 50 since it's my after-hours static display, so it's 15%...which puts the value of 1 at frame 84. I changed the gamma to 1.0 for everything, which moved the value of 1 to frame 9. While this improved the issue a fair amount, there is still some stepping happening. Based on your response, does this mean that this is expected and there isn't a way to make it smoother unless I increase my brightness? Or is there still something else that can be tuned besides brightness?

I know you mentioned that you wouldn't have time to look at this for a few days, but I am interested in improving this further, should there be other options, just as soon as you do have time. Thanks again!

**Comment by darylc** [comment]
@nmiller0113 WS281x pixels take values 0 to 255 per color (8 bits).  They have no brightness control as such, they use this color value to also limit brightness.  If you set your brightness to 15% then you are just left with values 0 to 38.  There is no way around that beyond removing the brightness limit you've applied or using pixels that have 12 or 16 bit color capabilities. There is a handy table here showing those pixel types. https://www.advateklights.com/knowledge-base/pixel-protocols

**Comment by nmiller0113** [comment]
Thanks @darylc, I guess I didn't realize just how much impact that limitation would have in terms of fade fluidity (it was late and I wasn't thinking math haha). Otherwise, it makes sense, I was aware of how the brightness was controlled on the 8-bit color led. I guess the reason I didn't see it last year was that I wasn't running gamma at 2.2, and that is what came as default with the K128. I have my answers and will close this out. Thank you @dkulp @darylc for the feedback/guidance! Have a great rest of your holiday season!
