### ISSUE TITLE
Scheduler changes requires manually restarting fppd to preview changes

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1435]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.2 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to schedule
2. Click modify schedule, e.g. add or delete items
3. Click save
4. Click preview
5. Changes are not in preview
6. Manually restart fppd
7. Click preview, now changes are reflected

**Expected behavior**: 
If a fppd restart is required, prompt user, or do not require fppd restart to preview saved schedule changes.

**Additional context**: 
N/A

**Additional Attachments**
Please include the log files. To create the file:
N/A

N/A

**Comment by darylc** [comment]
did you try pressing the reload button at the top of the scheduler page?

**Comment by ptr727** [comment]
> did you try pressing the reload button at the top of the scheduler page?

Yes, save, reload, no difference, to see the updated schedule must manually (press button at bottom of page) restart fppd.

**Comment by darylc** [comment]
that's not my experience..

**Comment by ptr727** [comment]
> that's not my experience..

I last created schedules on 6.1, and the preview did work without needing to restart.
Last night with 6.2 I did have to restart to get the preview to reflect changes.
Your experience my differ, but that was my experience, so at minimum the behavior is inconsistent.

**Comment by ghormann** [comment]
@ptr727  When this happens again, it would be really helpful if you can download and attach the logs.  There is a download button on the "logs" tab of File Manager.

**Comment by ptr727** [comment]
I've been running with logging set to debug and now it does not happen, maybe due to a timing change.
I do wonder if it is related to other reports of problems with the scheduler, specifically around the locking logic, and that the behavior I see may be related to e.g. a lock problem that gets resolved when restarting the service.

**Comment by darylc** [comment]
Closing for now given none of us can replicate it.  If you do manage to replace it, feel free to re-open.
