### ISSUE TITLE
BRANCH playlist item doesn't populate correctly when selected for editing

### ISSUE THREAD

**Issue by bluecreeklightguy** [FalconChristmas/fpp#1439]
FPP 6.1.1, running on RasPi4.

When I use the BRANCH playlist item in a playlist, and I later click on the edit button to edit that playlist item, it doesn't initially populate with the correct information.

To reproduce bug:
1.  Create playlist with BRANCH entry, using the time test condition and choose "call playlist" for the true condition and "do nothing" for the false condition.
2. From playlist, select the yellow edit button for the BRANCH playlist item.
3. See that the time and playlist selections aren't available in the dialog box.
4. Select one of the other options in the "if true" dropdown.
5. Re-select the "call playlist" option
6. Observe that the time and playlist information is again present.

**Expected behavior**: 
When I enter the edit dialog box, I expect it to populate with the current settings from the BRANCH playlist item.

1st screenshot is of the playlist. 2nd screenshot shows the dialog box after first clicking on the edit button.  3rd screenshot shows the edit dialog after selecting something other than "call playlist".  4th shows the edit dialog box after re-selecting the "call playlist" option.

<img width="1421" alt="Screen Shot 2022-12-13 at 12 46 53 PM" src="https://user-images.githubusercontent.com/71750486/207420803-1770dade-4cb3-460b-a721-f5903da7b669.png">
<img width="617" alt="Screen Shot 2022-12-13 at 12 47 44 PM" src="https://user-images.githubusercontent.com/71750486/207421035-0cd8a8c1-af0e-40db-935c-f515f657461d.png">
<img width="608" alt="Screen Shot 2022-12-13 at 12 47 59 PM" src="https://user-images.githubusercontent.com/71750486/207421060-74c690ec-82fa-43c1-833f-2b10dc2f7c3f.png">
<img width="623" alt="Screen Shot 2022-12-13 at 12 48 12 PM" src="https://user-images.githubusercontent.com/71750486/207421086-4f1229ba-6b1f-4395-b300-933139a81303.png">

**Comment by ghormann** [comment]
@bluecreeklightguy  I'm unable to reproduce in the master branch.  Please review the video and let me now if you see that I tested incorrectly. 

https://user-images.githubusercontent.com/24968726/209897269-86f8cc5a-c8b5-4406-a0d4-72218c7ed68c.mp4

**Comment by ghormann** [comment]
Closing. No response from OP.
