### ISSUE TITLE
FPP Player with Local Strings and DPP or E1.31 Output Causes Duplicate Data with Xlights Output to Lights

### ISSUE THREAD

**Issue by cbennett6008** [FalconChristmas/fpp#1440]
**FPP Version and Hardware**: 
FPP 6.2 Running on BBB with Kulp K16-B Cape

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. FPP with local strings set as a player, Outputting DPP/E131 from wlan0 or eth0 as dictated by network requirements. In this example a K16 is used.
2. Another controller accepting DPP or E1.31 data; In this example a Dig Uno running WLED is used.
3. FPP controller is added to Xlights in the usual fashion, Active is set to Xlights only, as it is playing back to local strings on a cape.
4. Wled is added to Xlights, DPP or E1.31 behave the same
5. This test sequence has only two 50 pixel strings; one on  port1 of the WLED instance, one on Port1 of the FPP cape. Outputs are uploaded, and FPP connect is performed to upload Models and UDP.
6. Playback from Xlights with output to lights, we see the rapid flickering symptom as if the wled instance is receiving duplicate data.

**Expected behavior**: 
Lights perform as sequenced without flickering due to duplicate data

**Additional context**: 
This issue only exists since FPP 6, and still exists in 6.2, Reving back to 5.5 this works as expected.
In FPP Disable Network Bridge Monitoring being checked has no bearing
If we take action to prevent fpp from sending data to WLED, ex. turn of E1.31 input on the FPP controller, or set FPP to inactive in xlights,  the WLED controller functions as expected.

**Additional Attachments**
Please include the log files. To create the file:

[FPP_Logs_20221213.2048.zip](https://github.com/FalconChristmas/fpp/files/10221913/FPP_Logs_20221213.2048.zip)
This is a packaged sequence with steps above performed.
[testsequence.zip](https://github.com/FalconChristmas/fpp/files/10221919/testsequence.zip)

**Comment by cbennett6008** [comment]
For what it's worth I'm not sure this is an FPP issue vs an xlights one, why is output to lights sending the pixel data for the WLED controller to the FPP controller, if it's not marked as proxied?  Starting with posting it here since FPP 5.5 - fpp6 is the software change that seems to induce the behavior.

**Comment by nmiller0113** [comment]
@cbennett6008 I'm not sure I'm following your description. Do you have a rough drawing of what you're doing and how all parts connect to eachother? This sounds more like a configuration issue than a bug. Screenshots of your FPP configuration would be helpful as I'm trying to figure out what you're doing when you mention "FPP with local strings set as a player, Outputting DPP/E131 from wlan0 or eth0 as dictated by network requirements. In this example a K16 is used." on one line, then you mention outputting from xlights in another "Playback from Xlights with output to lights, we see the rapid flickering symptom as if the wled instance is receiving duplicate data."

**Comment by cbennett6008** [comment]
Sure thing
So all I'm doing it taking a K16, and making it the player for another E1.31or DPP controller as well as it's own local strings.
It plays uploaded sequences as intended, but Output to lights causes duplicate data.
Here's the controllers in xlights
![image](https://user-images.githubusercontent.com/45939942/207446072-601c1f50-ed41-47d2-80b9-84bc5409f9ec.png)
![image](https://user-images.githubusercontent.com/45939942/207446139-63d49144-6c5d-4d97-9c19-992f2f3fbcc5.png)
Here's the E1.31  outputs in FPP
![image](https://user-images.githubusercontent.com/45939942/207446674-09887bca-6eb4-4aae-b07b-ffb00bc23052.png)
Are there additional FPP screenshots I can provide?

**Comment by cbennett6008** [comment]
Pardon the poor diagram quality, but this is a flat network
![image](https://user-images.githubusercontent.com/45939942/207447565-c88dc9c0-5baa-4083-9266-6b6595912dcf.png)

**Comment by ravenridgelights-turtle** [comment]
So 
If you have a kulp or fpp device 

If u have it set to send e1.31 or ddp data to wled 

When u hit output to lights 
It sends the data intended for wled through fpp to wled 
At the same time sending it though xlights

You can confirm this in wled interface from where it's getting the data via the ip 

If u drop down to 5.5 it doesn't do this 
The ip comes from xlights as it should ..

**Comment by nmiller0113** [comment]
@cbennett6008, I'm not sure why you have the WLED output configured in xlights and FPP. What do you intend to use as your sequence player? Also, why do you have a K16 output configured at all? I understand that its disabled but you would configure that on the K16 tab, not the tab you're on.

**Comment by nmiller0113** [comment]
@cbennett6008 please share your channel input tab screenshot in FPP as well.

**Comment by cbennett6008** [comment]
![image](https://user-images.githubusercontent.com/45939942/207453021-d4270128-6bac-4479-bdad-06649f61578d.png)
![image](https://user-images.githubusercontent.com/45939942/207454686-797c1166-a61c-4652-b0b7-5562069c34fb.png)

The intended state is that sequences are uploaded to the K16 acting as a show Player, and played back the K16's scheduler, and with that configuration, this part works as intended.
The break happens when testing what an effect might look like with output to lights.
The K16 in Xlights is set to Xlights only, so it uploads to FPP as unchecked, to avoid the warning about sending data to Self.

**Comment by ravenridgelights-turtle** [comment]
> @cbennett6008, I'm not sure why you are trying to output from xlights and FPP. What do you intend to use as your sequence player? Also, why do you have a K16 output configured at all? I understand that its disabled but you would configure that on the K16 tab, not the tab you're on.

It's only when u use the output from xlights lightbulb💡or tools test 

Playing as seq from fpp works as normal expected .

**Comment by nmiller0113** [comment]
@cbennett6008 perhaps something isn't working because the output setup is incorrect in FPP. I know this shouldn't be in play based on what your describing but humor me since it should be reconfigured if you plan on having FPP run your shows anyhow. Based on how your have xlights configured you should delete the inactive K16 line in your outputs and make the WLED one E1.31 and channel universe site 510.

**Comment by cbennett6008** [comment]
Sure.  For what it's worth this configuration is the result of full xlights control of the K16.
Changed WLED to E1.31 in xlights uploaded all outputs and FPP Connect pushed the UDP outputs, then manually deleted the K16 from itself in FPP.  
The symptoms remain the same.
![image](https://user-images.githubusercontent.com/45939942/207467832-a8c8fa0f-a233-4d60-a3db-5a474fe1d608.png)
![image](https://user-images.githubusercontent.com/45939942/207467683-921826e8-adc6-43a5-a565-1ddb5b9fb25e.png)

**Comment by cbennett6008** [comment]
For what it's worth, this is not my config, or an issue with my actual show setup, this an issue reported by users in the community that I have duplicated and am submitting a bug report on behalf of.

**Comment by nmiller0113** [comment]
@cbennett6008 I thought they would, but it was worth a shot :)

If this started with 6.x of FPP then perhaps it's related to FPP not respecting the DDP the xlights channel number in the DDP stream. I honestly don't know much about DDP but that's the only thing I can think of since the "Keep channel numbers" box is selected in xlights so it should be sending them. If it wasn't being sent, or ignored on the receiving side, then the 150 channel DDP stream would be sent out the channel output to the WLED.

When you're running the output test do you get anything to the K16 150 Channel tree output on port 1? If not, then I'd say that what I stated above is likely the case....but still not sure.

**Comment by cbennett6008** [comment]
Yes, the output to the FPP string displays as you'd expect under pretty much everything I've tried, I have the two strings set with different color effects pretty much specifically so I can tell the correct string is getting the correct effect.
When the WLED device is set to E1.31, the problem stays the same.

**Comment by cbennett6008** [comment]
For what it's worth, I jut repeated the test with an F16v4, the issue is not specific to WLED controllers. (Again deleting the inactive Self-controller as you requested)

![image](https://user-images.githubusercontent.com/45939942/207473280-a22e70f0-c1bd-464a-b7aa-98dd9da55341.png)
![image](https://user-images.githubusercontent.com/45939942/207473371-751b6ed1-f5a2-4a51-bda1-ea569e09116a.png)

**Comment by dkulp** [comment]
This is working as designed and is not a bug.  When FPP outputs a frame, it outputs the entire frame to all of the configured outputs.   If you have e1.31/ddp outputs configured, data will be sent out to them.

When FPP receives data via a channel input, it just overlays the data it receives onto the frame (which then gets sent as above).

**Comment by dkulp** [comment]
On option would be to configure the WLED IP as a Proxy on the FPP proxies page and set the FPP instance as the proxy in xLights.   In that case, xLights would send all the data (via DDP) to FPP only and then FPP would send the data to WLED.

**Comment by cbennett6008** [comment]
> This is working as designed and is not a bug. When FPP outputs a frame, it outputs the entire frame to all of the configured outputs. If you have e1.31/ddp outputs configured, data will be sent out to them.
> 
> When FPP receives data via a channel input, it just overlays the data it receives onto the frame (which then gets sent as above).

Dan, was this a change or fix in FPP6?  If I re-flash this K16 to 5.5 this behavior doesn't happen.

**Comment by nmiller0113** [comment]
@dkulp, thanks for that meaningful info. That makes perfect sense! @cbennett6008, there's your answer...not sure about 5.5 not exhibiting the same behavior. His workaround is likely your best option either way.

**Comment by ravenridgelights-turtle** [comment]
> On option would be to configure the WLED IP as a Proxy on the FPP proxies page and set the FPP instance as the proxy in xLights.   In that case, xLights would send all the data (via DDP) to FPP only and then FPP would send the data to WLED.

I think I've tried this but wled don't support proxies.. last time I tried has been a min

**Comment by ravenridgelights-turtle** [comment]
> > This is working as designed and is not a bug. When FPP outputs a frame, it outputs the entire frame to all of the configured outputs. If you have e1.31/ddp outputs configured, data will be sent out to them.
> > 
> > When FPP receives data via a channel input, it just overlays the data it receives onto the frame (which then gets sent as above).
> 
> Dan, was this a change or fix in FPP6?  If I re-flash this K16 to 5.5 this behavior doesn't happen.

@cbennett6008 can u test the proxy and tell me if uploads work and web ui works ? I dont have a test set up to test on ATM.  But this changed in 6.0 I've been using wled with fpp since 4.0 and it's never done this

**Comment by cbennett6008** [comment]
> @cbennett6008 can u test the proxy and tell me if uploads work and web ui works ? I dont have a test set up to test on ATM. But this changed in 6.0 I've been using wled with fpp since 4.0 and it's never done this

I know that WLED Web UI does not work correctly thru the FPP proxy, there's at least one absolute URL inside of the javascript that break out of the proxied URL. I'll do a check on the rest of the functions in the morning.

**Comment by darylc** [comment]
Does the comment from Dan resolve this issue?

**Comment by darylc** [comment]
@cbennett6008 Does the comment from Dan resolve this issue?

**Comment by cbennett6008** [comment]
Unfortunately no.  The way that the wled ui is structured, it’s not
accessible thru the proxy.  Has issues with URLs that break out of the
proxy that are built inside the JavaScript as absolute.

**Comment by darylc** [comment]
@cbennett6008 This comment https://github.com/FalconChristmas/fpp/issues/1440#issuecomment-1350175590 - eg that this is working as designed.  If you send data to your wled from both xlights and fpp at the same time, this is fully expected behavior.
