### ISSUE TITLE
Mixing RGB and RGBW lights on same controller results in wrong color output

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1441]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.2 on K4-PB and K8-A

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Connect and configure RGB pixels on a port (I used 4 and 8)
2. Connect and configure RGBW pixels on another port (I used 3 and 7)
3. Test output using xLights or FPP
4. RGB port test different colors ok
5. RGBW port test different colors ok
6. Now enable output on the RGB and the RGBW port at the same time, blue output on RGB pixels suddenly turns red, RGBW pixel color remains correct

**Expected behavior**: 
Colors behave as programmed regardless of pixel type and mix.

**Additional context**: 
I tested output with xLights and with FPP.
I tested with a K4-PB and a K8-A.
I am testing with [Mattos RGB Trim](https://mattosdesigns.com/collections/rgb-trim/products/rgb-trim-pro) RGBW puck lights (SMD5050 IC2904B RGBW LED) and with [Mattos 12V regulated pixels](https://mattosdesigns.com/collections/smart-pixels/products/12v-regulated).

**Additional Attachments**
[FPP_Logs_20221215.0007.zip](https://github.com/FalconChristmas/fpp/files/10232571/FPP_Logs_20221215.0007.zip)

Video (too large to attach, even if compressed): https://photos.app.goo.gl/sY83BWc7LPUtPMbL6

**Comment by darylc** [comment]
This is expected, display testing does not attempt to try and make the colors the same across outputs.

See the warning at the top of the display testing page "Note: RGB patterns have NO knowledge of output setups, models, etc... "R" is the first channel, "G" is the second, etc... If channels do not line up, the colors displayed on pixels may not match."
