### ISSUE TITLE
Incorrect OS version displays in SSH. 

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1442]
I have several fpp instances upgraded to 6.2 OS v2022.11... I noticed when I log in via ssh, it shows v2022.09b OS.  This happens on  BBB based and Raspberry Pi based controllers both.  Here are images and log zip from my K8B.
![image](https://user-images.githubusercontent.com/88390168/207966055-f93cefdb-05f3-4005-87ae-941764d2c1fe.png)
![image](https://user-images.githubusercontent.com/88390168/207966275-d6975997-e917-483c-8480-18f33658eb34.png)

[k8b-version display issue.zip](https://github.com/FalconChristmas/fpp/files/10240629/k8b-version.display.issue.zip)

**Comment by derwin12** [comment]
Looks like Dan fixed this on Nov4th..
![image](https://user-images.githubusercontent.com/4643499/208757967-4b4bd030-8114-4478-9d39-334a550b0a0a.png)

**Comment by ghormann** [comment]
I tested with a 6.3 FPPOS upgrade and the correct version displays now.

**Comment by bloojoop** [comment]
@ghormann , I did a FPP 6.3 upgrade on my k8 today and it is still showing the wrong OS version in ssh.  I did NOT do a fppos upgrade and the notes stated that NO OS changes since 6.2.  I guess this would still be the expected behavior?  so it really does take a "OS" level upgrade to resolve this ?

**Comment by dkulp** [comment]
That is displayed from /etc/issue (or /etc/issue.net ) and thus would require the fppos install.

**Comment by bloojoop** [comment]
> 

copy that, thanks
