### ISSUE TITLE
Would like Advance Scheduling for commands on remotes...

### ISSUE THREAD

**Issue by bcarriveau** [FalconChristmas/fpp#1443]
Possible to Allow an "Advanced Schedule" for remotes? 

Would allow the ability to schedule reboot script.

Seems fpp drops from the network and reconnects all the time, sometimes it fails to reconnect and i cannot figure out why, have seen this alot in the zoom room as well. If i could schedule a reboot once every 24 hrs i would never have to power cycle the units that fail to reconnect and would never care if it dropped off outside of display times.

 All DHCP with reservations. 

Here is just two of my many controllers , had to power cycle them this afternoon to get them back. 

![2022-12-15 19_10_11-UniFi Network - Bills Dream](https://user-images.githubusercontent.com/60801063/207999453-63e41a82-39dc-40ab-9692-5890ac6c0c45.png)
![2022-12-15 19_09_29-UniFi Network - Bills Dream](https://user-images.githubusercontent.com/60801063/207999454-1c6065e0-855f-44ca-b8f8-c9e8964f7090.png)

**Comment by bobreese** [comment]
You could try a scheduled / Remote reboot script
Scheduler - Create new
Schedule Type - Command
Playlist / Command ARGS - Remote Run Script
New Window
Remote IP - the device to reboot
Script Name - Reboot

Just set the times you want it to run and you should be done.

**Comment by bcarriveau** [comment]
If it's no longer online how would it receive the command?

**Comment by cpinkham** [comment]
We have debated enabling FPP Command scheduling on remotes.  The fppd backend piece should be only a couple lines of code, but we also need to tweak the UI a bit to only allow FPP Commands to be scheduled on remotes and disallow playing playlists and warn the user if they have a scheduled playlist, but switch a system to remote.  This is the main reason I haven't done it yet.

**Comment by bcarriveau** [comment]
that is great the conversation happened! I'm all for it :-) Deff can see how some users could make a mess of it.!

**Comment by patdelaney** [comment]
@cpinkham  I'm not sure where to look for the enhancement in the UI so I can test this.

**Comment by cpinkham** [comment]
@patdelaney Set a system to Remote mode then go schedule a FPP Command on that system.  The scheduler should now show up on Remote systems, but it will only schedule FPP Commands and will warn in the UI if a playlist or sequence is scheduled.  A warning will also appear on the main status page in addition to the scheduler page.
