### ISSUE TITLE
6.3 Log file small horizontally

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1444]
6.3 New log file viewer is smaller horizontally

Content Manager
File Manager
Logs
Click a log and click View

**Expected behavior**: 
Fill screen to show as much of the log are a horizontally as possible.

![Log File 01](https://user-images.githubusercontent.com/461610/208772683-65322d46-90bb-413f-8646-8835444bb8b8.jpg)

**Comment by ghormann** [comment]
I fixed this via 5182f32ea92313f12cb598b94f8458eab30895f7  *HOWEVER* I made it affect a lot more then file viewing.   On larger screens, I basically changed the max width on a dialog to be 5.5rem less than the width the screen.   If others don't like this, then feel free to revert but I tested a number of dialogs and like it better on a bigger screen.
