### ISSUE TITLE
6.3 SD Card Size - Grow System

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1445]
New image from the 6.3 post.
At now time during setup does it ask to grow the file system.
Going into FPP Settings, Storage, the image is written with 2 partitions already.
The SD Card I used is a 32G card freshly formatted.
Storage shows 
mmcblk0p1 - 0.2GB
mmcblk0p2 - 3.4GB

![Storage 01](https://user-images.githubusercontent.com/461610/208775468-5dad4804-ae45-4991-9d11-8e5862f5ba6e.jpg)

**Comment by dkulp** [comment]
Can you do an update?  I think I just fixed this.

**Comment by bobreese** [comment]
Yes sir, that fixed it.
If the IMG file is fixed I will be more than happy to test it.
FYI: The log file screen is still small...
