### ISSUE TITLE
Add Genius Controller filter in FPP multisync page

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1446]
**Feature request**
Please add Genius Receivers to Platform filter list in FPP MultiSync page.

![image](https://user-images.githubusercontent.com/8147459/209558365-642d2b67-e123-43de-9467-90960007aaef.png)
![image](https://user-images.githubusercontent.com/8147459/209558381-cb9bec76-cb43-4da5-991d-59746f429c50.png)

**Comment by ghormann** [comment]
@patdelaney  This *SHOULD* work but I don't have a controller for testing.   Please reopen if it doesn't work.
