### ISSUE TITLE
FPP 6.x schedule stops playing and fpp -s status shows 'false' 

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1447]
I have a master fpp that plays 2 schedules every weekday for the entire year.  Ever since upgrading to 6.x, the schedules would not fire after several days of run time.  This is a pi 3b (have substituted 3b+ and 4b as well same issue).  I have upgraded from 6.0.2 to 6.1, to 6.1.1. and to 6.2 with all version exhibiting the same behavior.  In each case there are lots of entries in the fppd.log showing: 2022-12-15 01:26:57.286 (26132) [ChannelOut] /opt/fpp/src/channeloutput/UDPOutput.cpp:348: UDP Interface eth0 now up.   These messages occur about every minute.  There are no corresponding down messages just up messages. 
When it gets hung up, I would notice it stating the next scheduled item would be a day or so in the past from current time.  Ex: would show next scheduled item at 12/15 12:00PM when it would actually be 12/17 already.   Also I would notice if I manually play the playlist it would play fine, but the schedule would never fire. 
I also noticed that in the web gui I could 'restart fppd' and it would act like it would restart however, it would NOT actually restart fpp according to the logs.  
When looking at the logs, all logged seem to just stop at the time that fppd would get in this hung up state.  It would show the udpoutput logs every minute up to that point then just absolutely nothing in the logs. 
If I were to run fpp -s from the shell while in this state it would just output 'false'.  
Additional notes: 
This issue only occurs if I have upd output to other controllers configured (which I do). I reburned the card with a brand new 6.2 image and just added a single sequence and schedule and same issue. This fpp is using dhcp via eth0 (I run most of my controllers via dhcp and use host names).  I remembered this network had dhcp lease times purposely set to 2 minutes.  These messaged in fppd log seem to occur for every dhcp renewal request.  I set lease time to 10 minutes and those message come less frequent now.  **This issue does not seem to occur if configured for static IP, just when using dhcp.** 
these messages do NOT occur on fpp 5.5.  This pi has ran all year on 5.x without any issues. only when running 6.x so these problems occur. 

After changing the dhcp lease time, it would take quite a bit longer before this would occur, it has been about every 3 days since upgrading and now it is about every 15 days. 
It appears that on fpp 6.x after getting so

 many dhcp renewal requests, and fpp logging them as a udpoutput eth up messages, that fpp get in some wierd hung up state and no longer shows a valid status and scheduling and restarts fail to occur.  I have been troubleshooting and working to understand this issue for most of the season.  I can reproducer it on request but it does take several days for it to get hung up.  

Attached are fpp log zip and a crash report that occurs when it can't ping some of the udp outputs (I shut down some controllers). 
[pi scheduler fpp stuck.zip](https://github.com/FalconChristmas/fpp/files/10304847/pi.scheduler.fpp.stuck.zip)
[fpp-Pi-6.2-2022-12-25_17-15-11.zip](https://github.com/FalconChristmas/fpp/files/10304846/fpp-Pi-6.2-2022-12-25_17-15-11.zip)

**Comment by bloojoop** [comment]
My instance of fpp has had this issue again.. no further fpp logging since 12/27 at 15:50.   Here is the current fppd.log file from today 12/29.  Also some screen shots, notice the next scheduled item show 12/27 17:00 when the current time is 12/29 18:25. 
![image](https://user-images.githubusercontent.com/88390168/210023345-740c6e98-a7c3-4462-9eee-6b1a551cfc68.png)
fpp status from the CLI shows status of 'false' : 
![image](https://user-images.githubusercontent.com/88390168/210023386-4604720c-3979-4e1e-9103-001c0fc27aa9.png)


[fppd.log](https://github.com/FalconChristmas/fpp/files/10322643/fppd.log)

**Comment by bloojoop** [comment]
[strace capture.log](https://github.com/FalconChristmas/fpp/files/10333845/strace.capture.log)
Here is an output from 'strace -fp 20739' where 20739 is my fppd pid.  It also looks like recQ for the 32320 port is up to 181248... I'm curious if we are encountering port exhaustion ?? I see that via 'netstat -an'

**Comment by darylc** [comment]
A fix for this has been made, and @bloojoop is testing it.

**Comment by darylc** [comment]
@bloojoop Are you happy that this is resolved now?

**Comment by bloojoop** [comment]
Thanks for the follow up Daryl.  Yes it appears to be resolved, I'm fine
with this issue being closed.  If I have any further difficulty, we will
address it separately.
