### ISSUE TITLE
[MINOR] Multisync: CORS Error in Multisync with v2.51 Falcon controller

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1448]
**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. On 6.x master in a network that Falcon v2.51 controller.
2. Open javascript debug console
3. Open up Multisync tab

![image](https://user-images.githubusercontent.com/24968726/209890434-3e9c704e-2fc9-4531-b73f-b0af1d5e5eae.png)

**Expected behavior**: 
There really shouldn't be an error as we *should* be doing all these checks on the server side because of proxies and such. 

**Additional Info**

This comes from `getFalconControllerStatus()` in multisync.php.

**Comment by dkulp** [comment]
Fixed
