### ISSUE TITLE
Video Recording Mode/Starting Sync Flash

### ISSUE THREAD

**Issue by cabrower** [FalconChristmas/fpp#1451]
**Is your feature request related to a problem? Please describe.**
It is difficult to precisely sync an audio file and a show recording without audio, when editing video recordings. 

**Describe the solution you'd like**
The ability to put FPP into a mode which flashes a model, pixel, etc at the start of a sequence. This would let you precisely know when the sequence starts. This will aid in the ability to sync music and video tracks in post production editing. 

**Describe alternatives you've considered**
Another way would be to permanently edit each sequence, but this isn't ideal for if you have a large collection of sequences.

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this as a feature.

**Comment by Poporacer** [comment]
This can be accomplished through several other means that are currently available.
