### ISSUE TITLE
Add disk utilization sensor

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#1452]
Add a disk utilization sensor (or sensors) to FPP to allow those to be displayed in the UI header and exposed to remote systems such as via the Home Assistant plugin.  Also possibly add code to MQTT to automatically expose FPP's sensors via MQTT.

**Comment by ghormann** [comment]
@cpinkham  For the MQTT publish part, my proposal is that we just publish /api/system/status on a regular basis.    We have the poorly named setting "MQTTFrequency" that will periodically publish Playlist information, but we add a second option defining the frequency to publish the status JSON this makes quite a bit if information available. including sensors.

**Comment by ghormann** [comment]
@cpinkham  Is this needed posted 23600c35161da8a1df8da2b2128a0783ed7f9711 ?

This commit adds an option to periodically publish the fppd status json.   This json already exposes `advancedView.Utilization.Disk`  just not as a sensor so by default it doesn't show up in the UI Header.

**Comment by cpinkham** [comment]
I think we're good, my main goal was to allow it to be exposed remotely which your patch does.  Thanks.
