### ISSUE TITLE
Make FPPD restart and reboot windows more visable.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1453]
Many people are missing the restart messages because they never show on their screen unless they scroll up to find them.  FPP should make these more visible,  potentially having them float at the top of the screen vs just being at the top of the page.

**Comment by cpinkham** [comment]
We could potentially make a set of reboot/restart buttons which would float just below the “top” button that shows when you have scrolled down the page.  We already have some non scrolling table headers and trying to add another non scrolling page header above those has proved rather painful when tried in the past.

Chris

**Comment by ghormann** [comment]
I was looking into this and the top button suggestion, but it  only works on screens that are 992 pixels wide (or wider) because of how the menu is handled.     I'll dig into this as well.
