### ISSUE TITLE
K128D-B Channel Output Numbers Incorrect When Reverted

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1454]
**FPP Version and Hardware**: FPP 6.2 running on BBB

**Describe the bug and Steps to reproduce**: 
1. Go to the Channel Outputs section
2. Take the channel outputs backup I attached and apply it to a K128D-B (it's zipped)
3. The differential section will show smart v2 and 6 Smart Receivers
4. Change differential section from smart v2 to standard for section ports 1-4.
5. You'll see that it changed port 1A to 1, but 2a, 3a, and 4a remained the same

**Expected behavior**: 
All port numbers should lose their letter association when the differential section is changed to standard

Here is a video of me reproducing this issue
https://user-images.githubusercontent.com/1048868/211457659-612577b6-3c0e-4116-94d2-5faf2743319b.mp4

Here is the JSON config backup of the Controller Output
[fppmain_channelOutputs-backup_v5_20230109191707.json.zip](https://github.com/FalconChristmas/fpp/files/10378715/fppmain_channelOutputs-backup_v5_20230109191707.json.zip)

**Comment by darylc** [comment]
fixed in master

**Comment by nmiller0113** [comment]
Thanks @darylc
