### ISSUE TITLE
Add 'Notes' to entries in the FPP Scheduler

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1457]
**Is your feature request related to a problem? Please describe.**

Currently if I add a 'command' as an entry in the FPP scheduler there is no way to put a note against it to describe what that entry is doing in real terms.  E.g. if using the TP-link Kasa plugin to control smart switches I can't record what the command is actually doing in the real world - like 'turn off indoor lights", " turn on amplifier", "turn on controller xyz"

When you have lots of these types of entries it is currently very hard to understand what you have scheduled - see screenshot example of what I did this year
![Capture](https://user-images.githubusercontent.com/68251154/212205054-b80a3742-8acf-458d-8029-8d723cdae18f.JPG)

**Describe the solution you'd like**
Ability to add notes against scheduler entries like you can in playlist entries and have these display in the scheduler UI

**Comment by darylc** [comment]
FPP will not override the fields a plugin author has defined for their plugin. If you want them on this screen, for this plugin then please raise this with the plugin author.

If you put these commands in a playlist, you do get a generic notes field to put such information.  I'd suggest this would be better than us trying to coordinate all of the plugin authors to add the field.

![image](https://user-images.githubusercontent.com/7511887/214237806-42b8999a-b5b5-441e-9e24-d439eda09bb4.png)

**Comment by OnlineDynamic** [comment]
@darylc "If you put these commands in a playlist, you do get a generic notes field to put such information"

So why wouldn't we put the same functionality in scheduler entries as we do in playlist entries? Seems in consistent

**Comment by cpinkham** [comment]
I would like to keep this open.  I want to work on the scheduler UI at some point, but haven't exactly figured out what to do with it yet.  It is really cramped already, so adding a notes field to it as-is wouldn't really be feasible, but I think that if it is updated a bit, then we could include an area to put in a note as to what the scheduled item was for.
