### ISSUE TITLE
Custom NTP Server does not always get used and reverting to public NTP is not using full pool.

### ISSUE THREAD

**Issue by mjunek** [FalconChristmas/fpp#1459]
*FPP 6.3 running on Raspberry Pi*

***

### Setting custom NTP Issue ###
1. Go To FPP Settings -> Time 
2. Set a custom NTP server
3. Run the ```ntpq -pn``` command
4. Observe that the public debian pool is still being used
5. Check ```/etc/ntp.conf``` - the ```pool``` entries for the public pool are still entered

Custom server highlighted in red: ![image](https://user-images.githubusercontent.com/55641392/213028145-a79c869d-a7a5-4084-acc5-0f849897c239.png)

ntp.conf
![image](https://user-images.githubusercontent.com/55641392/213028236-e8aab87e-330f-494d-affe-b5748e9b937d.png)

***

### Removing Custom NTP Issue ###
1. Go To FPP Settings -> Time 
2. Remove the custom NTP server
3. Check ```/etc/ntp.conf``` - the entries for the public pool are specified as ```server``` lines

At the moment, due to the original pool servers not being cleared out on the above setting of the custom servers, the full gamut of servers are accessible, however this is not good practice.

ntp.conf 
![image](https://user-images.githubusercontent.com/55641392/213030710-210b5dfa-38ba-449e-9865-591a6a6abe33.png)

***

**Expected behavior**: 

* Once a custom NTP server is defined, the default Debian pool servers should be removed from ```/etc/ntp.conf``` and the FPP instance should NOT reach out to the internet for time.
* Once the custom NTP server is removed, ```/etc/ntp.conf``` should revert to using the ntp.org pool as a Pool rather than as list of servers as per the default Debian configuration. The NTPD documentation suggests using this scheme over the older ```server``` method. http://doc.ntp.org/documentation/4.2.8-series/discover/#server-pool-scheme

**Comment by darylc** [comment]
Thanks Mike
