### ISSUE TITLE
Show playlist parents if exist recursively 

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1465]
In the case of multiple "insert playlist now" executions, implement a method to display the entire list of parent relationships.

**Comment by darylc** [comment]
@bloojoop Can you confirm Dan's code addresses this need?

**Comment by bloojoop** [comment]
The breadcrumb shows up on the status page... Is there a way to determine nested playlists programmatically ?  fpp -s just shows current... I didn't see anything in api either.   Use case is working with playlist triggered via buttons and if already nested, then do nothing.

**Comment by dkulp** [comment]
The json from the status REST API should have the breadcrumbs in there.   Using fpp -s for status is pretty much deprecated in favor of the REST API's.
