### ISSUE TITLE
fpp not loading in safari

### ISSUE THREAD

**Issue by bcarriveau** [FalconChristmas/fpp#1473]
Master as of 2-4-2023 , fpp does not load on M1 Mac / Safari.

Wasn't loading earlier, so I pulled in the latest updates as of now and still doesn't load. 

Loads fine in Firefox.

![Greenshot 2023-02-04 15 59 23](https://user-images.githubusercontent.com/60801063/216791639-ec7c7ad2-c279-43b4-ab37-affe4d4e523c.png)

**Comment by darylc** [comment]
Bill was using Safari and also provided:
![image](https://user-images.githubusercontent.com/7511887/216792596-d1472fc5-4a01-4693-9c47-6e652f72318a.png)

Seems Safari lacks support for the regex.  https://caniuse.com/js-regexp-lookbehind

Regex is not a strong point of mine.. so looking for someone else to fix.

**Comment by bcarriveau** [comment]
@darylc 

in opt/fpp/www/js/ fpp.js, line 3255,  Replaced  `/^(?<=.{200})[\s\S]+$/, " ..."` **with** `/^(.{197}[\s\S]*).*/, "$1..."` Does fix the issue. But i dont know where to add it to the code here to fix it.

**Comment by bcarriveau** [comment]
@dkulp , your fix works aswell. Thank you both!

**Comment by bcarriveau** [comment]
fixed with cbcb0f92ffd35c9c4fe6e9c79c930c828d8d4cc9
