### ISSUE TITLE
PiFM Integration

### ISSUE THREAD

**Issue by SparkyDan555** [FalconChristmas/fpp#1476]
**Is your feature request related to a problem? Please describe.**
Having an external FM transmitter seems unnecessary and leaves many unknowns when selecting an appropriate model. 

**Describe the solution you'd like**
I recently came across the awesome [PiFM project](https://github.com/MundeepL/PiFM) which allows the Raspberry Pi itself to become the FM transmitter. It works well and has RDS support too. Has anyone ever considered if this project could be integrated into Falcon Player to evade the need for an external FM transmitter in some use cases. It claims to work across all Pi models using a simple GPIO pin with a wire antenna. A simple filter circuit is optional to improve noise from the carrier. 

**Describe alternatives you've considered**
There are various versions of the PiFM project. 

**Additional context**
The user would be able to choose to use the internal FM transmitter or an external audio device as is the case currently. The feature would include a UI to configure the frequency and other parameters. RDS can be integrated as current similar solutions.

**Comment by darylc** [comment]
The FPP developers discussed your request.  This is not the first time this has been requested and they do not intend to add this.

If someone wants to write a plugin for PiFM the developers would include it in the list of plugins, however the plugin would need to take into account the following complexities:
- Careful not to break the DPIPixels and PWM pixel outputs which use the same hardware as the PiFM
- Handle the requirement for different binaries for each model of RasPi (currently FPP uses the same binaries for all platforms)
- Ensure it works with all audio functions in FPP, not just playing sequences.
