### ISSUE TITLE
BBB - F4-B - has problem with a Pixel String Output start channel > 512

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#148]
Output from the four String Outputs works well when the Start Channel is within Universe 1.

Go above 513 and you get no output.

Testing done with F4-B in Bridge Mode, Fixed IP, and data from xLights Test.
F4-B is using Master Branch, latest rev of pre-1.5

**Comment by JonB256** [comment]
I tried something that I thought might work - The master is playing an fseq file designed for the P10 panel and starting at channel 16385. I used the Channel Remap feature to see it would "move it down" to Channel 1. I was hopeful. But it didn't work.

**Comment by JonB256** [comment]
I tried the remap again because of "gross technical error" on test setup. :(
This time it worked just like it should have. The FSEQ starting at 16385 began playing on the strings set with a Start Channel of 1.

But - I don't know if goes successfully past the first universe. I'll try to set that up for a test.

**Comment by cpinkham** [comment]
I will be looking as soon as we cut the v1.5 Beta images, so it will get fixed in master and stage branches.
