### ISSUE TITLE
WiFi client does not reconnect using DHCP after AP goes offline and back online

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1480]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
6.3-1-gdbe9f8b3 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. K4-PB is always on, and scheduled to reboot nightly at 11pm.
2. Power outage.
3. After power was restored the K4-PB was not reachable over the network.
4. UniFi controller dashboard showed device is connected to WiFi, but was using 192.168.8.1 as IP.
5. K4-PB OLED showed IP is 192.168.8.1.
6. I used the UniFi controller to force reconnect the K4-PB to the network.
7. K4-PB reconnected, but did not renew IP on WiFi reconnect, stayed using 192.168.8.1.
8. Had to physically power cycle to get a DHCP address.

**Expected behavior**: 
On WiFi client reconnect do a DHCP reconnect, do not stay on fallback 192.168.8.1.  

**Additional context**: 
Fallback 192.168.8.1 IP is only useful in AP or tether mode, it is not useful in network client mode.  
It may be (speculate) that the BB booted before the network was up, and used the fallback IP, but on WiFi reconnect it would still be expected to do a DHCP request.

**Additional Attachments**
[FPP_Logs_20230211.0232.zip](https://github.com/FalconChristmas/fpp/files/10712401/FPP_Logs_20230211.0232.zip)

**Comment by ghormann** [comment]
FPP8 is going to revamp how wifi is done at the OS level.  Closing.  Please retest when FPP8 is available.
