### ISSUE TITLE
Sort WLED palettes list entries

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1482]
**Is your feature request related to a problem? Please describe.**
Finding specific palette entries in the WLED palette list is troublesome because it is not sorted.

**Describe the solution you'd like**
Please sort list entries.

**Describe alternatives you've considered**
Scroll until found.

**Additional context**
<img width="615" alt="image" src="https://user-images.githubusercontent.com/2061579/218351443-4ea94455-de32-4620-bae6-6763f51be868.png">

**Comment by darylc** [comment]
@ptr727 what do the *'s mean in that list and do you expect the sort to respect them or ignore them?

**Comment by jaredb7** [comment]
I was thinking we would respect their position, then sort the actual palette's correctly.
