### ISSUE TITLE
WLED config color palette edit in Hex

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1483]
**Is your feature request related to a problem? Please describe.**
Creating WLED overlay color palettes I have to manually convert between hex and decimal.  
Editing colors is done in decimal, color values after edit is displayed in hex.

**Describe the solution you'd like**
Allow color edit in hex, or decimal, or let me paste a hex color.

**Describe alternatives you've considered**
Use e.g. colorhexa.com to manually convert between colors.

**Additional context**
<img width="578" alt="image" src="https://user-images.githubusercontent.com/2061579/218354527-c06364a0-512a-46cb-b2bf-38491dc36d2d.png">
<img width="928" alt="image" src="https://user-images.githubusercontent.com/2061579/218354554-6df23311-e537-45ce-b228-d8fd016f07f1.png">

**Comment by jaredb7** [comment]
It appears for the colour input we're relying on the browsers browsers picker to allow the user to choose a colour and we're just taking the HEX value that's returned by the colour picker.

This is chrome's built in colour picker, it's not obvious initially but if you click the in the section where R G B  is, you can switch between the different colour definition modes. 3rd one is HEX you're chasing.
Doesn't appear to be a way to force one mode over another and also if it could be done not all browsers support the same ones. 

![image](https://user-images.githubusercontent.com/799998/219864330-281b791e-93d5-4b7b-a116-3e05375c5cc5.png)

**Comment by adamcoulombe** [comment]
Other pages (eg. display testing) within fpp use a color picker from a javascript library ([colpick](https://github.com/mrgrain/colpick))
![image](https://user-images.githubusercontent.com/469038/219869697-d36c8d00-7793-4907-b387-55f9b404936b.png)

**Comment by jaredb7** [comment]
That would be ideal for the commands requiring colour input, I'm sure the existing implementation was done for a reason. It literally requires nothing more than a input element with type colour and then everything else is automatic.
It works, but not entirely full featured and consistent.

![image](https://user-images.githubusercontent.com/799998/219873337-5070a661-b061-4943-a484-fd8067d2d480.png)

I did have a play switching it over to colpick, but unsure what other changes are required.
![image](https://user-images.githubusercontent.com/799998/219873705-f7f5c937-b7d9-49d0-930f-51f5c892ff2d.png)

**Comment by dkulp** [comment]
If it looks like that will work, please submit a pull request.   That looks much better.

**Comment by jaredb7** [comment]
Had some issues with the modal breaking the colpick plugin when it closed, but it's turned out nice.
![image](https://user-images.githubusercontent.com/799998/220348743-3cd23f81-d63d-435a-85f8-2e3b2a09fdd5.png)
