### ISSUE TITLE
Capture debug information from SSH CLI when web UI is not working

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1484]
**Is your feature request related to a problem? Please describe.**
One of my K4-PB frequently hang in the web UI #1436, making it impossible to capture logs.  
Accessing via SSH or terminal should be very reliable, and capturing logs from the CLI allow debug data collection when e.g. the web UI is not working.

**Describe the solution you'd like**
E.g. SSH, run debug capture command, capture logs, save local or auto upload results and return log ID to be used in error report.  
Additional troubleshooting would be cool, e.g. restart ffpd, print info, update, etc.

**Describe alternatives you've considered**
If the web UI is not working not much to do other than manually collecting files.

**Additional context**
NA

**Comment by darylc** [comment]
You already have a workaround to use the web UI - incognito mode.

**Comment by ptr727** [comment]
Today even incognito mode is not working, that is what prompted me to file this request.  
And what about the next bug where the UI is for some other reason not working?

**Comment by darylc** [comment]
@ptr727 If the UI doesn't work then the recommended solution is to reinstall FPP.  That is the quickest way forward for the end-user.  

There are very few people contributing to FPP, the unfortunate reality is way more issues, bugs and feature requests come in each year than can be handled by the current volunteers.   We are trying to close off requests that seem unlikely to be implemented in the next few years like this one.
