### ISSUE TITLE
FPP Backups then a Restore Configuration

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#1488]
FPP Backups then a Restore Configuration issue 

Pi 3 Model B Rev 1.2 on the 6.x-master

Last week I did a FPP Backups then a Restore Configuration on a Pi 3 Model B Rev 1.2 after the Restore Configuration "Remote Git Version:" was not able to connect.

This morning I did a redid Pi-6.3.fppos on this unit and got things working  then switched over to the master

It is up and running at 7.x-master

Don't know if there's an issue doing FPP Backups then a Restore Configuration

**Comment by darylc** [comment]
how sure are you the remote git version was correct on the FPP you backed up?

**Comment by JerryPlak** [comment]
Update info.
Decided to try again by making a new Backup Configuration than doing a Restore Configuration

Remote Git Version: was not available,  Was getting Could not read from remote repository.

Checking the logs I was getting  warning:  Clock skew detected
this is when I decided compare two unit one that I did a Restore Configuration and one I did not!!

This is when I realized the unit I did a Restore Configuration was no longer time and date synchronize
was comparing the two units and notice the restored unit NTP Server had "admin" entered I deleted and restart it the FPPD  now is synchronize time and date and Remote Git Version: available and was able to update to v7.x-master-43-gfcb09c38 (master branch)

Now looking in the JSON Backup file I was able to find this  "ntpServer":"admin"  don't know where it found "admin"  or up is part of the JSON Backup file

**Comment by jaredb7** [comment]
The ntpServer setting is in the main settings file for FPP, on a fresh install it won't be there as it's never been set but as soon it's set via the UI it'll appear with whatever value was entered. And backup process just takes the whole settings file as is (no processing of individual settings), meaning it was likely set to that when the backup was made.

It's weird the system you're backing up from doesn't have the issue though (i.e time issues)... On the system you made the backup from (which results in a backup config containing ntpServer = admin, are you able to check what the setting is, either via the web UI 
or via shell (go Help -> _SSH Shell, then enter the OS credentials of user: fpp, pass: falcon or OS password you set) then run `cat /home/fpp/media/settings | grep "ntpServer"`

Was the system you backed up on still v6.3?

Just examples what the settings and config backup files look like in regards to the system settings.
settings file
![image](https://user-images.githubusercontent.com/799998/227668693-e5098b71-c360-439b-b2a3-8839ddcc1ea3.png)

Backup Config
![image](https://user-images.githubusercontent.com/799998/227672512-1f5dbb3d-5376-42df-8c2c-cf3bb5f623db.png)

**Comment by darylc** [comment]
@JerryPlak ?

**Comment by darylc** [comment]
Close due to no response from @JerryPlak
