### ISSUE TITLE
Forum on website not sending emails 

### ISSUE THREAD

**Issue by adam-jones-net** [FalconChristmas/fpp#1490]
Hi this is about the forum on http://falconchristmas.com/ so a bit off topic but I found no other way of contacting anyone related to the project.

I've tried signing up and so has a friend in the last day and neither of us got confirmation emails to verify our accounts.    Is the site definitely working ok ?

**Comment by darylc** [comment]
Sorry that site is unrelated to us, all I can suggest is try an email with another email provider, or check spam folders or try a few days later etc.

**Comment by adam-jones-net** [comment]
@darylc  do you know who does run it out of interest?   And besides that, do you have other websites that you guys run yourselves or is everything contained within the github pages ?
