### ISSUE TITLE
There should be easy access to re-run the image resize tool after the prompt for it dissapears

### ISSUE THREAD

**Issue by adam-jones-net** [FalconChristmas/fpp#1491]
Due to lots of customisation of a remote player install, I created my own image of an SSD that was already setup and then used that image to create more remote falcon players.

In some cases, the new SSD's I was replicating the image onto were larger than the image itself.   The issue is that once these additional players have been setup, the web interface doesn't prompt for me to resize the partition to use all the space available, like it does on a fresh install.

I can't see anywhere in the documentation/web interface that refers to how to re-run this feature.   Can it be made into an option somewhere please.

If you could also clarify how I could re-run this script from the UI or shell that would be great.

**Comment by adamcoulombe** [comment]
Frist go to **Status/Control > FPP Settings > UI**  
Select **User Interface level = Advanced** 
Click on the **Storage** tab

You should have the option there to expand it

**Comment by adam-jones-net** [comment]
@adamcoulombe, amazing thanks for that!
