### ISSUE TITLE
Booting with a 1366x768 monitor on a Raspberry Pi 4b causes the screen to not initialise properly

### ISSUE THREAD

**Issue by adam-jones-net** [FalconChristmas/fpp#1492]
I am running FPP 6.3 on a Raspberry Pi 4b

I just ordered a new "UPERFECT 10.1’’ Raspberry Pi Touchscreen Monitor 1366x768 with Case" and my Pi 4b device fails to work with the screen on a fresh Falcon install, causing the monitor to instead show the famous test frames/colours that Pi's have been known to do, esp when using 1366x768 screens.

The device is booting fine, so it was possible to find on my network, go into the web UI and then change the resolution to 1024x768, which works but is far from ideal as the screen now has a quite large black border area that isn't used.

If this is a general issue with many 1366x768 monitors, maybe when the image first boots it detects an hdmi monitor with 1366x768, maybe it could auto down size to 1024x768 ?

**Comment by darylc** [comment]
Can you please explain further? FPP uses a web ui, no need for any screen.  I tested FPP on 1360x768 monitor via HDMI and it works fine.

**Comment by adam-jones-net** [comment]
I'm referring to the video output of the raspberry pi (ie a monitor plugged into the pi via hdmi) when being used for video playback by the software.

**Comment by darylc** [comment]
What does this mean? " causing the monitor to instead show the famous test frames/colours that Pi's have been known to do, esp when using 1366x768 screens."

**Comment by darylc** [comment]
None of us have the new "UPERFECT 10.1’’ Raspberry Pi Touchscreen Monitor 1366x768 with Case"  so I doubt we can do much unless you tell us what config file needs what changes in order to work properly on the raspi, then we could consider if those changes could be safely incorporated into FPP
