### ISSUE TITLE
BBB Failure update to  44272e26 

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#1493]
BBB Failure update to  44272e26 
the Pi and Debian ok 
[FPP_Logs_20230309.1951.zip](https://github.com/FalconChristmas/fpp/files/10935531/FPP_Logs_20230309.1951.zip)

**Comment by dkulp** [comment]
I'm not seeing this.  Are you sure the SD card is not full?     Try doing another upgrade.   Maybe do a "sudo ccache -C" to clear the ccache.   Not really sure what to suggest.

**Comment by JerryPlak** [comment]
the SD card is not full?  its a 32GB SD card it showing 25.75GB free

Tried doing a rebuilt FPP and tried "sudo ccache -C" to clear the ccache, it did not work.

I decided to run the BBB-6.3.fppos updater file, then did update FPP to.6.31 staple at that point
then change Git branch to master..

I was watching as it was doing changing Git branch to master was seeing some error I've attached the file with the message I was seeing... Don't know if this is helpful info for you..

[BBB master info1.txt](https://github.com/FalconChristmas/fpp/files/10936754/BBB.master.info1.txt)

I have the BBB back up and running on 7.x-master-27-g43b03c8b

**Comment by JerryPlak** [comment]
Closing this issue have moved on
