### ISSUE TITLE
FPP V7 server certificate verification

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1498]
fatal: unable to access 'https://github.com/FalconChristmas/fpp.git/': server certificate verification failed. CAfile: none CRLfile: none
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ghormann** [comment]
@bobreese  Can you give a bit more information about how this occur?  Was this a new install, were you trying to update an existing install if so what version are you currently add when trying to do the update.

I updated two differnt 7.0-masters to the latest w/o any issues.

**Comment by bobreese** [comment]
I did a 6.3 to 7 update.
It appears in the apache2-base-error.log
[apache2-base-error.log](https://github.com/FalconChristmas/fpp/files/11132601/apache2-base-error.log)

**Comment by darylc** [comment]
the clock is set wrong on your device:
Mon Sep 12 20:58:49.851773 2022

Fix that up and the certificate would then be valid.

The github.com certificate is not valid before Tue, 14 Feb 2023 00:00:00 GMT
