### ISSUE TITLE
Playing mp4s on FPP and Raspberry PI 4's results in some failing to output video after various hours of reliable playback

### ISSUE THREAD

**Issue by adam-jones-net** [FalconChristmas/fpp#1499]
This is using the latest (at time of writing) FPP 6.3 on multiple (5) Raspberry Pi 4b's.

All the devices run the same single video on a loop.   After a while some of the PIs will just go black.   Then this happens the problem PI's are still _up_ on the network and contactable and I can access their remote web interface.     

They seem to be sending a video signal still, it's just pure black.  I say this because the monitors never go into a screen stating "no signal" at any point.  

Often when this happens it seems that the multisync screen on the master player is missing the problem PI's that are now showing video.

Does this mean that this has to be a networking issue or is it a video output issue?  I thought for a while that maybe the PI's are unintentionally rebooting and if they do that during the night (when the screens are off) they are not able to initialise their video feed and so get confused.   Note that I DO have the "force hdmi display" option enabled.

Some more detail:
We had plugged in the 5 Raspis and left them running with the screens off for around 2 days.  Upon returning to them and turning on all the screens 3 of the 5 were just showing black screens, the other two fine.  I'd assumed maybe they had overheated and rebooted but this wasn't the case as via the web interface they all showed an uptime of 2 days, as well as very reasonable temperatures (50/60 degree range) so crashing/overheating had definitely not occurred.

**Comment by darylc** [comment]
Please upgrade to v6.3 and re-test, v4.3 is no longer supported.

**Comment by adam-jones-net** [comment]
Please re-open @darylc , I was using 6.3, that was an error on my part.

**Comment by dkulp** [comment]
This MAY be due to https://forums.raspberrypi.com/viewtopic.php?t=347881     I did upload 7.0-alpha1 images that are using the latest kernel.   Might be worth seeing if they help or not.

**Comment by wizoz** [comment]
wow! Thanks! looks spot on. Sorry for the lack of experience here, but can this be upgraded via the "developer" UI option (the same way I updated to the master)? or do I need to create the flash from scratch?

**Comment by darylc** [comment]
@adam-jones-net Did you re-test on fpp 7 alpha 1 as requested?

**Comment by darylc** [comment]
@wizoz @adam-jones-net Did either of you check to see if fpp 7 alpha 1 fixes this?

**Comment by wizoz** [comment]
I responded at the time - yes, it did (for me). There are still very rare failures, but nothing like before. (I work around it by setting a cron to look for ERR in the syslog and reboot when found)

**Comment by wizoz** [comment]
I have found that tho same video issue continues to occur in the latest release (7.1). I now testing a system with increased GPU memory (from 128 to 256MB' which is half the available RAM on a Raspberry pi 3) and it appears to be stable after several continuous operation. 

(I also did a reverse test - by reducing the GPU memory to 64MB and indeed the problem started to occur very frequently)
