### ISSUE TITLE
Please add php5-curl to the base image

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#150]
One of Ben's Plugins requires php5-curl. We have a few options.
-Add php5-curl to the v1.5 installer
-Have Ben's plugin check for the existence, if not there let the plugin install it.
-Add a message to Ben's plugin that it needs php5-curl and have the end-user install it

here is the command to add php5-curl

sudo apt-get install php5-curl

Pat

**Comment by JonB256** [comment]
"Ben's Plugin" is the projector plugin?

**Comment by patdelaney** [comment]
No - the plugins that you haven't seen yet.  The Weather Plugin

Pat

**Comment by cpinkham** [comment]
I have added php5-curl to my local copy of the FPP_Install script. Once I commit the change, the package should get installed when we build the next set of images or when users run the install script manually.

**Comment by darylc** [comment]
Can I suggest we have a generic way to add packages to fpp install's?

Eg perhaps a list of packages fpp should add.

I for instance want to use snmpset from scripts and have to install snmp
manually each time.
