### ISSUE TITLE
Detect and use the status of hdmi output in various parts of FPP

### ISSUE THREAD

**Issue by adam-jones-net** [FalconChristmas/fpp#1500]
This relates to ongoing issues I've had that I reported recently in [this bug issue](https://github.com/FalconChristmas/fpp/issues/1499).

Basically I'm requesting that the FPP software actively detects the status of any HDMI ports that are available on the platform it is running on.   It should then use this information in various new fairly simple features....

1) On the about page where a general status is shown for various hardware elements, there should be a status listed for the HDMI port/s.    It should show if something is actively connected, and if so what (ie obtain it's hardware description)

2) In the scheduler there should be an event that can be triggered if the HDMI port/s status changes, of it if equals a specific status (ie connected/disconnected).

These settings would be really useful in general I believe, not just to troubleshoot the kind of specific problem I face that I mention in the other ticket I reference.  Why? ...

- With multiple HDMI devices connected listing what is connected to each HDMI port could avoid confusion and clarify things are plugged into the right socket
- With an event possible in the scheduler, it would provide another level of failsafe.   I've used various pro display monitors and most of them all have logic and software control options to do certain things if they detect a problem with the HDMI source plugged into them.   This would be FPP assisting in the same way but from the other side of the setup, ie the source, not the output.

**Comment by darylc** [comment]
I am happy to add #1 to help->troubleshooting commands if you can let me know the name of the command the appropriate arguments to give it.

#2 seems best handled by a script.

**Comment by darylc** [comment]
@adam-jones-net any update?

**Comment by cpinkham** [comment]
It might be easiest to add a script to do this using tvservice and add the script to the troubleshooting commands. We should be able to use "tvservice -l" to get a list of connections and use the info from that with "tvservice -s -v ID_FROM_L_LISTING" to get info about each connected display.  Here are some examples from several systems:

DPIPixels enabled
state 0x400000 [LCD], 362x162 @ 60.00Hz, progressive

VGA monitor connected via GPIO header
state 0x400000 [LCD], 1366x768 @ 60.00Hz, progressive

DVI/HDMI monitor connected
state 0x6 [DVI DMT (87) RGB full 16:9], 1600x900 @ 60.00Hz, progressive

no HDMI, nothing on composite
state 0x40000 [NTSC 4:3], 720x480 @ 60.00Hz, interlaced

**Comment by darylc** [comment]
FYI tvservice seems deprecated, having trouble finding a replacement that works.  https://github.com/raspberrypi/userland/commits/master/host_applications/linux/apps/tvservice

**Comment by darylc** [comment]
I've done a bunch of research and unless someone can provide a way to determine the status of hdmi ports under modern linux on raspi, we're stuck.  Closing until such a time.
