### ISSUE TITLE
7.0-alpha1 wlan not enabled

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1505]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
BBB - 7.0-alpha1

**Describe the bug and Steps to reproduce**: 
Fresh image using RPimager, BBB connected via eth0 and wlan0 adapter plugged in for initial setup.
Perform initial setup, all DHCP, configure wlan update interface, grow f/s... both interfaces listed.
Shutdown and remove eth0 and restart... NOTHING. Doesn't acquire an IP address.
Plug eth0 in reboot, only see eth0 interface. Wlan has the right info, restart wlan interface and it comes up. 
Switch to use that IP, all okay.
Unplug eth and restart.. nothing

**Expected behavior**: 
Expected to run on wifi after inital config
NOTE.. same steps as above but using the 6.3 BBB image all works as expected.

**Additional context**: 
I did upgrade to latest V7 release after the image and still nothing.

[FPP_Logs_20230208.2025.zip](https://github.com/FalconChristmas/fpp/files/11300094/FPP_Logs_20230208.2025.zip)

Before updateing interface:
![image](https://user-images.githubusercontent.com/23619433/233758086-ce303a95-4c35-4d0d-80fb-5a294035b9c7.png)

After: (wifi config was already there, updated and restarted interface) poof....
![image](https://user-images.githubusercontent.com/23619433/233758142-c6a513e2-9ca0-4b6f-ae01-4bafb77c79b8.png)

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by cybercop23** [comment]
Seems to only be an issue with the alpha and the fppos images. 
Fresh install from 6.3 => upgraded to 6.3.5 => switched to master branch => All okay.

**Comment by bloojoop** [comment]
I can confirm that the issue I see is after doing a fppos upgrade.  with fpp os v2022.11 and on fpp master branch, wlan0 successfully joins my wifi network without issue.  Once I upgraded via fppos or fresh burn of alpha image (os vers v2023.04) then it will no longer join my wifi on boot up.  It will launch the tethering interface and I can tether successfully.  I can then select update interface and restart network with zero other changes and it will join my network just fine.  But will not join on boot up.  I do NOT observe this issue with my raspberry PIs... only by BBB/pb based controllers.  is the USB enumerating later in the boot process ??

**Comment by cybercop23** [comment]
Thanks @dkulp . The latest fppos ([BBB-7.0-alpha1_2023-04b.fppos](https://github.com/FalconChristmas/fpp/releases/download/7.0-alpha1/BBB-7.0-alpha1_2023-04b.fppos))  fixes the issue. Thanks much.
