### ISSUE TITLE
Upload Output from Xlights 2023.6 to FPP 5.5.26

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1506]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.5.26/K-16, xLights 2023.6

**Describe the bug and Steps to reproduce**: 
Saw this on the Zoom room just now and I was able to replicate it on one of my own ctrl.

Trying to Upload Outputs from 2023.6 => 5.5.26 gets Input Upload failed.
Using FPP connect and checking the cape checkbox allows the config to be uploaded, but of course that doen't upload Inputs.

View Log shows...

2023-04-25 17:47:28,632 8243223360 log_base [INFO] FPPConnect GET http://192.168.3.118/config.php  - Return: 0 - RC: 200
2023-04-25 17:47:28,662 8243223360 log_base [INFO] FPPConnect GET http://192.168.3.118/api/system/info  - Return: 0 - RC: 404  - <!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Limonade, the fizzy PHP micro-framework</title>
	<link rel="stylesheet" href="/api/?/_lim_css/screen.css" type="text/css" media="screen">
</head>
<body>
  <div id="header">
    <h1>Limonade</h1>
  </div>
  
  <div id="content">
        <div id="main">
      <h1>Page not found:</h1><p><code>(GET) /system/info</code></p>      <hr class="space">
    </div>
  </div>

</body>
</html>

2023-04-25 17:47:28,662 8243223360 log_base [ERROR] Attempt to upload controller inputs failed on controller Hanson Electronics:rPi-MFC:

**Expected behavior**: 
Expecting I/O to be send to the ctrl.

**Comment by darylc** [comment]
This would be an xlights but not a fpp bug since fpp 5.5 has not changed in some time.

Dan Kulp has stated that xlights will stop working with FPP 5.5 in 2023.  Whilst I don't agree with this, you should probably upgrade FPP to avoid getting caught up in it.
