### ISSUE TITLE
Mute Button

### ISSUE THREAD

**Issue by robbiet76** [FalconChristmas/fpp#1507]
It would be nice to have a Mute button option as an alternative to changing volume to 0.  This requires another step to return the volume back to its previous state.  A separate mute button would be nice as a temporary way to turn off the sound but then return to the previously set volume.

There could be a set of Mute and Unmute commands that go with this functionality.

I don't have a strong use case for this personally but just had the idea and thought I would share.  Perhaps this has already been discussed before.

**Comment by darylc** [comment]
If people really want this sort of functionality they can create a button to do it the big buttons plugin or similar.
