### ISSUE TITLE
REST API Endpoints not showing under help menu

### ISSUE THREAD

**Issue by dgrosch23** [FalconChristmas/fpp#1508]
End Points/Examples are not showing up under the help menu
![Screenshot 2023-05-02 084023](https://user-images.githubusercontent.com/48385716/235684411-4bdb77e7-2f77-4d13-83a7-89f49dc5f47f.jpg)

**Comment by dkulp** [comment]
Please upgrade to the latest on master (currently -88).   There are changes in this area. (splitting rest API and Command API's into two separate pages)

**Comment by dgrosch23** [comment]
I see the new menu item for the Command API's, listing and examples, however nothing is showing up for the REST API's.  Also, probably low priority, but the Brightness plug-in(at least from an API perspective) isn't working with this release either.  It always returns "Not Found".

**Comment by Poporacer** [comment]
@dgrosch23 Are you on the Current Master Branch as suggested? 
![image](https://user-images.githubusercontent.com/46263877/236234551-99afa0aa-9e60-49e1-86aa-da6a31a131ba.png)
