### ISSUE TITLE
Starting Effect with Script Not Working

### ISSUE THREAD

**Issue by Randomaker** [FalconChristmas/fpp#1509]
I needed to start an effect with a script. For testing, I am using the StartEffect.sh script from the script repository browser with no modifications (other than effect name).

My effect runs perfectly fine when I start it from the Effects page. However, I am having trouble getting it to work from the script.

When I run the script, it gives this output-
2,1,Starting Effect,0,,,,,,,,,

If I then look on the Effects page, it shows that it is running. However, it doesn't actually seem to output the effect on the lights or the virtual display.
If I stop it and restart it from the Effects page, it once again works perfectly fine and plays on the lights.

I am very stumped and have no clue what the problem is since there don't even seem to be any error messages. Already posted in two forums, no response from either after a few days.
I guess its a bug, but it's a very odd one.

**Comment by darylc** [comment]
I'd suggest starting effects via the REST API, the start effects script really should be removed.

**Comment by Randomaker** [comment]
> I'd suggest starting effects via the REST API, the start effects script really should be removed.

Could you give an example of how to do this?

**Comment by darylc** [comment]
eg curl http://127.0.0.1/api/command/Effect%20Start/deer1/1/true/false/false

but more to the point, why are you calling a script to start effects rather than starting effects directly from your playlist?

![image](https://github.com/FalconChristmas/fpp/assets/7511887/d892c368-b381-4d72-b86e-b2e9a2454dfc)

**Comment by Randomaker** [comment]
I need to control a snow machine from Remote Falcon. Apparently, RF cannot run a script directly, I already asked about that. Also, I need some way to only start the snow machine if it hasn't run in 5 minutes, which I am doing in my script.

**Comment by darylc** [comment]
@Randomaker What is causing your script to run?

**Comment by Randomaker** [comment]
> @Randomaker What is causing your script to run? Eg how does a script help you get around the remote falcon limitations?

I meant to say effect, not script. RF can not run an effect directly, I have no idea why. I think it could start an effect through an FPP command, but this still doesn't fix my problem. I still need to use a script to take care of only allowing the effect to run once every 5 minutes. I will give the REST API a try when I get a chance, that seems like a valid option.

**Comment by Randomaker** [comment]
REST API seems to be working. AFAIK this should work just fine the other way, but at least its working now.
