### ISSUE TITLE
I have been unable to get the "Display Testing" to work lately

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#151]
I used it last year frequently during light install.
I have yet to get it to work this year.

**Comment by JonB256** [comment]
Ooops, just tried it again on my BBB/Octoscroller and it worked. But, still no luck on my F4-B
Last year I only had a RasPi B and it almost always worked. Almost.

**Comment by JonB256** [comment]
The testing tab for playing a sequence seems to be very reliable.
The first tab testing, though, just seems to work when it feels like it.

**Comment by JonB256** [comment]
per AussiePhil's comments in a PM series, he does not have this problem. For me, it persists. Works fine when it works.

**Comment by JonB256** [comment]
This has been working very well now in v1.5 Master branch

**Comment by cpinkham** [comment]
Thanks for testing the new code, it should be a major improvement over the code in v1.5 and prior.  Closing ticket as part of v1.6 milestone.
