### ISSUE TITLE
home/fpp/media is running low on space (and "setting file does not exist")

### ISSUE THREAD

**Issue by wizoz** [FalconChristmas/fpp#1511]
I am running FPP version 7.x-master-69-ga4383cb1 on Raspberry Pi (Pi 3 Model A+).

I have a 4 FPP system, all with the above version, one master and 3 slaves, driving synchronized audio files in a single playlist. All are connected to a private dedicated wireless network. It has been working flawlessly for several days.

After a long time, the master failed and when opening its webpage, it only opens the initial setup page (initlialSetup.php) with the "low space" warning - despite the 16GB flash being only 30% utilized. 

**Remote reboot does not help** (I am accessing the FPP's remotely via a 5th RP that acts as my gateway using RealVNC - in fact I am filling this report remotely via the same RP).

If I check status via 'fpp -s', I get the following output:
(25052) [Settings] /opt/fpp/src/settings.cpp:255: Attempted to load settings file  which does not exist!

Important note: I am not using the "schedule" option, as it would be tedious to set it up to start the playlist every 15 minutes, so I created a cron that triggers the setlist every 15 minutes. The cron file has the following line:
*/15 * * * * /home/fpp/start_playlist.sh "Home Sounds Audio"
(start_playlist.sh is a simple script that takes one argument

playlist = "$1"
/opt/fpp/src/fpp -P "$playlist"

I cannot do anything with the UI, as it opens on the initial setup page, and refuses to save my entries.
I can access the files via the shell script, so the linux appears to be fine - log directory attached.

[logs.zip](https://github.com/FalconChristmas/fpp/files/11450499/logs.zip)

**Comment by darylc** [comment]
You appear to have multiple issues here. 

First re the initial setup page, you seem to have a corrupted install, potentially it could be a faulty SD card, hard to tell.  I'd reimage and see how you go.  

eg [Thu May 11 11:55:16.449921 2023] [proxy_fcgi:error] [pid 2070:tid 1549726720] [client 192.168.0.100:52684] AH01071: Got error 'PHP message: PHP Warning:  opendir(home/fpp/media/plugins/): failed to open dir: No such file or directory in /opt/fpp/www/api/index.php on line 183', referer: http://192.168.0.101/initialSetup.php?redirect=about.php

You also have a lot of these audio errors:
2023-05-10 21:25:19.735 (8548) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:1144: Audio has stalled   0

We've seen this error from time to time.  Usually it's something related to the hardware setup eg needing to use a powered USB hub when using a USB audio device etc eg issue #908

**Comment by darylc** [comment]
Also re  /opt/fpp/src/fpp -P "$playlist", usually you are better off using the FPP API from a script rather than calling these fpp with options - consider that deprecated.

**Comment by darylc** [comment]
> eg [Thu May 11 11:55:16.449921 2023] [proxy_fcgi:error] [pid 2070:tid 1549726720] [client 192.168.0.100:52684] AH01071: Got error 'PHP message: PHP Warning: opendir(home/fpp/media/plugins/): failed to open dir: No such file or directory in /opt/fpp/www/api/index.php on line 183', referer: http://192.168.0.101/initialSetup.php?redirect=about.php

I cut & paste the wrong error message, but from your log files your media directory doesn't exist which is why nothing can be saved either.

**Comment by wizoz** [comment]
Thank you for your help! 
Regarding the error about the media directory not existing, it does exist in its correct place, and it contains all the required subdirectories, including media/plugins which is empty (not surprising as I have not used plugins). I wonder if there could be an issue with the referral from /opt/fpp/www/api/index.php line 183?..

I plan to go over to check the platform physically (and perform power-on reset) later today.
Regarding using the FPP API from a script rather than calling the fpp with options - can you clarify? Is the following being deprecated?fpp -h	  Usage: /opt/fpp/src/fpp [OPTION...]  (from the help page), or do you mean to execute fpp -P 'playlist' directly and not via a parameter?

**Comment by wizoz** [comment]
Well, I am closing this issue.
Upon power-on reset, all returned to normal.
Thanks for the support!
