### ISSUE TITLE
Playlists containing only a script cannot be modified (or viewed) once created

### ISSUE THREAD

**Issue by wizoz** [FalconChristmas/fpp#1514]
Hi - I am running an FPP set as player (version v7.x-master-69-ga4383cb1
I am testing the feature which can run a python script, and created a simple playlist with a single (very simple) script to flash a couple of LED's a few times.

It works fine when I start the playlist in the status page - both one time, or in repeat mode. 

The problem is when I go back to check the contents of the playlist, and it looks completely empty with no option to add or replace scripts. (see attached picture). Pressing the button to +Add a Sequence/Entry appears to work but the playlist cannot be saved again, once originally created.

![Screenshot 2023-05-30 at 14 06 30](https://github.com/FalconChristmas/fpp/assets/39157192/d1f59c00-5aff-4c81-acf1-59a9e9dab31e)

**Comment by dkulp** [comment]
Can you update to the latest master code?  There are a bunch of updates to master since -69 and I want to make sure it's not fixed already.

**Comment by wizoz** [comment]
I updated the master to v7.x-master-103-g8b25feb3 (master branch), however, the problem unfortunately still persists.

**Comment by dkulp** [comment]
Fixed

**Comment by wizoz** [comment]
Great. Checked it and working. Thanks!
