### ISSUE TITLE
Not able to use the pause feature in the playlist.  

### ISSUE THREAD

**Issue by Richbeard** [FalconChristmas/fpp#1515]
FPP Version 6.3-7-g15823ca6 and 7.x-master-69-ga4383cb1 on a Pi4

**Describe the bug and Steps to reproduce**: 
I am not able to add the "Pause" feature in a playlist.   
1 go to "playlist"
2 click on "new playlist"
3 Name the playlist and add a description and leave randomize "off"
4 click "add a Sequence/Entry"
5 set type to "Pause"
6 set duration to anything I have tried from 5 secs to 120 secs 
7 Add a note if you want.  
8 and click "add" and nothing gets inserted.  

**Expected behavior**: 
I would expect the pause feature to show up in the list. 

**Additional context**: 
There are no errors it just doesn't show up in list.  

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20230603.1806.zip](https://github.com/FalconChristmas/fpp/files/11643371/FPP_Logs_20230603.1806.zip)

**Comment by dkulp** [comment]
Please upgrade to the latest on the master branch.   I believe this might be fixed.

**Comment by Richbeard** [comment]
Is 6.3-7 not the latest?   I have tried on both 6.3-7 and the Bata of 7 with the same results on 2 different Pi's.   
I can pull out my Kulp controllers and see if it happens on them as well.

**Comment by Richbeard** [comment]
I just reverted back to 6.x-master-648-g8378421c and the Pause works.

**Comment by darylc** [comment]
@Richbeard did the fix work for you?

**Comment by Richbeard** [comment]
> @Richbeard did the fix work for you?

Yes it did.   I updated and it works like a charm.
