### ISSUE TITLE
FPP7 Alpha:  rsync and samba settings are not restore after fppos update

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1517]
**FPP Version and Hardware**: 
*FPP 7.x master Pi and BBB*

**Describe the bug and Steps to reproduce**: 
If you have enabled Samba, rsync, and ftp and then do an fppos upgrade, the UI displays the services as enabled, but they were never really started.

**Expected behavior**: 
The services that were enabled before the upgrade should be enabled after the upgrade.

**Additional context**: 
This might also happen during a restore from backup

**Current Workaround**
Unselect the services and then reselect them.

**Comment by darylc** [comment]
@patdelaney did Dan's commit  https://github.com/FalconChristmas/fpp/commit/1d7a4152e663273d31436a4b69f4825108d3864d fix this?

**Comment by darylc** [comment]
no response from OP, closing
