### ISSUE TITLE
FPP 7.x Alpha:  popup Failed to save restartFlag setting

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1519]
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 7.x master BBB and PI* 

**Describe the bug and Steps to reproduce**: 
Whenever I restart fppd on any of my FPP's I get the Failed to save restartFlag setting popup
![image](https://github.com/FalconChristmas/fpp/assets/8147459/111fb56f-a449-49a5-bfe7-d350ffa5362b)

**Expected behavior**: 
That should not happen. It's happening on all my FPP

**Comment by dkulp** [comment]
Fixed
