### ISSUE TITLE
Latest Master update - BBB no longer Starts

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#152]
The Master change, probably related to adding the RGB/RBG/BRG etc and/or the Top Left/Right changes, is now keeping my P10 BBB from starting.

I was running Master on an F4-B, F16-B and a Octoscroller. Noticed the available update, 42fa5ff.
Once done, NONE of them would start.
Used developer.php to change to Stage branch.
Now, the F4-B and F16-B are working again
The Octoscroller still refuses to Start

**Comment by cpinkham** [comment]
I am running a clean master build from scratch on my BBB w/ Octoscroller and it is working fine.

Can you paste the tail end of your fppd.log file?

**Comment by JonB256** [comment]
noticed too late. Everything is working now.

**Comment by JonB256** [comment]
This can be closed.

**Comment by cpinkham** [comment]
Closing, I think this was a temporary breakage due to prep for addition of OLA output.
