### ISSUE TITLE
[DOC] MQTT Sound /Volume control

### ISSUE THREAD

**Issue by bakelitephone** [FalconChristmas/fpp#1520]
I am a big fan of controlling FPP using MQTT commands (from NodeRed) however it would be great if it was also possible to dynamically control volume via MQTT commands.

For example MQTT TOPIC "falcon/player/fpp1/set/volume"   MQTT PAYLOAD: "0 to 100"       (volume level)

My example "use case" I live away from busy roads so to it would be great if I could use my existing "microwave presence detectors" to increase the volume when an audience was present (within 30ft) and lower the volume if they walk away. For me this would be a big WAF as my wife thinks my existing external speakers annoy the neighbours if they are playing full volume when no audience is present to hear the sequence, but she still wants all the sequences to run but at much lower volume when the audience is not directly (more than 30ft away) outside the house.

Hopefully this extra MQTT volume functionality will have a lot of other similar uses, especially for small displays like mine :-) 
Plus in the UK (where I live) FM transmitters are not an option (FM power severely limited) and nearly all cars here are DAB so we rely exclusively on external speakers :-(

**Comment by bakelitephone** [comment]
After some really good help from Ben Dudley and Alex RB I can get it to work with the MQTT command line:
mosquitto_pub -h localhost -t "fpp/falcon/player/fpp3-NUC2/set/command/Volume Set/80" -m "" -u "username" -P "password"
So the current syntax is fpp/falcon/player/fpp3-NUC2/set/command/Volume Set/80

However to make it easier for people to understand and to implement it in "node red" etc could I request an enhancement so that volume value is sent as a "payload" rather than as part of the topic ???
EG: Topic: "fpp/falcon/player/fpp3-NUC2/set/Volume "  Payload: "80"

Regards & thanks Con Blackett

**Comment by ghormann** [comment]
@bakelitephone   What "help page" were you looking at?   
- https://github.com/FalconChristmas/fpp/blob/master/docs/MQTT.txt
- http://fppdev/commandhelp.php
- F1 on http://fppdev/settings.php#settings-mqtt

**Comment by bakelitephone** [comment]
> @bakelitephone What "help page" were you looking at?
> 
> * https://github.com/FalconChristmas/fpp/blob/master/docs/MQTT.txt
> * http://fppdev/commandhelp.php
> * F1 on http://fppdev/settings.php#settings-mqtt

The main one I use is the third one <F1> on the FPP itself as it populates the local host in the MQTT Topic etc (very neat) however I believe it would be useful to update all three with this information. :-)

Regards & thanks Con Blackett
