### ISSUE TITLE
x button to close git changes window not closing popup window

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1521]
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7 running on rpi zero
v7.x-master-118-ga91d7a52 (master branch)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to see git changes in popup
2. Try to close popup by clicking top right 'x'
3. Popup doesn't close

**Expected behavior**: 
Close git changes window

perhaps related to latest bootstrap update

**Comment by ghormann** [comment]
@OnlineDynamic  What browser were you using?   I attempted to reproduce but could not using Chrome on Windows 10.

![chrome_qSUcmjAgTl](https://github.com/FalconChristmas/fpp/assets/24968726/0b192a8a-1ece-41af-acdb-7a7f2fa3b138)

**Comment by OnlineDynamic** [comment]
on firefox 114.0.2 (64-bit)

**Comment by darylc** [comment]
Confirm that I also see this on firefox 114.0.1 (64-bit)

**Comment by ghormann** [comment]
I tried 114.0.2 (64-bit) on Windows with the latest version from master and can't reproduce.    Are any errors thrown in the console when clicking on the "x"? 

Here is my attempt: 

![firefox_vgJP8LLew2](https://github.com/FalconChristmas/fpp/assets/24968726/9a4ce7f7-8c8d-4977-b1d3-8b5b51ed9691)

**Comment by darylc** [comment]
![image](https://github.com/FalconChristmas/fpp/assets/7511887/1f486a5d-e98a-4576-9ed4-e228be487867)

**Comment by darylc** [comment]
you know, its just a problem of needing to refresh the page, shift-ctl-refresh fixed it for me.
