### ISSUE TITLE
Channel Output tabs varying on different browsers

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1524]
**FPP Version and Hardware**: 
[v7.x-master-122-g461d0928 (master branch)
rpi zero w
firefox and edge

**Describe the bug and Steps to reproduce**: 
1. go to channeloutputs.php in firefox
2. go to channeloutputs.php in edge
3. tabs at top of page vary between the 2
4. see screen shot - on the right the edge browser looks to be displaying correctly 
5. on left of screen firefox displaying LEDPanels which I expect to be disabled on this cape

**Expected behavior**: 
As above

![outtabsCapture](https://github.com/FalconChristmas/fpp/assets/68251154/9f14f8dc-b247-4a89-a630-67e072139511)

**Comment by dkulp** [comment]
Can you make sure you clear the caches on each browser and refresh?   I cannot reproduce this with different browsers on Mac.  (safari/chrome/firefox).     It looks like the UI level was changed between the two (Left is set to advanced, right to basic), but a refresh SHOULD make sure both are using the same level.

**Comment by OnlineDynamic** [comment]
@dkulp I have tried closing firefox, deleting all cache and broswer history but still seeing issue of difference between broswers, I'm on Win10

looks correct on chrome and edge - just firefox misbehaving

**Comment by OnlineDynamic** [comment]
@dkulp Have just tested via my phone and the latest Samsung Internet browser is misbehaving the same as firefox

**Comment by dkulp** [comment]
Is it actually misbehaving or is edge no correct?   if the UI level is set to "Basic", then only having the two tabs is likely correct.

**Comment by OnlineDynamic** [comment]
edge/chrome looks correct to me - tabs coming on and off as I enable/disable them in the cape config
firefox and samsung seem to be showing more than they should
UI is set to 'Basic'

Cape config has:

    "disableOutputs" :
    [
        {
            "file" : "config\/co-pixelStrings.json",
            "type" : "RPIWS281X"
        },
        {
            "file" : "config\/co-pixelStrings.json",
            "type" : "spixels"
        },
        {
            "file" : "config\/channeloutputs.json",
            "subType" : "RGBMatrix",
            "type" : "LEDPanelMatrix"
        },
        {
            "file" : "config\/co-other.json",
            "type" : "SPIws2801"
        }
    ],

So would expect the LED Panels tab to be hidden

**Comment by OnlineDynamic** [comment]
fixed with pull request #1589
