### ISSUE TITLE
menu not working in v7.x-master-134-g0ed2932f (master branch)

### ISSUE THREAD

**Issue by wizoz** [FalconChristmas/fpp#1527]
just upgraded to latest - 
menu item links (Status/Control, Content Setup..) all point to the current link, and do not open.
If I point the browser to the explicit link, e.g. xxx.xxx.xxx.xxx/multisync.php#, it obeys.

**Comment by dkulp** [comment]
Clear the browser caches.  That's important with this update.

**Comment by andyaz** [comment]
It looks to me like this was possibly resolved in 1b24fe2e. You might want to update to the current latest in the master branch and see if it works for you like it did for me...

**Comment by wizoz** [comment]
> Clear the browser caches. That's important with this update.

Thank you. It worked.
