### ISSUE TITLE
After Upgrade OS use the Pi does shutdown instead of reboot requiring hard power cycle

### ISSUE THREAD

**Issue by andyaz** [FalconChristmas/fpp#1528]
I have noticed the last couple of times I use the Upgrade OS button going back to v6 versions or so that instead of the Pi doing a restart it appears to do a shutdown. The remedy is to physically access the Pi and do a power cycle. This can be a pain as some of my Pis live in difficult to access places. I recall older versions did a restart after the OS upgrade in place finished...
Is this normal now or something that needs to be fixed in the upgrade OS code?

This is on Pi v3, 3b+ (don't have a 4 in my fleet to test on)
Multiple OS versions in the last year or so.
No logs attached as I don't think they would be of any use for this "issue"

**Comment by darylc** [comment]
@andyaz This bug is fixed was fixed after the v6.x series, so upgrading from any v7.x to any v7.x should be fine.

**Comment by andyaz** [comment]
After testing on 2 more Pis I disagree that this is fixed. I used Upgrade OS from 2023-04 7.x-135 to 2023-06 (Pi-7.0-beta1.fppos) and it appears to have shutdown. After completion the close button never came out of grey and waited 30 minutes with a continuous ping running and no ping from the device. Light on the Pi was only solid red as it would be from a shutdown.
Required a power cycle to reboot.

Pi3b+
![Capture](https://github.com/FalconChristmas/fpp/assets/19541773/e7bf0c55-7e26-4d85-bac1-c9bf46eab888)
[FPP_Logs_20230628.0429.zip](https://github.com/FalconChristmas/fpp/files/11889753/FPP_Logs_20230628.0429.zip)
