### ISSUE TITLE
Pixel Overlay bug - clean up both ends of Display

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#153]
The current code puts a few extra pixels on the ends to account for different size characters that could appear in the changing text but it does not account for a changing string length.  I think it would be possible to compare the previous string length to the current and when the new length is less than the old then either blank the display to clear or pad a few extra chars on the beginning and end to account for the difference in length.  I will think about it.  Can you open a bug report so it doesn't get forgotten?

**Comment by cpinkham** [comment]
This code was totally rewritten to do the text scrolling in fppd instead of the pixel overlay perl module.  Closing ticket as this does not seem to be an issue anymore.
