### ISSUE TITLE
Unable to start a playlist after the latest update 0eacb23

### ISSUE THREAD

**Issue by cscool36** [FalconChristmas/fpp#1532]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*
7.x-master-159-g0eacb23e Raspberry Pi 4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to status page
2. Click on arrow down for playlist and select playlist
3. Select playlist.
4. Press the play button.
5. A small screen with Command failed "Unable to start Playlist"

**Expected behavior**: 
Playlist does not start and no lights on.

**Additional context**: 
Also I have tring to setup the input from the F16V4 controller to FPP command Presets to start playlist but dose not work as well.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
6. Attach to this ticket.

![Screenshot (1)](https://github.com/FalconChristmas/fpp/assets/55654262/7718a6f1-0142-4858-a45e-922167843cd6)
![Screenshot (2)](https://github.com/FalconChristmas/fpp/assets/5565
![Screenshot (3)](https://github.com/FalconChristmas/fpp/assets/55654262/5f7b0483-02e8-4593-baca-71e24bbe6f74)
4262/910b8b36-5d3e-4c1d-8bd8-0c52be6660d1)

**Comment by Poporacer** [comment]
I am not seeing this, but there was an issue with one update that required you to clear your browser cache...What browser are you using? Try clearing your browser cache (all items) and see if that fixes it and let us know.

**Comment by dkulp** [comment]
I think the issue is that you have the Presets all named "PLAYLIST_STARTED" which would trigger when you start a playlist so it's going into a loop starting a playlist which triggers the other commands to start more playlists.

**Comment by Poporacer** [comment]
Just to expand on what @dkulp stated, you really shouldn't put a "Start Playlist" command in a PLAYLIST_STARTED system command (let alone multiples!)
The system commands are commands that will get triggered when certain system events happen. In your case, you used the PLAYLIST_STARTED system command. So ANY time FPP starts a Playlist, it will then trigger your first PLAYLIST_STARTED command and start your "Show 2023" playlist. But starting this playlist Triggers the PLAYLIST_STARTED  system command and will trigger your second PLAYLIST_STARTED entry and start your "After Hours 3" playlist...

But wait, this will then trigger a system command of PLAYLIST_STARTED and then start your "Show 2023" playlist and keep going in circles....

What are you actually trying to do? It isn't clear from your post.

**Comment by Poporacer** [comment]
Closed as this appears to be user error and no response from original poster
