### ISSUE TITLE
Most menus no longer function after updating to V7 beta

### ISSUE THREAD

**Issue by vanwilliam1960** [FalconChristmas/fpp#1535]
I just updated from V6.3 to V7beta on my main system player (Pi4). Now none of the dropdown menus are functioning (marked red on attached screencap). The links marked in green work. I've done a reboot and an FPPD restart, but no change. I've tried going to the system info screen to change back to V6.3, but nothing happens when I press Update OS.

I am running Chrome browser on Windows 10 Pro

![fppv7](https://github.com/FalconChristmas/fpp/assets/60276663/3587fc69-26dc-4889-a10e-26c51ef0ba2e)

Version Info |  
-- | --
FPP Version: | 7.x-master-130-g1b4fff63
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2023-06
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 10000000c529514d
Kernel Version: | 6.1.21-v8+
System Boot Time: | 2023-07-12 17:56:42
fppd Uptime: | 54:11
Local Git Version: | b0ee88e ChangeLog (Update is available)
Remote Git Version: | 1ba16bb Preview Changes

**Comment by dkulp** [comment]
After the 7 update, you will need to clear the browser cache or trigger a full refresh in the browser for the site.  That should get them working.

**Comment by jaredb7** [comment]
When viewing the FPP page, hold down Ctrl key and press F5 or hold down Ctrl and press the Refresh icon in Chrome

This will force the browser to reload all the assets for the web UI and get things going again.

After that, do an update via the about page to pull in all recent fixes.

Hopefully that helps 😊

**Comment by vanwilliam1960** [comment]
That worked! Thanks.
