### ISSUE TITLE
Can't play 1080p videos

### ISSUE THREAD

**Issue by bearpixels** [FalconChristmas/fpp#1536]
**FPP Version and Hardware**: 
FPP 6.3 running on RaspberryPi 2

**Describe the bug and Steps to reproduce**: 
When trying to play videos in 1080p, all I get is a green screen that flashes.

1. Installed FPP 6.3 on 2x RaspberryPi2
2. Set it to be one master and one remote
3. transfer a video file (Exported from Premiere, using H.264, so .mp4 file, 1920x1080, square pixels)
4. Created playlist and played it
5. Green screen flashes
5.1. If resolution changes to 1336 x 768, video plays normally and in sync on both RaspberryPis, but due to the wrong resolution, the image is distorted.
6. Trying to play only one video with only one RaspberryPi has the same effect.

**Expected behavior**: 
Play both videos in sync on 1080p.

**Additional context**: 
This is for 2 videos to play in sync, on a loop.

**Additional Attachments**
[FPP_Logs_20230714.zip](https://github.com/FalconChristmas/fpp/files/12052430/FPP_Logs_20230714.zip)
![WhatsApp Image 2023-07-15 at 01 04 14](https://github.com/FalconChristmas/fpp/assets/10836627/87c5225f-3277-4a07-bde2-301d7715942e)

**Comment by darylc** [comment]
@bearpixels please advise if this is still an issue in V7.0 https://github.com/FalconChristmas/fpp/releases/tag/7.0-beta1  No work is being done on 6.x release anymore.

**Comment by bearpixels** [comment]
> @bearpixels please advise if this is still an issue in V7.0 https://github.com/FalconChristmas/fpp/releases/tag/7.0-beta1 No work is being done on 6.x release anymore.

Yep. It happens on v7.0 too. :c
We've been testing all possible combinations.
When we export the file at 1.333 pixels size, the video kind of works. The issue then is that the quality goes down quite a bit, since the RaspberryPi running FPP doesn't seem to know how to adjust that...

Exporting with 1.333 pixel size basically gives us a 1440 file but since the size of the pixels are 1.333, it fills a 1920 area.

When we play the exact same file directly on TV or on MAC, the players know  how to adjust it and we get smooth curves and high quality, but whenever we play them on the RaspberryPi, we get different columns of pixels that don't seem to match correctly.

I'm adding some pictures of the screens (I know, maybe not the best method, to photograph a screen, but it is what I can do...) 
The umbrella in the corner and the actress's face are good examples of what changes. These pictures are from the exact same file, running on a MacBook Pro (quicktime) and on a RaspberryPi 2 running FPP v7.0.

![MacBook - Umbrella](https://github.com/FalconChristmas/fpp/assets/10836627/f2169b44-676d-4aaa-a0d0-0c8900b18663)
![MacBook - Face](https://github.com/FalconChristmas/fpp/assets/10836627/168b97fe-51e8-49da-b2fb-c0f2c6ceabc7)
![RaspPi - Umbrella](https://github.com/FalconChristmas/fpp/assets/10836627/787d9129-53e2-4fcd-9b76-609a0794b6b7)
![RaspPi - Face](https://github.com/FalconChristmas/fpp/assets/10836627/d039c3c8-4cfb-4d75-b493-718c06c4b014)

**Comment by bearpixels** [comment]
Was wondering if someone managed to play 1080p videos on 2x RaspberryPi 2 running FPP and in sync.
If so, how? What am I doing wrong / missing here?

**Comment by dkulp** [comment]
Doing some google searching, I'm generally seeing lots of problems with 1080p videos on the ancient Pi 2's, not even with FPP, just generally trying to play 1080p videos.  I'd definitely suggest an update to a Pi3 or Pi4.   Either that or use handbrake or similar to re-encode to 720p.

**Comment by dkulp** [comment]
Likely not something we can do anything about.
