### ISSUE TITLE
V7-master and .10 xlights - unable to handle sequence with foreign character

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1537]
When using fpp connect to upload a sequence with a foreign character it uploads but then breaks the File Manager.
It no longer shows any of the sequences.

The special e is not handled.

Pokémon Theme Song (Music Video).fseq

We can still see sequences in the drop drown in the status page - it just the file manager that goes empty.

**Comment by Poporacer** [comment]
Fixed with #c49f708
