### ISSUE TITLE
FPPv7. beta - Kulp16A-B - DAC not recognized or still falls back to "dummy output"

### ISSUE THREAD

**Issue by Jaimy-D** [FalconChristmas/fpp#1539]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP Version 7 beta, on BBB with Kulp16A-B

**Describe the bug and Steps to reproduce**: 
After helping a fellow enthousiast doing the intial settings & test some sequences, alle went fine till actual playback of a sequence with music.

FPP kept stating that it outputted audio to dummy output. 
- Set this to the onboard DAC from Kulp16A-B and rebooted.
- Once playing sequence it again stated to dummy output

- Retried setting it - not longer an option to choose Kulp audio DAC" 
- Rebooted 3x no luck setting the "DAC audio chip" - if it was an option to set, after reboot it was on "Dummy" again.

Reverted to FPP6.3 where with same sequence/mp3 and filenames there was no issue. As I'm fairly new to "submitting" issues in github, I forgot actually to dump files etc. However what I will do & update this issue where possible is to "reproduce this on my own Kulp16A-B controller by installing FPP7 beta & start playing with it" Will add screenshots & dumpfiles where possible on short notice

**Expected behavior**: 
DAC chip recognized & thus expected to hear the song while led would do blinky blinky flashy flashy

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by dkulp** [comment]
On the system settings tab, can you try setting a "Boot Delay" of 10 seconds and seeing if that helps.   It's quite possible/likely that the onboard sound is being detected after FPP has given up waiting for it and an additional few seconds could allow Linux to get it properly initialized.

**Comment by Jaimy-D** [comment]
Daniel,

And of course me trying to reproducing it on my own Kulp16A-B isn't going
well, in the sense of - I have a perfectly booting system over and over
again and having the DAC chip recognized.
The guy I was helping did buy the full monty from you, so controller, BBB,
and a pre-flashed 32Gb SDcard.

We will come over more to learn, thus might be that I have a small chance
to reproduce it then, however for now I think I consider this issue a
non-issue, and will remind myself that if I encounter it that I will start
out with a 10sec boot delay.
It makes the most sense for the time being.

Nevertheless, thanks for the initial quick response, keep up the good work,
it is really enjoyable using your controllers, FPP and xlights. I'm in year
3 and learning every day.


Best regards

Jaimy Deelen

Op ma 17 jul 2023 om 22:55 schreef Daniel Kulp ***@***.***>:

**Comment by dkulp** [comment]
This will be fixed with FPP7 final. (new Linux kernel)
