### ISSUE TITLE
Router Access

### ISSUE THREAD

**Issue by PapaStiff** [FalconChristmas/fpp#1544]
First, this is not a bug with FPP.  Instead, I no longer have access to my FPP because of an upgraded router.

Quick background.  My xLights show, and accompanying RPi/FPP, have worked great for years.  However, I just cut the cord and dumped my AT&T Uverse TV, AT&T modem, and AT&T router.  I went with a Spectrum modem (500M service) for internet service.  I originally went with an EERO Pro6E mesh network for the router.  I loved the EERO mesh because of the amazing wifi connections throughout the house.  The massive downside is they've taken away all admin rights.  You can now only access the mesh router via their phone app.  In other words, they've cut off my RPi/FPP/xLights show access via my home computer.  Note:  I have my xLights/FPP on its own network so it doesn't bog down my home network.  I talk wirelessly from my home computer to my RPi/FPP and also to my 3 falcon controllers.  I called EERO tech support: No luck.  They're stood pat on removing all admin access.  So, I set the mesh network aside and called spectrum.  Had them send me their wireless router (gave me their latest model SAX1V1R).  To my amazement, I still have no admin access rights.  I just read tech blogs online (about Spectrum's latest SAX1V1R wireless router) and apparently, they've also taken away admin access.  All access is now via phone app.  Ugh!!!  This must be a new trend! 

My question to the tech community is; What wireless router, here in summer 2023, can I go buy that still allows admin access to the router and will thereby allow me to access my RPi/FPP/xLights show from my home computer?  My Christmas xLights show is down until I can figure this out.  BTW:  Can I mix and match any of your newly suggested routers with my spectrum modem?  I assume the router is independent of the modem?

**Comment by Poporacer** [comment]
This is not the place for help requests. The best place for help would be in the xLights Zoom Room for info look here: https://youtu.be/YLf4Q98y_vk
But to answer a few questions...
`they've cut off my RPi/FPP/xLights show access via my home computer` You do not need admin rights to access your Show network.
`Note: I have my xLights/FPP on its own network so it doesn't bog down my home network.` You can have your FPP and controllers on your home network and it will not bog down your home network and is MUCH easier to manage and maintain. Refer to https://falconchristmas.github.io/FPP_Manual.pdf#page=163 In particular the With a Switch (non FPP Based Controllers) section.
