### ISSUE TITLE
Twinkly lights stop responding to FPP if Twinkly resets power midstream

### ISSUE THREAD

**Issue by tomhammond** [FalconChristmas/fpp#1545]
**FPP Version and Hardware**: 
Latest FPP 6.3 running on RPi4

**Describe the bug and Steps to reproduce**: 
When starting a playlist in FPP, FPP tells Twinkly to initialize, then it starts the playlist.  However, if Twinkly loses power in the middle of a playlist, then gains power again, it ignores FPP that is still running the playlist.  I have to stop the playlist in FPP then restart it.  At that point, the Twinkly's are initialized again and work properly.

When it works right:
1. Power on Twinkly
2. Start playlist in FPP
3. Twinkly lights up properly

When it doesn't work:
1. Power on Twinkly
2. Start playlist in FPP
3. Twinkly lights up properly
4. Pull power to Twinkly
5. Apply power to Twinkly
6. Twinkly does not resume playlist that FPP is still sending.  Instead, Twinkly lights are "off" or show built-in rainbow pattern.

Steps to workaround problem:
1. Power on Twinkly
2. Start playlist in FPP
3. Twinkly lights up properly
4. Pull power to Twinkly
5. Apply power to Twinkly
6. Stop playlist in FPP
7. Start playlist in FPP
8. Twinkly lights up properly.

Would it be possible to add a "command" in FPP's playlist feature that reinitializes the Twinkly outputs?  That way, I can add that command after a sequence.  When the playlist runs, it reinitializes the Twinkly's between sequences.  So, if the Twinkly's experience a temporary power loss, they will start working again at the next sequence.

Thank you for considering this,
Tom Hammond

**Comment by tomhammond** [comment]
Hi Dan,

Thanks for looking into this.  By closing this ticket, did you solve the problem?  If so, do I need the latest 7.x beta to try the solution?

Thanks,
Tom

**Comment by dkulp** [comment]
Yes.  On v7, it will validate the auth token every 120 seconds.   If it's invalid, it will re-authenticate.  Thus, if the Twinkly resets, then it restart itself after less than two minutes.

**Comment by tomhammond** [comment]
You made my day, thank you!  In thanks, I just now buy a K16 controller from you.  :)

To try your fix, do I download the latest 7 beta image, boot FPP, then tell it to upgrade using a different "branch" to get your latest Twinkly fix?

Thanks again,
Tom

**Comment by dkulp** [comment]
Yep.  The latest FPP7 beta fppos file and then go to the about page and hit the normal Upgrade button.   It will take while though as there have been a lot of changes since the beta.

**Comment by tomhammond** [comment]
Thanks so much.  Good to see you again at Expo.

**Comment by tomhammond** [comment]
I tested the fix; it works great.  Thank you.
