### ISSUE TITLE
Add subSeconds to MQTT output

### ISSUE THREAD

**Issue by pcuser42** [FalconChristmas/fpp#1546]
**Is your feature request related to a problem? Please describe.**
I'm trying to sync a custom application to what Falcon Player is currently having; it's mostly working but having whole seconds only in the MQTT output isn't quite precise enough.

**Describe the solution you'd like**
Adding subSeconds to MQTT output - I've seen references to this in the C code, though not sure how easy it is to add

**Describe alternatives you've considered**
Using the existing seconds field

**Additional context**
N/A

**Comment by ghormann** [comment]
Technically this is doable, but I would think the MQTT brocker is going to add additional lag that would be hard to predict.    For your use case would it be better to listen to the FPP Multisync packet? 
https://github.com/FalconChristmas/fpp/blob/master/docs/ControlProtocol.txt

**Comment by pcuser42** [comment]
Thanks for that, looks like the multisync packet will do the job. :)
