### ISSUE TITLE
v 6.3 Does "RUN" work from the File manager?

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1547]
I have a simple 2 line script that echoes to a file - to show that it is running. 
When I run from here .. it does not work.
![image](https://github.com/FalconChristmas/fpp/assets/4643499/9d7a9c5e-74c7-480e-8e00-074aee1f048b)

When I run from here it does..
![image](https://github.com/FalconChristmas/fpp/assets/4643499/f502700a-459e-4838-be14-ec8c9330225b)

**Comment by derwin12** [comment]
Simple script
![image](https://github.com/FalconChristmas/fpp/assets/4643499/65c1054a-8359-43f0-8675-dacb58d048da)

**Comment by ghormann** [comment]
I suspect it is running, just putting the log file in a different location than you would expected.   I tested with 7.0-master

![image](https://github.com/FalconChristmas/fpp/assets/24968726/9ef52b3e-f4fb-46cf-860c-66b18b26b64b)

File end up in a protected directory

![image](https://github.com/FalconChristmas/fpp/assets/24968726/1f145d7a-8cfc-4e8a-a24d-afba43842d9f)

Data is outputted to the screen as expected. 

![image](https://github.com/FalconChristmas/fpp/assets/24968726/afac759f-fcad-46bb-86d9-c88564884b31)

**Comment by derwin12** [comment]
Yea .. that was likely it .. it wasnt outputting to the expected directory.
