### ISSUE TITLE
v7 . X master down load issue

### ISSUE THREAD

**Issue by jeffc930** [FalconChristmas/fpp#1549]
1. Issue downloading FPP v7 Beta via the About FPP page 
2. Windows 11
3. Not sure what I'm missing her but when i  have downloaded version 7  to a pi none of the drop down lines work for me. I've done this on a BB and get the same results, the only way I do get these to work is download a new image and start over.
Some points can be reached using the mouse but not any of the drop down lists on the top (Status,Content,Input,Help)

Thanks
(https://github.com/FalconChristmas/fpp/assets/81841941/0f1a4a3e-7ee4-44be-bdd3-317f16292e1e)

**Comment by dkulp** [comment]
You likely need to clear the browser cache.

**Comment by jeffc930** [comment]
That was it exactly, thanks Dan
