### ISSUE TITLE
Audio output Device drop-dwon not displaying correct

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#155]
I think there is an issue with the parser to determine audio devices. When I plug in a USB audio dongle in PI v2 the second option I get in the dropdown is Set.
![audio_error](https://cloud.githubusercontent.com/assets/8147459/9173201/28930d82-3f3e-11e5-8ed9-f7ed22dfc3b6.jpg)

**Comment by patdelaney** [comment]
FYI if I edit the /etc/modprobe.d/alsa-base.conf  file and comment out this line:
options snd-usb-audio index=-2

Then reboot, I still get the odd choice in the dropdown, but I am able to use the Behringer XENYX 302 mixed as an audio output device.

**Comment by patdelaney** [comment]
I accidentaly closed this

**Comment by cpinkham** [comment]
I have a Pi v2 installed using the FPP v1.5 Beta image for the Pi and when I plug in my Behringer 302, I get 'ALSA' and 'CODEC' in the dropdown.  Which image are you running on your Pi?  Can you update to the Beta image posted by Mat in the developer forum in the release timeline thread on page 4?

**Comment by patdelaney** [comment]
I got the same, when I plugged in the mixer, when I plugged in a different
USB audio device I got Set in the dropdown.

The usb device I am using is:
http://www.dx.com/p/hexin-universal-usb-2-0-external-sound-card-adapter-for-laptop-pc-white-160513#.Vco50P3bKUk

I should have updated the ticket

Pat

**Comment by patdelaney** [comment]
Sorry I was using latest image.
Pat

**Comment by patdelaney** [comment]
I can investigate on my end .. what it the webpage parsing to get the
dropdown choices?

Pat

**Comment by cpinkham** [comment]
/opt/fpp/www/settings.php runs a shell command to get the list of cards from /proc/asound/card*/id:

for card in /proc/asound/card*/id; do echo -n $card | sed 's/.*card\([0-9]*\).*/\1:/g'; cat $card; done

Then it builds the dropdown from the id:name array it read in.

**Comment by patdelaney** [comment]
So I did some poking around, so if I cat out the "cards" file I get the
following with the usb audio card inserted.
 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [Set            ]: USB-Audio - C-Media USB Headphone Set
                      C-Media USB Headphone Set at usb-3f980000.usb-1.4,
full speed

So the name that it's choosing for each device is the ALSA for the on-board
audio and Set for the USB card. It appears to be the last word in the
string.

So a few Questions:
1) On a Pi using a USB audio device, what does the "Force Analog Audio
Output" check box in FPP Global Settings really do?

I am going to retest USB audio on a fresh image and fresh USB stick. I do
not want to carry over any previous files.

Pat

**Comment by cpinkham** [comment]
I found I have a USB dongle from Adafruit that does the same thing. 

fpp@FPP ~ $ for card in /proc/asound/card*/id; do echo -n $card | sed 's/.*card\([0-9]*\).*/\1:/g'; cat $card; done
0:ALSA
1:Set

I have a better command to get the card array:

fpp@FPP ~ $ sudo aplay -l | grep '^card' | sed -e 's/^card //' -e 's/:[^\[]*\[/:/' -e 's/\].*\[.*\].*//' | uniq
0:bcm2835 ALSA
1:C-Media USB Headphone Set
2:HiFi-FMT / VAST ELECTRONICS

FPP stores the card by ID, so these names work fine.  Fix committed to master and stage.

**Comment by patdelaney** [comment]
OK so I started with a fresh OS and a USB Media Stick. After it's was all
installed, I checked the Audio drop down. There was only one setting.
I plugged the USB audio card in, hit F5 to refresh the UI and I saw the new
USB audio stick.

I chose the USB audio Stick. I was prompted to restart fppd. I restarted it.
I went back to the status page and tried to play an audio file.
I move the speaker plug to the USB audio card and started the playlist.....
No audio
I move the speacker plug back to the on-board audio jack and I could hear
the music.

I Went to the settings page  and clicked on Force Analog Audio Output,
Repeated the steps above and still no audio out the USB.

I reboot, but only get the audio out the onboard audio jack.

But the good news is I think I know the fix:

$ sudo nano /etc/modprobe.d/alsa-base.conf

look for this line:
options snd-usb-audio index=-2

Now comment it out:
#options snd-usb-audio index=-2

Save the file

Reboot

and now the Pi speaks the IP address out the USB Audio card

FYI the Volume control does not adjust the volume of the USB audio card
output

I changes the Audio card back to on-board and then restarted FPPD.
Move the speaker plug back to the on-board jack
Started teh playlist. I got audio out and I can adjust the volume.

We will is there a better way? If not we will have to release note the
issues with "some" USB audio cards.

I will cross post this on developer forum.

Pat

**Comment by Materdaddy** [comment]
I replied on the developer forum, but might as well put it here.  Change your steps from:

> OK so I started with a fresh OS and a USB Media Stick. After it's was all installed, I checked the Audio drop down. There was only one setting.
> I plugged the USB audio card in, hit F5 to refresh the UI and I saw the new USB audio stick.
>
> I chose the USB audio Stick. I was prompted to restart fppd. I restarted it.
> I went back to the status page and tried to play an audio file.
> I move the speaker plug to the USB audio card and started the playlist.
> No audio
> I move the speacker plug back to the on-board audio jack and I could hear the music.

Change those steps to:

> OK so I started with a fresh OS and a USB Media Stick. After it's was all installed, I checked the Audio drop down. There was only one setting.
> I plugged the USB audio card in, hit F5 to refresh the UI and I saw the new USB audio stick.
>
> I chose the USB audio Stick. I was prompted to restart fppd. I restarted it.
> I went back to the status page and tried to play an audio file.
> ***Adjust the volume (even though the UI will still show what the original card's volume was, the new one is likely muted).***
> I move the speaker plug to the USB audio card and started the playlist.

If this works for you, I'll make a change that when we switch audio cards we also set the volume to what the UI (and therefore user) thinks it is.
