### ISSUE TITLE
6.3 FPP Setting Input/Output tab not accessible

### ISSUE THREAD

**Issue by kepowell2** [FalconChristmas/fpp#1550]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.3 running on RPi 3B*

**Describe the bug and Steps to reproduce**: 
When in the FPP Setting page, there is no Input/Output tab to select. 

I am trying to select a Command Preset Control Channel. When in the Command Presets page and click the button to go to the Input/Output tab nothing loads, just the spinning wheel.

**Expected behavior**: 
In the FPP Settings page I would like to get to the Input/Output page to set the Command Preset Control Channel.

**Additional Attachments**

![FPP I_O page not loading](https://github.com/FalconChristmas/fpp/assets/140576833/45299359-af35-4ea6-af58-6fcae7e449d0)

**Comment by kepowell2** [comment]
[FPP_Logs_20230727.0154.zip](https://github.com/FalconChristmas/fpp/files/12178622/FPP_Logs_20230727.0154.zip)

**Comment by Poporacer** [comment]
This is by design. In order to access the Input/Output tab, you have to be in the Advanced UI Mode.
From the Manual:
![image](https://github.com/FalconChristmas/fpp/assets/46263877/6566cccc-7a85-4564-86ec-e088e21b9002)
