### ISSUE TITLE
Permission denied  on /dev/i2c-1 and on /dev/ttyAMA0

### ISSUE THREAD

**Issue by djulien** [FalconChristmas/fpp#1555]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.0 on RPi 3B

**Describe the bug and Steps to reproduce**: 
When running fppd manually using fppd_gdb.sh, a couple of Permission Denied errors are occurring:
```
Error: Could not open file `/dev/i2c-1': Permission denied   
...
[ChannelOut] /opt/fpp/src/channeloutput/USBDMX.cpp:99: Error 13 opening /dev/ttyAMA0: Permission denied  

```
**Expected behavior**: 
No permission-denied errors

**Additional context**: 
`groups fpp`  #gives the following:
>   fpp : fpp adm sudo audio video gpio 

*It looks like fpp does not belong to a couple of needed groups: i2c, dialout
To fix, use these commands:
```
  sudo adduser fpp i2c
  sudo adduser fpp dialout

```
**Additional Attachments**
added via comment

Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by djulien** [comment]
[FPP_Logs_20230731.0339.zip](https://github.com/FalconChristmas/fpp/files/12211269/FPP_Logs_20230731.0339.zip)

**Comment by dkulp** [comment]
fppd needs to be run as root.   fppd and the gdb scripts should not be run as the fpp user.

**Comment by djulien** [comment]
Ah, okay.  I guess my notes on debugging are incorrect.  Thanks!
