### ISSUE TITLE
Hide 172.16.x.x/12 Subnets in systems list

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1557]
Is /12 accurate? I cant find anything in google referencing what /12 might be used for.
![image](https://github.com/FalconChristmas/fpp/assets/4643499/dff25d27-cdc7-4ced-ae21-cbeb00e1afb0)

**Comment by darylc** [comment]
See https://datatracker.ietf.org/doc/html/rfc1918
