### ISSUE TITLE
"Failed to scan for WiFi networks" popup

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1560]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.0.ff5e66d on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Network Configuration / Host & DNS Settings page
2. Do nothing
3. Popup comes up
<img width="1415" alt="image" src="https://github.com/FalconChristmas/fpp/assets/2061579/a42051c6-5e21-4d60-86a5-7e567d2b180b">

**Expected behavior**: 
No uninitiated popup.

**Additional context**: 
NA

**Additional Attachments**
[FPP_Logs_20230811.1521.zip](https://github.com/FalconChristmas/fpp/files/12322907/FPP_Logs_20230811.1521.zip)

**Comment by ghormann** [comment]
Can you provide the output of http://fpp/api/network/wifi/scan/wlan0

I don't see an obvious problem looking at the logs.

**Comment by ptr727** [comment]
I upgraded two K4-PB's, and bot did this when I was just sitting on the DNS page.

I am trying to run the API get, but the page just hangs, oh wait it just returned, just took a while:

```json
{"status":"OK","networks":[[],{"freq":2437,"signal":"-80.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":2437,"signal":"-80.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"},{"freq":2437,"signal":"-72.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":2437,"signal":"-80.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":2437,"signal":"-72.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":2437,"signal":"-71.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"},{"freq":2462,"signal":"-47.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":2462,"signal":"-47.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"},{"freq":2462,"signal":"-47.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":5200,"signal":"-72.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":5200,"signal":"-71.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"},{"freq":5200,"signal":"-71.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":5220,"signal":"-79.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":5220,"signal":"-83.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":5220,"signal":"-73.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":5220,"signal":"-73.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"},{"freq":5220,"signal":"-74.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Family"},{"freq":2412,"signal":"-76.00 dBm","lastSeen":"6 ms ago","SSID":"Skaariboon"},{"freq":2412,"signal":"-77.00 dBm","lastSeen":"6 ms ago","SSID":"Skaariboon-guest"},{"freq":5765,"signal":"-41.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos"},{"freq":5220,"signal":"-86.00 dBm","lastSeen":"6 ms ago","SSID":"Draadloos_Guest"}]}
```

**Comment by ptr727** [comment]
Lol, just happened again, just sitting on the page:  
<img width="1018" alt="image" src="https://github.com/FalconChristmas/fpp/assets/2061579/83fec501-fe60-4f69-bfaf-421a0559bf40">

**Comment by ghormann** [comment]
Pushed a change to master that increase the timeout limit for wifiscan.    Also add a visual queue that a scan was being preformed.

**Comment by ptr727** [comment]
Per the code the timeout is now 30s if I understand it right, and I wonder if a different approach is not required?

I did some timing testing using Chrome's network developer tools for timing, and here are the timings from one device using `api/network/wifi/scan/wlan0`:

- 22.2s, results ok.
- Never completed, waited 5+ minutes.
- 30.4s: no results returned, `{"status":"OK","networks":[]}`
- 18.73s, results ok.
- 14.83s, results ok.
- Never completed, waited 5+ minutes.
- 7.4s, results ok.
- Never completed, 504 timeout, 20 minutes.

There seems to be an issue with some scans never completing, and a 30s timeout will still result in an unwanted popup?  
Maybe the actual scan itself needs to limit its own runtime?

**Comment by dkulp** [comment]
Could you try SSH'ing in and running "sudo time iw dev wlan0 scan" a bunch of times and seeing how long that may take?

Maybe try "sudo time iw dev wlan0 scan duraction 10s" to see if that would limit it to 10 seconds?

**Comment by ptr727** [comment]
`sudo time iw dev wlan0 scan`:

- `0.02user 0.14system 0:09.99elapsed 1%CPU (0avgtext+0avgdata 1432maxresident)k`
- `0.01user 0.15system 0:09.75elapsed 1%CPU (0avgtext+0avgdata 1488maxresident)k`
- `0.02user 0.15system 0:09.65elapsed 1%CPU (0avgtext+0avgdata 1428maxresident)k`
- `0.02user 0.15system 0:09.91elapsed 1%CPU (0avgtext+0avgdata 1432maxresident)k`

`sudo time iw dev wlan0 scan duraction 10s` -> `duraction` -> `duration`?  
`sudo time iw dev wlan0 scan duration 10s` -> `command failed: Operation not supported (-95)`

**Comment by patdelaney** [comment]
I reopened this issue as I am now seeing it on a Pi5.
I have the latest code from the master branch,
My time is correct on the Pi
I get the following out put when running http://192.168.1.140/api/network/wifi/scan/wlan0
`<br />
<b>Fatal error</b>:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /opt/fpp/www/api/controllers/network.php:41
Stack trace:
#0 /opt/fpp/www/api/controllers/network.php(41): strpos()
#1 /opt/fpp/www/api/lib/limonade.php(430): network_wifi_scan()
#2 /opt/fpp/www/api/index.php(185): run()
#3 {main}
  thrown in <b>/opt/fpp/www/api/controllers/network.php</b> on line <b>41</b><br />`

I also ran the sudo time iw dev wlan0 scan command and I will attachethe output.

[imescan.txt](https://github.com/FalconChristmas/fpp/files/14072563/imescan.txt)

**Comment by patdelaney** [comment]
While validating the fix I no longer get the time out, but I noticed that after I enter the SSID and the Preshared Key, when I press update interface I see the red Performing WiFi Scan... message appear.  Note: is does the same thing in 7.5, but is it really supposed to?

![image](https://github.com/FalconChristmas/fpp/assets/8147459/588bdc5e-b931-4f36-a237-5af79e575c5d)
