### ISSUE TITLE
Half the WLED string lights were white, got a crash report

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1561]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.0.ff5e66d on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. WLED schedule runs every day
2. Today I noticed half the string is white
3. Logon to web, see there is a crash report

**Expected behavior**: 
All lights work as always, no crash.

**Additional context**: 
I did some painting and wire cleanup, thought I may have broken power injection, but double checked, PI working, then looked on web console, and saw crash report. 

**Additional Attachments**
[FPP_Logs_20230823.0439.zip](https://github.com/FalconChristmas/fpp/files/12415173/FPP_Logs_20230823.0439.zip)
[fpp-BBB-7.0-2023-08-22_21-28-59.zip](https://github.com/FalconChristmas/fpp/files/12415174/fpp-BBB-7.0-2023-08-22_21-28-59.zip)

**Comment by dkulp** [comment]
This looks like the schedule/WLED commands were created with FPP6.3.   The WLED effects are completely updated in FPP7 and take different arguments.  Some take fewer, some take more, etc...   Thus, the commands that use them will need to be re-created.

**Comment by ptr727** [comment]
I did notice the palette colors were different after upgrading, but 1) I must have missed the release notes that an upgrade requires WLED recreation, and 2) if the upgrade is going to break something them maybe it should a) support an upgrade or b) delete the will-be-broken after upgrade settings, especially if it will crash, 3) I'm then surprised it's been running for as long as it did.

**Comment by ptr727** [comment]
I have scheduled WLED commands for daily and for yearly holidays, is it sufficient if I just open the schedule, edit the command, fix the WLED palette, and save the entry, or do I literally have to delete and recreate the scheduled commands?
