### ISSUE TITLE
Idle Power Relay Control

### ISSUE THREAD

**Issue by carlallen** [FalconChristmas/fpp#1562]
**Is your feature request related to a problem? Please describe.**
Digital LED strips still use power when seemingly switched off, about 1W per 200 LEDs. Using GPIO to switch a relay on the power to the LEDS when the player is idle will help conserve power.

**Describe the solution you'd like**
This feature already exists in WLED, implementing similarly would be ideal. 

In WLED there is a setting for `Relay GPIO`, and also an invert checkbox. When this settings is not `-1`, the respective GPIO pin is pulled high(or when invert low) when LED output is on.

**Describe alternatives you've considered**
I could probably use the `CheckIfPlaying.sh` script in a loop and flip the GPIO there, but this feels like something that might be better in mainline fpp.

**Additional context**
https://kno.wled.ge/features/relay-control/

**Comment by dkulp** [comment]
This is already implemented in FPP7.  There are command pre-set trigger names of "OUTPUTS_ENABLED" and "OUTPUTS_DISABLED" that can be used to do anything that is needed when the outputs are enabled/disabled.  You can create a pair of command presets that turn on/off the GPIO pin.
