### ISSUE TITLE
7.1 Upgrade - No Manual Button

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1564]
The instructions say
"you can go to the FPP about page (about.php) and click on the "Manual Update" button."
There is no Manual Update button on the screen.
There is however the Pi-7.1_2023_08.fppos option in the Upgrade OS pull down.

![FPP Upgrade](https://github.com/FalconChristmas/fpp/assets/461610/985a715b-dba8-491c-accd-41af7d1e1cfb)

**Comment by dkulp** [comment]
You are a bit too quick....   None of the upgrade to new version things were updated to Bootstrap 5 (since there wasn't a way to test it) so we're still working on that part.  7.1 hasn't been announced yet.  Give use a little more time.
