### ISSUE TITLE
Playlist starts after manually playing an FSEQ file from the status page

### ISSUE THREAD

**Issue by robbiet76** [FalconChristmas/fpp#1566]
After manually playing any FSEQ file from the status screen, the player immediately starts playing a playlist upon the FSEQ file finishing.  I've removed the playlist that was being played, but there is now an error that pops up after the FSEQ file finishes, as FPP is still looking for the playlist. "Could not load playlist..."

I've attached 3 screenshots.  First in FSEQ playing.  Second is error message.  Third is the FPPD log entries.
[FPP_Logs_20230828.1438.zip](https://github.com/FalconChristmas/fpp/files/12455503/FPP_Logs_20230828.1438.zip)
![FSEQ Finished](https://github.com/FalconChristmas/fpp/assets/63306703/1138a75c-9ecb-40a8-b7f8-6f29ca26ad1b)
![FSEQ Playing](https://github.com/FalconChristmas/fpp/assets/63306703/9e202d49-2308-409c-9127-83be221e41b1)
![FPPD Log](https://github.com/FalconChristmas/fpp/assets/63306703/733a5a7d-526c-4bcd-9b2f-627aeefaf2f1)

**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP 7.0 on Rasp Pi 3B (also tried with 7.1): 

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by dkulp** [comment]
You likely have a schedule set to play that playlist.   When fpp is done playing a playlist, it checks the schedule to see if there is something else it's supposed to be doing.   Check the Scheduler page to see what is scheduled.

**Comment by robbiet76** [comment]
It doesn't look like there is any schedule behind the scenes...

fpp@Main:~ $ cd /home/fpp/media/config
fpp@Main:~/media/config $ ls -1
backups
cape-eeprom.bin                                                                                                                                                                        
channeloutputs.json                                                                                                                                                                    
ci-universes.json                                                                                                                                                                      
commandPresets.json                                                                                                                                                                    
co-universes.json                                                                                                                                                                      
dns                                                                                                                                                                                    
Falcon.FPDV1
FPP.FPP-Plugin-MessageQueue.db                                                                                                                                                         
instantCommand.json                                                                                                                                                                    
interface.eth0                                                                                                                                                                         
interface.wlan0                                                                                                                                                                        
media_durations.cache                                                                                                                                                                  
model-overlays.json                                                                                                                                                                    
outputprocessors.json                                                                                                                                                                  
plugin.fpp-BigButtons.json                                                                                                                                                             
plugin.fpp-brightness.json                                                                                                                                                             
plugin.fpp-HomeAssistant.json                                                                                                                                                          
plugin.FPP-Plugin-EventDate                                                                                                                                                            
plugin.FPP-Plugin-Matrix-Message                                                                                                                                                       
plugin.FPP-Plugin-MessageQueue                                                                                                                                                         
plugin.remote-falcon                                                                                                                                                                   
proxies                                                                                                                                                                                
schedule.json                                                                                                                                                                          
virtualdisplaymap                                                                                                                                                                      
fpp@Main:~/media/config $ cat schedule.json
[]fpp@Main:~/media/config $

**Comment by Poporacer** [comment]
Do you have any Command Presets?

**Comment by robbiet76** [comment]
Since setting up my halloween schedule, this issue has gone away and I cannot reproduce.  This can be closed if nobody else is seeing this issue.  Thanks.
