### ISSUE TITLE
[ChannelOut] /opt/fpp/src/channeloutput/UDPOutput.cpp:435: sendmmsg() failed for UDP output (key: 1936   Socket: 11   output count: 4/5 ) with error: 101   Network is unreachable

### ISSUE THREAD

**Issue by dianaj93** [FalconChristmas/fpp#1568]
fppd.log and syslog keep showing this error:
[ChannelOut] /opt/fpp/src/channeloutput/UDPOutput.cpp:435: sendmmsg() failed for UDP output (key: 1936   Socket: 11   output count: 4/5) with error: 101   Network is unreachable

log files attached.
My setup:
eth0 is connected to network data box (controller), wlan0 is connected to local network router with static IP.
Seq is created using xlights and uploaded.
Whenever the router is disconnected, seq continues playing as expected, but above error is written in log until eventually fpp runs out of memory.
Please advise.

**Comment by darylc** [comment]
Nothing was attached, but in any case, why is the router disconnected?  Is the router connected to eth0 or wlan0?  If its a problem when wlan0 is down then it sounds like you have a misconfiguration in the udp output section to send data out wlan0.  If its a problem with eth0 is connected and that disconnection is planned, then you should schedule your playlist to stop playing to avoid this problem.
