### ISSUE TITLE
New 7.1 Image PiHat and LED Panels 

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1569]
During a new image install of 7.1 on a Pi3b.
In the Initial setup I configured everything and selected Installed Cape/Hat as PiHat.
I finished the configuration, expanded the storage and rebooted.
When the Pi rebooted I went to Channel Outputs and found the LED Panels Button was Missing.

Is this normal? As I had to do another image install and leave out the PiHat from the Installed Cape/Hat.
I ask because even if I was to have a PiHat on the Pi3b for some pixels, I would assume I should also be able to setup a matrix using the LED Panels button thru eth1.
![PiHat 01](https://github.com/FalconChristmas/fpp/assets/461610/70e76ede-030c-4e89-85d2-a0fff9b6796a)

**Comment by bobreese** [comment]
Yes, it does remain if you do Not configure it during the Initial Setup configuration.
What I am asking is if you Do configure the Hat during the initial configuration, should the LED Button remain or go away?
This could confuse others as it did for me and force another fresh install to fix it.

**Comment by darylc** [comment]
I believe it will go away unless the vendor of the hat you used allows it to remain.

**Comment by cpinkham** [comment]
I just pushed a fix to allow configuring the ColorLight if a non-LED-panel cape is installed and the UI is set to Advanced mode.  We allow E1.31/DDP outputs to be configured in Advanced mode even if a pixel cape is installed, so it makes sense to allow ColorLight cards to be configured in the same situation.
