### ISSUE TITLE
re: Fix #1567

### ISSUE THREAD

**Issue by mc-sketchy** [FalconChristmas/fpp#1570]
I edited the sequence.php file on my current FPP to mirror the changes in the Fix for 1567; the errors are gone, but /api/sequence/:SequenceName/start/:startSecond does not start a sequence. I receive the correct response from the call:
{"status":"OK","SequenceName":"1_Mephistos_Lullaby_(Xtortion_Audio).fseq","startSecond":"100"}

[FPP_Logs_20230902.1701.zip](https://github.com/FalconChristmas/fpp/files/12504426/FPP_Logs_20230902.1701.zip)

**Comment by mc-sketchy** [comment]
ok daryl.  apologies for the delay, there was a death in my family.  I'll work on it tomorrow

**Comment by ghormann** [comment]
Closing due to lack of response form OP.
