### ISSUE TITLE
LED Panel Height Larger than 16 doesn't work

### ISSUE THREAD

**Issue by bluecreeklightguy** [FalconChristmas/fpp#1571]
**FPP Version and Hardware**:   FPP 7.1 running on Pi4B 8gb

**Describe the bug and Steps to reproduce**: 
Attempts to output to a 320w x 640h p5 panel doesn't produce expected output.  Only displays panel rows 1-16.  This is true when attempt is made to run the test pattern on the LED panel setup tab in FPP.  It is true when trying to test from the Display Testing option on the Status menu.  And it is true when creating a sequence file in xlights, uploading to FPP, and running the sequence from the main Status page in FPP.

1. On the Input/Output Setup tab, select Channel Outputs.
2. Access the LED Panels tab
3. Set the connection to ColorLight
4. Create a 5w x 20h panel
5. Select Auto Layout
6. Scroll down and see that for all panels below row 16, the Output settings are blank.
     *  Note that, if you choose Hat/Cap/Cape, the Output settings are blank below row 3.
     *  Also note in the attached photo, you can see that panels 1-5 don't appear to be correct either, as they don't match the include screenshot from xlights that shows the first row of panels should be white.  This is odd, as the test pattern on the LED panel setup tab shows the expected panel outputs, with O1P1 to O1P5 across that row.

**Expected behavior**: 
It is expected that all 17 rows of panels have an available output.

**Additional context**: 
Setup using LEDVision works as expected.  Video attached (LEDVisionTest.zip).

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

Screenshots and photos of panels attached.
[FPP_Logs_20230513.1143.zip](https://github.com/FalconChristmas/fpp/files/12508298/FPP_Logs_20230513.1143.zip)
[LED Panel Heigh Issue Scree
[LEDVisionTest.zip](https://github.com/FalconChristmas/fpp/files/12508369/LEDVisionTest.zip)
ns.zip](https://github.com/FalconChristmas/fpp/files/12508313/LED.Panel.Heigh.Issue.Screens.zip)

**Comment by bluecreeklightguy** [comment]
I've done a little more testing.  When I lay out the panels as a 640w x 320 panel, with 10 panels wide x 10 panels high, it works completely as expected.  However, that doesn't match the way I need to lay out the hardware for my show, so I would still appreciate a bug fix to address this.  Note, also that when I do the 10x10 layout, there are also no issues with the way the .fseq file displays to the panels.  It works as expected as well.

**Comment by darylc** [comment]
Try changing to master branch and updating, I bumped the limit from 16 panels high to 24.

**Comment by bluecreeklightguy** [comment]
Switched over to Master.  Went back into the LED Panel setup tab.  The panel setup information now populates with outputs 17-20.

Now FPPD is crashing.  When I Start FPPD or Restart FPPD, it generates another crash report and remains Stopped.  I've tried a reboot as well as a full power-down and power-up.  FPPD did not restart after either.  And attempting a manual start generates another crash report.  Included are the most recent logs as well as the crash reports generated after switching over to Master.

[FPP_Logs_20230904.1844.zip](https://github.com/FalconChristmas/fpp/files/12516041/FPP_Logs_20230904.1844.zip)
[fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-32-28.zip](https://github.com/FalconChristmas/fpp/files/12516042/fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-32-28.zip)
[fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-35-58.zip](https://github.com/FalconChristmas/fpp/files/12516043/fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-35-58.zip)
[fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-37-33.zip](https://github.com/FalconChristmas/fpp/files/12516044/fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-37-33.zip)
[fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-39-26.zip](https://github.com/FalconChristmas/fpp/files/12516045/fpp-Pi-7.x-master-234-g577a800c-2023-09-04_19-39-26.zip)

**Comment by bluecreeklightguy** [comment]
Further testing reveals that, when I reduce the height to 16 or less, FPPD will stay running.  Any time I select a height of 17 or more, FPPD crashes and can't be restarted.

**Comment by cpinkham** [comment]
There are 2 things involved here, the # of outputs and the # of panels high.  The variable changed in the commit above allowed more than 16 outputs, but that also requires a change in src/channeloutput/PanelMatrix.h to bump MAX_MATRIX_OUTPUTS to 24.  Note that this also assumes you are using multiple colorlight cards to get that number of outputs since no single card that I have seen supports 24 panel outputs.

If you are really just trying to have more than 16 panels stacked on top of each other, then you need to change the "Panel Layout:" height to be more than 16 or switch to using the Advanced layout UI which uses a pixel-based matrix size instead of a panel based size since the Advanced layout supports positioning panels in practically any way you pattern you want.

**Comment by bluecreeklightguy** [comment]
I'm using 4 colorlight cards.  I'm trying to stack 20 panels on top of one another.  I've tried changing it to something larger than 16, which works for the panel layout on the bottom of that page.  But then FPPD fails to keep running.  I haven't tried the Advanced layout UI, so I can try that as well.

**Comment by bluecreeklightguy** [comment]
Tried using the Advanced layout UI.  Same issue.  As soon as I created rows 17 or higher, FPPD won't run.

**Comment by darylc** [comment]
Thanks for the pointer @cpinkham @bluecreeklightguy can you update to the latest master and test again please?

**Comment by bluecreeklightguy** [comment]
Thanks for the update. I’m away on travel for a couple days. Will give it a shot when I get back on Thu.

**Comment by bluecreeklightguy** [comment]
You guys are awesome!  Updated to the latest master (7.x-master-241-g638710e2).  Everything works as expected.  Thanks for the quick fix.
