### ISSUE TITLE
Remap output processor has unintuitive behavior when reversing to source location

### ISSUE THREAD

**Issue by Glitch752** [FalconChristmas/fpp#1572]
### **Is your feature request related to a problem? Please describe.**
The Falcon Player manual describes the reverse option as follows:
> Reverse- This can be useful if you wired a prop in reverse or changed a
> controller connection to the opposite end of a string. The reverse can be by
> channel or by pixel type.

I had a few strands of lights I needed to reverse (which couldn't easily be done in the sequencer); no matter what I tried, reversing caused the pixels to be mirrored. The issue, as it turned out, was the remap output processor reverses the channels into the input.

Here is the related code:
https://github.com/FalconChristmas/fpp/blob/e612ec4cc1eb82ef6a6b3453ea2a46d33b54d06f/src/channeloutput/processors/RemapOutputProcessor.cpp#L91C1-L93C107
```cpp
for (int c = 0; c < count;) {
    channelData[destChannel + c + 0] = channelData[sourceChannel + count - 1 - c - 2];
    channelData[destChannel + c + 1] = channelData[sourceChannel + count - 1 - c - 1];
    channelData[destChannel + c + 2] = channelData[sourceChannel + count - 1 - c - 0];
    c += 3;
}
```

This may be intentional for performance reasons, but it seems like a pretty standard use case to flip a series of pixels to their original location (and, from what I understand, is what the manual suggests it can do).

### **Describe the solution you'd like**
It would be much easier (and save others the frustration I went through) if the channel data was reversed into a temporary location and copied afterward; that way, it wouldn't use the now-reversed data for half of the output and have a mirrored result.

### **Describe alternatives you've considered**
My solution is to reverse to a far-away channel (I used 10,000) and copy back; this works, but it requires twice as many output processors, and this issue is difficult to find.
Another alternative solution is updating the manual to state this is the intended behavior.

Apologies if I'm overlooking something here. Thanks!

**Comment by darylc** [comment]
Feel free to contribute a pull request if you are capable, otherwise I would guess this will just sit in the queue indefinitely due to lack of developers.

**Comment by Glitch752** [comment]
Sure; I'll see what I can do.
