### ISSUE TITLE
Fpp network didn't work when tethering is ON

### ISSUE THREAD

**Issue by trolly98** [FalconChristmas/fpp#1574]
FPP 7.1 running on Raspberry pi4

**Describe the bug and Steps to reproduce**: 
With plugged int the ethernet cable to PC:
With keyboard plugged into pi i setted eth0 ip address, open now the browser on my pc and I went on 
ip address setted before, then:
1. Finsihed first configuration
2. Go to network settings and set static ip for eth0 192.168.4.1
3. Set static ip for wlan0 192.168.5.1
4. Go to Tethering settings and set always enable
5. Reboot pi
6. See the message: [FAILED] Failed to start Dispatcher daemon for systemd-networkd
7. Ethernet and wifi don't work anymore

**Comment by Poporacer** [comment]
You should not typically be setting network configurations from the console, can you explain more about that process and screenshots of what you mean by "With keyboard plugged into pi i setted eth0 ip address" I believe that is causing the problem.

**Comment by Poporacer** [comment]
But configuring the network settings via the SSH is likely what is causing your problem. Please explain how you were doing that.
You probably couldn't connect via eth0 because you were connecting the Pi directly to your computer? You computer probably does not have a DHCP server and the Pi is expecting to get the eth0 IP address from a DHCP server (typical networking method)

**Comment by trolly98** [comment]
Ok, I thought IP address was static. My fault!
With keyboard and a display I logged into system and I lanched "ipconfig eth0 192.168.8.1" to set a static eth0 ip address, and then I opened UI from browser

**Comment by Poporacer** [comment]
By default, FPP has the eth0 set to DHCP like most network devices and I don't think using ipconfig that way will actually work correctly. Using the keyboard and display is typically only for SUPER ADVANCED users that understand the underlying code structure. All the documentation refrains from even attaching a keyboard with FPP!

**Comment by Poporacer** [comment]
We are talking about network configuration, and you can SSH from within the GUI
