### ISSUE TITLE
Playlist not Randomized when started by Command Preset

### ISSUE THREAD

**Issue by petegallagher** [FalconChristmas/fpp#1585]
**FPP Version and Hardware**: 7.1 RPi3

**Steps to reproduce**: 
I want a playlist to start on boot in a random order, however it appears that a playlist started via a Command Preset does not get randomized.

1. Create a Playlist which is configured to **Randomize Every Iteration**
    <img width="457" alt="Screenshot 2023-09-29 at 16 13 09" src="https://github.com/FalconChristmas/fpp/assets/688331/f0cd275f-4b48-4d5e-a2a8-10668e80438b">

2. Create a **Command Preset** to **Start Playlist** when **FPPD_STARTED**
    <img width="806" alt="Screenshot 2023-09-29 at 16 13 29" src="https://github.com/FalconChristmas/fpp/assets/688331/40189919-fd82-47ad-9aee-a4add47feecc">

3. Click **Run Now** (or click **Restart FPPD**)
4. Playlist starts in the default order each time (but does randomize on the next iteration).

**Expected behavior**: 
The playlist should start on boot in a random order.

**Comment by Poporacer** [comment]
I believe that is the intended design. When it starts the playlist, it loads it and will play the first entry, then it "iterates" and becomes random. Try the FPP Command of Start Playlist at Random Item instead of Start Playlist and let us know if that works as intended.
