### ISSUE TITLE
FPPD crashing continously on master branch v7.x-master-265-gba86815c (master branch)

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1588]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
v7.x-master-265-gba86815c (master branch
on rpi4
[fpp-Pi-7.x-master-265-gba86815c-2023-10-02_11-09-57.zip](https://github.com/FalconChristmas/fpp/files/12781761/fpp-Pi-7.x-master-265-gba86815c-2023-10-02_11-09-57.zip)

**Describe the bug and Steps to reproduce**: 
FPPD not running any sequences - just sitting idle is crashing and restarting fppd every few minutes

Example crash Log file attached
[fpp-Pi-7.x-master-265-gba86815c-2023-10-02_11-09-57.zip](https://github.com/FalconChristmas/fpp/files/12781761/fpp-Pi-7.x-master-265-gba86815c-2023-10-02_11-09-57.zip)

**Comment by dkulp** [comment]
It's crashing trying to read the state of GPIO pins.   I'd start with disabling all the GPIO inputs and see if that helps.   Also, check the syslog and dmsg output to see if there are any i2c issues or similar.
