### ISSUE TITLE
7.2 BBB Fresh install Kulp 128D  FPPD restart crash loop and WIFI adaptor not found

### ISSUE THREAD

**Issue by Timmyloowho** [FalconChristmas/fpp#1593]
**FPP Version and Hardware**: 
7.2 Fresh Install, BBB on Kulp128D

When 7.2 initial setup is complete,  first FPPD restart causes a crash.  FPPD never comes back up, just keeps crashing.

Kulp USB WIFI adaptor is not found.  If it is pulled and re-inserted in the USB slot, FPPD crashes and reboots.  Still not found after boot.

**Expected behavior**: 
Previous version of 6.3 worked fine, no issues with FPPD loop or WIFI.

**Additional Attachments**

[fpp-BBB-7.2-2023-10-05_12-44-28.zip](https://github.com/FalconChristmas/fpp/files/12835334/fpp-BBB-7.2-2023-10-05_12-44-28.zip)

**Comment by dkulp** [comment]
I'm not able to reproduce this at all.    With  new K128, beagle, new SD card with 7.2, I can boot it up, it see's the WLAN adapter, I can get things configured.   I can reboot it.  I can restart FPPD 15 times in a row making adjustments to the various string configs in between, etc...   As far as I can tell, everything in FPP is working properly.     I even tried using the config files (other than IP addresses and such) from your zip file and everything is working. 

I have no idea what to suggest as everything is working.   Maybe a power issue?   Are you sure your power supply is providing enough clean 5V power?  Likely 4amps?

**Comment by Timmyloowho** [comment]
Interesting.  Is there anything in the crash file that shows I am doing
something wrong?  Yes clean 5 volt power from a meanwell attached to the
128, which feeds the beagle. (no power hooked direct to the beagle)

I tried a Beagle Bone Black, and my spare industrial red.  (I have more
coming to try)

I am curious why I do not have this issue with 6.3 at all.

**Comment by Timmyloowho** [comment]
Dan,

I found it.  I was able to get 7.2 re-fresh installed without issues and
started playing with it.  I had no issues (except for the wifi not
working)  Voltage is constant at 5.04.  I then configured some outputs and
again, all was fine.  Then, I placed the FPP instance in Remote Mode and it
wanted to restart FPPD.  Restarted FPPD and was instantly greeted with the
spinning windows wheel.  It refreshed after 5 or 6 seconds but FPPD was
still stopped and did not start with 1 crash report.  Each time I tried to
restart FPPD another crash and report.

I switched it back to player mode, and then rebooted.  Once it came back
up, FPPD would restart as normal, no issues.

Please let me know if this repeats on your end.  I am getting new BBB's
tomorrow and will try swapping it out for effect.

Gary Clark

**Comment by Timmyloowho** [comment]
Correction.  I  can repeat the process on demand.  Once the switch to remote mode happens, restart FPPD and all is fine.  Then, go  to the 128d output page and just save it.  This will prompt the FPPD restart, which will hang and crash.

**Comment by dkulp** [comment]
Can you flip to master branch and test?  (reboot after flipping to master)  I made a change to how the PRU's data ram is initialized that I HOPE will fix this.

**Comment by Timmyloowho** [comment]
Yes, confirmed!  Issue is gone and FPPD restarts normally now.

My issue with the WIFI is also resolved.  I was using your high gain
adaptor and FPP does not see it at all.  I switched to a low gain one and
it immediately picked it up.

Is there a better high gain that will work with these?  ( I am now powering
the BBB with the barrel, no power issues)

**Comment by dkulp** [comment]
Fixed pushed to v7.2 branch as well.
