### ISSUE TITLE
Upgraded to FPP v7.2 and now FPPD will not start

### ISSUE THREAD

**Issue by northerntaco** [FalconChristmas/fpp#1594]
# Please answer the following:
**FPP Version and Hardware**: FPP v7.2 running on K8-pb

**Describe the bug and Steps to reproduce**: 
I just updated my k8-pb to FPP v7.2, I did the FPP upgrade and the OS upgrade from the about us page. I was on version 6.x previously I think it was 6.3.  

- Now the FPPD wont start. On the Pixel Overlay Model screen I get a pop-up, saying load failed, is FPPD running? 
- I also get a red pop up on the channel Outputs screen now saying: "Error: Unable to retrieve GPIO pin info.

- I tried pressing the start FPPD button. I get a green pop-up that says completed, but FPPD does not start. 
- I pressed restart FPPD. It completes the restart, and the shows FPPD is idle for a moment, then it shows it switches to FPPD stopped to idle and back and forth in the top bar. 
- If I navigate to the pixel overlay model I get the message saying load failed and the start FPPD button doesn't fully load. the white outline is there but the text is missing.

**Expected behavior**: 
I expected FPPD to run, and my pixel overlay models to load.

**Additional Attachments**
[FPP_Logs_20231007.0554.zip](https://github.com/FalconChristmas/fpp/files/12836928/FPP_Logs_20231007.0554.zip)
![gpio pin error](https://github.com/FalconChristmas/fpp/assets/56813846/97fd8a4e-5990-458b-b7d6-56cff82bb5a5)
![pixel overlay screen](https://github.com/FalconChristmas/fpp/assets/56813846/0c5299ce-0355-49d6-9792-5e8895fa2275)

**Comment by dkulp** [comment]
The overlay models are fine.  The problem is the command presets.   The new version of WLED is not compatible with the older WLED command presets as the parameters have completely changed.    You will need to delete/recreate the command presets you have that are triggering WLED effects.

**Comment by northerntaco** [comment]
Ok, thanks.  I deleted the presets and I can now rebuild them.
