### ISSUE TITLE
Effect Command with Model Start Channel Off

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1596]
# Please answer the following:
Example: FPP 7.2 across multiple controllers.  Model is connected to a K40D

**Describe the bug and Steps to reproduce**: 
I have a model that is connected to a K40D with a start channel of 488533 as indicated in the screenshot below.

<img width="797" alt="image" src="https://github.com/FalconChristmas/fpp/assets/3765696/713fde96-8cb3-44be-98a7-532ab41b1d40">

I'm using the auto generated pixel overlay models which is generated correctly as indicated below.

<img width="765" alt="image" src="https://github.com/FalconChristmas/fpp/assets/3765696/11f8b63d-5a90-4f05-a61e-d267c4148900">

When I run a the effect start command and manually specify the start channel of 488533 the teddy displays as expected (brown outline).

<img width="813" alt="image" src="https://github.com/FalconChristmas/fpp/assets/3765696/43f4f103-4ddd-499a-abe1-f9f1b6e4bbf9">

If I change the start channel to reference the overlay model "Teddy" then the start channel is off and the outline is purple.

<img width="881" alt="image" src="https://github.com/FalconChristmas/fpp/assets/3765696/00653e3b-66ed-404d-ba5d-2268b55bdc14">

**Comment by dartunder** [comment]
Specify 1 as the start channel if you assign a model.
