### ISSUE TITLE
FPP 7.x Will Not Connect to Internet via wlan0

### ISSUE THREAD

**Issue by charbaugh1** [FalconChristmas/fpp#1597]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.2 on Pi4B

**Describe the bug and Steps to reproduce**: 
7.x will not connect to the internet when using eth0 for show network and wlan0 for internet communications.
FPP fails the internet item in System Health Check.
Unable to browse to FPP using the IP address of the wlan0 connection or the name of the FPP from computers on the wifi network.  Only able to browse to FPP from hardwired connection on the show network (eth0)
Problem did not exist in 5.5 (the previous version I was running.

**Expected behavior**: 
Expectation is to use the wireless interface for internet connection for managing plugins, updates, etc.

**Additional context**: 

Problem started when I updated from 5.3 to 5.5 to 7.2.
Network communication from eth0 to control panels (F16v4) and FPP Connect working fine.
wlan0 connects to the wireless network fine.  I am able to see it from within my router UI.

Network Configuration:
- eth0 is set to static with 192.168.5.31
- wlan0 is set to DHCP
- DNS is set to DHCP

Troubleshooting steps:
1. Performed a clean image on a brand new SD card at 7.2 to test if upgrade had corrupted somehow.  Problem persisted.
2. Performed a clean image of 7.0 to test if it was localized to 7.2.  Problem persisted.
3. Performed a clean image of 5.5 to confirm nothing had failed on the hardware.  No network or internet problems occurred.  Everything works fine.
4. On 7.x images, tried programming static DNS of 8.8.8.8 and 1.1.1.1.  Problem persisted.
5. While programming static DNS, I attempted to ping the DNS.  The message received was that it was unreachable.  The message was received back from 192.168.5.31, indicating FPP was using eth0 to try and communicate to the internet instead of wlan0.
6. Connected a USB wifi adapter and connected to wireless network to test if it was something with the internal wifi chip.  Problem persisted.
7. Went back and forth between the 5.5 image and 7.2 image to make sure all settings were exactly the same.  No differences found, but problem persists.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
8. Open the the File Manager (Content Setup->File Manager), 
9. Select the "Logs" tab
10. Click "zip" button.
11. Attach to this ticket.

[FPP_Logs_20230513.1108.zip](https://github.com/FalconChristmas/fpp/files/12841981/FPP_Logs_20230513.1108.zip)

**Comment by charbaugh1** [comment]
7.x does not support different gateways on eth0 and wlan0

**Comment by dartunder** [comment]
This issue should be apparent when running a health check, yes?
