### ISSUE TITLE
FPP 7.2 continues sending data after all sequences and effects are stopped

### ISSUE THREAD

**Issue by rudybrian** [FalconChristmas/fpp#1600]
**FPP Version and Hardware**: 
FPP v7.2-1-g1ca81bce on Pi 2B

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. In FPP settings for Input/Output: _Automatically turn on/off outputs_ = checked and _Always transmit channel data_ = unchecked
2. Play _Halloween-2023-preshow_ playlist (manually or via schedule)
3. After playlist has completed (which stops all sequences, effects and overlays), observe that E1.31 is still being sent to all universes of the second configured E1.31 Channel Output definition (192.168.3.10) and Colorlight protocol to an LED panel (Colorlight 5A-75B) connected to a second NIC.
4. Running _All Lights Off_ and _Clear All Overlays_ for all models have no effect.
5. FPPD must be restarted to stop sending E1.31 and Colorlight network traffic.

**Expected behavior**: 
FPPD should respect the _Automatically turn on/off outputs_ setting and stop sending network traffic after all sequences/overlays/effects are stopped.

**Additional context**: 
The issue only seems to manifest with the second Channel Output (192.168.3.10) and the LED, but not the first defined E1.31 Channel Output (192.168.1.50). Individual testing with effect start/stop, sequence start/stop, overlay start/stop does not seem to be able to reproduce this.

**Additional Attachments**
Network pcap attached showing E1.31 traffic being sent to the second configured E1.31 Channel Output.
[packetcapture-ix0.1001-20231009092638.zip](https://github.com/FalconChristmas/fpp/files/12858677/packetcapture-ix0.1001-20231009092638.zip)
[FPP_Logs_20231010.1455.zip](https://github.com/FalconChristmas/fpp/files/12858669/FPP_Logs_20231010.1455.zip)
[Halloween-2023-preshow.json](https://github.com/FalconChristmas/fpp/files/12858711/Halloween-2023-preshow.json)
[FPP_all-backup_v7_20231010080240.json](https://github.com/FalconChristmas/fpp/files/12858724/FPP_all-backup_v7_20231010080240.json)

N/A

**Comment by Poporacer** [comment]
Just a FYI
In FPP settings for Input/Output: Automatically turn on/off outputs = checked
**This setting is only for Devices that have e-Fuses.** You mentioned a Pi as your device but no cape. The Pi itself does not have e-Fuses and I don't know of any pi hats that have e-fuses
How are you determining that It is still sending E1.31 traffic and what problem is it causing?
I have a feeling that what you are actually seeing are the Ping requests from the Monitoring settings in the Outputs page?

**Comment by rudybrian** [comment]
> Just a FYI In FPP settings for Input/Output: Automatically turn on/off outputs = checked **This setting is only for Devices that have e-Fuses.** You mentioned a Pi as your device but no cape. The Pi itself does not have e-Fuses and I don't know of any pi hats that have e-fuses 

Understood, the pertinent setting that doesn't seem to be respected is _Always transmit channel data_ = unchecked.

> How are you determining that It is still sending E1.31 traffic and what problem is it causing? 

I monitor the network traffic to and from all my FPP instances via SNMP, and with previous versions of FPP, FPP stops transmitting E1.31 after playback is stopped when _Always transmit channel data_ = unchecked. After initially observing the difference in behavior with FPP 7.1 (and see the same with 7.2), I captured the traffic being sent from enxb827ebc7c7d5 (persistent name for eth0) being sent after the show had shut down for the day (see [packetcapture-ix0.1001-20231009092638.zip](https://github.com/FalconChristmas/fpp/files/12858677/packetcapture-ix0.1001-20231009092638.zip) referenced in the initial post) I don't have a capture from enxc056278fcbc7 (persistent name for eth1 connected to the Colorlight receiver card), but saw the same behavior in my NMS for this interface. See the following image for reference. Notes: All sequences and effects shut down 30 minutes after sunrise ~07:41, and the transmit traffic drops when I manually restarted fppd ~09:35. Please ignore the rest of the time shown in the graph as I was doing testing)
![FPP-interface-traffic](https://github.com/FalconChristmas/fpp/assets/6729532/0573d394-4310-461f-bad3-3460c72b4ef6)

> I have a feeling that what you are actually seeing are the Ping requests from the Monitoring settings in the Outputs page?

Nope, it's definitely E1.31 traffic being sent out enxb827ebc7c7d5 (have a look at the pcap with Wireshark with the ACN protocol enabled (Analyze->Enabled Protocols->ACN->ACN over UDP) and with the 'Streaming DMX' enabled under Preferences->Protocols->ACN). For whatever reason FPPD is only sending traffic to all of the defined universes (101-116) for 192.168.3.10 (the second E1.31 output defined in Channel Outputs) on this interface, but isn't sending traffic to the first defined output (192.168.1.50 universes 1-23)

It may simply be a benign bug as it doesn't appear to impact anything other than sending network traffic and inducing a larger load on the Pi's CPU compared with when FPPD first starts up and isn't sending anything.

**Comment by rudybrian** [comment]
An interesting observation: I restarted fppd after midnight this morning to apply a few updates after my main show stopped for the night. After restarting fppd, it picked up and started playing my _Halloween-landscape-afterhours_ playlist as expected (I run an after-hours playlist to keep the landscape lighting on from 23:45-sunrise+30).

Interestingly enough, this morning at sunrise+30 (~07:42) the schedule stopped the playlist as expected, but fppd also stopped sending E1.31 and Colorlight traffic out the NICs which is what I would expect it would do with _Always transmit channel data_ = unchecked. This suggests that either my main _Halloween-2023-preshow_ playlist has something in it that induces this state, or that by having a scheduled playback time that crosses midnight may be the cause. I will continue testing and report back.

**Comment by rudybrian** [comment]
A bit more testing, and it looks like this is related to one or more overlay models still being active. If I force all overlay model states to disabled, this stops the output.

I will keep digging as to which models are being left enabled and how this might be happening.

**Comment by rudybrian** [comment]
Some additional findings since yesterday suggest that the symptoms are not actually caused a bug, but by nuances in a recent script change. I also discovered some differences with how WLED overlay effects are being handled that make it harder to stop them compared with other effects.

The PixelOverlay-ScrollingText.php script [was modified ~5 months ago](https://github.com/FalconChristmas/fpp-scripts/commit/e3935d2c0447c2497818be50c4fcdb38d7ca08b9) in a way that I hadn't paid close enough attention to. Mainly that it only sent the text to scroll, but no longer cleared and disabled the overlay model afterwards. This left the overlay model in an enabled state which required that model mode set to off so that fppd does not keep sending data to defined outputs. 

The second observation is that if using commands to enable WLED overlay effects, there does not appear to be a functional equivalent command to stop the WLED effect. You can disable the overlay model mode which will stop the output, but the WLED effect will keep running (which consumes system resources). The only way I have found to stop the WLED effects is via the REST API's _Overlay Model Effect_ command, but would be interested to learn if there is another way to do this.

**Comment by rudybrian** [comment]
I hacked up PixelOverlay-ScrollingText.php to POST the Stop Effects command  to the REST API for the Spiderx models that had the WLED effect running on them and it seems to be working for me. Closing this issue as NAB.

```
#!/usr/bin/php
<?php
    #############################################################################
    # Setup some variables (this is the part you want to edit for host and models.)
    $host  = "localhost";    # Host/ip of the FPP instance with the overlays
    $models = "Spider1,Spider2,Spider3,Spider4,Spider5,Spider6,Spider7,Spider8,Spider9,Spider10,Spider11,Spider12,Spider13,Spider14,Spider15,Spider16,Spider17,Spider18,Spider19,Spider20";     # Overlay models to stop

    #############################################################################
    # Function to post the data to the REST API
    function do_post($url, $data) {
        //Initiate cURL.
        $ch = curl_init($url);
        //Tell cURL that we want to send a PUT request.
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');

        //Attach our encoded JSON string to the POST fields.
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);

        //Set the content type to application/json
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        //Execute the request
        $result = curl_exec($ch);

        return $result;
    }

    #############################################################################
    # setup a signal handler to clear the screen if ctrl-c is used to
    # stop the script
    $running = true;
    declare(ticks=1); // PHP internal, make signal handling work
    function signalHandler($signo)  {
        global $running;
        $running = false;

    }
    pcntl_signal(SIGINT, 'signalHandler');

    #############################################################################
    # Main part of program

    $data = array('command' => 'Overlay Model Effect',
                  'multisyncCommand' => false,
                  'args' => array($models, 'Enabled', 'Stop Effects'));
    #echo json_encode($data);
    do_post("http://$host/api/command",
        json_encode($data));

    exit(0);
    #############################################################################
?>
```
