### ISSUE TITLE
Using DHCP for device on show network, adds and then removes from proxy UI 

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1601]
V7.2 Enable DHCP, reconnect the host to get a DHCP address. It adds this address to the proxy setting UI in a section at the bottom. *NOTE/BUG* You must go to this page and SAVE or the proxy is not usable from the url.

![image](https://github.com/FalconChristmas/fpp/assets/4643499/7e5120d4-2ef0-4a31-8dbd-dd5f6b6efa77)
![image](https://github.com/FalconChristmas/fpp/assets/4643499/82531dd9-70ab-499e-8d90-8e0d2a776874)

The proxied host is accessible - all good.
http://192.168.0.199/proxy/fppkurt.local/proxies.php

Now mark the DHCP ip as ENABLED and restart network.
![image](https://github.com/FalconChristmas/fpp/assets/4643499/8121858c-d49a-468d-8ee8-85f0ce0ace1a)
Update and restart

The proxied host is *no longer visible* in the proxy settings UI page *but* it is still valid as you can still hit the proxied host on the browser.
![image](https://github.com/FalconChristmas/fpp/assets/4643499/1ac61410-604c-4c5f-8972-9eeda71e4ff7)

I think it is just a UI issue in that it is not being shown anymore on the proxy settings table.

**Comment by derwin12** [comment]
I think I found my issue - if I click the Checkbox to enable the static IP, I update interface AND hit reset network. That caused the setting to be removed. Can others confirm?
![image](https://github.com/FalconChristmas/fpp/assets/4643499/70bdfb57-ed45-4908-a80a-0b144d163a47)
I should not have hit the restart network?

**Comment by darylc** [comment]
I'm told this issue still exists

**Comment by darylc** [comment]
Ron Armstrong demonstrated the issue.  The issue seems to be that when you press restart network, fpp restarts the dhcp server (systemd network) which then forgets about the IP until the client renews the DHCP lease at which time it reappears in the proxy page.

**Comment by bloojoop** [comment]
also when enabling dhcp or adding a manual proxy entry, it creates wild card rewrite rule so even if the IP is not diplayed in the table, the proxy will still work.  As soon as a dhcp client renew's it's IP it will show in the DHCP Hosts table again.

**Comment by darylc** [comment]
@bloojoop do you think its worth doing anything here or just closing this if the proxy actually works?

**Comment by bloojoop** [comment]
Well, I ultimately defer to the original requestor.  I will say there is a
warning message in xlights if you try to upload and the configured
controller ip address is not in the proxy table.  It seems to still work,
just a warning that the controller is not listed in the proxy table so it
would give a user the impression that something is not configured
correctly.

**Comment by darylc** [comment]
Speaking to Ron today, yes there is a small edge case hard to fix visibility issue in fpp, but the real reason this issue was created was due to misleading warnings in xlights.  Going to close this out.  If anything an issue in xlights should be created for reporting failure when there was indeed an upload success.
