### ISSUE TITLE
Allow the video media to match the sequence name (not just the audio)

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1602]
Is there a technical reason that the video needs to match the audio on a projector fpp setup? Can it be changed/enhanced to match either the audo or the fseq file? Would eliminate the questions and confusions and critical step that is missed using this feature.

**Comment by darylc** [comment]
@derwin12 I feel this will cause unintended consequences and make it more confusing eg if people upload both the audio and video and video is named after the sequence it would never be played etc.
