### ISSUE TITLE
Expand Storage of a new Install -- make it obvious to Expand the storage

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1604]
Right now the correct (ie 99% of the time) option is to click the little black "expand storage" link where as the LEAVE UNUSED is a big green button. This is leaving many folks with an unexpanded SD card. Can this UI be tweaked/reversed or something to avoid this common mistake.

**Comment by darylc** [comment]
Dan has made it impossible to make the warning of the need to expand storage go away if you haven't expanded. https://github.com/FalconChristmas/fpp/commit/0d6a8840416055dc14b08eae84251d3cb548f601
