### ISSUE TITLE
Multisync Page Crash Report Link for Remote is not Absolute

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1609]
**FPP Version and Hardware**: 
Example: 7.2-2-ge35c0df7 on Pi4

**Describe the bug and Steps to reproduce**: 
I have a remote Pi that has 1 crash report.  The player correctly indicates that the crash report exists.  When I click on the crash report it goes back to the same device instead of the remote where the crash report actually exists.  This seems to be because the URL is reletave instead of absolute.

**Expected behavior**: 
Clicking on the link should take me to the IP of the remote.

**Additional context**: 
Here is a a screenshot showing the issue where the remote IP is 192.168.86.180 but the link to the crash report is going to 192.168.86.59 (self).  Not displayed on the screenshot is the location of the cursor which is directly above the crash report hyperlink.

![image](https://github.com/FalconChristmas/fpp/assets/3765696/ea36de4f-bff0-420c-8667-2ef5759cf2d6)

**Comment by darylc** [comment]
Care to send a PR @MrPaulAR?

**Comment by MrPaulAR** [comment]
Tried to figure out where the php was for this but couldn't find it.

If you want to spend time with me in zoom getting my IDE setup I'll be
happy to look at the php.

**Comment by dartunder** [comment]
Couple hints.

Either fixed when the message is created, or in SystemGetStatus, or in multisync.php

fpp/www/api/controllers/system.php : function SystemGetStatus()
or 
fpp/www/mutlisync.php : around line 450 is where it's read then...
I think this is where it's set  $('#' + rowID + '_status').html(status);

**Comment by darylc** [comment]
Hey Paul - you might find this video useful - https://www.youtube.com/watch?v=h2MhkFKUOow thats how I learned how to setup the IDE

**Comment by MrPaulAR** [comment]
See comments in pull request.  In short, don't change the API output.  Issue is that the URL should resolve to proxied endpoints too.
