### ISSUE TITLE
Add option for "all-off" after playing each sequence

### ISSUE THREAD

**Issue by forkineye** [FalconChristmas/fpp#161]
Enhancement / Feature Request:
An option for "all-off" after playing each sequence within a playlist would be nice.  I guess there would be a need to configure which channels this applies to in order to not mess up elements which are triggered to stay on the length of show (like tune in signs, static elements, etc...).  Or maybe auto-magically exclude those?

**Comment by cpinkham** [comment]
This is complicated a little by events and will get more complex with some of the enhancements planned for the player and the ability to play multiple sequences at one, so this won't make it in this year but I'm leaving it open so we can try to get it in for v2.0 next year.

**Comment by cpinkham** [comment]
blankBetweenSequences setting was added a while back, closing issue.
