### ISSUE TITLE
Extract Audio Button

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1614]
**Describe the solution you'd like**
A button on the Videos tab labeled "Extract Audio".  This button is very similar to the mp3gain button but instead it will extract the audio from the video and place it in the Audio folder.

The appropriate tool, ffmpeg, is already built into FPP so no other utilities need to be installed.  The syntax for ffmpeg to do this is below.

`ffmpeg -i INPUT_FILE OUTPUT_FILE.mp3` 

The above is reasonable defaults but the audio will always be re-encoded.  The various Pi & BBB based boards can handle this task without issue.

Possible enhancements to the above could be below but it's really not needed
* Logic to detect if the source codec is already mp3 and if so put `-c copy` between the INPUT_FILE and OUTPUT_FILE and nothing will be re-encoded and only file io is used.
  * Another option is to try to do the `-c copy` option first and check the exit code of ffmpeg.  If it fails then run the convert method.
* Option to run mp3gain after extraction

Note, I already tried to write the feature myself but did not have success.  I modified upload.php in /opt/fpp/www duplicating the mp3gain stuff in the Videos section, duplicating the function and duplicated run_mp3gain.php.    After adding this section none of the files would show up in the File Manager

``` php
<? if (file_exists("/bin/ffmpeg") || file_exists("/usr/bin/ffmpeg") || file_exists("/opt/homebrew/bin/ffmpeg") || file_exists("/usr/local/bin/ffmpeg")) { ?>
    <input onclick="ButtonHandler('Videos', 'extractAudio');" id="btnExtractAudio" class="disableButtons singleVideosButton multiVideosButton" type="button"  value="Extract Audio" />
<? } ?>
```

**Comment by darylc** [comment]
I wonder if this would do more harm than good?  Eg if you had the video file, then pressed this button, you'd also end up with the audio file and and then fpp has to guess which one you want to play?

**Comment by MrPaulAR** [comment]
I agree that this can cause some confusion.  I think there are options

- Don't implement this
- Add logic that will delete the source file upon successful return code.  This will need to be displayed on the screen and fully automatic. 

Regarding the 2nd option above,  I'm not a fan of keeping both files as clicking the button and accepting the pop-up implies that they don't want the video file.  If they do want it then they can upload it again with ffp connect or manual and then go delete the audio file.

**Comment by dartunder** [comment]
IMO: These types of changes ( conversion and maybe mp3gain ) need to get processed/updated in xLights or the files will just get overwritten on the next FPP connect.

If we are using this as a tool just to do the conversion then just have the resulting file download to the PC for the user to decide how to implement the new file as the sequences need to be updated to point to the mp3 for this to really work correctly.
potentially append _AUDIO_ONLY or something to the file name.
