### ISSUE TITLE
FPPD 7.2 crashing in BBBPru constructor

### ISSUE THREAD

**Issue by jkriegshauser** [FalconChristmas/fpp#1615]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.2 running on a K16B 

**Describe the bug and Steps to reproduce**: 
1. Upload from XLights
2. Occasionally experience FPPD crash

**Expected behavior**: 
No crash

**Additional context**: 
N/A

Crash report from logs:
```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6660ee4 in __GI___wait4 (pid=13208, stat_loc=0xbebd6978, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#2  0x004f883e in handleCrash(int) ()
#3  <signal handler called>
#4  memset () at ../sysdeps/arm/memset.S:46
#5  0xb69ebd7e in BBBPru::BBBPru(int, bool, bool) () from /opt/fpp/src/libfpp.so
#6  0xad5f1c0e in BBB48StringOutput::StartPRU(bool) () from /opt/fpp/src/libfpp-co-BBB48String.so
#7  0xad5f5ce6 in BBB48StringOutput::Init(Json::Value) () from /opt/fpp/src/libfpp-co-BBB48String.so
#8  0xb69f0792 in InitializeChannelOutputs() () from /opt/fpp/src/libfpp.so
#9  0x004f577c in main ()
```

[FPP Tree Crash Log fpp-BBB-7.2-2023-10-19_18-11-44.zip](https://github.com/FalconChristmas/fpp/files/13059276/FPP.Tree.Crash.Log.fpp-BBB-7.2-2023-10-19_18-11-44.zip)

**Comment by dkulp** [comment]
Can you update to the latest on the 7.2 branch?   You WILL need to reboot afterword to unlock the PRU memory.  There was a fix put in place for this.

**Comment by jkriegshauser** [comment]
Will try it after the show tonight. Curious about the change though, can you link the PR that fixed it?

**Comment by dkulp** [comment]
It would be https://github.com/FalconChristmas/fpp/commit/1ca81bceb4d90a2af5822a1bb21637d630e152f1

**Comment by jkriegshauser** [comment]
Thanks, that seemed to fix our crashing problem!
