### ISSUE TITLE
Schedules using even/odd days not displaying in preview past 30 days into the future

### ISSUE THREAD

**Issue by aggie81** [FalconChristmas/fpp#1616]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.3.2 and 7.2.2 running on RPi 3B+

**Describe the bug and Steps to reproduce**: 
1. In advanced system settings, set Scheduler max timeframe to schedule out to 3 months
2. Create a test schedule with Start Date = today's date, End date to defualt 2028-12-31, Days to Even or Odd
3. Start time 3pm to stop 4pm, some test playlist, loop immediately (these don't seem to matter)
4. Save the new schedule, reload schedules then open the preview.
5. Even/odd day schedules stop showing in the preview past about 30 days or so into the future from the current date.

**Expected behavior**: 
Preview should show even/odd day schedules out to Jan 2024 because of the 3 month scheduler max timeframe set.

**Additional context**: 
All other days settings in the scheduler seem to work OK and the preview correctly shows them scheduled out to Jan 2024. I do not know if this is just a previewer issue or they really are not scheduled properly, I first found this on FPP 6.3.2 then tried 7.2.2 to see if it still exists. Had no issues with even/odd scheduling last year using FPP 5.5.

If I try a future state date for the odd/even schedule, like Nov. 23, 2023 (Thanksgiving eveniing) then nothing shows up in the preview and it says nothing is scheduled.

**Additional Attachments**
7.2.2 logs attached.

Screen shots attached.
[FPP_Logs_20231022.0022.zip](https://github.com/FalconChristmas/fpp/files/13062115/FPP_Logs_20231022.0022.zip)
![Everyday Preview correct](https://github.com/FalconChristmas/fpp/assets/9982279/acb3945a-e2d3-4e46-b775-c853721ac291)
![Everyday Schedule](https://github.com/FalconChristmas/fpp/assets/9982279/aca4d1bb-4d97-46d0-b5ff-b2cc62b91249)
![Odd Preview](https://github.com/FalconChristmas/fpp/assets/9982279/92bf8038-4c25-4e7a-a36a-68d779c31d86)
![Odd Schedule](https://github.com/FalconChristmas/fpp/assets/9982279/1a1fb59e-ab2b-4bd0-a1d7-0f9f3c60a438)
![Even Preview](https://github.com/FalconChristmas/fpp/assets/9982279/8c63f88e-0733-484f-a253-07f80dbbf6c8)
![Even Schedule](https://github.com/FalconChristmas/fpp/assets/9982279/31b89b85-684f-47cb-bdfd-9e32cc1ba5d4)
![Advanced Settings](https://github.com/FalconChristmas/fpp/assets/9982279/8a2ff358-9dfd-42ed-8494-4f670d4265a5)
![2023-09-23 (8)](https://github.com/FalconChristmas/fpp/assets/9982279/2b9baf39-18f5-4230-8ede-c773bcac134c)
![Future Start Error](https://github.com/FalconChristmas/fpp/assets/9982279/49353358-5717-432d-82f1-cbea8e66e457)

**Comment by aggie81** [comment]
Some additional info: I did a test first with two schedules, Even days starting today running Playlist_A from 6pm to 8pm, Odd days starting today running Playlist_B from 6pm to 8pm. I see Playlist A & B alternating everyday as expected, but both stop on Nov18 (even) and Nov 19 (odd) in the preview. Same as I got yesterday. Then I added a third schedule starting today set to everyday running Playlist_C from 5pm to 6pm. The preview does expand to the full 3 months, but looking carefully, Playlist A & B still stop on Nov 18/19. Playlist_C continues on by itself for the rest of the preview out to 3 months. I have not found a combination yet where odd/even schedules run past Nov 19. At least not shown in the preview.

**Comment by aggie81** [comment]
After watching this for a few days, it seems to be just a preview issue. Even/odd schedules stop showing in preview after 30 days or so into the future from the current date. While all other schedule types display for the full max schedule time set in advanced settings.

**Comment by cpinkham** [comment]
This was just a preview issue, the preview for Odd/Even was previously fixed at 35 days.  I think that limit existed before we bumped up the preview to allow looking out longer distances into the future in another part of the code.  It is fixed in the master branch now.

**Comment by aggie81** [comment]
Sweet, thanks!
