### ISSUE TITLE
Playing MP4 Videos on a Raspberry Pi Zero 2 Crashes FPP after a few minutes, requires hard reboot to start again.

### ISSUE THREAD

**Issue by theadster** [FalconChristmas/fpp#1617]
**FPP Version and Hardware**:  FPP 7.2 running on a Raspberry Pi Zero 2 with a USB Sound Card

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Fresh install of FPP 7.2 on a Raspberry Pi Zero 2
2. Upload several MP4 Video Files. In this case I was using files from AtmosFX designed for pumpkin projection. (Jack-o-Lantern Jamboree)
3. Create a playlist of several different MP4 files.
4. Manually start the playlist with the 'Repeat' option selected.
5. After a few minutes of repeating files, the audio cuts out but the video continues to play.
6. The video ends on the last frame of the video.
7. Logging in to FPP shows that FPPD has crashed. Clicking Start FPPD or Restart FPPD  does not work in this case and the only way to start FPPD again is to reboot from the web interface or a hard reboot by cutting power.

**Expected behavior**: 
The playlist will continue to cycle through the MP4 files without issue.

**Additional context**: 
Attached are log files that were written during the crash. The audio cut out at around timing 19:13:35 in the log file. Date: 10-20-2023. This was confirmed by using 2 separate Raspberry Pi Zero 2's with the same result. This is with a brand new fresh install of FPP 7.2 on a new SD Card.

**Additional Attachments**
Attached is a full log in 'Excessive' mode while completing the steps above.

[FPP_Logs_20231020.2315 (1).zip](https://github.com/FalconChristmas/fpp/files/13110575/FPP_Logs_20231020.2315.1.zip)

**Comment by dkulp** [comment]
In the /boot/config.txt, near the bottom, there is a section where we set the gpu memory for each pi.   Can you try adding:

`
[pi02]
gpu_mem=128
`

and then rebooting and see if that fixes it?

**Comment by bobreese** [comment]
There was a discussion on Sunday in the zoom room where a user with a Pi4 was playing videos in repeat mode and Not within a playlist, after finishing the video once and starting it over a Crash Log was created.
Myself and others with PI4's were able to duplicate it with the users video's.
Here is the users crash log

[fpp-Pi-7.2-2023-10-22_10-45-53.zip](https://github.com/FalconChristmas/fpp/files/13113939/fpp-Pi-7.2-2023-10-22_10-45-53.zip)

**Comment by derwin12** [comment]
The video from Bob crashed mine after 1 iteration.
[fpp-Pi-7.2-1-g1ca81bce-2023-10-24_09-16-54.zip](https://github.com/FalconChristmas/fpp/files/13114972/fpp-Pi-7.2-1-g1ca81bce-2023-10-24_09-16-54.zip)

**Comment by theadster** [comment]
> There was a discussion on Sunday in the zoom room where a user with a Pi4 was playing videos in repeat mode and Not within a playlist, after finishing the video once and starting it over a Crash Log was created. Myself and others with PI4's were able to duplicate it with the users video's. Here is the users crash log
> 
> [fpp-Pi-7.2-2023-10-22_10-45-53.zip](https://github.com/FalconChristmas/fpp/files/13113939/fpp-Pi-7.2-2023-10-22_10-45-53.zip)

I also encountered this issue when getting this project setup. I would just play a video from the main status page and click repeat. After it ended, a crash log was generated. I got around that issue by making a playlist of 2 videos and having the playlist repeat. Since I was able to get around that, I figured this was a separate issue.

**Comment by theadster** [comment]
Here's an update since I was messing around with this all day.

I replaced the Pi Zero 2 with a full size Raspberry Pi 3+ and moved the Micro SD card from the Zero to the Pi 3 with no changes. The Playlist has been playing nonstop for about 7 hours now with no issues!

**Comment by darylc** [comment]
Please test the very latest 7.3.x, Dan has fixed numerous crashes in that in the past few days.

**Comment by darylc** [comment]
no response
