### ISSUE TITLE
ffmpeg/ffprobe appears to be missing from docker container

### ISSUE THREAD

**Issue by Cassock** [FalconChristmas/fpp#1619]
**FPP Version and Hardware**: v7.x-master-286-gfc5b676b (master branch) running on Ubuntu docker host

**Describe the bug and Steps to reproduce**: 
Was not able to see media details ("Unknown" length on Audio tab in File Manager), and playlist throwing errors that accompanying media files were not present

Snip from my compose.yaml:

`
  fpp:
    container_name: fpp
    image: falconchristmas/fpp:latest
    restart: unless-stopped
    privileged: true
    hostname: FPP-Docker
`

Execing into the container and manually installing ffmpeg resolved the issue, at least for now. 

**Expected behavior**: 
Audio deets and happy playlists

**Additional context**: 
Initial discussion on FB here: https://www.facebook.com/groups/xLights/permalink/6882724058429957

**Comment by dkulp** [comment]
Should be resolved now
