### ISSUE TITLE
Removal of PiFace can lead to orphan GPIO settings

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#162]
If you configure certain GPIO settings with a PiFace connected, then remove the PiFace, you lose the ability to de-configure those GPIO settings.  This is due to the auto-detecting of the PiFace and hiding certain UI configuration from the user when not present.

We should either temporarily disable them in fppd if a PiFace isn't connected on startup, or maybe disable them altogether in the config file on boot.

**Comment by cpinkham** [comment]
This was fixed in master by showing the PiFace section if there are any PiFace GPIO inputs enabled.  Once they are disabled, the PiFace section does not show up anymore.
