### ISSUE TITLE
7.2 will not allow me to select SoundBlaster

### ISSUE THREAD

**Issue by cmjewells** [FalconChristmas/fpp#1620]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by derwin12** [comment]
If it doesnt show up there are a couple things to check .. first - do you have an fm transmitter, turn it off, restart the fpp and check again. If that isn't it, then try the soundblaster in your pc to see that it is recognized.

**Comment by dartunder** [comment]
You may want to enable a "FPP Boot Delay" on the System Settings tab.  15s likely way less works too.

**Comment by cmjewells** [comment]
> If it doesnt show up there are a couple things to check .. first - do you have an fm transmitter, turn it off, restart the fpp and check again. If that isn't it, then try the soundblaster in your pc to see that it is recognized.

I do have an FM transmitter, i unplugged it and restarted FPP, plugged it back in and it did show up, but today when my show started up, FPP reverted to the headphone jack and sound blaster was not an option again. I did test the sound blaster in my laptop and it is working fine.

**Comment by derwin12** [comment]
Some FM transmitters are known to cause this. There is some sort of low vs high power mode. Any docs about powering up and choosing a low power mode? You need to get the transmitter far 5-10ft away from the soundblaster/usb. Shielded if possible.

**Comment by darylc** [comment]
@cmjewells When you have this problem can you go to http://<your fpp ip>/troubleshooting.php

then paste us the output from sections:
[USB Device Tree]
[USB Devices]
[Sound Cards]

**Comment by darylc** [comment]
@cmjewells  please provide the information requested

**Comment by darylc** [comment]
No response
