### ISSUE TITLE
64x64 LED panels not available in FPP for BBB

### ISSUE THREAD

**Issue by thisim** [FalconChristmas/fpp#1622]
FPP 7.2 running on BBB

Hello, I want to control 64x64 LED panels with an octoscroller card on my BBB.
In the version of FPP for BBB, there is no possibility to choose the 64x64 panels.
On the other hand, on FPP 7.2 for raspberry PI, there are 64x64 LED panels.
Would it be possible to add them in the version of FPP for BBB.

![Capture d'écran 2023-10-30 145418](https://github.com/FalconChristmas/fpp/assets/31959517/d48d0e4e-dd22-43f2-a68e-4ffff82441f5)

**Comment by dkulp** [comment]
It's likely not possible on the Octoscroller/PocketScroller unless they are "Outdoor" panels that are 1/16 scan (or 1/8 scan) and I haven't seen any such panels.   The 64x64 panels require an "E" addressing line and the Beagle doesn't have enough pins to add the E line and keep the 8 panel connectors.

**Comment by thisim** [comment]
> It's likely not possible on the Octoscroller/PocketScroller unless they are "Outdoor" panels that are 1/16 scan (or 1/8 scan) and I haven't seen any such panels. The 64x64 panels require an "E" addressing line and the Beagle doesn't have enough pins to add the E line and keep the 8 panel connectors.

Here are the images of the IN and OUT connectors with pin details.

![received_296518369936138](https://github.com/FalconChristmas/fpp/assets/31959517/25d56ac1-aee4-41d4-b803-832ca408e148)
![received_347871204396524](https://github.com/FalconChristmas/fpp/assets/31959517/f7cd5e6a-e963-4e34-b02f-e0cb0954a576)
![received_668669588579136](https://github.com/FalconChristmas/fpp/assets/31959517/e3970117-c386-4d9f-97c3-815d6170d6ce)

**Comment by darylc** [comment]
As Dan said your panels have an E data line which octoscrollers do not, so they can't be used with an octoscroller.
