### ISSUE TITLE
Unable to grow file system via the UI in 7.2

### ISSUE THREAD

**Issue by russellmcfarlandsc** [FalconChristmas/fpp#1624]
FPP 7.2 on BBB.

I am unable to retroactively grow the file system after bypassing that option inadvertently during the initial setup.  Grow filesystem isn't exposed in the developer (or advanced) UI under the storage menu in 7.2.

**Comment by russellmcfarlandsc** [comment]
I had to revert back to 6.3 to make the change through the FPP UI.  Seems like unexpected behavior.

**Comment by darylc** [comment]
Dan has made changes in https://github.com/FalconChristmas/fpp/commit/0d6a8840416055dc14b08eae84251d3cb548f601
