### ISSUE TITLE
FPP Upgrade Source - show current value as the default value

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1626]
When showing this page, if the current value is not valid, it shows github.com. Can it show this invalid IP? 
Not knowing the actual value can lead to confusion on on failed attempts etc.

Perhaps show the current value, then github.com as the first value in the dropdown if not the current value.
![image](https://github.com/FalconChristmas/fpp/assets/4643499/73284ed0-5811-45a1-8d5a-1159c29513d4)

**Comment by ghormann** [comment]
I'm not sure I understand why.  github.com is a good default value as it should work if you have internet access.  (I do understand that some people have a show network w/o internet access and thus can't use github.com, but I would believe the majority of devices do have internet access).

**Comment by derwin12** [comment]
We saw the issue tonight in zoom .. the user was on a show network .. it showed github.com but when he ran the upgrade it failed on unable to connect to some old show network ip. That IP was not shown and the *fix* was to select another then go back to github.com. The ask here is to simply show the current value of the source and if no current value, default to github.com

**Comment by dartunder** [comment]
Trivial, but just in case someone searches for this...  

The FPP Upgrade source does not work if the source is on the master branch and the remote is on the release branch.
FPP Upgrade source works if they are both on master or both on the release.
