### ISSUE TITLE
Refresh Models pushed from FPP connect completely by removing prior pushed models.

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1627]
With folks having multiple show folders (halloween, christmas etc). Models for testing is getting a bit confusing and cluttered. 
Can models be tagged in some way that fpp connect pushed "models" could be removed and refreshed in their entirety?
Leave manually added models untouched.

Perhaps a flag A vs M (automatic vs manual) on the side?

![image](https://github.com/FalconChristmas/fpp/assets/4643499/510bc70f-2d38-44ee-a92f-52d8183a171d)

**Comment by computergeek1507** [comment]
FPP side is implemented 927de9f2fd67499de3c8812382fce5dfdbc0c8e8

**Comment by darylc** [comment]
@computergeek1507 Have you had a chance to do the xlights side?

**Comment by computergeek1507** [comment]
Everything is implemented
