### ISSUE TITLE
Add a pause button.

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#1628]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when.

 [there have been times where I have wanted to pause my show while it's in the middle of a schedule without disrupting the order of the schedule due to having to direct traffic or deal with somebody with bad behavior]

**Describe the solution you'd like**

Add a pause button to the bottom of the player on the status page so that the current playlist could be paused for a moment and then can be restarted.

**Describe alternatives you've considered**

Maybe the play button could be made to toggle between play and pause.

**Additional context**

**Comment by darylc** [comment]
@ebuechner The FPP team has already decided that it will not be implementing this - see https://github.com/FalconChristmas/fpp/issues/486
