### ISSUE TITLE
Enable software audio mixing

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#163]
Enable software audio mixing for overlapping audio file support.

**Comment by darylc** [comment]
@ghormann shall we close this?

**Comment by ghormann** [comment]
On this one, I'd ask @cpinkham .  I can see the value.   Chris also has this idea for the ability to run multiple playlist in parallel in the future...

**Comment by dkulp** [comment]
This actually is already implemented for 5.0.   For 5.0, we do use the alsa dmix plugin for all devices except for the built in audio devices on the Raspberry Pi.   For some reason, it doesn't work at all on the built in audio, but that's OK as the built in audio already supports multiple streams.
