### ISSUE TITLE
WLED does not work behind proxy... they claim it's an FPP issue.

### ISSUE THREAD

**Issue by dartunder** [FalconChristmas/fpp#1632]
https://github.com/Aircoookie/WLED/issues/3503

I know it's more complicated than that, but this is the related bug report if someone cares to explain better the proxy issue or has any idea how to fix it.

**Comment by cbennett6008** [comment]
The problem I saw last I looked at this is that WLED is using an absolute URL embedded inside the javascript to access their API stuff, and FPP does not rewrite that URL to use the proxied equivalent.

**Comment by darylc** [comment]
@cbennett6008 That is correct, and more importantly FPP can't rewrite the URL given the way they've embedded it inside javascript etc.
