### ISSUE TITLE
Sequences fail to properly upload via FPP Connect under 7.3

### ISSUE THREAD

**Issue by smtpboy** [FalconChristmas/fpp#1634]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
7.3 on Pi 4, xLights 2023.18 on Mac and 2023.19 on Win64

**Describe the bug and Steps to reproduce**: 
Upload sequence via FPP Connect (both in 2023.18 on Mac and 2023.19 on Win)
Process completes, but uploaded fseq file is only 10-15kb in size, will not play back.  
Did not happen under 7.2.

**Expected behavior**: 
fseqs should upload correctly

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20231105.2114.zip](https://github.com/FalconChristmas/fpp/files/13260811/FPP_Logs_20231105.2114.zip)
[xLights_l4cpp.log](https://github.com/FalconChristmas/fpp/files/13260816/xLights_l4cpp.log)
<img width="1615" alt="Screenshot 2023-11-05 at 4 13 07 PM" src="https://github.com/FalconChristmas/fpp/assets/71394162/55d45fda-efc2-41f5-b1ba-5a3a4be224b0">

**Comment by bobreese** [comment]
Is this an upgrade from an older version or a new clean SD install?
Seems there are a few issues.
FPPD Log: [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:917: Warn: "02 Gloria.m4a" - [mov,mp4,m4a,3gp,3g2,mj2 @ 0xa5d14f40] stream 0, timescale not set

XLights log: /var/folders/7y/h4xfc3nd7ybg61xbjbw0b20w0000gn/T/org.xlights/GloriaSfm3RV

My guess, corrupt SD card......

**Comment by smtpboy** [comment]
@bobreese Not possible on that one. I tried it both ways, both an upgrade and a clean install.  I started it with the upgrade from 7.2 to 7.3 where the problems started.  When I couldn't get things to work, I took a different SD card and imaged it directly to 7.3 - so there's no chance its a corrupt card.  As I said everything worked flawlessly in 7.2.... and the xLights versions didn't change.

**Comment by smtpboy** [comment]
Also worth noting that this isn't happening with every single sequence, but a large percentage of them have the nearly empty fseq files on the FPP.

**Comment by dartunder** [comment]
What format are you using, V2 or V2/sparse?  Does it still happen with V2 selected?

**Comment by smtpboy** [comment]
@dartunder Will give it a try momentarily.  Thanks.

**Comment by smtpboy** [comment]
> What format are you using, V2 or V2/sparse?  Does it still happen with V2 selected?

Was using v2/sparse, but tried v2 as well - files were larger but same problem seemed to manifest.  The resulting fseqs were only a couple of hundred kb vs the megs you'd expect.

**Comment by smtpboy** [comment]
I've figured out the issue, this is indeed an xLights problem (or possibly user error on my part, still unsure), it just happened to manifest around the time of the 7.3 upgrade.  Apparently when I added a couple of shadow models, xLights started only rendering those models into the fseq for some unknown reason, which is why the fseqs were so small.  This isn't an FPP issue, sorry for the fire drill.
