### ISSUE TITLE
Visualizer and Monitor broken on Proxied board

### ISSUE THREAD

**Issue by Fonzi03** [FalconChristmas/fpp#1635]
Pi4 running FPP 7.3.1
F16v4 on Bld 27

Navigate to the proxied board
click on visualizer or monitor
neither work due to the URL looking for the proxied IP

you can manually update
http://xxx.xxx.1.xxx/proxy/xxx.xxx.0.xxx/index.html
with
http://xxx.xxx.1.xxx/proxy/xxx.xxx.0.xxx/visualizer.html    or http://xxx.xxx.1.xxx/proxy/xxx.xxx.0.xxx/cmon.html

and the pages work, a fix for this would be to determine if the user navigated to the board through a proxy and if so append the visualizer and monitor URLs with the original fppIP/proxy/boardIP

**Comment by darylc** [comment]
Please log this issue at https://github.com/Pixelcontroller/f16v4_issues and I'm sure they'll fix it in the next version for you.
