### ISSUE TITLE
K8-PI issue with smart receiver output (channelshift??)

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1639]
Copied from xlights issue #4112.   This user known as 'racing' is having what appears to be a channel shift issue... even if outputing a single channel in display testing getting mixed results.  It was suspected to be caused by the DUMMY configuration that gets created with xlights upload but the dummys were removed and other models put in place with same issue.   Issue specifically is on K8-PI port 9-12 using a srx4 receiver.   I got a fpp logs and packaged sequence from the user I am attaching. 
[FPP_Logs_20231109.2156.zip](https://github.com/FalconChristmas/fpp/files/13313211/FPP_Logs_20231109.2156.zip)
[k8pi smart reciever issue.zip](https://github.com/FalconChristmas/fpp/files/13313212/k8pi.smart.reciever.issue.zip)

From Zoom.
This might be more for awareness or to see if it can be duplicated.
FPP 7.2, 2023.16 with k8-Pi (raspberry pi not a bb)

Scenario:
SRx4 - v2 remote type, set to A on the receiver.
The goal was to put the tree across the middle of the SRx4 to distribute power.

Had Star on 13A
Had 8 Port Tree on 13B + C, 14B+C, 15B+C, 16B+C
When pushed to the controller it created DUMMY entries seemingly on every port.
They were set to 0 pixels

Testing from the outputs page, tools->test, display testing etc
For Red a couple of strands would be Green.
Swapping of ports/pixel strips made no difference .. the port was putting out Green

"Fix" was to place ANY prop on 14A, 15A, 16A.
Wanted to distribute power, so we didn't move the tree to A.

I didn't see anything in a recent release so we never tried a newer version of xlights or fpp.
If this is addressed already, feel free to close. If you cant duplicate it - we can chalk it up to dumb luck. :-)
Daryl

**Comment by bloojoop** [comment]
original issue captured in xlights github https://github.com/smeighan/xLights/issues/4112

**Comment by Racingj29** [comment]
I is with my fpp srx4

**Comment by dkulp** [comment]
There seems to be some problems with the SRx# firmware with the v2 protocol.   Using a v2.01 smart receiver, everything works fine.   Also, using the v1 protocol with the SRx# receivers also seems to work OK, but obviously limits to only chaining 3.   I'm likely going to need some help from @dpitts.    For now, I suggest using the v1 protocol.

**Comment by Racingj29** [comment]
OK so all I have to do is change the v2 to v1 on everything and it should work properly?

**Comment by derwin12** [comment]
That can be done via the visualizer -- right click on each prop on those ports and update the type. Save and upload to controller.

**Comment by dkulp** [comment]
Actually, my issue turned out to be termination issues (forgot to turn on the terminating resistors when I wasn't daisy chaining) and now I cannot reproduce any of the problems.   With an SRx2, I can configure strings on the A/B and they seem to test fine with v2 protocol.  K8-Pi and Pi4.   I may need full configurations and likely sample sequences to see how things are being uploaded.    (and double check your terminating switches)

**Comment by Racingj29** [comment]
So do you recommend me trying to use a/b for the tree instead of trying to use b/c like I am and put the star back on c as well

**Comment by dkulp** [comment]
Now that I've fixed the terminators on the SRx4 and SRx2, I'm not seeing any issues with FPP using the K8-Pi and a Pi4.   The SRx4 is set to "A" and all the colors and such are exactly as I'd expect them to be.  Outputting directly from xLights (DDP) is showing exactly what I'm putting on the strands.

**Comment by Racingj29** [comment]
OK I have no idea on what to do from here. I guess it's my lose. I have done everything you guys have said to do with same results. My board is set to a and all dip switches are set to on. There is an issue somewhere heck maybe it's in my k8-pi I don't know. Is it possible I'm getting interference from the power supplies I have under said board. I don't know it's my first year doing this. The only thing this is powering up is the tree and star. It's not the strands cause I put different strands on ports and has same results. Maybe you can get into a zoom room with me and help go through it all to see if you see anything that could be out of place.

**Comment by Racingj29** [comment]
On the board when lit up is the light for v1 v2 v4 supposed to be lit up for v2 or no

**Comment by Racingj29** [comment]
Seems as if A on the board is the issue. I have been testing and trying different things and port A is the one that is really messing up. Not sure if that info is any good to you but that's what I have come up with.

**Comment by Racingj29** [comment]
Got it running. The dip switches were all up where it says on. I moved all dip switches down and it started to work. Thank you all for the responses.

**Comment by Racingj29** [comment]
moved it from where i was testing which meant unplugging everything and its acting up again and did nothing different. there has got to be an issue with the board

**Comment by cybercop23** [comment]
Is this still and issue or can this be closed? If so please close.

**Comment by Racingj29** [comment]
Still has the issue I believe it's the k8 pi that's the issue but I'm
working on trying to put together my experience lights long range and see
if it works with it. If it doesn't then I know it's the k8 pi
