### ISSUE TITLE
Repeat of playlist or item inconsistent

### ISSUE THREAD

**Issue by Kryptonit3** [FalconChristmas/fpp#1643]
FPP 7.3.1
RPi 4B

when playing a playlist or file from the status page manually, I select an item, check the repeat box then click Play. More often than not I see the item plays and stops. It will randomly keep playing but it’s hit or miss, have to watch full item playback to see if it will keep playing. 

Once the item fully plays it then tries to repeat the item and shows the "FPPD Daemon is not running" error and doesn’t end up running again.

https://youtube.com/shorts/T918Pkr5VP8

[FPP_Logs_20231112.2326.zip](https://github.com/FalconChristmas/fpp/files/13329437/FPP_Logs_20231112.2326.zip)

**Comment by Kryptonit3** [comment]
This is the log file with debug enabled and the issue happening again
[FPP_Logs_20231112.2335.zip](https://github.com/FalconChristmas/fpp/files/13329452/FPP_Logs_20231112.2335.zip)

**Comment by darylc** [comment]
Can you be specific about the timestamp when you did this and it did not work?

I see a lot of problems from your fppd.log (in no particular order):
Trying to play playlists that don't exist via the API causing fppd to crash.
lots of API calls
VLC errors (video?) VLCOut.cpp:140: AStreamSeekStream: hard seek failed

I cat actually see you doing 'I select an item, check the repeat box then click Play. ' in the log files you provided.

**Comment by derwin12** [comment]
I can duplicate this .. using 7.2.1. Just select an mp4 and set to repeat and play. It almost seems that it is too quick to repeat and the file is locked or in use or something. Perhaps a playlist with a 1 sec pause after would suffice?

**Comment by cpinkham** [comment]
Claiming this ticket.  I have a fix for this and will get it committed.

**Comment by Kryptonit3** [comment]
1. When this fix merges with 7.3 Ill test. Most recent available is #ec0504a8
