### ISSUE TITLE
Show all active network interfaces in the upper right of the UI

### ISSUE THREAD

**Issue by TrekErs** [FalconChristmas/fpp#1645]
**Is your feature request related to a problem? Please describe.**
In the past all active network interfaces would show up at the top of the UI. Now an active network, set to dhcp, that does not receive an assigned address will not display. For example when connected to a colorlight card the 169.x.x.x address will not appear. During troubleshooting in the Zoom room it is often beneficial to see that this interface is active. 

**Describe the solution you'd like**
Always show IP addresses for active network interfaces in the top right of the UI.

**Comment by bobreese** [comment]
Colorlight cards do not use IP Address's. Leave the eth1 network on DHCP and it will auto connect. 
Because of the protocol the colorlight uses, it will not appear as a network connection.

**Comment by TrekErs** [comment]
Please reopen this issue.  You do not understand what I am asking for and DarlyC requested that I put this request in so he can look at it next year.

**Comment by darylc** [comment]
I asked Ryan to log this, I want to check this out when I have time

**Comment by TrekErs** [comment]
A small icon would be sufficient, just about anything to show the link as active.
