### ISSUE TITLE
Allow for the setup of multiple WiFi SSID's so that FPP can connect to the one it's currently near

### ISSUE THREAD

**Issue by HolidayLighting** [FalconChristmas/fpp#1647]
Right now FPP only allows for one SSID and its password.  The OS already allows you to have multiple configured and it will connect to the one that's available, possibly the one with the strongest signal.

I want FPP to be able to be configured for more than one SSID.

The scenario for me is I often configure things at home on my local WiFi using the eth0 as the show network and then move the Pi and equipment to a remote location that has a different WiFi available.

So when at home it would connect to my Home Wifi and then when I'm on site it would connect to the site's WiFi and I wouldn't need to reconfigure anything.

**Comment by darylc** [comment]
I've added some code to FPP 8 to allow backup SSID configuration, which FPP will connect to if it stops seeing the primary SSID, or the signal strength of the backup is better.  This needs testing please, you'll need to put the UI into advanced mode for the configuration to show up.

![image](https://github.com/FalconChristmas/fpp/assets/7511887/e4eb7c1f-cff7-4859-9b03-6f9ced568d84)

Please let me know how the testing goes.

**Comment by 7OaksFX** [comment]
I've tested this and can see & configure the backup SSID and PSK but the settings don't persist even after doing Update Interface, e.g. if you set it, go back to Status and back to Networking the backup settings are blank.

**Comment by darylc** [comment]
@7OaksFX pushed a fix where it wasn't populating the fields on the page if you reloaded it.
