### ISSUE TITLE
Add logging for mp3gain

### ISSUE THREAD

**Issue by Cassock** [FalconChristmas/fpp#1648]
**Is your feature request related to a problem? Please describe.**
Once the initial MP3Gain function runs it shows logs, but once that window is closed, these same logs are not found in File Manager > Logs

**Describe the solution you'd like**
Longer term logging added somewhere

**Describe alternatives you've considered**
N/A

**Additional context**
If these are already shown in one of the log files, I apologize - I didn't see it

**Comment by darylc** [comment]
@Cassock Can you please explain why logging is required for this?  Personally I can't see the need.

**Comment by Cassock** [comment]
"Need" is a strong word, maybe. I was interested in 2 things after I ran it:
1. to understand how much specific tracks were adjusted so I can potentially do some of that on the frontend as I'm putting custom tracks/voiceovers together in Audacity
2. to understand why a few tracks were not adjusted at all (based on their timestamps). Two of them happened to be .wav files which are apparently not supported, but an error message available there would have informed me much more quickly
2a. if an adjustment on an mp3 track failed for some reason in the future, logging would be nice to refer to

**Comment by bcarriveau** [comment]
Just map your fpp audio folder as a network drive and use mp3 gain like you normally would on the pc. Didnt even know it was part of fpp untill today lol
