### ISSUE TITLE
Does FPP support Raspberry Pi 5?  

### ISSUE THREAD

**Issue by cnebrask** [FalconChristmas/fpp#1649]
Will FPP OS work on Raspberry Pi 5?

**Comment by dkulp** [comment]
Not at this time.   FPP is currently based on Debian 11 (Bullseye).  However, the Pi5 requires the very latest Pi OS which is based on Debian 12 (Bookworm).   Some efforts have been started to get things updated, but it definitely will not be ready for this year.

**Comment by dg6464** [comment]
Just wanted to say thanks for the efforts on FPP... amazing project - happy to see efforts already going towards support of RPi 5.

**Comment by cnebrask** [comment]
Thanks Daniel, i appreciate the info!  Keep up the good work !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
