### ISSUE TITLE
PiHat (notDPI) showing lagging in first 100ish pixels with 7.3.x

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1651]
From zoom but I duplicated it as well.
Placed 200-400 pixels on Falcon PiHat (3b+ or 4) using 7.3 fppos update or fully updated to 7.3.2
Using just a display test from fpp the first 100ish pixels will lag/roll from one color to the next. The remaining > 100ish pixels will change colors "instantly".
Works fine in 7.2. No other changes other than the upgrade.

User from Zoom had multiple stars where the first star 50+ pixels would roll thru the color changes.
I duplicated with triple arches and the first arch would roll thru the color change.
All other pixels performed normally.

The zoom roomer went and bought a license and switched to DPI and didn't have the issue.

For me capeinfo shows
PiHat
1.0
FPP-INTERNAL

**Comment by cybercop23** [comment]
@derwin12 If I recall exactly the other zoomer with a PiHat and Pi4 had not issues.

**Comment by derwin12** [comment]
This was the guy with the 10 or so stars on his roof. I think was his name was Chris

**Comment by CHSEngineering** [comment]
Yes, it was Chris, that is me, do you need further info?

**Comment by CHSEngineering** [comment]
I am running a pi 3b+ and a pixel controller pi hat
![controller](https://github.com/FalconChristmas/fpp/assets/78917460/f078d202-ef6f-4b3f-b228-e274dfe14197)

The guy with the Pi 4 was not seeing the issue

**Comment by CHSEngineering** [comment]
Was this resolved or just eliminated because of the release of FPP8

Thx
Chris

**Comment by derwin12** [comment]
Yea... need to test again on v8 .. it wasnt looked at by the devs afaik

**Comment by CHSEngineering** [comment]
Understood, thanks for helping with this
