### ISSUE TITLE
The control channel output type in FPP 7.3.1 does not appear to work.

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1654]
I created a command preset in FPP 7.3.1 on a raspberry pi to start a playlist.  I named it start and set the slot number to 1.  I then created an other output type using the control channel type in FPP 7.  I set it for start channel 77 in this case and a value of 1 to call the start preset.  I then created a single channel model and set the start channel to 77.  I set an effect with a value of 1 and it does not trigger the command preset.  I can see that the ddp data packet are arriving on the status page.  
![image](https://github.com/FalconChristmas/fpp/assets/88390168/8573b1d7-4388-4d32-ac06-57e324b434de)
![image](https://github.com/FalconChristmas/fpp/assets/88390168/0f2dc27d-7bfe-4b55-8a91-5062b5e90489)

I then took another test pi and set it up on 6.3.2.  In 6.3.2 I created the very same command preset and set the command preset channel number to 77 on the input/output tab in fpp settings (since that is where it is in 6.3.2. I changed the ip address of the controller in xlight to point to this 6.3.2 instance and it worked like a charm with zero issue. 
![image](https://github.com/FalconChristmas/fpp/assets/88390168/f44c2c63-08c9-432c-80e2-3874920df719)

It appears that the new control channel other output type is not working for me.

**Comment by dkulp** [comment]
This was fixed in 7.3.3.
