### ISSUE TITLE
forum/help - Related to eeprom

### ISSUE THREAD

**Issue by Fonzi03** [FalconChristmas/fpp#1655]
I bought a board from microcyb (8 port picape) and accidently overwrote the eeprom. I got a .bin from him but i get the missing cap-info.json. I asked for that and he has not provided it, instead he told me to rename the .bin .zip then extract and the json would be in there...that method does not work as it doesnt make it a proper compressed file structure. 

I tried to build my own via the samples listed here and made a .bin but when I loaded I got the same error. 

I tried to log in to falconchristmas.com/forum and my account never got approved by admins. Really just looking for support here, or more clear instructions on generating the eeprom/json.info and where it should go.

**Comment by darylc** [comment]
per facebook reply, you really need the vendor to create the EEPROM as you nor us have the required information to do so.
