### ISSUE TITLE
WLED Controller not appearing in  Multisync page 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1656]
**FPP Version and Hardware**: 
*FPP 7.x-master-348-g4c04f754*
*as well as 7.2.1*
*WLED v0.13.3 "Toki"*

**Describe the bug and Steps to reproduce**: 
Open FPP Multisync page and you should see WLED Devices in Multisync page.

**Expected behavior**: 
We should see that device in the list.

**Comment by cbennett6008** [comment]
Pat,  I've found that if you restart FPPD, that the discover action happens again (on the IP's/subnets configured for discover) and they show up.  After a while they change from WLED to Unknown, and then disappear until FPP is re-started again.

**Comment by darylc** [comment]
@patdelaney I think I heard you discuss this in zoom and it is no longer an issue?

**Comment by patdelaney** [comment]
Unfotunatly this is still an issue with WLED. Status is Last Seen is showing up right away (WLED version 0.15.0-b4
![image](https://github.com/user-attachments/assets/d0c89c81-e85c-4d47-9db7-dc39522ac9b6)

**Comment by patdelaney** [comment]
Closing after discussing with @darylc
