### ISSUE TITLE
battling to get the Fpp v7.3.1 to save my wifi detials

### ISSUE THREAD

**Issue by csinnett1910** [FalconChristmas/fpp#1658]
i decided to up date my Pi 4 hat with the latest veriosn of FPP, but once i flash the sd card and do the intial set up and then i do the network set up. i like update/save and reboot the pi, but it doesnt connect to the wifi. if i plug in the ethernet cable again it is connectable again. witht he ethernet cable plugged in, if i go into network settings again, there isnt any wifi settings saved.

it almost seems to not be saving it? is there a way i can manually save the details to the sd card for the wifi

regards

**Comment by bobreese** [comment]
After setting up the Wifi ID and password, click the Update Network button in the lower left corner.

**Comment by csinnett1910** [comment]
Hello,

Hope you well.

Thank you so much! I did, then rebooted but after rebooting it still didn't have the wifi settings

Be well.

Calvin

**Comment by Arcxk** [comment]
I use BeagleBone based Kulp controllers and when I setup my wifi, I usually just edit the config file via ssh then reboot. Perhaps you can use the same method on the Pi.

The filepath is /home/fpp/media/config/interface.wlan0

INTERFACE="wlan0"
PROTO="static"
ADDRESS="X.Y.Z.50"
NETMASK="255.255.255.0"
GATEWAY="X.Y.Z.1"
SSID="ABC"
PSK="123"
HIDDEN=

**Comment by csinnett1910** [comment]
Hello,

Hope you well.

Thank you so much!

Be well.

Calvin
