### ISSUE TITLE
Add search domain to FPP network config UI

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1659]
**Is your feature request related to a problem? Please describe.**

FPP does not support search domains in the network configuration.  For networks with a local DNS zone, FPP is unable to resolve hostnames on the network without entering the entire FQDN.  for example, if I want a script to contact the host fppInstanceName.  I cannot just use fppInstanceName.  I must append the full domain to every reference.  e.g. fppInstanceName.domain.tld.  In my network I use the chuchla.local domain.  I have FPP instances with the hostnames fppMaster and fppSign.  In order for fppMaster to talk to fppSign, I must use the full fppSign.chuchla.local in every reference.  It would be much easier to just refer to it as fppSign.

**Describe the solution you'd like**
Implement the search domain feature.  I can manually add the search domain to resolv.conf and it will work temporarily.  I can also use "sudo systemd-resolve --interface eth0 --set-domain chuchla.local"  this will also cause the search domain to temporarily work.  But neither of these methods survives a system reboot.  I assume that FPP is overwriting the network config at boot.  So it would need to have this search domain field in the network configuration that it writes at boot.  When DHCP is enabled, it should use the search domain provided by DHCP.  when static IP is enabled, it should have a user specified search domain field alongside the Host and DNS settings.

**Comment by darylc** [comment]
It is extreme unlikely that this will be implemented in FPP unless someone sends us a pull request to implement it.

**Comment by Jchuchla** [comment]
This used to be simple in early FPP releases, but as FPP moved to more complex network configuration stacks, it’s now very difficult to override the settings because FPP overwrites it on every boot.  I dug into this when I wrote up the ticket.  This request is really just as simple as adding one more input field on the network configuration page and writing it to the configuration file that FPP writes on each boot.  I just don’t have the experience to add this to the FPP application and submit for PR myself.

FPP neither honors this field when it’s provided via DHCP, nor does it allow you to specify it manually.

-- Jon Chuchla --
