### ISSUE TITLE
Show total current draw on current monitor page

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1660]
**Is your feature request related to a problem? Please describe.**
For controllers with eFuses and current monitoring, power is provided in known banks.  It would be nice to see a field with the total power per bank and total for the controller.

**Describe the solution you'd like**
Add fields for subtotals per bank (all outputs connected to the same power bus)
Add field for total power consumption on controller.

Also see Issue #1661 for related request.

**Comment by OnlineDynamic** [comment]
Dan has added this in fpp8 master branch
