### ISSUE TITLE
Add current stats to MQTT reporting

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1661]
**Is your feature request related to a problem? Please describe.**
I would like to be able to monitor the current of the controllers, per port, per bank and total per controller from my home automation system.

**Describe the solution you'd like**
Provide current stats in an MQTT topic.

**Additional context**
See Issue #1660 for related request.

**Comment by ghormann** [comment]
I don't have one that reports current, but I *think* these are just configured as sensors.    

If you enable the stats publishing, doesn't it show up as a sensor?
![image](https://github.com/FalconChristmas/fpp/assets/24968726/7e85fb7d-224d-41a6-9f84-cf3ee164a62d)

Here is what I see on my version w/o current sensors

![image](https://github.com/FalconChristmas/fpp/assets/24968726/734e2419-b2f7-42f6-a7d4-3aaaae927d8c)

**Comment by Jchuchla** [comment]
Nope, they don’t show up under sensors.  And really it should show up as it’s own subtopic, not a whole bunch of json stuffed into a single status topic that we have to parse to make use of.

**Comment by Jchuchla** [comment]
I don't use Home Assistant.  I use Homeseer.  It predates Home Assistant by a few decades.  While not really related to this issue here, I don't really understand why HA encourages stuffing a bunch of information as json into a single topic.  It makes it a pain to parse for the data you actually need.  It also forces you to update all your parameters any time any part of that json changes.  Topics and subtopics are free.  Start a new one for each parameter.  Then you could just subscribe to the ones you care about.

**Comment by libby2cm** [comment]
Disregard my comment, I was assuming system attributes were intended to be included in 'sensors' but after looking at the code, they aren't... it's just select hardware. I may submit a feature request for that and other non-hardware sensors though.
