### ISSUE TITLE
Remote FPPs Not Triggering via Multisync. Seems to be timing-out.

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1663]
v7.3.5 (v7.3 branch)

I cannot trigger via multisync to remotes (all latest version) until I manually restart FPPD on the remotes. It's like they time-out or something? The remotes show idle and it appears FPPD is running, but they don't do anything when triggered by the player FPP. I manually restart the remote FPPD, then the player triggers it fine. When the remotes are idle overnight, they won't trigger remotely anymore. 

I have three remotes and all act the same way.

Yesterday, I installed the script to restart FPPD if it stops. Made no difference.

No crashes. Nothing obvious that's wrong that I've observed. Been fighting this for a couple of weeks now and unable to resolve. 

Is there a way to set the FPP to restart FPPD at a scheduled time? If I could at least get them to restart on their own prior to the show starting, maybe that will get me through the season until this bug is found/fixed? Right now, I'm having to manually restart all remotes before the show.

**Comment by McCoyCOREUSA** [comment]
LOG (Master): https://mccoycloud.com/index.php/s/NZ6qGYqJrHatbZp
LOG (Remote): https://mccoycloud.com/index.php/s/rbj5ag6RHWRsSty

**Comment by dkulp** [comment]
This is most likely not a bug in FPP, but an issue with your router/switches.   Many consumer routers still don't properly support IGMP subscriptions.  You may need to flip to using unicast by selecting the individual remotes on the players multi sync page.

**Comment by McCoyCOREUSA** [comment]
Looking through the logs with the Zoom Room, we figured it was stopping listening for remote 'signals' from the player due to a time-out with not receiving anything for a while (overnight). That's not it?
