### ISSUE TITLE
Make `DDP_CHANNELS_PER_PACKET` an advanced configuration option (similar to xLights)

### ISSUE THREAD

**Issue by dbinit** [FalconChristmas/fpp#1664]
**Is your feature request related to a problem? Please describe.**
I have a HinksPix Pro (v5.1 PN#925) that is not accepting DDP from FPP. After talking to Joe Hinkle about it, I discovered that I could lower the "Channels Per Packet" in xLights to 599 to get it to work. This has something to do with the controller using a smaller MTU to save memory or something.

<img width="340" alt="Screenshot 2023-11-24 at 1 32 12 PM" src="https://github.com/FalconChristmas/fpp/assets/77516/1d9e616e-4f90-4647-8b33-11e80c9e8479">

**Describe the solution you'd like**
I see that there's a `DDP_CHANNELS_PER_PACKET` constant defined and set to 1440. It would be great if this were configurable in the Output channel configuration, perhaps as an advanced setting.

**Describe alternatives you've considered**
I've attempted to reduce the MTU on the interface using `ifconfig` but this doesn't seem to do anything.

**Additional context**
Note that everything worked fine last year and the year before, so I'm not exactly sure what has changed since then. The firmware on the controller automatically upgraded when I turned it on, and I've also upgraded to the latest FPP and xLights versions. Joe says he hasn't made any changes to the firmware... so not sure what to think. He recommends I just switch to E1.31.

**Comment by OnlineDynamic** [comment]
Have you tried manually adjusting the defined value in the cpp source and recompiling? Would be good to confirm that achieves what you want before making any change to make this a configurable option

**Comment by darylc** [comment]
@dbinit please advise on the question above.

**Comment by darylc** [comment]
no response
