### ISSUE TITLE
People are downloading 7.3 instead of 7.3.1

### ISSUE THREAD

**Issue by dartunder** [FalconChristmas/fpp#1665]
@dkulp Can you remove 7.3(.0) images from the release?

Some people have been downloading these directly instead of using Raspberry Pi Imager and are getting stuck with wifi issues.
FPP-v7.3-BBB.img.zip
FPP-v7.3-Pi.img.zip

**Comment by cpinkham** [comment]
I removed the 7.3 files from the release page for now.
