### ISSUE TITLE
Enable Unicast 

### ISSUE THREAD

**Issue by bcarriveau** [FalconChristmas/fpp#1666]
Would it be possible to have a Send Multisync Packets via Unicast button (check box) that auto enables all remotes that Multicync currently has populated and turns off Mulicast at the same time?

Preferably would show right under the main Send Multisync Packets?

**Comment by darylc** [comment]
@OnlineDynamic One for you perhaps?

**Comment by OnlineDynamic** [comment]
How would it work for instances with multiple IP addresses?  Think current screen makes you select which ip address to use for unicast on each instance of fpp

**Comment by darylc** [comment]
@OnlineDynamic That is a good point.  @bcarriveau can you please comment?

**Comment by darylc** [comment]
no response
