### ISSUE TITLE
On Mobile - Clicking "FPP" icon takes you to network settings, not status

### ISSUE THREAD

**Issue by marx1** [FalconChristmas/fpp#1667]
**FPP Version and Hardware**: 
FPP 7.3.5 on Raspberry Pi 4, however issue has happened for a long time - all of 7.x

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Access FPP on mobile 
2. go to any other page, like Display testing
3. Tap on "FPP" or FPP icon in upper left
4. Be taken to network configuration page

**Expected behavior**: 
Be taken to the status page. like on desktop

**Additional context**: 
I'm using android, but I'm sure this would happen as well on iOS. If I switch to "desktop" in the browser it works as expected. This is super annoying as I'm expecting the same behavior as on desktop. tap FPP icon to quickly get back to main status page - instead I have to dig though menus on mobile, and that's a pain.

**Comment by cpinkham** [comment]
I'm currently unable to reproduce this on my iPhone or in Chrome on the desktop in developer mode emulating a mobile device.  The code has index.php hardcoded in it for the link destination on the logo.  For the version string link, the destination is the About page.

Has anyone else see this?

**Comment by bcarriveau** [comment]
Your clicking the host name that you probably didnt rename from Fpp. Not the fpp logo like on your browser.

**Comment by bcarriveau** [comment]
If you want more on your screen, use chrome browser, click the three dot menu, click zoom, and zoom out. You will get the view your looking for.

**Comment by marx1** [comment]
The issue is on desktop if you click the icon OR the hostname it takes you to the status page, not the network config page. I'll upload a video shortly in desktop mode showing this.

________________________________

**Comment by marx1** [comment]
here's the video https://photos.app.goo.gl/p6vhUXQbGYQw9RjM9

The main difference is you tap the upper left on desktop it's the fpp icon/logo on mobile it's the host name - this should be consistent; or at least have an option to switch this behavior - because on mobile it's very annoying when you have a title in the corner and expect it to take you to the home page and it doesn't.

**Comment by bcarriveau** [comment]
I dissagree, the host name is to know what unit you are on is far more important that a button to go back to the home page. Again. Every browser can been zoomed out. Here's my note 8 , chrome mobile. 

Zoom....out

![Screenshot_20231129-130828_Chrome](https://github.com/FalconChristmas/fpp/assets/60801063/1c760fa8-8e3a-4279-884e-799bdf634209)

**Comment by bcarriveau** [comment]
The more I think about it, I'm with @marx1, in the times I'm in fpp(alot) and the 50-100 or so iv helped set up or diagnosis, myself and others have never clicked a host name or asked someone to go to a host and dns page from the home page, always status control/ network..

I always have people click the logo as a short cut!

host name & fpp logo should go to status page! haha. 

Plus 2 on this please 🎉🙏

**Comment by marx1** [comment]
Thanks for changing it!
