### ISSUE TITLE
Volume control returns to 75 on its own

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#167]
Even if I manually edit the value in the settings file, it returns.

I prefer to keep my RasPi at 100 since I think it sounds better there.

But it appears to be common to RasPi and BBB

**Comment by cpinkham** [comment]
This is fixed now, it was affecting stage, master, v1.5, and v1.6.  I pushed the fix to all branches.  It was a = vs == issue in a comparison.
