### ISSUE TITLE
Remotes w/ a Virtual Matrix and a ColorLight intermittently not Displaying Content when indexing from MP4 sequences to MP3 sequences in playlist 

### ISSUE THREAD

**Issue by ahallber** [FalconChristmas/fpp#1670]
**FPP Version and Hardware**: 
Master (FPP-60PiCon): running version 7.3.5 on a Pi4
Remote (FPP-70PiRem): running version 7.3.5 on a Pi4 - running a Virtual Matrix for a 896 x 512 LED Display
Remote (FPP-93PiRem): running version 7.3.5 on a Pi4 - running a Virtual Matrix for a 512 x 256 LED Display

**Describe the bug and Steps to reproduce**: 
SOME INITIAL CONTEXT:
- Our Christmas display has 2 LED screens, controlled by 2 separate Pi Remotes, with which we include videos as part of the sequenced content. 
- Rather than embedding the videos on the prop within the sequence in xlights (we had render issues last year doing this as well as very large FSEQ files were generated), we create mp4 files that are used for the audio in the xlights sequence (MP4 with audio only in xlights), then the MP4s (with audio and video) are uploaded to the 2 Pi Remotes.
- In effort to use a "whole house" effect on some sequences (with the "whole house" including the 2 LED displays) some sequences are created with MP3 audio files and the LED Displays are mapped as part of a whole house grouping for xlights effects rather than using video on the 2 LED displays.

THE ISSUE:
- When the FPP Master is running the show and cycling through the playlist, intermittently, when the playlist transitions from a sequence that uses a MP4, to a sequence using a MP3, one or both of the FPP remotes for the LED displays will not display the content...the displays remain blank when the MP3 sequence starts, and throughout the entire sequence. On the Remote Status page, it shows that that they are linked to the master and counting down the sequence time, but the displays are blank
- The displays will display content when a FPPD restart is initiated, or intermittently will start to display content when the next sequence with a MP4 is initiated.

**Expected behavior**: 
The ability to display content on the LED displays when:
1. a sequence is designed using a MP4 file for the audio in xlights and for the MP4 file to display video content on a LED display on a Pi Remote using virtual matrix
2. a sequence is designed using a MP3 file for the audio in xlights, and the LED display prop is part of a whole house effect in xlights
3. a sequence is designed using a MP3 file for audio in xlights, and a video is added to the prop in xlights, and the video that is embedded in the FSEQ file is played on the LED display when the sequence is initiated.

**Additional context**: 
- PLEASE NOTE that this issue manifested during last year's Christmas Season as well when we were running FPP VERSION 6.3 on the rasberry pi remotes.
- This is an intermittent issue, but will happen every 1 to 2 cycles of our 30 minute playlist.
- Recently we added up to a 4 second pause in the fpp playlist between Sequences with MP4 files and Sequences with MP3 files to see if the additional time between sequences would help. The issue continued to intermittently manifest with the pause added.
- The MP4 files that are used are run through Handbrake to compress them to a smaller file size.
- Attached you will find 1) fpp backups of the master and 2 remotes mentioned, 2) fpp logs from the master and 2 remotes mentioned, 3) a crash log from one of the remotes that did not correspond with the MP4 to MP3 issue based on the time the log was generated. 

[60PiCon_all-backup_v7_20231126190755.json](https://github.com/FalconChristmas/fpp/files/13468910/60PiCon_all-backup_v7_20231126190755.json)
[70PiRem_all-backup_v7_20231126190738.json](https://github.com/FalconChristmas/fpp/files/13468911/70PiRem_all-backup_v7_20231126190738.json)
[93PiRem_all-backup_v7_20231126190644.json](https://github.com/FalconChristmas/fpp/files/13468912/93PiRem_all-backup_v7_20231126190644.json)
[FPP_Logs_20231127.0131_60PiCon.zip](https://github.com/FalconChristmas/fpp/files/13468913/FPP_Logs_20231127.0131_60PiCon.zip)
[FPP_Logs_20231127.0133_70PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468914/FPP_Logs_20231127.0133_70PiRem.zip)
[FPP_Logs_20231127.0135_93PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468916/FPP_Logs_20231127.0135_93PiRem.zip)
[fpp-Pi-7.3.5-M1-100000004137ef4b-2023-11-26_17-15-52_93PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468917/fpp-Pi-7.3.5-M1-100000004137ef4b-2023-11-26_17-15-52_93PiRem.zip)

**Additional Attachments**

[60PiCon_all-backup_v7_20231126190755.json](https://github.com/FalconChristmas/fpp/files/13468924/60PiCon_all-backup_v7_20231126190755.json)
[70PiRem_all-backup_v7_20231126190738.json](https://github.com/FalconChristmas/fpp/files/13468925/70PiRem_all-backup_v7_20231126190738.json)
[93PiRem_all-backup_v7_20231126190644.json](https://github.com/FalconChristmas/fpp/files/13468926/93PiRem_all-backup_v7_20231126190644.json)
[FPP_Logs_20231127.0131_60PiCon.zip](https://github.com/FalconChristmas/fpp/files/13468927/FPP_Logs_20231127.0131_60PiCon.zip)
[FPP_Logs_20231127.0133_70PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468928/FPP_Logs_20231127.0133_70PiRem.zip)
[FPP_Logs_20231127.0135_93PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468929/FPP_Logs_20231127.0135_93PiRem.zip)
[fpp-Pi-7.3.5-M1-100000004137ef4b-2023-11-26_17-15-52_93PiRem.zip](https://github.com/FalconChristmas/fpp/files/13468931/fpp-Pi-7.3.5-M1-100000004137ef4b-2023-11-26_17-15-52_93PiRem.zip)

**Comment by ahallber** [comment]
I made an error in my original post...93PiRem is configured running 2 Colorlight controllers for the 512x256 LED Display (P5 - 8x8 module configuration), one Colorlight controller for each half of the display. Updated FPP Version and Hardware  information for this issue are:  

Master (FPP-60PiCon): running version 7.3.5 on a Pi4
Remote (FPP-70PiRem): running version 7.3.5 on a Pi4 - running a Virtual Matrix out the HDMI port for a 896 x 512 LED Display
Remote (FPP-93PiRem): running version 7.3.5 on a Pi4 - running Colorlight controllers out ETH1 (w/ USB to ethernet adapter) for a 512 x 256 LED Display

Also, there is an new error log attached for 70PiRem. Not sure whether or not this corresponds with the time of a display outage as described above.

Our temporary work around is we created a script to restart FPP during the transition from a MP4 Sequence to a MP3 Sequence and put the script in the playlist ...this is working for now.

Happy to do any testing you suggest to provide more information. Thanks much for all you folks do!

[fpp-Pi-7.3.5-M1-10000000a16d6a95-2023-11-28_18-38-14_70PiRem.zip](https://github.com/FalconChristmas/fpp/files/13519387/fpp-Pi-7.3.5-M1-10000000a16d6a95-2023-11-28_18-38-14_70PiRem.zip)

**Comment by bulldozer2003** [comment]
Merry Christmas and Happy Holidays to you as well.

Regarding my own problem I did find #1039  which says remotes will play audio. Now I need to figure out why mine won't.

**Comment by darylc** [comment]
@ahallber Have you tried enabling the ' Ignore Media Sync Packets' setting on the remote having problems?

**Comment by darylc** [comment]
No response
