### ISSUE TITLE
Unable to set FPP time zone

### ISSUE THREAD

**Issue by MikeLebeck** [FalconChristmas/fpp#1674]
Have Kulp 32A-B running FPP.  Upgraded to newest versions below.

In FPP settings on the time option, I do not get a drop down menu for the real time clock and for the time zone.  Both drop downs are blank.  My time looks like it is pulling from the NTP server but does not have an offest.  It is in GMT.

![FPP Seting Time tab](https://github.com/FalconChristmas/fpp/assets/152243665/7627d5fe-fd3d-49df-96c9-e185dde44099)

Help->Troubleshooting also show offset is set to "+00:00"

NTP Peers:    pgrep ntpd > /dev/null && ntpq -c peers

RTC:    sudo hwclock -r -f /dev/rtc0
2023-11-28 00:23:05.115624+00:00

Versions:
Version Info	 
FPP Version:	7.3.5
Platform:	BeagleBone Black
FPP OS Build:	v2023-11
OS Version:	Debian GNU/Linux 11 (bullseye)
Hardware Serial Number:	2213SBB27980
Kernel Version:	5.10.168-fpp
System Boot Time:	2023-11-27 23:53:33
fppd Uptime:	-184:-4
Local Git Version:	a4434ab ChangeLog
Remote Git Version:	a4434ab

**Comment by cpinkham** [comment]
Those dropdowns are filled in with the results of API calls, so it looks like something else is broken.

Try to hit the following URLs (changing the IP for yours):

http://192.168.0.1/api/settings/RTC/options
http://192.168.0.1/api/settings/TimeZone/options

Do those return any errors?  If not, check the apache error logs in the FPP File Manager to see if any errors are listed there.  That could lead to finding the real problem.

**Comment by MikeLebeck** [comment]
Both commands worked:

http://192.168.68.200/api/settings/RTC/options

{"None":"N","DS1305 \/ DS1307 \/ DS3231 (PiCap)":"2","pcf8523 (Kulp \/
Adafruit PiRTC)":"4","pcf85363 (Kulp)":"5","mcp7941x (PiFace)":"3","pcf2127
(RasClock)":"1"}

http://192.168.68.200/api/settings/TimeZone/options

["Africa\/Abidjan","Africa\/Accra","Africa\/Addis_Ababa","Africa\/Algiers","Africa\/Asmara","Africa\/Asmera","Africa\/Bamako","Africa\/Bangui","Africa\/Banjul","Africa\/Bissau","Africa\/Blantyre","Africa\/Brazzaville","Africa\/Bujumbura","Africa\/Cairo","Africa\/Casablanca","Africa\/Ceuta","Africa\/Conakry","Africa\/Dakar","Africa\/Dar_es_Salaam","Africa\/Djibouti","Africa\/Douala","Africa\/El_Aaiun","Africa\/Freetown","Africa\/Gaborone","Africa\/Harare","Africa\/Johannesburg","Africa\/Juba","Africa\/Kampala","Africa\/Khart.
.
.
,"Pacific\/Yap","Poland","Portugal","PRC","PST8PDT","ROC","ROK","Singapore","Turkey","UCT","Universal","US\/Alaska","US\/Aleutian","US\/Arizona","US\/Central","US\/Eastern","US\/East-Indiana","US\/Hawaii","US\/Indiana-Starke","US\/Michigan","US\/Mountain","US\/Pacific","US\/Samoa","UTC","WET","W-SU","Zulu"]

In the Apache error log it is showing the error below multiple times since
I cleared and restarted:

[Wed Nov 29 00:41:26.280195 2023] [proxy_fcgi:error] [pid 1012:tid
2779759648] [client 192.168.68.74:56474] AH01071: Got error 'PHP message:
PHP Notice:  date_default_timezone_set(): Timezone ID 'null' is invalid in
/opt/fpp/www/config.php on line 615'
[Wed Nov 29 00:41:27.636518 2023] [proxy_fcgi:error] [pid 1012:tid
2762974240] [client 192.168.68.74:56476] AH01071: Got error 'PHP message:
PHP Notice:  date_default_timezone_set(): Timezone ID 'null' is invalid in
/opt/fpp/www/config.php on line 615', referer:
http://192.168.68.200/index.php
[Wed Nov 29 00:41:27.848344 2023] [proxy_fcgi:error] [pid 1009:tid
2712618016] [client 192.168.68.74:56472] AH01071: Got error 'PHP message:
PHP Notice:  date_default_timezone_set(): Timezone ID 'null' is invalid in
/opt/fpp/www/config.php on line 615', referer:
http://192.168.68.200/index.php
[Wed Nov 29 00:41:29.061244 2023] [proxy_fcgi:error] [pid 1012:tid
2737796128] [client 192.168.68.74:56476] AH01071: Got error 'PHP message:
PHP Notice:  date_default_timezone_set(): Timezone ID 'null' is invalid in
/opt/fpp/www/config.php on line 615', referer:
http://192.168.68.200/index.php

To load the OS I needed to be on a wired DHCP network (IP 192.168.68.74).
After the OS was loaded I set up my wireless network with DHCP (IP
192.168.68.200) and disconnected the wired network.  Is there something I
need to update to remove the wired network IP?

Mike

**Comment by OnlineDynamic** [comment]
@MikeLebeck is this still an issue on FPP v7.5 or the latest master branch?  If not we will close the issue

**Comment by MikeLebeck** [comment]
Thanks, please go ahead and close.  I ended up reloading FPP with a new
image and the problem did not reappear.
