### ISSUE TITLE
Kiosk mode screensaver or sleep mode for led screen.

### ISSUE THREAD

**Issue by MDickson00** [FalconChristmas/fpp#1676]
Kiosk mode with my 7" official Raspberry Pi touch screen works great, except that the screen never shuts off. My Pi runs 24/7 during show season and I am concerned about screen burn in. Is it possible to add a screensaver or put the screen to sleep after X amount of time with the ability to wake it up with a touch of the screen or mouse movement etc. ?

**Comment by darylc** [comment]
I spent a fair bit of effort trying to make this work, and I just can't @MDickson00

**Comment by MDickson00** [comment]
Thanks for looking into it.

**Comment by dkulp** [comment]
Implemented for FPP8... will need to re-install kiosk mode to get the scripts in place.

**Comment by MDickson00** [comment]
Great news, thanks Dan.
