### ISSUE TITLE
2 FPP instance to same controller

### ISSUE THREAD

**Issue by skipit79** [FalconChristmas/fpp#1677]
**FPP Version and Hardware**: 
Show Player  - FPP 7.3.5 running on Pi 3B+
Tune to player - FPP 7.3.5 running on Pi 4

**Describe the bug and Steps to reproduce**: 
I have two falcon player's running.  One for my show with only the channels and universes for my show and second player for my tune to sign with only the channels and universes for that prop.  Last year on version 6.x I could run both with no issue.  This year, with FPP 7.3.5 my tune two sign is showing some serious delay and jumpiness when panning across the text effect.

**Expected behavior**: 
Last year on v6.x I could run this configuration with no issue, this year it's having some trouble.

**Additional comments**

After some more testing it appears running two FPP instances is affecting my other props that share the same controller, they are all experiencing random behavior when both players are running.  I would like to emphasize I have double checked that the players are broadcasting only the channels and universes applicable to the props the FPP is broadcasting.

[FPP_Logs_20231129.0535 (Show Player).zip](https://github.com/FalconChristmas/fpp/files/13496492/FPP_Logs_20231129.0535.Show.Player.zip)
[FPP_Logs_20231129.0535 (Tune Player).zip](https://github.com/FalconChristmas/fpp/files/13496493/FPP_Logs_20231129.0535.Tune.Player.zip)

**Comment by derwin12** [comment]
Any chance your first pi, in input output setups, channel outputs, is PUSHING data over to the other pi or prop?

**Comment by derwin12** [comment]
Check your outputs on both PI's - make sure they are not both set send data..

**Comment by skipit79** [comment]
> Check your outputs on both PI's - make sure they are not both set send data..

Can you tell me/show me where that option is?

**Comment by derwin12** [comment]
Input/Output Setup
..channel outputs
Only the master should have things set there.
If you need help see the folks on xlightszoom.com

**Comment by cpinkham** [comment]
What happens if you only run the playlist/sequence on one FPP instance at a time?  Does the Tune To act normally?

**Comment by ghormann** [comment]
Closing due to lack of response from OP.   Recommendation is to get assistance vi xlightszoomroom.
