### ISSUE TITLE
wifi dongle on BBB on 7.3.5+ (master) doesn't work on reboot until reinserted

### ISSUE THREAD

**Issue by dartunder** [FalconChristmas/fpp#1686]
This is repeatable.

The ethernet cable is connected to the home router, and the Wi-Fi dongle is plugged in.  No Cape, fresh install, switched to the master branch. Reboot.  The eth0 connection returns and the Wi-Fi does not.  While running, unplug the wifi dongle and reinsert it, and the wifi connects.  

Both connections are to the same network, so when it does connect, the only error I get in the health check is multiple gateways.

I would be happy to help with testing debugging if you can point me where to start looking.

7.x-master-369-g16f8ea7a  (2023-12-02)
BeagleBone Black
v2023-11

[FPP_Logs_20231202.1446.zip](https://github.com/FalconChristmas/fpp/files/13536584/FPP_Logs_20231202.1446.zip)

USB Devices:    sudo lsusb -v
can't get debug descriptor: Resource temporarily unavailable

Bus 001 Device 003: ID 0bda:b812 Realtek Semiconductor Corp. RTL88x2bu [AC1200
Techkey]
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.10
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x0bda Realtek Semiconductor Corp.
  idProduct          0xb812 RTL88x2bu [AC1200 Techkey]
  bcdDevice            2.10
  iManufacturer           1 Realtek
  iProduct                2 USB3.0 802.11ac 1200M Adapter

**Comment by dartunder** [comment]
I've ordered a different adapter that was reported to work correctly.  I will report the results in a few days.

**Comment by darylc** [comment]
@dartunder how did you go?
