### ISSUE TITLE
Twilio plugin versions fpp v.4.6.1

### ISSUE THREAD

**Issue by marciuliani** [FalconChristmas/fpp#1690]
Does anybody have a copy of the older plugin version?  I accidentally updated the plugin and broke it on my working matrix

**Comment by marciuliani** [comment]
I believe the version was 2.5 which was working

**Comment by ghormann** [comment]
I'm not sure the plug in has been updated in a while...  The Git Repo shows more than 2 years.   All the source code is there if you want to take a look.   Hash 5d6533e25b8e56db511ed6fa0355763d8f94e2c3 is show to have worked with fpp before 6.0. 
https://github.com/FalconChristmas/FPP-Plugin-TwilioControl

**Comment by patdelaney** [comment]
We restored the folder from one of his other FPP's
