### ISSUE TITLE
Scheduler-List and Preview are not the same

### ISSUE THREAD

**Issue by Anykan** [FalconChristmas/fpp#1691]
Hi,

I use the FFP on an Raspberry Pi.
I have the softwareversion 7.3.1 and i used the Raspberry Pi Imager to creat the SD Card.

I make in the scheduler one entry
![schedule](https://github.com/FalconChristmas/fpp/assets/10184152/db14b343-df79-489f-ace1-f3838f107425)

So now comes the problem.
If i take a look to the Preview the list is longer than i choose. The schedule is up to the 6th jan. and  don´t stops at the 9th dec.
![list](https://github.com/FalconChristmas/fpp/assets/10184152/5926ddde-fb7b-40f4-a6d1-ff85067fe14e)

If i make a second sequence, begin from the 10th dec, the first and the second are parallel in the List
![schedule2](https://github.com/FalconChristmas/fpp/assets/10184152/b6b7f246-108c-40c3-a1e3-db1a36e797c1)
![list2](https://github.com/FalconChristmas/fpp/assets/10184152/45e5377c-75fa-42fe-9cbe-535db479556f)

**Comment by dkulp** [comment]
Your end years are 2028.   Why would it stop on Dec 9th, 2023?

**Comment by Anykan** [comment]
LoL sorry i will try it again, but why is it defailt 5 years later

**Comment by Anykan** [comment]
Yeah it was the Problem, i didnt see that is 2028
