### ISSUE TITLE
Backup files being created every one or two seconds - filling up SD card

### ISSUE THREAD

**Issue by PLLaberge** [FalconChristmas/fpp#1694]
**Version Info:**

FPP Version: | 7.3.5
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2023-11
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 1000000026a501ce
Kernel Version: | 6.1.21-v7l+
System Boot Time: | 2023-12-03 16:19:23
fppd Uptime: | 53:47
Local Git Version: | a4434ab ChangeLog
Remote Git Version: | a4434ab

**Issue**
~/media/config/backups is filling up with backup files being created every second or so as shown below.

-rw-r--r-- 1 fpp fpp  575772 Dec  3 17:07 MasterFPP_all-backup_v7_20231203170749.json
-rw-r--r-- 1 fpp fpp  575772 Dec  3 17:07 MasterFPP_all-backup_v7_20231203170751.json
-rw-r--r-- 1 fpp fpp  575772 Dec  3 17:07 MasterFPP_all-backup_v7_20231203170753.json
-rw-r--r-- 1 fpp fpp  575772 Dec  3 17:07 MasterFPP_all-backup_v7_20231203170754.json

Over the last couple of days, 25,710+ files were created, consuming 14,492,360  bytes. I'm able to delete them, but I have to keep an eye on this before the 32G SD card fills up. 

This is a bare install using 7.0, which I then upgraded to the latest version. I only run 3 add-ins on this machine: Big Buttons, BRP Voting, and Falcon Hardware Monitor.  It is running as Master. While I am seeing backup files being created in another 7.3.5 install that I am running as a backup (in Remote mode), these are less frequent, and based on what I'm seeing on other devices, normal, as shown below.

-rw-r--r-- 1 fpp fpp 535303 Dec  2 12:21 YardMaster_all-backup_v7_20231202122109.json
-rw-r--r-- 1 fpp fpp 535334 Dec  2 16:43 YardMaster_all-backup_v7_20231202164319.json
-rw-r--r-- 1 fpp fpp 535334 Dec  2 23:26 YardMaster_all-backup_v7_20231202232614.json
-rw-r--r-- 1 fpp fpp 535334 Dec  3 13:26 YardMaster_all-backup_v7_20231203132625.json
-rw-r--r-- 1 fpp fpp 535334 Dec  3 13:33 YardMaster_all-backup_v7_20231203133356.json   

Log files attached.
[FPP_Logs_20231204.0139.zip](https://github.com/FalconChristmas/fpp/files/13541019/FPP_Logs_20231204.0139.zip)

Paul.

**Comment by ghormann** [comment]
Closing. after creating and relating issue to correct repo.

**Comment by cpinkham** [comment]
Can we keep this open, we should not let this happen just because something is saving a setting multiple times per minute.  We need limits on the number of backups and the ability to delete them in bulk in the UI.ChrisOn Dec 4, 2023, at 2:33 PM, Greg Hormann ***@***.***> wrote:﻿
Closed #1694 as completed.

**Comment by jaredb7** [comment]
That's correct, there shouldn't be that many backups kept even if something is changing every second.

The hardcoded limit is 45 then it should be deleting the oldest to stay under this limit. I'll investigate more in a couple hours when I get few moments.

**Comment by PLLaberge** [comment]
Letting you know that the developer of the plug-in determined the cause of the issue. Both the backup creation (and it turns out an associated memory allocation issue) were resolved.

Appreciate you looking into this.

**Comment by jaredb7** [comment]
No problems, I did see the author made some changes. There was a bug though that prevented deleting old backups which I fixed on the FPP side so we don't end up thousands of files.

Also made some changes to keep only 5 recent backups when changes are triggered through a specific API endpoint.
