### ISSUE TITLE
PHP version and launchctl errors using macOS install script

### ISSUE THREAD

**Issue by voik** [FalconChristmas/fpp#1695]
_FPP Version and Hardware:_ 
FPP Version 7.x running on M1 Mac Mini, macOS Ventura 13.2.

New computer, staring with a fresh blank slate. Installed homebrew and ran the shell script to install FPP on macOS. After the script is "complete," the web interface did not load. Instead the browser gave a parsing error for some php file missing a closing bracket.

So I started hunting through the output and saw a bunch of "file not found" during PHP configuration. The PHP version in the shell script is 8.2, but homebrew installed 8.3. Changed the version in the script to 8.3, deleted the installed FPP files and folders, re-ran the script, and ran `% brew services restart php` The web interface loaded and seemed OK, but FPPD would not start. Dug a little deeper through the output and found launchctl was unhappy loading the fppd plist. Got the oh-so-helpful message "Load failed: 5: Input/output error" Huh, no kidding, Captain Obvious... Conferred with the man pages and Doctor Google, but Nurse Practitioner reddit had the answer: 

[https://www.reddit.com/r/MacOS/comments/kbko61/launchctl_broken/](https://www.reddit.com/r/MacOS/comments/kbko61/launchctl_broken/)

Obtained my user ID:

`% id -u <username> `

Then unload, enable, load, and start:

```
% launchctl unload -w ~/Library/LaunchAgents/falconchristmas.fppd.plist
% launchctl enable user/<UID>/~/Library/LaunchAgents/falconchristmas.fppd.plist
% launchctl load -w ~/Library/LaunchAgents/falconchristmas.fppd.plist      
% launchctl start falconchristmas.fppd
```

Now FPP is running as expected and everybody seems to be happy. PHP 8.3 appears to work fine. It is unclear if the launchctl gymnastics is a new "feature" from Apple or if this was a one-off. Maybe things got mucked up with my dirty un/re-install. Regardless, the info is here for reference.

It is understandable Mac compatibility is far from the top priority. Just thought I'd share this  in case anyone else finds it helpful.

**Comment by darylc** [comment]
@voik Looks like this might have been fixed by this commit? https://github.com/FalconChristmas/fpp/commit/fb1525e73e8c7739d7eee8f2f2d1e9ccd0bcab3b

**Comment by voik** [comment]
Sorry, I was out of town and off the grid last week. Yes, it looks like the issue has been resolved, and much more has been tidied up.

Thank you for your work on this project. The way we spread the holiday joy would not be the same without your efforts. 

Best wishes,

voik
