### ISSUE TITLE
Scheduler - Commands running a script not going into schedule

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1697]
**FPP Version and Hardware**: 
Example: *FPP 7.3.5 on RPI zero 2 w

**Describe the bug and Steps to reproduce**: 

1. Go to scheduler
2. Create an entry to run a command to 'Run Script'  (in my case the command takes arguments in case that makes a difference)
3. Enable the line and save
5. Now click on the preview of Schedule and its says 'Nothing Scheduled'  (and nothing is running at the scheduled time either)

**Expected behavior**: 
Created schedule entries to appear in the schedule preview 

**Additional context**: 
Attached screenshots
![Screenshot 2023-12-04 235729](https://github.com/FalconChristmas/fpp/assets/68251154/a16143ed-5095-42cf-b242-44a630ce63e4)
![Screenshot 2023-12-04 235755](https://github.com/FalconChristmas/fpp/assets/68251154/8c1c5fdb-2f59-4827-a588-880cf9313b04)

**Comment by derwin12** [comment]
Wonder if perhaps you need to make end time 11:31 PM so it can run?

**Comment by cpinkham** [comment]
The scheduler is disabled on FPP systems running in Remote mode.  We need to hide that menu entry on Remote systems.ChrisOn Dec 4, 2023, at 6:08 PM, Daryl ***@***.***> wrote:﻿
Wonder if perhaps you need to make end time 11:31 PM so it can run?

**Comment by OnlineDynamic** [comment]
@cpinkham agree - I can confirm this was in remote mode with the UI set to basic - it's definetly confusing - hadn't realised scheduler was diabled in that mode

**Comment by OnlineDynamic** [comment]
I have seen the 'Remote Run Script' command on the player so will use that instead of running commands directly on the remotes...

It would be good if the dialog box on the 'Remote Run Script' auto populated the names of available scripts on the remote like it does on the 'Run Script' command when running locally.

**Comment by cpinkham** [comment]
In the master code branch, the Scheduler menu has now been hidden on Remote FPP instances and the Scheduler status boxes on the main status page are hidden as well in that scenario.  I made a note about seeing if we can populate the Remote Script dropdown in the FPP Command Editor.

Closing this ticket.
