### ISSUE TITLE
Plugin callback for playlist saved/created/edited

### ISSUE THREAD

**Issue by freman** [FalconChristmas/fpp#1699]
**Describe the solution you'd like**
The ability to run a script/plugin on playlist update (save/create/edit)

**Describe alternatives you've considered**
Polling fppd, listing all the playlists, running my check scripts and website update.

**Additional context**
Personally I'd like to have some tooling run checks and update a 'static' website whenever I update a playlist, currently I'm doing it via crontab but it seems wasteful to poll for playlist changes when they may happen 4-5 times a day some days or 2-3 times a week otherwise.

**Comment by darylc** [comment]
fppd does not get notified when a playlist gets changed, the UI just changes the file on the disk.  There is no infrastucture in the UI to do any sort of callback to a plugin.  I'd suggest polling fpp every hour or similar.
