### ISSUE TITLE
Pause-All

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1700]
Feature Request

It would be handy to have a checkbox on the Status page at the top that would disable scheduler and prevent FPPD from restarting. Kind of a stop-all when helping someone test so it prevents schedules from starting and such.

**Comment by cpinkham** [comment]
I'm not sure why this would be re-enabled.  I ran a quick grep of the source of both FPP and xLights and don't see what would be overriding the DisableScheduler setting when FPP Connect uploads.  Are you sure that something isn't manually starting the playlist?

**Comment by McCoyCOREUSA** [comment]
I guess I'm thinking when I forget to have someone turn off the schedule, or if I don't notice at first that it's running or scheduled. Once notices, we go there and disable. In testing while the show is running, obviously causes issues. Someone will come in and the show is not playing. We do something and FPPD starts for some reason (setting change, etc) and the show begins. They had it manually stopped when we started, so I thought the show wasn't running or scheduled in the first place.

**Comment by darylc** [comment]
Checked with dkulp, no action required on this one
