### ISSUE TITLE
Add the ability to add sequences to a playlist directly from FPP File Manager

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#1702]
**Is your feature request related to a problem? Please describe.**
Add a quick way to add multiple sequences to a playlist without having to go through the popup to add each one.

**Describe the solution you'd like**
Add a new 'Add to Playlist' button on the FPP File Manager Sequences tab.  After selecting one or more sequences, the script would prompt for a playlist or allow specifying a name for a new one.  The code would check each sequence and add it as a Sequence type if no media file could be found or a 'Both' type if a media file could be found using the media name in the .fseq or by finding a media file with the same base name.  Another option would be to have a checkbox on the playlist popup which would specify that the selected playlist would be used as a template when creating a new playlist.  The Lead In and Lead Out of the template playlist would be copied to the new playlist and the main section of the new playlist filled in with the selected sequence(s).

**Comment by derwin12** [comment]
That is what fpp connect is for :-)
