### ISSUE TITLE
Status Page, keep Elapsed/Remaining time in header

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1708]
FPP 7.3.3 on Pi
Tested in Chrome and Edge on Win 10

**Describe the solution you'd like**

It would be nice if the elapsed and remaining time counters on the status page were to stay with the play control buttons above the scrolling list and not scroll with the list.  When you have a long playlist and you're trying to watch the active item far down on the list, you can't see the counters at the top of the list because they're scrolled out of view.

**Comment by cathelest** [comment]
I second this, been driving me nuts this year trying to time a jump in the playlist.

**Comment by OnlineDynamic** [comment]
I have now implemented this in the latest master branch of fpp8
