### ISSUE TITLE
PiFace Detection is broken in v1.5/v1.6

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#171]
We set output 207 and read from 215 as a check, but this doesn't appear to work anymore, so we need to test just reading from 207 instead.

Code is in scripts/functions in detectPiFace()

**Comment by rudybrian** [comment]
False alarm: http://falconchristmas.com/forum/index.php/topic,3278.msg35821.html#msg35821

**Comment by cpinkham** [comment]
Thanks for reporting back.
