### ISSUE TITLE
homepage main demo link is USA only

### ISSUE THREAD

**Issue by ssbarnea** [FalconChristmas/fpp#1710]
I was quite unpleased to see that [falcon player main](https://falconchristmas.github.io/) page advertise a demo page on its first paragraph, one that does not play for any user outside USA...

![](https://sbarnea.com/ss/Screen-Shot-2023-12-11-14-08-06.12.png)

And I am now in UK, not another problematic location.

Basically getting rid of ABC.com would seem like a good idea.

**Comment by darylc** [comment]
The link is just meant to illustrate that FPP is used by many Great Christmas Light Fight contestants, not link to videos or provide any demo etc.
