### ISSUE TITLE
RSync to a target that isn't FPP

### ISSUE THREAD

**Issue by badbread** [FalconChristmas/fpp#1711]
Just got on the FPP train and am absolutely loving it. 

Would it be possible to add a way to backup the FPP folders (Settings, sequences, media, etc...) to a host of my choosing. In my case it's a Synology NAS that supports rsync. I only have 1 FPP in use so backing up to another FPP isn't possible. I am able to setup rsync via SSH on the FPP with a CRON job to schedule it but it would be awesome if there was an option in the UI to do this.

Thank you!

**Comment by darylc** [comment]
There are no plans to implement this as a FPP feature, please use cron etc.
