### ISSUE TITLE
Strange log behaviour

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1714]
**FPP Version and Hardware**: 
FPP 7.4 running on RPI4

Been experienceing some crashes and whilst invetsigating I have noticed that /var/log/syslog and /var/log/daemon.log seem to be both populating with the same content.

2 questions from this....

a) should they both be doing the same thing as they had been getting really big with content and having 2 makes the filesystem fill up twice as fast (think I found the reason they were filling (which I think was a different issue to the crashing I'm still seeing)
b) should there be log rotation happening in general across all the log files?

**Comment by darylc** [comment]
This look resolved in fpp 8
