### ISSUE TITLE
Renaming playlist using cog icon dialog creating new playlist rather than renaming

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1715]
**FPP Version and Hardware**: 
FPP 7.4 running on RPI4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to a playlist (open it)
2. Click on the cog (settings icon)
3. Change name of playlist and click save
4. Go back to list of playlists and you will see a new playlist with new name as well as one with the original name

**Expected behavior**: 
I would expected editing the name just to change the playlist name

**Comment by cpinkham** [comment]
This is working as intended.  It is a 'Save As' if you change the name inside that popup.  If you want to really rename, you use the 'Rename Playlist' option under the Playlist Actions dropdown.
