### ISSUE TITLE
Batch render enhancement

### ISSUE THREAD

**Issue by jlwright325** [FalconChristmas/fpp#1716]
When batch rendering, if you have made any changes in your layout and you are unaware that it will impact an  older sequence, there is no way to cancel the batch render. 

When prompted with the information that groups, props, etc. are missing. Allow the capability to cancel the batch render.

**Comment by darylc** [comment]
@jlwright325 FPP has no batch render function.

**Comment by jlwright325** [comment]
> @jlwright325 FPP has no batch render function.

Yes, apologies. Bad idea to try and function on little sleep. Thanks for closing this out and I will post the request on xLights.
