### ISSUE TITLE
Remote player hangs when starting sequence with audio #bug

### ISSUE THREAD

**Issue by pdobrien** [FalconChristmas/fpp#1717]
**FPP Version and Hardware**: 
FPP 7.4 on Kulp K16A-B and K32 with BBB

**Describe the bug and Steps to reproduce**: 
1) Configure a K16A-B as player and K32 as remote
2) Upload sequences with and without an associated audio track to both using FPP
3) Play the sequence without an audio track.  It works fine and the player and remote are in sync
4) Play the sequence with audio track.  The player plays the sequence fine, but the remote does not play the sequence.  It hangs on "Waiting for MultiSync commands".  Last log entry is "[Sync] /opt/fpp/src/MultiSync.cpp:2365: OpenSyncedMedia(Takin Care Of Christmas.mp3)"

**Expected behavior**: 
Both sequences should play on both player and remote.

**Additional context**: 
The remote has a VAST-FM transmitter hooked up, but this seems to be functioning normally (broadcasts the IP address announcement on boot) so I don't think it's related.  Other things I have tested/tried:
- removing the apostrophe from the media file names (anti-Irish programming bias is real!)
- removing the VAST-FM transmitter / changing the audio output device to the internal audio jack rather than USB
- enabling unicast to the remote
- updating to the lastest FPP

**Additional Attachments**
[FPP_player_Logs_20231215.0433.zip](https://github.com/FalconChristmas/fpp/files/13681005/FPP_player_Logs_20231215.0433.zip)
[FPP_remote_Logs_20231215.0433.zip](https://github.com/FalconChristmas/fpp/files/13681006/FPP_remote_Logs_20231215.0433.zip)

**Comment by pdobrien** [comment]
More detail: I was able to get this working by disabling RDS in the VAST-FM plugin.  So it appears to be a plugin issue, but still an FPP bug since FPP shouldn't allow a plugin to silently and irrecoverably wedge the system to the point a reboot is required.

**Comment by darylc** [comment]
Glad you found a workaround.  Unfortunately due to the nature of plugins they can very much wedge fppd with bad code.  This is the tradeoff for an extremely flexible plugin environment to allow plugins to have a wide range of functions.
