### ISSUE TITLE
FPP does not play MP4 video on remote when playing a sequence (not a playlist)

### ISSUE THREAD

**Issue by jayg7800** [FalconChristmas/fpp#1718]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.3.5 on Raspberry Pi 4 (both player and remote)

**Describe the bug and Steps to reproduce**: 
1. Set up fpp remote with a projector/tv attached to Raspberry Pi 4.
2. On Player, choose any sequence that has a matching-named MP4 video on the remote.
3. Sequence will play, but MP4 video will not play on remote.

**Expected behavior**: 
The remote fpp should play MP4 video which has the same filename (minus extension) as the sequence and audio files.

**Additional context**: 
This works properly when playing a PLAYLIST, but does not work properly when playing a sequence directly.

**Comment by pdobrien** [comment]
Sounds like it may be related to previous bug #1717

**Comment by dkulp** [comment]
On the master, is there an appropriate mp3/mp4?    When you select the fseq file and start it, does the master properly find a media to go with it and start that media?

**Comment by jayg7800** [comment]
I cannot reproduce this issue after upgrading to FPP 7.4.1.  I'll open a new case if this re-occurs in the future.  Thanks!
