### ISSUE TITLE
Unable to add a virtual matrix

### ISSUE THREAD

**Issue by fovea1959** [FalconChristmas/fpp#1719]
*FPP 7.4 running on rPi 2*

**Describe the bug and Steps to reproduce**: 
Bring up a fresh image. Try to configure a virtual matrix output. When you go to save the virtual matrix, you get the message "Output type must be selected on row 1".

**Expected behavior**: 
Should allow me to configure the virtual matrix.

**Additional context**: 
Restoring a configuration from an earlier version that contained a virtual matrix works fine.

**Additional Attachments**
[FPP_Logs_20231216.0052.zip](https://github.com/FalconChristmas/fpp/files/13690893/FPP_Logs_20231216.0052.zip)

![image](https://github.com/FalconChristmas/fpp/assets/5349196/74c7e358-65b2-4f45-becc-bbc102652f15)

**Comment by cpinkham** [comment]
You have to select something off the dropdown box and configure the Virtual Matrix.  Once you select a type off the dropdown box then the dropdown will go away and it will show you are creating a Virtual Matrix and will have additional inputs to select the size of the Virtual Matrix and which HDMI/framebuffer device will be used.

This dropdown box should show "Select a type" by default which forces you to pick something.  I'm not sure how it is showing Virtual Matrix there for you.

**Comment by Poporacer** [comment]
@fovea1959 did this resolve your issue? Please let us know.. Thanks

**Comment by fovea1959** [comment]
It is still flaky, but just retrying configuration works, so I'm fine.

**Comment by cpinkham** [comment]
We should be able to prevent this error if we either skip rows without a selected type or don't enable the save button until something changed.  The former would be a lot easier than tracking changes everywhere.
