### ISSUE TITLE
Loss of Internet causes delay between sequences & periodic hault of playlist

### ISSUE THREAD

**Issue by EricLangness** [FalconChristmas/fpp#1722]
This past weekend our Internet went out for about an hour and when I bumped into FPP (version 7.4 on Pi 4 Model B) it was continually trying to reach the Internet for FPP Remote Monitoring Plugin.  I simultaneously had an atypical 3-5 second delay between sequences and several times FPP just stopped the playlist entirely.  An hour later when our Internet was restored by our ISP, it instantly worked as normally expected.  I'd suggest that when FPP loses a live connection to the Internet it perhaps temporarily disables any plugin's or other features that require Internet use for greater stability.  If a log is needed, I'm happy to provide but uncertain which one would be helpful to review.  

Thank you developers on the great software I've come to enjoy!

**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by darylc** [comment]
please attached fppd.log and tell us the timestamp of the time the problem occurred, otherwise we have nothing to go on.

**Comment by darylc** [comment]
No response, no information
