### ISSUE TITLE
UI Bug when accessing same FPP instance from PC browser and phone

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1727]
**FPP Version and Hardware**: 
FPP 7.4 running on RPI4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to fpp ip/url on PC (windpows/firefox) navigate and interact as normal
2. Connect Phone to same network (via wifi) that the RPI is physically wired on to
3. Navigate to same fpp ip/url on phone (Samsung S22 Ultra)
4. Stop playlists, start playlists etc (general interaction) (which works fine)
5. Go back to PC and refresh the page to get latest fpp status
6. The UI then says FPP isn't running (despite the fact it is and lights still happily playing the current sequence)
7. The "FPP Mode" at the bottom of the screen has neither mode selected (see screen shot)
8. Chnaging the mode  back to 'Player' at the bottom of the screen refreshes the browser window then correctly shows the current status (2nd screen shot shows what it looks like after setting the mode back)

**Expected behavior**: 
The UI to show the current status and not get confused into showing FPPD as down when it isn't

![error_state](https://github.com/FalconChristmas/fpp/assets/68251154/405c69fa-1599-4e94-bc2f-4813a1535b26)
![corrected_state](https://github.com/FalconChristmas/fpp/assets/68251154/0b7d5927-a3c5-4992-8b7b-aa1f8c824d1f)

**Comment by cpinkham** [comment]
This works fine for me.  The web browser on the PC side works correctly whether I leave it as-is or reload/refresh it manually.  The PC follows along with the start/stop done via mobile or another browser.  The PC browser automatically updates even when I change the mode back and forth between Player and Remote on the mobile browser.

If you can reproduce this, does the PC browser not show the changes for you as you are starting/stopping playlists from the mobile browser?  The PC browser should be updating it's status automatically, you shouldn't have to refresh.

**Comment by OnlineDynamic** [comment]
Thought this was phone related but this evening the player UI in the browser managed to forget its fpp mode again and I haven't put my phone on the show network.. and UI is only open in one firefox tab...

Using the drop down to set it back to player mode the UI refreshed and showed the correct status again - what could be causing it to loose the mode?

**Comment by cpinkham** [comment]
If it happens again, check the web browser developer UI to see if the JSON returned for the status API call is valid.  The JSON contains the current mode and other info to update the screen.  Also check the browser's developer console in case there was an error logged there.

**Comment by OnlineDynamic** [comment]
Browser debug console showing:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help https://xhr.spec.whatwg.org/#sync-warning jquery-latest.min.js:2:79716
Source map error: Error: request failed with status 404
Resource URL: http://192.168.0.100/js/jquery.jgrowl.min.js
Source Map URL: jquery.jgrowl.map

**Comment by cpinkham** [comment]
None of that applies.  If you go to the Network tab, you should be able to see the calls where it is fetching the 'status' url and look at the result code for that (should be 200) and the data returned to see if it is invalid.  You can copy/paste the response here or attach it as a file if you can't read the json.

**Comment by OnlineDynamic** [comment]
![Screenshot 2023-12-23 161216](https://github.com/FalconChristmas/fpp/assets/68251154/1fdba422-11da-45f9-962b-88d77b3e71da)
manage to capture this when it just happened again

**Comment by ghormann** [comment]
That screenshot suggest you are having a networkwork issue at this time.  For example, it took 21 seconds to load 43 bytes of data.   I don't believe this is related to fpp code.

**Comment by OnlineDynamic** [comment]
Hi - it would appear to be a network related but you will see in this screenshot as soon as I manually reset the fpp mode to player using the UI the error state which looks like network issues immediately clears and response times go back to around 100ms...
![Screenshot 2023-12-28 232819](https://github.com/FalconChristmas/fpp/assets/68251154/35502d16-32f2-4917-845d-a7497f3edd31)

you can see the point I changed the mode  'fppMode' appears in the File column of the network debug

**Comment by jaredb7** [comment]
When the UI on the PC is reporting FPPD is stopped, can you still start/stop the playlist from the phone?

If you can reproduce this again, open another tab and go to http://192.168.0.100/api/system/status
Attach the contents/response as txt file and attach here, Don't change the player mode like you've been doing and attach your logs after waiting say 10-15 seconds (timing is not crucial, just need some timeouts to expire).

I hazard guess the response will look like this, which would indicate FPPD is not running (hence no player mode and the warning). But you mentioned the lights still run regardless so it has to be running.
When you change mode, even if your selecting the same mode, FPPD is being restarted which is fixing whatever the issue is.
![image](https://github.com/FalconChristmas/fpp/assets/799998/3aa3c6c6-879f-4dcc-ab43-4dd5f8b070d7)

**Comment by darylc** [comment]
Any update @OnlineDynamic ?

**Comment by OnlineDynamic** [comment]
Nope - Now out of show season I'll try to test on my show network setup again and see if I can reproduce - perhaps its because the phone is on wifi network with same subnet as the fpp show player but my PC connects from a different subnet via some traffic routing...

**Comment by darylc** [comment]
@OnlineDynamic What do you want to do with this issue?

**Comment by OnlineDynamic** [comment]
Going to close for now and will see behaviour on new home network and fpp v8 and see if I can still recreate
