### ISSUE TITLE
FPPD won't start without reboot after changing command preset.

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1730]
**FPP Version and Hardware**: 
FPP master branch (7638be7)

**Describe the bug and Steps to reproduce**: 
Edit a command preset.  (all I was doing was changing the start channel of an existing start effect command)
Save it.
Save the command presets list.
Yellow bar appears for required restart of FPPD.
Hit button to restart.  Go back to main status page.
Red bar stating abnormal conditions, FPPD not running.
Try to restart FPPD, still no success.
Reboot FPP and it starts properly.

**Expected behavior**: 
It should save the command preset list and FPPD should restart properly.

fppd logs attached.

[fppd_stop.log](https://github.com/FalconChristmas/fpp/files/13723080/fppd_stop.log)
 attached.
[fppd_start.log](https://github.com/FalconChristmas/fpp/files/13723077/fppd_start.log)
[fppd_restart.log](https://github.com/FalconChristmas/fpp/files/13723078/fppd_restart.log)
[fppd.log](https://github.com/FalconChristmas/fpp/files/13723079/fppd.log)

**Comment by Poporacer** [comment]
I don't see anything odd in the Logs and I can't replicate it either. Can you uninstall FPPMon and the Home Assistant plugins (and any others that you might have) and see if you get the same behavior? If so, note the time that you clicked on the Re-Start FPP and let it sit for a while to see if it eventually comes back on. Do you have any outputs enabled that are not actually online? If it doesn't come back on, then note the time that you rebooted it and post the logs again so we can look at the times you took those actions. Thanks

**Comment by Jchuchla** [comment]
I actually think the problem is not specifically related to command presets.  I've been having more persistent problems restarting FPPD on my master.  I've got another ticket #1743 that covers this.  It seems to be any time I restart FPPD.  Now that the show season is over, I'll have more time to troubleshoot this. I have 4 plugins installed.  FPPMon, Big Buttons, Crontab Editor and Remote Falcon.  I'll try disabling them one at a time to see if this helps the FPPD restart issue.

**Comment by Jchuchla** [comment]
I just followed the advice and disabled FPPMon and rebooted.  I then tried restarting FPPD from the UI about 5 times and it restarted properly and resumed the schedule every time.

**Comment by Poporacer** [comment]
Thanks, there have been a couple issues that appear to be FPPMon related but we haven't been able to verify if that is the actual cause yet....Keep us informed.

**Comment by Jchuchla** [comment]
Will do. And I’m happy to do further testing. I’ve got this FPP instance driving a static display for the next few months.

**Comment by cpinkham** [comment]
I believe this is the same issue as #1743 which I added to the v8.0 queue and will be looking into.  Closing this ticket as a duplicate.

**Comment by Jchuchla** [comment]
I agree.  I think I didn't realize at the time that the problem was actually broader than just after the command preset changes.
