### ISSUE TITLE
Diskspace is still being consumed and runs out within a week.

### ISSUE THREAD

**Issue by JMHaro** [FalconChristmas/fpp#1732]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:   7.4-3-gd3702c26 running on Pi 3B

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Just constantly seeing my memory being consumed until it runs out of space.  I'm attaching a log where I was recording the memory usage about every day and most of the time, several times in a single day.  I've been having to flash a new SD card about once a week just to be able to keep my show playing during the season.

**Expected behavior**: 
Expect the memory usage to stay relatively stable at least long enough to make it through the season.

**Additional context**: 
If my issue is unique, I'm willing to work with someone to try to find out why this is happening.

**Additional Attachments**
I couldn't supply the log files.  The current file is 42Megs, your limit was 25MB.  If there is a way to send it to you let me know.  Even a previous crash file, is over 40MB so I can't send that one.

[FPP Memory Issues.txt](https://github.com/FalconChristmas/fpp/files/13747412/FPP.Memory.Issues.txt)

**Comment by JMHaro** [comment]
I tried splitting up the log files.  See if these will update.  The first one is everything except for the fppd.log file.  That one file is over 1GB is size.  I'll try to upload it in the second zip file but it's right at 25MB so not sure if it will go.
[FPP_Logs_20231222.0058-1.zip](https://github.com/FalconChristmas/fpp/files/13747464/FPP_Logs_20231222.0058-1.zip)
[FPP_Logs_20231222.0058-2.zip](https://github.com/FalconChristmas/fpp/files/13747467/FPP_Logs_20231222.0058-2.zip)

**Comment by cybercop23** [comment]
Were you in the Zoom room last night where they cleared sysvar and deamon.log? If so... something is happenig within your setup that's causing those files to get extremly large. You can set up a scheduler to truncate them, but you need to figure out what's causing it in the first place. 
Can you go into Content Setup - File Manager, Logs and choose "tail" for those large files and post a screen shot here, vs those large files?

**Comment by JMHaro** [comment]
No I wasn't on the Zoom last night but those are the files I'm seeing getting very large also along with the FPPD one that was in the log files I sent yesterday.  I'm assuming you mean the /var/log/syslog file.  My syslog currently is at 3.48GB.  To me the daemon.log and syslog files almost look exact.  I've posted screen shots of both.  I don't see the daemon.log file show up in the File Manager.
![syslog](https://github.com/FalconChristmas/fpp/assets/3945942/eafbc2ee-d6b2-4444-b3e3-903e3899d536)
![daemon log](https://github.com/FalconChristmas/fpp/assets/3945942/d26b1215-4d16-44f6-9c42-f6c7730d1426)

**Comment by bcarriveau** [comment]
are you really sending UDP to all them fpp controllers on your outputs and not using Multisync on purpose?

**Comment by JMHaro** [comment]
That was the way I was told at one time to do it.  I'm open to doing it how ever would be the best way.

**Comment by derwin12** [comment]
Your fpp devices .. in xlights on the controllers tab, chance "active" to "xlights only".  They should NOT have a check mark on the above screen grab. In your case, only falcons would need checkmarks. The FPP controllers would be in remote mode as well.

**Comment by bcarriveau** [comment]
> Your fpp devices .. in xlights on the controllers tab, chance "active" to "xlights only". They should NOT have a check mark on the above screen grab. In your case, only falcons would need checkmarks. The FPP controllers would be in remote mode as well.

without knowing for sure i was just wondering with he was going both and it was causeing errors? im no log reader but i didn't peek at his config and noticed all these fpps are being sent udp instead of rsync with multisync.

**Comment by JMHaro** [comment]
I set them all an inactive but now none of the FPP's are displaying anything.  I even uploaded all the fseqs to all of them and still nothing displayed.

**Comment by JMHaro** [comment]
If there is a way that I could schedule a cleanup of backup log files I would appreciate getting the instructions on how to do that (I looked for any scripts or plugins but didn't see anything).  I was up to 66% disk usage.  This time I did see that the daemon and syslog had been backed up so I deleted the backup files and that got be back to 27%, so at least that was easier than rebuilding a new SD card again.  Unless there is an easy fix for my issue, I could at least do the cleanup of log files to get me through the rest of this season, and then hopefully get some help to see if there is a different way I should be sending my data to the other FPP remotes.

**Comment by JMHaro** [comment]
OK, I was out and only just got home so the show is running right now.  I'll try this in the morning.  Thanks,

**Comment by JMHaro** [comment]
I wasn't able to make changes on the 25th, but on the 26th, I turned on the "Send MultiSync Packets" and then set all the FPP's to non active.  At that time I it was at 50% used at 10:20 AM.  At 9:00 PM it was at 51%.
I just now checked it at 9:00 PM and it's at 50%.  So if it holds here I will be very happy and can live with this for the rest of the season.

**Comment by Poporacer** [comment]
Has this been resolved? If so, please close or provide additional information. Thanks

**Comment by JMHaro** [comment]
I am closing issue.  It did seem to keep the memory consistent where it was at for the remaining last week.  Thank you.
