### ISSUE TITLE
Locking timecode hours to specific sequences rather than automatically incrementing in playlists.

### ISSUE THREAD

**Issue by jasejman2000** [FalconChristmas/fpp#1733]
Hi there. Love the timecode output. We are using ARTNET timecode to sequence our whole display with ONYX and are also using UDP packets to control specific cuelists within ONYX as well. Works extremely well (our show is https://YouTube.com/@wattsuphux). Only bummer is when you randomise a playlist or play single sequences the hours meter option increments in a different manner for each sequence. It's fine when you are always using the same playlist but if I add anything to the playlist (a pause or other command) the timecode hours meter increments when we don't want it too. 

Obviously for the sync with our ONYX desk for each specific song we are using the hours increment to tell ONYX which set of cues to use.

In addition to the wonderful SMPTE and ARTNET timecode feature you have, could you maybe add an option to hard-lock the hours meter to specific sequences. So for example the sequence named Sequence A always starts at 01 hours no matter what playlist it is in. And the one named Sequence B always starts at 02 hours no matter what playlist it is in. That means that no matter how it is played or where it is played in a playlist it will always have the exact same hours code so that lighting software cues can be locked to a specific sequence. Even if we actually had to specify it for all sequences otherwise it is just 00 hours that would be perfect. 

Hope that makes sense.

Jason.

**Comment by darylc** [comment]
![image](https://github.com/user-attachments/assets/4d958169-543c-49cb-a2ed-967f686f0f2a)

If you want to test this, download FPP 8 beta 1 image, then do an upgrade in the help->about page, then install the artnet plugin.
