### ISSUE TITLE
PI Crashes / Videos not playing

### ISSUE THREAD

**Issue by PhatAdam** [FalconChristmas/fpp#1734]
FPP 7.4 / Pi 4 - 2GB RAM
Upon play of show, playing mp4 files to pi video output to colorlight card (via Ethernet Cat6) - nightly 2 or 3 times - the screen is just black - on reboot of pi - show returns.  (interestingly) on reboot of led screen, video also returns however its about playing at a speed of about 1.5x, and remains 1-2 minutes behind, and can't catch up until next fseq file starts from master.

[fpp-Pi-7.4-3-gd3702c26-M1-10000000266c6bbe-2023-12-24_17-22-44.zip](https://github.com/FalconChristmas/fpp/files/13767266/fpp-Pi-7.4-3-gd3702c26-M1-10000000266c6bbe-2023-12-24_17-22-44.zip)

Please reach out glad to help provide any details neccesary. 

(PI is connected to FPP Master via Wireless (unifi 6 network.)

**Comment by PhatAdam** [comment]
FYI - last night i updated to d3702c2 - didnt seem to have issues last night.

**Comment by Poporacer** [comment]
Is this resolved then? Please close or provide additional information

**Comment by darylc** [comment]
no response
