### ISSUE TITLE
A "Pause" button on the Status page

### ISSUE THREAD

**Issue by RobertBurton1** [FalconChristmas/fpp#1737]
I would like to see if a "Pause" button can be added to the "Status" page. Also to have this "Pause" keep the lights on at whatever part the song is in, in the sequence. Also to have the music stop at that moment as well.

I have a display where I watch on camera. I also use a wireless mic to talk to people who might, get out of their car (we don't allow since it is on a dark street and creates issues when they do get out), park on the wrong side of the street to watch (again, traffic problems) or in case of an emergency. 

Thanks for considering,
Robert Burton

**Comment by Poporacer** [comment]
Adding a Pause button to the status screen would also require a Resume button as well. In my opinion this will add additional clutter to this screen.
This functionality is somewhat available through FPP Commands (the lights don't stay on when it is paused) so this might be the better method?

**Comment by libby2cm** [comment]
Pause/resume playlist is available via FPP command. You can invoke it thru the 'run fpp command' button on any screen, though it does take an extra click. If you want a cleaner interface for it, you could use the big buttons plugin or create a management dashboard for your show in home assistant to handle it however you like (this is what I do).

**Comment by darylc** [comment]
Best use the big buttons plugin and call the FPP commands.
