### ISSUE TITLE
Log File Delete

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1739]
While going through the log files, you can delete old log files except for:
/var/log/messages
/var/log/syslog

Turns out the UI does not have the needed privileges' to delete these.
SSH sudo rm Will allow you to delete them.

![FPP Delete](https://github.com/FalconChristmas/fpp/assets/461610/5328ff2f-61ea-480c-b42e-abc90b73ba9c)

**Comment by ghormann** [comment]
I'm unclear if this is a bug or a feature. (Inability to delete system log files.)   Deleting messages and syslog would likely also need rsyslogd restarted to fully free up the space.

**Comment by cpinkham** [comment]
I don't see any reason not to allow it.  It wasn't implemented originally because fppd did not log to syslog at the time so the file(s) grew very little.

**Comment by derwin12** [comment]
ghromann is likely correct .. linux wont release the space for the active logs. You can echo null to them to reset them - but delete wont do much. Perhaps something can be done to rotate them out then delete.

**Comment by jcrossbdn** [comment]
Logrotate would likely be a good option and has a simple configurationJasonSent from my iPhoneOn Dec 31, 2023, at 10:50 AM, Daryl ***@***.***> wrote:﻿
ghromann is likely correct .. linux wont release the space for the active logs. You can echo null to them to reset them - but delete wont do much. Perhaps something can be done to rotate them out then delete.

**Comment by darylc** [comment]
this looks fixed in fpp 8
