### ISSUE TITLE
FPP Kiosk mode with 1024x600 display not showing correct resolution

### ISSUE THREAD

**Issue by rvcullen** [FalconChristmas/fpp#1740]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 7.4 running on Pi 3B

**Describe the bug and Steps to reproduce**: 
I cannot seem to get the HDMI output to display 1024x600 correctly for a 7" capacitive display.
Setting are Kiosk mode and resolution of 1024x600/60
I have tried forcing the HDMI output and tried other numerous lesser resolutions all with same result.
Result is that bootup and "DOS" pages with text all scroll by fine and normal resolution, up to the last one which states "this FPP console is for advanced users...." and then it changes resolution and shows two halves of kiosk screen, with split down the middle.

Adding photo of kiosk screen as displayed. mouse can be seen on either side of screen.
Capacitive touch function seems to work and can scroll up and down page 
![kiosk screen](https://github.com/FalconChristmas/fpp/assets/19362835/80436674-95cd-402b-ab2e-5a9c167fee75)

**Comment by rvcullen** [comment]
![device](https://github.com/FalconChristmas/fpp/assets/19362835/53837ca6-bb8d-422d-a8d8-95b26b371cb9)

**Comment by darylc** [comment]
Please test again with FPP 8, there have been lots of changes related to this.
