### ISSUE TITLE
Add an "Insert Gracefully" capability to queue up any song to play next and then continue the playlist

### ISSUE THREAD

**Issue by reelpilot** [FalconChristmas/fpp#1741]
**Is your feature request related to a problem? Please describe.**
I often get requests for specific songs when I'm out talking to visitors. It would be nice to be able to queue up a specific song to play next, even if it's not on the current playlist. Then when the requested song is finished, the active playlist will resume where it left off. Currently this is not possible and while I can skip to songs on the current playlist, I cannot play songs on a different playlist without completely stopping the current playlist. In either case there is no easy way for the current playlist to be resumed from the present position after the requested song is played. 

**Describe the solution you'd like**
On the main status page, create a button called "Insert Gracefully", when selected it would take you to a list of all available playlists / sequences. Then the user selects a song and it will be queued to be next up to play. Then after the requested song is played, FPP will either resume the playlist where it left off or play another queued song if an additional one was selected. 

**Describe alternatives you've considered**
While remote falcon can do some of these things, it's really a tool for people to vote on the next song. In this scenario I don't want people to have a vote, I simply want to be able to add a specific song to play next via FPP even if that song is not part of that night's playlist.

**Comment by derwin12** [comment]
Isn't there an fpp command to do this?

**Comment by cpinkham** [comment]
I think the command requires a playlist.  I also want the requested functionality and think it could make things like Remote Falcon easier if the requesting app can insert a sequence instead of having to insert a playlist.ChrisOn Jan 1, 2024, at 3:19 PM, Daryl ***@***.***> wrote:﻿
Isn't there an fpp command to do this?

**Comment by dkulp** [comment]
The "Insert Playlist After Current" does this.   You can select fseq files and it auto-creates a playlist internally for it just like if you selected it from the status page.

**Comment by reelpilot** [comment]
I see the "insert playlist after current" command, but I don't see how that works. If a playlist is currently running and I add that command to the playlist and save it, the current playlist doesn't update to show the command until it finishes in it's entirety and cycles to the beginning.

**Comment by cybercop23** [comment]
You don't add it to the actual playlist itself. Use the Run FPP Command and you can choose immediate oe after and it will insert itself into the playlist one time only. No need to edit the actual playlist itself.

![image](https://github.com/FalconChristmas/fpp/assets/23619433/f0be6cba-2d0c-4dd8-8532-59c247e355d6)

![image](https://github.com/FalconChristmas/fpp/assets/23619433/a0ac2057-2b91-4025-b57b-5a2f5a3e6342)

**Comment by reelpilot** [comment]
Ok I got it now. Originally I was thinking the command got inserted into the playlist, but I forgot about the insert command at the bottom of the UI. 

![Screen Shot 2024-01-03 at 2 58 00 PM](https://github.com/FalconChristmas/fpp/assets/41338890/05214929-43e5-4f23-8c51-e268f26bb41e)

I'm happy to know that this effectively does what I'm looking for, but perhaps this feature could be simplified into a more user friendly interface like I described in the original post. I'm sure I'm not the only one wants this feature, but wasn't aware how to properly use it.

**Comment by cybercop23** [comment]
So you sort of need two buttons or one to insert and one to choose immediate or graceful. I use immediate, using big buttons plugin to insert a reminder when i see people being.. you know.. stupid people.... so one button is not enought or it needs to have a 2nd layer; insert now or next.

**Comment by reelpilot** [comment]
For my purposes I think graceful would be all I would use, but having an immediate and graceful option is probably a good idea. I had never thought about using the big buttons for this, but that would be another great place to utilize this feature. This could be done now, but every song would need its own button. I could probably setup the top 5 most requested songs, but it would be great if selecting a button could trigger a menu for choosing any song.

**Comment by cpinkham** [comment]
Closing this ticket as I believe we determined the existing functionality accomplishes the original request.  Additional items discussed such as popping up a menu may be better handled by things like the Remote Falcon plugin.
