### ISSUE TITLE
Several Reboots Needed before FPP will start show as scheduled

### ISSUE THREAD

**Issue by Timmyloowho** [FalconChristmas/fpp#1742]
For the week after Christmas, each time the show was scheduled to start, FPP indicated it was playing, but no lights, nothing was lit.

Typically, rebooting the PI would be enough and it would start,    Every day, it appeared to get worse as more than one reboot was needed.  The first reboot would allow the show to play however,  the lights would pause every 3-5 seconds (not audio).
 
On Dec 30th, upgraded to the latest v7.4-3-gd3702c26

On Dec 31 st, 5 reboots were needed before the show started as normal. 2 crash logs were collected.

FPPMon is installed on the show PI only.  
Raspberry Pi 4 Model B 8GB RAM 64-bit 1.5GHz Quad-core Processor.   128GB Sandisk Pro SD
Controllers are all Falcon, running in E131 mode, no multisync.
[fpp-Pi-7.4-3-gd3702c26-M1-10000000e856f7f2-2023-12-31_17-37-41.zip](https://github.com/FalconChristmas/fpp/files/13816359/fpp-Pi-7.4-3-gd3702c26-M1-10000000e856f7f2-2023-12-31_17-37-41.zip)
[fpp-Pi-7.4-3-gd3702c26-M1-10000000e856f7f2-2023-12-31_17-14-55.zip](https://github.com/FalconChristmas/fpp/files/13816360/fpp-Pi-7.4-3-gd3702c26-M1-10000000e856f7f2-2023-12-31_17-14-55.zip)

**Comment by derwin12** [comment]
Various networking alerts in the logs .. something change there? reboot the switch? No gateway (correct) in the show eth0 config?

**Comment by Timmyloowho** [comment]
No gateway, just a gig switch that powers on with the controllers and off after the show.  

New crash last night, no show was playing.  Is this FPPMon caused?
[fpp-Pi-7.4.1-M1-10000000e856f7f2-2024-01-04_17-18-31.zip](https://github.com/FalconChristmas/fpp/files/13847913/fpp-Pi-7.4.1-M1-10000000e856f7f2-2024-01-04_17-18-31.zip)

**Comment by darylc** [comment]
Does this still happen in fpp 7.5?

**Comment by Timmyloowho** [comment]
I am no longer running a show.   To be honest FPP was a total nightmare last year and an unneeded source of stress.   The issues were too many and the blame always went on the user (followed by another patch). I am talking with others to find  other options that are better supported.

**Comment by ghormann** [comment]
We'll close the ticket then.     Sorry you had so many problems with FPP.
