### ISSUE TITLE
Command Preset 4 channel White, wrong color

### ISSUE THREAD

**Issue by Fonzi03** [FalconChristmas/fpp#1745]
FPP Version: | 7.4.1
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2023-08

Controller: F16v4
Build: 30

Pixels 4 channel APA109
Total Channels on F16: 3172

Pixel Overlay Models
CH./NODE: 4
Total Channels: 3172

When using a Command Preset set to:
Overlay Model Fill
     (models selected)
     State: Enabled
     Color: #ffffff

Instead of lighting the Warm White channel the lights are going full RGB. 

Xlights tests, .fseq and the F16 tests work as expected.

**Comment by darylc** [comment]
it would be lighting the white channel as well as the R, G & B channels.  This seems expected.

**Comment by Fonzi03** [comment]
> it would be lighting the white channel as well as the R, G & B channels. This seems expected.

What would be the proper procedure to light only the warm white channel?

**Comment by darylc** [comment]
I'd probably sequence something in xlights and save it as an effect sequence and play it back on fpp
