### ISSUE TITLE
FPP time data from GPS instead of RTC or Internet

### ISSUE THREAD

**Issue by markzvo** [FalconChristmas/fpp#1749]
Many users need the correct time on FPP - and maintain the correct time after power loss/reboot. There are two ways to do this currently.
1. Give the Pi/BBB FPP instance internet access (not feasible in all use cases)
2. Set the time manually and add a RTC module (time can drift and battery can die)
**3. NEW: Get the time form an attached USB GPS dongle**

I have already purchased a GPS dongle from Amazon and can confirm it reports the time received from GPS on my Pi 3 running FPP
Dongle link: https://www.amazon.com/gp/product/B078Y52FGQ
After running `sudo apt-get install gpsd gpsd-clients` using the _>_SSH Shell_ option in the About menu of FPP, the GPS module successfully reports position and time data as device /dev/ttyACM0 using both commands `gpsmon` and `cgps -s` - see below screenshots. A reboot may be required after installing the GPS Daemon (maybe not? needs confirmation)

The FPP Setting Time Config UI would need to be modified to accommodate time from the GPS module. The time reported from GPS may need some translation/normalizing as well... GPS Time (GPST) is a continuous time scale (no leap seconds) so it is unique time format - I believe there are already libraries to do this(?). Additional info also located here: https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html

This could also potentially auto-populate the Lat/Long data in FPP during initial setup or post-setup as well.
A consideration is that some GPS receivers may take a while (up to a minute) to lock on - especially if the line of sight is poor or if the GPS module is in an ammo case or other similar scenario.

**Additional context**
![image](https://github.com/FalconChristmas/fpp/assets/93454788/1a298828-62fd-4d97-8c57-d284117cff74)
![image](https://github.com/FalconChristmas/fpp/assets/93454788/0a147208-15cc-4856-997d-96fede3b48ef)

**Comment by markzvo** [comment]
Additional info here: [https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html](url)

**Comment by markzvo** [comment]
Followed these instructions but no luck getting FPP to recognize the time from GPS:
https://www.rapid7.com/blog/post/2015/07/27/adding-a-gps-time-source-to-ntpd/
(I even commented out the falconplayer ntp pool in ntp.conf, but it eventually came back after more testing)

**Comment by chrkov** [comment]
If you have the PI talking to GPS, couldnt you just add the sntp server service to the PI now and then point FPP to 127.0.0.1 to get the time?   Nice thing about this then is any of your other FPP devices could then get the time for that pi also using ntp.

Just a thought.  

If they add this to FPP, it would make sense to have the FPP device also be an SNTP server for other devices on the network.

**Comment by bobreese** [comment]
I have resolved this with a DS3231 clock.
I hope the Dev's will make the needed changes to apply this......
[RTC Setup.pdf](https://github.com/FalconChristmas/fpp/files/13956644/RTC.Setup.pdf)
[ds3231clock.zip](https://github.com/FalconChristmas/fpp/files/13956645/ds3231clock.zip)

**Comment by darylc** [comment]
This feels better suited for a plugin?

**Comment by darylc** [comment]
It is extreme unlikely that this will be implemented in FPP unless someone writes a plugin or sends us a pull request to implement it.
