### ISSUE TITLE
7.5 Scheduler not showing any available Playlists

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#1753]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP Version: | 7.5
Platform: | Raspberry Pi (Pi 3 Model B+)
FPP OS Build: | v2023-12
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 000000005e8ac461
Kernel Version: | 6.1.21-v7+
System Boot Time: | 2024-01-13 23:39:32
fppd Uptime: | 02:26
Local Git Version: | eacc0bd ChangeLog
Remote Git Version: | eacc0bd

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Content Setup / Playlists show multiple playlists available
2. Content Setup / Scheduler does not show any available playlists after adding an additional schedule entry.  It also deleted the playlist from all existing schedules so had to edit the json file directly to get the schedule linked to the playlist.

![bugReport1](https://github.com/FalconChristmas/fpp/assets/10160178/81797909-b572-4c98-8c2a-2b798c5048a8)
![bugReport2](https://github.com/FalconChristmas/fpp/assets/10160178/67493f5d-afe6-4eec-a0cd-adcdbf2c6a5d)
![bugReport3](https://github.com/FalconChristmas/fpp/assets/10160178/f0fae7b3-0a9d-42d6-8798-099594b9d1f1)

**Comment by ghormann** [comment]
I'm not able to reproduce this using eacc0bd  (7.5)   
1) Any errors in fppd.log or apache2-error.log?
2) If you call the playlist api (http://{ipaddr}/api/playlists)  what does it return?
3) If you hit F12 on your browser to put Chrome in Developer mode, switch to "console" tab, and reload the scheduler page, do any errors get displayed?

**Comment by jcrossbdn** [comment]
1) No errors that seem relevant.  After the update to 7.5 I do see that there are errors when attempting to query if the sandevices controllers are online.  Not sure why they couldn't be reached as they were online and reporting to my monitoring system the entire time

Here is the snippet (althought likely irrelevant tot this issue):
```
2024-01-14 01:44:03.063 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.10): Timeout was reached
2024-01-14 01:44:04.063 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.12): Timeout was reached
2024-01-14 01:44:04.104 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.20): Unsupported protocol
2024-01-14 01:44:04.140 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.21): Unsupported protocol
2024-01-14 01:45:04.135 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.10): Timeout was reached
2024-01-14 01:45:04.137 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.12): Couldn't connect to server
2024-01-14 01:45:04.171 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.20): Unsupported protocol
2024-01-14 01:45:04.204 (1829) [General] /opt/fpp/src/common.cpp:1060: curl_easy_perform() failed (http://192.168.10.21): Unsupported protocol
2024-01-14 01:46:04.379 (1829) [Sync] /opt/fpp/src/MultiSync.cpp:1155: Have not seen 192.168.10.10 in over 2 hours, removing
2024-01-14 01:46:04.379 (1829) [Sync] /opt/fpp/src/MultiSync.cpp:1155: Have not seen 192.168.10.12 in over 2 hours, removing
2024-01-14 01:46:04.379 (1829) [Sync] /opt/fpp/src/MultiSync.cpp:1155: Have not seen 192.168.10.20 in over 2 hours, removing
2024-01-14 01:46:04.379 (1829) [Sync] /opt/fpp/src/MultiSync.cpp:1155: Have not seen 192.168.10.21 in over 2 hours, removing

```
I do also see a timescale error once per song: 2024-01-12 18:41:41.115 (1834) [MediaOut] `/opt/fpp/src/mediaoutput/SDLOut.cpp:919: Warn: "Shut Up and Dance With Me.m4a" - [mov,mp4,m4a,3gp,3g2,mj2 @ 0x78f560] stream 0, timescale not set`


---------------------------------------
None of the appear to be scheduler or playlist related

No entries from today in the apache error log

The api returns the three playlists properly: ["Christmas 2023","Christmas 2023 - Copy","testing1"]

There are no console errors listed in dev tools

The ui call to scheduler.php is receiving the first playlist entry that I updated directly (the rest of the entries are showing null which is what I believe the original issue was post update).
```
[
    {
        "enabled": 1,
        "sequence": 0,
        "playlist": "Christmas 2023",
        "day": 7,
        "startTime": "17:30:00",
        "startTimeOffset": 0,
        "endTime": "22:00:00",
        "endTimeOffset": 0,
        "repeat": 1,
        "startDate": "2024-01-14",
        "endDate": "2029-01-21",
        "stopType": 0
    },
    {
        "enabled": 1,
        "sequence": 0,
        "playlist": null,
        "day": 7,
        "startTime": "17:00:00",
        "startTimeOffset": 0,
        "endTime": "23:00:00",
        "endTimeOffset": 0,
        "repeat": 1,
        "startDate": "2023-12-31",
        "endDate": "2023-12-31",
        "stopType": 0
    },
    {
        "enabled": 1,
        "sequence": 0,
        "playlist": null,
        "day": 12,
        "startTime": "17:00:00",
        "startTimeOffset": 0,
        "endTime": "22:00:00",
        "endTimeOffset": 0,
        "repeat": 1,
        "startDate": "2023-12-01",
        "endDate": "2024-01-13",
        "stopType": 0
    },
    {
        "enabled": 1,
        "sequence": 0,
        "playlist": null,
        "day": 13,
        "startTime": "17:00:00",
        "startTimeOffset": 0,
        "endTime": "23:00:00",
        "endTimeOffset": 0,
        "repeat": 1,
        "startDate": "2023-12-01",
        "endDate": "2024-01-13",
        "stopType": 0
    }
]
```

I see the UI's call to validate.php is returning the playlists successfully
```
[
    {
        "name": "Christmas 2023",
        "valid": true,
        "messages": []
    },
    {
        "name": "Christmas 2023 - Copy",
        "valid": true,
        "messages": []
    },
    {
        "name": "testing1",
        "valid": true,
        "messages": []
    }
]
```

**Comment by jcrossbdn** [comment]
I just tried it in edge, safari and firefox and everything is working properly so this is just a chrome issue.

**Comment by cybercop23** [comment]
We had this issue last night in the zoom room. Please try to clear cache in Chrome and try again. That got it fixed. The person was having the same issue with Chrome and worked in Edge without an issue.

**Comment by ghormann** [comment]
@cybercop23  Did the zoom room user just preform an upgrade?  (Trying to figure out the root cause)

**Comment by cybercop23** [comment]
If I recall, he tried on 7.5 originally and didn't work and then fresh reimage on 7.2. We tried a hard browser refresh, but that didn't work either.

**Comment by darylc** [comment]
@jcrossbdn How did you go with clearing the chrome cache?

**Comment by darylc** [comment]
no reply
