### ISSUE TITLE
Add Last Will and Testament to Ready Topic in MQTT

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#1755]
**Is your feature request related to a problem? Please describe.**
Mainly an enhancement.

**Describe the solution you'd like**
Right now, if FPP stops gracefully, it updates the Ready topic to 0 and when FPP starts, it updates to 1.   Its a great way to know the device is online and FPP is running.   But if the device drops offline (network loss, power loss or device failure) this topic will not be updated.   By adding a Last Will and Testament to it, the broker would update this automatically to 0 when the device stops updating the Topic.  This is a better way to know loss of a device than just a ping to it.

**Describe alternatives you've considered**
Right now, I just ping the device separately.

**Additional context**

**Comment by ghormann** [comment]
Interesting idea.   I've added it to my list of items to look at....

**Comment by chrkov** [comment]
I can confirm that this is working perfect!
