### ISSUE TITLE
FPP Remote MQTT 'current_song' format different than FPP Player format

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#1756]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: FPP 7.5 running on PI

**Describe the bug and Steps to reproduce**: 
When using a remote to output audio also:

MQTT 'current_ song' on remote displays path to file where MQTT 'current_song' on player does not.   
I would think this should be consistent without the path as there is a 'media_filename' that does show the path.

Player
![image](https://github.com/FalconChristmas/fpp/assets/57808614/a0f409d9-24f2-41c9-a866-384749c404ad)

Remote
![image](https://github.com/FalconChristmas/fpp/assets/57808614/df4502b1-9757-46b9-ae0c-8186d09d723f)

**Expected behavior**: 
None

**Additional context**: 
None

**Additional Attachments**
Dont believe these are needed.

See above

**Comment by darylc** [comment]
@ghormann Do you think you'll get a chance to do this before FPP 8 release or shall we retarget it for FPP 9 and beyond?

**Comment by ghormann** [comment]
@darylc  It won't be soon I'm afraid.   Too much business travel. :-(

**Comment by darylc** [comment]
this was also flowing through into the multisync page on the player
