### ISSUE TITLE
Help tip for FPPD not running

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1757]
The goal is to give a help page for when FPPD is not running.  It would include some common debugging tips and *perhaps* run some of the automatic troubleshooting steps and give suggestions of possible causes. 

1. Check if fppd file exist -- If not, may have been failed upgrade
2. Check fppd.log file.  If quickly crashing after restart, try and flag error

**Comment by ghormann** [comment]
@patdelaney  (as well as others who frequent the zoom room).  Can you provide some suggestions of items to include in this tool tip?

**Comment by Poporacer** [comment]
One of the common causes/fixes to this issue that I have seen are:
Configuring xLights with the wrong type of controller, typically selecting an F instead of K series controller (or vice versa)  or one of the other similar controllers. 
Fix-Configure xLights correctly  and go to FPP Settings>System and reset Channels, re-upload from xLights

**Comment by cybercop23** [comment]
If player only, empty play lists after deleting sequences - shoud really not crash on that.
For controller.. they eeprom issue from last year...  checking i2cdetect, looking for 50 and if the scan works at all and sometime removing the oled.

**Comment by ghormann** [comment]
> If player only, empty play lists after deleting sequences - shoud really not crash on that. For controller.. they eeprom issue from last year... checking i2cdetect, looking for 50 and if the scan works at all and sometime removing the oled.

@cybercop23  I don't do much work on eeprom.   Can you give me an example of i2cdetect and exactly where you are looking for 50?

**Comment by cybercop23** [comment]
From Help -> Troubleshooting - bottom of 3rd column...
We look for the 50 in the 50/0 column. That shows that it sees the eeprom. When there's a problem, either there's no 50 int he 50/0 slot or the command hangs...

![image](https://github.com/FalconChristmas/fpp/assets/23619433/542ca2dc-9143-47b5-8112-1750f20eabfd)

**Comment by darylc** [comment]
@OnlineDynamic Lets use this issue for the generic help tip infrastructure on warnings

**Comment by OnlineDynamic** [comment]
beginning of warning framework for this in #1933 but think the actual help page for this particular scenario is going to take a bit of group think to define

**Comment by darylc** [comment]
Thanks @OnlineDynamic we can continue updating the warning messages as needed.
