### ISSUE TITLE
Migrate to Debian 12/Bookworm

### ISSUE THREAD

**Issue by dkulp** [FalconChristmas/fpp#1759]
This is required in order to support Raspberry Pi 5.   Base images are available for Pi and BBB.

The bulk of the testing for this will be around the UI frontend as it will be moving from PHP 7.4 to PHP 8.2.   FPP on the Mac has been using PHP 8.x so most things have been fixed, but things like the string page and panels and such may require more updates.

**Comment by OnlineDynamic** [comment]
python environment handling has changed too which is breaking a lot of the plugins... see #1778 for what I think is potential fix is

**Comment by darylc** [comment]
do we call this done @dkulp?
