### ISSUE TITLE
Missing MQTT information in fppd_status (interfaces & advancedView)

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#1761]
**FPP Version and Hardware**: FPP 7.5 on PI

**Describe the bug and Steps to reproduce**: 
According to "https://github.com/FalconChristmas/fpp/blob/master/docs/MQTT.txt", there should be an 'interfaces' and 'advancedView' section and I don't see either on 2 instances.   Not sure if Docs are wrong, I am missing a setting, or if this is a bug.

Output of fppd_status on one unit:

{
  "MQTT": {
    "configured": true,
    "connected": true
  },
  "bridging": false,
  "current_sequence": "",
  "current_song": "",
  "dateStr": "Tue Jan 23",
  "fppd": "running",
  "media_filename": "",
  "mode": 8,
  "mode_name": "remote",
  "multisync": false,
  "playlist": "",
  "seconds_elapsed": "0",
  "seconds_played": "0",
  "seconds_remaining": "0",
  "sensors": [
    {
      "formatted": "44.0",
      "label": "CPU: ",
      "postfix": "",
      "prefix": "",
      "value": 44.008,
      "valueType": "Temperature"
    },
    {
      "formatted": "34.5",
      "label": "Temp: ",
      "postfix": "",
      "prefix": "",
      "value": 34.5,
      "valueType": "Temperature"
    }
  ],
  "sequence_filename": "",
  "status": 0,
  "status_name": "idle",
  "time": "Tue Jan 23 10:49:07 CST 2024",
  "timeStr": "10:49 AM",
  "timeStrFull": "10:49:07 AM",
  "time_elapsed": "00:00",
  "time_remaining": "00:00",
  "uptime": "2 days, 23:53:35",
  "uptimeDays": 2.9955439814814815,
  "uptimeHours": 23.893055555555556,
  "uptimeMinutes": 53.583333333333336,
  "uptimeSeconds": 35,
  "uptimeStr": "2 days, 23 hours, 53 minutes, 35 seconds",
  "uptimeTotalSeconds": 258815,
  "uuid": "M1-00000000e3a1b8ee",
  "volume": 100
}

HA/fpp/falcon/player/cmk-od-fpp02/fppd_status

**Expected behavior**: 
See interfaces.

**Comment by ghormann** [comment]
I **think** this is an accidental side effect of a change made some time ago...   Is there any value in having the interfaces?  I'm leaning towards just fixing the documentation.

**Comment by chrkov** [comment]
On the Interfaces, not really, but there is a ton of great information in advancedView!

**Comment by chrkov** [comment]
So is that a no to the advancedView part?

**Comment by ghormann** [comment]
@chrkov I don't think adding the "advancedView" back is the correct fix.  My suggestion would be to any any specific fields that appear valuable.  Can I suggest creating a new enhancement request for any data you believe is needed?

**Comment by chrkov** [comment]
OK.   I understand and will go through and let open a new ticket.
