### ISSUE TITLE
Provide visual feedback to user that Samba/CIFS is being installed

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1766]
**Issue**
Currently when you go to enable Samba/CIFS, you click the checkbox and under the covers FPP silently installs the components needed for Samba/CIFS. The problem is the checkbox doesn't get the X put in it until FPP is done installing the components. There is no visual feedback that anything is really happening until FPP is done, then you see the checkbox and a pop in the upper right.  The same holds true for uninstalling Samba/CIFS.

**Describe the solution you'd like**
add some sort of visual feedback for the user, cursor hourglass or some other sort of pop up

It's also the same behavior for FTP and RSYNC check box

**Comment by darylc** [comment]
I think removing the UI hang is probably more useful than providing feedback (which we usually do via a popup window)

**Comment by darylc** [comment]
(for what it's worth, it wasn't installing anything during that pause, just starting it up, or shutting it down)
