### ISSUE TITLE
FPP v8: Plugin Install Error: fpp-PictureFrame

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1773]
Error in installtion script

**Comment by cpinkham** [comment]
This appears to be running into an issue with apt or dpkg.  The fpp_install.sh script stopped (possibly timed out) and I had to run "sudo dpkg --configure -a" manually to fix things up.  Once I did that, an uninstall and reinstall worked.  This same issue may affect any other plugin that needs packages installed.

**Comment by darylc** [comment]
@patdelaney is this still a problem in the latest image & version of master?

**Comment by patdelaney** [comment]
The pluging appears to install with an issue, but I have not yet successfully configured it to run

**Comment by patdelaney** [comment]
In version 8 using the example play list, you see the image to a split second and then the screen goes black. It then sits on the pause command for 60 seconds and then repeats, Just a quick flash. It's not holding the image. I'm guessing its a VLC setting on the new version of VLS that we are using for V8
@cpinkham

**Comment by OnlineDynamic** [comment]
on v8.x-master-311-gf08308a7 (master branch)

The plugin install is hanging on "Processing triggers for php8.2-fpm (8.2.7-1~deb12u1+rpi1) ..."
