### ISSUE TITLE
FPPv8: Plugin Install Error: FPP Tir Programmer

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1774]
Needs to be reviewed is this still a valid plugin

**Comment by darylc** [comment]
@patdelaney is this still a problem in the latest image & version of master?

**Comment by patdelaney** [comment]
I tested with [v8.x-master-306-gfa61f2a6 (master branch)]

I don;t think it compiled right, @Materdaddy 


`Installing plugin fpp-tirprog
Cloning into 'fpp-tirprog'...
Running fpp_install.sh script for fpp-tirprog
~/media/plugins/fpp-tirprog ~/media/plugins
Submodule 'tirprog' (https://github.com/Materdaddy/tirprog.git) registered for path 'tirprog'
Cloning into '/home/fpp/media/plugins/fpp-tirprog/tirprog'...
Submodule path 'tirprog': checked out 'ae00d6a89e522223056a1656edb6698a656bdadb'
make: Entering directory '/home/fpp/media/plugins/fpp-tirprog/tirprog'
gcc -g -o tirprog tirprog.c
tirprog.c: In function ‘main’:
tirprog.c:258:17: warning: implicit declaration of function ‘sleep’ [-Wimplicit-function-declaration]
  258 |                 sleep(1);
      |                 ^~~~~
tirprog.c: In function ‘SerialOpen’:
tirprog.c:285:17: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
  285 |                 close(*fd);
      |                 ^~~~~
      |                 pclose
tirprog.c: In function ‘SendData’:
tirprog.c:386:9: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
  386 |         usleep(200);
      |         ^~~~~~
tirprog.c:396:9: warning: implicit declaration of function ‘write’; did you mean ‘fwrite’? [-Wimplicit-function-declaration]
  396 |         write(fd, channelData, 513);
      |         ^~~~~
      |         fwrite
make: Leaving directory '/home/fpp/media/plugins/fpp-tirprog/tirprog'
~/media/plugins

Done`

**Comment by darylc** [comment]
Compile looks ok Pat, they are just warnings
