### ISSUE TITLE
FPPv8: Plugin Install Error: Si4713_FM_RDS

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1777]
E: dpkg was interrupted you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by ShadowLight8** [comment]
@patdelaney Thanks for reporting this! I happened to see it and I'll take a look.
For non-FalconChristmas plugins, it might be good to also post the issues to their "Submit a bug" page - https://github.com/ShadowLight8/Si4713_FM_RDS/issues in this case.

**Comment by darylc** [comment]
@patdelaney is this still a problem in the latest image & version of master?

**Comment by patdelaney** [comment]
@darylc the installer no longer fails, but I can't test the functionality because I don;t think I have that transmitter, unless that is the same one that a Kulp K-32 uses
