### ISSUE TITLE
Vast FMT-212R Audio glitches on Pi

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#178]
Creating a ticket to help track the other github ticket open with the Pi kernel/firmware guys.

That ticket is located at: https://github.com/raspberrypi/linux/issues/1145

**Comment by dvisser** [comment]
This issue is still present. Latest fpp image. Vast fm tx noise until vol up or down is clicked.

**Comment by wingrunr21** [comment]
@dvisser what Pi are you running? I should note that Vast FMT audio quality isn't particularly good even on devices that "work". I switched from a Pi to a Beagle Bone Black a few years ago due to this issue and I'm considering replacing the whole thing due to the quality.

**Comment by cpinkham** [comment]
I believe this is still an issue on the Pi and there may be an unrelated issue on other hardware platforms as the Vast FMT has some issues on non-Pi/non-BBB as well.   Workaround code has been added to the Vast-FMT plugin to bump the volume down/up whenever the media callback is called.  Other than that, there may not be much we can do if the underlying issue is with the transmitter itself across multiple Linux kernel versions and hardware platforms.  Keeping ticket open for now, but it may get closed in the future unless someone finds the time to take a deep dive into USB troubleshooting.

**Comment by libby2cm** [comment]
sort of determined to fix this.  are there no reports of other usb audio devices having similar issues?  I would think same driver is used for all usb audio devices, so like the usb soundblasters should have issues too..

**Comment by cpinkham** [comment]
We have had at least one report that this issue is fixed with the latest v4.x SD image.  Given that, and the fact that this is a kernel issue and not something we as FPP developers can do much about, I'm going to close this ancient ticket.
