### ISSUE TITLE
FPPv8 ntpsec-systemd-netif.service

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1781]
On boot, O/S reporting: failed to start ntpsec-systemd-netif.service

**Comment by OnlineDynamic** [comment]
@bobreese can you please provide more detail on FPP version and what device are you running ?

**Comment by bobreese** [comment]
Pi3b+ 
FPP v7.5

**Comment by darylc** [comment]
@bobreese Can you please test again on fppos alpha2 and latest master?  I'm not seeing this

**Comment by darylc** [comment]
actually mine started doing this today after.  I've fixed it now, that fix will appear in the next fppos release.
