### ISSUE TITLE
Point of Contact for Raspberry Pi Imager

### ISSUE THREAD

**Issue by tdewey-rpi** [FalconChristmas/fpp#1783]
Hi,

As of Raspberry Pi Imager v1.8.1, I now require OS vendors looking to offer their OS via the Raspberry Pi Imager list to provide a named point of contact for coordinating future releases of Imager and associated software.

Please contact me via applications@raspberrypi.com so we can established a named point of contact for FalconPlayer.

**Comment by darylc** [comment]
@tdewey-rpi I have reached out via email.
