### ISSUE TITLE
8.x master.  Playlist did not load correctly by scheduler

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#1784]
**FPP Version and Hardware**: 
[v8.x-master-49-g3a0cfa85 (master branch)]  on Pi 3B+

**Describe the bug and Steps to reproduce**: 
This issue just started today after I updated my master.  I didn't note the exact previous version, but it was a 7.x master before I updated.  It's now showing the 8.x series.  I have not updated the OS. (nor am I aware if I was supposed to or not)

I've got a simple playlist running this month.  two static sequences and two branch commands to determine which sequence plays based on time window.  I noticed the sequences were toggling back and forth instead of going back and repeating like it should have.  When I compared the playlist on the main status page, against what i see when i edit the playlist, the one currently loaded by the scheduler was missing the first 3 items, which happened to be two startup items, and the first entry in the main section which was the first branch item.

I then restarted FPPD and it loaded the playlist properly.

**Expected behavior**: 
The playlist should load properly in the scheduler.

**Other information**
I'm happy to keep testing master branch stuff, but I do use this for year round lighting, so I need basic functionality to continue working as I do so.
Tonight is the last night for this schedule.  Tomorrow it switches to the valentines day schedule which is basically the same, just two different sequences.

Playlist and schedule files attached.  
[WinterBlue.json](https://github.com/FalconChristmas/fpp/files/14120703/WinterBlue.json)
[schedule.json](https://github.com/FalconChristmas/fpp/files/14120705/schedule.json)

**Comment by darylc** [comment]
Whilst we'd like not to break master, at this time of year, and specially with the huge changes related to FPP 8, it's not unexpected.

If you require a stable system, please revert to FPP 7.5

Before logging bugs in FPP 8.x master, please ensure you are running the FPP 8.x fppos image, not the FPP 7.x fppos image.

**Comment by darylc** [comment]
Is this still an issue in fpp 8 beta 1?

**Comment by darylc** [comment]
no response
