### ISSUE TITLE
FPPv8: upload_max_filesize and post_max_size are out of range

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#1786]
php scripts are throwing warnings:
`PHP Warning:  Invalid "upload_max_filesize" setting. Invalid quantity "4G": value is out of range, using overflow result for backwards compatibility in Unknown on line 0

PHP Warning:  Invalid "post_max_size" setting. Invalid quantity "4G": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
`

Need to update the values from 4G to a value that is acceptable (likely "0")

**Comment by darylc** [comment]
This is fixed already, but will not take effect until the next fppos upgrade which is not yet available.
