### ISSUE TITLE
FPPv8: Restore backup from v7 results in ungraceful http 500

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#1787]
error from /home/fpp/media/logs/apache2-error.log

`[Thu Feb 01 21:52:06.790475 2024] [proxy_fcgi:error] [pid 1452:tid 1682846656] [client 192.168.1.36:53881] AH01071: Got error 'PHP message: PHP Warning:  Trying to access array offset on value of type null in /opt/fpp/www/backup.php on line 749; PHP message: PHP Warning:  Trying to access array offset on value of type null in /opt/fpp/www/backup.php on line 749; PHP message: PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /opt/fpp/www/backup.php:749\nStack trace:\n#0 /opt/fpp/www/backup.php(419): processRestoreData()\n#1 /opt/fpp/www/backup.php(341): doRestore()\n#2 {main}\n  thrown in /opt/fpp/www/backup.php on line 749', referer: http://192.168.10.2/backup.php`

It appears that Channel Outputs restore works but it fails after that (or shortly after that)

**Comment by jaredb7** [comment]
Hi @jcrossbdn, this has been fixed. It should be all ok! but if you wanted to pull in the latest commits/updates on your alpha install and test that would be great.

Restoring does take a little longer than it used to (at least for me anyway), unsure what's causing that but I'll investigate further
