### ISSUE TITLE
Log when eFuse is triggered

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1788]
_NOTE: This is captured discussion from the Developers session in the xlights zoom room in early February_

**Is your feature request related to a problem? Please describe.**
Periodically the eFuse is triggering on my Falcon board.   I'm not sure when in my sequence this is happening.   

**Describe the solution you'd like**
When an eFuse is triggered, the log file should capture a WARNING message that includes the sequence being played and the position in the sequence.  This would aid in identifying when a sequence needs adjusted. 

**Describe alternatives you've considered**
Stand out side and watch my show and hope I spot it. :-)

**Comment by dkulp** [comment]
This has been in a for a few weeks.
