### ISSUE TITLE
Upload of .eseq file reports a missing file in the xlights log

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1790]
I originally logged in xlights but it appears to be bad response to a curl command.
http://192.168.0.42/api/sequence/Matrix.eseq/meta
It tries to get the meta for an eseq file during and fpp connect upload operation.

The response - perhaps is just noise or a bad print statement(?). It comes back as
![image](https://github.com/FalconChristmas/fpp/assets/4643499/0b686d2b-8b92-4f3f-96e4-2b988b73594e)

You can likely repeat this by searching for any .eseq file .. it seems it always assume its an fseq file?
http://192.168.0.42/api/sequence/123.eseq/meta
![image](https://github.com/FalconChristmas/fpp/assets/4643499/fe7b16fa-2940-4b52-8bc5-45f63cfed678)

**Comment by cybercop23** [comment]
Looks like the API is looking for an extension of .fseq... There's not effects endpoint so it makes sense to also check if not .eseq or maybe just "-3 seq"
` if (substr($sequence, -5) != ".fseq") {`

**Comment by darylc** [comment]
@cybercop23 I went back and forth on this a couple of times, in the end I think it's reasonable for this api to mostly work for .eseq as well.

**Comment by darylc** [comment]
@derwin12 Can you please retest on latest 8 master?

**Comment by derwin12** [comment]
Looks good .. seems to be searching & finding the .eseq file on subsequent uploads
