### ISSUE TITLE
Cleanup: git config --list  displays multiple directory = /opt/fpp lines

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1794]
**FPP Version 8 on Pi but likely all hardware variants**: 

**Proposed fix:**
We shouldn't run the 'git config --global --add safe.directory" in git_pull, only in FPP_Install.sh.  It doesn't check for duplicates it always adds.

**Comment by OnlineDynamic** [comment]
I will add some logic to only add a config line if one doesn't already exist
Will also output the git config as a new troubleshoot git command so thes ettings are easily accessible
