### ISSUE TITLE
Upgrade rpi-ws281x to support Pi v2 B

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#180]

**Comment by cpinkham** [comment]
Instructions for testing were posted to http://falconchristmas.com/forum/index.php/topic,2100.msg40685.html#msg40685

**Comment by jsm174** [comment]
Just to add to this, I was having issues with @richardghirst fork on the RPI2 and Jessie lite. I was getting:
Can't open device file /tmp/mailbox-X: No such device or address.

I switched to the @popoklopsi fork, and it works great.

This particular commit references the issue:

https://github.com/popoklopsi/rpi_ws281x/commit/c2ebca3b0a8711e4e658edc38b38ed90f623f19a

**Comment by cpinkham** [comment]
Should be covered by pull request #185

**Comment by cpinkham** [comment]
#185 was pulled in, closing this ticket.
