### ISSUE TITLE
Troubleshooting page doesn't render FPPD Status correctly

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1809]
Post #1807 from @OnlineDynamic , the button at the bottom of the page that shows FPPD Status and allows for restart is not rendering correctly on http://fpp/troubleshooting.php.   Works fine for other pages. 

![image](https://github.com/FalconChristmas/fpp/assets/24968726/c732b4ed-1b70-47e3-9c6d-cf921f435a95)

**Comment by ghormann** [comment]
@OnlineDynamic  can you take a look?  I tested with commit 4089004

**Comment by OnlineDynamic** [comment]
fixed in PR #1810

**Comment by ghormann** [comment]
Confirmed.  Closing.
