### ISSUE TITLE
FPP v8: Plugin update not working

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#1812]
**FPP Version and Hardware**: Pi3B+  8.x-master-174-gd1ec8350 / git: d1ec835

**Describe the bug and Steps to reproduce**: 
Content Setup / Plugin manager / Check for Updates / Update
Simply says Done and does not update the plugin.  I ensured my directory was unchanged (even deleted and reinstalled and it still didn't do the update).  Check for updates continues to report update available.

Only way to get the update is to delete the directory in plugins and then reinstall or uninstall/install from plugin management.

**Comment by bobreese** [comment]
I can confirm this issue.

**Comment by Poporacer** [comment]
If there has been any "manual" editing of the plugin, then this can happen due to a 'dirty' state of the plugin.... I just tried an update and it worked.
![image](https://github.com/FalconChristmas/fpp/assets/46263877/cdcea762-8c33-4d5b-96a8-a6413876a5b3)

**Comment by jcrossbdn** [comment]
Yes as mentioned I deleted the directory fully and fresh installed to make sure there were no head differences.  I'm updating fpp to latest release right now then will try again

**Comment by bobreese** [comment]
Still broken (Did not delete directory).

FPP Version:	8.x-master-177-g4c9d6249
Platform:	Raspberry Pi (Pi 4)
FPP OS Build:	v2024-02
OS Version:	Raspbian GNU/Linux 12 (bookworm)
Hardware Serial Number:	100000001a8e75ff
Kernel Version:	6.7.0-rc8-v7l+
System Boot Time:	2024-02-25 06:23:14
fppd Uptime:	00:59

**Comment by darylc** [comment]
@bobreese Is this still broken on a fresh install of FPP8 alpha5

**Comment by darylc** [comment]
no reply
