### ISSUE TITLE
Verify Plugins work in V8

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1814]
This is to keep track of the progress of plugins for the V8 release. Add comments for the progress. Some of these plugin are quite old and could use a little updating. Like implementing FPP Commands instead of scripts and using the FPP PrintSettings functions. I think we should focus on the top 10 plugins, I don't know how many people are using the rest.

Here are the top 10 Plugins that are being used:
Remote Falcon **COMPLETED**
WLED Effects
Brightness
FPP Mon
Home Assistant
vast FM
Big Buttons
Matrix tools
Simple Countdown **In Progress**
Projector Control **In Progress**
After hours-**COMPLETED**
Announce Zettle **COMPLETED"**

**Comment by Poporacer** [comment]
Simple Countdown    Plugin GUI works in V8. fully working in 7.5     Waiting on fppos upgrade from 7.5->8 to verify functionality
Projector Control       Plugin functional in v7.8 and v8                        Waiting on additional testing

**Comment by jcrossbdn** [comment]
After hours is now working in v8

**Comment by PiSignage** [comment]
My plugin is working **Announce Zettle!** It is updated.

I am working on a new plugin **Jukebox** that also works with fpp8

**Comment by Poporacer** [comment]
Thanks a million for the update!
    On Thursday, February 22, 2024 at 06:15:03 AM MST, Michael Jones ***@***.***> wrote:  
 
 


My plugin is working Announce Zettle! It is updated.

I am working on a new plugin Jukebox that also works with fpp8

**Comment by darylc** [comment]
@Poporacer What is left to do here?
