### ISSUE TITLE
FileManager - sorting

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1816]
Adding column headings/sorting to the filemanager

I have completed this in PR #1815  

Sounds simple! but I have used this as an opportunity to do lots of updates to tablesorter and general jquery usage
so it now has stickyHeaders on the table and sorting by file size works correctly on all tabs

**Comment by ghormann** [comment]
@OnlineDynamic  Can we close this now that the PR is merged?

**Comment by OnlineDynamic** [comment]
Chris has asked me to add table filtering as well – just working on that logic, additional PR coming soon and then we can shut this one

**Comment by cpinkham** [comment]
Closing issue, both PRs merged.  Thanks.
