### ISSUE TITLE
FPP image on Raspberry Pi imager v1.8.5 writes FPP v7.5 BBB instead of the Pi version

### ISSUE THREAD

**Issue by johna777** [FalconChristmas/fpp#1818]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*
FPP 7.5 image creation using Raspberry Pi Imager v1.8.5

**Describe the bug and Steps to reproduce**: 
-start Raspberry Pi Imager current version wihich is 1.8.5
-select a Raspberry Pi system. I picked Pi 3 but same problem exists for Pi zero W when I checked that too
-under "choose OS" select "other specific-purpose OS" then select FPP
-
**Expected behavior**: 
I expected to get the Pi version, not the BeagleBone version

**Additional context**: 

**Additional Attachments**

![Capture](https://github.com/FalconChristmas/fpp/assets/36684845/28ec85cc-58c3-4e9f-9cbb-8e7c58430def)

**Comment by cybercop23** [comment]
What happens when you skip that first selection? No real need to choose the Pi system.

**Comment by dkulp** [comment]
I think this is now fixed.  I'm not sure if rpi imagers caches things or not so it might be a bit before it works.

**Comment by cybercop23** [comment]
I'll check again later, but a fresh start and **with** or **without** filter, the FPP section is blank.

**Comment by cybercop23** [comment]
Okay, all good now with a filer and witout.

**Comment by johna777** [comment]
yes, all good now. I would never have guessed to skip the filter part. Thanks for the suggestion Alex.
Dan, it's working now correctly thank you.  Would you mind having someone check the sales@falconplayer.com for my message from yesterday? As part of rebuilding the FPP image I went to reinstall the license key and it failed saying it could not find the order number.  I have a key from another system that's not running currently and was able to install that one so this new FPP runs, but eventually I'll need to fix this up.  thanks.
