### ISSUE TITLE
Multisync: When a multisync page is filtered, and errors on non-filtered FPPs show up in the grid, the warnings are not filtered out.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1819]
**FPP 8.x master, but this has been around for a while**: 

**Describe the bug and Steps to reproduce**: 
If you have a lot of FPP devices in your environment they all display fine, even when you filter the list. But if a FPP instance is displaying any sort of error in the multisync page, if you filter the display the error messages from the FPP's that are not part of the filter appear.

**Expected behavior**: 
Error mesages from the FPP's that are not part of the filter should not be displayed.

**Additional Attachments**
Non Filtered display
![image](https://github.com/FalconChristmas/fpp/assets/8147459/c672da34-61d8-4e7f-b3f8-08d296342c47)

Filtered Display
![image](https://github.com/FalconChristmas/fpp/assets/8147459/175d47da-a3dd-4ddf-9b9a-3a0c3497fba6)

**Comment by ghormann** [comment]
I only notice the problem when Auto refresh is turned on.   I'm guessing the "display" property is just set to late, but didn't look too hard at the code. 

![chrome_gF0EnZfRg5](https://github.com/FalconChristmas/fpp/assets/24968726/3282fec5-9844-4254-98d2-10bece5d9d3e)

**Comment by OnlineDynamic** [comment]
PR Request submitted with a fix - the .show() .hide() jquery is problematic with filtered tablesorter
