### ISSUE TITLE
FPP test mode - needs an Off button 

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#182]
From my smartphone,  it is very difficult to turn off all output using the sliders. Even a value of 1 or 2 was enough to keep some thing running. I have a few dmx controllers that will hold that last intensity until a new value 8s sent or I power cycle.

**Comment by rawcreative** [comment]
There's already an on/off, it's the 'Enable test mode' checkbox at the top of the page.

![enabletestmode](https://cloud.githubusercontent.com/assets/1143718/11727799/13ba7884-9f54-11e5-835a-159dc34ce7a7.png)

**Comment by JonB256** [comment]
Yes, but it doesn't send an OFF command when you uncheck the box. Some
devices will stay on.

**Comment by rawcreative** [comment]
Just curious, do you have the 'Always transmit channel data' box checked in the FPP settings? Looking over the code, there is no explicit OFF command sent when test mode is disabled from what I can tell, it just stops sending data altogether. However if that box is checked in the settings, data continues to transmit but essentially with an off value. So while it's not necessarily a solution, it would likely solve the issue in the meantime and it's likely why it hasn't been brought up before. 

I'll make sure to add an 'All Off' button to the v2 interface. I don't think there's any releases scheduled until after the season is over so I'm not sure it'd be worthwhile putting in the current interface but I can if need be. Thoughts @cpinkham ?

**Comment by JonB256** [comment]
After season in V2 will be fine. It is an enhancement, for sure.

**Comment by cpinkham** [comment]
I will probably add an 'Off' button' or at least send an off when the checkbox is toggled off.  I was running into the same issue the other night, out in the yard trying to turn things off and it was a pain from the phone.  I guess I could have started a sequence up and stopped it, but it would be easier if it just worked.

**Comment by cpinkham** [comment]
This will be accomplished by turning off the channels that were being tested when test mode is disabled by unchecking the checkbox.  I have the code in my head, I just need to write it down one day and test.  I will get this in for v1.8.
