### ISSUE TITLE
RGB123 Cape was not detected properly when using Beaglebone Green.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1822]
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 7.5 running on BBG*

**Describe the bug and Steps to reproduce**: 
In Help -> About -> EEPROM Upgrade
Cape/Hat dropdown is not populating
![image](https://github.com/FalconChristmas/fpp/assets/8147459/c95ba3fa-2c1e-4226-b899-b92f573e6c7e)
Meanwhile I did some JS-debugging and found the reason for the empty drop-down box. Maybe my results are interesting for you.
In cape-info.php:eepromVendorListChanged you can find the following lines:

if ("platforms" in capeObj) {
                var plat = capeObj.platforms;
                if (settings["Platform"] == "BeagleBone Black") {
                    if (!plat.includes(settings["Variant"])) {
                        valid = false;
                    }
                } else {
                    if (!plat.includes(settings["Platform"])
                       && !plat.includes(settings["Variant"])) {
                        valid = false;
                    }
                }
            }

This line causes the empty list:
if (!plat.includes(settings["Variant"])) {

"plat" is in my case "Beaglebone Black" and "settings['Variant']" is "Beaglebone Green".
Therefore this can't never be true on my installation. I really use a Beaglebone Green, but I 
think there is something missing in the check or in the settings loading process.

Thank you very much again and have a nice day.

Best regards

Sven

**Comment by darylc** [comment]
@patdelaney Is this still an issue against fpp 8 beta 1?

**Comment by patdelaney** [comment]
I'll reach out to the user

**Comment by patdelaney** [comment]
Hi Pat,

I finally found some time to upgrade my RGB123 Cape to version 8 beta 1. My initial report seems to be fixed now. The drop down list is populated with some entries:
Thank you very much, for reaching out to me.

Sven
