### ISSUE TITLE
Script to mount 2nd sd card for data retrieval

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1824]
**Feature request**
There are times when a ffp sd card will not boot up enough to allow access to the contents of the disk either via the web UI or SSH. There may be sequence data, scripts or one-off configurations that may never have been backed up. Yes I know shame on us.

How about a script that would allow us to mount an sd card that is attached via a usb adapter so that we can mount the secondary usb card and copy the data off.

if we run the script and the mount is successful, please expose the new mount point in file manager so that we can copy the data off the mounted disk. 

Copying/downloading to the local PC would be great.

**Comment by darylc** [comment]
How strongly do you feel about this feature request @patdelaney?  To me seems that only a handful of users might ever use it?

**Comment by patdelaney** [comment]
It can wait, I have documented the steps, but this can pushed out post release. Or just closed
