### ISSUE TITLE
Sticky theads throughout the UI (e.g. on channel inputs, outputs, gpio ins etc) 

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1826]
This is a placeholder for a PR request that I have almost finished which will make all the table theads sticky (on the screens where it makes sense) to keep column headings on display when the page scrolls

@cpinkham Would it be possible to get rights to be able to assign issues to myself as I help with contributions? Just so I can start to attack some of the already open items and you would know I'm looking at it so we don't duplicate effort

**Comment by darylc** [comment]
@OnlineDynamic I can't do anything re permissions but I can assign things to you if you comment in the issues you want assigned

**Comment by patdelaney** [comment]
I think I understand the enhancement, once completed, please list the places where the enhancement is so that we can test it. Thanks  Pat

**Comment by OnlineDynamic** [comment]
Will do.. simply it changes the scroll behaviour on the tables so the headings stay at the top, so from looking like:

![image](https://github.com/FalconChristmas/fpp/assets/68251154/0b2e33db-c2f1-4abf-84a6-582c11b8c68b)

to:

![image](https://github.com/FalconChristmas/fpp/assets/68251154/db3fce88-0a1d-4c5c-a860-0d6ac3d3d506)

**Comment by cpinkham** [comment]
I added you as an external collaborator for now with triage privs on the fpp repository.  I think that should give you the ability to assign tickets to yourself.

**Comment by OnlineDynamic** [comment]
Have raised PR #1829 

@patdelaney places to check:

    adds sticky table headers to:

    backup.php (2 tables on same page)
    index.php and its modal schedule preview
    proxies.php
    commandPresets.php
    scheduler.php (main page and modal preview)
    channelinputs.php
    channeloutputs.php (all tabs with table/header content)
    outputprocessors.php
    gpio.php
    pixeloverlaymodels.php ( 2 tables)

It also introduces a new text search/filter on the script broswers page
