### ISSUE TITLE
enhancement to Remap Channels

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#183]
On the Remap Channels screen, can you add a Comment Field to describe what is being moved to what?

For example - Green Candy canes 
or - Moved strobes to closer controller

**Comment by cpinkham** [comment]
I think this is a good idea across the board.  The conversion to JSON config files should make this easier.

**Comment by rawcreative** [comment]
Marginally related, but I also have it planned to add a description field as well as groups to the outputs page to make it easier to recognize and manage large channel counts - something I really wish xlights had. I lost my channel spreadsheet from last year and had to spend 4 hours this year retracing what goes where and what's mapped to what.
