### ISSUE TITLE
Installing FPP_Install.sh from 7.5 branch installs 8.x master

### ISSUE THREAD

**Issue by Gilimi-the-Grim** [FalconChristmas/fpp#1832]
Hello,

Please excuse my newbie-ness.  FPP is new to me.

I am running Ubuntu 22.04 server and am wanting to install FPP 7.5 locally.  I used the following commands as the root user.

```
wget -O ./FPP_Install.sh https://raw.githubusercontent.com/FalconChristmas/fpp/v7.5/SD/FPP_Install.sh
chmod 700 ./FPP_Install.sh
./FPP_Install
```

Now it is a successful install but it installs v8.x-master-232-g1746fddb at the time of this writing.  While I am able to run my handful of props with it., I am unable to configure a virtual matrix. When trying to add a Virtual Matrix it selects 'Virtual Matrix by default but you are not permitted to set any data for it.  See Attachment. (I am able to create a virtual matrix in xLights and upload it to FPP but when it plays it does not use the full screen.  It looks like it displays the actual resolution of the matrix, 224x126 in the corner of the screen rather than stretching to fill the entire screen.) See Attachment.

It was suggested that I use FPP v7.5 as 8.x is still in high development.  Can someone assist in telling me how to install v7.5 on a stand alone machine?

Regards,
Joe

![v8 x Add Virtual Matrix Screen](https://github.com/FalconChristmas/fpp/assets/108493995/c7c97079-666f-4aee-8d6f-37d1ff6e8059)

![Virtual Matrix displayed on Monitor](https://github.com/FalconChristmas/fpp/assets/108493995/90436764-9ca2-4c50-9f3c-e5fe374b6ede)

**Comment by cybercop23** [comment]
Try Input/Output -> Pixel Overlay Models and see if you can make any adjustments there.

**Comment by Gilimi-the-Grim** [comment]
Tnank you for the tip.  I will have to read up on that to figure out how that works.  I will get back to you.

Joe

**Comment by Gilimi-the-Grim** [comment]
Unfortunately, That didn't help me.  Any ideas on how to get v7.5 installed?

Joe

**Comment by cybercop23** [comment]
FPP 8 as a show player and what you are trying to do, I think is stable. I don't think 7.5 will give you diff results. 
However if you want.... edit the install script and change the branch to 7.5 : FPPBRANCH=${FPPBRANCH:-"master"}

**Comment by Gilimi-the-Grim** [comment]
I done a fresh install of Ubuntu 22.04 and edited the script to point to the v7.5 branch.  When I open FPP in the browser, I get a message that reads, FPPD not found, Rebuild Required.

When I click the rebuild button, it fails.  I have the output below.  Not being a programmer, it doesn't mean a lot to me.  Am I just chasing my tail here, or is there a fix I can do?  Install a library or something else?

Again, I want to thank you for all the help you have given me.  I do appreciate it very much.

Regards,
Joe

[FPPD Rebuild.txt](https://github.com/FalconChristmas/fpp/files/15031163/FPPD.Rebuild.txt)

**Comment by darylc** [comment]
@Gilimi-the-Grim FPP_Install.sh is intended to be run on Debian, exactly which version of Debian depends on the version of the script you are using.  The script in master would be using Bookworm at this point.
