### ISSUE TITLE
FPP 8 : Testing  causes freezing on Raspi 4

### ISSUE THREAD

**Issue by natepowersphoto** [FalconChristmas/fpp#1833]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 

[v8.x-master-238-gc2a87070 (master branch)](http://192.168.1.50/about.php)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Clicking on status control > testing and enabled testing.....doesnt connect so I turned it off and tried to do Output testing or switch to any other tabs.  I causes the pi to freeze up entirely and has to be restarted by power turning off and on. Replicated multiple times beyond frustration.  Moved back to FPP 7 in hopes to clear this issue. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Comment by OnlineDynamic** [comment]
Please retest with latest FPPv8 build - if still an issue then please upload crash logs

**Comment by darylc** [comment]
Closed due to no response against an alpha version
