### ISSUE TITLE
GUI issue after upgrades/restarts

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1845]
with the last couple of updates, starting that large one... after an upgrade or reboot.. this is what shows up... if i refresh the page it goes away.
![image](https://github.com/FalconChristmas/fpp/assets/23619433/24eaf63d-5344-47af-9383-fae293a510ef)
![image](https://github.com/FalconChristmas/fpp/assets/23619433/11420466-4a3d-4bab-b3e0-24e2e8372eb1)

**Comment by cybercop23** [comment]
![image](https://github.com/FalconChristmas/fpp/assets/23619433/24e66ba7-7fd6-4f55-93f5-491e0bca836a)

**Comment by OnlineDynamic** [comment]
latest commits on master branch should have resolved this - please confirm so we can close issue
