### ISSUE TITLE
FPP v8: ZipArchive Isn't Installed

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1847]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Pi4 with K8-Pi cape running 8.x-master-275-gbc771770 installed via 8.0 pre alpha 3

**Describe the bug and Steps to reproduce**: 
When clicking the zip button at the bottom of the logs view in file manager I'm presented with this error.

```
Fatal error: Uncaught Error: Class "ZipArchive" not found in /opt/fpp/www/api/controllers/files.php:508 Stack trace: #0 /opt/fpp/www/api/lib/limonade.php(430): GetZipDir() #1 /opt/fpp/www/api/index.php(189): run() #2 {main} thrown in /opt/fpp/www/api/controllers/files.php on line 508
```

**Comment by darylc** [comment]
Can't work this one out yet, but it's related to:
fpp@FPP:~ $ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib/php/20220829/zip.so (libcrypto.so.1.1: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/zip.so.so (/usr/lib/php/20220829/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.2.7 (cli) (built: Jul 20 2023 18:02:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

**Comment by darylc** [comment]
Fixed FPP_Install.sh which means this will be fixed next time fppos images are released.
