### ISSUE TITLE
FPP Email breaks during fppos upgrade from base. 6.3 to v7.3.6-2-g8a16ddd9 (v7.3 branch)

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1852]
**FPP Version and Hardware**: 
v7.3.6-2-g8a16ddd9 (v7.3 branch) on Pi

**Describe the bug and Steps to reproduce**: 
I had a few hours to kill this afternoon while doing other things, I decided to try and track down when email notifications in FPP broke. The chart below shows the test cases and results. I don't know exactly why its broken, or the fix yet. It does have to do with authentication though. The problem is I can only test a few times an hour or my ISP locks me out because of failed attempts. :disappointed:
Summary Fresh install 6 it works. As you can see as you are doing upgrades it then breaks. The good news is base 6.3 to Latest v8 fppos and then update to current is OK. A fresh v8 install is OK.

**Expected behavior**: 
In place upgrade should not break email

Test Scenarios
![image](https://github.com/FalconChristmas/fpp/assets/8147459/58035f7c-dc8f-46bd-8e83-205e441a2e78)

**Comment by darylc** [comment]
@patdelaney

**Comment by patdelaney** [comment]
I was using the send test email button after each upgrade. It appears to be some sort of authnetication issue. I'll see If I jhave any logs
