### ISSUE TITLE
HTTP Virtual Display is not working in V8-287

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#1853]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 8.0-287- Raspberry Pi 4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Use FPP Connect and upload V2 sequences and Models to the FPP device
2. Go to channel outputs>Other and add HTTP Virtual Display and make it active.
3. Set device to Remote mode
4. Play sequences
5. Navigate to the Virtual Display page and nothing appears.

**Expected behavior**: 
The HTTP Virtual Display should display,

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
6. Attach to this ticket.

**Comment by darylc** [comment]
@Poporacer Is this still an issue in fpp 8 beta1?

**Comment by Poporacer** [comment]
I will check when I get back home

**Comment by darylc** [comment]
@Poporacer is it fixed by https://github.com/FalconChristmas/fpp/commit/3e55e38449a844fcea03f2a04aadf9e341450c2c ?

**Comment by Poporacer** [comment]
I will check when I get home on Monday, Thanks for Cleaning things up
