### ISSUE TITLE
Crossfade between sequences or fade to black on demand

### ISSUE THREAD

**Issue by ardumiguel** [FalconChristmas/fpp#1854]
Hello. Is it possible to crossfade, or fade to black on demand when running sequence?

For example, if I have a sequence running, or an FX running I'd like to fade to black via a command preset or a physical button.

My main goal here is to bridge my standby sequence and my main show sequence more pleasantly. 

Right now what I have is an FX running in the background and a music playlist. When I press a pushbutton I insert my main show playlist leaving the effect on standby and the music playlist paused. However this happens without any fading at all.

I suspect this could be done with a script that controls the output brightness as well as the volume fading it in the desired time.

Has anyone ever come with an approach for this?

Thanks in advance.

**Comment by darylc** [comment]
I'd call a script from the gpio that calls the API to manually fade the brightness plugin  & audio than have your show playlist reset them to normal levels.

**Comment by ardumiguel** [comment]
> I'd call a script from the gpio that calls the API to manually fade the brightness plugin  & audio than have your show playlist reset them to normal levels.

Wait, is there a brightness plugin? Didn't know that, I thought I'd call the API responsible for brightness.

**Comment by darylc** [comment]
Yes once you install that plugin you get an API call that can handling brightness
![image](https://github.com/FalconChristmas/fpp/assets/7511887/9eb1305e-add5-4ece-ba49-f74ba05f969e)

**Comment by ardumiguel** [comment]
> Yes once you install that plugin you get an API call that can handling brightness
> ![image](https://github.com/FalconChristmas/fpp/assets/7511887/9eb1305e-add5-4ece-ba49-f74ba05f969e)
> 

Thanks. I guess I'll have to use a for loop of some kind in the script right?
