### ISSUE TITLE
Fatal Error when change Audio Output Device

### ISSUE THREAD

**Issue by jeremy-rafflin** [FalconChristmas/fpp#1855]
Hi, I have install FPP on a raspberry pi. I want to configure the Audio Output Device in 'FPP Settings' -> 'Audio/Video'. in my select fiel I choose other than Dummy , in console I have en PUT request on 'http://fpp.local/api/settings/AudioOutput' with this body "2". 
The response is : 
`
Fatal error: Uncaught Error: Call to undefined function SetAudioOutput() in /opt/fpp/www/api/controllers/settings.php:119 Stack trace: #0 /opt/fpp/www/api/lib/limonade.php(430): PutSetting() #1 /opt/fpp/www/api/index.php(185): run() #2 {main} thrown in /opt/fpp/www/api/controllers/settings.php on line 119
`

my config : 

FPP Version: | 7.5-5-gda02180d
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v2023-12
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 000000001d364e53
Kernel Version: | 6.1.21-v7+
System Boot Time: | 2024-05-31 18:43:17
fppd Uptime: | 04:08
Local Git Version: | da02180 ChangeLog
Remote Git Version: | da02180

**Comment by darylc** [comment]
Closed due to no response
