### ISSUE TITLE
Virtual Display stops working when channel input enabled in V8-287

### ISSUE THREAD

**Issue by schreyack** [FalconChristmas/fpp#1857]
**FPP Version and Hardware**: 
FPP 8.0-287 running on Ubuntu

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce.

1. Use FPP Connect and upload V2 sequences and Models to the FPP device
2. Go to channel outputs>Other and add Virtual Display and make it active.
3. Connect a monitor to the appropriate port on the FPP hardware.
4. Play a sequence and confirm that you see the sequence playing on the monitor.
5. Now, go to channel inputs and add universe(s) and channels that match all output channels (so that FPP can bridge the input to the output) and make it active.
6. Play the sequence again and the monitor will be blank.

**Expected behavior**: 
The monitor should display the output.

**Additional context**: 
The objective is to send xFade output to the FPP so that the output from xFade can be seen on the monitor of the FPP and FPP should then bridge the input from xFade to the controllers configured for output in FPP.

**Comment by darylc** [comment]
Is this still an issue in FPP 8 beta 1?

**Comment by schreyack** [comment]
i can't get the newest version to build... see log attached.
[Untitled document.txt](https://github.com/user-attachments/files/16401656/Untitled.document.txt)

**Comment by darylc** [comment]
You probably need the latest FPPOS.  Since you are on Ubuntu, you'd need to re-run the FPP_Install script from a clean ubuntu install.

**Comment by schreyack** [comment]
I am still unable to get the latest version to build on ubuntu 22.04... I did try with what I think is the latest FPP_Install script but getting a make error: make: *** [Makefile:85: mediaoutput/SDLOut.o] Error 1
[install log.txt](https://github.com/user-attachments/files/16416820/install.log.txt)

**Comment by dkulp** [comment]
22.04 is possibly too old now.    I've been working on getting it running on 24.04 and it seems to be OK now.

**Comment by schreyack** [comment]
i'm happy to try 22.10 if that is working - last time (about 6 months ago) when I tried 22.10 it failed, so I went back to 22.04.

**Comment by darylc** [comment]
@schreyack Is this still a current problem?

**Comment by schreyack** [comment]
I'm blocked on this while waiting for 24.04 to be able to build.  i think maybe this commit (https://github.com/FalconChristmas/fpp/commit/c258d002979f63b73c10f087eaa289cb42be919c) got missed somehow?  it just needs to be merged (i think).

**Comment by darylc** [comment]
@schreyack that commit is in master right now

**Comment by schreyack** [comment]
The issue is resolved in 8.x-master-441-ga514ef1a. Thanks!
