### ISSUE TITLE
Turning Off Logging

### ISSUE THREAD

**Issue by stevefromNewcastle** [FalconChristmas/fpp#1859]
FPP 7.5, raspberry Pi 4, running in kiosk mode.

I have a quick question, I was wondering if there is a way to turn off the logging?

I have a remote FPP instance that is running a show. Often the controller is left on while the LED drivers are turned off. Over time the log builds up as it cannot ping or connect to the controllers. Eventually this fills up the SD card and stops the FPP player booting thus not running the show.

Sys log is runing to 8-10Gb with the following messages.
May 13 11:37:13 FPP fppd[1725]: 2023-05-13 11:37:13.334 (1818) [ChannelOut] /opt/fpp/src/channeloutput/UDPOutput.cpp:455: sendmmsg() failed for UDP output (key: 1  Socket: 17  output count: 281/320) with error: 0  Success
May 13 11:37:13 FPP fppd[1725]: 2023-05-13 11:37:13.334 (1818) [ChannelOut] /opt/fpp/src/channeloutput/UDPOutput.cpp:455: sendmmsg() failed for UDP output (key: 1  Socket: 17  output count: 281/320) with error: 11  Resource temporarily unavailable

I realize logging network issues is important, but is there a way to turn this off.
I do have a script that runs on boot that should clear the logs but for some reason this doesn't seem to be doing its job everytime.
I have turned of monitoring in the channel outputs.
Thanks for any help.
Cheers
Steve

**Comment by darylc** [comment]
No, there is not a way to disable logging.  The most you can do is set the log levels to error only. http://yourfpp/settings.php#settings-logs
