### ISSUE TITLE
FPPv8: Plugin fpp_install.sh not running on install of the plugin (Jukebox)

### ISSUE THREAD

**Issue by PiSignage** [FalconChristmas/fpp#1869]
FPP Version and Hardware: Pi4B 8.x-master-324-g66745d8c

Describe the bug and Steps to reproduce:
Content Setup / Plugin manager / Jukebox
When installing the Jukebox plugin the fpp_install.sh script does not run. What am i doing wrong?

Only way to get the script to run is to do it in the shell

**Comment by darylc** [comment]
The problem is that fpp_install.sh does not have the executable bits set on it in your repo.

Eg:
fpp@fpp:/tmp/fpp-jukebox$ ls -l scripts/
total 4
-rw-rw-r-- 1 fpp fpp 937 Jul  4 18:27 fpp_install.sh

**Comment by PiSignage** [comment]
Thank you for the quick replay. I have made the file executable in the repo
