### ISSUE TITLE
Fop

### ISSUE THREAD

**Issue by corp-jones-damarcus** [FalconChristmas/fpp#1870]
https://github.com/FalconChristmas/fpp/blob/66745d8c469929f0f1a2e2c4dd8605158550490d/src/fseq/FSEQFile.cpp#L781

**Comment by patdelaney** [comment]
I don't understade the title of this issue or the proposed fix. Does this have any impact on Documentation and what would I be testing or looking for ?  I'm not sure of the downstream effect of this change.  Can you add a comment>

Thank
