### ISSUE TITLE
FPP GPIO configuration Possible incorrect Port configuration issue for PWM setup.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1872]
# Please answer the following:
**FPP Version and Hardware**: 
*FPP V7 and V8 on a Pi*
**PWM Questions:**

I think that the lookup table for GPIO pins in Channel Output may be incorrect according to some online PI GPIO documentation.  While setting up GPIOs,  P1-33 (GPIO 13) is not recognized as PWM. It does recognize P1-13 (GPIO 27) as a PWM but according to the online documentation that is not a PWM. I’m guessing that it’s a typo in the look up table.

**My second question**: Is this port truly PWM and is it configurable? I’m chatting with guys in the Zoom Room the user had an oscilloscope on the PWM pins there was no output.
![image](https://github.com/FalconChristmas/fpp/assets/8147459/6ae864ee-5366-4e1f-a21c-ae7c45037131)

![image](https://github.com/FalconChristmas/fpp/assets/8147459/3325b3cb-292f-4e8d-8e51-3ca5d3661021)

**Comment by OnlineDynamic** [comment]
@patdelaney Looking at code the lookup of pin capabilities is different for pi5 compared to other pis, do you know which flavour of pi they were testing with?

**Comment by bobreese** [comment]
I believe this was a Pi4 from the conversation in the zoom room

**Comment by OnlineDynamic** [comment]
were they getting PWM ok on the GPIO18 (P1-12) pin on the scope?
