### ISSUE TITLE
FPP v8: Restarting FPPD on a BBB with Octoscroller causes LED panels to trun on, You need to go into toggle test mode to turn them off.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1873]
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 8.x master running on BBB*

**Describe the bug and Steps to reproduce**: 
Restarting FPPD on a BBB with Octoscroller causes LED panels to trun on, You need to go into toggle test mode to turn them off. This does not happen if your panels are configured with Colorlight. I can reproduce the issue on 2 different systems. One with 4 P10 panels and one with 9 P5 panels.  If you upload anything to that BBB and FPD restarts then the panesl turn on.

**Expected behavior**: 
FPPD should restart and not effect the panels.

**Additional context**: 
Video link
https://youtu.be/hKd_8BypcEk

**Comment by ghormann** [comment]
Sending "All Lights Off" command also works.

**Comment by patdelaney** [comment]
@ghormann "Sending "All Lights Off" command also works."  as a workaround you mean right?

**Comment by darylc** [comment]
@patdelaney Is this still an issue on beta1 image?

**Comment by patdelaney** [comment]
This was fixed with:
--> [a8c727e8](http://bb4.local/changelog.php#) - Daniel Kulp         - 2024-07-29 15:20:06 -0400 - Hopefully get BBMatrix memory initialized and mapped properly (HEAD -> master,

Tested on two different BBB panel matrixes
