### ISSUE TITLE
ci-dmx.json not backed up...

### ISSUE THREAD

**Issue by dkulp** [FalconChristmas/fpp#1875]
A semi-placeholder for now....

With the new support for DMX INPUT, there are now two files used for configuring inputs.  The ci-universes.json for the UDP based inputs and ci-dmx.json for dmx.     However, the backups currently only grab ci-universes.json.

In the backup.json files, the channelOutputs is an array of "files" and can thus be easily expanded to add additional outputs.  However, the channelInputs is the ci-universes.json file directly.  Thus, adding ci-dmx.json to the backup would require a bit more significant changes and doing so in a backwork compatible way may be challenging.

I'd LIKE to make the channelInputs match the channelOutputs, but then that would be incompatible with previous backups.   Maybe make it flip only if cxf-dmx.json exists and has something enabled.   Not really sure.

**Comment by dkulp** [comment]
@jaredb7 I'd like your thoughts on this.

**Comment by jaredb7** [comment]
I can make that work, There's a fpp_backup_version element in the backups that I've been using for some very small backwards compatibility stuff already.

Channel Inputs in new backups will have the same format as channel outputs (array of files) and well use the fpp_backup_version  flag to massage the the old layout up to match the new one for anything < 8.0.

I'll have a look over the next few evenings.
