### ISSUE TITLE
Pi4 Touchscreen 8.x-master-354-ge34595c7 Images

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1882]
Ever since the prepare for Beta1 images, my touchscreen does not display images correctly.
The image shows up twice (one above the other) and flashes.
I have no pixels installed on this Pi.
The upgrade logs have

cpp -DCLOCK_FREQUENCY=2400000 vc4-kms-dpi-fpp.dts | dtc -@ -I dts -O dtb -o vc4-kms-dpi-fpp-pi3.dtbo 
vc4-kms-dpi.dtsi:38.15-43.4: Warning (unit_address_vs_reg): /fragment@102: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:45.15-53.4: Warning (unit_address_vs_reg): /fragment@103: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:55.15-60.4: Warning (unit_address_vs_reg): /fragment@104: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:62.15-72.4: Warning (unit_address_vs_reg): /fragment@105: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:74.15-82.4: Warning (unit_address_vs_reg): /fragment@106: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:84.15-92.4: Warning (unit_address_vs_reg): /fragment@107: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:94.15-99.4: Warning (unit_address_vs_reg): /fragment@108: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:102.3-103.28: Warning (gpios_property): /__overrides__:backlight-gpio: property size (25) is invalid, expected multiple of 4
vc4-kms-dpi.dtsi:101.16-110.4: Warning (gpios_property): /__overrides__: Missing property '#gpio-cells' in node /fragment@107/__dormant__/pwm_pins or bad phandle (referred from backlight-pwm-gpio[0])
  also defined at vc4-kms-dpi-fpp.dts:51.16-73.4
cpp -DCLOCK_FREQUENCY=7200000 vc4-kms-dpi-fpp.dts | dtc -@ -I dts -O dtb -o vc4-kms-dpi-fpp-pi4.dtbo 
vc4-kms-dpi.dtsi:38.15-43.4: Warning (unit_address_vs_reg): /fragment@102: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:45.15-53.4: Warning (unit_address_vs_reg): /fragment@103: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:55.15-60.4: Warning (unit_address_vs_reg): /fragment@104: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:62.15-72.4: Warning (unit_address_vs_reg): /fragment@105: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:74.15-82.4: Warning (unit_address_vs_reg): /fragment@106: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:84.15-92.4: Warning (unit_address_vs_reg): /fragment@107: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:94.15-99.4: Warning (unit_address_vs_reg): /fragment@108: node has a unit name, but no reg or ranges property
vc4-kms-dpi.dtsi:102.3-103.28: Warning (gpios_property): /__overrides__:backlight-gpio: property size (25) is invalid, expected multiple of 4
vc4-kms-dpi.dtsi:101.16-110.4: Warning (gpios_property): /__overrides__: Missing property '#gpio-cells' in node /fragment@107/__dormant__/pwm_pins or bad phandle (referred from backlight-pwm-gpio[0])
  also defined at vc4-kms-dpi-fpp.dts:51.16-73.4
cp -f vc4-kms-dpi-fpp-pi3.dtbo /boot/firmware/overlays
cp -f vc4-kms-dpi-fpp-pi4.dtbo /boot/firmware/overlays
rm -f  vc4-kms-dpi-fpp-pi3.dtbo vc4-kms-dpi-fpp-pi4.dtbo
>>SUCCESS upgraded to config version 88
Up to date at config version 88

![RPIWS281x](https://github.com/user-attachments/assets/8e1eedcc-26f4-451f-aa54-38ef9af61c28)

https://github.com/user-attachments/assets/a81fdd58-f465-4a35-98b2-f6bc03309a75

**Comment by dkulp** [comment]
Reconfigure the virtual matrix/overlay to use HDMI-A-1 and not fb0.   With the new OS, using fb0 is deprecated and does some really strange things.   xLights does need to be updated to handle this change, hopefully later this week.

**Comment by bobreese** [comment]
I did what you asked.
Now I do not get the startup picture and my video does not display when run.
Here is a backup of this Pi4

Also have this:
2 FPPD WARNINGS: Could not initialize output type RPIWS281X. Check logs for details.,RPIWS281x: No output pin configuration for: PiHat

[Test8x_all-backup_v8_20240724144115.json](https://github.com/user-attachments/files/16366834/Test8x_all-backup_v8_20240724144115.json)

**Comment by bobreese** [comment]
I tied the DSI-1 in Channel Outputs.
The video is working again
The pictures are still messed up.....
Under troubleshooting commands I see this

Command: test -e /dev/fb0 && echo "/dev/fb0" && fbset -s -fb /dev/fb0 ; test -e /dev/fb1 && echo "/dev/fb1" && fbset -s -fb /dev/fb1
/dev/fb0

mode "800x480"
    geometry 800 480 800 480 16
    timings 0 0 0 0 0 0 0
    rgba 5/11,6/5,5/0,0/0
endmode

**Comment by bobreese** [comment]
So I finally got the touchscreen working properly with my pictures and video.
I am including the backup of the PI4 with V8 so you have some reference to the setup.
[FPP8test_all-backup_v8_20240807151059.json](https://github.com/user-attachments/files/16534001/FPP8test_all-backup_v8_20240807151059.json)
