### ISSUE TITLE
Can we add a "debounce" value to GPI inpute

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1886]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a "debounce-like" timer on FPP GPIO inputs?

**Describe the solution you'd like**
I user wants to user majic wands with an IR sensor, the problem that he explaned was when the Reciever got the signal from the wand it sent several GPIO triggers.  I propose that we add a timer or counter to accept the first trigger and then ignore the next triggers in a during a waiting period Make it user definable in miliseconds 0 - 300000 ms (5 min)

**Describe alternatives you've considered**
we couls use a script that writes a timestamp when it triggered and then each subsequent trigger it checks the timestamp and then if the lookup value 100ms for example then that triggers another action.  I do something similar for the Zombie containment center.

**Comment by darylc** [comment]
FYI FPP already has a static debounce time of 100000 usecs, it can be tweaked in gpio.cpp - the following line

#define GPIO_DEBOUNCE_TIME 100000

I suggest the user do that, since it seems unlikely this will ever get implemented?

**Comment by patdelaney** [comment]
ok I'll test it out

**Comment by OnlineDynamic** [comment]
looks like Dan added this with https://github.com/FalconChristmas/fpp/commit/0328731415b8e0a42242f2ee42f367359f4b6ef7
