### ISSUE TITLE
FPPV8 the Math function =(b3/127)*100  is case sensitve. If you use B3 it will crash FPP  (midi plugin)

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1890]
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP v8 running on PI*

**Describe the bug and Steps to reproduce**: 
If you configure the brightness plugin with a remove midi command with as =(B3/127)*100  instead of =(b3/127)*100,  it will crash fpp when you try to adjust the brightness with a midi knob
![image](https://github.com/user-attachments/assets/e0167b06-3155-40f8-bc70-03aa23046253)

[fpp-BBB-8.x-master-329-g82c2ec8b-M1-414BBBK0351-2024-07-26_17-52-51.zip](https://github.com/user-attachments/files/16397295/fpp-BBB-8.x-master-329-g82c2ec8b-M1-414BBBK0351-2024-07-26_17-52-51.zip)

**Expected behavior**: 
It should not crash

**Comment by darylc** [comment]
I started to have a look at this one.  It's almost certainly a bug in fpp-brightness plugin, not FPP 8 or the fpp-midi plugin.  I can't understand the fpp-brightness code enough to work on this one.

**Comment by patdelaney** [comment]
Closed and recreated it in Midi Plugin
