### ISSUE TITLE
High CPU utilization at idle

### ISSUE THREAD

**Issue by JamesMoore2090** [FalconChristmas/fpp#1891]
FFP 8.x-master-371-g1fe9c75e
Raspberry Pi (Pi 4) & BeagleBone Black

Updated both a pi and BBB last night noticed that the CPU utilization on the Multisync tab was randomly hitting 100% on both devices.

Both devices are at idle with nothing but fppd running. Started looking into what process was hogging the CPU and it appeared "php-fpm8.2" was ramping up to 30-40%. 

Attached are the logs from the BBB. There is an issue with exporting the PI logs.

[FPP_Logs_20240727.2052.zip](https://github.com/user-attachments/files/16401463/FPP_Logs_20240727.2052.zip)

**Comment by cybercop23** [comment]
Did you have  Auto Refresh tuen on, ont he Multisync page? That will do it. Try htop for a closer look.

**Comment by JamesMoore2090** [comment]
I do. 

<img width="1428" alt="Screenshot 2024-07-27 at 7 12 51 PM" src="https://github.com/user-attachments/assets/d4e54e8f-6c9e-46f0-81ee-99c05405ad3e">


I captured these as well. 
<img width="1470" alt="Screenshot 2024-07-27 at 7 16 39 PM" src="https://github.com/user-attachments/assets/5da4cb03-28a2-4b0b-b693-a57b94a61086">
<img width="1470" alt="Screenshot 2024-07-27 at 7 16 52 PM" src="https://github.com/user-attachments/assets/d989fc43-0b4c-45b5-822c-115ea0e8e06b">
<img width="1470" alt="Screenshot 2024-07-27 at 7 17 05 PM" src="https://github.com/user-attachments/assets/6326b753-c73b-478c-bb1d-ed02fd49ece6">


I am not sure if this will affect the show or not. Just idle testing. Also should the auto refresh not be on as standard practice?

**Comment by cybercop23** [comment]
It will... tuen off Auto Refresh and watcvh HTOP. The auto refresh should only be used for a brif time and DO NOT leave your screen on that.

**Comment by JamesMoore2090** [comment]
Understood. turning it off has stabilized the cpu percentage to under 5%. I am ok with closing this issue.
