### ISSUE TITLE
Zip Archive not found on PI

### ISSUE THREAD

**Issue by JamesMoore2090** [FalconChristmas/fpp#1892]
FPP version 	8.x-master-371-g1fe9c75e
Platform:	Raspberry Pi (Pi 4)

Trying to export logs for the a different issue came cross this:
"Fatal error: Uncaught Error: Class "ZipArchive" not found in /opt/fpp/www/api/controllers/files.php:508 Stack trace: #0 /opt/fpp/www/api/lib/limonade.php(430): GetZipDir() #1 /opt/fpp/www/api/index.php(190): run() #2 {main} thrown in /opt/fpp/www/api/controllers/files.php on line 508"

Steps to reproduce:
1. Select "Content setup"
2. Select "File Manager"
3. Select "Logs"
4. Select "ZIP"
5. Error

<img width="1582" alt="Screenshot 2024-07-27 at 5 00 26 PM" src="https://github.com/user-attachments/assets/2da92121-05a8-4fce-914f-0e9e84c83ff9">

[Uploading apache2-error.log…]()

**Comment by dkulp** [comment]
Are you using the latest "beta1" fppos image?    I cannot reproduce this with beta1.   (OS level 2024-07)

**Comment by JamesMoore2090** [comment]
Yes. I also rebooted the PI just incase something was hung. No joy. 

<img width="1424" alt="Screenshot 2024-07-27 at 7 10 09 PM" src="https://github.com/user-attachments/assets/a80b16e3-44d2-4565-99f5-a4bc8b14b781">
<img width="1428" alt="Screenshot 2024-07-27 at 7 12 51 PM" src="https://github.com/user-attachments/assets/500c7849-b26c-49eb-94da-327a25544114">

**Comment by JamesMoore2090** [comment]
I build out a spare SD card and started up a new PI4. Went through the initial setup. The zip button worked. I also backed up the original issue pi and then restored it to the new. The zip button again worked. 

I am not sure what is going on with the original PI.
