### ISSUE TITLE
API command "Insert Random Item From Playlist" only randomises for playlists > 2 items

### ISSUE THREAD

**Issue by PeteMatthews** [FalconChristmas/fpp#1893]
FPP 7.5-5-gda02180d on Pi 2, although I can see the problem code is still there in git.

**Describe the bug and Steps to reproduce**: 
Have at least 2 sequences on FPP (SeqA and SeqB)
Create a playlist with 2 entries (PlayA, consisting of SeqA then SeqB)
Call API "Insert Random Item From Playlist", with PlayA as the argument, immediate mode true
FPP starts playing as expected, but the sequence played is _always_ the first in the playlist (SeqA).

**Expected behavior**: 
FPP should play the 2 sequences with equal(ish) frequency.

**Minor investigation**:
It seems this is deliberate, if a little confusing. 
The playlist code checks the length of the playlist, and will only randomise if length is greater than 2. I assume there was a reason for this in the past (maybe before this specific API existed?), but it's definitely producing a bug now.

https://github.com/FalconChristmas/fpp/blob/a4db27c5654bd6f30096dccf92ef2642df7a2a54/src/playlist/Playlist.cpp#L1179

Any chance someone could take a quick look? 

Thanks :)

**Comment by darylc** [comment]
Yeah theres all sorts of problems with randomness in FPP, eg #934 which has been waiting almost 4 years for a fix :/

**Comment by darylc** [comment]
@PeteMatthews Fixed in master for FPP v8.0 release.  Thanks for the code pointer, turned out to be elsewhere but much appreciated as it got me started.
