### ISSUE TITLE
FPPV8 but it is in FPPv7 as well. Accidentally changing the boot dick in storage and resetting back to the original setting, before rebooting puts fpp in initial setup loop

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1895]
**FPP Version and Hardware**: 
Example: *FPPV8 but it is in FPPv7 on Pi*

**Describe the bug and Steps to reproduce**: 
Go o Settings -> Stoage ->Storage Device
Take not of the current setting, click the dropdpwn to see what is there.
Change the storage setting but don't reboot
Change the storage back to the original setting and reboot
FPP comes back as initial setup page.
None of the changes are saved, I'm guessing it mounted a no read only Disk.

**Expected behavior**: 
The use should be able to log i and reset the storage device, 

**Additional context**: 
We should take into account that a user cna be swithcing between NVMe and SD.
I have to think that there is a way to fix this via SSH so the user does not have to reimage the disk.
If it was an unsucessful NVMe mount then how does the user withc it back to SD card via cli.

I have been burned by this several times in the last few months. Most Recently with NVMe booting

**Additional Attachments**
![image](https://github.com/user-attachments/assets/f41dd454-dfcc-4575-9b0e-9fc963be115e)
![image](https://github.com/user-attachments/assets/0646e568-5564-4e9a-b116-f3a2d6fc2ec6)

**Comment by darylc** [comment]
@patdelaney Did a message asking you to reboot come up in between the two changes?  I think it would be a bunch of work to fix this edge case (that I expect was caused ignoring the reboot prompt?) for very little gain, eg in a perfect world sure we spend time to fix it, but in reality maybe 0 users per year hit this?

**Comment by darylc** [comment]
no reply
