### ISSUE TITLE
FPPv8  Flash to NVMe and Clone to NVMe Descriptions don't make sense  See note below for more information

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1896]
**FPP Version and Hardware**: 
 *FPPv8 master Beta1 on Pi*

**Describe the bug and Steps to reproduce**: 
The Text in the NMVe Actions: references "See note below for more information"  There doesn't appear to be any information below.
I'm guessing that Flash to NVMe copies SD card to NVMe and then makes NVMe bootable?
Im' guessing that Clone to NVME just moves that datafiles to NVMe, but you are still booting from SD card.

**Expected behavior**: 
We should impove the text to clear state what each button does.

**Additional context**: 
A more detailed descriotion of how to setup NVMe would be great in the F1 help

**Additional Attachments**
![image](https://github.com/user-attachments/assets/c3b82193-048b-43f9-a35b-349c31fe939c)

.

**Comment by darylc** [comment]
@patdelaney Can you please specify exactly what text changes you want made?

**Comment by darylc** [comment]
No feedback received, I made some minor tweaks, closing.
