### ISSUE TITLE
FPP v8 - Fpp Mon Plugin causing FPPD to repeatedly restart

### ISSUE THREAD

**Issue by AGFazio** [FalconChristmas/fpp#1897]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 8 on Pi4

**Describe the bug and Steps to reproduce**: 
After installing FPP  Monitor Plugin, FPPD will restart itself about every minute or so.
Uninstall FPP Mon Plugin and issue stops.
[ffpd.log](https://github.com/user-attachments/files/16406010/ffpd.log)

**Expected behavior**: 
FPPD not restart continuously

**Comment by darylc** [comment]
@AGFazio Can you try uninstalling all other plugins to rule those out?  I see there are at least a couple of others installed.

**Comment by darylc** [comment]
@AGFazio Closing this issue.  Please open issues related to FPP Mon at the FPP Mon project: https://github.com/KulpLights/fpp-FPPMon/issues
