### ISSUE TITLE
8.x-master-398-g32fd7fc6 - Invalid "post_max_size" setting. Invalid quantity "4G": value is out of range

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1905]
Invalid "post_max_size" setting. Invalid quantity "4G": value is out of range

Fresh install of V8

Logs included

[FPP_Logs_20240801.0140.zip](https://github.com/user-attachments/files/16448734/FPP_Logs_20240801.0140.zip)

**Comment by patdelaney** [comment]
What did you do to get this message? What hardware is involved?
The more information in the issue, the quicker is may be to reproduce and get fixed.
Thanks
Pat

**Comment by darylc** [comment]
@bobreese  I cannot replicate this error on a fresh install of FPP 8 beta 1 on a Pi 4.  This particular error was solved in FPP 8 already, so I am assuming you just need to do a fresh install of FPP 8 beta 1.

**Comment by bobreese** [comment]
Fresh install of 8 and updated to 8.x-master-406-ga60c3ea1
No more errors... Closing
