### ISSUE TITLE
FPP 8.x-master-398-g32fd7fc6 Kiosk Mode only shows "Disable"

### ISSUE THREAD

**Issue by DonMc33** [FalconChristmas/fpp#1906]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 

FPP Version:  8.x-master-398-g32fd7fc6
Platform:  Raspberry Pi (Pi 4)
FPP OS Build:  v2024-07
OS Version: |Raspbian GNU/Linux 12 (bookworm)

When going to Status Control>FPP Settings>System to enable Kiosk Mode, even though Kiosk Mode has not been installed it only gives the option to "Disable".  There is no option to install.

**Expected behavior**: 
The option to install Kiosk mode would be presented.

Screenshot of System page attached
![Screenshot 2024-08-01 100650](https://github.com/user-attachments/assets/3ea69a36-2b6a-46e3-b527-4af8ba4435e7)

**Comment by darylc** [comment]
I cannot replicate this on a fresh install of FPP 8.0 beta 1 on a pi 4.

![image](https://github.com/user-attachments/assets/2b698461-56c8-4dfd-888b-e6042ab93072)

A couple of errors in the log file give me impression that you are not running a fresh install of FPP 8.0 beta 1?  Can you please try that.

**Comment by DonMc33** [comment]
ISSUE RESOLVED.  Installed fresh install as suggested and KIOSK Mode now installs and works as intended.  I had used the upgrade function in FPP Help, upgrading from the Alpha 1 version.

Many thanks for your help!
