### ISSUE TITLE
Ability to pause and/or start a sequence at any point

### ISSUE THREAD

**Issue by schreyack** [FalconChristmas/fpp#1907]
**Is your feature request related to a problem? Please describe.**
I wish I could pause a playing sequence and/or start a sequence at any point (not just the beginning).  Technically, two different asks, but related.  I perform my shows live, and typically I sequence them as a continuous 20 minute show (so that the audio and lights can be seamless).  I live in fear that something will happen mid show (a technical problem that causes the show to stop) and I don't have a way to start back up mid show.  Also when I'm practicing the show, it makes it hard to not be able to repeat a given section.

**Describe the solution you'd like**
1. Add a pause button 
2. Ability to drag current playing indicator to specific location and start playing from that point (and/or a text input box that would indicate "start playing at: mm:ss").

![Screenshot 2024-08-01 at 8 55 47 AM](https://github.com/user-attachments/assets/61e4f174-f563-403c-a88b-ead9eb926364)

**Describe alternatives you've considered**
I don't believe there are any.

**Comment by darylc** [comment]
FPP is certainly not designed to be used in the way you are trying to use it, but having said that:

Pause is already requested in #1700 but I cannot see it being implemented any time soon.

Starting a sequence at a particular spot seems possible already via the API, 

![image](https://github.com/user-attachments/assets/81a2c53e-267f-45f9-86c0-5a5da4e97bac)

**Comment by darylc** [comment]
@schreyack FYI if you play a sequence for the testing page you can pause - this might be useful to you.  http://fpp.local/testing.php#tab-sequence

**Comment by schreyack** [comment]
interesting, i hadn't looked at that page before.  seems like it only plays the sequence not the audio file, so it wouldn't work for my actual shows, but good for a quick test.
