### ISSUE TITLE
Custom Model, Model Data Chart, Missing Columns

### ISSUE THREAD

**Issue by Fonzi03** [FalconChristmas/fpp#1909]
Win 11, 22631
XLights 2024.13

Cannot reproduce on another custom model but 100% reproducible on the particular model in my show directory. I am uncertain of the exact order of steps I took to get into this state but I did do the following: 

Create a custom model
name custom model
select edit model data
changed width, height, depth
cycled through a few of the tabs for depth 
clicked OK
re-opened click model data
added a few pixels on one of the tabs
cut pixels from that tab and pasted on another
increased the value for depth to 31
added more pixels on multiple depth pages
cut and paste a few times between tabs as I defined the shape
clicked OK and save periodically throughout 
closed XLights, reopened and resumed work later

At some point I noticed the Depth tabs were not populating to match the specified variable. 
The variable said 31, visibly you could only see 15
I changed the variable to some number above 31 and the tabs showed up
from this point forward, every time this model data chart is opened only 15 (this was the last tab I had pixels on so far)

if a pixel is on a tab that will become the maximum number of visible tabs. IE add a pixel to tab 26 and when you close then reopen the model data tab 26 is the maximum shown even if the depth variable is set higher than 26. 

removing a pixel causes the same thing to happen, remove from tab 26 and you next furthest pixel is on 20, upon closing and reopening the maximum number of tabs shown is now 20. 

I'm have not yet finished it but the attached model is the one I am able to consistently reproduce this on. 
[Articulating Reindeer.zip](https://github.com/user-attachments/files/16481094/Articulating.Reindeer.zip)

**Comment by darylc** [comment]
Please log this against xlights https://github.com/xLightsSequencer/xLights/issues rather than FPP.

**Comment by Fonzi03** [comment]
Sorry about that, wasn't thinking when I logged this. Will drop in the XLights instead.

________________________________
