### ISSUE TITLE
Change DSCP Tag on Sync Packets to EF (46) from CS0 (00)

### ISSUE THREAD

**Issue by krhodus** [FalconChristmas/fpp#1910]
**Is your feature request related to a problem? Please describe.**
Changing the DSCP tag on Sync packets would allow for QoS to be implemented in larger show networks to ensure that sync packets are protected and priortized through the network above standard traffic. Many switches natively will treat EF packets with priority with QoS enabled or already have EF setup as a priority queue when enabling DSCP-based QoS. 

**Describe the solution you'd like**
Set DSCP tag to EF (dec 46) on sync packets. This would fall in line with other network based protocols utilizing sync-style messages like PTP (IEEE1588). 

**Describe alternatives you've considered**
Manually protect the sync packets by utilizng ACLs/ ingress filters on edge switches.

**Comment by darylc** [comment]
This is a very edge case request.  We would be open to receiving a pull request to implement this, but I cannot see it being implemented otherwise.
