### ISSUE TITLE
Setting brightness for LED Panel w/ Colorlight card.

### ISSUE THREAD

**Issue by thekameleon** [FalconChristmas/fpp#1911]
**Is your feature request related to a problem? Please describe.**
I am sure this has been asked before, but I see a need for setting the LED Panel when using a Colorlight card. So, with xLights managing channel configuration, the start channel of my LED Panel can change if I move or adjust props. This means I need to remember to chase the Out Processor to reduce the brightness to the level I want.

**Describe the solution you'd like**
Have a brightness setting like the OctoScroller for Colorlight controlled LED Panels... Or in the Out Processor, be able to specify the LED Panel Start Channel as opposed to manually typing it in. This way when xLights changes a start channel configuration the Output Processor will change with it. There could be better ideas to handle this, so if you guys think of something better, go for it.

**Describe alternatives you've considered**
I have to manually verify the start channel every time I upload a sequence with FPP Connect in xLights to verify that the start channel did not change.  If it did change, then I must change manually and restart FPP.

**Comment by darylc** [comment]
The main brightness is controlled by the colorlight card in ledvision.  You can permanently set it there.  If you don't want to do it there you can set it in xlights.  I don't see us implementing an additional place to set brightness in fpp.

**Comment by darylc** [comment]
If you really want to do keep doing it the way you are doing it without the channels changing, just make sure your fpp controller containing the matrix is at the top of your controller list in xlights, then it will always be channel 1.

**Comment by thekameleon** [comment]
Setting my various LED panels to the 1st channel isn't practical as my layout changes between Halloween and Christmas.

I'll write it script. No big.

**Comment by dkulp** [comment]
As mentioned above, you REALLY want to set the brightness in LEDVision, not FPP or xLights, if at all possible.    By setting it in LEDVision, the panels can continue to display the full 256 shades for each color which will keep images and such looking nicer.   If you set the brightness using the brightness plugin or in xLights, the number of shades for each color is significantly reduced and can/will cause images to wash out.
