### ISSUE TITLE
FPP ignore universe count and size

### ISSUE THREAD

**Issue by ECAkshit** [FalconChristmas/fpp#1912]
Hello everyone,

I am using Xlights software for generate light patterns, which give me .fseq file format.

Actually  I am working on one project using ESP32 and RGB led Strips. In my hardware setup there is two board means two esp32 hardware and each and every had RGB led strips, both hardware connected with each other using RS485 communication protocol.

So in .fseq file leds are need to be connected in series connection right, so when i create one sequence pattern file and run on my hardware it fully run on one board, but i want run that file like sequence for both board like started from first board and continue to second board and end it there like leds are in series but both boards connected with each other using RS485 communication so it's not working like that as i understand.

I thoght if i have universe count and sizeof universe then i make that two board different universes and apply logics based on that so i can run single sequence file in both hardware like series connection. But i found that Xlights/FPP ignores Univers count and Sizeof universe.

So can any one have any idea or solution for that so i can run single .fseq file in both hardware like both hardware leds are act as connected in series.

Thank You.

**Comment by darylc** [comment]
I've read what you wrote 3 times, but I'm struggling to work out what you are trying to do with FPP. Modern FSEQ files do not contain universes, just raw blocks of channels.

**Comment by ECAkshit** [comment]
Hello @darylc 

Thank you for your response on my query.

Yes, you are right modern FSEQ file ignore universes. So can you have any other idea or solution for my query what i need to do exactly for my project workflow as i explain before?

It's very helpful to me if is there any solution for that.

Thank you.

**Comment by darylc** [comment]
@ECAkshit If you want to run the same sequence file on each, you just select what channels you want to output from that in your software. If you are using FPP then you configure the channel outputs to use those channels.
