### ISSUE TITLE
V8 Backups Link Broken

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1915]
8.x-master-430-gbba4ca43
Raspberry Pi (Pi 4)
v2024-07
The link to FPP Backups under Status/Control does not work.

AH01071: Got error 'PHP message: PHP Parse error:  Unmatched '}' in /opt/fpp/www/backup.php on line 1688'

**Comment by darylc** [comment]
@bobreese @jaredb7 This was my bad. Please update master and try again
