### ISSUE TITLE
FPP Arcade Plugin - Game selection from GPIO

### ISSUE THREAD

**Issue by craig-monson** [FalconChristmas/fpp#1918]
**Is your feature request related to a problem? Please describe.**
FPP Arcade plugin is great, but there is no ability to jump from one game to a specific game other than pressing the select button multiple times to get to the game that a player wants. 

**Describe the solution you'd like**
Would like to have the ability to assign a GPIO button action to select a specific Game row # created in the Arcade plugin setup screen. For example if I have created four games in the arcade setup (Row #1) Tetris, (Row #2) Snake, (Row #3) Break Out, (Row #4) Pong and then have 4 different interactive buttons on a podium in my display labeled with the names of the available arcade games. I would then  be able to assign the GPIO pins in FPP for those four buttons to select which specific game row # and play that game. This, for example, would allow the user to press the button on the podium labeled "Break Out", which would trigger the GPIO pin to select Row #3 (Break Out) from the arcade setup and then the user can press the button on the podium labeled "Tetris" and immediately start playing Tetris if the GPIO pin were assigned to select Row #1 of the arcade set up. This would make it easier and more intuitive as to what games are available to play and how to access those games. 

Also created the enhancement request in the FPP Arcade/Issues repository:
https://github.com/FalconChristmas/fpp-arcade/issues

**Comment by darylc** [comment]
This is related to a plugin, not fpp
