### ISSUE TITLE
Vendor Firmware download certificate issue

### ISSUE THREAD

**Issue by Fonzi03** [FalconChristmas/fpp#1919]
7.5 on pi3b

Tried with DNS servers:
1.1.1.1
8.8.4.4
8.8.8.8
9.9.9.9

Downloading https://microcyb.com/M8-cape-eeprom.bin to /home/fpp/media/tmp/tmp-eeprom.bin 

--2024-08-16 02:03:46--  https://microcyb.com/M8-cape-eeprom.bin
Resolving microcyb.com (microcyb.com)... 206.188.192.89
Connecting to microcyb.com (microcyb.com)|206.188.192.89|:443... connected.
ERROR: The certificate of ‘microcyb.com’ is not trusted.
ERROR: The certificate of ‘microcyb.com’ doesn't have a known issuer.

Problems downloading firmware.  Check above errors for details.
You may be able to manually download the file and do the upgrade directly with the file.

ERROR: No firmware file specified.

**Comment by darylc** [comment]
I'd say the clock on your FPP device is set incorrectly.

**Comment by patdelaney** [comment]
@Fonzi03 Try Help -> System Health check and see what you get,
![image](https://github.com/user-attachments/assets/10264b2e-21f5-4c8c-8ab9-3c1c1656552b)

**Comment by patdelaney** [comment]
![image](https://github.com/user-attachments/assets/68d7956c-d702-43b6-b1fd-cc25179e3710)

**Comment by patdelaney** [comment]
Actually I can reproduce the error:
![image](https://github.com/user-attachments/assets/4cb3c77e-1985-4638-b079-d162283ad6e4)

**Comment by Fonzi03** [comment]
My health check got green check ✅ for everything. I am able to download others just not this particular one.

**Comment by darylc** [comment]
@Fonzi03 We looked at this, it doesn't appear to be a FPP bug, it appears to be a problem with the microcyb website.  I'd suggest contacting microcyb.  We see wget/curl fail on Mac, Windows and Linux.
