### ISSUE TITLE
Option to allow live update of Bridge Mode statistics

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#192]
A check box or something within the BridgeMode status window to enable live update of data or not. This may reduce overhead of the system by not needing to update the screen while using the system. Default should be UNCHECKED for live data. If you happen to leave the screen 'open' to that tab while it is running.

**Comment by cpinkham** [comment]
In conjunction with this, I would also like to optimize the retrieval of this data to get it directly from fppd rather than having fppd write a file which the web server then reads.  We should be able to return JSON directly from fppd now.

**Comment by cpinkham** [comment]
Bridge mode stats are not actually loaded when the tab is not active.  This is due to the GetFPPStatus optimizations that Tim added a while back.  Checkbox is being added to make UI more consistent with Falcon controllers.  Commit pending...
