### ISSUE TITLE
stuck on login screen in fpp8 beta 1 

### ISSUE THREAD

**Issue by tmc11755** [FalconChristmas/fpp#1921]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: fpp8-beta1. BBB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. I see the ip address with a scanner, i can ping it, but when i go to it in a browser, i get a login screen,  blak,  admin/falcon, admin/blank dont work.

I re-installed twice, and get the same

**Comment by tmc11755** [comment]
Hmm.  this thing is booting into fpp without and sd card

**Comment by cybercop23** [comment]
BBB booting off of the emmc

**Comment by tmc11755** [comment]
ok, i see that i can edit  /boot/uEnv.txt, the issue is that the filesystem is full.  Before i realized this, I ran an upgrade, and now the file system is full.  any suggestions on files that I can delete?  Do i do this running sudo rm xxxxx?

**Comment by cybercop23** [comment]
I ran into this same issue and frankly I'm not happy. With 8 the image got a lot larger and you can no longer have both the system and an fppos on at the same time. You can try to compress the system.... well.. idk if that's supported on the BBB; may be Pi only, but that will get slowwwwer too. Hoping we can poke around and find things not needed for BBB and can them; heck even if just BBB and not PB since those don't have emmc.

**Comment by tmc11755** [comment]
I am sure that much of it is the newer version of the underlying OS (Debian I think it is)Sent from my iPhoneOn Aug 17, 2024, at 20:48, AlexB ***@***.***> wrote:﻿
I ran into this same issue and frankly I'm not happy. With 8 the image got a lot larger and you can no longer have both the system and an fppos on at the same time. You can try to compress the system.... well.. idk if that's supported on the BBB; may be Pi only, but that will get slowwwwer too. Hoping we can poke around and find things not needed for BBB and can them; heck even if just BBB and not PB since those don't have emmc.
