### ISSUE TITLE
FPP8: Soundblaster 3: Could not open Audio Output Device  Only on Pi 5

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1923]
**FPP Version and Hardware**: 
Example: *FPP 8.x master running on Pi5*

**Describe the bug and Steps to reproduce**: 
Plug SB3 into USB port,
Configure audio out for SB3
Reboot
Try to play audio file and you get the following error:
![image](https://github.com/user-attachments/assets/984a1a7c-229f-46c5-ae3b-117dc89a6c5e)

**Expected behavior**: 
Audio File should play

**Additional context**: 
The SB3 works on Pi4, this appears to just be a Pi 5 issue

**Comment by dartunder** [comment]
I have had it start playing once then due to errors fppd restarts either trying to play the next song or before.

**Comment by darylc** [comment]
@patdelaney Is this still an issue?

**Comment by dartunder** [comment]
FPP Version: | 8.x-master-464-g811c4b31
Platform: | Raspberry Pi (Pi 5)
FPP OS Build: | v2024-08
OS Version: | Raspbian GNU/Linux 12 (bookworm)
Kernel Version: | 6.6.45-v8+

I confirmed it is still a problem in the latest version as of today, 08/21/2024.

**Comment by dkulp** [comment]
The SB3 MUST be plugged in BEFORE booting.   That's always been the case.

**Comment by patdelaney** [comment]
I'll retest with Dan's sugestion when I get home.

**Comment by dkulp** [comment]
I cannot reproduce this.   With the soundblaster plugged into a blue port, I can boot with a fresh image, select the SB3 (first in the list), reboot, and sound works.

**Comment by bobreese** [comment]
I just tested my Pi5 with the latest V8.
Used after hours plugin and all worked as expected.

**Comment by patdelaney** [comment]
I retested based on Dan's comment and it works as expected. I will close the ticket
