### ISSUE TITLE
8.x beta seems to ignore custom NTP server

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1924]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
currently 8.x-master-457-g0b6c5e2c on PI 4 running fpp os v2024-08

**Describe the bug and Steps to reproduce**: 
When setting a custom ntp server via the fpp settings time tab, FPP does not appear to use the custom set NTP server as observed via the troubleshooting command or via ntpq querries from the ssh session. 
![image](https://github.com/user-attachments/assets/8bee98d2-a15d-44df-b53d-f1e64e0a9bf0)
![image](https://github.com/user-attachments/assets/72d3f6a3-568e-491b-972f-9246ca56359f)
from ~/media/settings
ntpServer = "time.nist.gov"

the ntp.conf at /etc/ntpsec/ntp.conf never gets updated with the ntp setting. 
from the bottom at that .conf file. 
restrict 127.0.0.1
restrict ::1
pool falconplayer.pool.ntp.org iburst minpoll 8 maxpoll 12 prefer

**Expected behavior**: 
I would expect the system to use the defined NTP server.

**Comment by darylc** [comment]
fixed in https://github.com/FalconChristmas/fpp/commit/e94cbbecf76d2a82d1051a1e46c1639e85a29931
