### ISSUE TITLE
FPPv8:  Multisync page A crashreport link references the wrong FPP instance

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1925]
**FPP Version and Hardware**: 
*FPP 8.master running on PI v3plus*

**Describe the bug and Steps to reproduce**: 
I am  running Multisynce page on 192.168.50.200 Piv3+
One of my Pis displays a warning that there are crash reports in that multisynce page
Float over the crashes report hyperlink and it display a bogus tooltip hyperink that takes you nowhere.
![image](https://github.com/user-attachments/assets/b6a9362b-5a82-4a98-a5d4-9cdd0c07ed21)

**Expected behavior**: 
The hyperlink should take to the device that has the errors

**Comment by dkulp** [comment]
Fixed
