### ISSUE TITLE
Voltage error

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#1927]
I'm on the latest Master Branch on a raspberry pi 3B+ 
And I've been getting a low voltage error message. 
I even increased the voltage to 5.13v 
I see there was some changes to accommodate the pi5 on 8/16 I just thought I would report that it's not working on my 3B+.

**Comment by bobreese** [comment]
What power supply are you using and what is the Amp output on it?
Do you have anything else plugged into the Pi (i.e. soundblaster, touchscreen, etc)

**Comment by ebuechner** [comment]
Dedicated Mean Well RS-15-5. 
Voltage tested with a fluke 117. 
Wasn't a problem until recently running on the master branch.  With that said, I just did a full power cycle on that pi and it seems to have cleared up?  I've been running the updates without doing a full power cycle.

**Comment by cybercop23** [comment]
Observed the same issue here. V8Beta2, Pi4 with nvme pants, LRS350-5. After a reboot it cleared up. Something is deff happening.
There used to be a voltage indicator on the status page. I looked all over the setting options and I don't see it. Is it still there?

**Comment by ebuechner** [comment]
The problem hasn't come back since I did a power cycle on that pi. I'm going to close this issue.
