### ISSUE TITLE
Add dacplusadcpro to Enable_HiFiBerry.sh

### ISSUE THREAD

**Issue by SopherConklin** [FalconChristmas/fpp#1928]
Have a couple HiFiBerry dacplusadcpro that I am using on my Pis.   Tried a simple edit of script to get it working, but ended up having to go to command line and fiddle around until I got it working.   I'm 71, I can't remember what I had for lunch, let alone what all I did to get these to work.   Would be nice if next time I had to do this the script worked for this.

**Comment by SopherConklin** [comment]
The script hung and never completed.   I ran the script commands manually, and it paused and waited for me to interactively answer a question (can't remember what it was - was maybe during the update or  upgrade steps.  I think some required stuff wasn't available and I googled how to add them and ended up getting it running eventually.   Also, for HiFiBerry stuff - FPP should default to mixer "Digital"

**Comment by SopherConklin** [comment]
Sorry, I was pretty brain-addled yesterday - this is on a Pi 4B with FPP 7.5

**Comment by darylc** [comment]
Thanks for the report.  This script was developed when hifiberry had one product.  Since then they have a ton of different ones that require different installation instructions.  I've marked the script as incompatible for FPP 7 and beyond.  I don't think it's practical to provide an updated script given we don't have the hardware to test it with.

**Comment by SopherConklin** [comment]
I'm not sure what "incompatible" entails, but the script has excellent
hints to lead someone to the eventual interactive steps to make this
work. Therefore it is a valuable reference, I hope "incompatible"
doesn't mean "inaccessible", or "invisible".

	-----------------------------------------From: "darylc" 
To: "FalconChristmas/fpp"
Cc: "SopherConklin", "Author"
Sent: Sunday August 25 2024 6:57:22AM
Subject: Re: [FalconChristmas/fpp] Add dacplusadcpro to
Enable_HiFiBerry.sh (Issue #1928)

	Thanks for the report. This script was developed when hifiberry had
one product. Since then they have a ton of different ones that require
different installation instructions. I've marked the script as
incompatible for FPP 7 and beyond. I don't think it's practical to
provide an updated script given we don't have the hardware to test it
with. 

	—
 Reply to this email directly,  view it on GitHub [1], or  unsubscribe
[2].
 You are receiving this because you authored the thread.Message ID:  

Links:
------
[1]
https://github.com/FalconChristmas/fpp/issues/1928#issuecomment-2308780122
[2]

**Comment by darylc** [comment]
@SopherConklin Thanks for the feedback.  I've made a change to FPP version 8 that will show incompatible scripts for reference.
