### ISSUE TITLE
FPPV8 Virtual Matrix Device dropdown list inconsistant.  (This might be an xLights bug, but not sure)

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1929]
**FPP Version and Hardware**: 
*FPP V8 Beta2 running on Pi*

**Describe the bug and Steps to reproduce**: 
There appears to be an inconsistancy with manually configuring a Virtual Matrix on Pi5 vs xLights configured Virtual Matrix.
If I manually create a Virtual Matrix, I get 3 options in the dropdown (see below)
![image](https://github.com/user-attachments/assets/fab3cc38-b58e-4221-a77b-6cf17d4cb9a5)

If I delete that manually created matrix (reset) and then Upload outputs from xLights I get 4 Options and the wrong one is slected:
![image](https://github.com/user-attachments/assets/88d1f551-0b7d-4f22-adbc-30be75edbac0)
![image](https://github.com/user-attachments/assets/2038192e-0ede-4ed2-9f09-deffd45d9975)
Note that xLight port number can be set to 0,1,or 2
I Upload outputs to FPP and get this now
![image](https://github.com/user-attachments/assets/c5aaa993-4109-4265-81cb-02fab711f237)
It is configured for HDMI-A-0
I run FPP connect
![image](https://github.com/user-attachments/assets/3576189e-8295-4d89-92e6-daabb79747c3)
![image](https://github.com/user-attachments/assets/b50f1520-5f61-447e-b58f-cf68839025e5)
I still had 4 options, and it defaulted to HDMI-A-0
I tried to run a sequence and there was no Output.
I switck the device to HDMI-A-1, restarted FPPD and played a seqience and it worked.

**Expected behavior**: 
Th correct buffer should have be selected and saved after the upload,

**Additional context**: 
I'm not sure if the outputs are 0 based or 1 based.

**Comment by darylc** [comment]
HDMI-A-0 is an xlights issue, in the code related to this xlights commit
