### ISSUE TITLE
Network Gateway Error When Making Show Network

### ISSUE THREAD

**Issue by ChooChooMan74** [FalconChristmas/fpp#1931]
# Please answer the following:
FPP 8 Beta 2 On Raspberry Pi 4

**Describe the bug and Steps to reproduce**: 
Connect the Pi to the home network via DHCP on Wlan0
Create Static IP for Show Network on Eth0 (Ip, Subnet, NO Gateway)

ERROR CANT SAVE, Need Gateway

**Expected behavior**: 
Using DHCP on the home network is common use for end users who are not network savvy. The zoom room gets many people at the beginning of the season with IP conflicts.  

Current workaround is to temporarily make the Wlan0 Static, make the Show Network on Eth0, then revert Wlan0 back to DHCP

**Additional context**: 
Any way to make IF Wlan0 has an established dhcp connection, no need for gateway in Eth0

**Comment by darylc** [comment]
@ChooChooMan74 I made a change such that an interface configured with DHCP and having a status of UP (eg plugged in, or connected to the SSID) then that is considered a default gateway and won't require or allow another default gateway to be configured.  Let me know if you see any further problems.

**Comment by ChooChooMan74** [comment]
Thank you
