### ISSUE TITLE
FPP8 - Setting eth0 and wlan0 to static at same time causes error :  cannot set multiple gateways

### ISSUE THREAD

**Issue by AGFazio** [FalconChristmas/fpp#1936]
FPP version:    8.x-master-532-g39546d88

Trying to set wlan0 for static to home network and eth0 to static for show network. See screenshots.

wlan0
IP: 192.168.68.207
Netmask:  255.255.252.0
Gateway: 192.168.68.1

eth0
IP:  192.168.11.2
Netmask: 255.255.255.0
Gateway:  (Empty)

Clicking on update causes error stating cannot have multiple gateways.

![Screenshot 2024-08-30 173008](https://github.com/user-attachments/assets/9d1bd6f6-faef-4665-aa82-0d27224c7e32)
![Screenshot 2024-08-30 173042](https://github.com/user-attachments/assets/e5d2860e-5b6d-4556-8413-5f09c1a1cd9a)
![Screenshot 2024-08-30 173112](https://github.com/user-attachments/assets/e36c72ea-fce6-4d93-b913-bcef9c36a5d9)
![Screenshot 2024-08-30 173125](https://github.com/user-attachments/assets/71e3193b-6c70-4dde-bae4-6b02114f55d5)
![Screenshot 2024-08-30 173345](https://github.com/user-attachments/assets/a8e40dd1-87a3-44a4-9a69-87d80bdddd2b)

**Comment by AGFazio** [comment]
Zipped logs : 
[FPP_Logs_20240830.2142.zip](https://github.com/user-attachments/files/16822364/FPP_Logs_20240830.2142.zip)

**Comment by darylc** [comment]
AGFazio confirmed this fixed it.

**Comment by Agitatedfall** [comment]
How was this fixed? Can someone dumb this down for me?
