### ISSUE TITLE
FPP V8 - Insert Playlist Immediate - Command Preset

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1937]
I have a schedule setup in FPP to play a playlist of pictures. This works as expected
Playlist - Santa Pictures
Type - Image
Image - /home/fpp/media/images/
Pixel Overlay Model: VirtualMatrix (Touchscreen on Pi)

When the touchscreen is activated a command preset is run
Command - Insert Playlist Immediate
Playlist Name: Santa Sleigh (MP4 Video)
If Not Running - Checked Yes

The MP4 runs (can be seen in the logs at 4:20
When the movie is done (4:23) the screen is Locked on the Last Frame yet FPP Status shows the Santa Pictures playlist is running.
For some reason VirtualMatrix output is not reset.

Running the MP4 thru Status - Santa Sleigh playlist on its own runs and stops as expected.
I turned on General and Playlist logging to Debug for these logs.

[syslog.zip](https://github.com/user-attachments/files/16824159/syslog.zip)
[fppd.zip](https://github.com/user-attachments/files/16824160/fppd.zip)

**Comment by darylc** [comment]
Bob says the sequence here is plays pictures, then plays a video and plays pictures but the last set of pictures never appear, the last frame of the mp4 is still stuck on the screen.

**Comment by cybercop23** [comment]
Least frame "stuck" is the same issue when playing a video file on a remote that's shorter than the media on player (when they are named the same) 

In <= 7.5 the video would finish and switch to fseq effects, if any. Now it stays stick on the last frame.

**Comment by dkulp** [comment]
I believe this is now fixed.  Can folks update and test?

**Comment by bobreese** [comment]
I am sorry sir.
Video still frozen at the same last frame on my screen, yet FPP shows the pictures playlist running.
Anything else I can supply for you?

**Comment by bobreese** [comment]
I put the logging into excessive for playlist.
Maybe this will give more info to what is happening.
[fppd.log](https://github.com/user-attachments/files/16828412/fppd.log)

**Comment by bobreese** [comment]
Latest updates of 9/1/2024 seems to have fixed this issue.
With the pictures running, touchscreen starts video. At the end of the video (on first run) there was a 5 sec delay for the pictures to return.
Once the pictures came back, touchscreen start of video. When the video ended the pictures came back immediately!
