### ISSUE TITLE
Flickering lights

### ISSUE THREAD

**Issue by Nadurru** [FalconChristmas/fpp#1938]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 7.5-6-g72ca6d6b
Example: *FPP 4.2 running on BBB* Raspberry Pi (Pi 4)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to xLights and open a sequence
2. Click on render, save, FPP connect, upload, Upload outputs
3. Click on output to lights

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.
I expect the lights to come on steady or according to the effect. That should be the normal operation.
**Additional context**: 
When I click the output to lights (regardless of the effect) the lights act as though they in "shimmer" mode. I open FPP and turn off input/output Setup, click on Channel output, turn off Channel Output and the lights act correctly in xLights. I just updated the firmware yesterday. Prior to this I didn't have to turn the outputs off.
[FPP_Logs_20240831.1843.zip](https://github.com/user-attachments/files/16825715/FPP_Logs_20240831.1843.zip)

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by darylc** [comment]
Please log this against xlights, not fpp

**Comment by dkulp** [comment]
This is likely working as expected.   If you have FPP configured to output to the same controllers as you have xLights configured to output, then when running from xLights with output to lights on, the controller is likely getting data from both locations which is causing the flickering.
