### ISSUE TITLE
Clean up OS Dropdown box.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1939]
# Challenge
Today, the OS (fppos) dropdown box for upgrades is a big of a mess.   
- There are lots of versions, many of which are unlikely to be used any more
- The sort order isn't very logical.   
![image](https://github.com/user-attachments/assets/1b4fc54b-5d98-4c75-bf74-4c618d43a210)

# Possible Solutions
- Apply a better sort order in the UI so that the most recently release is at the top.
- Add some filtering hide really out data versions. 

Not 100% sure which option is the best. 

Note:  What seems  odd is that `api/git/releases/os` seems to return the results in a reasonable order wit the most recent release at the begining of the array.

**Comment by OnlineDynamic** [comment]
think I know what to do... the git asset_id seems to be cronological in order so I could change the logic to sort by that and then have a legacy lookup array which would allow ancient ones to be excluded by default but have UI option to include if required.... @dkulp are all OS releases on git? as my approach would work if they are... needs a bit of rework as the current setup is a mixture of getting downloaded files data and then git data seperately but recording the 2 with different values/text in the select option

**Comment by cybercop23** [comment]
I think downloaded files shoud be listed first, even if out of numerical sequence and then the available ones for download.
Same as Pat's, although beta 2 is the latest.. if anything's already downloaded should be at the top and then available for download. the lists should not be intertwined.
![image](https://github.com/user-attachments/assets/32808e86-e936-4344-b720-b9d52ef1fcd4)

**Comment by OnlineDynamic** [comment]
This solution work for everyone: 

https://github.com/user-attachments/assets/57c9fee6-d9c1-4019-9920-188786ff83f3

**Comment by darylc** [comment]
Yes, presumably historic only appears in advanced UI mode.

**Comment by cybercop23** [comment]
I see the list is sorted by version number, most recent at the top. If you keep it like this, I know it says (download) but that's hard to see... maybe bold/highlight.. diff color... the already downloaded ones for easier id.
My suggestion was to have sort of two lists, top already downloaded with the same sort order and below that the availables ones in the same order. if you have just one list.. would be nice to somehow have even an easier identification

**Comment by darylc** [comment]
I also wonder if beta/alpha images should only show in advanced UI mode, and if we should move 6.x to historic now that 8.x is basically out (eg show n -1)

**Comment by OnlineDynamic** [comment]
Like all the ideas will try to do when I wake up...tomorrow

**Comment by ghormann** [comment]
I love the video.   That was a good idea! 
- I think the "downloaded" ones could be better highlighted.   (color or bold)
-  I would suggest that the only "non-legacy" ones are 8.x the latest 7 release. (7.5).   I struggle with why someone would want to install any version of 7 other than 7.5.     
- Personally, I consider 6.3 legacy, but keeping it not is fine.

**Comment by OnlineDynamic** [comment]
So just pulled in the change - please test - I have made it so...

- only 7+ are considered non legacy
- I have also made it so alpha and beta only so in advanced+ mode
- show legacy is only an option in advanced+ mode

formatting the appearing of select box options isn't supported by all browsers - but will have a play with that at some point - wanted to get this in before v8 release

**Comment by ghormann** [comment]
I like it.. 

I did notice that if a file (say 5.5) is downloaded, but I don't have legacy selected, it is filtered out.  I was thinking that downloaded files should always be displayed, but honestly, i don't have a strong feeling about it.
