### ISSUE TITLE
FPP 8 upgrade

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1948]
When upgrading from beta2 to prod 8 or prod 8 to prod 8 when the fppos was already previously uploadedvia FM.. when the upgrade os is started.. it proceeds to redownload the file... even when the dd list shows it being local.

![image](https://github.com/user-attachments/assets/b3a5d8e1-d930-4c8c-bad7-e702e56bb6bc)

**Comment by cybercop23** [comment]
As expected when upgrading from 7.5.6 and manually uploading FPPOS, this is not an issue. But I suspect any upgrades from 8 on will.
![image](https://github.com/user-attachments/assets/46597c5f-b4d3-4f01-b705-62354b648c7f)
![image](https://github.com/user-attachments/assets/e36efa62-258d-41ea-8753-5261b00db094)

**Comment by bobreese** [comment]
When I tried to upgrade my Beta2 to the release, it would only let me do an on-line upgrade.
Note: Downloaded V8 was 6.64Gig in size. The on-line upgrade is 991.74MB
Even now on V8, I cannot get the FPP Upgrade Source off of Github.com
![No Local Upgrade](https://github.com/user-attachments/assets/15f9cba1-dd60-4eb0-b640-5aa11c73546f)
![No Local Upgrade 1](https://github.com/user-attachments/assets/0a09fd3b-78ad-4680-b293-6c675ce80bd3)

**Comment by cybercop23** [comment]
wrong file. you need to upload the ffpos file not the img/zip file.

**Comment by OnlineDynamic** [comment]
fixed in PR #1965

**Comment by darylc** [comment]
confirmed fixed
