### ISSUE TITLE
Matrix Tool display for very large P10 arrays

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#195]
Posted on the Falcon site also -

While I'm not planning to build one, I know others will. :)

If I make a Matrix Overlay for a 5x5 P10, I can clearly draw and see text in the Matrix Tools windows (text or draw)

If I make a Matrix Overlay for a 6x6 P10, I can still see it, but now the "grid lines" are getting in the way of a clear display

If I make a Matrix Overlay for a 7x7 P10, there is just a hint of my drawings or text

Finally, when you get to 8x8, you see nothing. Just gray from the grid lines. At first I thought it wasn't working but I went back by steps and saw the actual problem was the grid lines.

So, along with the "show round pixels" choice, can there be a "Remove Grid Lines" choice so you can see what is being drawn?

**Comment by cpinkham** [comment]
Bug fixed in matrixtools repo.  By default the grid is off and can be optionally enabled.
