### ISSUE TITLE
 Panel Hats on RPi dont (yet) work on FPP8

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1952]
Tested on Pi3B, Pi4 & Pi5 , enable LED Panel Output, attempt to restart FPPD and it wont come up.  Disable the Output, restart FPPD and its fine.

**Comment by OnlineDynamic** [comment]
We know the Pi5 isn't yet supported on the external library but shouldn't 3's % 4's be working?

**Comment by OnlineDynamic** [comment]
fix for 3's and 4's hopefully in commit 6274fbf - needs testing

**Comment by darylc** [comment]
Greg Macaree confirmed the commit fixed it on facebook.
