### ISSUE TITLE
V8 Pi K8 3b+ reports underpower although it has normalized

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1957]
Seems to show up on reboot for about 5 secs. 
Can't see how/why since it is on a K8 hat connected to a Meanwell LRS 350-5 set to 5.17v
![image](https://github.com/user-attachments/assets/c4e64e19-0648-4b76-8b0a-73d77f496a67)

**Comment by darylc** [comment]
If it's showing up in dmesg, then there is nothing FPP can do.   FPP is only reporting what linux is seeing.  Linux would also see this in previous FPP versions just FPP wouldn't report ig.
