### ISSUE TITLE
Docker image missing iproute2

### ISSUE THREAD

**Issue by bjhiltbrand** [FalconChristmas/fpp#1962]
**FPP Version and Hardware**: FPP v8.x-master-588-g1a7150d4 (master branch) on Ubuntu 24.04.1

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Setup docker-compose file and deploy docker compose container
2. Upload fseq and media
3. Go to status page and attempt to start playback
4. See that the media playback buttons are greyed out, the playlists don't load, and the volume slider doesn't respond.

I asked about this on Facebook (https://www.facebook.com/groups/FalconPlayer/posts/3818019358473019), and James Vance pointed me to the fact that iproute2 was not available in the container image. I started an exec session and ran 'apt install -y iproute2'. This immediately fixed the issue. This needs to be added to the image so this step isn't required everytime the container is built.

**Comment by ghormann** [comment]
Will take a bit for the "-latest" image to build via automation.
