### ISSUE TITLE
Panel Test Pattern no display on FPP v8.0

### ISSUE THREAD

**Issue by cbennett6008** [FalconChristmas/fpp#1963]
# Please answer the following:
FPP 8.0 on K8-B-Scroller v1.0
P5 Panel: 2 wide 3 tall

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

1. Install FPP to SD card
2. Set Passwords and Expand Flash, Reboot
3. I/O | Channel Outputs | K8-B-Scroller tab
4. W:2 H:3 Click Auto Layout
5. Verify that O and P numbers match the board outputs.  In my case it does.
6. Restart fppd as prompted
7. click Test Pattern

With an 7.5 OS, the output pattern displays.
On 8.0 final (fresh flash or upgrade), there is no display, all black.
(Test Mode works, and Output to lights works, this is just a Test Pattern isssue)

**Expected behavior**: 
Expect the test pattern to display on the panel(s)
**Additional context**: 
Duplicated issue in Zoom with Ron A.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by cbennett6008** [comment]
[FPP_Logs_20240907.0425.zip](https://github.com/user-attachments/files/16914349/FPP_Logs_20240907.0425.zip)

**Comment by dkulp** [comment]
Fixed
