### ISSUE TITLE
Allow for effects to run on remote FPP

### ISSUE THREAD

**Issue by CaffeinatedFunctionality** [FalconChristmas/fpp#1969]
**Is your feature request related to a problem? Please describe.**
This is likely a niche feature for some people so not urgent. I have a permanent roof line that I would like to set and forget that just shines some effect on the house to light it up at night with a white light. I'd like to set that as an effect that will run on a schedule. It's a remote FPP on a Kulp controller. I also have a Kulp running in my car for under car lights that I would like to run with my show when I am home and run an effect when I am out. 

**Describe the solution you'd like**
I'd prefer to make that some kind of background effect run on startup and/or run on a schedule for a remote FPP instance but when the master is playing and sending data the background effect goes away and starts playing from the master.

**Describe alternatives you've considered**
I can have the master send a remote command to play an effect or have it send a different playlist afterhours, but I won't always have my master running. My master control is only out during the holidays because I need it close to my outdoor speakers close to a tree.

**Comment by darylc** [comment]
@CaffeinatedFunctionality I feel like this functionality already exists, have you checked the FPP manual?

**Comment by ghormann** [comment]
Closing due to lack of response
