### ISSUE TITLE
Detect USB flash drive with network config during network initialization

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#197]
At boot, we should check to see if the storage directory/device is present and contains network device config files.  If so, we should configure the interfaces file with that info rather than reverting to DHCP.  This will prevent the situation where we boot with DHCP then later reinitialize to using a static IP and the router DNS still contains the original DHCP IP.

http://falconchristmas.com/forum/index.php/topic,4259.0.html is one discussion on this topic.

**Comment by jcochran** [comment]
This is addressed in my network patch once its pulled in. It will remove the "two stage" network initialization and use the config on the storage device before reverting to a default DHCP config. It will also check for the presence of a custom interfaces file on the storage device and use it over the FPP generated network config.

**Comment by darylc** [comment]
@jcochran did your network patch ever get pulled?

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this, although similar functionality could be provided through #1251 or similar
