### ISSUE TITLE
Pi5 v8.0 software will not run fseq files over 30 seconds

### ISSUE THREAD

**Issue by camguy52** [FalconChristmas/fpp#1972]
I am testing both a Pi4 and Pi5 Show Controller each running FPP v8.0 software.

The Pi4 will run fseq files from 30 sec to 6 minutes.  Both animation and music sequences run properly.

The Pi5 will ONLY run files 30 seconds or less.  The Pi5 Elapsed Time Display shows "Nan%" when a longer fseq file is loaded.  
The Log file displays:
2024-09-12 11:42:01.991 (1683) [Sequence] /opt/fpp/src/Sequence.cpp:298: Sequence file /home/fpp/media/sequences/Landscape-Nightime-2min.fseq does not exist
2024-09-12 11:42:01.997 (1683) [Playlist] /opt/fpp/src/playlist/PlaylistEntrySequence.cpp:60: Error opening sequence Landscape-Nightime-2min.fseq 

I am using FPP Connect to upload the sane fseq files to both show controllers and both controllers File Manager show the file is available.  

Hope this helps,

Doug Hurrell

---------------------------------------------
xlights - 2024.15 64 bit
Show Controller- Pi4 or Pi5 with V8.0 sdcard
Multisync for FPP Controllers

Led/Matrix Controllers:
1. Front Yad - Falcon F48V4-NS
2. Back Yard - Falcon F16V4 (2 area specific units)
3. Family Room - Falcon F16V4. 
4. FPP-Front Garage Halloween & Christmas - Pi3 with Microcyb M.8
5. FPP-Front Drive Left - Pi3 with  Microcyb M.8
6. FPP-*Mega Tree - Pi3 with M.2 Controller
7. FPP-*Stairway - Pi3 with Falcon  Falcon Pi Cap 
8. FPP-*Snowmen - Pi3 with Falcon  Falcon Pi Cap 
9. FPP-*Office - Pi3 with Falcon  Falcon Pi Cap 
10. FPP-*Wifi Chandelier - Pi4 with Falcon Pi Cap
11. FPP-*Living Room Ledge - Pi3 with MicroCYB M4
12. FPP-*Video Wall TV 1 thru 4 - Pi5 Video Matrix
13. FPP-*Family Room Display - Pi5 Video Matrix
14. FPP-*Front Window TV - Pi3 Video Matrix
15. FPP-*Roamer TV - Pi4 Video Matrix

**Comment by Poporacer** [comment]
Can you update to the Most current version of FPP and the OS? I am not seeing the results you are describing?
![image](https://github.com/user-attachments/assets/73a9ea8e-9d1b-4ed2-b27b-03cf9e9bb67d)

**Comment by camguy52** [comment]
I will do that and get back to you,

 

Doug Hurrell

**Comment by camguy52** [comment]
I once again downloaded the most current version of  FPP and confirmed I am on the most current OS.  I am trying to run in the Pi5 Kiosk Mode.

It appears the problem is not related to length (although the longer the segment, the bigger the file).  The problem is related to fseq file length.  

Both "Landscape Dark" (378.51MB) and "Landscape-Nighttime" (1.1GB) will run OK without problems
Both "Landscape-Daytime" (2.21GB) and "Spell on You" (9.12GB) will not run and generates errors of "can't be found" even though the files show up under "File Manager Content".

All files will run OK with the Pi4 and V7.2 software.

Hope this helps,

Doug

![Spell On You File does not exist](https://github.com/user-attachments/assets/1887890f-4348-49c5-bc4e-e050827e72f8)
![Landscape Dark OK](https://github.com/user-attachments/assets/c7500d9c-a856-4654-8cf9-da3383c78f16)
![Landscape-Daytime File does not exist](https://github.com/user-attachments/assets/4a9227bb-05f0-4a52-b9ae-126afd178af2)
![Landscape-Nightime OK](https://github.com/user-attachments/assets/95273bb5-89ac-4be0-bad1-017e74c6f5c0)
![Pi 5 Content File Manager](https://github.com/user-attachments/assets/e9741460-ec0d-4ed0-a373-e6c95cb61362)

**Comment by dkulp** [comment]
Can you send me (privately is fine) the packages sequences?    I can try and reproduce.   I assume sending the fseq is smaller than a 9G fseq file.  :) 

That said, are you sure you are uploading via FPP connect and using v2 zstd sparse sequences?   The 15sec sequences at 1.1G would already be a problem.   The Pi cannot even read that much off an SD card in that amount of time.

**Comment by dkulp** [comment]
I believe the "does not exist" issue for FSEQ files > 2G is now fixed on master branch.

**Comment by camguy52** [comment]
Thank you, thank you!

I will check it out.

 

Doug

**Comment by camguy52** [comment]
Will there be a new V8.01 Release or is there another way I can check out the current Master Branch software?

Doug

**Comment by cybercop23** [comment]
Sttus Control -> FPP Setinngs -> UI - Change from Basic to Developer then in the new Developer tab, change to master branch.

**Comment by camguy52** [comment]
V8.1 update with Pi5

Good News, I am successfully running V8.1 on Pi 5 with large 18 - 28 GB fseq files in Kiosk Mode. --> Thankyou !!

My setup includes (4) Flacon, Led Controllers, (9) Pi FPP Led controllers, (7) Pi5 Video Matrix controllers all being controlled by a Pi5 FPP Show Controller running in Kiosk Mode.

I was under the impression that the Show Controller needed "V2zstd" files which explains why my fseq files are so large.

I have tried running the Show Controller with "V2sparse/zstd" files and everything seems to work.  The difference in a Ghostbusters show file is 18.04gb versus 15.14mb.  Of course the communications with the Falcon Controllers is real time versus multisync to the FPP Controllers.

Is there any reason I need "V2zstd" files on the Show Controller?

All the best, and again, thank you!

Doug Hurrell

**Comment by dkulp** [comment]
There really is no "modern" reason for using the v2/zstd on the player/controller.    We used to upload the full sequence to the master and then r-synced it out to the remotes in which case it did need everything.  However, using FPP Connect, it handles everything much better and user the sparse option is way better.

**Comment by camguy52** [comment]
Thank you - you just changed my total show upload time from 6 hours to 5 minutes ! :)

Take care,

Doug Hurrell
