### ISSUE TITLE
No Backup SSID shown in Network Configuration

### ISSUE THREAD

**Issue by brennja** [FalconChristmas/fpp#1977]
FPP Version: | 8.0
Platform: | BeagleBone Black (PocketBeagle)
FPP OS Build: | v2024-09
OS Version: | Debian GNU/Linux 12 (bookworm)
Hardware Serial Number: | 1740GPB30354
Kernel Version: | 6.6.44-fpp16

Network Configuration shows 
Wireless Settings, WPA SSID
WPA Pre Shared key (PSK)

But no place for backup SSID

**Comment by cybercop23** [comment]
Change your UI to advanced. Doesn't show up in the basic UI.

**Comment by brennja** [comment]
Thank you
Suggest updating Release Notes for backup SSID with "(Advanced UI)"
