### ISSUE TITLE
Raspberry Pi 5 - Falcon Player Video Issue with Kiosk Mode

### ISSUE THREAD

**Issue by sagarpateldt** [FalconChristmas/fpp#1979]
FPP 8.0 running on Raspberry pi5*

1. Go To status/control 
2. fpp setting 
3. on developer option from UI tab
4. kiosk on from system tab

When running videos on a Raspberry Pi 5 through Falcon Player (FPP), an issue arises when Kiosk Mode is enabled. Specifically:

Video Playback Issue:
After enabling Kiosk Mode, the video does not display as expected. Instead, only the control page shows up, and the video remains hidden. However, the video file is running in the background.

Kiosk Mode Persistence:
Once Kiosk Mode is enabled, it cannot be disabled again via the standard settings or control interface. Even after trying to disable it, the system continues to function as if Kiosk Mode is still active.

Normal Functionality Without Kiosk:
When Kiosk Mode is not enabled, the video plays normally and all functions operate as expected.

**Comment by dkulp** [comment]
Videos won't work when Kiosk is enabled as the Kiosk stuff takes over the display.    

The disable of kiosk is now fixed on master.

**Comment by sagarpateldt** [comment]
Thanks you so much for answer.
