### ISSUE TITLE
not able to play big video on fpp 8.0.

### ISSUE THREAD

**Issue by sagarpateldt** [FalconChristmas/fpp#1981]
FPP 8.0 running on Raspberry pi 5 4GB.

1. Upload a video file that is around 2GB in size to the Falcon Player.
2. start video from select status page from media section. but not able to play video.

When attempting to play large video files (approximately 2GB) through Falcon Player (FPP) on a Raspberry Pi 5, the videos do not start, despite the status page indicating that the playlist has begun. Videos smaller than 1GB, however, play correctly without any issues.

**Comment by darylc** [comment]
fixed in master and will be in next release https://github.com/FalconChristmas/fpp/commit/9375ccabd4ef1bac12dd440678869f1d6f9829c1
