### ISSUE TITLE
Virtual Matrix issue FPP 8.1 running on Pi5 4GB

### ISSUE THREAD

**Issue by cabriobrad** [FalconChristmas/fpp#1985]
FPP 8.1 running on Pi5 4GB

Set virtual matrix size to anything other than actual resolution of tv/projector.
Upon display preview screen it will not auto fill to the screen size and becomes a fraction of screen 
depending on resolution set in step 1.

Ver 7.5 on Pi4 works as normal and fills screen regardless of resolution chosen in step 1

[FPP_Logs_20241003.0158.zip](https://github.com/user-attachments/files/17238045/FPP_Logs_20241003.0158.zip)

**Comment by darylc** [comment]
See this piece of advice: 
![image](https://github.com/user-attachments/assets/ea905e6d-f326-41ba-9844-5a8e9a40e909)

**Comment by cybercop23** [comment]
This works fine, helped someone in the zoom room tonight with this, but the issue is that xLights will override it if/when Upload Outputs. If going back to the old school and put it first in the list, mostly likely you won't need to ever repush it.
Also the xLight def has to be the fullres/pixel size.. if they are diff, it will not fill the screen.

**Comment by cabriobrad** [comment]
Well, that seems to have fixed it. So simple
Thanks

**Comment by bobreese** [comment]
Once I had my virtual matrix configured correctly, I went into the visualizer in xLights and moved it off the controller (Pi3+ with FPP V8).
Everything works as expected and I can still can upload outputs for any other changes.

**Comment by bobreese** [comment]
Been testing with my projector on Pi4 HDMI-A-1
Channel Outputs pixel size set to 3
Pixel Overlay Models pixel size stays at 1
![Channel Outputs](https://github.com/user-attachments/assets/01ccc5ca-0ed6-4acb-b569-84249d6b4aea)
![Overlay Models](https://github.com/user-attachments/assets/725f1fa4-69e7-4ee9-a478-778b9ec3a6ae)

**Comment by bobreese** [comment]
Upgraded my test pi4 to master branch.
Pixel overlay models did not change after doing an update.

**Comment by darylc** [comment]
Dan fixed the virtual matrix stuff in https://github.com/FalconChristmas/fpp/commit/41c32940e54ee7efa808d71a9885ca993c8e0d77 in master

**Comment by Littleaton** [comment]
This has raised further issues now as if you had the matrix set to a specific size like one I have, not wanting it to use the full screen and just a portion, it now spans the whole screen.

**Comment by darylc** [comment]
@Littleaton If you want to use a portion of the screen then you have to configure the appropriate pixel overlay models to do so, like in v6.x & v7.x

**Comment by Littleaton** [comment]
> @Littleaton If you want to use a portion of the screen then you have to configure the appropriate pixel overlay models to do so, like in v6.x & v7.x 

i reverted back to 7.5.6.  so "fixed" for now.  will try that in a test pi.
