### ISSUE TITLE
"Always transmit channel data" functionally disables "Automatically turn on/off outputs"

### ISSUE THREAD

**Issue by morelup** [FalconChristmas/fpp#1986]
**FPP Version and Hardware**:  FPP 8.0 on BBB

**Describe the bug and Steps to reproduce**: 
Always Transmit Channel Data overrides "Automatically turn on/off outputs." when using system with eFuses
1. Go to 'Input/Output'
2. Enable  'Automatically turn on/off outputs'
3. Enable  'Always Transmit Channel Data'
4. Restart FPPD
5. Navigate to "Current Monitor" page
6. Observe ports never turn off

**Expected behavior**: 
Expected behavior is that the data channel would continually send "0/0/0 RGB" for all assigned nodes but leave power off.

**Additional context**: 
If "Always Transmit Channel Data" requires "Automatically turn on/off outputs" not function then enabling "Always Transmit Channel Data" should grey out "Automatically turn on/off outputs" when it is enabled to make the UI more clear

**Additional Attachments**

**Comment by ghormann** [comment]
Personally, I think it is working as expected (not powering off).   I'm not a huge fan of disabling a UI feature when it isn't totally obvious what it is disabled.   I did clarify the help text. 

![image](https://github.com/user-attachments/assets/591de89a-2cb8-45b0-bfd2-e5878a641386)

**Comment by dkulp** [comment]
Also note:  if you want to schedule when the outputs are on or off, there are FPP Commands that will turn on/off the outputs which could be used in the lead in/out sections.   But it is working as designed as per the updated help.
