### ISSUE TITLE
Current monitor page shows "Ports NaN-NaN"

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1999]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 8.1 in K4-PB eFuse

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Current Monitor page
2. See "Ports NaN-NaN"

**Expected behavior**: 
Non "NaN"

**Additional context**: 
Upgraded to 8.1 using OS update.

**Additional Attachments**
Please include the log files. To create the file:
[FPP_Logs_20241012.1910.zip](https://github.com/user-attachments/files/17351174/FPP_Logs_20241012.1910.zip)

![image](https://github.com/user-attachments/assets/7e003f39-9a51-4a23-aa23-4c7f76618f64)

**Comment by dkulp** [comment]
I'm not seeing that.  On my K4's, I'm not seeing the NaN.  It's not correct as I'm seeing 1-8 instead of 1-4, but not NaN.

<img width="858" alt="Screenshot 2024-10-12 at 3 20 15 PM" src="https://github.com/user-attachments/assets/8d0ec48d-ea61-4d14-9a19-08e1921a9a70">

**Comment by patdelaney** [comment]
On my K4-pb: running an earlier version: v8.x-master-593-g7fcc0f24 (master branch) on o/s level" v2024-08.    I willupgrade to latest

Other thant 1-8 mine is correct, Did you try in cognito broswer?

![image](https://github.com/user-attachments/assets/27005c65-b65a-4bc1-9647-ab9a1cdf9ad9)

**Comment by ptr727** [comment]
v8.2 now says "Ports 1-4", don't know if it was specifically fixed, or just randomly works.
