### ISSUE TITLE
Raspberry Pi Imager on Linux fails with BBB image

### ISSUE THREAD

**Issue by shanerehm1234** [FalconChristmas/fpp#2000]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 8.2 OR 7.5 on BBB

Running Linux Mint OS - Raspberry Pi Imager installed through Software Manager
I cam burn PI images to SD cards all day long, but the BBB image fails at approx 50% during the write phase. 
Error message: Download Corrupt. Hash does not match.
Same result on both 7.5 and 8.2 images. 
Same problem on Windows  11 laptop. 

![image](https://github.com/user-attachments/assets/4c432426-6ce0-4bc5-9595-14e9c55044b9)

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by darylc** [comment]
This is not an FPP issue, do some googling, perhaps https://github.com/raspberrypi/rpi-imager/issues/209 might give you some hints?
