### ISSUE TITLE
FPP Gives Error Message When Zip Button Pushed For Log Files

### ISSUE THREAD

**Issue by jpappas6** [FalconChristmas/fpp#2008]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to File Manager-Logs
2. Click on Log File
3. Click Zip

**Expected behavior**: 
I was attempting to file another bug report and attempted to zip log files to attach to report. Got screenshot error message. Had to download logs to zip locally.
![Screenshot 2024-10-17 at 5 04 24 PM](https://github.com/user-attachments/assets/5ce1ca0f-3f55-4119-b5bb-6b0ead29a140)

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
6. Attach to this ticket.
[apache2-error.log.zip](https://github.com/user-attachments/files/17423902/apache2-error.log.zip)
[apache2-base-error.log.zip](https://github.com/user-attachments/files/17423903/apache2-base-error.log.zip)
[fppd.log.zip](https://github.com/user-attachments/files/17423904/fppd.log.zip)

**Comment by ghormann** [comment]
Did you use the ffpos upgrade? I can see from the logs this was an fpp 7 box.   You need to use the fppos upgrade for 8.2 to fix the zip library.

**Comment by jpappas6** [comment]
I'm an idiot. Thanks!
