### ISSUE TITLE
FPP8.2 - Setting eth0 and wlan0 to static at same time causes error : cannot set multiple gateways

### ISSUE THREAD

**Issue by technageek** [FalconChristmas/fpp#2015]
Trying to set wlan0 for static to home network and eth0 to static for show network. See screenshots.

wlan0
IP: 10.1.1.125
Netmask: 255.255.252.0
Gateway: 10.1.1.1

eth0
IP: 10.10.1.125
Netmask: 255.255.255.0
Gateway: 10.1.1.1
Clicking on update causes an error stating that there cannot be multiple gateways.

![10-1-1-125](https://github.com/user-attachments/assets/546f021e-5e55-48eb-b8e6-d03e05336f7d)
![10-10-1-1](https://github.com/user-attachments/assets/1dc96a8c-1dc2-4976-b35e-fb25979143e6)

<html>
<body>

FPP Version: | 8.2
-- | --
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2024-10
OS Version: | Raspbian GNU/Linux 12 (bookworm)
Hardware Serial Number: | 100000003405a6f3
Kernel Version: | 6.6.51-v7l+
System Boot Time: | 2024-09-06 01:26:29
fppd Uptime: | 16:47
Local Git Version: | 93f1fff ChangeLog

</body>
</html>FPP Version:	8.2
Platform:	Raspberry Pi (Pi 4)
FPP OS Build:	v2024-10
OS Version:	Raspbian GNU/Linux 12 (bookworm)
Hardware Serial Number:	100000003405a6f3
Kernel Version:	6.6.51-v7l+
System Boot Time:	2024-09-06 01:26:29
fppd Uptime:	16:47
Local Git Version:	93f1fff [ChangeLog](http://10.10.1.125/changelog.php)

**Comment by patdelaney** [comment]
Remove the gateway on the ETH0 you don't need it

**Comment by technageek** [comment]
> Remove the gateway on the ETH0 you don't need it

Thank you. It works

**Comment by ghormann** [comment]
I'm just going to close.   I think the error message is generally clear and there are no code changes required.
