### ISSUE TITLE
Volume Control Slider generates hundreds of XHRs, bogging server

### ISSUE THREAD

**Issue by edalquist** [FalconChristmas/fpp#2027]
# Please answer the following:

Version Info |  
-- | --
FPP Version: | 8.2
Platform: | BeagleBone Black (PocketBeagle)
FPP OS Build: | v2024-10
OS Version: | Debian GNU/Linux 12 (bookworm)
Hardware Serial Number: | 1744GPB50307
Kernel Version: | 6.11.0-fpp7
System Boot Time: | 2024-10-31 13:47:41
fppd Uptime: | 47:31
Local Git Version: | 93f1fff ChangeLog

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Status Screen
2. Open Browser Dev Tools to Network tab
3. Mouse over and/or interact with volume slider
4. Observe hundreds of XHR POSTs to /api/system/volume

**Expected behavior**: 
POSTs to /api/system/volume only happen when the volume slider is actually clicked on

**Additional Attachments**
* Screen Recording of issue: https://youtu.be/dCJDzkGI1hI
* [FPP_Logs_20241031.2253.zip](https://github.com/user-attachments/files/17594072/FPP_Logs_20241031.2253.zip)

**Comment by edalquist** [comment]
Should https://github.com/FalconChristmas/fpp/blob/9d6ca9e428e990a761d8e08922eaa552989b9caf/www/index.php#L183 be checking if the mouse button is pressed?

**Comment by OnlineDynamic** [comment]
Fixed in PR#2029
