### ISSUE TITLE
Add Channel Output for TLC59711 PWM IC's

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#203]
https://www.adafruit.com/products/1455

https://github.com/adafruit/Adafruit_TLC59711/blob/master/Adafruit_TLC59711.cpp

http://falconchristmas.com/forum/index.php/topic,4391.0.html

**Comment by hirani89** [comment]
+1 for me. would love to work with higher res pixels.

**Comment by cpinkham** [comment]
I'm going to close this, it may not be needed given the new PCA9685 servo/LED Channel Output.  If we do add support for chips, it may be a part of that same channel output or at least build on it.
