### ISSUE TITLE
Kiosk Button

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#2030]
I'm new to the Kiosk feature and it's very handy!

I'd suggest a checkbox in settings to display a button on the home/status page to directly launch into Big Buttons. I think sitting on the status page is best to monitor the show, but a quick button to go directly to Big Buttons would be better than navigating the menu on small Pi touch screens.

Thanks.

**Comment by darylc** [comment]
You can already do this by putting the big buttons URL in Kiosk Start URL
![image](https://github.com/user-attachments/assets/62d83a79-789a-44c5-a54c-c4adaefaa372)

**Comment by cybercop23** [comment]
He's asking for a button on the main status page when it "knows" its in kiosk mode to "jump" to big buttons; wants both, keep status page jump to BB with a single click.

**Comment by McCoyCOREUSA** [comment]
Correct. Button on status screen to open big buttons.

**Comment by cybercop23** [comment]
> Correct. Button on status screen to open big buttons.

or really.. watever is configured in that URL and maybe also enhance BB if its Kiosk mode to have a button to go to Status screen.
