### ISSUE TITLE
Crash on version (93f1fff) during startup

### ISSUE THREAD

**Issue by koensayr** [FalconChristmas/fpp#2035]
Crash when running version v8.2 93f1fff on a RPi 4B+ 

FPPD seems to startup for a few moments but crashes when attempting to play a sequence or send and DMX data through.

Logs attached.

[fpp-Pi-8.zip](https://github.com/user-attachments/files/17609493/fpp-Pi-8.zip)

**Comment by dkulp** [comment]
You have a DMX output set for 1024 channels.    DMX can only have 512 so it's ending up overwriting a buffer.   We'll get that fixed to truncate to 512, but you should be able to yourself up and running by setting that 512.

**Comment by koensayr** [comment]
Well. That’s embarrassing. I should have caught that. Thank you. On Nov 3, 2024, at 12:19 AM, Daniel Kulp ***@***.***> wrote:﻿
You have a DMX output set for 1024 channels.    DMX can only have 512 so it's ending up overwriting a buffer.   We'll get that fixed to truncate to 512, but you should be able to yourself up and running by setting that 512.

**Comment by dkulp** [comment]
Put a limit in the code (and a warning) to prevent the crash.

**Comment by koensayr** [comment]
Would there have been a commit for this?

**Comment by dkulp** [comment]
https://github.com/FalconChristmas/fpp/commit/286f28d33225e9f91244bde9527466e8532f514f
