### ISSUE TITLE
Networking doesn't update

### ISSUE THREAD

**Issue by krzimmer** [FalconChristmas/fpp#2039]
I installed FPP 8.2 on a RPi5 using the `SD/FPP_Install.sh` script. Everything appears to be working properly except for network settings. The network menu option isn't displayed from the Status/Control dropdown, but you can navigate to it manually by entering the url "/networkconfig.php".

After doing some research, maybe this issue is occurring because Pi uses Network Manager (nmcli) versus /etc/network/interfaces.

**Comment by patdelaney** [comment]
Why did you use the install script rather than burn the SD card image?

to enable the networking I believe you need the --img flag argument.   The install script is typically meant for VM's or O/S's that we do not have an image for.

**Comment by krzimmer** [comment]
I wanted to host FPP and LedFx on the same Pi5. I started by burning the image for FPP then install LedFx. I couldn’t get past compile errors. I raised the issue with the LedFx project. Their stance was that LedFx installs without issue on RaspbianOS. So, I attacked from the other direction. I burned RaspbianOS, installed LedFX without issue, and then installed FPP with minimum issues. I haven’t found any issues other than with networking.

**Comment by ghormann** [comment]
I personally don't see this as something we'll address.   I think the install script is clear on this point.  FPP APIs make some assumption about the networking environment.

# NOTE: This script is used to build the SD images for FPP releases.  Its
#       main goal is to prep these release images.  It may be used for othe
#       purposes, but it is not our main priority to keep FPP working on
#       other Linux distributions or distribution versions other than those
#       we base our FPP releases on.  Currently, FPP images are based on the
#       latest OS images for the Raspberry Pi and BeagleBone Black.  See
#       appropriate README for the exact image that is used.

**Comment by dkulp** [comment]
It's working as designed.   If you want fpp to manage networking, you need to pass -img to the script and it will install the stuff that is needed.   If -img is not passed, it assumes networking is being managed however is "normal" for that linux distribution and thus the networking page is not displayed as it won't work.

**Comment by krzimmer** [comment]
Ok. Sounds good. I didn't know that `-img` existed. I'll start from scratch and install using that.

**Comment by krzimmer** [comment]
That worked. I started with the latest RaspbianOS, removed the desktop environment, installed LedFx and then installed FPP using `SD/FPP_Install.sh --img`. Everything looks good.
