### ISSUE TITLE
Effect at start of sequence missed by LOR hardware

### ISSUE THREAD

**Issue by Joetripp** [FalconChristmas/fpp#204]
There's a problem when an effect is right at the start of an XLights sequence and then subsequently saved as fseq and played on FPP to a LOR controller.  That first effect will either be skipped entirely, flicker wildly, or come in really late but end on time. Saw this with both V2 and V3 CTB16PC LOR controllers and it didn't matter what one was first or second in the chain.  Sadly if the sequence is 30 seconds long and the first effect is a 30 second ON for the channel and it is not picked up the channel will never come on.
I set up a 2 second "ON" effect for both controllers right at the start of the sequence followed by 1 second on/off alternating for 28 seconds.  Sometimes one of the two controllers would pick up the early 2 second effect but most times not.  Sometimes I'd see one flicker and the other would come on properly. Out of 10 times they both came on right for that first 2 second ON effect 2 times -a  20% success rate.  I didn't try different port refresh rates.  The controllers were daisy chained off of each other.  If played directly from XLights to the controllers it worked fine.  Almost like it's not 'waking up' the controller initially.

**Comment by cpinkham** [comment]
I believe this may be due to the LOR controller's auto-detect code missing the first packet while checking to see whether the player is sending LOR or DMX.  We may need to allow sending the same channel values a couple times a the beginning of a sequence even though it is not optimal.

**Comment by darylc** [comment]
lets close this issue
