### ISSUE TITLE
FPP OS upgrade followed by updating to compat plugin version broke plugin

### ISSUE THREAD

**Issue by aggieNick02** [FalconChristmas/fpp#2040]
**Describe the bug and Steps to reproduce**:
Was on FPP 7.2 on BBB and wanted to upgrade to latest. First updated FPP to 7.5, then did in-place OS upgrade to 8.2.

Everything went fine. When all done, I was told that the Si4713/Vast V-FMT212R was not compatible. UI said there was a compatible version available, so updated it.

After that, FPPD complained it could not load the plugin. Log file showed:
`2024-11-07 04:49:26.343 (29498) [Plugin] /opt/fpp/src/Plugins.cpp:492: Failed to load shlib: libjsoncpp.so.24: cannot open shared object file: No such file or directory`

Checked and the OS image has libjsoncpp.so.25. Looked at my plugin install log to see no "install" of plugin corresponding to updating the plugin. So without rebuilding the plugin, it was still pointing to the old OS's libjsoncpp.so.24

**Expected behavior**: 
I'm just wondering if I did something wrong in this sequence of steps to upgrade, or if the vast plugin should somehow be triggering a rebuild and isn't.  After manually uninstalling and reinstalling the plugin, the plugin was linked to lilbjsoncpp.so.25 and worked fine.

I've attached my install_plugin.log file. In it you can see the original install of the plugin in 2022. There is no log entry corresponding to when I upgraded the plugin. The last log entry is when I reinstalled it after uninstalling.

[install_plugin.log](https://github.com/user-attachments/files/17656362/install_plugin.log)

**Comment by darylc** [comment]
This is expected, plugins need to be uninstalled and reinstalled after an FPPOS upgrade.

**Comment by aggieNick02** [comment]
Ah ok, thanks, I didn't realize. Did I miss an obvious warning somewhere (quite possible) or would it make sense to let users know when they upgrade?

**Comment by patdelaney** [comment]
We are going to add a warning message.

**Comment by aggieNick02** [comment]
Thanks!
