### ISSUE TITLE
Upgrade to 8.3OS failed with error message on Pi4

### ISSUE THREAD

**Issue by jeffla** [FalconChristmas/fpp#2043]
<img width="738" alt="Screenshot 2024-11-08 at 1 27 30 AM" src="https://github.com/user-attachments/assets/8d685e1b-0aa8-49af-beb5-028332ccf4ba">
<img width="507" alt="Screenshot 2024-11-08 at 1 30 11 AM" src="https://github.com/user-attachments/assets/4f2c2730-9dcc-4f6a-9644-7b7c24dcfc04">

**Comment by JonD24** [comment]
Your 8.2 installation is at the wrong OS level.  Print screen shows it as v2024-09 and it should be v2024-10.  Might not have followed the installation directions correctly.  Make backup of FPP, try installing FPP 8.2 OS v2024-10 over the top of what you have and verify OS is at v2024-10 before proceeding to 8.3

**Comment by jeffla** [comment]
"Might not have followed the installation directions correctly." That is not out of the realm of possibilities. It's been a while since I re-imaged. Today is the day. 😂

**Comment by JonD24** [comment]
You should be able to install OS v2014-10 over the top of what you have.  Just suggested to backup to be safe.  Several people missed the directions in bold black letters including myself, and is not uncommon issue.  Welcome to the club! ;)
