### ISSUE TITLE
FPPD fails to start on SanCloud Enhanced/K16/FPP 8.3

### ISSUE THREAD

**Issue by wingrunr21** [FalconChristmas/fpp#2047]
# Please answer the following:
**FPP Version and Hardware**: 
FPP 8.3 running on SanCloud Beaglebone Enhanced w/ K16A-B version 3

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

1. Boot FPP
2. The Abnormal Conditions banner pops up after FPPD fails to start:
![image](https://github.com/user-attachments/assets/da76389b-8bae-491a-b44f-86a4f603db3e)
3. Attempts to manually start FPPD fail. The crash logs will increase up to 10-11 and stay at that number.

**Expected behavior**: 
FPPD starts correctly

**Additional context**: 
This is happening on two brand new builds (both have the same setup). It's a clean install of FPP, running off the eMMC, with no other settings, schedule, etc configured

**Additional Attachments**
[FPP_Logs_20241110.0324.zip](https://github.com/user-attachments/files/17690054/FPP_Logs_20241110.0324.zip)

**Comment by dkulp** [comment]
This should now be fixed on master if you want to try flipping to master branch and testing

**Comment by wingrunr21** [comment]
Works! Thanks for the quick turnaround!
