### ISSUE TITLE
Enhancement: Add export to CSV option to Multisync page

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#2056]
**Is your feature request related to a problem? Please describe.**
I would like to be able to export the mutlisync page to CSV

**Describe the solution you'd like**
Add an option to export the page as CSV

**Comment by darylc** [comment]
Hi Pat, this data is exposed by the API, perhaps you could convert the json to csv?
http://fpp.local/api/fppd/multiSyncSystems

**Comment by patdelaney** [comment]
@darylc thanks for the heads up on the API. I did run it and took the output and ran it through an online json to csv converter, https://www.convertcsv.com/json-to-csv.htm  and that produced a file. This did solve my immediate need. But I thinkthe ability to do this from the UI would be cool.

I'm ok with leaving this for 9.x wish list

**Comment by ghormann** [comment]
@patdelaney  Maybe I'm not awake enough yet this morning, but how is this request different from the export button I added a few years ago?

![image](https://github.com/user-attachments/assets/68235fd3-7cec-48b6-a0ee-0b0e9bc3bcab)

**Comment by patdelaney** [comment]
Ugh I can't belive I forgot about that button.
Thanks
