### ISSUE TITLE
Add row indicator to show disabled.

### ISSUE THREAD

**Issue by Joetripp** [FalconChristmas/fpp#206]
I'd love to see a change both for FPP (and XLights) where if a row is disabled it shows as red text or red background - either one.

**Comment by rawcreative** [comment]
What are you referring to exactly? When outputs are disabled?

**Comment by Joetripp** [comment]
Yes on the Outputs screen. If an output is unchecked a visual indicator to show this would be helpful in case it was done by accident.  I can see this being useful on the Scheduler page too.  There may be other places that would make sense.

http://falconchristmas.com/forum/index.php/topic,4420.msg46964.html#msg46964

**Comment by rawcreative** [comment]
Yep, already exists in the v2 UI. In addition to the visual difference of the toggle switch (which replaces the 'Active' checkbox in v1), any disabled or inactive output is subdued compared to the others. If the outputs are turned off completely (the switch up top), all outputs are greyed out and a message is displayed. 

![outputs](https://cloud.githubusercontent.com/assets/1143718/13080509/f455e23a-d496-11e5-9dca-f0773883a2a3.png)

**Comment by Joetripp** [comment]
you guys rock!
