### ISSUE TITLE
Tool Tips in MQTT page may be incomplete or Truncated.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#2061]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
**FPP Version and Hardware**: 
Example: *FPP 8.x running on Pi*

**Describe the bug and Steps to reproduce**: 
From an email:  Do you know where I can find the rest of this message? Since v8 it's been truncated and I'm tryhing to find the topics to use?
![image](https://github.com/user-attachments/assets/bba6081a-c51f-45f4-9e9c-fa02b0e6304d)
This example is for MQTT Subscribe Topic

**Expected behavior**: 
Perhaps a section in the manual or in FPP help that has MQTT information in it.

**Comment by ghormann** [comment]
I found the bug.  I'll fix it.  It use to state the following: 

Subscribe to a MQTT topic.  Use '#' (without the quotes) to subscribe to all topics from MQTT server.  Use 'smartthings/#' to subscribe to all topics starting with 'smartthings', or use an exact topic to subscribe to a single topic.
