### ISSUE TITLE
Null Pixels Not Working Properly

### ISSUE THREAD

**Issue by ChooChooMan74** [FalconChristmas/fpp#2073]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
Running Fpp 8.3.1, K16V3, Receiver 21-24 Outputs, SRX1v5.

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Added 2 ports of 99 pixel candy canes. 3 on 1 port and 2 on the other port.  First I added a null pixel on the end of each candy cane and the extra pixel lit and the last pixels didn't light.  Then I tried start nulls with the same results.

**Expected behavior**: 
Null pixels are not expected to light

**Additional context**:

**Comment by ChooChooMan74** [comment]
In testing, when adding a null to a 99 null prop, it appears to null one of the modeled pixels.

**Comment by ChooChooMan74** [comment]
After post season testing, this issue only seems to happen from the I/O Channel Out page. I like to do port number testing when setting up. When duplicating now, it still does it during I/O testing, but regular testing works fine.

**Comment by Poporacer** [comment]
Good to know, Port testing is a High Level test just for the overall port and not model level, so it just blasts the port with the appropriate data. Model testing is more low level to test those attributes.
