### ISSUE TITLE
Updated....now what?

### ISSUE THREAD

**Issue by Shredder5262** [FalconChristmas/fpp#2074]
So This is the first time I've attempted to update FPP since installing it. I don't have a fancy setup or anything just the FPP connected to 4 strings of lights for my christmas tree. I went to the about page, selected upgrade OS and waited... I got the message below after the download was done...nothing seemed to happen that i could tell (i.e. no reboot or anything). I forced a reboot, still on the same version...so not sure what to do at this point. I read the instructions, but not sure if i could have done anything different besides clicking the button.  I'm currently on V5.5

FPP OS Upgrade
Image: Pi-8.3_2024-11.fppos
==========================================================================
Upgrading OS:
Checking for previous /home/fpp/media/tmp/upgradeOS-part1.sh
Image of '' does no match 'Raspberry Pi'
==========================================================================
Rebooting.....Close this window and refresh the screen. It might take a minute or so for FPP to reboot

My current version info 

Version Info |  

FPP Version: | 5.5
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v5.3
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 10000000ae74afcf
Kernel Version: | 5.10.63-v7l+
System Boot Time: | 2024-11-29 17:39:57
fppd Uptime: | 05:50
Local Git Version: | 7fa4149 ChangeLog (Update is available)
Remote Git Version: | 169da65 Preview Changes

**Comment by ghormann** [comment]
Honestly, if you are at 5.5, would *NOT* recomend trying to do an fppos upgrade direct to 7.x or 8.x.  I've tried this in multiple devices and always ended up with something that won't boot.   (I think it is related to a change between 5.x and 7.x).    My recomendation would be to use the "Fpp Backup" menu item to back up your configuraiton to your laptop, and then to create a new image from https://github.com/FalconChristmas/fpp/releases/download/8.3/FPP-v8.3-Pi.img.zip and restore that from backup.   .

**Comment by cybercop23** [comment]
We have folks on zoom, do this all the time, no issues. Make sure you're on the latest 5.5. We do have them run the update twice, but a whole lot easier

**Comment by Shredder5262** [comment]
> Honestly, if you are at 5.5, would _NOT_ recomend trying to do an fppos upgrade direct to 7.x or 8.x. I've tried this in multiple devices and always ended up with something that won't boot. (I think it is related to a change between 5.x and 7.x). My recomendation would be to use the "Fpp Backup" menu item to back up your configuraiton to your laptop, and then to create a new image from https://github.com/FalconChristmas/fpp/releases/download/8.3/FPP-v8.3-Pi.img.zip and restore that from backup. .

Thanks, I tried a bunch of crap that didn't work. Then I decided to try the os upgrade again, but only going to v6...that worked, so then I tried v7.5, that also worked, I then tried v 8.3 and had a little trouble but eventually that worked also, So yeah, I was trying to do to big of a jump. Happy for this to be closed
