### ISSUE TITLE
Nested scheduled items no longer work

### ISSUE THREAD

**Issue by jlange6648** [FalconChristmas/fpp#2076]
**FPP Version and Hardware**: 
FPP v8.3.1 on BBB

**Describe the bug and Steps to reproduce**: 
I have a nested schedule where starting at 4:30PM, I play a static animation sequence that ends at 11 PM. Then starting at 5:30 PM running to 10:00 PM I have a playlist running. In previous versions of FPP this always worked perfectly as expected. However, in 8.3.1, the static animation starts at 4:30, and the status page says that the next item in the schedule is the playlist at 5:30, but it never advances to the playlist. if I hit the start next button, it will move onto the playlist. but it will not start on its own.

**Expected behavior**: 
The nested playlist should start and end at the expected times.

![image](https://github.com/user-attachments/assets/8a5d9731-2634-4220-99ad-ba185b51db13)
![image](https://github.com/user-attachments/assets/cc3e9d6d-2905-4efe-b31f-ca6ad640edcd)

**Comment by jlange6648** [comment]
![image](https://github.com/user-attachments/assets/33b831b0-b618-49c2-94d4-a8c9f7ff8e14)

**Comment by cybercop23** [comment]
WAD.. All in the Notes!!!
![image](https://github.com/user-attachments/assets/dee06ed3-df77-4ad2-9394-9a5ac9cb44f7)

**Comment by jlange6648** [comment]
OK. easy enough fix, but if this is the case, then the preview shouldn't imply it will work as it shows, and the header on the main page shouldn't say the next item will start at the scheduled time, if it actually wont.

**Comment by derwin12** [comment]
In your case you just want those two items reversed. The preview needs to be a bit more intelligent. Since the top checked item is set to immediate it will never relinquish the control to the subsequent item.

**Comment by jlange6648** [comment]
Fixing the order did resolve the issue, but I still think there should be a ticket for revising the preview and the "up next" in the header bar to show what is really going to happen.

**Comment by Poporacer** [comment]
The Preview page has been updated to show scheduled items that are skipped 
![image](https://github.com/user-attachments/assets/9dbcd85a-bd51-49a4-8111-e39762dcb420)
Up next would be problematic since an overlapping schedule might or might not be totally skipped based on all of the schedules.
