### ISSUE TITLE
Publish an API to Provide Actual Playlist Playback Order

### ISSUE THREAD

**Issue by rdkbob** [FalconChristmas/fpp#2079]
I'm trying to reliably get the next media file to be played by the FPP, before it starts.

The `playlist/:PlaylistName` API allows for retrieval of a playlist, but the response is a static look at the playlist that does not account for a randomized order that may be set on load or on each iteration, if these options are selected.

The FPP UI appears to use `fppd/playlist/config` to get the actual "to be played" order of the loaded playlist.  However this API is not documented in `apihelp.php`.  Is this API ok to use?  Or is there a reason this is undocumented?

If this API is not meant to be used outside of the FPP UI, is there an alternative?

**Comment by dkulp** [comment]
The api/system/status would have the information you need in it.   However, it's a bit more heavy weight so not something I'd encourage calling more than once a second.  Even then I'd back off that.

Q:  in the PulseMesh plugin itself, could you call playlist->GetConfig() which would give you the exact json from the playlist in memory.  There is also GetCurrentStatus, but that would have more information than you need.  

I'm wondering if it might make sense to also add hooks into playlist so the plugin could get events/notifications when InsertPlaylistAsNext/Immediate is called so you can prepare as that would be jumping out to an entirely different playlist.

**Comment by rdkbob** [comment]
Thanks for the quick response.  Looking at the response of api/system/status I'm not seeing any information that would tell me the next song, although the next playlist is there.  Am I missing it?

I'll look into playlist->GetConfig() as that would be preferable to calling an API.  I assume this would include the current randomized list if randomization is enabled?

Yes, it would be great to have a way to get a notification when InsertPlaylistAsNext/Immediate is called.  Right now I have to tail (Inotify) the Remote Falcon log to figure out what it has inserted.  This obviously doesn't work with anything else using InsertPlaylistAsNext and I would love to remove this workaround.

**Comment by dkulp** [comment]
Sorry, you're right.  The main webpage calls fppd/playlist/config first to get the playlist and then system/status to just highlight the current entry.  

The GetConfig() creates the json directly from the elements in the arrays in memory.  Thus, the current randomization would be taken care of.

**Comment by dkulp** [comment]
New API for that now on master....

**Comment by rdkbob** [comment]
Awesome, thanks so much!  Closing this issue as my questions are answered and new API is on master.
