### ISSUE TITLE
Master-v1.x  FPPD is stopping (Octoscroller installed)

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#208]
But, the BBB with an F4-B cape is not stopping.

The one with the Octoscroller will Restart FPPD just fine, but will stop at the end of an fseq (it is a Remote)

The fppd.log file shows an error message concerned about the associated sound file. The file is not on the BBB.

Seems to stop the FPPD between every FSEQ file when the Master is playing a list. If I restart, it stays running until the end of that FSEQ.

**Comment by cpinkham** [comment]
I believe this was fixed or is not an issue anymore.  Closing.

**Comment by JonB256** [comment]
Confirmed - v1.8 works well with the octoscroller
