### ISSUE TITLE
FPPD crashing on K128 while running playlist

### ISSUE THREAD

**Issue by compufritz** [FalconChristmas/fpp#2081]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:  8.4.1 on BBB with K128D cape
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
Having multiple FPPD crash events in the logs and show obvious isn't able to run when that happens. Have seen it happen on both 8.3.1 and now 8.4.1.

**Expected behavior**: 
FPPD to run normally without crashing and stopping the show.

**Additional context**: 
Only plugins installed are the Big Green Button and Remote Falcon, but I currently am not running viewer control mode. Relevant section of the log from tonight's crash:

`2024-12-07 17:39:03.933 (28250) [ChannelOut] /opt/fpp/src/channeloutput/channeloutputthread.cpp:211: SLOW Output Thread: Loop: 10000us, Send: 3060us, Read: 4083us, Process: 48477us, FrameNum: 2715
2024-12-07 17:45:15.584 (28250) [ChannelOut] /opt/fpp/src/channeloutput/channeloutputthread.cpp:211: SLOW Output Thread: Loop: 10000us, Send: 13641us, Read: 160us, Process: 50598us, FrameNum: 1917
2024-12-07 17:45:17.980 (1058) [General] /opt/fpp/src/fppd.cpp:806: Shutting down main loop.
2024-12-07 17:45:18.982 (1058) [General] /opt/fpp/src/fppd.cpp:1028: Stopping channel output thread.
2024-12-07 17:45:18.985 (1058) [General] /opt/fpp/src/fppd.cpp:1032: Main Loop complete, shutting down.
2024-12-07 17:45:20.009 (1058) [General] /opt/fpp/src/fppd.cpp:267: Crash handler called:  7
`

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[fppd (1).log](https://github.com/user-attachments/files/18050158/fppd.1.log)

**Comment by compufritz** [comment]
Changed configuration this morning before tonight's show to try and prevent crashes from occurring thinking maybe the BBB was having a problem being the FPP Player and also outputting to the K128 cape. I set up a Pi3B+ to be the Player and only the player, K128 BBB changed to player. Both running 8.4.1

Everything tested out good after setup and at 5:25pm when my schedule fires off I got the below from the Pi3B+ player fppd logs:
`2024-12-08 17:25:05.226 (2507) [General] /opt/fpp/src/fppd.cpp:806: Shutting down main loop.
2024-12-08 17:25:06.227 (2507) [General] /opt/fpp/src/fppd.cpp:1028: Stopping channel output thread.
2024-12-08 17:25:06.227 (2507) [General] /opt/fpp/src/fppd.cpp:1032: Main Loop complete, shutting down.
2024-12-08 17:25:07.081 (2507) [General] /opt/fpp/src/fppd.cpp:267: Crash handler called:  7`

Looks to be the same crash handler being called with completely different hardware. Again only plugins installed were big green button and Remote Falcon (viewer control not turned on).

Log file from the Pi3B+:
[fppd (3).log](https://github.com/user-attachments/files/18055054/fppd.3.log)

Looking for any guidance on these crashes. I believe I have crash reports being sent automatically, but don't want to check while the show is running to confirm.

**Comment by compufritz** [comment]
Update to the issue. I uninstalled all plugins (Big Green Button and Remote Falcon) prior to last night's show. Schedule fired off at 5:25pm and ran with no crashes the entire night. FPPD.log attached:
[fppd (4).log](https://github.com/user-attachments/files/18079392/fppd.4.log)

So it seems that the plugins, either RF or BGB, were causing the crash for some reason. I will re-install BGB today before my show starts to see what happens and update the issue afterwards. Is there and additional logging I should turn-on to help identify the problem?

**Comment by dkulp** [comment]
The fact that "Shutting down main loop" is appearing there suggests that something is triggering an FPPD stop.  It's crashing after the stop which is a bit concerning, but the fact that it's being told to stop is the main issue.  Maybe turn the "Command" logging up to debug level to see what commands it's getting

**Comment by compufritz** [comment]
Didn't get a chance to comment or upload the logs yesterday. So yesterday I had 'Command' logging set to debug and installed/configured only Remote Falcon. Here is the logs from that:
[fppd (5).log](https://github.com/user-attachments/files/18104955/fppd.5.log)

Reading through it and seeing that the command right before the crashing was 'Remote - ProjectorOn.sh' I was thinking that maybe the remote-runscript scripts were causing the issue seeing as how the script repo says that they "are from other versions and known to not function with this version or have been replaced", so I re-did the playlist to only use FPP commands to execute scripts, both locally and on the remotes. Ended up with the same crash loop occurrence today almost immediately after the schedule started at 5:25pm. Logs from today's problem: 
[fppd (6).log](https://github.com/user-attachments/files/18104991/fppd.6.log)

I forgot to turn debug logging back on so not as much info in that file, but I'm pretty sure the fppdwatcher scripts are the cause of the looping, but still not sure of the reason for the initial crash unless they are also the cause of that if they don't see the correct status of fppd and then start the loop. I repeated my process, which worked last night, of disabling the schedules, uninstalling the RF plugin, restarting fppd, and then starting the playlist manually on repeat to no avail tonight. Still got fppd crash loop occurring until I took the fppdwatcher script out of the lead-in of the playlist which is also guiding me towards that script as the root cause.

Next steps to test will be to re-install the RF plugin and then start the playlist with the fppdwatcher script removed from the lead-in to see what that result that provides. Any other thoughts on what I should test?

Thanks and sorry for the wall of text.

**Comment by patdelaney** [comment]
@compufritz Are you available Thursday night to jump on a Zoom meeting with me?

**Comment by patdelaney** [comment]
I just got home from work, let me know if yo are free.

**Comment by compufritz** [comment]
I'm free and hanging out in the xLights zoom room

**Comment by compufritz** [comment]
Determined the cause of the crash issues was the fppdwatcher.sh script being called.

With the changes to FPP commands and the migration to the API this line of the script fails and returns 'No file found.' as fppjson.php doesn't exist in v8
`curl -m 2 http://localhost/fppjson.php?command=getFPPstatus 2> /dev/null | grep '"running"' > /dev/null`

I think this change will fix it, but I will test later to confirm and then submit a pull request after I verify the fix.
`curl -m 2 http://localhost/api/fppd/status 2> /dev/null | grep '"running"' > /dev/null`

**Comment by compufritz** [comment]
Closing the ticket here as the fix would be a PR in the fpp-scripts repo
