### ISSUE TITLE
FPP_Install.sh on Stretch

### ISSUE THREAD

**Issue by jcochran** [FalconChristmas/fpp#210]
In Jesse:

"systemctl disable serial-getty@ttyAMA0.service" alone is not sufficient to stop the serial console, you must also remove "console=ttyAMA0,115200" from /boot/cmdline.txt.

The "pi" user will continue to auto login after running FPP_Install.sh, need to remove "--autologin pi" or change to "--autologin fpp" in /etc/systemd/system/autologin@.service.

"dtparam=i2c=on" may have been updated to "dtparam=i2c_arm=on" in /boot/config.txt

**Comment by cpinkham** [comment]
Fixed in c692a71
