### ISSUE TITLE
Undisciplined Local Clock

### ISSUE THREAD

**Issue by jcochran** [FalconChristmas/fpp#214]
Adding the following lines to /etc/ntp.conf will allow for an undisciplined local clock (e.g. a device without internet connection and time source itself, but ideally with a RTC) to provide time to other devices on the local network:

```
server 127.127.1.0 
fudge 127.127.1.0 stratum 10
```

**Comment by darylc** [comment]
The FPP development team met and decided that this issue is no longer relevant given all the changes to NTP in FPP since 2016.
