### ISSUE TITLE
Enhancement Request: Gui to install NTP Server.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#215]
Should we make it easier to set up a BBB or FPP with an RTC to be an NTP server so that that isolated  configurations of Master and Slaves and sync to the unit with the RTC?

Perhaps add the installer to the plugin page?

Pat

**Comment by darylc** [comment]
I suggest https://github.com/FalconChristmas/fpp/issues/1067 is a better way to deal with this, and to close this issue.

**Comment by darylc** [comment]
sorry I meant #214

**Comment by cpinkham** [comment]
FPP has allowed setting the NTP server from the Time tab on the settings page for a while now, this ticket should be closed.
