### ISSUE TITLE
Enhancement Request: MultiSync Manual IP Address

### ISSUE THREAD

**Issue by rickcowan** [FalconChristmas/fpp#216]
Allow for the manual entry of an IP address on the MultiSync page. Currently the auto discover of other FPPs doesn't work with VPN. If you wish to use a remote FPP through VPN you have to manually edit the settings file. However, if you make any changes on the MultiSync page then the settings file is overwritten and any IP addresses that had been manually set are lost. Allowing the entry of an IP address on the MultiSync screen would solve this issue. Also, it would allow for the syncing of files direct from the master rather than having to manually place the files on the VPN remote.

**Comment by cpinkham** [comment]
This feature was added to the MultiSync config UI a while ago, closing the ticket.
