### ISSUE TITLE
Enhancement Request: Separate Checkbox For Syncing Files On MultiSync Page

### ISSUE THREAD

**Issue by rickcowan** [FalconChristmas/fpp#217]
Add another checkbox next to all remotes for file syncing purposes. This would be beneficial when you have multiple FPPs that you want to use as remotes but perhaps you don't want to send the files to all of them. An example is, 5 remotes where 2 of them have custom sequences that have been manually loaded on to them. If you uncheck the "Sync Files" checkbox for those 2 then you can still sync the other by clicking on the "Sync Files" button without disturbing the files on the 2 with custom sequences. This ties in with my other request for the manual IP entry. In my case I have 3 remote FPPs at my house which will all get the same sequence. Through VPN I will connect to a 4th FPP that is controlling a different house. Since the house layout is different, the sequences are different (same name of course).

**Comment by cpinkham** [comment]
This was fixed in master in ee314bf964 and is now in v2.6

**Comment by cpinkham** [comment]
Maybe not, I didn't read the per-host part.  I don't know if we will go that far, but will re-open the ticket for now.

**Comment by cpinkham** [comment]
Closing this as a "won't fix".  If you name your unique Remote sequences as "YourNormalSequenceName-YourRemoteHostname.fseq", then you shouldn't have an issue.  FPP looks for a .fesq with the Remote hostname in it and if that doesn't exist, then it checks for a file with the same name as the master .fseq file.
