### ISSUE TITLE
If a sequence is running, Stop it before Restart FPPD

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#219]
A few times I've clicked the Restart FPPD or Stop FPPD buttons while a Playlist is running.

It seems to badly confuse the FPPD. While it eventually recovers, it is always "best" to Stop a playlist before doing any Reboot or Shutdown or Restart FPPD.

Can you add a "Stop" to the script sequence for those buttons?

**Comment by cpinkham** [comment]
Fixed in 3441d89
