### ISSUE TITLE
Artnet Enhancement Request: Listen to Artnet to trigger events 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#224]
This from a participant at the Xlights event in Las Vegas:
I see. I’m glad its in the works because ArtNet is the industry standard and I would love to see some compatibilities.

 I would hope that the next step would be to accept Art-Net commands or sync to time-code in some way. A lot of times a master show controllers will output timecode and all ArtNet devices sync to it. In some cases, the RP would make a great mobile device but not a master (Because we have intel or fireworks or whatever). It would need to accept that kind of data to make it useful for that.

**Comment by cpinkham** [comment]
ArteNet input will be added after the ChannelInput framework is written and the existing E1.31 bridge mode code is converted to use the new framework.  This will be a v2.x feature.

**Comment by cpinkham** [comment]
Basic ArtNet bridge mode was added in 24be33f58.   I don't know how much further we will take this support anytime soon. Closing ticket since the basic initial request has been satisfied.
