### ISSUE TITLE
Enhancement Request: BBB/BBG  Display on About page the Boot Device

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#226]
As a user, I would like something in the UI that tells me whether my BBB or BBG was booted from eMMC or SD card.

**Comment by darylc** [comment]
@patdelaney as a user, do you still want this 5 years later?

**Comment by dkulp** [comment]
The about page currently displays the $full of the boot and media devices.   I DO keep on meaning to add the actual device names to those labels.  Just been very low priority.

**Comment by patdelaney** [comment]
Yes I think we should add it, as it could help troubleshoot end user issues.

**Comment by darylc** [comment]
Looks like this was sorted by https://github.com/FalconChristmas/fpp/commit/2c6f249255c7136aa61c06170ee45c0ad44c7da9

I now see this in the about page.
Root (mmcblk0p2) Free Space: | 10.85 GiB (37%)
