### ISSUE TITLE
Jessie: BBB master branch - /etc/fstab file is not un-commented after selecting USB stick for storage

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#227]
After installing FPP on a fresh Jessie image, after rebooting and then going to the WEB UI, I select the USB stick for storage. When I click reboot it shows and error that it can't write something?  But after reboot I check /etc/fstab and the USB sitck line is still commented out.  This only happens on BBB.

I also suspect that the same problem happens on BBB if you install the OS to the eMMC and they you try to select the micro SD card for storage.

Pat

**Comment by cpinkham** [comment]
This should be fixed in the BBB patches from Dan's Stretch-based branch and will be in master-v1.x and master once we merge the BBB-updates branch.
