### ISSUE TITLE
BBB - Newer jessie installs use kernel too new for our pre-built 8192.ko

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#228]
In addition to the kernel being newer and not working with the 8192.ko, the previous instructions for compiling it and the script used in the compile no longer work.

We need to come up with new set of instructions and possibly add a "--build-8192" option for the installer.

**Comment by cpinkham** [comment]
The next SD images will be based on Raspbian/Debian Stretch and this shouldn't be required because those will have a much newer 4.x.x kernel.  Closing ticket.
