### ISSUE TITLE
BBB: Jessie ping program is broken in jessie version. This breaks various things.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#229]
Ok it appears to be an issue with ping in the jessie version of Debian for BBB.
There are 2 ways we could fix it based an a web article.

We can have the install script change the permissions on the ping command: with this command:

I say just add this to the installer script
sudo chmod u+s /bin/ping

Or then install a different version of ping:
sudo apt-get install inetutils-ping

This will remove iputils-ping and replace it with inetutils-ping.
I switched the packages and that fixed it.
I also took a fresh jessie on BBB and did the permission change and that worded too.
so for now I would just add the permission change to the installer script.
We could get fancy with the script and check to see if it has the correct permissions, but I think just changing them is OK.

**Comment by cpinkham** [comment]
This has been fixed in an upgrade script and there is also a fix in the FPP_Install.sh script in the master branch.
