### ISSUE TITLE
Bug: BBB/BBG USB Audio out sounds crackley with some pops on Jessie

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#233]

**Comment by patdelaney** [comment]
This was not and issue with Wheezy.
=====
I loaded the 1.5 image that we have posted with Wheezy and a couple of observations.

The Audio does play back fine, no crackles or pops.
The Audio Slider volume control was stuck and would not move. I remembered an old post that you had to just delete the volume keyword in the settings file.
I deleted volume, and re saved the file and then hit F5 to refresh the UI display. The slider worked. But it had no effect on the actual output going to the speakers.
I rebooted the BBG and retested the volume control and still nothing. This is on version v1.5-5-ge3c1555 .
I clicked on the update to upgade the BBG to v1.5-57-ga4ebb52  , Re tested and still no output level change.
I am now upgrading to 1.8. v1.8-15-g3be9406 
FPPD would not start, I have rebooted
After reboot FPPD started
Volume control now works ok in Whezzy and v1.8-15-g3be9406 

Pat

**Comment by patdelaney** [comment]
I accidentally closed this and I don't know how to reopen it.

**Comment by dkulp** [comment]
Closing this... I've used BBB USB audio for a long time and I believe the new stretch images are OK.

**Comment by patdelaney** [comment]
I will retest, but on a Pi B  it doesn’t sound good. I used the same USB hardware on a V2 and it sounds fine. I still need to test a B+

 

Pat
