### ISSUE TITLE
BBB: Jessie: WebUI  fppd switched to stopped, then running when you start a sequence.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#234]
When you start a sequence on a BBB running jessie and the master branch, if you click Play, then check the FPPD status in the UI, you will see that it goes to FPPD is Stopped, then a few seconds later it goes to FPPD is Running.  You can see a demo here: https://youtu.be/f8IChRLrBaw

This is not the same behavior on Wheezy with master-v1.x branch.

**Comment by dkulp** [comment]
Since this is ancient, can we close this?   Is the new stretch images doing the same thing?

**Comment by cpinkham** [comment]
Going to close this, as I haven't heard any reports of it or seen it lately.  If it comes up again, we can reopen.
