### ISSUE TITLE
Next Playlist Status on UI delay or failure to update

### ISSUE THREAD

**Issue by jholmes09** [FalconChristmas/fpp#235]
First: When creating a schedule that starts multiple playlists at varying times of the day, the status page of the FPP web interface does not update the "next playlist" section after the last playlist of the day has been played. Typically, the "next playlist" section updates to show the next playlist on the schedule, but this does not happen when the next playlist is the following day or the schedule is starting its cycle (meaning the series of playlists scheduled) over again.

Second: In some cases, particularly when a short scheduled event is paired with a long scheduled event, the "next playlist" section appears to skip the long scheduled event. See the final screen-shot for this. Not shown is the additional schedule I added to loop a sequence from 13:05 - 14:00. 

See attached screen-shots for references. 

<img width="875" alt="screen shot 2016-07-01 at 1 16 27 pm" src="https://cloud.githubusercontent.com/assets/18503894/16642182/2ee4a7c0-43bd-11e6-9c0d-cd8035d3a6af.png">
<img width="819" alt="screen shot 2016-07-01 at 1 16 17 pm" src="https://cloud.githubusercontent.com/assets/18503894/16642183/2ee49726-43bd-11e6-9ede-dc15686d6a99.png">
<img width="893" alt="screen shot 2016-07-05 at 10 03 33 am" src="https://cloud.githubusercontent.com/assets/18503894/16642184/2ee51110-43bd-11e6-8d52-930605f44158.png">

**Comment by cpinkham** [comment]
The scheduler underwent quite a few changes during late 2019 and the beginning of 2020, I believe this is fixed by those changes.  If we can reproduce the issue on the current 3.5.x code, we can look into it again.
