### ISSUE TITLE
"Next Playlist" broken in some situations

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#236]
See http://falconchristmas.com/forum/index.php/topic,5101.msg53542/topicseen.html

The "next playlist" reporting may be broken when playlists are back to back and when playing the last playlist of the day until the scheduler re-runs at midnight.

**Comment by jholmes09** [comment]
Also see issue #235 for consolodated description and images

**Comment by cpinkham** [comment]
Closing this ticket as a dupe of #235 since the link above points to jholmes09's thread on the forum.
