### ISSUE TITLE
Schedule stops manually started playlist but does not play scheduled playlist

### ISSUE THREAD

**Issue by jholmes09** [FalconChristmas/fpp#238]
Found this by accident. See logs. We have a schedule set to play at 16:00 till 16:05. Prior to this, I started a playlist manually from the Status page, which looped continuously till 16:00. At 16:00, the system gracefully stopped the playlist but did not start the scheduled event. 
[fppd (2).log.zip](https://github.com/FalconChristmas/fpp/files/355050/fppd.2.log.zip)

**Comment by cpinkham** [comment]
This should be fixed in master and v2.6.
