### ISSUE TITLE
Merge settings files

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#24]
Merge pixelnetDMX file, E1.31 universes file, bytes received file, and schedule files into main settings file so common handlers, file utilities, etc. can be taken advantage of, not to mention one concise place for all configuration to take place.

**Comment by cpinkham** [comment]
Closing this ticket.  channel inputs will be separate from channel outputs.  bytes received shouldn't be in a file, we should get this directly from fppd, and schedule will move to its own json file eventually.
