### ISSUE TITLE
E1.31 output from a Remote is stopping (v1.8)

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#245]
Perhaps related to #240 

I am running a Raspberry Pi Model B for output to an F16v2. The Pi is configured as a Remote and has two FSEQ files installed. The Master is playing those two FSEQ files in a loop with a 5 second pause between.

Multiple indications that the E1.31 output from the Pi is stopping after starting the second FSEQ file. It plays the first, pauses, starts the second, then stops outputting E1.31.

The FPPD indication on the RasPi B shows it as still running, but the Packet count on the F16v2 stops, the RJ45 lights on the F16v2 stop fast flickering, the lights on my local ethernet switch also stop the data light flicker normally seen. Tried with Unicast and with Multicast but no difference. Stopped output when second FSEQ starts playing.

After verifying that my setup was normal (never more than 64 universes) and rebooting, I tried rolling back to v1.5.  
Now it works, all the time. Went through 8 cycles without pause.

Upgraded to v1.8.  Problem resumed.

If I Stop and Start the FPPD, it will play again, one time.

**Comment by JonB256** [comment]
There appears to be a problem in v1.8 when the Master Playlist repeats a sequence (same exact name).

In one playlist, I had an FSEQ, then a pause, then the same FSEQ, then a pause. That was set to repeat. When it hit the second occurrence, it would start playing then stop.
That did not happen in v1.5 or v1.7 (I didn't test v1.6 since v1.7 worked)

Is there some sort of duplicate checking logic in v1.8 for Remotes?

**Comment by cpinkham** [comment]
Can you tell me if it happens in v1.7 or is it a v1.8 issue?  That will help me pinpoint when the problem occurred.

Chris

**Comment by JonB256** [comment]
In v1.7, it did not happen. The E1.31 output continued without interruption. Pauses had no output, but it picked up when the next FSEQ started.

in v1.8, I even checked the "Always Transmit Channel Data" box and it stopped transmitting. The FPPD continued on as if it was actually working. I only noticed that it wasn't when I opened up the F16v2 status window and turned on Live Update (and it wasn't updating).

**Comment by JonB256** [comment]
This is a fresh install (new SD card, new flash drive) of v1.8. Only 2 days ago.

If it was happening last week, I never caught it. The difference between then and now is that I removed a SainSmart audio hat. Is there a possibility that the change in audio setup has anything remotely to do with this?

**Comment by JonB256** [comment]
I configured an F4B (v1.8), running as a wireless Remote, to output E1.31 on wlan0. Since it is wlan0, I am only outputting on Universe 1 and 2, unicast.

The E1.31 output continues through multiple cycles.

**Comment by JonB256** [comment]
So far, every Remote running v1.8 latest rev has quit output E1.31.  One of them, a RasPi3, quit because FPPD stopped (see my other recent entry). When I restarted FPPD on it, E1.31 output came right back with no intervention.

**Comment by JonB256** [comment]
Question - in v1.8 particularly, is there a difference in the way a Playlist is handled as a "Scheduled" playlist with Repeat checked vs. running that same Playlist from the Master status window with Repeat checked?

I ask, because this problem (E1.31 output stopping) is NOT happening when the same playlist is running because a Schedule exists. Plus, the two RasPi 3's with Matrix Hats seem to be better synchronized (per my eyeball).

**Comment by JonB256** [comment]
I'll set back up for this soon.

**Comment by JonB256** [comment]
I've lost my "troubleshooting" train of thought on this issue, but I'm no longer having this problem.

Dave Pitts thinks it may have been due to having 90 universes defined on the F16v2 instead of 64. I changed to 64 and haven't lost E1.31 activity in over a week.

**Comment by cpinkham** [comment]
Closing for now, ticket can be reopened if issue comes back up.  Thanks for reporting back, this will be high priority if it does come back up.
