### ISSUE TITLE
Might need updated SSL certificate authorities on BBB?

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#246]
Based on the error message, I'm guessing something is wrong with the trusted authorities on the BBB and a package update or one-liner might fix this.

http://falconchristmas.com/forum/index.php/topic,5370.msg55631.html#msg55631

**Comment by cpinkham** [comment]
Not sure what this issue ever was, but if it was due to the certs on the BBB, this is fixed in the Debian Stretch based v1.9 images so shouldn't be an issue going forward now or in the next BBB image.
