### ISSUE TITLE
fpp timings

### ISSUE THREAD

**Issue by robbaldwin12** [FalconChristmas/fpp#248]
I know this was stated last year some time that the fpp reads the header on the fseq and adjusts the timings accordingly... i can not verify the bbb version but the pi version this isnt working ... the sequence just plays at 1/2 speed if set to 25ms

https://vimeo.com/175770093
50ms timing

https://vimeo.com/175788548
25ms timing 

both were the exact same sequence one i just changed the timings to 25ms both were done in xlights which is supposed to have the timing in the fseq header. (the status page showed the time remaining on the 25ms sequence as 4 minutes and some seconds at the start and took off 1 second every 2 so it thought the sequence was supposed to be the same length).

Reposted from the falcon forums

**Comment by cpinkham** [comment]
This issue was found and corrected and merged into v1.8 and v1.9.  With the channel output thread not stopping between sequences, the updated default timing wasn't being read until the next time the thread needed to be started.  Now, we set the new timing whether we have to start the thread or not.
