### ISSUE TITLE
Change Volume

### ISSUE THREAD

**Issue by Wonderlandatroseville** [FalconChristmas/fpp#250]
Changing volume via script or ssh

fpp@FPP /opt/fpp/bin.pi $ /opt/fpp/bin.pi/fpp -v 98 
2,1,Setting Volume,,,,,,,,,,                                                                                                                                                                                     
fpp@FPP /opt/fpp/bin.pi $ /opt/fpp/bin.pi/fpp -s                                                                                                                                                                 
2,1,98,/home/fpp/media/playlists/1,m,,All I Want For Christmas Is You.mp3,1,1,101,132,No playlist scheduled.,,1                                                                                                  
fpp@FPP /opt/fpp/bin.pi $
 
Status says it changed, but in reality, it didn't.

Slider in web interface works fine

Using headphone jack

**Comment by Wonderlandatroseville** [comment]
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get Master                                                                                                                                                                 
amixer: Unable to find simple control 'Master',0                                                                                                                                                                 
                                                                                                                                                                                                                 
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get master                                                                                                                                                                 
amixer: Unable to find simple control 'master',0                                                                                                                                                                 
                                                                                                                                                                                                                 
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get master
amixer: Unable to find simple control 'master',0                                                                                                                                                                 
                                                                                                                                                                                                                 
fpp@FPP /opt/fpp/bin.pi $ sudo amixer scontrolls    
amixer: Unknown command 'scontrolls'...                                                                                                                                                                          
fpp@FPP /opt/fpp/bin.pi $ sudo amixer scontrols                                                                                                                                                                  
Simple mixer control 'PCM',0                                                                                                                                                                                     
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get pcm  
amixer: Unable to find simple control 'pcm',0                                                                                                                                                                    
                                                                                                                                                                                                                 
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get PCM
Simple mixer control 'PCM',0                                                                                                                                                                                     
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined penum                                                                                                                                              
  Playback channels: Mono                                                                                                                                                                                        
  Limits: Playback -10239 - 400                                                                                                                                                                                  
  Mono: Playback -4865 [51%] [-48.65dB] [on]                                                                                                                                                                     
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get PCM
Simple mixer control 'PCM',0                                                                                                                                                                                     
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined penum                                                                                                                                              
  Playback channels: Mono                                                                                                                                                                                        
  Limits: Playback -10239 - 400                                                                                                                                                                                  
  Mono: Playback 400 [100%] [4.00dB] [on]                                                                                                                                                                        
fpp@FPP /opt/fpp/bin.pi $ /opt/fpp/bin.pi $ /opt/fpp/bin.pi/fpp -v 1                                                                                                                                             
-bash: /opt/fpp/bin.pi: Is a directory                                                                                                                                                                           
fpp@FPP /opt/fpp/bin.pi $ /opt/fpp/bin.pi/fpp -v 1                                                                                                                                                               
2,1,Setting Volume,,,,,,,,,,                                                                                                                                                                                     
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get PCM                                                                                                                                                                    
Simple mixer control 'PCM',0                                                                                                                                                                                     
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined penum                                                                                                                                              
  Playback channels: Mono                                                                                                                                                                                        
  Limits: Playback -10239 - 400                                                                                                                                                                                  
  Mono: Playback -4865 [51%] [-48.65dB] [on]                                                                                                                                                                     
fpp@FPP /opt/fpp/bin.pi $ sudo amixer get PCM

**Comment by rudybrian** [comment]
Since the web interface is working, you can just use the same API call to set the volume that the web interface is using until this gets sorted out. 

To set the volume to 86%, this would be:
`/usr/bin/curl "http://localhost/fppxml.php?command=setVolume&volume=86"`

**Comment by ihbar** [comment]
Hello
I have tested with version 2.6, the ssh command is working when using the jack output, and UI is in sync.
Some big work around volume has been performed last year to include volume in playlist, it seems the problem has been fixed.  (Thanks to David or Chris)
I suggest to close the issue
@Wonderlandatroseville , is it ok for you ?
