### ISSUE TITLE
Pi3 running FPD and E1.31 out stopped with latest v1.8 update

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#252]
Been running non-stop until todays update to  v1.8-64-g0da4ff4  

Ran Windows checkdisk on the flash drive, no change, no FPPD running.
Installed new uSD card using v1.8 image. It no longer ran FPPD even before updating v1.8 to  v1.8-64-g0da4ff4

But, change it to v1.9 and it runs just fine.

This is a Pi3, running both wlan0 for internet and control and using eth0 for E1.31 output (Enable Routing is checked so I can reach two F16V2 boards). 

It also has an FPD attached to run DMX and Pixelnet.

**Comment by cpinkham** [comment]
Closing this since I think this issue has been resolved.  I have not experienced this issue at all on Pi 3 running v1.9/v1.10/master-v1.x code this year.  Users will be encouraged to upgrade to v1.10 after the holiday season.
