### ISSUE TITLE
REQUEST: Add Sqlite3 to base image

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#275]
Would it be possible to add sqlite3 to the base image to be used by some plugins or store information? Or should it be designed as a plugin to install the Sqllite3 OR just have it installed manually if required? 
OR --- 
Should we consider something else for a database backend. One that would be accessable through the network (mysql is big...)

**Comment by cpinkham** [comment]
sqlite3 was added via an upgrade script in v1.10 and master and is also in the new FPP_Install.sh script in the master branch which will be used to create the next SD image.
