### ISSUE TITLE
Ability to define LED panels on generic DEBIAN/VM Image

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#277]
Have the ability to use the LED outputs to define on a VM or non BBB/PI .
Unable to generate channelsoutput.json file due to this. 

Workaround: create a channeloutputs.json file on a fpp on a pi or bbb, and move it to the VM and fire it up - that works.

**Comment by cpinkham** [comment]
Closing ticket, this feature was added in v1.10.
