### ISSUE TITLE
Pi-createNOOBS.sh missing assets

### ISSUE THREAD

**Issue by theturtle32** [FalconChristmas/fpp#279]
I'm trying to create a new NOOBS image from having just built FPP master (2.0-alpha?) on Raspbian, but the script fails when it tries to replace the Raspbian logo file and Raspbian slides with the ones from FPP -- because those files don't exist in the fpp repo on GitHub!

For now I've just commented out that part of the script. But you might want to throw those into the git repo for the future?

**Comment by cpinkham** [comment]
We are no longer using NOOBS going forward, so I have removed this file from the master branch.  If you want to setup FPP yourself, install the latest Raspbian Wheezy Lite image and install FPP using the FPP_Install.sh script in the v1.9 branch or install Raspbian Stretch Lite and install FPP using the FPP_Install.sh script in the master branch.  Stretch support is currently a work in progress, we have a few more fixes that are in the BBB branches that will get merged to master after the new year.
