### ISSUE TITLE
Website wiki not working

### ISSUE THREAD

**Issue by MaitreDede** [FalconChristmas/fpp#280]
Hi,
I am trying to access to your website's wiki at http://www.falconchristmas.com/wiki/
```
Strict Standards: Declaration of Auth_SMF::modifyUITemplate() should be compatible with AuthPlugin::modifyUITemplate(&$template, &$type)
Strict Standards: Declaration of Auth_SMF::allowPropChange() should be compatible with AuthPlugin::allowPropChange($prop = '')
Strict Standards: Declaration of Auth_SMF::initUser() should be compatible with AuthPlugin::initUser(&$user, $autocreate = false)
Warning: Cannot modify header information - headers already sent by (output started at )
```
(removed file/lines, and multiple Warnings)

**Comment by dpitts** [comment]
We are working on it.On Sep 21, 2017 6:08 PM, Damien DALY <notifications@github.com> wrote:Hi,
I am trying to access to your website's wiki at http://www.falconchristmas.com/wiki/
Strict Standards: Declaration of Auth_SMF::modifyUITemplate() should be compatible with AuthPlugin::modifyUITemplate(&$template, &$type)
Strict Standards: Declaration of Auth_SMF::allowPropChange() should be compatible with AuthPlugin::allowPropChange($prop = '')
Strict Standards: Declaration of Auth_SMF::initUser() should be compatible with AuthPlugin::initUser(&$user, $autocreate = false)
Warning: Cannot modify header information - headers already sent by (output started at )

(removed file/lines, and multiple Warnings)

**Comment by patdelaney** [comment]
Wiki is back up
