### ISSUE TITLE
Enhancement request: add Brightness setting to Direct Connect Pixels output page

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#281]
Is it possible to add a brightness setting for direct connected pixels at run-time, list the Falcon controller can do.  I'l using a PiCap and I want to reduce the overall output to the ws2811 strings without recreating the fseq file.

Thanks

**Comment by cpinkham** [comment]
This will be part of the the new Virtual Strings code and completed as part of #302.  Closing this ticket and tracking feature under that Virtual Strings ticket.
