### ISSUE TITLE
Pressing Stop playing on the Master causes Master fppd process to stop and remote continues to Play

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#284]
I set up a test with 2 Pi 3's One master and one remote. The master is playing a mp3 audio only and the remote is playing the mp4 video version. If you press stop now on the master then fppd stops and the remote continues to run. IF you click start fppd nothing happens, you need to take it out of master, into standalone, then back to master again.
[Master_FPP_Logs_20171015.0244.zip](https://github.com/FalconChristmas/fpp/files/1385149/Master_FPP_Logs_20171015.0244.zip)
[Remote_FPP_Logs_20171015.0245.zip](https://github.com/FalconChristmas/fpp/files/1385150/Remote_FPP_Logs_20171015.0245.zip)

demo video of what happens: https://youtu.be/Ch600o4eXro

**Comment by ihbar** [comment]
Hello
I have seen a similar issue this week, without remote.  One PI 3 with 2 mp3 audio. Click on "stop now" sometimes stop the FPPD instea dof stopping playlist. "Stop gracefully" seems to be ok.
To restart FPPD, I need to click on the "restart FPPD" at the bottom of UI.
The issue may not be linked to master/remote.
Stephane

**Comment by cpinkham** [comment]
Also referenced at http://falconchristmas.com/forum/index.php/topic,8267.msg79657.html#msg79657

**Comment by cpinkham** [comment]
Would like to know if this is repeatable in the master code branch after the mutex locking additions that went into FPP v1.10 in late 2017.  The master branch also has rewritten playlist code which also may have fixed this issue.  For now, I'm going to move this ticket to the "optional for release" column unless we can determine that the problem still exists in master.  If it does, the ticket will move back to the "required for release" list.

**Comment by patdelaney** [comment]
I will try and test this today or Saturday

**Comment by cpinkham** [comment]
This does not appear to be an issue in current FPP, it was likely fixed long ago as part of the playlist rewrite.
