### ISSUE TITLE
fppdWatcher.sh not working

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#286]
while answering a question on the Falcon forum, I checked the status of fppdWatcher.sh on an older install. That FPP is a RasPi 2, running as my Master, loaded initially with v1.5 and upgraded to v1.8 then v1.9. The script functions as designed, restarting the FPPD 30 seconds after stopping.

I installed the script via the repository on a new RasPi 3 (remote) and it did not function. This was a v1.8 install upgraded to v1.9. I rebooted. Still not working. Changed to Standalone and Master, still not working.

Thru SSH, did a sudo bash fppdWatcher.sh and got a message that it was already running and gave the PID number.

**Comment by rudybrian** [comment]
Does _Processes_ in help->Troubleshooting Commands show that it is running? How are you starting  fppdWatcher.sh when FPP first starts up?

**Comment by rudybrian** [comment]
Also, can you run the following when logged in via SSH:

`ps -eadf | grep fppd | grep -v fppdWatcher | grep -v grep | awk '{print $2}'`
and
`curl -m 2 http://localhost/fppjson.php?command=getFPPstatus 2> /dev/null | grep '"running"'`

These are the two checks used in fppdWatcher.sh to see if fppd is running or not.

**Comment by JonB256** [comment]
Yes, it shows in Processes.

root      3082     1  0 19:06 ?        00:00:00 /bin/bash
/home/fpp/media/scripts/fppdWatcher.sh
root      4631  3082  0 19:37 ?        00:00:00  \_ sleep 30

As far as how I start it? It just starts after I ran the install script. I "assumed" that any scripts in the scripts folder were processed on boot.

**Comment by JonB256** [comment]
The Pi that wouldn't restart the other day (even after a reboot) is restarting FPPD now. Just took longer than 30 seconds. I am not logging FPPD starts or stops so I don't know exactly how long (yet).

**Comment by JonB256** [comment]
I'm not sure what delayed the functioning of the fppdWatcher.sh script, but it is working.
I'm closing this.
