### ISSUE TITLE
Need additional day of week settings for scheduler

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#290]
There's several combination settings in there, but two that I use most commonly aren't in the list.  Sunday thru Thursday, and Monday thru Thursday.  

-

**Comment by nathan815** [comment]
I see Sunday-Thursday on the list.

**Comment by cpinkham** [comment]
Closing this ticket, it was fixed in v1.10 by the new "Day Mask" type allowing selecting any combination of days of the week.
