### ISSUE TITLE
Scheduler: Add support for repeating every x minutes during start/stop times

### ISSUE THREAD

**Issue by marx1** [FalconChristmas/fpp#293]
Please add support for scheduled items to run every X minutes during the Start & end times.

The current repeat function only repeating the playlist during the time frame - creating a non-stop show. 

If you don't have a non-stop show you have ie you have a show that runs say every 30 minutes, you make multiple schedule items for each show. 

Then if you have more than one show order (to mix things up) That's a second/third/fourth set of schedules. This also prevents playing effects automatically between shows without the same work. 

I suggest changing the Repeat checkbox to a dropdown of 15 minute intervals, and accompanying code.

**Comment by cpinkham** [comment]
This can now be accomplished in the latest FPP using a few schedule entries and the new 'Hard Stop' stop method.  You could also have fairly accurate timing using the branch playlist entries to only execute the main portion of the playlist during certain times.  Given that there are already a few ways to accomplish this, I doubt we'll add the ability and complexity to run a playlist every 'X' minutes with a hard stop at the end of 'X' minutes so it can be restarted at X:01 on the dot.
