### ISSUE TITLE
GUI errors with version 1.10-25-gc53ece6

### ISSUE THREAD

**Issue by ezellner** [FalconChristmas/fpp#295]
On the Playlist and Schedule page of the GUI, some of the fields overflow into the background. This just began with the latest automatic download 1.10-25-gc53ece6. I did not see it on any other pages but these two. Attached is a snip of the Schedule page. The Playlist is similar but a bit harder to see in some areas.
![fpp gui bug](https://user-images.githubusercontent.com/35223720/34670764-b5e730be-f445-11e7-9018-7a36a230648c.PNG)

**Comment by LightsOnHudson** [comment]
I had to clear my cache in my browser and then it was fine.

**Comment by ezellner** [comment]
That fixed it. Thanks!
