### ISSUE TITLE
Web UI Tool Tips

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#3]
Tool tips in the Web UI should be added.

For example, when hovering over "Stop Gracefully" it should let the user know that means it will stop after the completion of the playlist.  One could think it ends after the current song.

**Comment by cpinkham** [comment]
Closing ticket as this is an ongoing, gradual process that while not never-ending, it will be a long time before we could ever say it was 'done'.  Some tooltips have been added already for most settings and others are being worked on as portions of the UI are updated.
