### ISSUE TITLE
Media Output - Switch to SDL output as default audio media player

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#310]

**Comment by cpinkham** [comment]
SDLOutput is now being compiled in by default on all platforms to make testing easier.  To Enable SDLOutput, create a setting called "ForceSDL" with a value of "1" in the settings file.  See 52121f1 for more info.

**Comment by dkulp** [comment]
This was done in cfe97eba127a3b094d5daf5b20b4f746550b0f9e
