### ISSUE TITLE
E1.31 - Fix unicast slowdown when controller is offline

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#311]

**Comment by dkulp** [comment]
This should now be "fixed".   If things slow down, the un-pingable e1.31/DDP/ArtNet outputs are removed from the list in runtime.   HOWEVER, they are never re-added thus a FPPD restart is necessary at this time.

**Comment by cpinkham** [comment]
Great. 

We can look at adding a monitor/watchdog thread to re-enable outputs that are marked down.  It also might be nice to expose the downed outputs list via the API so that the UI can show which outputs are currently disabled.  I think these can be added as other enhancement requests.
