### ISSUE TITLE
MQTT - Complete MQTT pub/sub support

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#318]
This will allow remote control as well as Home Automation integration.

**Comment by ghormann** [comment]
@cpinkham What is needed to Mark this as feature complete? Maybe I can help close the gaps, but I'm not seeing any gaps at the moment. 

* Publishing status seems to work
* Playlist Features seem reasonable
* Events are supported

**Comment by cpinkham** [comment]
I think it is probably good for now.  I want to add some more things over time, but don't have a roadmap.  I welcome any input on additional ways this integration could be helpful.
