### ISSUE TITLE
BBB Audio - Fix BBB .asoundrc issue

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#328]
Need to try to reproduce this on a Stretch image and investigate a fix.

**Comment by cpinkham** [comment]
Removing milestone for now.  We are going to see a sample of the bad .asoundrc file to figure out what this is.  I have checked over the code and can not see what could be causing this.

**Comment by dkulp** [comment]
I believe this is now fixed... if there isn't a sound card, it skips the also config entirely.
