### ISSUE TITLE
Fix any Pi Stretch regressions

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#333]
Known issues:
- ogg123 status parsing needs to be updated.
- Add Pi logo for 3 B+ model.
- Need to fix apache to use /home/fpp/fpp if it exists (for development use)

Possible issues:
- need to test serial outputs, one report of projector control plugin not working??
- report of possible mp4 playback speed issues using our patched omxplayer
- Edimax WiFi dongle not working with DHCP on some systems, possibly a race at startup:
    http://falconchristmas.com/forum/index.php/topic,8795.msg82615.html#msg82615

Fixed issues:
- switching omxplayer to ALSA has broken HDMI audio output.  may need to change 'force analog' deprecated setting into 'force HDMI' - new setting for forcing omxplayer audio output to HDMI, ALSA, local, both, disabled
- Settings page always shows SD card selected even when set otherwise.
- switch to using /sys/firmware/devicetree/base/model on the Pi in config.php instead of using the revision number from /proc/cpuinfo.
- omxplayer position status not being reported
- Switched to new mpg123 status parsing code for newer mpg123 version.
- Updated Pi RGB Matrix library to support Stretch
- Need to switch from using network-manager to connman (fixed static IP config issue)
- /etc/fpp_nginx.conf is not updated to use /home/fpp/fpp/www when /home/fpp/fpp exists (fixed in git)
- /etc/default/shellinabox needs "-t" added to args (fixed in 20180314 image and git repo)
- resolv.conf not getting updated properly (fixed by switching to connman)
- nginx gateway error after configuring static IP (fixed by adjusting php & nginx timeouts)

**Comment by dkulp** [comment]
Another known issue:  /etc/default/shellinabox needs to have "-t" added to the args or it doesn't work.  (discovered on BBB a while ago)

**Comment by patdelaney** [comment]
did some testing of omxplayer via SSH window:
Plays video but boot text is still on screen / audio is coming out mini jack not hdmi
/usr/bin/omxplayer -I -s "/home/fpp/media/videos/test.mp4" 2>&1

Heed to figure out ho to force audio out HDMI

**Comment by cpinkham** [comment]
Closing this as v2.0 has been out for a while.  Will address any issues separately as some are already in other tickets.
