### ISSUE TITLE
Merge new BBB related changes in master-v1.x back to master branch

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#337]

**Comment by dkulp** [comment]
This will likely be an ongoing thing as I flush out a few things for the newer BBB related hardware.

**Comment by cpinkham** [comment]
That's fine, we can leave the ticket open for master-v1.x -> master, I just want to make sure we don't miss merging the enhancements back and also so users can look at the project in github and see what is left to do before v2.0.

**Comment by cpinkham** [comment]
Canceling this ticket as there will be no v1.11 release so we can focus on v2.0.
