### ISSUE TITLE
prioritized play lists, and multiple sequences running at once

### ISSUE THREAD

**Issue by SteveGase** [FalconChristmas/fpp#34]
From: Steve Gase
It would be nice to have "prioritized" play lists (PL).  The idea would be to have overlapping schedules, and when the higher priority PL is started, the lower priority PL is stopped or interrupted... only for the lower priority PL to resume when the higher priority PL is complete.

From: CaptainMurdoch
Not a lot of time left this  year for bigger features like this.  I have had a similar idea in my head already though, to allow multiple sequences to be playing at the same time. Essentially it's the same as my effects sequence code which allow multiple effects to be playing at the same time, but thinking a bit larger. :)

**Comment by cpinkham** [comment]
Some of the framework is done for this already.  We don't prioritize playlists, but higher items in the schedule do take priority.  We likely won't see multiple playlists/sequences running at the same time in 2020, so closing this ticket for now.  It is still on the todo/ideas list.
