### ISSUE TITLE
Pi Stretch SD Image - see what can be done to shrink size of download image.

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#341]
Pi download zip is hitting close 900MB or higher if we don't zero out free space before creating the image.  See what can be done to shrink this so we don't have 2.5GB of files on the base install. This is supposed to be Stretch Lite, but doesn't seem very Lite.

**Comment by dkulp** [comment]
On the BBB, I'm at:
/dev/mmcblk0p1   3357264 2088188   1078820  66% /
so just over 2GB.   One thought:  I currently have both python 2.7 and 3.5 installed.  Not sure if we need both.

**Comment by cpinkham** [comment]
Closing for now, we have tossed some ideas around, but don't currently have a plan.
