### ISSUE TITLE
Update backups and logs zip scripts to pickup new JSON config files

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#342]
The backups and logs zip code needs to be adjusted to pickup all files in the /home/fpp/media/config directory.  Backups may require additional changes, not just a file glob.

http://falconchristmas.com/forum/index.php/topic,8790.msg81903.html#msg81903

**Comment by jaredb7** [comment]
I'm looking into the backup script at the moment, I'll get it working right (has few issues with restoration) then try to smarten it up capture all the files in the config directory.

I can look into the logs zip too and keep this all one package of work.
