### ISSUE TITLE
Blank screen on startup doesn't blank screen

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#345]
Blank screen does not work on Version: v1.x-master-124-g183a815f (master-v1.x branch) .

**Comment by patdelaney** [comment]
I looked at the startup script in /opt/fpp/scripts/startup and added a echo comment just before the setterm command and it doesn't appear to even run that script. I'm not sure how 2.0 is using the boot script

**Comment by dkulp** [comment]
This is now fixes for v2.0
