### ISSUE TITLE
Makefile:312: recipe for target 'fppd' failed

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#350]
I tried to update my stretch version of FPP and got the following error:
channeloutput/RGBMatrix.o: In function `RGBMatrixOutput::Init(Json::Value)':
RGBMatrix.cpp:(.text+0x910): undefined reference to `rgb_matrix::GPIO::Init(int)'
collect2: error: ld returned 1 exit status
Makefile:312: recipe for target 'fppd' failed
make: *** [fppd] Error 1
strip: '/opt/fpp/src/fppd': No such file
md5sum: /opt/fpp/src/fppd: No such file or directory
==========================================================================
Restarting fppd...
==========================================================================
Update Complete

This may be due to the change from apache/php to nginx/php-fpm.  Can you open a bug report about that and we can investigate before 1.11 which will use this new SD image.

**Comment by cpinkham** [comment]
This should be fixed in the latest Pi Stretch 20180221 SD image.  I was able to successfully switch back and forth between master and master-v1.x via the developer.php page multiple times.
