### ISSUE TITLE
FPP Multisync page

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#356]
Go to multisync page, click on a link to go to another FPP, do some work on the other fpp screen and then use browser arrorw to go back to the original FPP instance. The web UI is locked up.

Even if you try to open a new browser. The Webui is "stuck"  I have to restart nginx service

**Comment by jaredb7** [comment]
I don't believe this happens 100% of the time so bit hard to pinpoint what's causing it, I  did run into this a few times during last season though so it is a issue.

Was able to reproduce it tonight while testing something on the multisync page, after digging around I believe it's either to do with the PHP session being deleted while or just before PHP goes to read and lock it. Then anything that requires access to the php session just hangs, or when 2 scripts try to lock he same file.

I found 3 apache processes waiting on the same session file. killing one seemed to sort things out. Just

**Comment by jaredb7** [comment]
Have developed a fix for this issue, the locking up of the Web ui becomes worse when you have many FPP devices and the multisync page tries to poll them all and worse again with auto refresh. I could get it fall over after 2 devices or hitting hitting the refresh button on the page.

**Comment by patdelaney** [comment]
I sm currently running Version:  <http://fpp6/about.php> v2.x-master-501-g481933ff (master branch)

And I have 7 FPPs in the list
