### ISSUE TITLE
FPP in remote mode starts even though its not configured on the master.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#357]
I had a multisysnc video test running with 4 pi's. The master was configured for 3 remotes (unicast).

I was playing with a 5th pi and set it to remote while the other test was running, and the video began to play on it. Remember that was not defined on the master as being a member. No check box.

**Comment by cpinkham** [comment]
This should be fixed in current FPP v3.x and master.  The functions that process MultiSync packets are not called unless FPP is in Remote mode.  I think this may have been broken for a while when the MultiSync code was converted to from C to the MultiSync C++ class.
