### ISSUE TITLE
Look at Pi-attached LED Panels pulsing when user is watching the status page

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#362]
Reports of a pulse once per second when watching the status page when playing a sequence or in test mode.

http://falconchristmas.com/forum/index.php/topic,8795.msg83211.html#msg83211

**Comment by cpinkham** [comment]
This is reproducible and related to the getFPPstatus call which hits fppd.  I need to step through the things that this function does and see what is causing the pulse.  This can also be seen on Remotes, not just on a system running as master or standalone player.

**Comment by dkulp** [comment]
I think I may have figured this out.  With the SDL audio, I'm getting periodic audio glitches on the single core Pi's, but not on the single core BeagleBones.  If I turn off the setting of the super high priority on the main thread (-DNOROOT) my audio issues go away.  I turned that off on the BeagleBones a long time ago (don't remember why) which may explain why I don't have my audio issue on the BeagleBones.     Anyway, with the main thread set at super high "real time" priority, it would take precedent over anything else.   I don't think it needs that as all the real "work" is on the background thread.  The getFPPStatus calls and processing the GUI requests and such really don't need real time scheduling.   I'm going to remove the priority setting in fppd.c.

**Comment by cpinkham** [comment]
Closing ticket.
