### ISSUE TITLE
Can not see F16v3 behind FPP

### ISSUE THREAD

**Issue by Trioxide1** [FalconChristmas/fpp#368]
Have an issue accessing my Falcon F16v3 via IP address when using FPP ver 2.x. Have the FPP configured so I can WIFI into it via my home network and then have my F16v3 connected to the ethernet port of the pi via a separate network. Have Enable Routing between network interfaces selected in the Network config. When using FPP v1.9 I could connect to the F16v3 via webpage. Changed FPP to 2.x and now I can't connect to it. Went back to 1.9 and fine. F16v3 is working fine and my pixels are lighting I just can't see the webpage for it and change settings, etc. What changed in 2.x that this doesn't work?

**Comment by rudybrian** [comment]
If the IP address of either network interface changed, it would indeed effect the routes through FPP to the F16V3. 

If you can confirm that the IP addresses haven't changed, a few good tests would be to first ping, then  `traceroute` (`tracert` on Windows) from a computer on the WiFi network to the IP address of FPP's Ethernet port. If for some reason the routing between interfaces stopped working, this would show this fairly conclusively.

**Comment by Trioxide1** [comment]
So IP address and network interface not changed.  Same pi with same settings, just changed SD card for FPP ver 1.9 and 2.x.  Home network is 192.168.1.xxx.  This is how I use wifi to connect the pi to it.  The eth0 on the pi is the show network at 192.168.70.xxx.   Did tracert to show how on v1.9 that tracert works to 192.168.70.10 where my F16v3 is but v2.x it does not.  Again the only thing that changes is the FPP version.  Have included pictures to show this.

![screencapture000058](https://user-images.githubusercontent.com/39142406/39961727-75cc9682-55f1-11e8-9612-49f18a56d1a2.jpg)
![screencapture000059](https://user-images.githubusercontent.com/39142406/39961728-75e26638-55f1-11e8-825f-e3be86ed43d9.jpg)
![screencapture000060](https://user-images.githubusercontent.com/39142406/39961729-75f9f47e-55f1-11e8-8a2b-342021098763.jpg)
![screencapture000061](https://user-images.githubusercontent.com/39142406/39961730-761f5804-55f1-11e8-9c77-373310a0a17a.jpg)

**Comment by Trioxide1** [comment]
David,
   I can not post on FalconChristmas.com website as I can not get an account.  Have tried 2 times and was denied both times, not sure why though.

**Comment by Trioxide1** [comment]
I used ThreeSizes' suggestion to put the route in the computer to be able to controller behind the master pi.
http://falconchristmas.com/forum/index.php/topic,4231.msg44170.html#msg44170

Here is the routes you requested.

![screencapture000062](https://user-images.githubusercontent.com/39142406/39962040-c9314816-55f8-11e8-9147-b434e666088b.jpg)

**Comment by rudybrian** [comment]
Thanks for that. Yes, using a host route is fine. 

Can you confirm that the default gateway on your F16v3 is set to 192.168.70.1?

**Comment by rudybrian** [comment]
Can you log in to FPP via SSH and run `cat /proc/sys/net/ipv4/ip_forward` and let me know what it returns?

**Comment by Trioxide1** [comment]
What is the login and password for it?

**Comment by rudybrian** [comment]
username: fpp
password: falcon

**Comment by Trioxide1** [comment]
0

**Comment by rudybrian** [comment]
Aha! We finally have something.

This means that the kernel routing between interfaces isn't enabled. Can you try disabling, and re-enabling in the GUI? You might need to reboot after doing so to get it to take effect.

**Comment by Trioxide1** [comment]
That did it.  So even though it was showing as enabled it wasn't.  That is why you asked me to disable and re-enable.  Thanks.

**Comment by rudybrian** [comment]
Glad to hear that worked. 

@cpinkham This is probably something that needs to be looked at for upgrading the configs from 1.x to 2.0.

**Comment by mseverin** [comment]
Bumping this one.  I also had this same issue, but the gui was never able to change it.

**Comment by nmiller0113** [comment]
> Bumping this one. I also had this same issue, but the gui was never able to change it.

I'd be surprised if this wasn't fixed already even though this case still says open.  Did you read through the thread and follow the routing steps to insure your computer knows how to get to the network behind the FPP as well as the correct default route on the F16v3?  I know these may sound like dumb questions but there is a lot more than the issue mentioned here that can cause the problem stated.  Just making sure :)

**Comment by nmiller0113** [comment]
> Yeah I just spent 4 hrs on it. I went back to the 1.X from scratch and got it working in 25 min including waiting on NOOBs.

Then if the GUI didn't fix your problem I'd open a new bug report on it as this bug report turned out to be a GUI issue.

**Comment by mseverin** [comment]
> > Yeah I just spent 4 hrs on it. I went back to the 1.X from scratch and got it working in 25 min including waiting on NOOBs.
> 
> Then if the GUI didn't fix your problem I'd open a new bug report on it as this bug report turned out to be a GUI issue.

will do, I will recreate it tomorrow so I can give good screen shots, for a bug report i would want to have way more detail for them

**Comment by cpinkham** [comment]
Closing this ticket.
