### ISSUE TITLE
Cannot save 'other' output channel due to javascript error

### ISSUE THREAD

**Issue by sjernigan** [FalconChristmas/fpp#372]
FPP v1.10-27-g259bc38 with a PiCap.  
I had a previous setup from a prior FPP version.  When I try to change the number of pixels in the 'other channels', the following javascript error occurs when I hit save.  The output line disappears as shown.  A full page refresh shows the original configuration.

channeloutputs.php:1251 Uncaught TypeError: Cannot read property 'Outputs' of null
    at PopulateChannelOutputTable (channeloutputs.php:1251)
    at Object.<anonymous> (channeloutputs.php:1512)
    at fire (jquery-1.9.1.js:1037)
    at Object.fireWith [as resolveWith] (jquery-1.9.1.js:1148)
    at done (jquery-1.9.1.js:8074)
    at XMLHttpRequest.callback (jquery-1.9.1.js:8598)

![image](https://user-images.githubusercontent.com/419815/40891742-44aa1c2c-6759-11e8-9b56-b576d44a07c9.png)

**Comment by sjernigan** [comment]
Manually editing the chaneloutput file is a viable workaround.

**Comment by dkulp** [comment]
Won't fix.... No work is being done on 1.x anymore.   If this is still occurring on 2.x, please let us know.
