### ISSUE TITLE
Cannot use "Event" in a playlist in V2.x

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#376]
I setup a playlist, in the "lead in" area I added my event which I can trigger manually in the events area but when I add it to a playlist it stops FPPD immediately when I hit play. Once I take the event out of the playlist, the playlist plays fine 

I am on v2.x-master-612-g78e44ade (master branch)

**Comment by rudybrian** [comment]
A couple questions: 

- Does it do the same thing if you put the event in the main playlist body?
- Can you enable Playlist, Event and Effect logging and provide a log excerpt from fppd.log from just before and after when the stop occurs?

**Comment by bchiaino** [comment]
Yes, in the body it also stops the player. 

I will try tonight after work with logging enabled and post my results

**Comment by bchiaino** [comment]
heres a quick video I shot showing whats going on and the log files with the above mentioned checked off to log

https://drive.google.com/file/d/1uUQauwF7LrpPjbHqwK0mDtyrr9y4zWNS/view?usp=sharing

https://youtu.be/OBFMCnMBvQE

**Comment by rudybrian** [comment]
Can you also provide a copy of the playlist (in media/playlists) and the event (in media/events)?

**Comment by bchiaino** [comment]
they are both in the zip file

[media.zip](https://github.com/FalconChristmas/fpp/files/2168208/media.zip)

**Comment by rudybrian** [comment]
@cpinkham is tracking this in #335

**Comment by jaredb7** [comment]
This should be fixed in #415 , there was small issue with how the event IDs were being saved in the playlist. 

If running the BETA and want to test it now, you'll have to switch to the 'master' branch from the /developer.php page

**Comment by bchiaino** [comment]
Right now I’m running the official 2.0 release and using an event in a playlist still stops fppd

**Comment by jaredb7** [comment]
Ah, yeah the bug still exists in the official release. Same still applies if you want to test, If you go to http://fpp/developer.php you can change Git branches from the 'v2.0' release to the main development branch 'master'. 
Or if you can wait it out a bit, the fixes will get merged into the v2.0 branch soon.

If switching between branches and find your FPPD doesn't start, go to Help -> About  & do a manual update - this will recompile FPPD and fix things.
![image](https://user-images.githubusercontent.com/799998/45616281-4d61cc00-bab2-11e8-9fd3-d40a14831e2c.png)

**Comment by bchiaino** [comment]
awesome thank you, ill give it a shot tonight and report back

**Comment by bchiaino** [comment]
seems to be good in the quick test I did doing a 23/24 in a lead in to start an effect and 24/24 to turn off

question though being im new to events, do I need to worry about my sequences interfering in these events? how do I know if channels in my XLights sequences/FSEQ files will mess with events? is it only of I add DMX effects in lights like moving heads and such?

**Comment by cpinkham** [comment]
Closing as fixed.  If there are any related questions, they should be addressed in the forum.
