### ISSUE TITLE
V2.x - After reboot, Schedule starts and theres a lot of lag

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#378]
Hi guys, not sure if this is a bug or just because the Pi is running processes after the boot up but I noticed yesterday and tested a few times with the same result that if I have a schedule running sequences and I have to reboot the Pi, I hit reboot, it restarts fine and the schedule starts up again immediately but everything is way off on the first 2-3 minute sequence, the lights are a few seconds behind what they should be and my remotes to my matrixes are all over the place, one played the entire 3 minute sequence on my remote in 30 seconds and then it restarted that screen at the right location. the show runs off a Pi3B+ and my 2 remotes are Pi 3's all running the July 9th 2018 release (sorry not at home to get the exact build number

Just wanted to report it in case anyone has to reboot during a show if things are not running right

**Comment by bchiaino** [comment]
ok, finally got a around to some testing and this seems to be an issue once my main master Pi is connected to Wifi, when its off the wifi it all works fine


when on wifi (even though the remotes are not on wifi, they are all plugged into a router on a separate network) when I reboot everything is way off and the screen feezes and blows through the entire sequence in less then a minute as you can see in the video below also the multi sync info it WAY off by minutes again as you can see in my walkthrough video. I deleted ALL my video files from the video folder which is awesome, saved some room and tried to set multi sync to all remotes and individual and it didn't help at all,


here is the link to the video - https://youtu.be/iZmruC2oYJs

**Comment by cpinkham** [comment]
Closing as this version is years old.
