### ISSUE TITLE
V2 Batch file for network creation

### ISSUE THREAD

**Issue by mararunr** [FalconChristmas/fpp#382]
Captain, this ticket is in reference to our discussion at Christmas Expo concerning v2.0 and network setup.

Have a windows batch file process to collect necessary network information for first start up.

In the hotel, while setting up Pi Zero's, the network address that got assigned by the automated networking process was not an IP I could access.  I had to go back and use Paul's v1.9 image because it already had interface.wlan0 and dns that I could modify to connect.

**Comment by darylc** [comment]
@mararunr Is this still required?

**Comment by mararunr** [comment]
@darylc No, this is very old.  Closing now.

**Comment by mararunr** [comment]
No, I have closed.

    On Saturday, June 19, 2021, 11:52:25 PM CDT, darylc ***@***.***> wrote:  
 
 


@mararunr Is this still required?
