### ISSUE TITLE
V2 Status screen does not reset when MP4 gets to the end.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#383]
When testing an MP4 only event in the playlist (no fseq) on a Pi B. When the PM4 gets to the end the countdown counter never resets. See pic

![image](https://user-images.githubusercontent.com/8147459/43108465-9679d126-8ea7-11e8-8405-fcfd3c90b788.png)

**Comment by patdelaney** [comment]
I did not see the issue with a Pi V2 with MP4 and a fseq in the playlist.  It seemed to have worked.
![image](https://user-images.githubusercontent.com/8147459/43108518-dc9aba94-8ea7-11e8-8f34-d0b91fbca786.png)

**Comment by dkulp** [comment]
Fixed
