### ISSUE TITLE
V2 Playlist Can't play multiple mp4 clips in a play list

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#384]
mp4 videos in a playlist never end. FPP doesn't come out of playing mode. Therefor the next event in a playlist never triggers.. I can put multiple mp3 audio files in the list and it plays those fine. It seems that how ever you detect the end of an MP4 file never happens.

**Comment by dkulp** [comment]
Fixed

**Comment by patdelaney** [comment]
If you have a play list with MP3 and MP4, mp3 never finishes to go to MP4.
MP3 to MP3 works.  Audio is glitchy on Pi B with onboard audio or USB
audion.. I need to test on faster Pis

**Comment by dkulp** [comment]
I have a playlist that alternates between mp4 and mp3 and it runs through the entire thing fine.

**Comment by patdelaney** [comment]
I am testing over lunch from the office So I am teamviewered in, but Now I
have a playlist with 2 mp3's and an MP4.  The MP3's are playing when it
finishes the last MP3 the timing bar advances down to the MP4, but the
countdown clocks are not working, but the status says Playing. Unfortunate
I am remote so I can't hear if it is actually playing..

**Comment by patdelaney** [comment]
It's not working on a Pi B but on a Pi V2 playlist with mixed media seems
to work
