### ISSUE TITLE
V2.x FPP does not appear to recognize when PiFace I/O cards are attached.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#387]
In 1.x software FPP was able to tell

 if a PiFace card was attached and then it adjusted GPIO setup screen to add the GPIs that the card supported. v2.x does not appear to. I have tested with PiFace and PiFace digital.

![gpio1_8](https://user-images.githubusercontent.com/8147459/43492943-013c7d02-94f1-11e8-8888-958f552a9a79.jpg)

![gpio2 x](https://user-images.githubusercontent.com/8147459/43492953-165dd8d4-94f1-11e8-9768-d6b883d04a4c.jpg)

**Comment by patdelaney** [comment]
Version 1.10 boot up
![image](https://user-images.githubusercontent.com/8147459/45597511-2496e500-b993-11e8-910f-7461cdb773cb.png)

Version 2.x boot up (looks like it skips the step)
![image](https://user-images.githubusercontent.com/8147459/45597523-4e500c00-b993-11e8-818c-d5bca4c506a4.png)


If you need access to the Pi with a PiFace attached let me know and I can set up up to ssh in.

**Comment by patdelaney** [comment]
I accidentally closed this the other day. It is Still and issue and I think needs to be addressed soon.

**Comment by dkulp** [comment]
That stuff won't be on the console with Stretch.   If you run "sudo journalctl -u fppinit" you should see:
"FPP - Checking for PiFace".   That said, it looks like the PiFace and wiringPi "gpio" utility no longer work well together: https://www.element14.com/community/thread/64502/l/piface-digital2-no-longer-works-with-wiringpi-246-under-current-raspbian-2018-06-27?displayFullThread=true

Can you send me the output of "ls -lR /sys/class/gpio/" on a system with the PiFace installed?

**Comment by patdelaney** [comment]
Here you go:


fpp@FPP6:~ $ sudo ls -lR /sys/class/gpio/
/sys/class/gpio/:
total 0
-rwxrwx--- 1 root gpio 4096 Sep 19 08:28 export
lrwxrwxrwx 1 root gpio    0 Sep 19 08:28 gpiochip0 ->
../../devices/platform/soc/20200000.gpio/gpio/gpiochip0
-rwxrwx--- 1 root gpio 4096 Sep 19 08:28 unexport
fpp@FPP6:~ $

**Comment by dkulp** [comment]
Darn.  Thats not helpful.  :(     Not sure we can detect it from the command line anymore.  May need to just add a "PiFace Enabled" checkbox someplace.

**Comment by dkulp** [comment]
Should now be fixed in 9bc39906927e0f2123b4b054a345b1666d91d65b
