### ISSUE TITLE
v2.x Need the ability to choose HDMI audio when playing audio files

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#389]
We need to allow audio output to HDMI for MP4s. 

Reason: For my Halloween Zombie containment system, I have a FPP playing the HDMI to a monitor on the Zombie box. But that same Pi has a Picap. Last year I pulled the audio for the speakers from the mini jack on the back of the HDMI monitor that was in the Zombie box. I could probably use a USB audio dongle, but that just adds to the complexity.

**Comment by dkulp** [comment]
This was just implemented yesterday. There is a new setting on the settings page specifically for configuring where omxplayer will send the audio.

**Comment by patdelaney** [comment]
I just verified the fix. I didn't realize it was put in last night, I also
verified that I could get USB audio in a pinch.

Thanks
