### ISSUE TITLE
Playlist editing - moving entries up and down is very touchy

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#39]
I have a playlist going right now with 8 entries.

a 90 second sequence with music
a 5 sec. pause
a 20 sec Tune To graphic
a 5 sec pause
A 120 second sequence with music
a 5 sec pause
a 20 sec Tune To graphic
a 5 sec pause

Getting them into that order was like play Whack-a-Mole. Drag one item and 3 would move. I could have saved time by deleting them all and recreating all 8 items.

I would love it to be more stable.
This was with the older 0.1.0 noob and with the new 0.2.0 noob (just loaded)

**Comment by JonB256** [comment]
This no longer seems to be "touchy."  Not sure when or how it got better, but I think this can be closed.(since I opened it!)

**Comment by cpinkham** [comment]
Closing this for now based on report and the fact that UI is planned to be rewritten for v2.0.
