### ISSUE TITLE
2.x - brightness adjustment for P10 panels not working

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#390]
I noticed in 2.x (currently on 497fc3a3) on a pi3 b that if I go into outputs, panels and change the brightness dropdown from 100 to 10 , save and restart FPPD that to doesn't actually make the change on the panel, the panel still runs at 100% brightness

Im using a color light board so not if its that taking over the setting.

**Comment by cpinkham** [comment]
FPP can not currently control the brightness on the ColorLight and Linsn cards, we need to hide this setting in the UI when configuring these Channel Outputs.  Created #391 to get this fixed.
