### ISSUE TITLE
V2.x Channel Outputs  Ui doesn't read "subType" from channeloutputs.json file when Hat/Cap/Cape is selected and saved.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#393]
When configuring a Pi for a pihat (Hub15)  when  you click save it does write out the new configuration to the channeloutputs.json file, but when you refresh the screen (F5) the UI do longer displays Hat/Cap/Cape.

The good news is  if you make any other changes to that page and click save, it does not wipe it from the json file. It appears to just be a display issue in the UI and should be fixed.

Better news, it's only for Hat/Cap/Cape. Linsn and Colorlight work fine.

**Comment by jaredb7** [comment]
Bit of a weird one, just resaving the php file without changing fixes the issue. Must of been something weird the line endings.

Submitted a fix for it anyway. Still don't get how the other 2 options shows up though, oh well :D.
