### ISSUE TITLE
v2.x FPPD high CPU utilization when Hub75 Pi cap is enabled.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#394]
I noticed today that fppd CPU utilization was very high on my Pi v2. It was at 75%.  When I disabled the LED panel outputs, the CPU dropped to .3%

I mentioned this to Brian Rudy and he mention that it might be the gamma correction code. 

A few questions:  
Are we still locking fppd to a single core or can it take advantage of multiple cores?
Should we add a toggle for Enable Gamma Correction if it really is going to be a resource hog?

Pat

**Comment by jaredb7** [comment]
I think this might just be the nature of having Hub75 on the Pi? With the BBB's they have PRU's which can churn away generating the data for the panel, where as on the Pi it's all software and the CPU is being used to calculate pixel data.

I'm no expert but fairly sure that's it.

**Comment by cpinkham** [comment]
I believe this utilization is the norm for this channel output now and goes higher the more panels are attached.  Closing old ticket.
