### ISSUE TITLE
v2.0 Onboard/USB audio sounds bad on on a Pi B  - it seems like something is stealing cycles and there is dropouts

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#398]
There is a noticeable difference in Audio quality between 1.10 and 2.x on a Raspberry Pi B. I know it's old. but I use it for a Halloween prop that plays a spooky sound track. when you play the track on the Pi B running 1.10 the on board audio and audio with a USB dongle sounds good. If you play the same file on the same Pi B via on board or USB audio the sound quality is bad. It sounds like random hiccups or dropouts in the audio track. Sort of like something is stealing CPU cycles. It's VERY noticeable.

**Comment by patdelaney** [comment]
From my testing it only appears on Pi B and Pi B+

**Comment by patdelaney** [comment]
Updated testing scenarios:
Pi B	        hiccup audio 5 sec apart
Pi B+	hiccup audio 3 sec apart
Pi V2	No problem
Pi V3	No problem
Pi V3+	No problem

**Comment by dkulp** [comment]
Can you run "cpufreq-info" and see if the high speed is close to "100%".   I have one Pi where the governor is being replaced by ondemand at boot, but another where it's sticking on performance.   On the same image.  Not sure what's going on yet, but if it's allowing the CPU on the older Pi's to drop to 600, that could definitely be part of the problem.

**Comment by dkulp** [comment]
Pulled out my Pi B and can duplicate this.   I THINK I see what is going on.   Hopefully will have a fix tomorrow.

**Comment by patdelaney** [comment]
Awesome

**Comment by dkulp** [comment]
Can you go to the developer.php page and flip back to master and retest?

**Comment by patdelaney** [comment]
I'm still getting the hicup on a B+ about every 6 seconds. Here is the output of lscpu, the other command doesn't run:
fpp@FPP1:~ $ lscpu
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model:                 7
Model name:            ARMv6-compatible processor rev 7 (v6l)
CPU max MHz:           700.0000
CPU min MHz:           700.0000
BogoMIPS:              697.95
Flags:                 half thumb fastmult vfp edsp java tls
fpp@FPP1:~ $

**Comment by dkulp** [comment]
Can you double check you are on v2.x-master-669-g594c0141 

If it's still an issue, can you send me an mp3?  On my "Raspberry Pi Model B Rev 2" the few MP3's I've tried are working OK now.

**Comment by patdelaney** [comment]
I did update yesterday, but for some reason it didn't pickup that update. I
just remoted in from work and upgraded it and now it's at the correct
version. I can test the audio when I get home.


Thanks

**Comment by patdelaney** [comment]
here is the audio file
https://drive.google.com/open?id=18szYX7MuPeVXHoAej-VtP2gUZYmhyloJ

**Comment by patdelaney** [comment]
Version Info
FPP Version: v2.x-master-670-g87dc7297
FPP OS Build: v2.0alpha
OS Version: Raspbian GNU/Linux 9 (stretch)
Kernel Version: 4.14.24+
Git Branch: master
Local Git Version: 87dc729 ChangeLog
Remote Git Version: 87dc729

**Comment by dkulp** [comment]
Your mp3 was definitely more cpu taxing than the two I was using.   I increased the buffer a bit more to match what ffplay uses.   It seems to play perfectly now, but it MAY have some effect on sequence timing as we don't have as fine a resolution of exactly where in the buffers the sound is now playing.   Anyway, if you could test again, that would be great!

**Comment by patdelaney** [comment]
I upgraded to Version: v2.x-master-671-g7be6f234 (master branch)  on my B+
and I'm still getting the hicup.

:-(

Pat

**Comment by patdelaney** [comment]
it even hicups on my voiceover

**Comment by patdelaney** [comment]
Legacy audio settings seem to fix the issue.

Pat

**Comment by dkulp** [comment]
OK. Can you try without the Legacy audio again?  I think I figured out what is happening (and why I don't have the issue on the single core BBB's).
