### ISSUE TITLE
Ran the "ConvertPiRootToReadOnly.sh" on a v2.x-Master RasPi - bad things happened

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#399]
Script installed and Ran with no error messages.
Rebooted.
The Pi was running Wireless and was now not accessible. My BBB Master gave an "unreachable" error when I did a Multi-sync scan. 
Using IP Scanner, the correct IP address showed in the list but it did not have HTTP running anymore. 
I could still SSH into it but that didn't really help anything.

Did I miss a warning about running that Script on v2.x-Master or just the first to try it?

**Comment by cpinkham** [comment]
These scripts do not work with FPP v3.x, so the Script Repository was been updated in commit a981948eef to mark them as only compatible with FPP v1.7-v2.1 so they should not display on FPP v3.x systems.  Closing ticket.
