### ISSUE TITLE
Is support for Pixel chips other than WS2811 possible using a PiCap?

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#400]
Specifically, I have a desire to run some TLS3001 pixels from a small/cheap controller. I know that the TLS3001 is a 12bit chip but does that prevent its support?

If not the PiCap, could it be added as an "Other" output like the SPIWS2801 ?

**Comment by cpinkham** [comment]
I have been wanting the same thing, but haven't looked at coding yet.
 I have some TLS3001 as well.  I need to ping David to get the protocol
spec from him and can see what it would take to implement.

On Fri, 2018-08-17 at 14:59 +0000, JonB256 wrote:
> > > Specifically, I have a desire to run some TLS3001 pixels from a
small/cheap controller. I know that the TLS3001 is a 12bit chip but
does that prevent its support?
> > If not the PiCap, could it be added as an "Other" output like the
SPIWS2801 ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/em
ail/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"Is support for Pixel
chips other than WS2811 possible using a PiCap?
(#400)"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/400"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/400",
> > "url": "https://github.com/FalconChristmas/fpp/issues/400",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> > "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> > "title": "Is support for Pixel chips other than WS2811 possible using
a PiCap? (#400)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**JonB256**",
> > "activityImage": "https://assets-cdn.github.com/images/email/message_
cards/avatar.png",
> "activitySubtitle": "@JonB256",
> "facts": [
> {
> "name": "Repository: ",
> "value": "FalconChristmas/fpp"
> },
> {
> "name": "Issue #: ",
> "value": 400
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > > > "body": "{\n\"commandName\":
\"IssueComment\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 400,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 400\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> > "uri": "https://github.com/FalconChristmas/fpp/issues/400"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
369548131\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]

**Comment by JonB256** [comment]
The "Other" list is in Channel Outputs and the "Other" tab
In the dropdown list are many items including that SPIWS2801 output choice. 

The F1 Help shows how you could connect up that 4-wire pixels direct to GPIO pins:


WS2801 Function | Raspberry Pi
-- | --
Clock | Pin 23 - SCLK
Data | Pin 19 - MOSI
Ground | Pin 25 - GND
Pixel Power | Not Connected to Pi

**Comment by cpinkham** [comment]
I found a doc with the TLS3001 spec, so maybe a 2019 feature enhancement.  If I could find a C/C++ library that implemented the protocol already then that would make things easier.

**Comment by darylc** [comment]
@cpinkham Seems to be some here if you are still interested https://github.com/TimGremalm/TLS3001_LED_ESP32

**Comment by cpinkham** [comment]
This is one of the goals of the new DPIPixels code.  To begin with, I started with 3-channel RGB WS281x, now I am looking at adding 4-channel support, and then longer-term could look at adding other protocols on a case by case basis if it made sense.

**Comment by darylc** [comment]
The FPP development team met and decided it is not aiming to implement pixel types other than WS281X.  Of course if someone feels strongly they can send a pull request to implement other pixel types.
