### ISSUE TITLE
Playing an MP4 to a Pixel Overlay Model is not releasing the buffers when done

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#406]
Running v2.x-master-661  (after the update to 1M channels)  
also just tested under v2.0  - still does this

Noticed that when I play (from a playlist) an MP4 file to a defined Pixel Overlay Model, when finished, the last frame of the video remains on screen. This occurs even if the MP4 is played in a playlist and followed by a normally good FSEQ/mp3 file. 

Only ways I've found to clear it and regain function is an FPPD restart or I went into Matrix Tools, Enabled, Cleared, and Disabled. 

If this was occurring before the 661 update to more channels, I never noticed.

**Comment by JonB256** [comment]
For now, I created an "fppdRestart.sh" script that I put in the LeadOut of the playlist.
It simply stops and restarts FPPD, clearing whatever buffers or modes keep the screen tied up.

[fppdRestart.zip](https://github.com/FalconChristmas/fpp/files/2364735/fppdRestart.zip)

**Comment by dkulp** [comment]
I BELIEVE this is fixed on master now.   I discovered that "Media" playlists were never calling stop which is where the SDLOut was cleaning up the overlay model data.    If you could flip to master ( v2.x-master-671-g7be6f234 ) and test, that would be awesome.

**Comment by JonB256** [comment]
Yes, Version: v2.x-master-671-g7be6f234 (master branch)  is now correctly progressing from MP4 (playing direct to Pixel Overlay) to FSEQ.
That does seem to work. Thanks.
JonB
