### ISSUE TITLE
2.0 - Cant complet 12 hours without FPPD stopping and requiring reboot

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#407]
Since the last couple of versions FPPD is stopping a lot. I have been running my regular schedule fine for months but lately in the morning when I get up, FPPD says its stopped and I cannot restart it without rebooting the Pi3B+. I have the default log info checked yet nothing seems to be logging correctly. 2.0 is on my SD card and all my files and sequences are on a USB drive. 

heres a copy of my zipped logs - [size=78%]https://drive.google.com/file/d/1Yq8IjhPpI6hyvF9XnVgFeawNHh_8JkMx/view?usp=sharing[/size]

https://drive.google.com/file/d/1xLORGRohXYET1VRvmN1a92HaUC8Gl0zN/view?usp=sharing
https://drive.google.com/file/d/1Um45RNRW5l0xoDWQvmv2BvHzxMw9rycy/view?usp=sharing
<img width="1176" alt="fpp1" src="https://user-images.githubusercontent.com/40632971/45254588-b164f180-b348-11e8-99d7-c0e39e9bc27a.png">
<img width="952" alt="fpp3" src="https://user-images.githubusercontent.com/40632971/45254589-b164f180-b348-11e8-9a8e-81ab100dcfd8.png">

**Comment by bchiaino** [comment]
Absolutely. I’ll be home in a few hours and I’ll gather all the info and post

**Comment by bchiaino** [comment]
here is everything on my flash drive - https://drive.google.com/file/d/1ud_shTJg4-UCLGqtGSqK58ItdIcji4_D/view?usp=sharing
<img width="1148" alt="screen shot 2018-09-09 at 2 01 26 pm" src="https://user-images.githubusercontent.com/40632971/45267382-4e06bc80-b439-11e8-92f4-e6433fe3d072.png">

also I attached a pic of my schedule and I have a thread going here also so not sure which one to stick to- - http://falconchristmas.com/forum/index.php/topic,9355.0.html

**Comment by dkulp** [comment]
I've had all of this running on my Pi3B+ for almost 40 hours now without a single issue.

**Comment by bchiaino** [comment]
I formatted my USB drive and added media back on and its been solid so far too for about the same..

Nothing is being logged in the fppd file like it used to though, it is blank, did something change on that end?

Log files:

https://drive.google.com/file/d/1aTifPXZP6uhn8ZfdNzs-t71YJ0czvBt8/view?usp=sharing

<img width="1148" alt="screen shot 2018-09-10 at 9 19 43 am" src="https://user-images.githubusercontent.com/40632971/45301099-2f0e3600-b4de-11e8-8fc7-57ea2820b713.png">



sorry, I know there is a post on the forum too, not sure which one you guys want to stick to

**Comment by bchiaino** [comment]
after formatting my USB and recopying the media back on the shoe schedule seems to be back running smooth, ill close this for now. thanks again guys!
