### ISSUE TITLE
Powered-off wireless UDP node not recognized when power restored. (V2.0)

### ISSUE THREAD

**Issue by bwmcin** [FalconChristmas/fpp#408]
I have a wireless UDP pixel node, with FPP running on a RB pi 3Bv2, 16gig SD card, no usb memory.  For an edge condition test, the wireless UDP pixel node is in a powered off state when the FPP v2.0 is powered on.  Once FPP is up, I start a sequence and then power on the pixel node.  The pixels go through the initialization sequence and then nothing happens (vs. the node receiving the sequence data and updating the pixels).   The webserver on the pixel node is working and shows no data being received, so the issue probably lies outside the pixel node. 

In attempting to fix this, I reboot (push reboot button on the status page) and when the system comes back up I press play to run the sequence.  At this point the sequence hangs (Elapsed time remains at 00:01 or there about) .  I shutdown again and cycle the power of the RB pi (while leaving the power on for the UDP pixel node), start the sequence, and all works as expected.

FPP v1.10 does not exhibit this behavior--the wireless UDP pixel node will receive sequence data once it has been powered up and has joined the network.  Will revert back to 1.10 for now.

**Comment by dkulp** [comment]
When FPP starts up, it pings all configured controllers and disables anything that is not pingable.   Every 60 seconds, it will re-ping the disabled controllers to see if they come online and, if so, will re-enable them.    Are you sure you waited at least a minute after power up? (possibly longer depending on how long they take to reach a state where they can be pinged)

**Comment by bwmcin** [comment]
Started v2.0 with sequence running in repeat mode, UDP node is powered off.

After 2 minutes of running the sequence I applied power to the node.

Waited even longer than before (per your suggestion) and it worked!  (Thanks). 

I’m back on version 2.0

 

Bruce

**Comment by dkulp** [comment]
Thanks for the confirmation.    Just an FYI:  the reason this is done this way is that sending UDP data (even multicast) to controllers that are offline can cause many WIFI access points to buffer data which can result in skips/pauses in the entire show if the buffers fill.   With 1.x, we always sent data and many people had issues if a controller dropped out or there was some wifi interference or similar.  With 2.x, we try and detect if controllers drop and we'll disable the output.   Thus, you may get a minute or so of skips/pauses, but it should self correct and continue to send data to the controller it can reach.   When the controller comes back online, it will detect that as well and self correct.
