### ISSUE TITLE
Pi no locking CPU freq governor to performance

### ISSUE THREAD

**Issue by dkulp** [FalconChristmas/fpp#411]
This was working at one point in the betas, and it IS running at boot, but somewhere later in boot it's being reset back to ondemand.  Need to investigate.

**Comment by darylc** [comment]
Confirmed on master on Pi4 that it is still ondemand:
fpp@FPP:~ $ cat /sys/devices/system/cpu/cpufreq/policy0/stats/time_in_state
600000 312190
700000 120606090
800000 186168
900000 15723
1000000 0
1100000 0
1200000 368441

I was going to submit a pull request to fix it, but then realised I actually want the governor on my pi4's to be ondemand to help manage heat load.

@dkulp We can fix this by changing /opt/fpp/scripts/init_pre_network - the setting of the cpu governor to performance is inside a platform check for BBB.  The question is, do we want to, I suspect maybe we just want to do it for slow pi's?

**Comment by dkulp** [comment]
Yea... it's really just needed on the BBBs as the flipping between frequencies causes a delay on  one of the interconnects between the PRU's and the GPIO pins.    

That said, I DO wonder if locking it might have an impact on the vlc video playing.   With the Pi4 heat issues, closing this makes sense as we don't really want it.
