### ISSUE TITLE
V2.x   Setting FPP to Force Legacy audio outputs (mpg123/ogg123)  needs fppd restart

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#413]
When testing the audio issues with Pi B and Pi B+ when I toggle the Force Legacy audio outputs (mpg123/ogg123) setting and try to play audio there is now audio output, but the playlist UI says it's playing. If I stop the playlist and restart fppd then the audio is OK. Going the other direction by untoggling Force Legacy audio outputs (mpg123/ogg123)  seems to be OK..

I would suggest auto restarting fppd when togging Force Legacy audio outputs (mpg123/ogg123) mode.

**Comment by dkulp** [comment]
I believe this was caused by the same things causing #414.   I just ran a playlist where I'd change the setting after each song started (so each would alternate) and it worked fine without restarting anything.

**Comment by patdelaney** [comment]
I can confirm that on Pi B+ a mp3 clips play correctly on normal settings
and force legacy setting.
I can confirm toggling between the two output methods does not require a
reboot.
I can confirm that mp3 playlists work as designed.


Thanks

Pat

**Comment by dkulp** [comment]
Awesome!  Thanks for the confirmation!  One less issue to deal with.   :)
