### ISSUE TITLE
V2.x  When running mp3 in a playlist in Force Legacy audio outputs (mpg123/ogg123) mode UI does not refress when clip is over.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#414]
Playlist broken when in Force Legacy audio outputs (mpg123/ogg123).  After a clip plays the UI never ends and goes to the next Clip.   

This is with Media playlist, not tested with sequence events yet.

Pat
![image](https://user-images.githubusercontent.com/8147459/45491338-1cd70680-b72f-11e8-95a9-dde40186fe34.png)
![image](https://user-images.githubusercontent.com/8147459/45491377-324c3080-b72f-11e8-90f4-ff168048cfda.png)

**Comment by dkulp** [comment]
Fixed in bbc24916ed463568c5187d748b7a70626362e1ab
