### ISSUE TITLE
Missing wlan0 addresses on boot screen

### ISSUE THREAD

**Issue by jeffla** [FalconChristmas/fpp#421]
When looking at the HDMI output of the Pi with eth0 & wlan0 configured, I only see the eth0 address and not the wlan0. Also, a connected speaker only reads out the eth0 address and not the wlan0 address. Is this a Pi bug or is fpp showing that? Pi3B (non-plus). On a Pi3B+, no addresses are shown on the HDMI output, but both eth0 and wlan0 are spoken.

**Comment by cpinkham** [comment]
I think that what is happening here is that if you have eth0 and wlan0 configured, FPP only waits for the first IP and then continues on booting.  We may need to see how many interfaces are configured and try to wait for that many IPs before continuing or timing out.

**Comment by darylc** [comment]
@jeffla This has been implemented in more recent versions (I tested the v5 master on a pi
)
@ghormann Can you please close this issue?
