### ISSUE TITLE
Copy Playlist to new name

### ISSUE THREAD

**Issue by JMHaro** [FalconChristmas/fpp#422]
I would like to request that in FPP, it would be nice to be able to **copy** an existing Playlist to a new name.  Keeping the original playlist but making a copy of it with all the same entries.

I have playlists with over 60 entries.  I've created one for Before Christmas.  I want to create one for an After Christmas which I substitute just a couple sequences for ones leading up to the New Years.  It's really a pain to replicate all these entries again for this second sequence just to change a couple sequences.  It would be nice to be able to copy the entire playlist to a new name and then just be able to change the few sequences as needed.

**Comment by bchiaino** [comment]
a workaround is to just copy and paste the playlist right from the folder structure if you unc into it

**Comment by jaredb7** [comment]
I've added a button to the playlists page to copy the currently selected playlist. Will be useful for others in the future and going into the season. Not currently on master but hopefully by weeks end.

**Comment by bchiaino** [comment]
awesome, thank you!

**Comment by JMHaro** [comment]
Yes thank you.  I did learn in one of the last zoom nights, how to do it via Windows explorer once I got it setup correctly to do that, but this will even make it easier.  Thank you.
