### ISSUE TITLE
See closed #406 - playing MP4 file to an Overlay

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#425]
This was working (playing an MP4 file from a Playlist to a Pixel Overlay Model).

Now it does not. FPPD immediately goes to Stopped. Pauses. Then restarts. Nothing plays, though.

Tried on RasPi3B+ (was working)
Tried on BBG running fully updated V2.1 and Master.

**Comment by JonB256** [comment]
Still happening. Attached is a Log file from a RasPi3B+
I cleared all the logs, then started two different MP4 files that previously worked well.
[PixelOverlayFail_FPP_Logs_20181011.1200.zip](https://github.com/FalconChristmas/fpp/files/2468785/PixelOverlayFail_FPP_Logs_20181011.1200.zip)

**Comment by JonB256** [comment]
So, it does NOT work in v2.x-master, latest update
It does NOT work in v2.1-1
but, it does work in v2.0  (as long as you don't click the green Update button for v2.1)

**Comment by dkulp** [comment]
Can you try with the latest on master?   I think the issue was due to a lack of audio device.  SDL output was assuming the audio device would drive timing.  Without it, it would just bail.   It should now work (just discarding the audio stream).

**Comment by JonB256** [comment]
using developer.php, changed my RasPi3b+ to Version: v2.x-master-702-gd8e4d89a (master branch) 

Still same behavior. I do have audio out on this FPP (Soundblaster, currently)
Immediately Stops FPPD, then restarts FPPD, but video stays frozen on one of the first few frames. 
You hear about 1/4sec of audio, then nothing.

**Comment by dkulp** [comment]
Just pushed one more fix.   Can you give that a try?

**Comment by JonB256** [comment]
That fixed it, sort of. 
My MP4 videos are playing, but I get <1second of audio, then it stops and the countdown clock stops.
The video plays just fine, though.

**Comment by JonB256** [comment]
I will test "shortly" on a BBB with no sound.

**Comment by dkulp** [comment]
I just pushed another set of changes.   Please test that.

**Comment by JonB256** [comment]
I had "accidentally" or "luckily" updated to that one. It is working on the BBB with a minor glitch - the FPPD status switches from Stopped to Running to Stopped to Running. Video continues unaffected, though.  The BBB is "media only" since it has no audio.

On the RasPi3b+/Colorlight - it is working as expected. Video is smooth (low res MP4 playing to the Colorlight). Audio is good and in sync.

**Comment by JonB256** [comment]
RasPi3b+ working normally on  v2.x-master-705-g6e3d8918 (master branch) 

but, on the BBB/Octo, not so much. I have 3 MP4 files. The first two "stop" the FPPD and do not play.
The third one Plays just fine.  I'll look up their Frame sizes and post back here.

**Comment by dkulp** [comment]
Is this with the latest code I just pushed about 1/2 hour ago?

**Comment by dkulp** [comment]
And if so, any chance you can send me the mp4's and the backup of your BBB's configs so I can try and reproduce?

**Comment by JonB256** [comment]
It is with the 2.x-master-705 (just released)
They were playing (all 3) in 704.
![mp4 frame size and rates](https://user-images.githubusercontent.com/5251235/47040917-1af8cc80-d14d-11e8-9d97-d33ee3f6e39d.JPG)

Files will get uploaded to Google drive and shared in a bit.

**Comment by JonB256** [comment]
Looking a MP4 files, it looks like I definitely have trouble with anything greater than 640 pixels wide (on the Pi3b+) and even lower on the BBB.

**Comment by dkulp** [comment]
Yea... Without hardware decoder, neither will have the horsepower to fully decode a high def video.   (omxplayer used to output to HDMI uses hardware decoder)

**Comment by dkulp** [comment]
If you "sudo apt-get install ffmpeg", you can run something like "ffmpeg -benchmark -i ~fpp/media/videos/Rudolph.mp4 -filter:v scale=160:-1-f null -" to see the decode speed.   For the Rudolph.mp4 file you sent, it gets 13fps on a Beaglebone.  Keep in mind, we have to decode ALL frames from an mp4 even if the sequence is 40fps.   And that also is using 100% of the CPU and we obviously need some CPU for the panels and such.

**Comment by JonB256** [comment]
Dan, Version: v2.x-master-707-g66515b38 (master branch) is working as expected/desired.
While the BBG still chokes up on my large format Rudolf.mp4 file, it is playing the others smoothly.
Whatever SDL changes you made helped.

I don't have the RasPi handy for testing right now. It is going on a Homecoming Parade Float and won't be home for testing until Tuesday.

**Comment by JonB256** [comment]
Did get a chance to test the RasPi before leaving for the Homecoming parade. It did play the MP4 files as desired. Closing this. Thanks, Dan.
