### ISSUE TITLE
Networking failure with 2.1

### ISSUE THREAD

**Issue by lrhorer** [FalconChristmas/fpp#426]
For some reason, the routing table and resolv.conf get blasted on reboot with the Pi set to forward packets between the Ethernet and WiFi interfaces and static IP addresses set for both interfaces.  I have etho set for 192.168.8.57 and wlan0 set for 192.168.1.57.

After reboot:
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.8.1     0.0.0.0         UG    0      0        0 eth0
66.90.130.10    192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.10    192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
66.90.130.101   192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.101   192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 wlan0
192.168.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 wlan0
192.168.8.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.8.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

I deleted the default gateway and added a correct one:

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.1.1     0.0.0.0         UG    0      0        0 wlan0
66.90.130.10    192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.10    192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
66.90.130.101   192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.101   192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 wlan0
192.168.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 wlan0
192.168.8.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.8.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0[/code]

Then I went in and cleaned up the table:

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.1.1     0.0.0.0         UG    0      0        0 wlan0
66.90.130.10    192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.101   192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 wlan0
192.168.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 wlan0
192.168.8.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.8.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0[/code]

I then (once again!) had to update resolv.conf, because (yet again!) it had reverted to:

# Generated by Connection Manager
nameserver 127.0.0.1[/code]

At this point I can reach the internet.  After I rebooted, resolv.conf reverted, and the routes are once again screwed up:

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.1.1     0.0.0.0         UG    0      0        0 wlan0
66.90.130.10    192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.10    192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
66.90.130.101   192.168.1.1     255.255.255.255 UGH   0      0        0 wlan0
66.90.130.101   192.168.8.1     255.255.255.255 UGH   0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 wlan0
192.168.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 wlan0
192.168.8.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.8.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

**Comment by cpinkham** [comment]
Closing ticket for old OS/FPP version.  It can be reopened if it is still reproducable on FPP v3.5.x SD images, but believe this issue is resolved in the newer scripts and OS version.
