### ISSUE TITLE
Networking issue with v2.x-master-723-g84d89f38

### ISSUE THREAD

**Issue by PeteyHall** [FalconChristmas/fpp#428]
I just installed  v2.x-master-723-g84d89f38 on a couple of my pi's and ran into the same problem on each of them.

If I have a Pi with the wifi connected to my primary network (192.168.1.83) and the Ethernet port (192.168.83.1) hardwired to the f16v3, after the above version gets installed on the pi, I lose the ability to go across the pi and get to the f16.  

I've tried removing the IP configs, turning off/on the enable routing feature but nothing works.

I can confirm it's this version because prior to it, I was running 2.1 and the routing was working as expected.  It's only once I upgraded did I see the network routing issue.

**Comment by cpinkham** [comment]
Closing this ticket for old OS/FPP version, this appears to be working newer FPP v3.5.x versions.
