### ISSUE TITLE
2.2 - Skipping playing sequence to next in playlist if there is a delay

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#429]
so now that I updated to 2.2 this issue just started happening

If I manually start my playlist everything runs fine but if I reboot my Pi and then the schedule kicks right in the Pi's are all delayed a little and then it totally skips to the next sequence and doesn't finish what was playing. This never happened to me in 2.0 or 2.1, only 2.2. I just went back to developer.php and went to 2.1 and there's a delay after reboot when playing but it finishes the sequence at least, I went back to 2.2 and it plays the sequence for 10 seconds or so and jumps to the next

here is a video showing what's up - https://youtu.be/FpOR2hXUHs4
Video showing what the lights are doing, they should be a nice slow marquee scroll but they freeze and start strobing at end and then the Santa voice just stops and goes to my 2nd sequence in list - https://youtu.be/F0SoaAMdLZ8

all my logs, FSEQ file and audio file - https://drive.google.com/file/d/1PRLCVXXrNdLYGodNoC71HWwxxoSwoNB9/view?usp=sharing

**Comment by bchiaino** [comment]
ok, I turned on channel outputs, rebooted and restarted FPPD once or twice and got it to happen at around 14:27:38 or so

[FPP_Logs_20181025.zip](https://github.com/FalconChristmas/fpp/files/2516259/FPP_Logs_20181025.zip)

**Comment by dkulp** [comment]
I think I'll need to have you try it on master.   The data I need to figure out where the bad number is coming from isn't logged until after 1 second has passed, but by then all hell has broken lose already. :(

That said, this might be fixed on master already.

**Comment by bchiaino** [comment]
ok cool, once im home ill test the screens and this on the master and report back to you. 
thanks as always!

**Comment by bchiaino** [comment]
so far so good on v2.x-master-731-g052c4b7e. I rebooted like 5 times where the schedule would immediately start and the first sequence played fine

If I am on wifi (even though all my syncing is hardwired and checked off to be on the ethernet network) there is a lot of delay when the sequence starts as if waverthing is trying to connect and sync up, Once it take all 3 off wifi its perfect BUT I need the master to be on wifi for the clock so kinda stuck in the middle. either way its awesome, thanks dan!!

**Comment by dkulp** [comment]
Fixed in 2.3
