### ISSUE TITLE
Scheduler - playlist reported as being next to play even after being deleted.

### ISSUE THREAD

**Issue by jnealand** [FalconChristmas/fpp#43]
I deleted the only playlist I had - named test1 and created a new playlist - test2.  However on the status page it shows that test1 is the next one up.  The pi has been rebooted since I deleted test1.  See pictures below.
![playlists](https://f.cloud.github.com/assets/2533387/1716946/f7f4662a-61c8-11e3-8a19-97f6da574e77.PNG)
![schedule error](https://f.cloud.github.com/assets/2533387/1716947/fc76d336-61c8-11e3-84ca-04d4997a6688.PNG)

**Comment by cpinkham** [comment]
The scheduler also needs to check to see if a playlist exists when it runs through to determine the next scheduled playlist.

**Comment by cpinkham** [comment]
This was fixed by e71042ee7dba
