### ISSUE TITLE
2.2 - Video on P10 matrix is very choppy now

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#430]
Just updated to 2.2 and my 2 matrix screens are very jumpy and have a lot of breaking up when a video switches scenes or a lot of movement, If I jump back to 2.1 it plays great. you can see in the video by the umbrella during movements how it breaks up. Also in the Christmas vacation scene you can see the lines jump when it goes from scene to scene. 

Tried a fresh formatted SD card with 2.2 and 1 FSEQ and still is very choppy

https://youtu.be/yMME6xDv3_M 
https://youtu.be/x6jXGw4UHBE

**Comment by dkulp** [comment]
This is fixed on master.
