### ISSUE TITLE
FPP Help fpp & fppmm Help screen is not working

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#432]
I think this broke recentlym but if you go to Help and then fpp &fppmm usage page, it's not displaying the help command information.  See pic

![image](https://user-images.githubusercontent.com/8147459/47593500-3037dd00-d93d-11e8-83db-9e6599755d33.png)

**Comment by jaredb7** [comment]
@dkulp Noticed that the fpp, fppd, fppmm bins are not longer in the /bin.bbb or /bin.pi not sure if there is a reason for this now? but if I do 'make release' they get put back there. There code in the functions bash script that looks like it removed the bins if they are the same as the github/compiled versions

**Comment by dkulp** [comment]
We should just use the binaries in /opt/fpp/src (and likely put sim-links in bin.bbb and bin.pi).   I didn't see the point of having compiled binaries checked into git and they tended to conflict so I removed them.
