### ISSUE TITLE
Issue adding music is & symbol

### ISSUE THREAD

**Issue by brian461** [FalconChristmas/fpp#433]
When adding music to a music only playlist and after trying to add music with a & symbol in the name makes the playlist inoperable and you can't select it the playlist anymore to edit it.

**Comment by JonB256** [comment]
Did you edit the filename or are you waiting for that to become a "handled" character?

You can access and edit contents of the FPP Media folders over your PC's network by typing \\192.168.0.172 in the "search window" of Windows (the IP is my FPP Master. Substitute your IP)

**Comment by brian461** [comment]
Editing the file name works fine.  If & is not a valid character then understood.  Wasn't sure if that was expected or not.

**Comment by jaredb7** [comment]
If it works manually adding it to the playlist, then it's supported (anything you can type into a file name should) and it should work from the GUI. 
The problem is just in the GUI , I probably should of checked this when looking at the '%' file name issue as well :( .
