### ISSUE TITLE
"Update Available" message when remote github version is unknown

### ISSUE THREAD

**Issue by MarkAAmber** [FalconChristmas/fpp#434]
This is minor, but I wanted to report it for the record.  I believed its an easy "if statement" fix

I've noticed when remote github version is "Unknown" the red "Update Available!" hyperlink shows up (even though the running version may be the latest).  I suspect this is triggered by a simple "if" statement which checks to see if the "R:" version and the "L:" version are different.   Probably needs an additional simple check that the "R:" version is not "Unknown".

**Comment by jaredb7** [comment]
It was something like that, I tried writing the test in one line but rewrote it in proper if statement. Kinda knew this would pop up. Just need to test it when I get a chance.

I added descriptions of the R: and L: down the bottom, It's just R - Remote (Github) and L - Local (On FPP)... In case users were wondering :) .

**Comment by jaredb7** [comment]
Bugger, Fixed properly now lol. Will put into master a bit later.
![image](https://user-images.githubusercontent.com/799998/47959339-33158a80-e02d-11e8-9c64-98237a0610d8.png)
