### ISSUE TITLE
Remote video playback sync/speedup/slowdown problems

### ISSUE THREAD

**Issue by MarkAAmber** [FalconChristmas/fpp#435]
I've updated to 2.3 and had a chance to play with this a bit more to gather more details and have attached a log:

Remote video playback starts and tries to sync, but has a terrible time getting "in sync".  First off, it has a prominent start delay of 1-second or more (probably caused by omxplayer startup) and then spends the next minute or so doing speed-up / slow-down / speed-up / slow-down.  Eventually, it appears to either get too far off or give up and proceed with playback at a slightly slower than normal speed.  By the end of the sequence, the video is quite far behind (several seconds or more).  The longer the sequence, the further behind it gets and doesn't complete.

I've filtered the fppd.log for media and multisync debug message and attached to this post.   This section is interesting and the pattern recurs many times throughout playback.  I'm confused by the multiple blocks of repeat speedup speedup speedup and slowdown slowdown slowdown.   Also, there seem to be cases where it initiates a slowdown even though the Master/Local time diff shows the local time is behind the master time (which would put it even further behind) 
[fppd_log.txt](https://github.com/FalconChristmas/fpp/files/2522980/fppd_log.txt)

**Comment by dkulp** [comment]
I believe this is now fixed about as good as we can do.

**Comment by MarkAAmber** [comment]
With omxplayer, I agree this is about as good as we can do (by not crossing the mute/unmute speed boundary)   However, it may be possible that a different player may not have as bad a startup delay (problem #1) or no additional delay related to muted/unmuted sound (problem #2)
