### ISSUE TITLE
Scriptable effects

### ISSUE THREAD

**Issue by pmscientist** [FalconChristmas/fpp#44]
It'd be nice to return values from a script that become the output of an effect. It's possible this may overlap with the request for background sequences.

The initial thought for this was to grab light color(s) from a feed such as cheerlights and  use that to drive pixels. In lieu of supporting every possibility, thought it might be easier to allow for scripts to return channel and intensity information and let people apply their own logic.

**Comment by cpinkham** [comment]
This can be done using the Pixel Overlay system now, Additional enhancements will come when I get around to creating a Channel Input framework similar to the Channel Output framework and the Pixel Overlay system becomes just another input.
