### ISSUE TITLE
v2.3 Pressing Play button on UI even though it's grayed out while playlist is running locks up ui

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#441]
I discovered this bug over Halloween it's in 2.3 and 2.1.. Start a single item playlist by pressing play. While the item is the playlist is running, click the Play button even though its grayed out, ( this happens with a multiple item playlist too)

Result: when the event is done playing the UI is displaying Playing "xxxxxx" and the elapse and remaining counters are frozen. F5 refresh doesn't do anything. You have to hit Stop Now to reset the UI. The same behavior happens it you are triggering a playlist with a motion sensor. If the sensor triggers before the playlist is done, then it locks up the playlist and you have to click Stop Now.

**Comment by jaredb7** [comment]
Not sure of the inner workings of FPP but yeah does seem like it's not liking being commanded to play a playlist while one is already running. It should stop what's happening and play whatever you tell it - though I'm not sure how that was ever intended to work.

I noticed if I hit play when one is running that I have to hit Stop Now twice to actually get it to stop. Almost like the 2nd play attempt is queued (timers don't reflect this though).

**Comment by patdelaney** [comment]
I'm not sure if this is a 2.x issue or if it's been around in 1.x.  I nned to load up a PI with 1.x and test it

**Comment by patdelaney** [comment]
In 1.10, if you press the grayed out play button while its running the current item in the playlist will stop.

**Comment by dkulp** [comment]
Just fixed.  We were previously just greying out the various buttons, not actually disabling them.   They are now completely disabled and you shouldn't be able to click on them.
