### ISSUE TITLE
Last push - FPPD will not start

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#442]
I've got 6 FPPs all stopped right now
 v2.x-master-765-g38be9519 (master branch) 

Am looking at logs to see if I find a reason.

**Comment by JonB256** [comment]
From fppd_start.log

Tue Nov  6 06:46:48 CST 2018
Checking for interfaces
Setting up Avahi
Setup channel outputs
Running pre-start scripts
Starting /opt/fpp/bin.pi/fppd
nice: '/opt/fpp/bin.pi/fppd': No such file or directory

**Comment by JonB256** [comment]
The 767 update did get FPPD started

**Comment by dkulp** [comment]
There WAS a period yesterday where the config update was creating sym links that would have then prevented future updates.   If you did an update yesterday while that was there, you may need to flip branches back to 2.3 and then back to master just to get everything cleared out.

**Comment by JonB256** [comment]
same message about FPPD not found

Starting /opt/fpp/bin.pi/fppd
nice: '/opt/fpp/bin.pi/fppd': No such file or directory

**Comment by JonB256** [comment]
I'll do the "switch" to 2.3 and back as suggested.

I am an obsessive updater
