### ISSUE TITLE
v2.x Pi B with PiFace will not trigger a relay playing a Sequence.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#444]
This took a while to reproduce. I had problems when I upgraded to 2.x, This doesn't happen on v3plus.
Scenerio: Raspbery Pi model B with Piface. Configure a single GPIO channel output for GPIO 200. save config and restart FPP.
Go to Display testing and click Enable Test Mode. You hear the relay clicking during the test. Put FPP in Bridge mode and play a single channel sequence to the PI and you can hear the relay clicking.

Upload the sequence to the Pi, create a single sequence playlist and then play it. Sequence shows it's playing, but no relay clicking.  Add a 2nd GPIO output pointing to GPIO 201 and enable it. Save, and restart FPP, Play sequence and you can hear the relay. Remove the 2nd GPIO output and it's then No replay clicking.  I do not have this on the v3plus.
Attached is the xlights files that you may need.
I use the Pi B's for interactive props that trip with motion sensors.

[Barrel_2.zip](https://github.com/FalconChristmas/fpp/files/2555236/Barrel_2.zip)

**Comment by dkulp** [comment]
Can you check something:  try adding an e1.31 output of a bunch of channels that would cover the same range.  I'm wondering if someplace there is a "numChannels = start - end" or something that is evaluating to 0 and not actually loading the single channel.   The e1.31 should force loading the channels.   If that still doesn't work, then it's likely in the gpio code someplace.   Just trying to narrow down where to look.

**Comment by dkulp** [comment]
Can you also grab "http://fpp/fppjson.php?command=getChannelOutputs&file=co-other" and attach here?

**Comment by patdelaney** [comment]
I did a few tests: Created a e1.31 with channels 1-10 and made it active, played the sequence and it worked. unchecked active on that line, restarted fppd, the relays did not work. 
Changed the start channel on e1.31 to 10 and universe size 10, clicked active and saved and restarted fppd. The relays work again.



[co-other.zip](https://github.com/FalconChristmas/fpp/files/2555312/co-other.zip)

**Comment by dkulp** [comment]
Can you try flipping to master and seeing if the commit I just made fixes it?

**Comment by patdelaney** [comment]
It seems to have fixed it but, now when I try to add or remove universes from the E1.31 Bridge mode universes it will not save the setting. If I hit refresh (F5) it reverts back to the same setting.

**Comment by patdelaney** [comment]
As an update the issue does also happen on Piv3+  the reason I didn't see it earlier was that there was a P10 panel output defined and enabled. When I unchecked the LED Panel output, the same error that I reported on the Pi B.
