### ISSUE TITLE
Feature request - copy settings from uSD to sda1

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#446]
Currently, the FPP settings mounts either the uSD partition or the sda1 partition for storage of settings (and all the media folder contents)

Could a script be written that would temporarily mount the sda1 drive and copy the media folder to it?

Then a user could use the Settings page to select sda1 and reboot.

(I ask because I am not a script writer, but mounting another drive seems very possible from within an SSH window, and then a copy to follow)

**Comment by MarkAAmber** [comment]
YES PLEASE!!!!

I think the logic should include a check whether the user selected to format or not format.  If they choose format, then FPP should format, mount, and copy the files.  If the user chooses "do not format" then FPP probably should assume they want to use existing files on the external storage and not copy over them.

Or maybe just add another checkbox where it asks for format to also ask to copy files yes/no?
