### ISSUE TITLE
2.x Master. I can't modify E1.31 Bridge mode Universes

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#447]
Since the bug fix earlier in the week for playing a sequence with a single channel define output. I can 't add or remove anything from the input page.

**Comment by JonB256** [comment]
I had to delete the ci_channelinputs.json file in the Config folder. 
At one point (while trying to get DDP working) I created 64 universes of input but then could NOT get it to go away. Save did not Save.

**Comment by patdelaney** [comment]
It's fixed now JonB256 in Master
