### ISSUE TITLE
DDP Raw works in v2.x-Master. Didn't work in v2.3 or v2.2

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#448]
As posted in a Forum entry about DDP.

My "sending" unit is running v2.x-master and has Channel Outputs configure for DDP to go to a specific P10 panel and its IP address.

That panel was running v2.3  Could NEVER get anything to light up on the panel
Oddly, if I changed the Channel Outputs to DDP One Based instead of Raw, I did get lights, though not what I wanted since everything dropped to channel 1.

But, when I changed my P10 panel to v2.x-master, it now works exactly as expected. 

Note - switch via Developer.php to v2.2 - Does not work
Switch to v2.1 - it does work
Switch to v2.0 - it does work

**Comment by dkulp** [comment]
Closing as it is working on master.  :)
