### ISSUE TITLE
V2.x Master  GPIO triggering a playlist while another playlist is playing locks up UI

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#450]
I discovered this bug at Halloween in 2.3, but I need to see if it was in 1.10.  I have a few props that use motion sensors to trigger a playlist. The problem I am seeing is that if the playlist is playing and the system gets a trigger to play that playlist again, it locks up the webUI, and will not respond to any commands until you click stop NOW. The currently playing event finishes, but the UI is frozen.

The workaround for a Linux savvy person is to write a script that eats the triggers for the duration of the event. But that is not your everyday user.
![image](https://user-images.githubusercontent.com/8147459/48261133-9b74bb00-e3e3-11e8-8f6e-a5a2533479d7.png)

**Comment by cpinkham** [comment]
I believe this is fixed now. There was a bug where starting a new playlist wasn't properly stopping the old one.
