### ISSUE TITLE
Upgrade breaks network routing

### ISSUE THREAD

**Issue by DClem85** [FalconChristmas/fpp#455]
I upgraded from 2.1 to 2.4 with a 2.3 re-image and then upgrade to 2.4.2 and couldn't get my routing to work after setting it all back up again. I made sure I had all the IPs and subnets correctly entered, no dice. I rolled back to 2.1 and upgraded incrementally to 2.4 and it worked perfect, _until_ I did a cold reboot. Then it wouldn't route again. Rolling back to 2.1 again....

**Comment by bchiaino** [comment]
yeah the networking is messed up on 2.4, I have all my stairs set but the Pi's don't actually set them, they still remain the DHCP on. I have my stain set to 192.168.219.205 but the top page and the IP I have to go to is 192.168.219.5 and I haven't been able to get wifi to actually work anymore, the IP address shows 192.168.0.1 even though the address of my home network is 192.168.1.1. the 169 address in my pic is a USB to ethernet for color light card
<img width="1152" alt="screen shot 2018-11-15 at 9 32 00 pm" src="https://user-images.githubusercontent.com/40632971/48594280-04958a80-e91e-11e8-9ca6-c551e7b19a26.png">

**Comment by dkulp** [comment]
Can one of you try putting in the gateway IP address for your wifi into the Gateway field for the eth0?   I believe we MUST have a gateway provided for a static IP address to work now.  :(    However, the gateway also needs to be valid and be the one that provides  internet access.

**Comment by bchiaino** [comment]
in 2.4.2 (non master) the gateway being in there seems to work. being its ok so far I'm going to stick to that for a little and start running some FSEQ files through the remotes. Thanks Daniel!

**Comment by cfmorrell** [comment]
I'm seeing similar issues in 2.5.  wlan0 configured with static 192.168.1.250/24 with a gateway of 192.168.1.1.  eth0 configured with static 10.0.0.1/24 with no gateway or with gateway of 192.168.1.1 (same result).  Default route shows up as 192.168.1.1 pointed at eth0 (should be wlan0).  I can run route add and route del to get routing configured correctly, but it does not persist.  After less than 30 seconds, the routing table has reconfigured itself back to its original state where it thinks the default gateway is out eth0.

**Comment by cpinkham** [comment]
Closing ticket as this version is so old and we have been through an OS upgrade since then.
