### ISSUE TITLE
2.4 - pi matrix adapter

### ISSUE THREAD

**Issue by robbaldwin12** [FalconChristmas/fpp#456]

**Comment by robbaldwin12** [comment]
on version 2.4... 

ouput 1 is working YAY fixed that
however panels are still shifted 1 to the right... when swapped back to 2.1 (last known working) they shifted a 2nd right and now stuck there no matter which version i choose. 
this was done using the update button from 2.1 to 2.4 

do i need to reiimage at 2.4? wait for 2.5?

**Comment by robbaldwin12** [comment]
do have it set to master branch for now
still 2 panels off on that

**Comment by cpinkham** [comment]
This seems to be working fine in FPP v2.x latest master code using a couple P5 panels.  If you are still having issues, please open a thread on the forum and we can help troubleshoot.
