### ISSUE TITLE
ip routing

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#457]

**Comment by 1991mustang50** [comment]
i have to controllers f16v2 and f4v3 behind fpp pi with a network switch between pi and controllers. i can ping both controllers. one of the controllers i can bring up controller page(after i switched to linux wifi drivers) but i can see the other one. the controllers work in display testing. just cant access controller page on second controller. xlights cant find it either. thanks

**Comment by LightsOnHudson** [comment]
There is a bigger item, in the lastest 2.5.3 version. The FPP networking page shows DNS entries, yet when you look at /etc/resolv.conf it only lists nameserver 127.0.0.1 .. Cannot ping outside of the network to any DNS servers. Also, default routes when EH0 and Wlan are in use, it is defaulting to ETH0 always as default route. doing an 'ifconfig eth0 down' temporarily causes the route to be brought back to Wlan0.  however, DNS is still an issue and needed to be resolved on the command line. I have done this for about 5 different individuals on 2.5.3 (including my own setup)

**Comment by nmiller0113** [comment]
@LightsOnHudson this must only be a problem when running WLAN0 and ETH0 simultaneously?  The only reason I ask is I'm running WLAN0 only and all is routing and resolving properly.  My resolv.conf also says 127.0.0.1, but I'm assuming it's intentional.

**Comment by cpinkham** [comment]
Believe this is not an issue on newer OS and scripts in FPP v3.5.x.  If it can be reproduced under FPP v3.5.x, we can reopen the ticket with updated info.
