### ISSUE TITLE
Unable to trigger event via MQTT

### ISSUE THREAD

**Issue by k5beason** [FalconChristmas/fpp#459]
I'm unable to trigger any events via MQTT. I have playlists and effects working.

I created an event 1/1 that triggers the stop playlist script. triggering it via web ui works as expected but mqtt will not trigger it. I've tried also triggering a playlist via an event via mqtt unsuccessfully.

Can you clarify the topic and payload required to trigger an event?

My end goal is to use a looping playlist that I trigger on and off via homeassistant and mqtt. I need a method to instantly kill the playlist rather than just end the loop so I can instantly select and start a new playlist

**Comment by dkulp** [comment]
The payload should just be the event name.

**Comment by k5beason** [comment]
Ok so with topic: test/falcon/player/FPP/playlist/name/set 
I'm able to trigger playlists with their name in payload.

Given the event ID 1/1 named off and channel selection id blank what should my topic and payload be or what should I change. settings below

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3156178/48736524-82f17580-ec19-11e8-89d5-5f75b4dae7cf.png">

**Comment by dkulp** [comment]
I believe it would be test/falcon/player/FPP/event/whatever and payload would be "off".   Looking at the code, everything after the slash in "event/" in the event topic is ignored, but something is required there for the match to work.

**Comment by k5beason** [comment]
Topic:  test/falcon/player/FPP/event
Payload: 01_01
It's now working as expected. Just couldn't find the working combo

**Comment by dkulp** [comment]
OK.  Good to know.  :)
