### ISSUE TITLE
No DMX from PiCap running v2.4.2

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#460]
First time I've needed DMX from the Falcon PiCap (for another person's project).

FPP v2.4.2 working perfectly in Tether Mode for this project.
Didn't try Master since there was no Internet connectivity to change branches.

I enabled the DMX in the "Other" tab
Tried ttyAMA0 and ttyS0 on both DMX Open and DMX Pro. 

Never got DMX from any of the 4 combinations. 
Ending using a USB DMX dongle. No problem there.

Left the PiCap connected though because they need the RTC feature.

**Comment by JonB256** [comment]
Saw a post on Falcon forum that may impact this (but I'm not setup up to test at the moment).
I did not have anything defined on the E1.31/Artnet Outputs page and the forum poster told someone that they "needed" to do that to cover the universe being sent to DMX.
I'll check that when I can on another PiCap.

**Comment by cpinkham** [comment]
I believe we have users using DMX on the PiCap now, have you confirmed this is fixed or is it still an issue in FPP v3.5.x?

**Comment by cpinkham** [comment]
This has been confirmed as working using the DMX Open Channel Output and ttyAMA0, closing ticket.
