### ISSUE TITLE
FPP will not play MP3 files where "MP3" is actually capitilized

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#461]
It's a Linux thing, I know, but if the sound file has a "Cap" in the extension, it wouldn't play.

Changed it and replaced. Works fine.

Also, the "Rename" feature in File Manager did nothing.

V2.4.2

**Comment by cpinkham** [comment]
This should be fixed in the master branch now as of bb38d906615ab753619809ac4cfce6413369a07e
