### ISSUE TITLE
FPP 2.5 - While playing a playlist, Status page does not show playlist contents

### ISSUE THREAD

**Issue by ItsFitz** [FalconChristmas/fpp#469]
I upgraded from 2.1 to 2.5 and now the Status page no longer shows the contents of the active playlist.  Even if I select the playlist again.  I have experienced this problem with Safari (on Mac) and Firefox (on Windows).

**Comment by dkulp** [comment]
I wasn't really able to reproduce this using the playlists created on FPP.   However, playlists uploaded/updated from xLights were not setting the playlist name correctly which can cause this.   xLights has been updated to fix that.    That said, a "save" of the playlist in FPP can also fix it.
