### ISSUE TITLE
Make FPP more platform independent

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#47]
There are already some pieces in place for this, but we should make an effort to become more platform independent as more platforms are requested, and supported.

Things off the top of my head:
• Build on the device after a checkout (instead of checking a Pi binary into the repo)
• Config "profiles" - maybe some sort of default settings files depending on hardware
• Turn some features into more "API" based things that can be loaded at runtime instead of compile time?!? (things like ogg vs. mp3, wiring Pi for SPI vs. some other SPI library vs. nothing)

**Comment by cpinkham** [comment]
Closing this as FPP v1.5 will support Pi and BBB.  More specific changes can be addressed under individual issues/tickets.
