### ISSUE TITLE
Comma in playlist name breaks scheduler

### ISSUE THREAD

**Issue by mattncsu** [FalconChristmas/fpp#476]
I noticed today that if I try to add a playlist with a comma in the name to the schedule, it causes that schedule entry to be messed up (invalid dates, wrong times, etc) after saving.  Need to escape the comma somewhere.

I'm running:

FPP Version: | v2.5.3
FPP OS Build: | v2.2
OS Version: | Raspbian GNU/Linux 9 (stretch)
Kernel Version: | 4.14.71-v7+
Git Branch: | v2.5
Local Git Version: | 926a5c0

**Comment by nmiller0113** [comment]
@mattncsu I don't believe they've ever supported characters like comma's.  I'd suggest just removing the comma as I doubt this will be high on the priority list.

**Comment by cpinkham** [comment]
The Scheduler still uses a CSV config file, so commas are not allowed
in the playlist name.  When we get around to rewriting or upgrading the
scheduler, it will be switched to a JSON file and allow more elaborate
playlist names.

On Tue, 2018-12-04 at 21:24 -0800, mattncsu wrote:
> > > > I noticed today that if I try to add a playlist with a comma in the
name to the schedule, it causes that schedule entry to be messed up
(invalid dates, wrong times, etc) after saving.  Need to escape the
comma somewhere.
> I'm running:
> FPP Version: | v2.5.3
> 
> FPP OS Build: | v2.2
> 
> OS Version: | Raspbian GNU/Linux 9 (stretch)
> 
> Kernel Version: | 4.14.71-v7+
> 
> Git Branch: | v2.5
> 
> Local Git Version: | 926a5c0
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/em
ail/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"Comma in playlist name
breaks scheduler (#476)"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/476"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/476",
> > "url": "https://github.com/FalconChristmas/fpp/issues/476",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> > "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> "title": "Comma in playlist name breaks scheduler (#476)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**mattncsu**",
> > "activityImage": "https://assets-cdn.github.com/images/email/message_
cards/avatar.png",
> "activitySubtitle": "@mattncsu",
> "facts": [
> {
> "name": "Repository: ",
> "value": "FalconChristmas/fpp"
> },
> {
> "name": "Issue #: ",
> "value": 476
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > > > "body": "{\n\"commandName\":
\"IssueComment\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 476,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 476\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> > "uri": "https://github.com/FalconChristmas/fpp/issues/476"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
419962435\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]
