### ISSUE TITLE
Show freezes if one controller goes down

### ISSUE THREAD

**Issue by gayde2** [FalconChristmas/fpp#477]
I have experienced my entire show freezing if a single controller goes down. I am using many ESPixelStick modules and occasionally one will stop responding for a few seconds. Unfortunately, this causes all of the other outputs to freeze until the Raspberry Pi is rebooted. The other controllers and Pi are both still on the network so it's not a connectivity issue. I have "Always transmit channel data" enabled.

Does FPP wait for a response from a controller when trying to send a packet? If so, can this be configured to not stop the entire show if one is missed?

**Comment by dkulp** [comment]
What version of FPP?   With 2.x, if it takes too long to send messages out, it should ping the controllers and remove anything not responding and then continue on.

**Comment by gayde2** [comment]
I am using 2.x. It took more than 20 minutes last night before it continued. How often does it ping the controllers? Also, once a controller is removed, will it ever get added back in?

**Comment by patdelaney** [comment]
Just to chime in it sounds like "contollers" are wireless esppixel sticks

**Comment by gayde2** [comment]
Yes, that is correct. They are ESP8266 chips running on Wemos D1 Mini boards. I don't think the issue is with the controllers since everything is fine when I reboot the Pi.

**Comment by valentinfr2** [comment]
hello, same things for me.... sequences lag if 1 espixelstick go down.... (I put one in my neighbor's house.) if he cut it, all lag...

**Comment by darylc** [comment]
what version of fpp are you running?  I don't have this issue on 3.4 for instance.

**Comment by valentinfr2** [comment]
The last from Yesterday and before same things....

**Comment by cpinkham** [comment]
Closing this as it does not appear to be an issue with the latest FPP v3.x and master branches.
