### ISSUE TITLE
 Enhancement request: Set audio volume per playlist

### ISSUE THREAD

**Issue by reynos** [FalconChristmas/fpp#480]
Would it be possible to add a feature to set the volume for each entry in a playlist to help cater for audio tracks with differing levels. Could the software remember the default level for each track on the system (as set by the user). 
Also useful - a % volume override at the playlist level, use case: music could be set to play quieter later In the night.

**Comment by cpinkham** [comment]
Per-playlist volume is supported in the new v2.x playlist format.  You can add a 'Volume' playlist entry to the playlist in the LeadIn section.  The volume override feature can be accomplished using the 'Branch' playlist entry.  You can have a Volume playlist entry in the Main Playlist section that is only executed after a certain time.  Create a Branch entry to test the time and skip over the Volume entry if the time is not after the time you want to lower the volume.
