### ISSUE TITLE
New install of 2.5.3 Image Upgrades/Compiles on every reboot, even without updates needed

### ISSUE THREAD

**Issue by bigwavedave42** [FalconChristmas/fpp#481]
I just imaged a new SD Card with 2.5.3 (FPP-v2.5-Pi.zip), and after every reboot it shows "_FPP is currently updating._"  Looking at the git_pull.log I can see it is doing a recompile.  This means it takes quite awhile before it is available after each reboot.

As I understand it, it should check for an update on each reboot, but should only take the recompile path if there was something new on GitHub.  However, I'm finding it to still be 926a5c0 before and after each reboot.

I've done this via imaging on both a Mac and Windows 10 machine, thinking there was something odd with the first SD Card imaging.  Both attempts are showing the same result.  

I've collected the logs from the most recent image AND included a FPP Backup in the following Google Drive folder:
https://drive.google.com/drive/folders/1zqvgB6M-lOWLj2Ee-SAtflsA0zPiQjzX?usp=sharing

**Comment by bigwavedave42** [comment]
A bit more info on the system:


Version Info	 
FPP Version:	v2.5.3
FPP OS Build:	v2.4
OS Version:	Raspbian GNU/Linux 9 (stretch)
Kernel Version:	4.14.71+
Git Branch:	v2.5
Local Git Version:	926a5c0 ChangeLog
Remote Git Version:	926a5c0

**Comment by bigwavedave42** [comment]
It seems to have the same behavior on : Version: v2.x-73-gbe4e0ed9 (zstd branch)

**Comment by cpinkham** [comment]
In FPP v2.x, we stopped storing binaries in git, so any update requires a recompile.  Normally these are very quick because we use ccache to cache the compiled object files.  There was an issue a while back where the ccache cache was too small causing slow recompiles, but this issue has been corrected in master and v2.6.
