### ISSUE TITLE
Playlists converted from 1.8 to 2.5, can become unusable

### ISSUE THREAD

**Issue by bigwavedave42** [FalconChristmas/fpp#482]
As reported on Facebook at:
https://www.facebook.com/groups/xLights/permalink/2037872762915135/

The user upgraded from 1.8 to "2.5".  When they did that, it asked them to upgrade the playlist.  The resulting playlist was named 14DEC18-CSV.

From the post : "Removing the -csv has fixed the problem! How bizarre as that’s what fpp did automatically when I hit the upgrade playlist button........"

**Comment by cpinkham** [comment]
The -CSV is the original CSV copy of the playlist.  The upgraded version should have the same name but without the -CSV appended.  We keep around the original CSV version as a backup because it can be loaded in the UI and is converted to the new JSON format when saved.
