### ISSUE TITLE
Enhancement: An API to handle thanks/like button

### ISSUE THREAD

**Issue by priyankchouksey** [FalconChristmas/fpp#487]
I would like to request enhancement of thanks/like button next year.
The Use case is:
- We will put a big Thanks button in Yard which viewers will press if they like the show.
- The API will be called but the button, I am thinking to call the API via ESP attached to the thanks/like button.
- When the button is press the current show will/may pause (Issue #486) and play a custom sequence of Thanks and then resume the show after playing thanks sequence. If pause/resume is not a better option then one or few universes can be configured to play an additional sequence (can play a thanks message in the fence or mega tree).
- The API will save the event to a file with a date-time stamp. The Web-UI can show the Count and log.
- Maybe the API can be configured to call another external API which can do custom implementation like triggering SMS or email.

**Comment by cpinkham** [comment]
This is better accomplished as a plugin than as a part of core FPP.  Maybe bring the idea up on the forum and see if any one decides to take a shot at creating a plugin to do this.  A lot of what you are looking for is already there including running an effect sequence or inserting a playlist into the middle of a running playlist.
