### ISSUE TITLE
Unable to configure wifi with ' in the ssid

### ISSUE THREAD

**Issue by sharebear** [FalconChristmas/fpp#488]
I created a standalone project to take to the office, and after realising I couldn't configure access to the WPA 2 Enterprise authentication required for the office network I tried connecting to the personal hotspot on my iPhone. The ssid is automatically configured to "Jonathan's iPhone" with no (obvious) way of configuring this. Unfortunately the ' is not escaped properly along the way causing an invalid ConnMan configuration to be created.

I was able to work around this by manually creating the ConnMan configuration via ssh (blog post being published in a few minutes, will link once it's up).

I guess this is basically the same issue as #474 that I guess is also escaping related.

**Comment by sharebear** [comment]
The blog post I mentioned https://blog.sharebear.co.uk/2018/12/advanced-wifi-configuration-with-connman-on-falcon-player/

**Comment by ghormann** [comment]
It looks like this was fixed by bdaa1be0ba03528f45c0fc6f696751d1bc2cafdd. I believe this is Duplicate of #117 and should be closed

**Comment by jaredb7** [comment]
Just checked and this was still an issue :( , have fixed it properly now (and tested). 
Fix incoming.
