### ISSUE TITLE
Scheduler does not stop a Schedule when it crosses from Saturday to Sunday

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#489]
When there is a schedule that runs past midnight, the schedule does not end at the correct time and the next playlist will not start when Saturday rolls over to Sunday. When this condition happens, the next scheduled playlist does not start. This left me without having a show one night. This was brought up last week but we weren't sure if it was an issue. The issue has repeated.

**Comment by cpinkham** [comment]
This should have been fixed in the master branch in ff0f0d6f and this commit has now been rolled into the v2.6 release.
