### ISSUE TITLE
Cannot update controller configuration uploaded from xLights

### ISSUE THREAD

**Issue by atairu** [FalconChristmas/fpp#490]
When I tried to manually update controller configuration that was uploaded from xLights into Falcon Player, error message: "Unable to save E1.31 Universes". Reloading Channel Outputs page produces empty page with all configuration disappeared. The only way to recover the controller configuration is to re-upload from xLights again.

What seems to be happening is that after upload from xlights, subsequent update to controller configuration page from GUI typically truncates the "co-universes.json" file with the result that jason file is not well formed and thereby in corrupt state not useful for GUI display.

If the configuration was created manually, this issue is not reproduced, only when configuration is uploaded from xLights.

Not sure if the original design by developers was to always make configurations from xLights and then upload to Falcon Player without the ability to make configuration uploaded.

However, there are situation when one needs to update uploaded controller configuration say for instance one needs to disable a controller/model/universe. As it stands now, one will have to disable from xLights and then upload to Falcon Player. I think user needs to be able to update uploaded controller configuration just like one is able to update manually created configurations

**_How To Re-create_**
===========
1. Open xLights. Validate that Setup tab has at least one or more universes configured
2. From Tools menu, click FPP Connect
3. Put a check on Upload controller configuration. Supply username & password
4. Click Upload button
5. Open Falcon Player
6. From navigate as Input/Output Setup -> Channel Outputs
7. Validate that controller configuration uploaded is correct
8. Make any update (such as un-checking the Active button) and click Save button
9. Result: Error message is produced
10. Reload the Channel Output page. Result: Page is empty.

**Upload & Update image**
![e131_model_config](https://user-images.githubusercontent.com/42845087/50663903-e0931480-0f70-11e9-8107-d452a8a1535d.png)

**Empty Page**
![e131_empty_page](https://user-images.githubusercontent.com/42845087/50664401-8bf09900-0f72-11e9-8d96-5bf2f0a04aa6.png)

**Falcon Version is 2.5.3**
![falconversion](https://user-images.githubusercontent.com/42845087/50664499-db36c980-0f72-11e9-8897-302a23987432.png)

**Comment by dkulp** [comment]
Most likely there is a description with an invalid character in it.

**Comment by atairu** [comment]
Okay I will look at my setup again. What invalid character should I be looking for? Will ampersand qualify as invalid character?

**Comment by darylc** [comment]
Yes, things like & * ; ` ' | etc are bad

**Comment by atairu** [comment]
You are absolutely correct. I remove the only & in my description and I was able to save configuration.

Thanks for the quick response and I will close the case now.

**Comment by darylc** [comment]
Perhaps xlights should be modify the fpp connect not to send characters other than a-z A-Z 0-9 to FPP?

**Comment by atairu** [comment]
I will agree. I'll create a ticket with xLights and see if they can modify xLights not to send invalid characters.
    On Thursday, January 3, 2019, 5:42:14 PM CST, darylc <notifications@github.com> wrote:  
 
 
Perhaps xlights should be modify the fpp connect not to send characters other than a-z A-Z 0-9 to FPP?

**Comment by cpinkham** [comment]
It is likely that the JSON has fields where the embedded quotes are not
escaped properly causing the JSON parser on the FPP side to fail.

On Thu, 2019-01-03 at 15:42 -0800, darylc wrote:
> > Perhaps xlights should be modify the fpp connect not to send
characters other than a-z A-Z 0-9 to FPP?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@darylc in #490: Perhaps
xlights should be modify the fpp connect not to send characters other
than a-z A-Z 0-9 to FPP?"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/490#issue
comment-451313669"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/490#issuecom
ment-451313669",
> > "url": "https://github.com/FalconChristmas/fpp/issues/490#issuecommen
t-451313669",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by cpinkham** [comment]
Sorry, didn't see this earlier message.  The & may need to be specially
handled as well.  I will make a note to try to test on the FPP side
sometime.

On Thu, 2019-01-03 at 15:40 -0800, atairu wrote:
> > You are absolutely correct. I remove the only & in my description and
I was able to save configuration.
> Thanks for the quick response and I will close the case now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@atairu in #490: You are
absolutely correct. I remove the only \u0026 in my description and I
was able to save configuration.\r\n\r\nThanks for the quick response
and I will close the case now."}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/490#issue
comment-451313340"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/490#issuecom
ment-451313340",
> > "url": "https://github.com/FalconChristmas/fpp/issues/490#issuecommen
t-451313340",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by atairu** [comment]
You guys are awesome in responses. Thank you very much.
    On Friday, January 4, 2019, 10:02:47 AM CST, Chris Pinkham <notifications@github.com> wrote:  
 
 Sorry, didn't see this earlier message.  The & may need to be specially
handled as well.  I will make a note to try to test on the FPP side
sometime.

On Thu, 2019-01-03 at 15:40 -0800, atairu wrote:
> > You are absolutely correct. I remove the only & in my description and
I was able to save configuration.
> Thanks for the quick response and I will close the case now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@atairu in #490: You are
absolutely correct. I remove the only \u0026 in my description and I
was able to save configuration.\r\n\r\nThanks for the quick response
and I will close the case now."}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/490#issue
comment-451313340"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/490#issuecom
ment-451313340",
> > "url": "https://github.com/FalconChristmas/fpp/issues/490#issuecommen
t-451313340",
