### ISSUE TITLE
Downloaded and installed FPP-v2.5-BBB-ext4 but saw 1.5.5 on boot

### ISSUE THREAD

**Issue by atairu** [FalconChristmas/fpp#491]
Downloaded FPP-v2.5-BBB-ext4.zip, formatted SD card, put image on SD card and booted up, but I got version v1.5.5. Not sure how that could happen.

Tried to update from help page but FP cannot connect to github. I am planning to use the version 2.4 to see if that will work. Any help will be appreciated.

Also how can one use the FPP-v2.5-BBB-btrfs.zip? Is there any document that I can use to install this option?

**Comment by jeffla** [comment]
It's probably still booting from flash. Did you hold down the boot button when powering on so it reads from the SD card? Also, have a series that might help if you haven't seen it. https://www.youtube.com/playlist?list=PLFyrAfJ-kKd70zujml8t3agTNJuYce92b

**Comment by atairu** [comment]
I need to watch the video. I did not hold the boot button. Guess I was just
treating this like RPi. Thanks.

**Comment by jeffla** [comment]
No worries. BBB is slightly different since it has onboard flash that the Pi doesn't.
