### ISSUE TITLE
ws2811 is not selectable in output

### ISSUE THREAD

**Issue by Emork142** [FalconChristmas/fpp#492]

**Comment by cpinkham** [comment]
It is now on it's own tab.  "Pi Pixel Strings".  The new code in FPP
v2.x support Virtual Strings and all the options that you'd normally
expect from a pixel string output.

On Sat, 2019-01-05 at 19:08 -0800, Emork142 wrote:
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"ws2811 is not selectable
in output (#492)"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/492"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/492",
> > "url": "https://github.com/FalconChristmas/fpp/issues/492",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by Emork142** [comment]
Thanks. Found it!
