### ISSUE TITLE
SSID issue with naming standard

### ISSUE THREAD

**Issue by Duramadmax** [FalconChristmas/fpp#494]
I have a pi 1 B+ that i have been having trouble getting wifi to work properly using v2.6. I also noticed that the fppd was not running.....click it and nothing. When i tried to logon via wifi, my SSID was all lowercase as per the router naming. Still would not logon to my router but the AP feature to log on via my phone via FPP (Christmas) worked fine, So I know the wifi Edimax dongle works. So I decided to put a capital first letter for the SSID, changed it in my router and wala.. It all works and fppd is now running. Does the pi have an issue with expecting the first letter to be capitalized? I know my show router and home router are capitilized but office router was not. Thought I would see if this is an issue.

**Comment by cpinkham** [comment]
FPP v2.6 is ancient and running an older OS version and network setup.  I expect this is not an issue in the new version or we would have heard about it by now.  If the problem can be recreated on a recent FPP v4.x version, we can reopen the ticket.
