### ISSUE TITLE
Upgrade to 2.6 - Doesn't see USB-mounted Drive

### ISSUE THREAD

**Issue by jeffla** [FalconChristmas/fpp#495]
Upgraded from 2.5x to 2.6. Have a Pi3B+ and USB data attached. FPPD wouldn't start after upgrade. Set External Storage Device back to boot drive, rebooted and back to USB and rebooted. All good.

**Comment by patdelaney** [comment]
Have you tested this going from 2.6 (or your current version) to 3.0 (software only update not using the new image)?

**Comment by jeffla** [comment]
No, but I can try it later this week. Is there any specific logging that might be helpful?

**Comment by dkulp** [comment]
Cannot reproduce.
