### ISSUE TITLE
Plug in control doesn't recognize previously installed plugins

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#498]
If I have plugins installed in version 2.x and change to the Master Branch, then the Installed plugins (specifically Matrix Tools and After Hours Music Player) do not show up as Installed Plugins. If I go to the Available Plugins and click on the install button, I get an error message stating that the plugin is already installed. If I go back to the 2.x branch and uninstall the plugin and then go back to the Master branch, I can install the plugin.

**Comment by cpinkham** [comment]
Closing this since we are now on FPP v3.5.x and don't support flipping back and forth between older v2.x versions that used the old plugin installer and newer FPP v3.x or master which uses the new plugin manager.  If we were going to fix this, it would have had to have been a while ago.
