### ISSUE TITLE
"&" symbol in universe name causes entire file to fail saving

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#499]
An "&" symbol in universe name field causes the whole universe config to fail saving and results in a co-universes.json file that is truncated at the bad symbol and then fails to be read.  The "&" symbol is not illegal in json.  If it's included either manually, or via a vixen export, FPP does read the file and will even display it on the universes setup page, but any save on that page causes it to truncate and corrupt the config file.

**Comment by ghormann** [comment]
@Jchuchla   Dan merged the change request for fpp web interface.  I'm not sure how Vixen import works.  If it works similar to xLights where it is a menu item in the sequencer, then it could be a bug in Vixen client.

**Comment by Jchuchla** [comment]
It actually had nothing to do with Vixen.  I just happened to notice it when doing vixen exports.  It was possible to put the "&" symbol in a universe name field right in the FPP UI, and when you hit save, it would fail to save the file.

**Comment by ghormann** [comment]
OK, then I believe this should be closed now after #503

**Comment by Jchuchla** [comment]
Great, thanks.
