### ISSUE TITLE
FPP GPIO-on and GPIO-off events trigger not working

### ISSUE THREAD

**Issue by ahallber** [FalconChristmas/fpp#500]
I have been working on setting up GPIO event triggers within FPP, using the scripts provided in FPP, to trigger relays to power up my controllers, fm transmitter, and other ancillary equipment. I have been testing with “Pin 11” (GPIO 17) on a Pi3 with version 2.6 of Falcon Player running in Stand-alone mode. 

By creating a sequence in xlights—using a DMX effect—I have been able to trigger Pin 11 on and off using the GPIO ON and OFF scripts. However, I have not been able to trigger the GPIO-on and GPIO-off scripts by setting them up in a Playlist on the Pi3—which is the ultimate goal. Some information from the test runs I did:
-	When selecting the GPIO ON-or-OFF scripts on the File Manager Scripts screen, then selecting the “Run” button, the FPP Event Screen will appear for the corresponding script, but Pin 11 will not change state. On a different note…selecting the “Reboot” script and pressing “Run” on the File Manager Scripts screen will produce the FPP Event Screen, and the FPP WILL reboot
-	On the Events Tab, when triggering the GPIO ON or OFF events that were created, then selecting the “Trigger Event” button, the Pin 11 output does not change state and the computer screen does not indicate an event occurred. Note that when the Reboot event is selected, and the “Trigger Event” button is selected on the Events Tab, the FPP WILL reboot…however, in the same vein nothing is indicated on the computer screen.
-	When trying to trigger Pin 11 with the GPIO- on and the GPIO-off scripts using the Playlist, I tried setting up the Playlist with the Playlist Entry Type configured as an Event, and then separately as a Script; and neither configuration would change the output state of Pin 11.

Not sure if I am missing something in the configuration, or if there is a disconnect in the 2.6 version software…any help is appreciated. Below are some screen shots of the configuration of the FPP…   
 
![1 gpio off script](https://user-images.githubusercontent.com/40327848/52905236-057bd800-31fd-11e9-85cd-5da26d2638c0.JPG)

![2 gpio on script](https://user-images.githubusercontent.com/40327848/52905240-0ad92280-31fd-11e9-9958-4f52718a146d.JPG)

![3 file manager-scripts screen](https://user-images.githubusercontent.com/40327848/52905244-13c9f400-31fd-11e9-9b80-7c4c5c7d0ab1.JPG)

![4 gpio on event script screen](https://user-images.githubusercontent.com/40327848/52905246-188ea800-31fd-11e9-9ef1-d85c3d7d8f13.JPG)

![5 events tab](https://user-images.githubusercontent.com/40327848/52905247-1d535c00-31fd-11e9-8955-b35944d7b6b4.JPG)

![6 gpio input triggers](https://user-images.githubusercontent.com/40327848/52905253-33f9b300-31fd-11e9-8188-bca7fd658190.JPG)

![7 playlist](https://user-images.githubusercontent.com/40327848/52905257-38be6700-31fd-11e9-8801-b7778de081cb.JPG)

![8 about fpp](https://user-images.githubusercontent.com/40327848/52905260-3e1bb180-31fd-11e9-8ec6-4cfd06acc1ab.JPG)

![9 gpio trblshoot](https://user-images.githubusercontent.com/40327848/52905261-407e0b80-31fd-11e9-9327-973549eb3fca.JPG)

**Comment by cpinkham** [comment]
Closing this ticket.  New versions of GPIO-On.sh and GPIO-Off.sh have been uploaded to the script repository.  The new versions use the "fpp -G" command to toggle GPIO instead of using wiringPi directly.  The WiringPi library caches the GPIO states in the running process, so any changes made outside of FPP are overwritten when FPP writes to the GPIO.  The "fpp -G" command performs the GPIO on/off via fppd so that the cached state in the fppd process is correct.

**Comment by ahallber** [comment]
Hello,

I looked in the script repository, and I did not see the new GPIO on and off scripts. Will they appear in a future software revision, or am I looking in the wrong place?

thank you.

**Comment by cpinkham** [comment]
They are in there, you can view the current versions of the files here:

https://github.com/FalconChristmas/fpp-scripts/tree/master/GPIO
