### ISSUE TITLE
Multisync "Advanced View" has stopped working

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#501]
Unsure when but within the last few weeks. (Master branch, currently at 215 on both)

Consistently returns a Get Status Failed for a PocketBB that previously had no problem. This is from a RasPi Master, connected via Ethernet. The PocketBB has Edimax wifi.

On the PocketBB, it doesn't successfully detect itself in Advanced, nor does it show details for the Master.

Will try with USB/Ethernet connect and see how that works.
Nope - no longer functioning with eth0 either. 
Normal mode, yes. Advanced, no.

**Comment by JonB256** [comment]
[Master_Multisyncproblem_FPP_Logs_20190228.1429.zip](https://github.com/FalconChristmas/fpp/files/2915403/Master_Multisyncproblem_FPP_Logs_20190228.1429.zip)
Log file. I erased all log files, rebooted, then enabled Most logs.
Then ran Multisync normal, then Advanced.
The PocketBB is 192.168.0.23 (eth0)

**Comment by dkulp** [comment]
I think I just fixed this.

**Comment by JonB256** [comment]
Yes, it did. Thanks.  I find this very useful when I have more than 3 FPPs running (especially master branch with its frequent updates).
