### ISSUE TITLE
Playlist:NextItem(), Playlist:PrevItem() calls Clean() when it shouldn't

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#506]
While testing the MQTT changes, I noticed that PlayList:NextItem() calls StopNow() which calls calls SetIdle() which calls Cleanup().   Cleanup will then delete all the PlaylistEntryBase records.   When control returns back to NextItem(), it tries to call Start().  Start() fails because there are no PlaylistEntryBase .   As a result, we end up in the Idle state.

Can't the call to Cleanup() in SetIdle() just be removed?  It is already called from Load(Json:Value) to prevent the memory leak.

**Comment by ghormann** [comment]
I did some further testing of and don't think Idle() should call Cleanup().   Removing caused NextItem() and PreviousItem() to work as expected.  I didn't find any other problems when testing via GUI or MQTT.  Thus, raising pull request #507

**Comment by dkulp** [comment]
This has been fixed for a wile.
