### ISSUE TITLE
Enhancement: Don't regenerate fseq's in FPP upload if nothing has changed in the fseq itself

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#511]
Just a suggestion

Is it possible in future release for FPP upload to only regenerate the V2 of a sequence that actually changed and was resaved? I have FPP upload open and about 20 sequences checked that I use, If I make a change to just one in xlights and save it, I then go to upload and it regenerates the file of all 20 again instead of just the one. I know we can select just the one we changed and uncheck the rest but I think people like keeping their main sequences checked to upload especially after weeks of some tweaks and saves. Not a big deal if this cant be done, the feature is amazing and works great, just would be a little bit of a time saver if it knew what FSEQ actually changed.

**Comment by dkulp** [comment]
This is possible, but requires some extra support from FPP as well.   The new fseq file does contain a unique ID that is created when xLights saves the file.   When we create the optimized fseq files, we keep the ID so we can compare the ID on the local machine with that on the remote and if they are different, regenerate.  However, at this point, FPP has no way to query that information without downloading the entire fseq.

**Comment by bchiaino** [comment]
gotcha, either way the feature is amazing.

**Comment by darylc** [comment]
this is an xlights feature request
