### ISSUE TITLE
Enhancement:  Add a notes field to the table on 'Other Output' config page.

### ISSUE THREAD

**Issue by SonnyJim** [FalconChristmas/fpp#518]
On this page:

http://fpp/channeloutputs.php

It would be just peachy if there was an extra field where I could write notes for each entry in the 'Other outputs' table.  Either that or being able to name each entry would make life a bit easier, as I'm always forgetting what I've setup each GPIO for.  It would function similarly to the 'description' field on the 'Pi Pixel Strings' table.

**Comment by darylc** [comment]
GPIO has a description field these days, so the specific issue here is sorted.  The generic problem is also logged in #673 Lets close this one @ghormann
