### ISSUE TITLE
Makefile issue with latest Master update ( v2.x-331-g027c34bc)

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#519]
got a file not found and makefile error at the very end (RasPi 3B+)

/usr/bin/ld: cannot find -lboost_date_time
collect2: error: ld returned 1 exit status
Makefile:413: recipe for target 'fppd' failed
make: *** [fppd] Error 1
==========================================================================
Restarting fppd...
==========================================================================
Update Complete.

**Comment by dkulp** [comment]
Yea.. I'm working on it.    Same problem on the BBB.

**Comment by JonB256** [comment]
now updates with no errors.

**Comment by cpinkham** [comment]
That's weird, I checked to make sure that library was available on a
test Pi before I committed that.  Maybe it was installed somewhere else
along the way.  Sorry about that.

On Wed, 2019-05-01 at 05:17 -0700, JonB256 wrote:
> Closed #519.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://github.githubassets.com/images/
email/message_cards/header.png","avatar_image_url":"https://github.gi
thubassets.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"Closed
#519."}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/519#event
-2311749792"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/519#event-23
11749792",
> > "url": "https://github.com/FalconChristmas/fpp/issues/519#event-23117
49792",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]
