### ISSUE TITLE
Import xLights network config

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#52]
Per a request on the forums: http://falconchristmas.com/forum/index.php/topic,789.msg6515.html#msg6515

The xlights_network.xml describes xLights' E1.31 output and could be easily imported to FPP's universes setup.  We should do this at some point.

**Comment by cpinkham** [comment]
Chris Debenham has added code to xLights to export the universes file and upload it to FPP via FTP.  Future changes will be done via the API which is being added for FPP v2.0.  Closing this ticket.
