### ISSUE TITLE
F16-B unsupported error

### ISSUE THREAD

**Issue by rubbaband** [FalconChristmas/fpp#520]
Just updated to the most recent version 2.7 for an older F16-B I still use and under the BBB strings page I am getting an error about an unsupported cape and outputs being limited?

**Comment by dkulp** [comment]
Can you login to the command line and run "sudo i2cdetect -y -r 2" and post the output?  Have you made any modification to the F16-B or is it completely "stock"?

**Comment by rubbaband** [comment]
Ok I can do that when I get a new BBB, I stupidly stepped on it and it won't power up now. Only thing I have done is soldered an led screen to it. It worked fine when I was on the previous master version.

**Comment by dkulp** [comment]
Please contact me via PM on falconchristmas to discuss options, but this is not something we will be changing/fixing in the short term.
