### ISSUE TITLE
Bug: CLI Volume control not saved after reboot

### ISSUE THREAD

**Issue by eliosm** [FalconChristmas/fpp#522]
### Description
CLI command `fpp -v` is working just fine.
The problem is that it isn't saved after reboot. It is saved only if changed with web interface slider.

### Example
1. Boot up -> Volume is at 15%
2. `fpp -v 50` -> Volume is changed to 50%
3. Reboot -> Volume got back to 15%

### Specs
Host: Raspberry Pi 3 B+
FPP Version & Branch: 2.7

**Comment by ghormann** [comment]
Looking at he code, I think it is working as designed.   It specifically just does a run time set of the volume and doesn't reference the configuration.    @dkulp  or @cpinkham  would need to confirm the design intent.

**Comment by cpinkham** [comment]
This is by intent.  If you want to manipulate the volume via the command line and save the value, you can use a command similar to this:

curl 'http://127.0.0.1/fppxml.php?command=setVolume&volume=85'

That will adjust the volume and save the new value to the settings file.  At some point, we will probably move this to the REST API and the 'fpp' helper will just call the API.
