### ISSUE TITLE
FPP Buster network utilities are missing from base image

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#523]
Testing a Debian Buster VM (net-install) the following utilities are missing:

ifconfig
iwconfig
netstat
sudo

This breaks Help -> Troubleshooting

**Comment by dkulp** [comment]
Not sure if this is still an issue.    sudo, net-tools, and wireless-tools are in the PACKAGE_LIST of stuff to be installed in FPP_Install.sh so they should be installed.
