### ISSUE TITLE
Untitled Playlist

### ISSUE THREAD

**Issue by kmacmaster** [FalconChristmas/fpp#526]
If you press the save button on the playlist screen, and nothing is in the title, it will save a blank titled playlist that you cannot delete or edit. Probably should not allow a save unless there is a name for the playlist.

**Comment by patdelaney** [comment]
This rings a bell, I think it was an issue in older versions as well. I
think the workaround is to edit the playlist file manually and remove the
entry from the playlist json file.

Pat

**Comment by kmacmaster** [comment]
Yeah, figured that part out quick.... Other's maybe not.

**Comment by dkulp** [comment]
Fixed... gives an alert now.
