### ISSUE TITLE
increase gpu_mem to help omxplayer issues

### ISSUE THREAD

**Issue by MarkAAmber** [FalconChristmas/fpp#528]
This info comes from https://kb.gosi.at/content/43/152/en/how-to-fix-comxaudiodecode-timeout-in-omxplayer.html.
Several people have testing this modification with positive results.  
Request to update the image builds to include the line gpu_mem=128 in /boot/config.txt

How to fix "COMXAudio::Decode timeout" in omxplayer?
This is a common problem with default settings on the Raspberry Pi.
The issue is a result of too little GPU memory, to fix this, you can adjust that value to 128MB.
You can find that value: /boot/config.txt
gpu_mem=128

**Comment by dkulp** [comment]
even with 128, we're still getting the error.  Just takes longer.    Need to figure out the real problem.

**Comment by MarkAAmber** [comment]
I agree its a band-aid but it helps run longer and I don't think it hurts anything

**Comment by dkulp** [comment]
This will be done with the buster images once we flush out the rest of the needed Pi4 changes
