### ISSUE TITLE
Virtual matrix displaying incorrectly

### ISSUE THREAD

**Issue by markphelan** [FalconChristmas/fpp#529]
When enabled the login prompt still shows, even when Force HDMI and screen blanking are enabled. My scrolling text also looks like this:
![IMG_0471](https://user-images.githubusercontent.com/2466933/60760043-77c34c80-a026-11e9-9d14-1e11fa47af68.jpeg)

Test pattern looks OK from FPP, but when I stop outputting data the 'smeared' text remains on screen. Running v2.7, matrix configured as 64x32 across 9 universes. FPP set for Bridge Mode. Does the same on Pi Zero and Pi 3, and also gives same display on screen when running in standalone player mode with fseq uploaded.

**Comment by patdelaney** [comment]
can you push the fseq to the pi and run it locally?  If it works it will
rule out bridge mode issues


Pat

**Comment by markphelan** [comment]
I tried that too in case it was network related and it behaves the same

**Comment by dkulp** [comment]
Can you login to the command line and run "sudo tvservice -o" and then "sudo tvservice -p" and then try running your sequences and such?

**Comment by markphelan** [comment]
Screen went completely blank and didn't show any output at all. When I restarted FPPD it was back to doing the same thing again - showing a very large login prompt with my matrix text dragged across it without clearing down.

**Comment by dkulp** [comment]
This might now be fixed on master.   While trying to test, I've discovered none of the framebuffer outputs work with the Pi4.  :(

**Comment by markphelan** [comment]
How do I revert back to master to try it? Currently shows I'm on 2.7.2 branch.

**Comment by dkulp** [comment]
Go to the "/developer.php" page on the Pi and select "master" from the drop down list.   Then wait a LONG time.

**Comment by markphelan** [comment]
And so the wait begins! :smile:

**Comment by markphelan** [comment]
Yep, that works better - thanks!
