### ISSUE TITLE
Request: run FPP with read-only file system

### ISSUE THREAD

**Issue by SteveGase** [FalconChristmas/fpp#53]
One of the issues that Raspberry Pi has is the risk of power outages and corruption of the file system.

What if the Pi switched automatically to read-only file systems after changes to configuration are applied...  it might be necessary to move all configuration settings and content to a separate file system...  when the changes are made the show is stopped/suspended -- the file system is mounted read/write -- changes applied -- the file system is mounted read/only -- the show is resumed.

The OS and the system would be on a file system consistently mounted read-only.

Logs and diagnostic info could be mounted on a file system that read/write all the time -- and regularly backed up to yet another file system.  When the system boots it could reformat the log space -- just in case it ever is left in a bad state due to loss of power.

I'm sure there are other solutions, but I supply one possible solution to illustrate the options of keeping the file systems in robust condition even if power is lost.  (the risk of power loss during a config change might be considered acceptable...)

**Comment by cpinkham** [comment]
This is now possible using a script in the script repository.  I'd like to merge that script into FPP v2.0 at least as an option for users.

**Comment by skulltronix** [comment]
Do you have a link to that script?  Thanks. If you can.. text to 9166002295

**Comment by rawcreative** [comment]
It is the very last script on the Script Repository Browser page in the FPP ui.  It's called: ConvertPiRootToReadOnly.sh

**Comment by skulltronix** [comment]
Thanks!  I did find it but haven't had the courage to try it yet.  I need to backup/copy the sd card first. 

I'm using the rpi fpp to control home lighting and want it to be reliable. 

Best regards!

Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by cpinkham** [comment]
Closing this as FPP has changed so much, this may be harder to do, but it is also a lot more stable, so may be unnecessary after the changes in Raspbian.  The current R/O script needs to be rewritten or deleted because it does not work with current FPP releases on the newer Raspbian.
