### ISSUE TITLE
Initial boot of 2.7.2 does not display IP address on UI after booting

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#530]
I installed the image on a PI v3 with network cable attached and after boot up I thought I would see the DHCP address that it was given on the console screen. At least it used to do that in the past. It did announce it however.

I also disconnected the network cable and rebooted. The Pi did not display the IP address on the console ui and it did not not announce it. It did go into tethering mode and I was able to connect to it to set it up.

Versions in the past displayed the IP address on the console UI. Is this a new issue or by design?

**Comment by jeffla** [comment]
@patdelaney I ran across this when installing earlier 2.x images (https://youtu.be/kn1BiolQbgw?t=606). Not sure if it's a stretch thing or what. It seems to act differently on different hardware. A quick Google search didn't reveal anything.

**Comment by dkulp** [comment]
It's completely dependent on how fast the dhcp server responds and how fast the Pi boots.   On the newer Pi's, they boot so fast that it gets to the login console before the dhcp server responds and thus the IP address is not displayed.   So kind of a stretch/buster thing.   They prioritize getting things up and running as fast as possible.

**Comment by dkulp** [comment]
With 3.2 (and more changes in 3.3) I'm attempting to delay starting FPPD until after this is displayed, but it's not guaranteed due to the async nature of the Stretch/Buster boot process.
