### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by dszoka** [FalconChristmas/fpp#535]
Was helping out Zack Marker on zoom, noticed that when viewing falcon V3 via proxy it wasn’t showing E131 info or string ports, when connected directly no problems..

Now this could have been Zacks router as it was causing issues too..

Just bringing it up just in case

**Comment by dkulp** [comment]
I believe this is solved in the newer firmwares for the F#v3 controllers.   Particularly the new 2.5 version are tested and work well.   My suggestion it to make sure to upgrade to the latest firmware (with the smart receiver support) and see if the problem persists.
