### ISSUE TITLE
Channel Outputs BBB String Ouputs Cape Version Selector Doesn't Update

### ISSUE THREAD

**Issue by computergeek1507** [FalconChristmas/fpp#537]
If I change the Version Selector Dropdown, the page with initially change the version to 2.x if selected and the BBB Outputs will work as expected. But then when I reload the webpage it will display the version as 1.x still.

![image](https://user-images.githubusercontent.com/2293065/62015468-ddb07900-b179-11e9-90c6-56273c0bd0b5.png)

![image](https://user-images.githubusercontent.com/2293065/62015442-ab068080-b179-11e9-994d-285c7130eac0.png)

**Comment by dkulp** [comment]
Umm.... you shouldn't even see that drop down.   That's not good.   Is my logo up in the right corner?

**Comment by dkulp** [comment]
Can you go to the troubleshooting tab and see what prints out for the "i2cdetect" section?

**Comment by computergeek1507** [comment]
i2cdetect:    sudo i2cdetect -y -r 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- UU UU UU UU -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by computergeek1507** [comment]
![image](https://user-images.githubusercontent.com/2293065/62017817-19514000-b186-11e9-9230-bc7e859513b6.png)

It is a BBB Green if that matters

**Comment by dkulp** [comment]
Did this end up resolving itself?   I haven't been able to reproduce it.  :(
