### ISSUE TITLE
FPP didn't like me adding 672 universes to the e131 tab

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#539]
This issue was reports by Nathan Miller on Facebook, my observations to follow.
Pat said---
I was on Master Branch, yes it does seem to hang when trying to do 674 in one batch. But here is the work around ... First set it up for 400 universes. Wait until it redraws the screen and displays 400, then change it to 674. It should work, because it's just adding 274 to the already 400. By using that method I got to 700.

**Comment by dkulp** [comment]
With 3.0, both Safari and Chrome allowed me to enter 999 and it eventually worked.   Safari was much faster, but it worked.   Takes about 35 seconds on my computer on Safari to add 800 universes.   About 1:41 with Chrome.
