### ISSUE TITLE
Big Buttons plugin only working when "&nopage=1" removed from URL

### ISSUE THREAD

**Issue by vcuncg** [FalconChristmas/fpp#540]
I am finding that in 3.0 the "Big Buttons" plugin is only working when the header is displayed by removing "&nopage=1" form the URL.  When this is in the URL, the buttons are not clickable.  Once this is removed and the header shows, the buttons work.  If this is a user error, let me know.  I could not get it to work otherwise.

Not working:
http://x.x.x.x/plugin.php?plugin=fpp-BigButtons&page=bigbuttons.php&nopage=1

Working, but shows header:
http://x.x.x.x/plugin.php?plugin=fpp-BigButtons&page=bigbuttons.php

**Comment by dkulp** [comment]
Just fixed... change needed in the big buttons plugin.  If you uninstall and reinstall the big buttons plugin, I believe it will work.

**Comment by vcuncg** [comment]
Wow, that was quick!  It is working perfectly now.  Thanks for the update.
