### ISSUE TITLE
Fpp 2.7  Triggering a Event that contains an audio only media file on BBG crashed fppd.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#542]
While testing the GPIO stuff, I was creating playlists and events on a BBG. I installed a USB audio dongle.
I created 4 playlists with a single mp3 audio file.
I created 4 "start playlist" scripts based on the sample in script repository.
I created 4 events, one for each script file.

When I try and trigger the event from the Events UI (trigger Event) FPPD stops.

Troubleshooting:
I ssh'd into the BBG and navigated to the scripts directory and I was able to manually launch each script file.  

I created a sequence only playlist and assigned it to an event and that worked as it should.
I added an audio/sequence as the second entry on the playlist and that played as expected.
I created a play list with the first entry just containing an MP3 and the second item as sequence and mp3.

Conclusion:  If the first entry in the playlist is an MP3 and no fseq sequence, then FPPD will stop when that playlist is called from a script by an Event.

**Comment by darylc** [comment]
Does this still occur in master?

**Comment by patdelaney** [comment]
@darylc I can re-test in master and let you know.

**Comment by darylc** [comment]
@patdelaney  How did you go?

**Comment by patdelaney** [comment]
I can check but this was 2.7 LOL

**Comment by darylc** [comment]
@patdelaney I'm OK if you prefer to close it.

**Comment by patdelaney** [comment]
We can close it since we no longer support events, I believe it was fixed
before anyway
