### ISSUE TITLE
3.1 upgrade not seeing USB thumbdrive

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#544]
After doing the 3.0 update then performing the 3.1 upgrade it no longer sees the usb external storage device in the FPP settings page.
Going to reflash the OS sd card and try again.

**Comment by dkulp** [comment]
Not able to reproduce.

**Comment by jeffla** [comment]
@derwin12 I've noticed this on some upgrades too. Just go into FPP settings and re-select it and it sticks.
