### ISSUE TITLE
FPP doesn't properly handle special characters in SSID and PSK

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#553]
FPP doesn't properly handle special characters in WiFi settings (SSID/PSK), this bug exists at least in versions 2.7.2, 3.1, 3.2, that I tested.

This is what happened when I tried to set up a passphrase "abc$def" via the UI - it got stripped off in the fpp.config, and obviously wasn't connecting to the WiFi access point:

```
root@FPP:/home/fpp# grep PSK /home/fpp/media/config/interface.wlan0
PSK="abc$def"
root@FPP:/home/fpp# grep Passphrase /var/lib/connman/fpp.config
Passphrase=abc
root@FPP:/home/fpp#
```

The solution is to replace escaped double quotes in the following code with single quotes in /opt/fpp/www/fppjson.php :

**Old code:**
```
	if (substr($data['INTERFACE'], 0, 4) == "wlan")
	{
		fprintf($f,
-			"SSID=\"%s\"\n" .
-			"PSK=\"%s\"\n" .
            "HIDDEN=%s\n",
			$data['SSID'], $data['PSK'], $data['Hidden']);
	}
```

**New code:**
```
	if (substr($data['INTERFACE'], 0, 4) == "wlan")
	{
		fprintf($f,
+			"SSID='%s'\n" .
+			"PSK='%s'\n" .
            "HIDDEN=%s\n",
			$data['SSID'], $data['PSK'], $data['Hidden']);
	}
```

Tested this fix on two Raspberry Pi 3 and 3B+ boards running FPP 3.2

**Comment by cpinkham** [comment]
This was fixed in 2014 in d766dde5a4bbe709390cd11e6fd89937e2be2b44 and
then broken earlier this year when
a0d97efd5f46e3d842a42ba20c7326cb9384a5d0 reverted the original change.

Personally, I'm on the fence.  I think that switching the config to
JSON like we have with other config files is the real solution, but
currently either way if we use single or double quotes, there are some
characters that can't be used in the values.

Waiting for others to chime in....

On Thu, 2019-09-05 at 15:41 -0700, Vlad-Star wrote:
> > > FPP doesn't properly handle special characters in WiFi settings
(SSID/PSK), this bug exists at least in versions 2.7.2, 3.1, 3.2,
that I tested.
> > > This is what happened when I tried to set up a passphrase "abc$def"
via the UI - it got stripped off in the fpp.config, and obviously
wasn't connecting to the WiFi access point:
> root@FPP:/home/fpp# grep PSK /home/fpp/media/config/interface.wlan0
> PSK="abc$def"
> root@FPP:/home/fpp# grep Passphrase /var/lib/connman/fpp.config
> Passphrase=abc
> root@FPP:/home/fpp#
> 
> > The solution is to replace double quotes in the following code with
single quotes in /opt/fpp/www/fppjson.php :
> Old code:
> 	if (substr($data['INTERFACE'], 0, 4) == "wlan")
> 	{
> > 		fprintf($f,
> > -			"SSID=\"%s\"\n" .
> > -			"PSK=\"%s\"\n" .
>             "HIDDEN=%s\n",
> > 			$data['SSID'], $data['PSK'], $data['Hidden']);
> 	}
> 
> New code:
> 	if (substr($data['INTERFACE'], 0, 4) == "wlan")
> 	{
> > 		fprintf($f,
> > +			"SSID='%s'\n" .
> > +			"PSK='%s'\n" .
>             "HIDDEN=%s\n",
> > 			$data['SSID'], $data['PSK'], $data['Hidden']);
> 	}
> 
> Tested this fix on two Raspberry Pi 3B+ boards running FPP 3.2
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > > "target": "https://github.com/FalconChristmas/fpp/issues/553?email_so
urce=notifications\u0026email_token=AADT72DLFVWZD2C3DPXNOTTQIGDIVA5CN
FSM4IUDGBW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HJVOUYQ",
> > > "url": "https://github.com/FalconChristmas/fpp/issues/553?email_sourc
e=notifications\u0026email_token=AADT72DLFVWZD2C3DPXNOTTQIGDIVA5CNFSM
4IUDGBW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HJVOUYQ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by Vlad-Star** [comment]
Let me start with that I am sysadmin, familiar with Bash and used to do PHP programming in the past. 

It's all about special characters (like "$") that are technically allowed in SSID and/or passphrase. I have traced the code to find out why it's wasn't working for me without a manual modification of /etc/wpa_supplicant/wpa_supplicant.conf file, and it turned out to be due to "$" character present in my WiFi passphrase.

Here is my findings:
1) When you on Network page click on "Update Interface" button, it calls SaveNetworkConfig() function from "www/networking.php" (calling fppjson.php with command=setInterfaceInfo parameter to save WiFi information to the media/config/interface.wlan0 file)
2) When you click on "Restart Network" it calls ApplyNetworkConf() function from "www/networking.php" (calling fppjson.php with command=applyInterfaceInfo parameter, which calls out "scripts/config_network" bash script)
3) "scripts/config_network" Bash script reads the "scripts/functions" file calls out "SetupFPPNetworkConfig" procedure, which finds "connman" binary and calls out "SetupFPPNetworkConfigViaConnMann" procedure.
4) The latter procedure has the following code:
`
. ${f}
`
to set up variables. Bash tries to substitute every variable it finds in double quotes (which is prefixed with "$" character), but leaves alone everything in single quotes. This is where my suggestion came from, that the original values in "interface.wlan0" file must be in single quotes. 

Given this info, I'll let you decide on the exact action how to fix the problem.

**Comment by Vlad-Star** [comment]
Sorry, occasionally clicked on the wrong button, reopening it.

**Comment by Vlad-Star** [comment]
Also, just wanted to add that the proper way to escape/restore special characters in PHP would be to use addslashes() and stripslashes() functions, from Bash prospective - to use single quotes.

**Comment by libby2cm** [comment]
just to pile on, i'd like to see this fixed.. threw me for a loop for a couple of hours earlier this year until i saw what was happening.

**Comment by Vlad-Star** [comment]
Just installed fresh FPP 3.4 and upgraded to 3.5.5. 
1) It still doesn't work with special chars. Everything after "$" char in PSK= line gets stripped while creating /var/tmp/fpp.config file

```
### Added SSID and PSK to wlan0 interface, clicked "Update Interface" button
root@FPP:/home/fpp# cat /home/fpp/media/config/interface.wlan0
INTERFACE=wlan0
PROTO=dhcp
SSID="MYSSID"
PSK="abc$def"
HIDDEN=
root@FPP:/home/fpp#

### clicked "Restart Network" button
root@FPP:/home/fpp# ls -l /var/tmp/fpp.config
ls: cannot access '/var/tmp/fpp.config': No such file or directory
root@FPP:/home/fpp#

### rebooted the FPP
root@FPP-206:/opt/fpp/www# cat /var/tmp/fpp.config
[service_wlan0]
Name=MYSSID
Security=psk
Passphrase=abc
Type=wifi
IPv4=dhcp
MAC=74:da:38:8d:16:1e
```

2) "Restart Network" button doesn't generate /var/tmp/fpp.config file at all
