### ISSUE TITLE
Raspberry Pi GPIO PWM 

### ISSUE THREAD

**Issue by BluePuffinC** [FalconChristmas/fpp#557]
As of FPP version 3.x, GPIO PWM output does not work on a Raspberry Pi. When you select PWM for a GPIO output, the pin no longer outputs anything. When PWM is unchecked the output works fine. I am guessing this issue is likely caused by the upgrade to Rasbian Buster, and the PWM library may be outdated.

**Comment by cscool36** [comment]
Using P3B+ with Ver 3.2. I can not get the GPIO outputs working in the scripts. All working in fine V1.9 on a P2B+. I can trigger in the events page.
Do I need to setup GPIO as an output?
