### ISSUE TITLE
test display from doesnt work

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#558]
enable test display on master doesnt work. if you test a sequence from master remotes work. Can test in test display on each remote they work. just not from master.

**Comment by cpinkham** [comment]
The Channel Tester screen only tests the Channel Outputs on the FPP system you are connected to, it does not turn on all channels on all FPP instances.

For playing sequences, in FPP v4.0, you will be able to select a sequence from the FPP File Manager and play that sequence along with its audio file without having to create a playlist, so you won't have to do this from the test page unless you need the ability to pause the sequence during playback.
