### ISSUE TITLE
REQUEST: master restart fppd button

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#559]
This is just a request or improvement if you want this removed tell me and i will delete it. When using master/remotes can a button be added to resend out command to restart all remote fppds. so that when you upload anything from xlights via fpp connect all that needs done to go to master and push button to restart all fppd. instead of having to go to each controller web page and restart fppd. maybe put button in multisync.

**Comment by dkulp** [comment]
Ideally (and something I've started working on) FPP Connect would detect when it needs to restart the FPPD instance and it would send the restart as part of the stuff is does.

**Comment by cpinkham** [comment]
I am looking at adding a button to do this as part of the changes being worked on for the MultiSync page.
