### ISSUE TITLE
Hitting "stop" on a playing sequence does not turn the lights off

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#561]
Is there a way to have FPP shut the lights off if I stop a sequence in the middle. I am testing out a few sequences and I notice if I hit stop during it to go do something else, all the lights stay on (paused) because they were playing. I know with XSchedule if I click stop, it also kills all the lights outside instead of "pausing" the lights like FPP does. thanks!

Video of it happening - https://youtu.be/e-0vO7DTM4I

**Comment by patdelaney** [comment]
Did you try  Blank between sequences:  in the FPP settings page?

Pat

**Comment by bchiaino** [comment]
I believe i did, i tried a bunch of changes to test, Ill try that again tonight and see if it makes a difference

**Comment by dkulp** [comment]
I believe I just fixed this on master, but I'm in Morocco without any lights or beagles or anything (just docker) so I'm not really sure.   If folks could test, that would be awesome.

**Comment by bchiaino** [comment]
Awesome thanks! ill check it out and report back when I get home in a few hours

**Comment by bchiaino** [comment]
Looks good Daniel, tested it a few times and the lights turned off when I pressed stop, thanks!

**Comment by bchiaino** [comment]
this was fixed but now in  v3.x-master-167-ga31ccf31 (master branch)  its back to not working right., When I hit stop the lights just freeze as you can see in the video but then FPPD just stopped working, I restart and then the stop button works as it should

https://youtu.be/xAkgNmza-pE
