### ISSUE TITLE
Show playing track up top or bottom on main page?

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#564]
Is it possible to have the sequence that's playing be on the main page at top or bottom? Reason I ask it I have this showing on a screen I remote into and like to glance from time to time to see what's playing, if I have a sequence playing that's down the list of what can be displayed, I don't know what track is playing. I don't always have a mouse Hooke up to it been its just to see. a playlist going. If its a big deal then no worries, was just curious, thanks as always!!
![71533414_2284542148310660_5440185544833236992_n](https://user-images.githubusercontent.com/40632971/66398771-5d459a00-e9ac-11e9-9815-d8958425daf0.png)

**Comment by cpinkham** [comment]
Click on the "Switch to Compact Status UI" link beside the FPPD Mode
dropdown and you will get a more compact version of the UI which by
default only shows the current item.  It's what I normally use when
controlling FPP from my yard to play test sequences as I am setting up
lights.

On Tue, 2019-10-08 at 06:16 -0700, bchiaino wrote:
> > > > > > > > Is it possible to have the sequence that's playing be on the main
page at top or bottom? Reason I ask it I have this showing on a
screen I remote into and like to glance from time to time to see
what's playing, if I have a sequence playing that's down the list of
what can be displayed, I don't know what track is playing. I don't
always have a mouse Hooke up to it been its just to see. a playlist
going. If its a big deal then no worries, was just curious, thanks as
always!!
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > > "target": "https://github.com/FalconChristmas/fpp/issues/564?email_so
urce=notifications\u0026email_token=AADT72HGT4SJ4JSNESGGJKDQNSB4PA5CN
FSM4I6RTS42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQLANLQ",
> > > "url": "https://github.com/FalconChristmas/fpp/issues/564?email_sourc
e=notifications\u0026email_token=AADT72HGT4SJ4JSNESGGJKDQNSB4PA5CNFSM
4I6RTS42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQLANLQ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by cpinkham** [comment]
Sorry, I thought I had it so that it showed the media/sequence on the
"Player:" line, but I just double checked and it doesn't.  I must have
forgotten that since my main use was to play single sequence playlists
for testing.

On Tue, 2019-10-08 at 14:38 +0000, bchiaino wrote:
> > I tried that but its still not showing the current track playing,
just the current playlist
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > > > "target": "https://github.com/FalconChristmas/fpp/issues/564?email_so
urce=notifications\u0026email_token=AADT72G7ZKXYQA6W7L3V4VLQNSLNTA5CN
FSM4I6RTS42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZ
GOEAUMZMI#issuecomment-539544753",
> > > > "url": "https://github.com/FalconChristmas/fpp/issues/564?email_sourc
e=notifications\u0026email_token=AADT72G7ZKXYQA6W7L3V4VLQNSLNTA5CNFSM
4I6RTS42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOE
AUMZMI#issuecomment-539544753",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by bchiaino** [comment]
no problem, thanks for looking, maybe in a future release we will see something added.
