### ISSUE TITLE
3.3 (Master) One Pi plays FSEQ really slow sometimes

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#565]
I noticed after I used Xlights and uploaded all my sequences using V2Sparse that my Matrix 1 pi (all the way to the left in video) sometimes plays a FSEQ REALLY slow, like 1 second plays of the FSEQ every minute that goes by. you can see in the video towards the end in this case that Frozen once I load the sequence plays fine on my show Pi (middle of screen) and Matrix 2 (right of screen in video)  which are different channels then Matrix 1 but Matrix 1 totally ignores any more info from the show Pi, Matrix 1 Pi plays Frozen incredibly slow and even if I change sequences on the show player Pi 1 ignores it and still continues to play Frozen slow

here's a video. - https://youtu.be/YDpF477bSQg

here are all my log files and the Frozen FSEQ if you need - https://drive.google.com/file/d/1miDsteTBNUIw5jcNCw5KICYbbf6lzGRr/view?usp=sharing

seems very easy to reproduce on mine Pi. Im copying the FSEQ over now without using the FPP connect to see if its that causing some kind of an issue on upload

EDIT - This happens on both Matrix Pi's on master branch, not just Pi Matrix 1, Matrix 1 and 2 are remote pi's

**Comment by bchiaino** [comment]
also in this video you can see in the master branch the matrix pi for my video takes a while to start the FSEQ and then syncs to the correct time, I start a sequence on the show pi and it starts right away but the matrix Pi's are frozen and then jump into real time like 10 seconds later, once I go to the developer page and switch to 3.2 or 3.3 they play fine

https://youtu.be/cIp2rVyA4FI

**Comment by patdelaney** [comment]
I'm not sure if you mentioned it, but are all the Pi's the same ie. v2
or v3 and do they all have the same storage (micro SD card) type?

**Comment by bchiaino** [comment]
Hey Pat! 

at first i uploaded from XLights FPP connect using V2 to the player Pi and V2sparse to my remotes for the screens. I alos tested just using V2's copied over manually not using FPP connect and got the same results.

the SD cards are all the same class 10 samsung 32gb 

This doesnt happen on 3.3, only seems to happen once i switch to the "master" branch for the latest updates. 

the slow loading of the tracks on the remotes happens only in "master" branch also. I made a video in the second post above showing that issue also

**Comment by bchiaino** [comment]
im not sure how to update to individual updates on the master to see which one of these cause the issue
<img width="1223" alt="Screen Shot 2019-10-09 at 7 53 41 AM" src="https://user-images.githubusercontent.com/40632971/66479164-f1296b80-ea69-11e9-9cff-589b38b2aed2.png">

**Comment by patdelaney** [comment]
To be clear ... are all the physical Pis the same type? (B, B+, Bv2, Bv3,
Bv4

Although it does sound like you narrowed it done a little.

**Comment by bchiaino** [comment]
yes, all 3 are 3B+

**Comment by dkulp** [comment]
I think this may now be fixed... Can you verify?

**Comment by bchiaino** [comment]
absolutely, I am at work and remoted in by my master pi is locked up for some reason, i can ping it but the interface freezes, lol... I think it needs a reboot, once im home ill reboot it

Can i send a CURL command to force reboot the master Pi?

**Comment by bchiaino** [comment]
so far so goo Daniel, Ill open it back up if it slows down after further testing
