### ISSUE TITLE
FPP 3.3 in Remote mode with configured VirtualMatrix doesn't blank the screen on boot

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#567]
FPP 3.3 in Player (remote mode) with configured VirtualMatrix doesn't blank the screen on FPP boot - shows the login prompt. It blanks the screen when manually switched to Bridge and then back to Remote mode.

*** Maybe related to the Issue #554

**Comment by dkulp** [comment]
Is "Blank screen on startup" checkbox turned on on the settings page?   If not, this is working as designed.

**Comment by Vlad-Star** [comment]
Sorry, indeed it was not checked, my bad. Too many recent re-installations :) so I missed the obvious. Thank you for the hint, closing the issue.
