### ISSUE TITLE
Web UI place sequence before the song mp3?

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#569]
When using the playlist screen seems like it would make more sense to list the sequence title first rather than the mp3 song title in the first column. Realize in a few cases they maybe the same but we work with sequence names way more then we work with song (titles).

**Comment by dkulp** [comment]
Done on master.  Also, when selecting the fseq file, it will query the media file name stored in the fseq header and populate the media drop down with the appropriate song automatically.
