### ISSUE TITLE
Enhancement: Add fast forward or "jump 10 second" button/plugin

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#570]
Is there a way to add a way to jump in a track like 10 second jumps or a fast forward button? Some sequences as we test i want to see if i fixed a spot lets say like 4 minutes into a track, would be cool to be able to fast forward to that point to see the 1 part you want vs having to watch the entire track again 

thanks!

**Comment by darylc** [comment]
The FPP development team met and decided that similar outcomes can be achieved through the display testing page where you can chose where to start a sequence at a particular time.

![image](https://user-images.githubusercontent.com/7511887/215242035-8570ccda-a3a8-40b4-b3a4-fefe355f44c3.png)
