### ISSUE TITLE
fppd stops (crashes) when you outputs are disabled and you start a sequence.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#572]
![image](https://user-images.githubusercontent.com/8147459/67342523-01c0f380-f4f8-11e9-944e-805cffe2e163.png)

Steps to reproduce:
Configure several E1.31 outputs in your FPP (Pi)
Save configuration
Restart FPPD
Play a sequence ( all is good )

Stop the sequence
go to outputs page and uncheck "Active" on 2 line. (see example)
Save configuration
Restart FPPD
Play a sequence and then FPPD crashes.

The sequence does not have any props configured on those channels.
I don't think it should crash FPPD.

I see nothing out of the ordinary in the logs.

**Comment by dkulp** [comment]
I cannot reproduce this.  :(

**Comment by patdelaney** [comment]
I can reliably make it happen on my system, I will try and reproduce it on
a test Pi.   It may be a combination of the sequence and I also have
overlays defined.  I get home around noon.
