### ISSUE TITLE
FPP not reachable after new install from 192.168.7.0/24 network

### ISSUE THREAD

**Issue by caseynielson** [FalconChristmas/fpp#574]
A new install (3.3 img to sd card via etcher) not reachable from 192.168.7.0/24 network.
My home network is configured for 192.168.7.0/24, it seems this is the same network chosen for the USB tethering capability (192.168.7.2/24).
ifconfig shows no-carrier for usb0 but the OS still attempts to use usb0 for any traffic destined for 192.168.7.0/24. In my case I had a static assignment set for the pi's mac address for 192.168.7.41. It took a while to figure out why the fpp was not reachable. Downing usb0 restores connectivity (sudo ifconfig usb0 down) but this is a rough hack. I would think there would be a way to disable usb0 if the tethering feature was not used. I realize I may be the edge case that happened to pick the same range used for the feature but wanted to log the issue.
One work-around to reach fpp without connecting a keyboard/monitor is to use IPv6 (if you can determine it's link-local address), this won't help with the connectivity problems for pixel controller or other devices on the 192.168.7.0/24 ipv4 network but it will allow access to fpp in order to disable usb0.

**Comment by dkulp** [comment]
As an FYI, this is not likely to change anytime soon.   The BBB images that FPP is based on use 192.168.6.x and 192.168.7.x for various USB tethering things with no easy way to disable.   The FPP 3.x images add 192.168.8.x onto that for the wifi tethering.     Thus, I do not expect things to work very well on any of those three subnets.

**Comment by fullsaildan** [comment]
Can I get some help figuring out the best way to fix this? I run an eero network and it automatically sets the default subnet to .7. 

Can I permanently disable the usb tethering? I'm hesitant to play with my network as literally dozens of devices are configured to static IPs

**Comment by fullsaildan** [comment]
Managed to change my routers subnet to fix this. Unfortunately this will mean anyone running an eero network will need to do the same since they default to 192.168.7.x

**Comment by jmaddox1** [comment]
This is really unfortunate, as I have an eero network with well over 60 devices on it.  PLEASE consider this for the future.  This is going to take me at least a week to get everything migrated over to a new subnet.  With Amazon now owning Eero and prices dropping every day, I'm sure this will effect many users out there in the future.

**Comment by bigwavedave42** [comment]
This is definitely a tricky situation, as lots of different consumer equipment chooses:
192.168.1.x or 192.168. 0.x
I've also seen some that do 192.168.254.x
Now Eero seems to be using 192.168.7.x 

Doing a quick Google search helped me find a list of common ranges different vendors use:
https://www.techspot.com/guides/287-default-router-ip-addresses/

You'll see that they are all over the 192.168.x.x range.  Trying to find something that won't get in the way somewhere is going to be difficult.  I would think IF someone were to take on this endeavor, it might be worth considering using the 172.16/12 ( another portion of RFC 1918) range, or consider something like the RFC 6598 range.  I would expect those to be less likely to conflict with peoples systems.

**Comment by perlsteve** [comment]
Alright, I know this is a bit of an old thread; however, I have a 192.168.7.0/24 network and there is no way I am re-doing that setup. 

Good news is that I found where this is set, and as long as you don't flash a new version it does remediate the issue:

Open **/opt/fpp/scripts/functions** with your favorite editor, and in the first function (AttemptCreateSoftAP()), you will see the offending section:
`if  [ "${FPPPLATFORM}" = "Raspberry Pi" ]; then
        modprobe g_ether iManufacturer="FPP-Tether" iProduct="FPP-Tether"
        ls /sys/class/net/
        if [ -e "/sys/class/net/usb0" ]; then
            ifconfig usb0 192.168.7.2 netmask 255.255.255.0
        fi
    fi`

What's working for me is changing 7.2 to 8.2. This survives reboots, and doesn't mess with my home network.

TBH this should be something that should be configurable/toggle for those that do not require this feature. 

Understand that this may break other things, so YMMV with this change.

**Comment by caseynielson** [comment]
It's not really practical for me to renumber my home network (192.168.7.0) so I moved my pixel controllers and FPPs to a 10.x.x.x network (separate nic on firewall). Its pretty safe to assume that I'll always have another instance on the 10 network that I can tunnel through to get to a newly installed fpp. The first thing I do is "sudo ifconfig usb0 down" which restores connectivity from the 192.168.7.0 network. The next thing I do is add that line to rc.local so it gets executed when the fpp reboots. Not and elegant solution but it works. FPP is an awesome project and I truly appreciate the development work that goes in to it. I still believe the right way to address the need for internal networking would be to use the carrier grade NAT range (rfc 6598). There is plenty of address space in the allocated range (100.64.0.0/10.) FPP could also use a block from the link local address range 169.254.0.0/16. With the work-around this really only bothers me when I upgrade to major revision and over-write the flash storage.

**Comment by dkulp** [comment]
FYI: This is not something we are likely to change anytime soon.    Not only does this affect things like the docs and videos and all kind of things that people are used to, but the above solution of updating the functions is only applicable for the Raspberry Pi.   For the Beagles, the use of 192.168.[6,7,8] is done at a much deeper level down in all the Beagle boot scripts and OS init things that we have no control over.

**Comment by darylc** [comment]
I propose we close this issue because we can't actually do much about it given at least on the BBB platforms it comes from upstream.  It's in our interests to keep PI & BBB the same from and end-user perspective.

**Comment by ghormann** [comment]
For 5.0, has been added if a user attempts to set a static IP in the 192.168.[6,7,8] range.   I realize this isn't perfect, but I think it is the best we can do at this point. 
![image](https://user-images.githubusercontent.com/24968726/122677954-98a0f000-d1b2-11eb-8c4a-a0c044b0c939.png)
