### ISSUE TITLE
FPPd not running

### ISSUE THREAD

**Issue by Emork142** [FalconChristmas/fpp#575]
I upgraded to 3.4, which I was at 3.2.  When I plug the monitor in, it wants me to sign in.  When I do, it looks like it is still at 3.2.  Faied at FPPd.

**Comment by nmiller0113** [comment]
Are you sure it completed the upgrade?  Do you have a screenshot of what is showing you 3.2 still?  Is there a reason you're having to plug in a monitor?  You shouldn't ever have to log in via the command line. Also, have you confirmed that your FPP instance has internet connectivity?

**Comment by Emork142** [comment]
It says "[FAILED] Failed to start FPPd.
See 'systemctl status fppd.service' for details.
Then I get the FPP login at the bottom.
Above that says Falcon player OS Image v3.2

It looks like it crashed during the upgrade process?

**Comment by Emork142** [comment]
Thanks Nathan,

I found it easier to pull the sd card, reinstall 3.2 image, and restore my
settings.  Then upograded overnight.  I may have pulled the power too soon
for a reboot before the update was done.

I appreciate your quick response!!

Emork142
