### ISSUE TITLE
Gpio Triggers Falling and Rising even if only one selected

### ISSUE THREAD

**Issue by ncosper** [FalconChristmas/fpp#576]
I am on 3.4.1 (same issue on 3.4) but I am assigning just a simple script that plays a playlist with one audio file. So as simple as push a button and an mp3 plays. Regardless of whether I assign the gpio pin to a rising of falling event it triggers it twice. I get a millisecond of sound, then a pause then it plays the full mp3. 
thanks

**Comment by Poporacer** [comment]
Did you configure a pull-up or pull down resistor? Internally or externally?

**Comment by darylc** [comment]
@ghormann Lets close this one given the lack of reply from the OP in a year or two
