### ISSUE TITLE
Multisync Advanced View shows 100x % CPU Utilization

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#580]
the Multisync Advanced View appears to be missing a decimal point in the CPU Utilization display as its off by a factor of 100.

For example when the Linux TOP command is reporting a cpu load of 1.32%, the Multisync Advanced View display 132% (should be 1.32 not 132)

**Comment by cpinkham** [comment]
This was fixed already in master and v3.5.x release branch.
