### ISSUE TITLE
Cant trigger events in Bridge mode

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#583]
Is there a way to trigger events in bridge mode?

I have ESEQ files that HAVE to be at 20FPS for some reason to play at the right speed when my remote is in remote mode and my main pi playing the show has all sequences at 40FPS. If I have a 40FPS model ESEQ on the remote and trigger it with the show files at 40FPS the scrolling message plays twice as fast

Last year I used bridge mode and triggered them from CURL and set the transmit interval in advanced setting to 25ms and it worked fine. Now im testing the new version with events triggering ESEQ and the 20FPS scrolling message looks so jumpy compared to the 40FPS so I would like to use the 40 but can't

**Comment by bchiaino** [comment]
For now I just set the event to trigger the URL that triggers the effect like below and it works fine
![Screen Shot 2019-11-07 at 12 21 22 PM](https://user-images.githubusercontent.com/40632971/68411833-3b7d3580-0159-11ea-8079-2cfa2b2ff17e.png)

**Comment by cpinkham** [comment]
This was fixed in d4c978f5bf
