### ISSUE TITLE
Lights still not "all off" when I stop my show

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#586]
I noticed in the branch an update to send a command to turn the lights all off but still when I start a show and stop it, my lights just freeze or shut off and a few in random props stay very dim, they do not turn off. I am on  v3.x-master-165-g3c808b80 (master branch)

**Comment by bchiaino** [comment]
video showing what's going on - https://youtu.be/xAkgNmza-pE

its hit or miss, sometimes I hit stop and the lights just freee and stay lit and other times it works as it should and shuts them off

**Comment by cpinkham** [comment]
I believe this was fixed by a previous patch, closing ticket.
