### ISSUE TITLE
DDP Status errors that aren't actual data or cabling errors

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#590]
I have four BBBs in Bridge mode and they accumulate errors every time the playlist changes or the FPP sending their data does an FPPD restart.

Is there a way to filter those predictable errors so I can tell an actual error?

**Comment by darylc** [comment]
@JonB256 Is this still an issue in more recent versions?

**Comment by JonB256** [comment]
While I don't have anything set up to give a valid test (yet), the errors were never consequential, just visible. 
I'll revisit when I get a Bridge Mode FPP up and running. I use DDP to all my FPPs and to my F16v3 board.

**Comment by darylc** [comment]
@JonB256 Any update?
