### ISSUE TITLE
3.5.1 and 3.x master, Effects not turning off if more then 1 is running 

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#592]
I have 3 effects that loop in the background during my show, one is a tiny light at my front door, a North Pole globe and a North Pole message (not in video)

When I turn the front door on and off it works great, when I turn the N pole on and off it works great but if the North Pole AND the door are looping at the same time then you cant turn just one of them off so if I stop the door in FPP, it remains lit until I turn off the pole also

v3.x-master-197-g117d8959 (master branch)

video - https://youtu.be/-lA06o5rPNI

fppd log - [fppd-6.log](https://github.com/FalconChristmas/fpp/files/3856204/fppd-6.log)

**Comment by bchiaino** [comment]
I fired this up on another Pi also and got the same results. I even created new ESEQ files and no luck. 

Here are the 2 ESEQ files and a pic of the channels I have them configured on on my F49


[FRONT DOOR3.eseq.zip](https://github.com/FalconChristmas/fpp/files/3858954/FRONT.DOOR3.eseq.zip)
[POLE3.eseq.zip](https://github.com/FalconChristmas/fpp/files/3858955/POLE3.eseq.zip)
![Screen Shot 2019-11-18 at 9 10 22 AM](https://user-images.githubusercontent.com/40632971/69059416-7bf37380-09e3-11ea-8f9d-43bf16cb164c.png)

**Comment by cpinkham** [comment]
I think that we need to clear the effect's channels in *channelData inside effect.cpp's OverlayEffect() function if the effect ends.  I can't remember how this was working before but I think that we need to clear the effect's channel range when the effect stops.  If there is a sequence playing that uses those channels, the channels will get repopulated, but if nothing is using those channels, then it looks like they would get 'stuck' on the last frame of data in the effect sequence until the next Sequence::BlankSequenceData() call.

**Comment by bchiaino** [comment]
nice, if it gets fixed ill give it a shot as soon as possible so we know if it works

thanks!

**Comment by bchiaino** [comment]
Chris is this something simple that may be fixed? reason I ask is my show starts next week so if this is not cleared up I will have to come up with a different way to do my effects on and off on loops. thanks!

**Comment by cpinkham** [comment]
I may have to defer to @dkulp  on this one since effects.cpp now uses his FSEQFile class to read effects files.  I think that we may be able to get the channel range list from FSEQFile and clear them, but it may be better to update FSEQFile or FSEQFile::FrameData to have a new method to clear the channels since it knows the ranges.

**Comment by bchiaino** [comment]
Just an FYI, this is still an issue, I just tested and the 2 effects still remain on until both are stopped, I cannot individually stop them
