### ISSUE TITLE
 FPPD Crash Help: fppd.c:96:Crash handler called:  11

### ISSUE THREAD

**Issue by rkpalmer** [FalconChristmas/fpp#597]
Over the past two days, I have been testing the FPP in preparation for this weekend's premier. Everything has been going great with proper starts and ends based on the playlists and schedules. Today, it crashed with following error after playing for an hour and a half. It required me going into the GUI webpage and starting FPPD again, and it continued on. Do you know what caused this?

> 2019-11-21 19:00:06.734 (22427) fppd.c:96:Crash handler called:  11
> 2019-11-21 19:00:06.734 (22427) fppd.c:102:  /opt/fpp/src() [0x14564]
> 2019-11-21 19:00:06.735 (22427) fppd.c:102:  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x74513120]
> 2019-11-21 19:00:06.735 (22427) fppd.c:102:  /opt/fpp/src/libfpp.so(_ZN8Playlist7ProcessEv+0xbc) [0x762fcf70]
> 2019-11-21 19:00:06.735 (22427) fppd.c:102:  /opt/fpp/src(_Z8MainLoopv+0x568) [0x1598c]
> 2019-11-21 19:00:06.735 (22427) fppd.c:102:  /opt/fpp/src(main+0x1e0) [0x13d5c]
> 2019-11-21 19:00:06.735 (22427) fppd.c:102:  /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0x744fd718]
> 2019-11-21 19:00:06.774 (23448) fppd.c:96:Crash handler called:  11
> 2019-11-21 19:00:06.775 (23448) fppd.c:102:  /opt/fpp/src() [0x14564]
> 2019-11-21 19:00:06.775 (23448) fppd.c:102:  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x74513120]

**Comment by dkulp** [comment]
There is nothing here that is usable.  If it can be reproduced, I'd be happy to remote in and debug, but there is nothing in the above to trace it to anything.
