### ISSUE TITLE
3.5.3 BBB Creates ~/media as root:root

### ISSUE THREAD

**Issue by jeffla** [FalconChristmas/fpp#602]
Reimaged with 3.5.3 & new USB drive. media is owned by root instead of fpp:fpp so can't upload any sequences, create playlists or add schedules. Tried sudo chown fpp:fpp media "Operation not allowed"

**Comment by jeffla** [comment]
This was a FAT formatted USB. Reformatted to ext4 and it's fpp:fpp. ¯\_(ツ)_/¯

**Comment by jeffla** [comment]
Formatted using Windows 7 format command if you want to look into it, otherwise, close.

**Comment by dkulp** [comment]
You do NOT want to use usb storage on a BBB.   It's too slow.    At BEST it's half the speed of a decent SD card.

Not sure what we could do as we specifically call a "sudo chown -R fpp:fpp ~fpp/media" so set everything in media (and the mmedia dir) to proper owner/group at boot.   And the mount flag we use for FAT is uid=500,gid=500 to set the FAT owner/groups.   Not sure what else could be done.

**Comment by jeffla** [comment]
This happened on my Pi as well so I'm thinking there's some other issue.

**Comment by jeffla** [comment]
It might also explain the other person's problem modifying playlists.
