### ISSUE TITLE
Cannot create Falcon Christmas account

### ISSUE THREAD

**Issue by Joemarthey** [FalconChristmas/fpp#603]
I just received my F16V3 and want to get started on my light show but cannot sign up on FC site.  I never receive the email to verify my account.  Yes, I have the correct email address.  Ideas??

**Comment by patdelaney** [comment]
I'm an admin on that site, what is the username you signed up with.  I
don't see any pending approvals.

Pat

**Comment by Joemarthey** [comment]
I was able to register with a different email address. Thanks for the response though.

Go Steelers!!

On Nov 27, 2019, at 11:19 AM, patdelaney <notifications@github.com> wrote:

﻿I'm an admin on that site, what is the username you signed up with. I
don't see any pending approvals.

Pat
