### ISSUE TITLE
Feature Request: Relative jump in playlist branch

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#605]
It would be helpful to have a relative jump in the playlist for branching entries rather than an absolute reference.  I find that when I reorder a playlist, or add entries, I then need to go back and redo the branching entries to correct the absolute jump reference.  This is especially tedious because there's no mechanism in the gui to edit an existing branching entry.  You need to delete and recreate it.  So instead of going directly to playlist index x,  jump forward/back x entries.  This relative method would reduce the need to go back and recreate the branch entries when the playlist gets modified.  It also eliminates the need to remember that you need to double check and edit your branch items when you edit the playlist.

**Comment by dkulp** [comment]
This is already there in 3.5.x.    Change the type to "Offset" and then you can offset by a positive or negative number.
