### ISSUE TITLE
Feature Request: Edit existing playlist entry

### ISSUE THREAD

**Issue by Jchuchla** [FalconChristmas/fpp#606]
It would be very helpful to be able to edit existing playlist entries rather than needing to delete and recreate them.  This is more relevant now that there's more complex options for playlist entries.  It didn't matter so much when it was just sequences and media.  But now that we have branching and other complex playlist entries, it would be nice to be able to edit them rather than remembering all of the settings so you can recreate it whenever you want to make and adjustment.

**Comment by JonB256** [comment]
workaround suggestion - Playlists are in json format (but very readable ASCII text).
If you connect to the Master's FPP folder, then open the Playlists folder, you can edit the entries pretty easily.  (I haven't looked "complex" playlists but my fairly simple ones are very easy to decipher)

**Comment by Jchuchla** [comment]
That's what I've been doing.  It's definitely a workaround though so I figured the ticket is worthwhile.  I'm of the opinion that if users are resorting to hand editing a data file to get something done, it's a function that should be in the application.

**Comment by cpinkham** [comment]
This is near the top of my ToDo list and something that I will be looking at after I get my lights on and one last sequence done.

I was thinking the same thing the other day when I wanted to edit a FPP Command to scroll text across my matrix and had to resort to editing the JSON.  I started looking at the code some and thinking how I would add the ability to the playlist editor.
