### ISSUE TITLE
Scripts dont run correctly when triggered by playlist or event.

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#607]
I am using the music streaming plugin.  If I run the "MP3StreamerStop.sh" from the files section it works as expected.  But if I trigger the script from either a playlist or an event, the script does not kill the process and the music continues to play after the volume returns.

**Comment by patdelaney** [comment]
I just ran a quick playlist (see image) and it ran just fine. I am testing it in a loop as well and it seems fine to me.

![image](https://user-images.githubusercontent.com/8147459/69820067-e49dd580-11c5-11ea-916b-3b42309bb01d.png)

**Comment by chrkov** [comment]
hmm..  This is an upgraded version of FPP and I may need to wipe it and start from scratch after the season.  I was able to work around the issue by modifying the script as follows:

# kill -9 $(cat /tmp/mpg123.pid)
killall mpg123

**Comment by Jchuchla** [comment]
i just found this ticket on a quick scan before posting my own ticket related to scrips and events.  Does your script use arguments?  I was just troubleshooting a similar script issue on my system and in my case I have it narrowed down to events not passing arguments to the script.

**Comment by cpinkham** [comment]
It could be an issue with the tmp file.  Can you start the streaming, then login via ssh and run "ps -edaf | grep mpg123 ; ls -al /tmp/mpg123.pid ; cat /tmp/mpg123.pid" and paste the results here?

**Comment by ghormann** [comment]
Closing as no additional information provided to the developer request in March..   if this is still an issue in 4.2, please comment and will reopen.
