### ISSUE TITLE
MQTT Client ID is not configurable

### ISSUE THREAD

**Issue by wingrunr21** [FalconChristmas/fpp#609]
Request to make the MQTT Client ID configurable. [The current code](https://github.com/FalconChristmas/fpp/blob/master/src/mqtt.cpp#L173) attempts to use the configured `HostName` and then falls back to `FPP` as a client id. Any objections to this being made configurable?

**Comment by dkulp** [comment]
No objection from me... patch  or pull request would be welcome.

**Comment by ghormann** [comment]
@wingrunr21 I could probably implement this change.   I'm curious though, what is the value? The hostname (not the client id) is used in the topic names.

Note: The master branch has been changed to append 4 random numbers to either FPP or the hostname depending on the configuration to avoid conflicts that occur if fppd crashes or if multiple devices are on the same network.

**Comment by wingrunr21** [comment]
Google and Amazon MQTT endpoints require a specific client ID to connect, so it would be configurable by the user.

**Comment by ghormann** [comment]
@wingrunr21 Interesting...   I've raised pull request  #668 to satisfy this requirement.

**Comment by cpinkham** [comment]
Fixed in ae400346a
