### ISSUE TITLE
SoundBlaster Play Not Holding Settings

### ISSUE THREAD

**Issue by byakymyk** [FalconChristmas/fpp#610]
Utilizing SoundBlaster Play 3 for Audio Output Device.  After configuring to use Speaker for Audio Output Mixer Device, FPP looses Mixer Device setting when powered down and then powered up again - it resets to PCM.  Have to make changes to Speaker each time on power up.

**Comment by dkulp** [comment]
I believe this is now fixed on master, but I've never been able to full reproduce so I'm not 100% sure.
