### ISSUE TITLE
Using "big buttons" to jump to a sequence stops current playlist from repeating

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#611]
I ran my show last night for the first time, went on at 5PM and everything ran great, a friend stopped over and wanted to see a certain sequence so I opened "big buttons" on my phone and hit the sequence set in big buttons to "start playlist at item 10" so it played it but the problem was that when it continued my schedule it ignored that it should keep repeating and played the lead out a few tracks later and the show shut off. I finally realized it a few minutes later when I saw no flashing through my window and all the cars clear out. I'm on v3.x-master-233-g4463a9cc (master branch)

**Comment by dkulp** [comment]
Is repeat turned on for the "start playlist at item 10" button?   There is a specific repeat flag for that.

**Comment by bchiaino** [comment]
I will try, I thought the repeat box was to repeat that particular sequence, not the playlist. 

If I do that will it then ignore the schedules "stop time" at 11PM?

**Comment by bchiaino** [comment]
> Is repeat turned on for the "start playlist at item 10" button? There is a specific repeat flag for that.

I just tried this, it repeats but ignores the stop time now of the schedule
