### ISSUE TITLE
Tethering Mode set to "Disabled" doesn't disable the usb0 interface

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#613]
Tethering Mode set to "Disabled" doesn't actually disable the usb0 interface in Connmann configuration (/etc/connman/main.conf).

![image](https://user-images.githubusercontent.com/19923088/69938370-1dca9400-14ab-11ea-8b61-459f845533b3.png)

![image](https://user-images.githubusercontent.com/19923088/69938198-a98ff080-14aa-11ea-9571-822fbb7d04a5.png)

In order to completely disable usb0 interface, this option needs to set PersistentTetheringMode=false in /etc/connman/main.conf

After setting up this value and reboot:
![image](https://user-images.githubusercontent.com/19923088/69938593-b95c0480-14ab-11ea-8aa1-1a87aecf7e73.png)

**Comment by Vlad-Star** [comment]
Tested against FPP 3.5.5

**Comment by dkulp** [comment]
It's not supposed to.... it's only supposed to disable the WIFI tethering.   That's as designed.

**Comment by Vlad-Star** [comment]
Well, but why would it keep persistent tethering interface when set to disabled? It makes sense to completely disable it when set to "Disabled", and I also suggest to have it disabled by default, for security reasons. I was freaked out when I suddenly found out broadcasting "FPP" SSID in my network, without any action from my side to enable it.

**Comment by Vlad-Star** [comment]
I guess, the latter happened because I booted FPP without connecting or configuring any interface.

**Comment by MarkA75160** [comment]
I think its just a wording issue.  The UI should probably say "WiFi Tethering" to reduce confusion with USB tethering.

**Comment by darylc** [comment]
The tethering page is significantly different at this point and resolves this concern as far as I can see.  We can close this.
