### ISSUE TITLE
Backups of size 0 with binary files...

### ISSUE THREAD

**Issue by dkulp** [FalconChristmas/fpp#616]
If the config directory has binary files (the .db files from the MessageQueue plugin for example), then the resulting backup file is 0 length and useless.  Most likely the .jpg for the VirtualDisplay outputs will also cause an issue.

**Comment by dkulp** [comment]
@jaredb7 - since you are looking at backups, not sure if you can look at this as well?

**Comment by jaredb7** [comment]
yep i'll check it out.
