### ISSUE TITLE
Blank between sequences not working for my DMX controlle

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#617]
I have a single DMX device that is not blanking between sequences even though it is enabled.  I'm running 3.5.5 on a BBB with an F32-B cape that is handling the DMX controls for this controller.  It's controlling my RGB Wristbands.  I've attached the sequence I'm testing with along with my FPP config.
[braceletstest.zip](https://github.com/FalconChristmas/fpp/files/3917927/braceletstest.zip)
[fppgrnd2_all-backup_v2_20191203095320.json.zip](https://github.com/FalconChristmas/fpp/files/3917937/fppgrnd2_all-backup_v2_20191203095320.json.zip)

**Comment by darylc** [comment]
@nmiller0113 Is this still a problem in the latest versions?

**Comment by ghormann** [comment]
No reply to old ticket from 2019 in 8 days.  Closing.
