### ISSUE TITLE
Scheduler enhancements not working

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#623]
not sure which recent update did it, but I can't create a schedule. Pi3b+ in Standalone (master branch)

3870ae5b - Chris Pinkham, 4 hours ago : Rename Touch Punch JS since it isn't the minified version an
1acd4f0c - Chris Pinkham, 4 hours ago : Scheduler enhancements and fixes
84bcb409 - Chris Pinkham, 4 hours ago : Allow regular playlists to be parsed by Dynamic playlist ent
97eae9aa - Chris Pinkham, 4 hours ago : Allow playlist nesting 5 levels deep and m_scheduled flag bu

**Comment by JonB256** [comment]
Since I could ADD a playlist, I copied a line from a non-updated FPP:

1,Christmas,7,17,00,00,22,00,00,1,2019-01-01,2099-12-31,

into the Pi3b+ sequence file.
It shows and is editable, but still can't ADD a new schedule.

**Comment by JonB256** [comment]
Interesting note - changed to v3.5.8 using developer.php
It let me ADD multiple playlists. Saved. Went back to Master branch.
They're still there and editable and Delete works.
But ADD still doesn't

**Comment by cpinkham** [comment]
I will take a look this afternoon, this could be another hardcoded column number messing things up.  I can add entries, but am seeing something odd that I will check into in a couple hours.

**Comment by JonB256** [comment]
That did get fixed!  Thanks.
