### ISSUE TITLE
GPIO

### ISSUE THREAD

**Issue by Jbdlr** [FalconChristmas/fpp#624]
I have a problem, I am using the GPIO 595 pins to control some LEDs, but I cannot control the intensity of the LEDs. How that can be fixed?

**Comment by dkulp** [comment]
I don't think you can.  The GPIO 595 is just "on" or "off".   There is now PWM capability to allow for any sort of dimming.

**Comment by Jbdlr** [comment]
So I could control the LEDs with an arduino using the generic serial output?

**Comment by cpinkham** [comment]
Sure, or some other device that can do PWM.  You may also need something with zero cross detection to do proper dimming.  Closing this ticket as it is something that FPP can't do with the GPIO595 channel output.
