### ISSUE TITLE
Not letting me save more than one universe

### ISSUE THREAD

**Issue by villadelmar** [FalconChristmas/fpp#625]
I upgraded from 3.0 to 3.5.8 today. I'm trying to add more universes but its not letting me save after i select more than 1 universe. I tried it in my phone and PC with no luck. After "inspecting" the website whenever i click on save i get errors and no scripts load. Any ideas? I'm getting this error: 

```
Uncaught TypeError: Cannot read property 'checked' of null
  | postUniverseJSON | @ | fpp.js?ref=1575656191:1506
-- | -- | -- | --
  | (anonymous) | @ | channeloutputs.php:480
  | dispatch | @ | jquery-3.4.1.min.js:2
 | v.handle | @ | jquery-3.4.1.min.js:2
```

Thanks

**Comment by mattcheww** [comment]
Did you find a solution for this? I'm having the exact same issue and can't find a fix for it.

**Comment by cpinkham** [comment]
Go to the FPP About page in the UI and pull in the latest updates, this bug was fixed soon after that release.

Chris
