### ISSUE TITLE
Script Viewer button appears to be pulling in the wrong script.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#626]
Navigate to script Repository
Find the 3 PixelOverLay entries
Click View button for each one, what you get is not the script,

It looks like the "view" is the same for each of the three entries.

The same thing happens when you try to "View" those 3 scripts via File Manager.

It seems it's only scripts with .php extension.

**Comment by cpinkham** [comment]
The problem was related to viewing files with < and > in them, the actual script downloaded was correct.  The < and > were intepreted by the browser causing the text to appear incorrectly when viewed.  Solution was to replace with html codes for these characters.
