### ISSUE TITLE
Ease of use enhancements

### ISSUE THREAD

**Issue by jnealand** [FalconChristmas/fpp#632]
Would like to see some enhancements that would make using FPP easier. 
 
1. A way to delete all or multiple objects from file manager for sequences, effects, or audio from an FPP instance.  I have a lot of good sequences as well as some junky ones that I tried and multiple versions of others.  This would also be very useful when switching between shows or seasons.

2. the ability to sort the list of remotes in the multisync window by name or by ip.

3. Add a text file to the root of the uSD that would state what version was on the card without having to boot it up.

4. Add the ability to export the data that is in the advanced version of the multisync window.  Would be great for documentation purposes, especially for those of us that use multiple remotes.

5. Add the ability to play a single sequence in the main window without a having a playlist.  I know you can do it in testing but that is without audio and does not work with master/remote sync.

**Comment by cpinkham** [comment]
I have created a couple tickets to try to address some of these for FPP v4.0 later this year.

MultiSelect for the File Manager - #650 
Ability to sort systems in MultiSync UI - #647  This also is related to #631

**Comment by cpinkham** [comment]
I have item 5 working as part of #298 and it will be committed to the master branch soon.  You will be able to play the sequence/media from the FPP File Manager and also directly from the main status screen.

**Comment by cpinkham** [comment]
#2 is done now as well.

**Comment by darylc** [comment]
@ghormann 1, 2, 4 & 5 are done here.  Do we want to do #3 or close this?

**Comment by ghormann** [comment]
I created #1048  for the Multisync download feature.  WIll close this mega ticket.
