### ISSUE TITLE
Doing manual update from 3.5.4 getting error  error: stray '\377' in program

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#633]
It is spitting out tons of these lines as it works its way thru the various source files.

Fingers crossed it still works after the update...

**Comment by derwin12** [comment]
From the host .. looking at various files and they are full of octal codes - not what you expect in a .h or .cpp file.

For example:
PlaylistEntryBranch.cpp  is all 1 octal code - perhaps a bunch of bad files in the pull?

**Comment by derwin12** [comment]
Jumped ahead to master (using /developer.php) and it was a clean pull and compile.

**Comment by dkulp** [comment]
Likely some sort of corrupt git pull.   Looks like a branch change cleaned it up.
