### ISSUE TITLE
Blank between sequence without box ticked

### ISSUE THREAD

**Issue by myhrmans** [FalconChristmas/fpp#637]
Running FPP version v3.5.6 (v3.5 branch) and when a sequence has finished all light are turned off even tho the box to blank between sequences is not ticked.

**Comment by cpinkham** [comment]
I am not seeing this on my systems.  Please try pulling updates to get up to 3.5.9 and retest.  Also, a lot of times when this is happening, the blanking is actually in the sequence file.  In your sequencer, make sure that your effects run right up to the end of the time or past if allowed.  Please report back and let us know the outcome so we can close the ticket.
