### ISSUE TITLE
network issue

### ISSUE THREAD

**Issue by eli-shoe** [FalconChristmas/fpp#639]
I am having a problem with FPP. when i go put the network data in for my wifi and save and restart and go to the home page the new ip address doesn't show up. jeff lacey told me to contact you about it because it may be a bug.

**Comment by jeffla** [comment]
FYI. This is on a Pi-Zero (which I don't have to test on). Not seeing this on Pi4.

**Comment by Poporacer** [comment]
How were you installing? USB tether or Wi-Fi tether? You might need to shut down the Pi and restart it. I think a reboot might do it as well. I just tried 3.6 and 3.6.1 on a Pi Zero with no problems.

**Comment by eli-shoe** [comment]
I fixed it

**Comment by Poporacer** [comment]
Since you submitted an issue, tell us what you did to fix it so that the developers could make the appropriate changes.

**Comment by eli-shoe** [comment]
I'm not sure that it was a problem with FPP I think it was just user error
