### ISSUE TITLE
Playlist Entry type - alphabetize - with default being Media & Sequence selected

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#652]
When adding a Playlist entry type, would be nice to have the list alphabetized, but having media & sequence as the default selected upon entering the playlist menu. Adding playlist entry types keeps making the scrolling and 'hunting' for what you want when the list not in order - longer time to find what you want.

**Comment by cpinkham** [comment]
This work has been done as part of a cleanup and rewrite of a portion of the playlist editor and status pages.  Ticket will be closed once the changes are committed.
