### ISSUE TITLE
FPP v4.0 Release Notes

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#653]
# New Features
* Add built-in video player based on libVLC and deprecate omxplayer usage.
* Add ability to send FPP Commands via FPP MultiSync protocol
* Allow MQTT client ID to be configured via settings UI
* Append random 4-char string to default MQTT client ID to eliminate conflicts
* Added ability to select multiple files at a time in the FPP File Manager to allow some multi-file operations (ie, deleting, downloading)
* Added ability to play a video in the web browser to preview it.
* Added built-in effects for Pixel Overlay models, accessible via FPP Commands
* Added ability to play a sequence file and its accompanying media without having to create a playlist.  This feature is available from both the File Manager UI and the main Status UI.
* Added MQTT topics to allow a FPP Pixel Overlay Model to be treated as a MQTT Light in Home Assistant.  This includes support for MQTT Discovery to allow Home Assistant to auto discover FPP Pixel Overlay models as MQTT Lights.
* Revamped Playlist Editor UI including adding the ability to edit existing playlist entries without having to delete and recreate items.
* Revamped MultiSync Setup UI to allow sorting and filtering of systems, upgrading multiple FPP instances at once, restarting multiple FPPD daemons at once.
* Added ability to set the time zone and Latitude/Longitude automatically.
* Added a file based virtual GPIO input/output for use on systems which do not have native GPIO ports.  This can be used in Docker and Virtual Machines to simulate physical GPIO ports.
* Test interface added to REST API help page
* Added optional "description" field to playlist that is published via MQTT and API for plugins.

# Changes
* Updated Event Control Channels to use raw IDs by default
* Added Help menu link to REST API help page
* Upgraded version of C++ used for compiling
* Revamped FPP File Manager UI code to allow multi-select to enhance file management abilities
* Set default MQTT port so it does not have to be specified in the UI
* UI updates to standardize format of tables used throughout the UI and plugins.
* Optimized ColorLight Channel Output by using sendmmsg() and allow driving larger displays
* Converted Scheduler config file from CSV to JSON.  Configuration will be auto upgraded by fppd.
* Updated FPP_Install.sh script to allow detection and installing on OrangePi
* Moved contents of developer.php into the Developer tab on the main FPP settings page
* Switched from using omxplayer to ffprobe for retrieving media file metadata.
* Manage fppd start/stop/restart directly from systemd rather than using a shell script wrapper.  This allows systemd to restart fppd automatically if needed.
* Deprecated Event, MQTT, and Volume Playlist Entries.  These entries will still be played by the player, but will be auto converted to FPP Commands the next time the playlist is edited in the playlist editor.
* Upgraded libhttpserver to latest release
* Adjusted JPEG compression level on main UI background image to reduce initial page load size.
* Removed unnecessary "divisible by 16" sanity check for Virtual Matrix resolution
* Removed use of deprecated jsoncpp function calls
* Removed dependency on boost libraries
* Removed support for CSV format MultiSync packet.  FPP and all compatible devices use the binary MultiSync data packets, so the CSV format packets were not in use.
* Removed CSV Playlist upgrade button and code.  Users upgrading from FPP v1.x will need to recreate their playlists in FPP v4.x.
* Removed Auto Update feature.  All updates must be user initiated.
* Removed Legacy mpg123/ogg123 support in favor of newer SDL audio player.
* Removed Legacy Raspberry Pi 16x2 LCD support
* Removed Triks-C Channel Output
* Removed OLA Channel Output (never was in UI)
* Removed Hill320 Channel Output (never was in UI)

# Bug Fixes
* Fixed parsing of Transition Type value for Image playlist entries
* Fixed max channel number issues in Channel Output UI
* Fixed issue with ICStation USB relays toggling on/off when fppd restarts
* Fixed panel rotation and panel number issues in ColorLight Channel Output.  NOTE: This will require users to reconfigure their panels in the FPP UI to correct the rotation and reverse the panel numbers on each output.
* Fixed error handling for some AJAX calls

**Comment by PixelPowerUSA** [comment]
Dan in case you didnt get my text file in regard to the wifi issue on the PB v4 here it is. Thanks!
[Trouble log for FPP v4 Sam Robb.txt](https://github.com/FalconChristmas/fpp/files/4441499/Trouble.log.for.FPP.v4.Sam.Robb.txt)

**Comment by cpinkham** [comment]
Closing, v4.0 has been released.
