### ISSUE TITLE
Remove FPP::MemoryMap Perl module

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#654]
This isn't needed anymore since we have the API now.  There are still a few remaining scripts in the Script Repository which need to be converted to use the API and then the lib directory and Perl module can be removed.

**Comment by darylc** [comment]
Can we consider leaving this there in order to support end-users who have written their own scripts around this?

**Comment by dkulp** [comment]
For 4.0, likely not.   We're planning on not even having perl installed in the images.

**Comment by dkulp** [comment]
And once this is gone, we can hopefully then remove the shared memory blocks and control channel things that this requires.  That will then allow a more arbitrary channel block instead of the hard coded 8M right now.  This is specifically why I wasn't able to flip to "however many channel is required" when I've been increasing the max each time.

**Comment by cpinkham** [comment]
I think there are advantages to having the ability to memory map blocks of the channel data, but wonder if a lot of these can be handled by C++ plugins.  I do wonder some cases are better handled by the concept in some other half-written code I have from back when I started working on a Pixel Overlay rewrite.  The idea back then was that any client wanting to write to channel data would make a request to fppd and fppd would open a new memory mapped file specifically for that client and channel range.  fppd would then copy data from the block until the client closed the block.  This wouldn't need a channel limit or the current memory mapped files we have now or the files which have an index of the pixel overlay models for the clients to read.  The client could either say "I want to write to model X" or "I want to write to channels 1025-2049" and they would get back a filename to open and write to.  I think the C++ plugin architecture is great, but one weakness is that it does leave fppd open to potential crashes due to bugs in plugin code.

**Comment by cpinkham** [comment]
This code will have to stick around until we can add back a few missing features in the new implementation.

- We can not update text while it is scrolling.  The perl module provides a way to pass in a callback function to generate the text message.  This callback is called once per second to allow changing text while the text is scrolling for countdowns, clocks, etc..  We may be able to accomplish for clock or time based messages by having % tags such as those used by the 'date' command and regenerating the text message every second, but there may be other use cases this does not satisfy.
- The caller needs a way to know when the text has finished scrolling.  The perl module TextMessage() function would block while the text was scrolling allowing it to be used in a while loop with no sleep() and continuous scrolling.  With the new method, the REST call is a fire and forget and the caller does not know when scrolling has completed and when to initiate another scroll.

**Comment by cpinkham** [comment]
Closed by Dan in 6af8f4e77f5
