### ISSUE TITLE
FPPD Restart isn't completely effective after an update

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#659]
On my Pocketscroller, after an update (Master branch), the Matrix Tools drawing or text does not work until I do another Restart FPPD or Reboot.

When the update finishes, it clearly states that FPPD has restarted, and the Status Page shows "Running" as it should, but Matrix Tools is unconvinced.

**Comment by JonB256** [comment]
I am using "Advanced Layout" for the LED Panels screen, if you think that matters.

**Comment by cpinkham** [comment]
Unable to reproduce this here.  Did you do anything other than pull in updates or were you also making changes to the pixel overlay or channel outputs?  The manual update process shuts down fppd before pulling in updates and restarts fppd when done.  The main difference between master now and master 5-6 weeks ago is that the update script sets a flag to tell fppd not to clear channel outputs when it starts, but that shouldn't cause anything like what you are describing. 

If you can reproduce the issue again, can you please test to see if you can play a sequence to help determine if it is the channel output side or the pixel overlay side of things that is not working correctly?

**Comment by JonB256** [comment]
Opportunity just occurred. Verified sequences and Matrix Tools were working before latest two updates (was at  v4.x-master-26).

Then updated. Now shows v4.x-master-28-g6ad38579. 

Matrix Tools does not display
Display Test of an FSEQ does not display
Manually choosing a sequence from a play list does not display.

Now I do a Restart FPPD at bottom of the screen.
All 3 above tests now work.

As of yesterday, I am getting this message in the FPPD.log (5 times, this is the latest entry)
Thu 23 Jan 2020 11:55:44 AM CST
Stopping fppd
/opt/fpp/scripts/fppd_stop: line 40: stopOLADaemonIfUnused: command not found

**Comment by JonB256** [comment]
FPPD_Boot.log clearly shows a Restart of FPPD twice.
Identical sets of entries, one at the time the Update finished
One at the time I manually restarted FPPD.

**Comment by JonB256** [comment]
I will get power back to one or more of my other Beaglebone/Octoscroller setups to see if it also affects them.
I have tried it on three different RasPi (master, remote and standalone) and they were not having this problem. So far, it is just the PocketBeagle with a LED Cape.

**Comment by JonB256** [comment]
The last update  v4.x-master-30-g501fdece (master branch) did NOT have this problem.
501fdece - Daniel Kulp, 19 hours ago : Hook up PocketScroller's I2C control pin to properly control ...

though it seems to involve an update to the PocketScroller's I2C setup, this is the first time in several days that my PocketScroller has functioned correctly without the second FPPD restart.

Will keep checking before and after each update.

**Comment by JonB256** [comment]
Some update between when I first noticed and current has fixed this issue on my Pocketscroller.
I'm closing the issue. Thanks.
