### ISSUE TITLE
"Repeat" self selects after unselecting and playing last few items of playlist

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#660]
Version: v4.x-master-26-gc4acf5dd

I have a playlist, it is running in repeat. 

I stop the playlist using STOP NOW. I unselect REPEAT. I select the 2nd to last entry of the playlist - as it is a script that I want it to run to delete some items from the system for me. 

The script runs, and the last item of the playlist runs and then Repeat is checked automatically and the playlist starts playing again. 

I would wish the playlist to respect the REPEAT option not being selected, and just stop when the selected entry and the ones below it are completed.

**Comment by cpinkham** [comment]
I think we determined in slack that this was the scheduler restarting the playlist after it completed it's manual run.  The playlist was played manually once during a time slot when it was set to play on repeat, so once the manual run finished, the scheduler checked to see if it should be running anything and it restarted the same playlist with repeat turned on.
