### ISSUE TITLE
Additions to Servo control PCA9685

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#661]
There are two items that I would like to see added to pca9685.
The first would be a center value with the default setup for 1500.
This is common for most of the servo controllers.
Quite often when making Servo controlled props you need a center value so you can Center your Servo and have different values going high and low.
An example would be a 3-axis skull with a nod servo that you want to center so it looks straight out but you want more travel going up and you do down so that the jaw doesn't crash with the neck piece. 
The second item that's not as important would be a way to adjust the travel speed of the servo to get a more fluid like movement. 
This often helps with eliminating jerky movements that you sometimes get by driving the servo from a Source like xlights where you have to scale the value up. 
I think on the frightprops servo controller they call it acceleration. 
And once again thanks for all the work you guys do.

**Comment by ebuechner** [comment]
I just thought of something else
The default min and max values should be adjusted with a Min of 1000 and a Max of 2000. 
The current default values could run some servos to their physical limit and break things.

**Comment by dkulp** [comment]
master now has the center option.   I also added an option for controlling what happens if a 0 is in the channel data.   I set the default to "Hold" to hold the current position.   Thus, in xLights, you only have to add effects for the actual movements.   If there is not an effect in an area, it will "Hold".   Also set the defaults to 1000-2000, center of 1500.

**Comment by dkulp** [comment]
If someone who actually uses servos can test and let me know how well it works, I can merge it to 3.6 if everything is OK.
