### ISSUE TITLE
PCA9685

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#662]
There seems to be some odd window Behavior while trying to do an add on the channel output page.
The zero Behaviour is a great addition and I was wondering if there is a way to add an option in there that would turn the pwm signal off on that channel.
Right now the Hat sends out a pwm signal all of the time which can be problematic for some servos. There are two distinct flavors of Servo out there, analog and digital and the analog will rest when it doesn't have a signal and the digital will hold it last position.
The problem with a Servo trying to hold its position for a long time when it should be in a resting state is that it can overheat if there's a slight bit of tension on it and some of them have been known to melt and burn up.
I'm using digital servos in my props so I have to come up with ways to cut the power when the item should be in a resting state. 
If we can kill the pwm signal this will give people an option to use analog servos so they don't need as complex of a setup. 

The centering is fantastic but it creates a new issue with the servo snapping back to Center at full speed when there's a zero input. Which brings me back to being able to control the speed of the servo. 
I'm not sure if it's possible but it would help tie things together but people should be able to sequence to compensate for that. 
![15800453392363320160312608097637](https://user-images.githubusercontent.com/16748687/73135918-9febba80-400d-11ea-9947-52c33f3f125d.jpg)
![15800454400317177829504289708696](https://user-images.githubusercontent.com/16748687/73135926-ca3d7800-400d-11ea-9c19-b70422074fd0.jpg)

**Comment by dkulp** [comment]
I think the layout issues and add additional outputs issues are fixed now. 

Also added a Stop PWM to the zero behavior.

**Comment by ebuechner** [comment]
Looking good on my end.
 thanks.
