### ISSUE TITLE
Schedule Priorities 

### ISSUE THREAD

**Issue by SmAsH-jl** [FalconChristmas/fpp#665]
Feature Request. 

Schedule priorities, Even a number system as per below. I use it in xSchedule a lot it would be a nice addition to FPP. 

10 - Highest
9
8
7
6
5 - Medium 
4
3
2
1 - Lowest

**Comment by dkulp** [comment]
This is already implemented.    The schedule priority is controlled by the order of the schedule entries on the page.   The first entry that "matches" is the higher priority.    With 3.6, you can now drag/drop the entries to re-order them to adjust the priorities.
