### ISSUE TITLE
Request to support Gs8208 protocol in BeagleBone pixel output

### ISSUE THREAD

**Issue by nick331** [FalconChristmas/fpp#670]
Hi everyone,
First, thank you to have create such a very useful project (FPP)

Second, i explain my problem...
I bougth some gs8208 led from BTF on Aliexpress some month ago. I try to use it with the last version (3.6) of the FPP in a PB and use some of the output to drive the led. It didnt work.
I try the same setup with some ws2812b, ws2813 and ws2815 and it works perfectly.
I tested the gs8208 with an esp8266 (only to try if it works) and it work but only with this particular program (i find it on google, i search only for an example to test it rapidly...if i refind it again i post here the link) In all my test i used a level Shifter (in particolar an 74hc541 to convert 3.3v to 5v) but it dosent work for the gs8208 (for the ws2812b/ws2813 and ws2815 it works perfectly)...So i think the problem is in the protocol itself.

With this conviction i try to find the difference between the esp and the FPP...with the oscilloscope i find that the output freqency in the esp is faster than in the FPP.

In particolar:
**Esp:**
1360ns or 735Mhz
T0H=328nS
TOL=1032nS
Reset=380uS
**Fpp:**
1560ns or 641Mhz
T0H=290nS
T0L=1270nS
Reset=43mS
Only now i realizzati that i forgot to measure the T1H and T1L

**My Possible solution:**
On github i find that there is a file named "Falconws281x.p" ( [Github File](https://github.com/FalconChristmas/fpp/blob/598e11fb13769b4d7e03ac23642b7a364f2f3c1e/src/pru/FalconWS281x.p) ) were i can see the timing used to drive the led...so if i can know how to modify this timing and how to recompile the file i can try to test it.

I try to modify this value with: 
#define T0_TIME      270  // i can decrese a little bit this if the frequency for this led is yet too low
#define T1_TIME      800
#define LOW_TIME  50  //i know thi value is too low bwcause the time to update the value is between the 500/550nS, Right? (this is was i observe from my experiment,tell me if im wrong)

This is the timing resulting from the oscilloscope :
T0H = 316nS
T0L = 920nS
T1H = 832nS
T1L  = 552ns
And now, it works...not very well but it show the color that i setting up in the test section of the FPP.

**Second problem:**

I see that if try to test it with the **CHASE R-G-B** all works fine and it works but if i try to test the strip with the **CHASE R-G-B-ALL** it start to not work at all, the first led is okey...after the strip color change becomes slower and slower as it proceeds (first led ok, second slow, third slower and so on )
But...the datasheet of this led show somthing intresting: 
![GS8208](https://user-images.githubusercontent.com/27915644/74052454-2de67e80-49da-11ea-8bbe-3d31799e3877.jpeg)
[Complete DataSheet](http://addressable-led.com/UploadFile/upi/file/20171130/GS8208.pdf)

...the interval between code...

Now i think the problem is here...
I have to add an 700uS to 10000uS every Pixel...or every 24bit in the chain

I try to find a method to do this in the Falconws281x.p file but i dont know the assembler and i dont understand some intruction that there are there. 
I understand how the bit are send...but i dont know how to create a function that every 24bits send waits for this period of time. 

Thnk you so much in advance if someone try to explain to me to do this
Thank you 

P.s. I ask in particular to @dkulp that i see from the cronology of the file on github modify it several times

**Comment by darylc** [comment]
The FPP development team met and decided it is not aiming to implement pixel types other than WS281X.  Of course if someone feels strongly they can send a pull request to implement other pixel types.

**Comment by tmitchellgcio** [comment]
Ah so this isn't currently implemented yet? Well I might need to figure out how to add a PR
