### ISSUE TITLE
Channel Output page: Add Labels for outputs

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#673]
While doing some more Servo testing on the other tab I came up with something that is going to be needed.
With all the different outputs on that page we need a way to label each output. 
Maybe a box just below the port number on the pca9685 And a box just to the right of the gpio output I'm not sure about the other outputs, but I'm sure it would Benefit them as well.
I ended up taking out a Servo because I put a value in the wrong box pushing the servo Beyond its physical limit, Because starting the port numbers at 0 through me off by one line. But I get it that was done to match the boards.

**Comment by ebuechner** [comment]
Labels added to the pca9685 output type. other output types may still benefit from a name field.

**Comment by ebuechner** [comment]
Description field has been added to gpio.

**Comment by Poporacer** [comment]
PCA9685 outputs now has a Description field for user labels
