### ISSUE TITLE
V4-Alpha: GPIO setttings for PiFace are being set but not updating the GPIO ui

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#674]
I upgraded to the 4.0 Alpha image. When I went to the GPIO page only one of my previous version GPIO settings appeared. (I never checked the json file)  I added a configuration for PiFace 2 and Piface 3.  I left the GPIO page and went to status page. I returned to the GPIO page and the only GPIO that appeared to be configure was PiFace 1.  I checked the JSON file and all 3 were there, so I suspect then the GPIO page is reading the json, something went wrong.

Note: I created a GPIO on the first GPIO pin. and saved and restarted FPPD. I hit refresh and first GPIO showed configued, but then the PiFace Events disappeared. I checked the JSON they are all gone, the only thing in the file is []

**Comment by patdelaney** [comment]
More information:  Setting and or changing the standard PI GIO pins saves and recalls correctly. The issue is when you set PiFace-1 - Piface-8.. They set correctly and appear in the gpio.json.

BUT when you leave the page and come back it only shows the first PiFace-x GPIO that you set. So I don't thing you are reading them back in correctly.  So when you click save the GPIOs that didn't populate in the UI get written back to the gpio.json file as empty.

**Comment by darylc** [comment]
Piface got deprecated by Dan, we should close this @ghormann

**Comment by patdelaney** [comment]
PiFace is supported again and work in master but we can close this.

**Comment by patdelaney** [comment]
PiFace is supported again and des work in master. But I will close it.
