### ISSUE TITLE
V4-Alpha: No HDMI Audio no matter what settings for OMXPlayer

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#675]
Both of the Pi's that I am using for this test have either a PiFace or Falcon PiCap.  I need to test on stand alone Pi with no cap.

They are also Pi V2s

**Comment by cpinkham** [comment]
Is this still an issue?  I haven't personally tested, but thought that other users have been testing the new video output code in the v4.0 beta images.

**Comment by cpinkham** [comment]
Believe this was solved.
