### ISSUE TITLE
V4-Alpha: Wifi on Pi4 id not working.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#676]
I enter the SSID and the password and I can se that it was saved in the interface.wlan0 file. I reboot and the Wifi did not connect.  Here is the contents of that file with the password removed

INTERFACE=wlan0
PROTO=dhcp
SSID="paddycakes"
PSK="password_here"
HIDDEN=

**Comment by KuhnDaniel** [comment]
Hello  patdelaney 
in the shell:
echo "NetworkInterfaceBlacklist=SoftAp0,usb0,usb1" | sudo tee -a /etc/connman/main.conf
works fine for me :-) at rpi4

**Comment by cpinkham** [comment]
Closing as this should have been fixed in the second alpha image.
