### ISSUE TITLE
Fix panel rotation and output number bug in ColorLight Channel Output

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#680]
The ColorLight Channel Output has a bug which requires users to configure their panels rotated 180 degrees and reversed on the output chains due to an incorrect setting being used while reverse engineering the protocol years ago.  Correcting the bug will require existing ColorLight users to reconfigure their matrices, but as more and more users start using the cards it seems more important to fix the issue to eliminate future confusion.

**Comment by patdelaney** [comment]
When you say "reconfigure their matrices" do you mean the FPP config or
using the Colorlight  app?

Pat

**Comment by cpinkham** [comment]
The only change would be in the FPP config UI.  Basically, it would require fliping all the arrows 180 degrees in the FPP UI and reversing the panel numbers on an output so panel 1 becomes panel 8, 2 becomes 7, 3 becomes 6 and then 4 and 5 swap.  Right now the display is rotated 180 degrees if you have your panel arrows pointing up and set the FPP UI to point up and you have to input incorrect panel numbers to get things to layout properly. The patch will correct that issue, but it will mean that users who already 'fixed' it on their own by flipping arrows and using incorrect panel numbers will need to correct their setup.  I am thinking of making a button in the UI to apply this flip, it would be a relatively simple javascript function to add.
