### ISSUE TITLE
Logfile view at v4.x-master-149-gea077366 at PI4

### ISSUE THREAD

**Issue by KuhnDaniel** [FalconChristmas/fpp#682]
Cant view LOG Files, any other (sequences,audio,video,images,effects,) work  perfect!
any browser firefox chrome edge (os linux/windows)
![Screenshot_2020-03-07 Falcon Player - FPP](https://user-images.githubusercontent.com/36757260/76153043-d3b70700-60c6-11ea-80ae-35d20895b560.png)

**Comment by cpinkham** [comment]
I have a local fix for this and will push it as part of some other changes to uploadfile.php.

**Comment by KuhnDaniel** [comment]
thanks Chris

**Comment by KuhnDaniel** [comment]
I found an older IMG. In this the LOG view is possible and works.
v4.x-master-116-g4c6dfdcc	LOG VIEW OK

**Comment by cpinkham** [comment]
Fixed in eabac291240
