### ISSUE TITLE
NTP Sync /  v4.x-master-158-gf272dc93

### ISSUE THREAD

**Issue by KuhnDaniel** [FalconChristmas/fpp#683]
After a restart, the local time is set to London UTC. Whether it is in the FPP Setup / Europe / Berlin. I found a file timezone in + / media. Euro / London was entered in this (date 15.Feb2020). I manually adjusted that to Europe / Berlin. Then the time setting is correct. In settings everything is set as in the setup time. Apparently the file timezone is being processed not the settings?!

Thanks and greetings Daniel

**Comment by cpinkham** [comment]
What time zone is listed in /etc/timezone and where does the /etc/localtime link point to?

When I use the FPP Settings UI to change time zones, this file is correctly updated and the date on the settings page changes along with the system date (running 'date' at the command prompt).

**Comment by KuhnDaniel** [comment]
etc/localtime link point to /usr/share/zoneinfo/Europe/Berlin 
(it works if i chanche at UI the information)

/etc/timezone Europe/Berlin 
(it works if i chanche at UI the information)

in /home/fpp/media the file "timezone" is not affected by changes in the FPP UI

as written, the content was Europe / London. If I enter the value Berlin there, the time is correct (logical). The file is NOT adjusted, however, if there are changes in the UI

if I delete the file in the directory, everything works 100%.  the date of the file is february 15th 2020 from an IMG i think same date as /backups and /cache  in the /media subdir :-)
