### ISSUE TITLE
Backup select ALL ( v4.x-master-195-g11c786da)

### ISSUE THREAD

**Issue by KuhnDaniel** [FalconChristmas/fpp#693]
JavaScript Object Notation (0 Bytes) <-

![grafik](https://user-images.githubusercontent.com/36757260/77288183-901fe800-6cd7-11ea-98c2-1ebcd2a292e2.png)

**Comment by KuhnDaniel** [comment]
thanks Chris

**Comment by cpinkham** [comment]
Did you close this because it is working?  I was going to try to take a look at it but haven't had a chance yet.

**Comment by KuhnDaniel** [comment]
last update - v4.x-master-216-g8d803737
it doesn't work
I just wanted to say thank you for the check
my fault

**Comment by KuhnDaniel** [comment]
When I choose on
Channel Inputs - fail
Pixel Overlay Models Old - fail
Output Processors - fail

always step back to select all

**Comment by jaredb7** [comment]
@KuhnDaniel did you have logs available from back when this was happening? If you go to File Manager -> Logs then click 'Zip' and upload it here. I have a few things to checkout but just want to have all the info in case there are any edge cases or if your error is specific.

I thought it might of been missing settings files but I fired up a Docker instance of FPP and the backups come out ok

**Comment by KuhnDaniel** [comment]
First of all, sorry for my late reply. I just made the latest update. Even with this, the selection ALL in the backup is not possible. The desired ZIP of the LOG entries is attached. Could it be because I live in Germany and need umlauts in filenames that this causes the problem?! Thanks for your commitment (the JSON Files are empty !)
[FPP_Logs_20200524.1357.zip](https://github.com/FalconChristmas/fpp/files/4673650/FPP_Logs_20200524.1357.zip)
![Screenshot_2020-05-24 FPP - FPP(1)](https://user-images.githubusercontent.com/36757260/82756066-fad4c900-9dd7-11ea-9402-a2069193e2bf.png)

**Comment by KuhnDaniel** [comment]
![Bildschirmfoto zu 2020-05-24 16-06-12](https://user-images.githubusercontent.com/36757260/82756164-bbf34300-9dd8-11ea-9a4d-3fb9ce74d6c1.png)

**Comment by jaredb7** [comment]
Could you browse to \\10.0.1.3 and go check your config directory (from memory it might go \\10.0.1.3\fpp\config ) directory to see if there is a backups folder in there?

If there isn't, I think the issue because the config backup system can't make a folder to store the config backups in.
I dug through the code and I think when it goes to give you the download it falls over

Folder layout should look something like this
![image](https://user-images.githubusercontent.com/799998/83023845-d34c5d80-a070-11ea-9aea-99198df4bde8.png)

**Comment by KuhnDaniel** [comment]
Thanks... it is inside a folder named backups and files! 
if i select the 1 (channels input) entry and the 3 (pixel overlay),  it doesn't work.
![Bildschirmfoto zu 2020-05-27 19-58-15](https://user-images.githubusercontent.com/36757260/83055704-7fcc1680-a054-11ea-88b0-fc1310e6f65a.png)

**Comment by KuhnDaniel** [comment]
Update: v4.x-master-218-gc31246a0 (master branch) new SD Image and it works :-) Thamks
before I always worked with updates! it will probably be the case that something was wrong with the directories or authorizations, maybe

big Thanks

**Comment by jaredb7** [comment]
Thanks Daniel, I was starting to lean towards a permissions issue or how things were mounting, bit of a weird issue. Glad it's working now :)

I've got some minor tweaks to the config backup system now, so something good come out of this.

**Comment by KuhnDaniel** [comment]
backups are important, at least for me :-) old school :-)
thank you for your commitment to FPP. 
Greetings daniel
