### ISSUE TITLE
 v4.x-master-232-g08d4b460  playlist Length 00:00

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#695]
When i create a playlist all "Sequence and Media" that i add to a playlist have a Length of 00:00
It seems to run the played time and time remaining correctly when running a sequence.

Please let me know if you need any additional information.

Version Info |  
-- | --
FPP Version: | v4.x-master-232-g08d4b460
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v4.0-alpha
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 00000000536ce80e
Kernel Version: | 4.19.97-v7+
Local Git Version: | 08d4b46

**Comment by iamwally** [comment]
Agreed all my sequences show 00:00 also

**Comment by cpinkham** [comment]
Can you pull in the latest updates and retest.  We believe this was probably fixed in 915b92f52

**Comment by horathgar2000** [comment]
It is working now!
