### ISSUE TITLE
E.131 Unicast address field not wide enough

### ISSUE THREAD

**Issue by lrhorer** [FalconChristmas/fpp#697]
![FPP Unicast Address](https://user-images.githubusercontent.com/44038449/78458919-ba2fbd80-767a-11ea-9f05-666032aa3c2e.PNG)

**Comment by ghormann** [comment]
What browser was this?  I tried with Chrome it if the with is less than 1124px the address field isn't wide enough, but nor is any other field.

**Comment by ghormann** [comment]
Closing due to lack of response.
