### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by ebuechner** [FalconChristmas/fpp#698]
On the latest Master branch when enabling test mode all the lights start flashing rapidly.
It seems to do it to all outputs panels, lights, relays, servos.
4x-master-232-g08d4b460

**Comment by cpinkham** [comment]
Did you have xLights or another program sending data to your controllers at the same time?  I am not seeing this on my systems running the latest code.

**Comment by ebuechner** [comment]
I just went back and rechecked this and I don't seem to be having the problem now on the latest Master branch. 
I'm pretty sure I didn't have anything else sending data to the fpp while I was trying to run test mode but now I can't remember everything I checked from 25 days ago.
This can be closed.
