### ISSUE TITLE
Wifi not loading when upgrading the PB to v4. Works fine on 3.6.2

### ISSUE THREAD

**Issue by PixelPowerUSA** [FalconChristmas/fpp#699]
[Trouble log for FPP v4 Sam Robb.txt](https://github.com/FalconChristmas/fpp/files/4441503/Trouble.log.for.FPP.v4.Sam.Robb.txt)

**Comment by PixelPowerUSA** [comment]
Dan is working on this I believe.

**Comment by dkulp** [comment]
I believe this was fixed for alpha4 image

**Comment by PixelPowerUSA** [comment]
This was filed before the fix but yes it was, thanks👍

Brian Roberson / 772-519-1338
