### ISSUE TITLE
Abnormal Conditions - May Cause Poor Performance Could not initialize output type BBB48String. Check logs for details. on kulp pocketscoller

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#704]
its works fine just get Abnormal Conditions - May Cause Poor PerformanceCould not initialize output type BBB48String. Check logs for details. on main screen. logs attached
[FPP_Logs_20200411.1819.zip](https://github.com/FalconChristmas/fpp/files/4465136/FPP_Logs_20200411.1819.zip)

**Comment by dkulp** [comment]
Somehow you have the BBB pixel string outputs enabled in addition the LED panels.   Not sure how that happened.   The "easiest" fix would be to ssh in (there is an SSH option on the Help menu) with username fpp, password falcon and run "rm ~/media/config/co-bbbStrings.json" to remove the config for the BBB pixel strings.   Alternatively, you would need to go the Advanced settings and turn on the "Show all settings" checkbox which would all the BBB String tab to appear where you could then turn it off.

That said, I'd be curious to know how you configured things to try and figure out how the strings config was enabled.   That's a bit concerning to me.

**Comment by patdelaney** [comment]
Dan this happened to me once and I think what I remember is that I think in
my case it was from an upgrade. It was on a BBB with octoscroller and the
BBB was 2.x or 3.x and my settings were on a USB stick so perhaps
something in 2.x or 3x  was created and the new version doesn't like it???

Pat
