### ISSUE TITLE
Feature request: option/trigger every X minutes in Scheduler

### ISSUE THREAD

**Issue by SmAsH-jl** [FalconChristmas/fpp#705]
Ask: 

Could a feature be added to the scheduler section to fire an event every X minutes?

Use case:

I run my show between the hours of 6pm - Midnight.  
with Musical sequences only playing between 6pm and 9pm, non musical animations the rest of the time. 

My ideal setup would be to only play a random single musical sequence every 15 minutes, during the musical period  (6-9pm) instead of playing out the whole playlist. 

Effect:
This cuts down on the traffic lurking in front of the house for to long clogging the street and keeps the neighbors a little happier.. ( who doesn't like Christmas lights weirdos!! )

Thanks guys for all your hard work. None of what I  do with these lights would be possible without you guys!

**Comment by cpinkham** [comment]
This feature was added in c8d0eb3da and is in the FPP v4.0 released version.
