### ISSUE TITLE
v4.x-master-240-g30c31aec blank between sequences checkbox seems to not be working

### ISSUE THREAD

**Issue by andrew-busbee** [FalconChristmas/fpp#706]
It looks as though the option to not blank between sequences is not working.  I have a sequence for floods that is a 30-second all white that had been running without a flash between the start and end of a sequence.  Now it does not matter if the checkbox for blank between sequences in settings is checked or not.  It always turns off at the end of the sequence and then right back on instead of looking like they are continually on.

**Comment by alborzs** [comment]
I wanted to confirm that I am having the exact same issue as described above running on v4.0.
It seems this issue [was reported before](https://github.com/FalconChristmas/fpp/issues/637) as well but then marked as fixed in version **3.5.9**.

**Comment by alborzs** [comment]
Hi, since there is no development regarding this issue, could a developer confirm this issue and maybe give some pointers on where to get start looking at the code, maybe we can solve this.

**Comment by alborzs** [comment]
Without knowing anything about this code base I followed "Blank between sequences" and ended up in the following recent commit.
commit 2916daf808169669c44eecaccf7e4532ce66d1da

That second `else if` at line 504 might be worth looking into.
or the use of function `getSettingInt` to get a checkbox value.

**Comment by cpinkham** [comment]
@vcuncg  Are you running the fpp-brightness plugin to adjust brightness of the display?  I fixed one issue related to that recently which was causing my overnight 30-second playlist to flicker every 30 seconds.  I'm curious if this is the same issue or a different one.

@alborzs that commit only blanks if we are not running a playlist so it doesn't apply to this situation.

**Comment by darylc** [comment]
@andrew-busbee  @alborzs  Is this still happening in 5.1?

**Comment by darylc** [comment]
no reply, closing
