### ISSUE TITLE
FPPOS Upgrade Method

### ISSUE THREAD

**Issue by PixelPowerUSA** [FalconChristmas/fpp#707]
I've found that the FPPOS upgrade method is great, quick, and you don't lose any network information etc. The only problem I see for the novice user is that at the end of the update dialog it just stops with no indication that its finished. Unlike a normal update, or re-image, there is no option to 'return to main page' at the end of the update, it just stops as if it timed out. I've included a photo of the end of action dialog. I had no issues but some people might. Having said that, its a brilliant way to upgrade.
![End action FPPOS update](https://user-images.githubusercontent.com/49037022/79465529-74072200-7fc9-11ea-9c50-ce1fd1aab1e9.JPG)

**Comment by cpinkham** [comment]
This should be fixed now since the OS upgrade now uses a popup dialog box for logging and the output has been updated so that it is flushed before the reboot occurs.  If you are still experiencing this issue, please test with the latest FPP code version and fppos image.
