### ISSUE TITLE
Routing issues since upgrade

### ISSUE THREAD

**Issue by fearfair** [FalconChristmas/fpp#708]
Since updating all of my controllers to Version: v3.6.2-1-g8c761fbc (v3.6 branch) I am having a strange network issue.

My setup is that all of my fpp instances have a 192.168.1.xx address on wan0 and a 10.10.1,2,3 on eth0 with routing between interfaces checked, then the attached Falcon controller will be in the 10.10.1,2,3 network... so for example
fpp1 192.168.1.43 wan0 10.10.1.1 eth0 falcon 10.10.1.2
fpp2 192.168.1.44 wan0 10.10.2.1 eth0 falcon 10.10.2.2

I have static routes in my router and this has been working for over a year now.  But, now, I can still ping the falcons from any computer on the 192.168.1 network, but cannot access the web interface on them and more times than not xLights fails to upload output settings.  Once in a great while, the falcon web interface will come up, but I am only able to load a page or two until it stops working again.  If I ping the falcons from the output settings page in fpp, it always works as well.

Again, this has been working fine and the only change I've made is updating the fpp version on all of the controllers.  I do have two Kulp F32B's on the network that are running the 4.0 alpha. But, I tried unplugging those two and it made no difference.  It would seem to be isolated to something happening with fpp not forwarding the http traffic.

A trace route always dies after the fpp wlan0, the ethernet on the falcon pings just fine.

Any idea what's going on?

**Comment by fearfair** [comment]
Have verified that connecting directly to the falcon and setting the laptop to the appropriate ip range pulls up web pages just fine.  So definitely isolated to the fpp.

**Comment by darylc** [comment]
This sounds like a networking or configuration problem than an FPP software bug. 

@fearfair If you still require help with this I suggest you try the xlights zoom room or similar, we'll close this out for now.
