### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by xmaslightman** [FalconChristmas/fpp#710]
Unable to delete playlists 😁

**Comment by dkulp** [comment]
This seems to be working for me...  If I click on a playlist and then click the "Delete" button, the playlist is gone.

**Comment by xmaslightman** [comment]
![20200429_120905](https://user-images.githubusercontent.com/64448695/80636998-26e86e80-8a13-11ea-9399-c965c3addf4a.jpg)
These 2 playlist were generated from fpp connect I think. The will not delete. Maybe the special characters?
