### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by xmaslightman** [FalconChristmas/fpp#711]
Using a soundblaster play 3 no audio since 4.0 upgrade.

**Comment by iamwally** [comment]
Don't mean to state obvious but did you make sure to select audio output device after upgrading?  I had to select mine after upgrading in place evidently it doesn't retain the setting through the upgrade.

**Comment by xmaslightman** [comment]
went into the settings it looks like it was selected. Reselected it and will try again.

**Comment by xmaslightman** [comment]
Fixed
