### ISSUE TITLE
 v4.x-master-274-g76363a6b (master branch) Video on Remote Stuttering

### ISSUE THREAD

**Issue by iamwally** [FalconChristmas/fpp#712]
Running  v4.x-master-274-g76363a6b (master branch)  on my raspberry pi 3b+ in remote mode to run video on a projector and the video is stuttering badly.

**Comment by iamwally** [comment]
mediaoutput/VLCOut.cpp:102: LoadFace: Error creating face for /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf - 0 - 2 - 2

Got this error out of fppd.log

making me think this might be related to new video player in 4.0?  Maybe?  Help?!

**Comment by iamwally** [comment]
Also saw some errors in the log having to do with brightness plugin so I have uninstalled it on all fpp's and will see if that does anything to help.

**Comment by dkulp** [comment]
I believe the stuttering is now fixed...
