### ISSUE TITLE
Feature request: Admin/Visitor/Guest access

### ISSUE THREAD

**Issue by brennja** [FalconChristmas/fpp#717]
I am testing www.remotefalcon.com for remote FPP and visitor playlist capabilities. 
I would like to enable Admin password for additional security, especially with remote FPP access, but this disables all access without password.
Ideal solution would be granular user access - define username and password, and check box to allow required access to different tabs.
Minimal requirement - allow Guest/Visitor limited access when Admin password is defined.
a) Read only access to existing Playlists
b) Access to Play existing Playlists in Status Page

**Comment by darylc** [comment]
These days there are solutions like https://remotefalcon.com/ that can give untrusted users access to influence what is playing. Will this cover your use case @brennja?

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this.
