### ISSUE TITLE
4.0-beta1 does not format extra partion when choosing the "create new partion" option (instead of the expanding SD card option)

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#719]
v4.x-master-302  when choosing the storage option to create a new partion instead of expanding the existing partition it never gives the option to format the partition and appeart to never be mount it (since it never gets formatted).   The partition gets created and says a reboot is necessary.  After the remote, the parition appears but is not formatted.  It can be selected again and requires another reboot, but still no change.  Its not formatted and not mounted.

I would like to see exFAT as a formatting option but if that is not possible then please add FAT32.  This would allow the storage partition to be read/written on a Windows or Mac PC

**Comment by dkulp** [comment]
Fixed problems with not being able to format the partition or copy settings/etc to the newly formatted partition.   That was a regression from 3.6 after migration from the old advanced settings page.   exFAT will not be added.   Going through FUSE introduces too high of latencies and unpredictability to make using exFAT reliable.  Even the regular FAT32 is strongly NOT recommended.

**Comment by MarkA75160** [comment]
I realize that regular FAT has its own set of drawbacks, but it does have the advantage of being accessable on Win/Mac systems which can be advantageous.  I understand its not the recommended option but its nice to have the option when desired.
