### ISSUE TITLE
Had to install 4.0 beta1 fppos twice!

### ISSUE THREAD

**Issue by PixelPowerUSA** [FalconChristmas/fpp#720]
Not sure if this is an issue or an anomaly. I upgraded 2- pi 3b+ units to 4.0 beta1 using fppos today. The pi's had 3.6.2 installed on it initially. Once upgraded with 4.0 beta1 they rebooted and showed the upgrade to 4.0 beta 1 was successful in the about section, however FPPD would not start. So I upgraded again using the fppos upload and it works fine.  This is more FYI in case someone thinks its an issue.

**Comment by PixelPowerUSA** [comment]
I noticed someone else has had this issue and posted it on the Official xLights FB page.

**Comment by cpinkham** [comment]
Closing as old since multiple v4.x versions have been released and we are up to v4.5.
