### ISSUE TITLE
Ping popup moves off screen

### ISSUE THREAD

**Issue by HansonElectronics** [FalconChristmas/fpp#721]
On FPP V4 Alpha 3 and Beta 1 for the Pi at least there is the following issue.
On the network setup page ( http://fpp/networkconfig.php ) if you ping the static IP address followed by pinging the gateway address the status popup appears off the top of the screen. It actually appears that doing sequential pings to either of those IP's cause the action. 
Currently using  v4.x-master-311-g120160d4 (master branch)  and tried with both Firefox and Chrome on Win7 Pro 32 bit with 1366x768 screen resolution.

**Comment by ghormann** [comment]
This seems to be a common problem in JQuery 1.9.1  https://bugs.jqueryui.com/ticket/8741 

There is a one line workaround which I will add for now.
