### ISSUE TITLE
Xlights Upload Output to BBB LED Panels causing FPP Abnormal Conditions

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#725]
Hello,
When I try to upload output to my BBB with Octa-Scrolla Plus " 4.0 FPP" for my led panels it enables the "Enable BBB String Cape". When this occurs it causes the homepage for the BBB to show.
###
Abnormal Conditions - May Cause Poor Performance
Could not initialize output type BBB48String. Check logs for details.
###
I believe this is because both the LED Panel and the BBB String Cape is enabled.
The only way to fix this so far is to enable Display all hardware options/settings:
Then disable the BBB String Cape option.

FPP Version is the latest 4.0 Master
I am currently running Xlights 2020.18 but this has been going on since 2020.12
For the controller it is set to Vendor: FPP Model: LED Panels

**Comment by dkulp** [comment]
This is a bug in xLights, not FPP.   Should have been logged there.  In anycase, it's now fixed in xLights for a future build.
