### ISSUE TITLE
Kiosk image not booting to the FPP webpage

### ISSUE THREAD

**Issue by vcuncg** [FalconChristmas/fpp#726]
I did a re-image using the new Kisok image and hooked up a monitor and keyboard/mouse prior to booting.  Upon booting the screen is blank.  I am able to right click to get a context type menu with various options, but can not get into the kiosk view.  Let me know if you need more details.  Tried on multiple Pi's (3b, 3b+, 4) all with the same issue.

**Comment by MarkA75160** [comment]
I see the same thing.  Not sure if we're missing a step?

**Comment by vcuncg** [comment]
It is working perfectly in the final 4.0 image that was just loaded.  Hopefully it is working for you as well, MarkA75160.
