### ISSUE TITLE
FPP on BBGreen Ping and Other Issues

### ISSUE THREAD

**Issue by AJR214** [FalconChristmas/fpp#731]
FPP 4.0 b2 on BBGreen (not wireless) would not Upgrade FPP; got the message "Can not access github.com, unable to pull git updates". (See below as this was resolved, but still some issues).

This is a new install (no previous FPP ever) and I'm running FPP 4.0 b2. I etched a 32GB SD card and used that same image to boot and copy to the eMMC on all 3 of the BBB and now the 1 BBG. BBB were fine clicking Upgrade FPP, which did update some files and took about 10 minutes. The BBG gives the github error message. When I follow your link and click the Script Repository Browser, there is nothing in the list to install to Fix_github (a problem with 2.x and 3.x).

Only thing different in Network Config on the BBG is IP .208, others are .205, .206, and .207. I hooked up .207 (a BBB) and clicked Upgrade FPP and it worked fine. There is no IP conflict. My primary router has DHCP enabled for .11 to .199. I have all my controllers static IP from 201 and up. It allows me to join and break the connection between the main and show networks. Right now the only difference is it's a Green, not a Black. I can ping it locally. I can go to the shell and sudo ping the router and github.com so the internet is working from the device. Someone on Zoom asked to see the Troubleshooting Commands screen (see attached), and noticed that when the system tries to ping, it says "ping: socket: Operation not permitted". So it may be a permissions issue.

[Troubleshooting Logs FPP - FPP-F8-B3.pdf](https://github.com/FalconChristmas/fpp/files/4641201/Troubleshooting.Logs.FPP.-.FPP-F8-B3.pdf)

Before submitting this issue, I figured I would wipe everything and start from scratch. Formatted and etched the SD card with 4.0 b2 image, went through all the same steps to copy eMMC and configure, and now it will download the upgrades from github. However, afterwards the OLED screen looked garbled. I had to power cycle everything twice to get the OLED to show properly. I also run the logs and it still shows the ping command issue. I'm unsure of what to do at this point with the BBGreen. It won't go into production for a while as it hasn't been assigned to the show yet. I don't want to put the Green out until I know it is working correctly.

[Troubleshooting Logs FPP - FPP-F8-B3 (After Upgrade FPP Worked).pdf](https://github.com/FalconChristmas/fpp/files/4641354/Troubleshooting.Logs.FPP.-.FPP-F8-B3.After.Upgrade.FPP.Worked.pdf)

**Comment by ghormann** [comment]
I don't have have a BBGreen, but didn't reproduce on 4.2 with BBB.   Is this still a problem?

**Comment by ghormann** [comment]
Closing
