### ISSUE TITLE
Auto Restart/HUP FPPD Process from xLights

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#733]
Feature request that would allow xLights to automatically restart/HUP the FPPD process after uploading input or output.  

Every user may not want this feature so maybe this would be two linked features
- Exposed API that'll allow this (may already exist)
- xLights integration to automaticially do this
-- Optionally a dropdown to enable/disable this feature (never/always/input only/output only)

**Comment by ghormann** [comment]
FPP already exposes an API that allows FPPD to be restarted.   fppxml.php?command=restartFPPD  Thus, I believe this should be opened with the xLights project instead.

**Comment by dkulp** [comment]
I should also note that xLights already uses it in one case.   If you have the "auto upload on output" checkbox turned on, xLights will restart FPPD automatically (and flip it to bridge mode) when the new configuration is uploaded as part of turning on the output to lights.
