### ISSUE TITLE
Feature Request FSEQ Effect Start Parameter

### ISSUE THREAD

**Issue by psander247** [FalconChristmas/fpp#735]
Hey
Could you add a parameter / option to the FSEQ Effect Start function which will stop all other running effects after enabling the current one?

Usecase:
You could use fpp as a light console to do lightning to a dj
Right now all effects stay running in background wich use processing power and after 100 effects you cant add another one. 

Thanks :)

**Comment by darylc** [comment]
I would suggest that you stop the currently running effects immediately before starting a new one, using the API such as:
http://x.y.z.a/api/command/Effects%20Stop

There are also API commands to stop specific FSEQ Effects and Effect Sequences rather than stopping all effects at once if you prefer.
