### ISSUE TITLE
Minor typos in beta

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#737]
Hostapd tethering, but **"unprecitable"** for ConnMan 
and
JSON Backups made from FPP v1.x are incompatible with the **FPP 3.x system.**

**Comment by ghormann** [comment]
@derwin12   Where do you see the typo with Backups? 

On the backup pag (: http://fppdev.hormann.local/backup.php ) the message was already changed to say **3.x and higher**. 

![image](https://user-images.githubusercontent.com/24968726/83333539-f3497000-a26e-11ea-9e68-8cb2c3b5027f.png)

**Comment by derwin12** [comment]
Gotcha .. after I updated my etcher beta 4 version, the above backup message is there.. Thanks!

**Comment by ghormann** [comment]
Closing.  "unpredictable" addressed as well.
