### ISSUE TITLE
If no pixels are defined in BBB strings, it causes: could not initialize output type BBB48String warning in status page. 

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#741]
If you just add 1 pixel to the setup, it doesn't display the error.  I have not tested with Pi Cap yet. But I will.  I will paste more in when I get back to my PC.

**Comment by libby2cm** [comment]
Just to pile on, i have a pocketscroller v2 and get same error (no pixels attached).

**Comment by dkulp** [comment]
Fixed for 4.1/master
