### ISSUE TITLE
FPP 4.0 doesn't handle "#" (special characters?) in MQTT password

### ISSUE THREAD

**Issue by swampdogmash** [FalconChristmas/fpp#743]
Hi all, just been playing with FPP for the first time and impressed so far. 

Been struggling to get it to connect to mosquitto though... Eventually did a tcpdump on the mosquitto server and noticed that the password was truncated inclusively from the "#" onwards in my password.  (ExamplePassword#01 becomes ExamplePassword sent to the mqtt server and then fails to connect).

I managed to get around this by putting the password in using URL encoding and using %23 instead of the hash in the password. Handy work around, but not sure if it is noted anywhere or possible to permit the special characters in the password field correctly?

**Comment by libby2cm** [comment]
There are escaping issues with special characters in wifi pw's too.. been there for ages.  probably same issue here, doubt it will be fixed.  just change your pw :)
