### ISSUE TITLE
Enhancement request: throttle FSEQ writes and / or network receive to prioritize active playback

### ISSUE THREAD

**Issue by leelindquist** [FalconChristmas/fpp#744]
On a reasonably fast network, if a sequence is actively playing and a new sequence or other media file is uploaded, the currently-playing sequence may temporarily stall, stutter or otherwise produce undesirable output. It seems like files upload to the FPP instances very quickly, and that isn’t necessarily optimal. It would be nice if file system writes and file-receive network throughout could be de-prioritized or throttled back during active playback such that playback stuttering would be less likely.

**Comment by Poporacer** [comment]
@leelindquist Could you tell us if this is still an issue? There have been a ton of code refinements since this issue was posted. We think it is resolved and cannot duplicate with the current version of FPP
