### ISSUE TITLE
FPP 4.0: C-media USB card not outputting audio via FPP

### ISSUE THREAD

**Issue by swampdogmash** [FalconChristmas/fpp#745]
I have a c-media USB sound card. It shows up fine in FPP, but whatever settings I seem to use it refuses to play audio.However, if i go into the /usr/share/alsa/alsa.conf file and change the :

defaults.ctl.card = 2
defaults.pcm.card = 2

to be both equal to 3 (the number of my card), then I can happily use speaker-test -c2 to generate white noise output via headphones connected to the device.

I can select the card in the options in the gui, and select the "speaker" (rather than "mic") from the mixer. I've checked to see if the deviec is muted in alsamixer and it doesn't appear to be. I've tried choosing all of the options for the Audio Output format and rebooting TNA. Not sure why this would happen...

Edit: i'm using a pi zero

**Comment by swampdogmash** [comment]
I've now done some further testing and tried on a pi3b+ as well as on the pi zero. I can't seem to get any audio out via the usb or headphone jack on the pi 3b+ either. I've reverted to fpp 3.6.2 and everything seemed to just work out of the box though

**Comment by patdelaney** [comment]
I have a USB audio dongle on 4.0 and its working fine.  I have a few
questions.
-did you use the image file to go to 4.0 or did you do the in place os
upgrade?
-Are you using and PiHats?
-So you have a picture of the C media dongle, I may have one here in the
lab I can test.

**Comment by 1991mustang50** [comment]
I had V4.0 on pi in place OS upgrade with USB sound blaster play 3 no sound. I tried restarts, reboots,different setting still no sound. I had to go back to beta 1 img on pie and after setting up I got sound. If I get a chance I will do fresh v4.0 install and see if that works if not I will pull logs and post. Had show going tonight so had to get it working for tonight.

**Comment by swampdogmash** [comment]
Hi


Ive not used fpp before so all of these were straight to 4.0 from image


No pi hats in use, these are both pi zero and 3b+ effectively naked as a trial for the moment


Ill grab a picture of the dongle later today.

**Comment by darylc** [comment]
@swampdogmash Is this still an issue in FPP 5.x?

**Comment by swampdogmash** [comment]
I'd have to retest. I reverted to using a pi 3 to eliminate the issue and ended up staying on that. I have a spare pi zero so I will have to give it a test over the next few weeks (although I am on holiday at the moment)

Andy

**Comment by darylc** [comment]
No response from OP, closing
