### ISSUE TITLE
FPP 4.0 - Raspberry Pi B not update DNS resolv.conf

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#749]
Hello,
I am seeing an issue where putting static DNS entries on a Raspberry Pi B does not update the resolv.conf file. This is from a fresh install of 4.0 os and FPP.
I am including the log files from the FPP, Please let me know if additional information is needed.
[FPP_Logs_20200623.2334.zip](https://github.com/FalconChristmas/fpp/files/4822431/FPP_Logs_20200623.2334.zip)

**Comment by neowolfwitch** [comment]
Just seconding this. Editing resolv.conf doesn't work on current Raspberry Pi OS anyway. The only way to get DNS settings to stick is to edit /etc/dhcpcd.conf.

**Comment by marx1** [comment]
@dkulp This is a breaker for 4.0.

**Comment by Tom-Neverwinter** [comment]
same as https://github.com/FalconChristmas/fpp/issues/825

**Comment by ghormann** [comment]
Closing duplicate ticket.
