### ISSUE TITLE
FPP 4.0: Crash Loop with LED panels

### ISSUE THREAD

**Issue by TechplexEngineer** [FalconChristmas/fpp#756]
I have a Pi3 with LED panels connected via a [panel pi hat](https://www.wiredwatts.com/panel-pi-hat)

I got the panels working. Some time later I used xlights to push ddp data to run the show, which worked for a while then the led panels stopped working.

Upon looking at the troubleshooting commands page I noticed the below output from `sudo journalctl -u fppd`

```
Jul 19 18:51:08 matrix systemd[1]: fppd.service: Main process exited,
code=exited, status=1/FAILURE
Jul 19 18:51:09 matrix systemd[1]: fppd.service: Failed with result 'exit-code'.
Jul 19 18:51:09 matrix systemd[1]: Failed to start FPPd.
Jul 19 18:51:09 matrix systemd[1]: fppd.service: Service RestartSec=100ms
expired, scheduling restart.
Jul 19 18:51:09 matrix systemd[1]: fppd.service: Scheduled restart job, restart
counter is at 9072.
Jul 19 18:51:09 matrix systemd[1]: Stopped FPPd.
Jul 19 18:51:09 matrix systemd[1]: Starting FPPd...
Jul 19 18:51:09 matrix fppd_boot_pre[29162]: Setup channel outputs
Jul 19 18:51:09 matrix fppd_boot_pre[29162]: Running pre-start scripts
Jul 19 18:51:10 matrix fppd_boot_pre[29162]: FPP - Turning OFF screen blanking
Jul 19 18:51:10 matrix fppd[29184]: === snd_bcm2835: found that the Pi sound
module is loaded. ===
Jul 19 18:51:10 matrix fppd[29184]: Don't use the built-in sound of the Pi
together with this lib; it is known to be
Jul 19 18:51:10 matrix fppd[29184]: incompatible and cause trouble and hangs
(you can still use external USB sound adapters).
Jul 19 18:51:10 matrix fppd[29184]: See Troubleshooting section in README how
to disable the sound module.
Jul 19 18:51:10 matrix fppd[29184]: You can also run with
--led-no-hardware-pulse to avoid the incompatibility,
Jul 19 18:51:10 matrix fppd[29184]: but you will have more flicker.
Jul 19 18:51:10 matrix fppd[29184]: Exiting; fix the above first or use
--led-no-hardware-pulse
Jul 19 18:51:10 matrix fppd[29184]: 2020-07-19 18:51:10.452 (29184) log.c:228:
```

I was able to fix the error by:
1. create a file in `/etc/modprobe.d/` called blacklist.conf (name doesn't matter) 
2. with a single line of content `blacklist snd_bcm2835` 
3. reboot

I'm not sure why the led panels were working then stopped.

**Comment by cpinkham** [comment]
A reboot should have fixed this.  One of the FPP startup scripts creates this blacklist file if necessary.  I'm not sure why it disappeared on you but it does normally work.

Did you perform a fppos upgrade on this system?  I'm wondering if the blacklist file was removed and not recreated during the next boot.

**Comment by TechplexEngineer** [comment]
No, I did not use the fppos update. This was a clean install. 
I even wiped the SD card and reinstalled the latest FPP which was 4.0 at the time. Still had to manually create the blacklist file. Once I created the blacklist file I haven't had to re-create it.

**Comment by darylc** [comment]
this seems black listed on latested images, I think this is good to close.
