### ISSUE TITLE
API request 'test' button not working from apihelp.php

### ISSUE THREAD

**Issue by idleup** [FalconChristmas/fpp#762]
If clicking the 'test' button from the apihelp.php page it returns 404. Works fine from /api/help.

**Comment by ghormann** [comment]
I just tested with latest build and **not** able to reproduce.  You can see in the header I'm using apihelp.php.  I used the "Test" button for api/commands

![image](https://user-images.githubusercontent.com/24968726/88442851-03e81380-cde4-11ea-8ae8-424c029e2c93.png)

**Comment by dkulp** [comment]
The test buttons that have to go back to the FPPD daemon don't work.  Try the fppd/version one.

**Comment by ghormann** [comment]
Still can't fppd/version works for me on /apihelp.php

![image](https://user-images.githubusercontent.com/24968726/88446758-c8a50f00-cdfa-11ea-92d7-9b003a3d3784.png)

**Comment by ghormann** [comment]
Oh.  Chris fixed it earlier. :-) 6d4b65bc49b0da8b73e4875e17d88faa0fb7104
