### ISSUE TITLE
Should vlc be optional in fpp_so.mk still? 

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#763]
On my FPP development box, I noticed that somewhere been June and July I can no longer cleanly compile FPP w/o VLC installed. No problem, running "./buildVLC.sh" fixed it.... 

However, I notice fpp_so.mk still checks to see if vlc.h is installed.   Shouldn't this just be cleaned up and vlc be a hard dependence with VLCOut.o always being included?   Happy to clean it up, but before I do, wanted some confirmation from someone closer to the code first. 

Code in question: 
```
ifneq ($(wildcard /usr/local/include/vlc/vlc.h),)
LIBS_fpp_so += -L/usr/local/lib -lvlc
OBJECTS_fpp_so += mediaoutput/VLCOut.o
CFLAGS_mediaoutput/mediaoutput.o+=-DHASVLC
endif

```

Error if VLC is not installed. 

/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::VLCOutput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediaOutputStatus*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::~VLCOutput()'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::Close()'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::IsPlaying()'
/usr/bin/ld: ./libfpp.so: undefined reference to `typeinfo for VLCOutput'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::Restart()'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::Start(int)'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::Stop()'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::AdjustSpeed(float)'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::SetVolumeAdjustment(int)'
/usr/bin/ld: ./libfpp.so: undefined reference to `VLCOutput::Process()'

**Comment by dkulp** [comment]
This check could/should now be removed.  It was needed at the time as the only "release images" out there were the 3.6 images which didn't have vlc so folks that were attempting to go from 3.6 to master branch would have had issues.   Now that 4.0 and 4.1 are released and there is an easy path to do the OS level upgrade (fppos file upgrade) and we don't really support the direct 3.6 -> 4x path, the checks are kind of irrelevant.

**Comment by dkulp** [comment]
Either that or the commands would need some +=-DHASVLC flags as well to exclude the "Play Media" FPP Command.
