### ISSUE TITLE
5.0Ghz WiFI band is not working without setting up a country

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#766]
FPP versions: 4.0, 4.1
Hardware: Raspberry Pi 4 (somehow my two Raspberry Pi 3B+ are working with 5.0Ghz without the country code, so this issue seems to be hardware-dependent)
Standard: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

```
root@FPP-210:/home/fpp# iwlist wlan0 scan | grep ESSID
ESSID:"MySSID24"
ESSID:""
_### no any 5.0 GHz networks were found_
root@FPP-210:/home/fpp# wpa_cli -i wlan0 get country
FAIL
root@FPP-210:/home/fpp# wpa_cli -i wlan0 set country "US"
OK
root@FPP-210:/home/fpp# wpa_cli -i wlan0 get country
US
root@FPP-210:/home/fppwpa_cli -i wlan0 save config
FAIL
root@FPP-210:/home/fpp# iwlist wlan0 scan | grep ESSID
ESSID:"MySSID24"
ESSID:"MySSID50"
_### now my 5.0 GHz SSID showed up_
root@FPP-210:/home/fpp#
```

Workaround: added the following line to /etc/rc.local
--- cut ---
wpa_cli -i wlan0 set country "US"
--- cut ---

Proper solution should implement reading /etc/wpa_supplicant/wpa_supplicant.conf config with the country code in it by WPA daemon. Will also require some country drop-down in the Network menu in the UI (or derive code from the timezome).

**Comment by Vlad-Star** [comment]
From the foundation guidelines: https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md

> On the Raspberry Pi 3B+ and Raspberry Pi 4B, you will also need to set the country code, so that the 5GHz networking can choose the correct frequency bands. You can do this using the raspi-config application: select the 'Localisation Options' menu, then 'Change Wi-Fi Country'. Alternatively, you can edit the wpa_supplicant.conf file and add the following. (Note: you need to replace 'GB' with the 2 letter ISO code of your country. See Wikipedia for a list of 2 letter ISO 3166-1 country codes.)
> 
> country=GB

**Comment by fullsaildan** [comment]
Setting the country code via CLI resolves the issue I brought up during the VCS with my K controllers not connecting to my wifi (eero... I know, I know..).  The beagle bones don't seem to use an rc.local file so I haven't found a way to make it persistent yet. Will report back once I've done enough googling on debian startup scripts.

**Comment by dkulp** [comment]
THis is likely something that needs to be setup somehow in /opt/fpp/scripts/functions : SetupFPPNetworkConfigViaConnMann function where we setup all the stuff pertaining to the network and wifi network and such.   Likely should be some sort of setting in the networks page when a wifi adapter is selected and then saved with the config for the wlan0.

**Comment by dkulp** [comment]
I think this is now working on master.   I've added a "WIFI Regulatory Domain" setting on the network page with the list of countries that have regulatory domains.   This is saved in the settings and the functions will now set this for the "iw reg set US" command.    It would be awesome if someone could verify this works outside the US.
