### ISSUE TITLE
MQTT Playlist Management

### ISSUE THREAD

**Issue by DamianFlynn** [FalconChristmas/fpp#767]
Thanks for the the MQTT support, Is it possible to have a command / channel which lists all the current playlists on the FPP instance, this would allow us to then change the play list which is running on the system.

I would like to also be able to use MQTT to start/stop/update plugins, for example update a message on a matrix, or send and updated RDS message to the VAST Plugin

**Comment by ghormann** [comment]
How do you envision the "List all playlist" working?  I see two options.
1) Similar to "Publish Status" where every xx minutes the list of playlist is sent via MQTT.
2) The status is published only when a message is received on another topic.   

Also, if we are going to implement this, I think the result back should be a JSON array that for each playlist contains (at minimum) the name and description of the playlist.    (It could also contain the entire Playlist JSON.)   This would differ from the current API (/api/playlists/playable) which just gives the names of the playlist.

Thoughts?

**Comment by ghormann** [comment]
@DamianFlynn Any input to previous comment?

**Comment by ghormann** [comment]
Closing due to lack of response to request for additional input.
