### ISSUE TITLE
Increase count in LED Panel Layout "Panel Number" Dropdown...

### ISSUE THREAD

**Issue by idleup** [FalconChristmas/fpp#768]
Channel Outputs -> LED Panels.

Dropdown for each panel in the LED Panel Layout Section only goes to "P-16". I currently have 24 panels per output using 32 x 32 P5's which with ColorLight cards are considered on the same Physical output even though they are on 3 different receiver cards. We need that drop-down to go higher like to "P-40" to accommodate panels up to 20-foot across using 32 x 32 panels.

**Comment by darylc** [comment]
I would also like to go more than 16 panels wide for colorlight

**Comment by darylc** [comment]
@ghormann Can we close this one please?

**Comment by ghormann** [comment]
Increased from 16->24 a while ago closing.
