### ISSUE TITLE
Mac address not working for LINSN cards

### ISSUE THREAD

**Issue by smartaleciam** [FalconChristmas/fpp#769]
i do a ipconfig /all and get that mac address (its the same mac address when i do a wireshark from reading frombit7)

how it doesn't matter what mac address i use, the cards will display the last thing they saw while being programmed.
these are the rv908 cards

now i have been able to run the linsn cards once in the past,
 but i remember i had to play about with behind the scene settings to get it working

I would be great full if its possible to look at this linsn card a fpp to still ensure it still works.
thanks alec

**Comment by cpinkham** [comment]
I am going to try to take a look at this before the v6 release, if I can get my Linsn card working again.

**Comment by darylc** [comment]
Linsn support is slated for removal in fpp v7, so will not be fixed.
