### ISSUE TITLE
GPIO outputs has a 5minute delay after bootup or reboot

### ISSUE THREAD

**Issue by smartaleciam** [FalconChristmas/fpp#770]
i have a script that does some GPIO stuff, 
and i noticed at bootup or reboot of the pi that there is like a 5-6min delay till it starts outputting GPIO results
(latest FPP version)

**Comment by patdelaney** [comment]
In an effort to reproduce the issue...

   1. Is this on a Raspberry Pi or BeagleBone?  (and what model)
   2. What does the script do? Can you supply the script?
   3. Have you enabled GPIO logging? Do the logs say anything

Thanks

**Comment by smartaleciam** [comment]
1. rasp pi 3 b+ with oled screen. running 4.1 fpp
2. the playlist plays a event, that event triggers the gpio port #23 (1-26)
on gpio#23 is a logic level converter into a 74ls74 flipflop, to turn on/off the relay.

When the rasp pi boots up or gets freshly rebooted, and i goto my events an trigger gpio#23. nothing will happen for 5minutes. then it will perform like there is no issue after them 5 minutes. 
(it does seem to remember what gpio's got trigged during that 5minutes, then does them all straight away after 5min tho)
i believe it is logging the gpio at info level! but no idea what file that is to send you

**Comment by patdelaney** [comment]
fppd.log file.

Pat

I have some GPIO relays and the rest of the hardware you mentioned. I will
test in the lab.

Pat

**Comment by patdelaney** [comment]
I have tested GPIO outputs on PI B+ and I am not seeing the behavior that
you described. In my test I have a 3 Relay hat that sits on the PI. The
relays are configured for GPIOs 26,20, and 21 respectively. I have a shell
script that turns the relays on and off. I assigned that script to an
event. I assigned each Relay (GPIO) as a channel in the Other tab of the
channel outputs.
[image: image.png]
I created a short sequence in xlights that turns each relay on then off.
I uploaded the fseq to the fpp.
I created a playlist that runs the fseq and then triggers the script.
I created a schedule that would start that playlist as soon as fpp rebooted.
I rebooted and FPP, as soon as FPP was up the relays started clicking away.
I also rebooted and as soon as the FPP web ui was back I triggered the
event and the Relays began to fire.

Admittedly I am not using the same GPIO number or Logic level converter.

I spoke to Dan this afternoon and he suggested that you send us screenshots
of the Playlist, GPIO Outputs, events setup pages. And perhaps a Backup
that we can restore on one of our systems.
Please include a link to the level shifter that you are using.


Pat Delaney

**Comment by darylc** [comment]
lets close this one given the lack of responses from the OP
