### ISSUE TITLE
Raspberry pi Audio jack

### ISSUE THREAD

**Issue by emil-johansen** [FalconChristmas/fpp#771]
I'm on version 4.1 and my raspberry pi won't let me select an audio device. only the dummy device is available, it's not only me having this problem. Hope it's just a simple bugfix :)

**Comment by dkulp** [comment]
Do you have a matrix hat or pixel hat configured?   If so, then it's working as designed and required.   The built in audio cannot be active if the Pi is using any of the normal "hat"s we use.

**Comment by patdelaney** [comment]
Note you can use a USB sound card for audio if you have a pixel hat., like
this one.
https://www.amazon.com/Creative-Labs-70SB173000000-Sound-Blaster/dp/B06XBZ38ZJ/ref=sxts_sxwds-bia-wc-p13n1_0?cv_ct_cx=sound+blaster+usb&dchild=1&keywords=sound+blaster+usb&pd_rd_i=B06XBZ38ZJ&pd_rd_r=f5e109aa-20aa-4db1-9721-fd82be296943&pd_rd_w=c5HEq&pd_rd_wg=fjtiX&pf_rd_p=13bf9bc7-d68d-44c3-9d2e-647020f56802&pf_rd_r=74VVAR3MR4ZC6MWRKY2E&psc=1&qid=1596758668&sr=1-1-791c2399-d602-4248-afbb-8a79de2d236f


Pat

**Comment by ghormann** [comment]
Closing as expected behavior if Hat is configured.   I also tested a 4.1 install on P3 and onboard audio output worked
