### ISSUE TITLE
Enhancement Request - Select destination for remote backup

### ISSUE THREAD

**Issue by andyaz** [FalconChristmas/fpp#778]
I would like to have the ability to select the destination for remote backups.
Example:
I have an external USB 512gb SSD on the master FPP. 
I would like to have a selection of what drive to save backups to on the master FPP.
This away I could steer to the SSD (or other USB drive) when using "Backup to remote" on a remote FPP instance instead of the SD card which is rapidly getting very full.

**Comment by jaredb7** [comment]
Created a PR for this but haven't merged it just in case something comes up & if I make more changes. It's tested and seems to work well.

The only question I have is around the [etc/rsyncd.conf](https://github.com/FalconChristmas/fpp/pull/1479/files#diff-01a16169c59c566ae499330a2cbb5835ddffdd9b78cc2361d64c038fd94481eb) file, how it's used (most likely when FPP is installed I guess) and whether it should be modified to reflect the desired setup IF a [upgrade/75/upgrade.sh](https://github.com/FalconChristmas/fpp/pull/1479/files#diff-d27b24027cb7d3e6b6d514bbddadf68a540f580e7b694e7c3bf1b8c37b538bc2) will add those add those modifications in?

Obviously I need the upgrade script to add the new folder/module to rsync on existing systems, but should etc/rsyncd.conf in this repository stay stock and unmodified and the upgrade scripts will run to make adjustments? 
Or are upgrade scripts skipped on new installs and etc/rsyncd.conf is copied into the systems /etc folder in which case it needs to reflect the desired setup.
