### ISSUE TITLE
Configure spixels clock-speed

### ISSUE THREAD

**Issue by s-p-s** [FalconChristmas/fpp#780]
Hi
Thanks for a great program.
Would it be possible to make an option for configuring the spi clock-speed in the spixels output.

I can see in another hzeller lib that he uses a default clockspeed of 4MHz which seems to cause problems for longer cables or for certain types of emc-protection etc. Lowering to 1MHz (which seems to be an option) or lower would be nice :)

Thank you in advance.
Soeren

**Comment by darylc** [comment]
@s-p-s is feature still of interest to you?

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this.   Of course if someone else feels strongly they can send a pull request to implement it.
