### ISSUE TITLE
Matrix Tools: 4.x master branch Text does not scroll on the Web UI in real time

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#785]
I noticed this problem last night while trying to demo Matrix tools in the Zoom room for troubleshooting panel alignment. Steps to reproduce: Go to the Text tab, Type some text, select Right to left and adjust the speed to fasted. Choose Enable in the State drop down and click GO.
Observed:
The test will crawl from right to left on the physical matrix, but no text appears on the FPP web UI. You can click Sync back button and the will refresh the screen, but it will not scroll in real time on the screen.  It used to work in previous versions. I'm not sure when it broke.

**Comment by cpinkham** [comment]
This seems to be working in current FPP both on my dev and production systems.  I also just pushed patches to both master and MatrixTools to reduce the amount of data being transferred which should help for faster updates.
