### ISSUE TITLE
Modify fsequtils utility to merge multiple files

### ISSUE THREAD

**Issue by idleup** [FalconChristmas/fpp#790]
Example:
/opt/fpp/src/fsequtils -o final_show.fseq -m section1.fseq section2.fseq section3.fseq section4.fseq

It should be iterative always treating the next file parameter as the overlay.

**Comment by dkulp** [comment]
This is already there via multiple -m:
/opt/fpp/src/fsequtils -o final_show.fseq -m section1.fseq -m section2.fseq -m section3.fseq section4.fseq

**Comment by idleup** [comment]
Thank you. I did not think to use the option flag multiple times.
