### ISSUE TITLE
Enhancement:  Flip the button functions when selecting Flipped display with OLED mini-capes

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#794]
When using an OLED with FPP, there is an option to flip the display.  It would be nice if the function of the menu buttons were also flipped so that the up/down/left/right buttons match the flipped display.

Currently if you select flipped display, and orient the board so the display is visually upright, the top button (intuitively "up") moves the menu bar down.  Likewise for the bottom button (intuitively "down") moves the menu bar up.   The left/right buttons work in a similarly backward fashion.

**Comment by darylc** [comment]
The FPP development team met and decided that implementing this would break flipped OLEDs that have already flipped their GPIO's to achieve this in their EEPROMS.
