### ISSUE TITLE
TetherSSID - Add SAVE button

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#796]
Not inutitive to have a SSID - you have to press ENTER after changing the SSID on Tether for FPP. Can we add a SAVE button and then a Reboot flag

**Comment by cpinkham** [comment]
This setting works like pretty much every other setting in FPP, it doesn't have a save button, the change is immediately saved when focus leaves the text box or you hit enter.  I just tested and the reboot flag is set when this field is changed and the red bar appears below the menu instructing the user to reboot.  Not sure what else you are asking for here, but it seems to work as expected.  Reopen if I'm missing something.
