### ISSUE TITLE
Matrix Tools and Pixel Overlay Models

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#806]
It looks like the Matrix tools might take the zoom or aspect ratio of the first loaded Pixel Overlay model and use that for the display of any other selected model. If the first model in the list is rather small, the "Visualizer" display will show correctly, but if you then select a model that is significantly larger, the "visualizer" disappears and any other model selected will no longer show in the "visualizer"

**Comment by cpinkham** [comment]
this issue should be fixed in the current MatrixTools plugin code.
