### ISSUE TITLE
Enhancement: Add ability to change the Blank Screen on Startup time.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#807]
As a tester there are times that I want the to be able to see the console output on the HDMI after a reboot, but then at some point I want it to blank so we don't get burn in on the screen. I would like a way to adjust that time out.

Option 1 add a setting to FPP setting UI
Option 2 Is it something I can SSH into the Pi and change? (but will it be retained after an upgrade?)

**Comment by ghormann** [comment]
Closing as duplicate.
