### ISSUE TITLE
Synchronization between light and audio

### ISSUE THREAD

**Issue by d5tn** [FalconChristmas/fpp#808]
I tried to use FFP as a standalone player for sound synchronous playback of prerecorded light shows.
The shows were recorded with MA2 and the E1.31 data was recorded using xLights capure.  I played the audio sperately using a media server triggered using E1.31.

It all worked, but the timing was messed up completely. Sometimes the recorded sequence was almost twice as fast, sometimes only half the speed of the original show. Therefore synched playback of lights and audio (using FPP playlist or external mediaserver) is not possible at all.

I cannot find a good standalone player out there which is capable of playing back prerecorded shows and audio/video at the same time. Adding this ability could make FPP a powerful tool for professional multivisual/medial installations. 
A solution might be to add an own recorder for external lighting data and offsetting of timing within playlists.

**Comment by ihbar** [comment]
Hello d5tn

I use (I should say we) FPP to play show with light and sound and usually, it is in sync. I have exported data from xlights to FPP in the past, and it was fine. (Output DMX and audio or DMX + video)
Have you tested the sequence under xLights ?  It would be interesting to know if it was ok on xLights or not.

**Comment by d5tn** [comment]
Hey ihbar,

no I didn't test the sequence in xLights as I never used it at all. All data came from GrandMA2 onpc. I just used xLights capture, which is part of xLights but runs as a seperate program. It's solely function is recording of Artnet/E.131 data and storing it into .fseq files that can be played back in FPP. I assume in xLights sequence playback from other sources than xLights is not possible.

**Comment by magdesign** [comment]
Could you find a solution to fix the playback time lags?
having similar issues with recorded sequences from a grandMA and searching for a good fix...

**Comment by cpinkham** [comment]
Try playback in xLights and see if that is in sync with the audio.  if it is, then FPP should be able to play the fseq in sync with the audio.  This sounds like a bad capture to me.
