### ISSUE TITLE
Force to black in Bridge mode.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#809]
When FPP is in Bridge Mode I don't see an option to "force output to black" if E1.31 data has not been received within xx seconds.   Am I missing the setting?  If not, I'm willing to try and implement it.

**Comment by dkulp** [comment]
I don't believe there is one...

**Comment by ghormann** [comment]
So here is my thought on how to implement this.

1) Inside of e131bridge.cpp, instead of calling sequence->SetBridgeData (three locations) create an inline function that first sets a variable to the current time and then calls sequence->SetBridgeData.   This way, this setting works with E1.31, ArtNet, and DDP and we've already validated that the packet is good. 

2) If the delay configuration is greater than 0 seconds, create a background thread that sleeps 1 second and then compares the current time against the time set via the SetBridgeData wrapper.  If the difference is greater than the configuration time, call sequence->BlankSequenceData.   (I don't think there is any reason to call SendBlankingData. )   I'm thinking I should also check that the mode is Bridge before creating this thread, but I'm not 100% sure on that.  

3) For the UI, add a field on channelinputs.php to specify the number of seconds of no input before blanking.   (Seemed more logical than somewhere under settings.)   Would include a "?" icon with hover over help text.  The result would be saved as a Setting and would require a FPPD restart if changed. 

Recommendations?
