### ISSUE TITLE
FPP Only Returns the Ethernet Port and doesn't include WiFi Too

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#810]
This is an issue we've seen twice on the Zoom room in 2 days.  The topology is the standard proxy setup with wifi as management and eth0 being connected to the controller.

FPP Version: 4.2
xLights Version: 2020.39

WiFI config is static (IP/mask/gateway)
LAN config is static (IP/mask only, no gateway)

What's happening is that when we run Tools > FPP connect from xLights the only IP that's returned is eth0.  When we try to manually add the wifi IP that address still doesn't display in the FPP Connect dialog.  

The only way we can get the right IP is to break link on eth0 by unplugging the ethernet cable then doing FPP connect.

I'm just guessing this is a FPP bug since that is where we're making the changes.  I tried to duplicate this myself but have been unable to.

**Comment by dkulp** [comment]
This is a bug in xLights discovery.   Just pushed a fix there.
