### ISSUE TITLE
netmask should not be allowed to be blank (and should auto-fill a default value for all class ranges)

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#811]
Entering an IP address in the 192.168.x.x range will auto-fill a default netmask of 255.255.255.0.  This is good.  However, entering an IP address outside that range does not auto-fill a default netmask and leaves that field blank.  If the user does not enter a value and the netmask remains blank. the IP address is invalid/meaningless and does not get set on the interface (ifconfig shows no IP address an that interface) and therefore the interface does not work even though FPP shows it with an IP address

SUGGESTED SOLUTION:
A default netmask should be provided for ANY IP Address entered.  Ideally, the default value would follow the internic class ranges.  Alternatively, a fixed default mask of 255.255.255.0 would be suitable in most FPP use cases.  The internic ranges are as follows:
Class A    1.x.x.x  - 127.x.x.x  default netmask 255.0.0.0
Class B 128.x.x.x - 191.x.x.x  default netmask 255.255.0.0
Class C 192.x.x.x - 223.x.x.x  default netmask 255.255.255.0
Class D-E (224.x.x.x - 254.x.x.x) should not be allowed as a host IP address.  FPP should block the user from entering a host IP address higher than 224.x.x.x

Supplying a default netmask will help the accidental blank netmask issue.  But the user must still be allowed to alter the netmask if needed.   In any case. the user should not be allowed to enter a blank netmask.

**Comment by ghormann** [comment]
Addressed biggest issues via c8cd4edef40cd42ae7c8cac411be1464cedb70df

* No longer possible to save if IP Empty and Static 
* No longer possible to save if NetMask Empty and Static
* Will auto fill netmask on 192.168.x.x or 10.x.x.x which should be most common.
* Show warning messages for invalid IP values on the page, not just in jGrowl

**Comment by MarkA75160** [comment]
Thanks for the update.  

Auto fill netmask still does not work for 10.x.x.x   
But it does give a warning message and not save if blank.

**Comment by ghormann** [comment]
I just tried using 10.0.0.4 and it pre-filed the netmask and gateway..  Can you give me an example that doesn't work? 
![image](https://user-images.githubusercontent.com/24968726/94176173-b6306b80-fe65-11ea-8c3a-7fcb530e54a2.png)

**Comment by MarkA75160** [comment]
I was using 10.1.1.1  But then I switched to DHCP and then back to STATIC and now it works.  So maybe just needed to refresh that page or something?  In any case it looks good now so you can close it.  Thanks! :)
    On Thursday, September 24, 2020, 12:01:42 PM CDT, Greg Hormann <notifications@github.com> wrote:  
 
 


I just tried using 10.0.0.4 and it pre-filed the netmask and gateway.. Can you give me an example that doesn't work?
