### ISSUE TITLE
LOR Output

### ISSUE THREAD

**Issue by borth79** [FalconChristmas/fpp#814]
I am trying to connect LOR Pixie controllers using FPP on a Raspberry Pi. I am using the LOR USB to RS-485 adapter with a max baud rate of 115200.

When testing my controller, it seems that only 16 channels are being output. I see 5 pixels display all three colors (RGB) and the 6th pixel only displaying red ((5x3)+1=16). I'm assuming that FPP is sending a max of 16 channels with the assumption that it is a 16 channel AC controller.

In xLights on Windows, I am able to get this working using the LOR Optimized protocol. I just can't seem to get the correct configuration in FPP.

If it will work in DMX mode, I will switch.

**Comment by dkulp** [comment]
The LOR optimized protocol is not supported on FPP.   There is currently not a way to use the crappy Pixie controllers.  My strong suggestion is to sell them on eBay and use the money to get a much better controller.  Even the person who wrote the LOR optimized stuff for xLights strongly recommends that.

**Comment by ghormann** [comment]
Closing as answered.
