### ISSUE TITLE
Cannot connect with RPi Zero W

### ISSUE THREAD

**Issue by lrhorer** [FalconChristmas/fpp#815]
When I attempt to connect to a Raspberry Pi Zero W upon installation of 4.2, I get an authentication problem when I try to log in to the FPP hotspot.  Since this is essentially the only way to connect to FPP the first time on a Zero W (I don't have a USB / WiFi adapter), this essentially means I cannot use 4.2 on a Zero W.

**Comment by darylc** [comment]
Can you please provide more detail?

What device/operating system are you trying to connect from, have you tried another device/operating system?  What ssid are you trying to connect to, what password are you entering etc?

**Comment by lrhorer** [comment]
I have not tried this before, but in order for my partner to buy off on this solution, this is going to have to work.  I can easily edit the network parameters manually from one of my Debian servers, but that is not going to work for clients, many of which have never even heard of Linux.

I loaded 3.6, with the same results.  I am trying it on both an Asus laptop running Windows 10 and a Motorola phone running Android with the same failure.  It just won't authenticate after a number of retries.

SSID: FPP
Passphrase: christmas

**Comment by lrhorer** [comment]
Pfft!  The passphrase "Christmas" has to be capitalized.
