### ISSUE TITLE
Sync issues with MP4 Video files

### ISSUE THREAD

**Issue by ChasingTraction** [FalconChristmas/fpp#816]
2020.30-40 xlights version tested
Pi4b 3gb and 3b+ tested
FPP 4.0, 4.1 and 4.2 tested. 

When using an mp4 video file as media file in xlights, sent via FPP connect, the video and audio is played via the FPP around 500ms before the e1.31 data is processed and sent out. This issue is not present when using xschedule to play.

**Comment by patdelaney** [comment]
an you send us the mp4 file
Thanks

Pat

**Comment by ChasingTraction** [comment]
https://drive.google.com/file/d/1BhXMvg1HC623ICQQgs12wsOaDSBnjfMA/view?usp=sharing

**Comment by patdelaney** [comment]
OK I have the video and a couple of things... We're (me) are probably going to need the xlights project. so we can reproduce it. I initially misunderstood what you were reporting as I only saw this on my phone. I thought the issue was video multisync. But I think what you are saying is that you are using an MP4 as the audio file and just sequencing that to that. Am I close?
1) Are you outputting the the video to a projector or a monitor of some sort?
2) Is this just a single FPP and no remote FPPs?

**Comment by ChasingTraction** [comment]
Hi Pat,

yes I have a sync issue with fpp from a pi 3b+ or pi 4 2gb outputting E1.31
delayed by around 400ms while using mp4 videos in all of my sequences -
it's the same on both Pi's ( I am solving this by bumping all of the
effects and beat tracks in xlights to the left slightly )

I do have another issue with xlights with the video window rendering black
but that is on another issue on the xlights git. the hdmi output from the
pi is always perfect

1) Video is running direct from the PI HDMI Output and is 100% in sync with
the audio - e1.31 data is delayed by approx 400ms
2) I have tried with remote and master only configurations, in both cases
the video and audio plays first, e1.31 data is delayed



sequence here
https://drive.google.com/file/d/1BWBcbLnc6N43bA0WOuGkNIRQqXTZ2FJI/view?usp=sharing

**Comment by patdelaney** [comment]
Please note, I am not the guy that will fix this. I am just gathering the
information that the developers will probably need to track it down.

Pat

**Comment by darylc** [comment]
@ChasingTraction Is this still an issue in FPP 5.x?

**Comment by ChasingTraction** [comment]
I narrowed it down to a very narrow use case bug - its based with Windows 10 N Edition, with the media pack installed. It does not happen with the regular windows 10 editions

**Comment by ChasingTraction** [comment]
I managed to find what the issue was and workaround it, but it still happens in 5.x - it seems to happen when you are using unicast to a controller that doesnt exist on the network, EG have 4x controllers and 1 is not online, for some reason the master plays the audio and video well before sending the data to the controllers, when all controllers are online this does not happen and everything plays in sync. 

Using static IP's on a cisco C9300-48T-A with Ubiquiti USG router

**Comment by darylc** [comment]
Yeah sending unicast to a controller that doesn't exist causes problems until fpp notices and disables those controllers.  Closing this.
