### ISSUE TITLE
DDP One Based Doesn't Work in Multisync

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#818]
Software Versions:
- FPP & FPP OS: v4.2 (via 4.2 etch)
- xLights: 2020.40

Topology:
- All mgmt traffic via wlan to Pis
- Master Pi with eth0 cabled to a Falcon
- Remote Pi with HDMI to a TV

Configuration
- Controller 1: e1.31 proxied to the falcon
- Controller 2: Pi set as "xLights Only", DDP, **UNCHECKED** Keep Channel Numbers

Does not work
- FSEQ files being played from master through multisync play fine on Falcon but do not work on the virtual matrix
- FSEQ files being played directly on the remote but in standalone mode do not display on the virtual matrix

Workaround
Enabling the keep channel numbers in the xLights controllers tab and changing the start channel on the virtual matrix within the Pi resolves the issue.

Expected Behavior
The multisync protocol will account for the start channel flag.

Additional comments
The main reason I think the one based DDP channel numbers should work as above is when adding additional FPP based devices to existing layouts they will be placed at the bottom of the list.  Yes, the new DDP device can (and should) be moved to the top of the list but that's not always practical for users that don't use the newer "auto layout models".  This leaves users chasing channel numbers as they modify their props.

**Comment by dkulp** [comment]
This is working 100% as designed and will not be changed.   If running in a mode that uses the fseq file as a source of channel data, the channel number that are configured for the outputs has to match the equivalent channel ranges in the fseq file.  An fseq file cannot have "multiple channel 1's" and it also has no concept of controllers or anything.   When configuring an FPP controller in xLights, it SHOULD have the Keep Channel Numbers turned on or you are definitely likely to have a lot of issues going into and out of bridge mode and other modes.
