### ISSUE TITLE
Virtual Matrix With Channel Offset Doesn't Fully Display

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#819]
Summary:
When doing a channel offset on a virtual matrix in the layout tab of xLigths testing directly from xLights doesn't show on the TV properly, only about the top 1/6th of the screen.  However, if I save & upload the fseq file to the Pi everything works properly.

Configuration:
FPP set for virtual matrix with start channel of 100000 and size of 256 x 144.
xLights model set to my Pi as !Pi-VM:100000
Same result with both e1.31 and DDP

Tests:
Sending bars from xLights with FPP in bridge mode does not work
Saving & Uploading the fseq with FPP Connect works fine

Workaround:
Changing the start channel from 100000 to 1 in both xLights model & Other tab of FPP fully fixed the issue.

**Comment by darylc** [comment]
I am having this problem too.  The work around doesn't work when you have 2 virtual matrixes on a single FPP instance

**Comment by dkulp** [comment]
Would need to see the full xLights setup and virtual matrix configs.  For the above, you would need at least 136864 channels for Pi-VM. And even that would only work if Pi-VM is the first controller in your list.  In FPP, the start channel is the ABSOLUTE start channel for the show/fseq file.

**Comment by darylc** [comment]
lets close this out, I no longer have the exact setup that was failing, I'll reopen if I experience the issue again
