### ISSUE TITLE
Weird LOR issue

### ISSUE THREAD

**Issue by Darkpoof** [FalconChristmas/fpp#820]
Maybe someone who knows FPP and coding better then me can help me understand this one......

I used this same set up last year without issue.
I have 4 LOR1602W boxes and a LOR 16ch low voltage controller all running off a Pi 3B+ with the usb LOR dongle. 
Now FPP can't seem to control box #1 set to any address, however it controls all other ch's perfectly.... Here is the strange part, the box functions perfectly when i try running it from LOR software. 
It seems the box is seeing a network connection and passing data, just seems FPP is not telling the first 16 chs to work.

Anyone got any thoughts? cause i have tried every way i can think of to troubleshoot this, short of changing out the box or board as that is where the Pi is mounted and i dont want to have to customize another one lol.

**Comment by ghormann** [comment]
* What Version of FPP?
* Are the box ID's consecutive? e.g 1,2,3,4
* Can you share your configuration for LOR: Example below

![image](https://user-images.githubusercontent.com/24968726/95134591-24f8a900-0731-11eb-93aa-e5898e6b568d.png)

**Comment by Darkpoof** [comment]
Yes of course!Version 4.1Boxes are consecutive I just finished 1 last test, any box set to id 01 does not fire que's1 LOR network start ch1 end ch80 port ttyusb0 speed at 19200 and first controller set at 1

Sent from Yahoo Mail 
 
  On Mon, Oct 5, 2020 at 4:35 PM, Greg Hormann<notifications@github.com> wrote:   

   
   - What Version of FPP?
   - Are the box ID's consecutive? e.g 1,2,3,4
   - Can you share your configuration for LOR: Example below

**Comment by Darkpoof** [comment]
So it got weirder.......
I changed my channel layout to have 16 blank ch's to skip the first box issue and changer box id's to match, and then hit play.... BAM lights up!!!!!
When i go into test mode and go ch by ch the first 16 ch's should be blank..... they are not! In test mode what is wired and programmed to be ch 17 turns on when you turn on ch 1.
Does this make sense to anyone? or is it just me?

**Comment by ghormann** [comment]
Not even sure I have an LOR device around to try and reproduce, but can you send your log and configuration files?   To do so, on the File Manager, go to logs, click "zip" and then attach the resulting file.

![image](https://user-images.githubusercontent.com/24968726/95400233-1993b200-08d8-11eb-8e00-d531427da9e2.png)

**Comment by Darkpoof** [comment]
[FPP_Logs_20201004.2217.zip](https://github.com/FalconChristmas/fpp/files/5344615/FPP_Logs_20201004.2217.zip)

**Comment by patdelaney** [comment]
@ghormann I have some LOR 16 channel boxes I can help you debug with if needed.

**Comment by ghormann** [comment]
I'll look at what I have in storage this weekend.   I can't remember if I saved any LOR boxes or not.  (If I did, it was a 8 channel one).   

I did look at the log files last night. When you say *"I changed my channel layout to have 16 blank ch's to skip the first box"* do you mean in xLights or fpp?   The log file shows multiple fppd restarts with different configuration, but each time it shows channel 0 (which is really 1) as the starting channel for the LOR driver.   (At least I **believe** that is what it showsI'm still learning the channeloutput code.)    

The log file shows it is mapping to 0-95
```
2020-10-04 16:47:30.891 (1272) channeloutput/channeloutput.c:359: LOR 0:  Determined range needed 0 - 95
2020-10-04 16:47:30.891 (1272) channeloutput/channeloutput.c:399: Determined range needed 0 - 95
```

And the co-configuration file also shows the first the first channel as 1 (not 17).   
```
{
	"channelOutputs": [
		{
			"enabled": 1,
			"type": "LOR",
			"startChannel": 1,
			"channelCount": 96,
			"device": "ttyUSB0",
			"speed": 19200,
			"firstControllerId": 1
		}
	]
}
```

**Comment by Darkpoof** [comment]
I added the blank 16 chs in xlights and just changed the fpp ch output settings to be start ch 1 end ch 96.
what i meant by 17 is that after changing the box IDs to skip box 1, ch 1 of box 2 should turn on as ch 17 but it turns on when you put ch 1 in test mode.
The lots of restarts for changes was me trying different things to see if it would make something reset or w/e. But yes that ch output is correct for what im running currently.

Last night i had another freak out that i am still trying to figure out, I have 3 songs playing "correctly" (lmao) and then i play a 4th and it plays back with the boxes out of order ie... 1 plays what 3 should, 4 and 5 are swapped 2 thinks its 1 and 3 is 2..... i am checking files and trying it all over again but one of the strangest things ive seen, and w/o reboot i went to test mode and chs worked right. All files made the same way same day.
If i dont find something in the programming or files, I will probably try making a new fpp card and see if starting over will fix it cause it seems something is not dealing with ch output right.

**Comment by Darkpoof** [comment]
ok so re-did file and new upload plays fine.... guess corrupted transfer???

**Comment by ghormann** [comment]
So I'm guessing (no data) something was either not transferred correctly or the sequence file was not fully updated/saved in xLights.  
There is no evidence of it in the FPP logs (from what I can see) of anything wrong with FPP.  if I understand correctly, ch1 in xLights is not correctly displaying as channel 1 (mapped to LOR box 1) in fpp.  

OK to close this issue?

**Comment by Darkpoof** [comment]
it still will not play a box set to id 01

**Comment by ghormann** [comment]
K.  I'll try and look at it more this weekend unless someone beats me too it.  

Also potentially related: https://www.facebook.com/groups/FalconPlayer/permalink/2765995450342087

**Comment by Darkpoof** [comment]
sounded like it, but i have swapped boxes and no change. It truly seems to see all the unit ids as 1 lower then they are set to, so for 1 to work needs to be set to 2.... 2 to 3 and so on and then works ok just at wrong addressing.

**Comment by ghormann** [comment]
I have a few very old LOR controllers, but no USB adaptor. ;-(   I'm not going to be able to look into this.  Sorry. 

In the facebook thread I linked earlier, someone else got LOR working with unit 4 and channel 65-80 which would be correct.  Based what I see in the logs (and that someone else got it working) I struggle to believe fpp has an off-by-one on the box id problem.

**Comment by Darkpoof** [comment]
Well then i guess either i have my address off by 1 or just let LOR run the show and take fpp out.
Thanks for looking.

**Comment by patdelaney** [comment]
Greg- I can confirm that this is an issue. I finally had time to test in the lab.
Scenario 1
2 LOR controllers (ID1 and ID2)
Connect controllers to a FALCON F48, that is configured to DMX on Port 3 of Falcon board
Plug AC lights into CTRL 1  port 2 and CTRL 2 ports 1 and 16 (17 and 32 for channels)
Configure xLights to talk to FALCON controller and test CH1 CH17 and CH32.  All work as expected

Scenario 2
2 LOR controllers (ID1 and ID2)
Connect controllers to LOR Dongle that is attached to PI USB0

Plug AC lights into CTRL 1  port 2 and CTRL 2 ports 1 and 16 (17 and 32 for channels)
Turn on Display Testing in FPP
Select channel 1  (Port 1 on controller 2 lights up)
Select channel 16 (Port 16 on controller 2 lights up)

**HACK WORK AROUND**  
You can manually edit co-other.json in the /home/fpp/config folder
change the firstControllerId":    to 0
save the file restart fppd   

I tested and that should work, but **don't make any changes** to the Other Tab in Channel outputs as it will overwrite that setting. Until it gets fixed.

**Comment by ghormann** [comment]
@patdelaney  @Darkpoof There is a potential fix in Master based on the workaround reported above.   It is totally untested as I don't have an LOR test system.

**Comment by Darkpoof** [comment]
i will try that here shortly and let you know

**Comment by patdelaney** [comment]
I pulled in Master and it is working.

**Comment by ghormann** [comment]
Thanks @patdelaney   Will close the issue as resolved.
