### ISSUE TITLE
Playlist duration does not properly display over 99 minutes 

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#824]
When FPP displays Playlist total time it appears to be using a mm:ss format mask which displays incorrectly for durations longer than 99 minutes.   For example, a 2-hour playlist (120 minutes) displays as 20:00 instead of 120:00 (or 2:00:00).

Request the format mask be changed to mmm:ss or hh:mm:ss

**Comment by ghormann** [comment]
Appears addressed by b916aa139264be511be31389340d559c6e7a07c4 in master
