### ISSUE TITLE
In Version 4.2, /etc/resolv.conf is not saving the DNS that is in the GUI

### ISSUE THREAD

**Issue by drums114** [FalconChristmas/fpp#825]
Had to manually update the /etc/resolv.conf file (thanks to Ben Shaver!) to download a EDM RDS plugin.  The file is currently not updating the DNS server that is in the GUI.  In the GUI I have 192.168.1.1 however in the /etc/resolv.conf file it stays at 127.0.0.1.

**Comment by dkulp** [comment]
FYI:   /etc/resovl.conf file should be a sym-link to the connman generated file.   Any changes you make there should get wiped out next time you boot.

**Comment by drums114** [comment]
The the problem.  It is not saving what is set in the GUI.  I even confirmed this with Ben Shaver this morning.  Once I updated the file to the correct DNS of 192.168.1.1, it was able to get to the outside world and download the plugins no problem.

**Comment by mover85** [comment]
I have the same problem. It looks like dnsmasq is overwriting resolv.conf. Disabling dnsmasq and rebooting fixes it.

**Comment by drums114** [comment]
Is this ticket still open or is it resolved?

**Comment by neowolfwitch** [comment]
This seemed to be fixed in later versions, but seems to have returned in v4.5.1-3 (possibly earlier and later versions).
I had to manually set a DNS server (1.1.1.1) in /etc/resolve.conf to get NTP and Git updates to work. I suspect it will get wiped out on the next reboot. I opened another ticket specific to that version.

**Comment by drums114** [comment]
> 
> 
> This seemed to be fixed in later versions, but seems to have returned in v4.5.1-3 (possibly earlier and later versions).
> I had to manually set a DNS server (1.1.1.1) in /etc/resolve.conf to get NTP and Git updates to work. I suspect it will get wiped out on the next reboot. I opened another ticket specific to that version.

I am glad it's just not me experiencing this.

**Comment by darylc** [comment]
Is this still a problem in 5.0?

**Comment by drums114** [comment]
I am not sure, haven't tested it again.

Mark Tarkowski
***@***.******@***.***>
1-847-312-3702

________________________________

**Comment by darylc** [comment]
@ghormann lets close this one
