### ISSUE TITLE
Schedule lights without sequence

### ISSUE THREAD

**Issue by DrewADennis** [FalconChristmas/fpp#826]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would it be possible to schedule a solid color / brightness without needing a sequence. Using a PI/pihat to run landscape lights. It would be cool to just tell it color / brightness and time on/off.  I'm running them as a sequence now, and they blink when the sequence resets. If there was a way to run with no sequence this would be eliminated

**Describe alternatives you've considered**
running a simple sequence that only turns on solid color.

**Additional context**

**Comment by MarkA75160** [comment]
They should not blink with a repeating sequence as long as these two things are true:

1.  make sure your sequence starts and ends with the lights ON.  Often the very end of a sequence will end (or fade) off.  Make sure your ON effect starts at the absolute beginning goes all the way to the very end (or beyond)

2.  make sure  you have "blank between sequences" turned off in FPP.  (under FPP Settings -> Playback)

**Comment by cpinkham** [comment]
Create an Overlay model and use the "Overlay Model State" FPP Command in a playlist to turn the model on and then the "Overlay Model Fill" FPP Command to set the color of the model.  When done, run another playlist that uses the Clear command to turn the lights off and then the State command again to turn the model off.

**Comment by cpinkham** [comment]
Closing this ticket since this can be accomplished using existing FPP Commands.
