### ISSUE TITLE
Look into integrating new Pi pixel output methods with DMA and SMI

### ISSUE THREAD

**Issue by leelindquist** [FalconChristmas/fpp#827]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I just read about this development today, and thought I'd share it with the FPP developers.

**Describe alternatives you've considered**
BBBs work great, but the Pi is cheaper. If this method can get more useful high-speed I/O performance out of the Pi then I think it's worth looking into.

**Additional context**

https://iosoft.blog/2020/09/29/raspberry-pi-multi-channel-ws2812/

**Comment by cpinkham** [comment]
Closing this ticket in favor of #1237 which allows up to 24 strings of pixels via the Pi's 40-pin connector by using the DPI24 framebuffer to drive pixels on 24 GPIO pins.
