### ISSUE TITLE
4.3 failed update

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#829]
4.2 on Pi 3 - master of the master remote. Just pressed the upgrade/update in the About 4.2 screen.

Log shows this..

Stopping fppd...
==========================================================================
Pulling in updates...
Upgrading git revision from branch master
fatal: unable to find remote helper for 'https'

Then goes downhill from there..

rm: cannot remove 'log.o': Structure needs cleaning
rm: cannot remove 'fppversion.o': Structure needs cleaning
rm: cannot remove 'events.o': Structure needs cleaning
rm: cannot remove 'falcon.o': Structure needs cleaning
rm: cannot remove 'fppversion.o': Structure needs cleaning
rm: cannot remove 'FrameBuffer.o': Structure needs cleaning
rm: cannot remove 'gpio.o': Structure needs cleaning
rm: cannot remove 'httpAPI.o': Structure needs cleaning
rm: cannot remove 'log.o': Structure needs cleaning
rm: cannot remove 'FPPLocale.o': Structure needs cleaning
rm: cannot remove 'MultiSync.o': Structure needs cleaning
rm: cannot remove 'mediadetails.o': Structure needs cleaning
rm: cannot remove 'mediaoutput/MediaOutputBase.o': Structure needs cleaning
rm: cannot remove 'mediaoutput/omxplayer.o': Structure needs cleaning
rm: cannot remove 'ping.o': Structure needs cleaning
rm: cannot remove 'fppversion.o': Structure needs cleaning
rm: cannot remove 'log.o': Structure needs cleaning
rm: cannot remove 'log.o': Structure needs cleaning
rm: cannot remove 'fppversion.o': Structure needs cleaning
rm: cannot remove 'log.o': Structure needs cleaning
rm: cannot remove 'fppversion.o': Structure needs cleaning

etc.

I end up with ": vUnknown (Unknown branch)"
and using Developer I cant go back to 4.2 or ahead to master. Seems dead .. looks like a re-image but thought I should post this.

**Comment by ghormann** [comment]
"Structure needs cleaning" almost always means there is some type of underlying filesystem corruption.   (Probably started before the ugprade, but the upgrade just changes so many files it becomes very obvious.).   Your best bet is to reformat, install the latest image, and restore from your last backup.
