### ISSUE TITLE
fppmm parsing allows ugly values

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#83]
I was going through testing individual channels using renard output with the fppmm application and accidentally passed it a typo.  It happily parsed a typo as somewhat good data.

pi@FPP /opt/fpp/bin $ ./fppmm -c 3-s 50
Set memory mapped channel 3 to 0

Note no space between 3 and "-s", yet the 3 was parsed, but the rest was ignored.

**Comment by darylc** [comment]
This is ancient, and the reported case now returns an error.  I propose we close this.

root@FPP:/opt/fpp/bin.pi# ./fppmm -c 3-s3
Response: Internal Error
