### ISSUE TITLE
F40D Cape Prevents FPPD From Starting after FPPOS Upgrade to 4.3 

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#830]
**FPP Version and Hardware**: 
4.3 on F40 (not K40)

**Describe the bug and Steps to reproduce**: 
Upgraded from 4.2 to 4.3 via FPPOS

**Expected behavior**: 
The FPPD process runs.

**Additional context**: 
If the BBB String cape is disabled then FPP starts.  I demonstrated this for Rick Harris in Zoom.  Also tried to delete all pixel overlay models with no success.
[FPP_Logs_20201014.0315.zip](https://github.com/FalconChristmas/fpp/files/5375382/FPP_Logs_20201014.0315.zip)

**Comment by dkulp** [comment]
Thanks for the logs/config files.   I was able to duplicate with your configs.   Just pushed a fix to v4.3 branch (and master)
