### ISSUE TITLE
Support for USB wireless devices that require a mode switch to work on Linux

### ISSUE THREAD

**Issue by netgodsrdn2** [FalconChristmas/fpp#832]
I found a USB wireless device that works well, but requires a mode switch to work with Linux.

I'm guessing there are other "driver free" adapters that we could add support for via this method as well. But this particular device I found on Amazon here - https://www.amazon.com/gp/product/B07LFC7VDC/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

To make it work we need to create /lib/udev/rules.d/41-fpp-usb.rules

And add the following to that file:

    # Part of usb-modeswitch-data, version 20170806
    #
    # Works with usb_modeswitch versions >= 2.4.0. Slash before %k parameter
    # is for compatibility only. Versions >= 2.5.0 don't need it.
    # 
    ACTION!="add|change", GOTO="modeswitch_rules_end"

    # Realtek 8821CU USB Wifi
    ATTR{idVendor}=="0bda", ATTR{idProduct}=="1a2b", RUN+="/usr/sbin/usb_modeswitch -K -v 0bda -p 1a2b"

    LABEL="modeswitch_rules_end"

Once that is created fpp will find the device and has worked great for me so far. If anybody thinks it would be useful, I can put something together explaining how I figured this out. Let me know.

**Comment by darylc** [comment]
The FPP development team met and decided not to implement this as a feature in the UI.
