### ISSUE TITLE
Enhancement Request: Upgrade offline Slaves from online Master.

### ISSUE THREAD

**Issue by bwellman989** [FalconChristmas/fpp#833]
When you have multi FPP systems and they are configured in a Master\Remote setup, with only one FPP able to reach the internet to preform an update.  The master should act as a hub and replicate the update package to the remote systems when you click Upgrade FPP in MultiSync.

Please see my attachments on how I'm setup and such.

Also please feel free to reach out to me if you don't understand.
[Upgrade offline Slaves from online Master.mpr.zip](https://github.com/FalconChristmas/fpp/files/5389163/Upgrade.offline.Slaves.from.online.Master.mpr.zip)
![Upgrade offline Slaves from online Master](https://user-images.githubusercontent.com/72953739/96212978-885ab600-0f3d-11eb-9b21-fcd31f622401.jpg)

**Comment by bigwavedave42** [comment]
This sounds fairly similar to the existing option.  on the About page, by the Upgrade, I can choose where to get the update.  I can choose github.com or from one of the other devices on the network.  The host i choose could be the Master:

![image](https://user-images.githubusercontent.com/11801385/96219825-788ea200-0f3c-11eb-9093-bbfe7930a641.png)

Is that different than what you are suggesting?

**Comment by bigwavedave42** [comment]
Another thought... this is more of a "pull" from the Master.  Perhaps you are wanting to "push" from the master to the slaves?  Magically upgrade them all from one view/location/UI?

**Comment by bwellman989** [comment]
@bigwavedave42, yes.  What I'm think is a hub and spoke replication of the git Dir. for the ones that cannot reach the internet, they could either pull of have the update pushed to them from whichever system has the update from github.

and yes, it is a little different then the current design, as I there is not an option to change the FPP Upgrade Source for the remotes when FPP is configured in the master\remote configuration. 

here is what I on the about page for my master that is online.

![Online-Master](https://user-images.githubusercontent.com/72953739/96224550-69681e00-0f55-11eb-8af1-73c3c42f9532.jpg)


and what I see from the offline-remote

![offline Remote](https://user-images.githubusercontent.com/72953739/96224777-b9df7b80-0f55-11eb-83b2-26f499999b9e.jpg)

**Comment by bigwavedave42** [comment]
Interesting.  My remote is able to choose the Master as the upgrade source.  However, all of my FPPs are "online" and can access the internet too.

**Comment by bwellman989** [comment]
@bigwavedave42 - That was my thought.  Hence why I didn't write this up as a bug.  I felt everything is working as designed and meets users requirements, then their are maybe a few that need something like this.

**Comment by bigwavedave42** [comment]
Yeah, I wonder if it is actually expected to already work that way?  Regardless, seems like a valid use case.

**Comment by MarkA75160** [comment]
> Interesting. My remote is able to choose the Master as the upgrade source. However, all of my FPPs are "online" and can access the internet too.

Same for me too.  I've been updating my remotes from the master and even some remotes from other remotes.  However my remotes do have internet access to get the time, but I wouldn't think they should need it to pull updates from an other FPP that it can access locally

**Comment by cpinkham** [comment]
@bwellman989 You have to set your UI Level to something higher than the default 'basic' level to see the FPP Upgrade Source setting on the About page.  This is an advanced setting and not something most users need to mess with.

**Comment by bwellman989** [comment]
Ok.

But my thought is that if I using the multi-sync function and I tell it to preform an update to all the remotes, then if they do not have access to the internet, they then should use the master (or which ever one has the highest version) as the source automatically.

I shouldn’t have to go to each one individually and change the up level, then go to it’s about page, then change the source and update, when you offer the feature to update fpp’s in multi-sync.  That defeats the purpose of having that.

**Comment by cpinkham** [comment]
So it sounds like you are really looking for a new "Upgrade Remote FPP system from Master" Action on the MultiSync page which is shown only on the master.  Selecting a few remotes and running that action would tell the remotes to upgrade from the master.  I can see that being useful.  It wouldn't even have to be just a master, it could be just "Upgrade Remote FPP system from this system" since there is a chance the system with internet connectivity may not be in master mode.

**Comment by bwellman989** [comment]
Yes exactly.

I think it would be a good feature for people that run more then one rpi or bbb.

**Comment by MarkA75160** [comment]
>  I shouldn’t have to go to each one individually and change the up level, then go to it’s about page, then change the source and update, when you offer the feature to update fpp’s in multi-sync. That defeats the purpose of having that.
> 

You don't have to change each one every time.  You only set it once.   This allows you to have a mix of some going to github, some going to the Master, and even have some remotes pulling from other remotes.   Once you set the preference, it stays that way and gets used with the multi-sync Upgrade option.    I have my remotes set to pull from Master and use Multisync Update FPP to update them and the pull from the Master.

**Comment by MarkA75160** [comment]
Can this be closed?  I believe the requested functionality is already there.

**Comment by bwellman989** [comment]
It is up to you guys as it is your product.
