### ISSUE TITLE
no static ip address

### ISSUE THREAD

**Issue by Wali79** [FalconChristmas/fpp#836]
*FPP 4.3 running on RPI 3*

Hi all,

As soon as I changed the IP address to static, my raspberry no longer has an IP address ??
What to do ??

Tank's

Steve

**Comment by bigwavedave42** [comment]
Can you post a screenshot of your networking page with the static IP address configuration?  

It looks like you edited your issue, but originally mentioned 192.168.8.x showing up. That is often an indication that FPP has gone into the tethering mode, because it didn't see a valid network connection elsewhere.

**Comment by ghormann** [comment]
Also, attching the logs may help: 

To create the file:
1. Open the FPP UI
2. Open the FOn the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by Wali79** [comment]
1: I changed the address
2: update interface
3: restart network
4: shutdown
5: DC off
6: DC ON
... and no address

I do not have the log file because I can no longer access the RPI
![Screen Shot 10-18-20 at 06 33 PM](https://user-images.githubusercontent.com/54595682/96374262-f38cce00-1171-11eb-8a4a-7af586e4320d.PNG)
![Screen Shot 10-18-20 at 06 41 PM](https://user-images.githubusercontent.com/54595682/96374264-f687be80-1171-11eb-9626-4fb682d5776f.PNG)

**Comment by bigwavedave42** [comment]
It looks like you're measuring whether it is up/down by the network share?

What happens if you try to go to http://192.168.1.107 in your browser, once the static IP is set? 

Can you ping 192.168.1.107?

**Comment by Wali79** [comment]
Shame on me,

The address I entered was already in use by another ring road.

Thanks to you bigwavedave42 for putting me on the right track.

I close this problem
