### ISSUE TITLE
mOUSE NOT VISIBLE

### ISSUE THREAD

**Issue by jyddentz** [FalconChristmas/fpp#837]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the FOn the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

mY MOUSE WILL WORK WITH MY rASBERRY pi 4b. When I have FPP running, my mouse is not visible. I need help with this please.  Thank you.

**Comment by bigwavedave42** [comment]
This sounds like you might have downloaded/imaged the "kiosk" version of FPP.  If so, please reimage with the normal (non-kiosk) version of FPP.  The kiosk mode version is for a more advanced use case.  In normal operation, you'll never need a mouse for your FPP.  You will install it, find the IP and then access it via web browser on a separate machine/device with that IP in the browser URL.

**Comment by jyddentz** [comment]
I got it working.  Thank you for your time and assistance

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
