### ISSUE TITLE
Enhancement: Expose Blank screen on startup time setting in Advanced UI

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#838]
**Is your feature request related to a problem? Please describe.**
There are times when troubleshooting or QA testing that I'd like the FPP console not to blank out so quickly. I do want it to blank, but I'd like the option to set the time longer before it does. Either a Dropdown list of times or just a text box to enter the number of minutes to wait before blanking would be great.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghormann** [comment]
@patdelaney  Is this the same as #807 ?

**Comment by patdelaney** [comment]
Yes  OMG my poor brain is failing,  you can merge them

**Comment by darylc** [comment]
This seems like a pretty specialized feature.  Do we really want to implement it?

**Comment by patdelaney** [comment]
Yes or at least to know how to go in under the covers to change the
setting. The feature can be added to the developer view so the average user
doesn't need to see it.

**Comment by cpinkham** [comment]
I have a patch for this, I just need to test on a Pi.

**Comment by patdelaney** [comment]
I can test it  is it in Master?

**Comment by cpinkham** [comment]
I'll look at testing and putting this patch in master after v4.6 is cut.

**Comment by cpinkham** [comment]
I pushed this to the master branch, it is a developer level setting so only shows up when the UI level is set to Developer.  Once you enable the screensaver setting, a new child setting should appear to let you set the timeout in minutes.  If this works for you, can you close the ticket?

**Comment by patdelaney** [comment]
Tested and confirmed on a Pi-Zero
