### ISSUE TITLE
Ability to Test All Channels Assigned to an Output of any Type (e131, Other, BBB String, PiHat, etc)

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#839]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to test per port via the "Display Testing" menu.  Specifically, I would like to expose another dropdown to the right of the "Models" dropdown that is auto populated based on what is enabled on the various "Channel Output" tabs.  Maybe even some hierarchy.
* e1.31 / ArtNet / DDP (if enabled is exposed)
** Controller line 1
** Controller line 2
* BBB Strings (if enabled)
** Port N would test all channels assigned to the port
** Port N+1 would test all channels assigned to the port
* Virtual Matrix (if enabled)
* Other (if enabled)
** One line per enabled output

Essentially for every single line item on any of the output tabs there would be an automated mechanism to send e131/ddp/artnet/ws281x output for those that are configured.  No switching between tabs or guessing at models that are plugged into a port.

**Describe alternatives you've considered**
This is workable by manually entering channel ranges on the Display Testing box.  Also, if you have "Pixel Overlay Models" enabled you can also somewhat test this today with a per model setting but not if doing chaining.

**Additional context**
None

**Comment by MarkA75160** [comment]
I like this idea

**Comment by darylc** [comment]
The FPP development team met and discussed this issue.  It was decided that a more targeted approach will be taken - eg the test mode on the led panel output page, the test mode on the BBB strings page etc.  Further work has occurred recently on the BBB strings testing - eg https://github.com/FalconChristmas/fpp/commit/690d75bfcb268259080c64301327f5804fda3f7d
