### ISSUE TITLE
Force HDMI Display not working in 4.x

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#841]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
v4.x-master-558-ga07df14e (master branch)   on Pi 3B+

**Describe the bug and Steps to reproduce**: 
Open FPP settings and go to System tab check the Force HDMI Display, reboot as directed.
If HDMI monitor is not connected to the Pi when the Pi boots back up, and after Pi boots you plug the Pi into the HDMI Port of the Monitor there is no output. (I played an Mp4 file and not display.)

Reboot again but leave the monitor connected, and you will see boot up message and when you play an mp4 it will work.

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.
You should be able to plug in a monitor and the PI should output to that monitor.

**Additional context**: 
This has been broken for a while in 4.x. I just got around to reporting it.

**Additional Attachments**
Please include the log files. To create the file:
[FPP_Logs_20201023.0018.zip](https://github.com/FalconChristmas/fpp/files/5426571/FPP_Logs_20201023.0018.zip)

**Comment by derwin12** [comment]
Had a user with this issue tonight as well as one on FB. Seems the hdmi config files are not working for pi4.. Similar to the retropie gaming world issues..

**Comment by dkulp** [comment]
Did they update to 4.3.1?    Some fixes are in place on 4.3.1 for this.

**Comment by derwin12** [comment]
We just had the lady tonight click on update .. still not luck .. also powered down and up with the projector turned on.
Reports something about unable to initialize FBVdisplay (something like that) under status page.

**Comment by patdelaney** [comment]
I did my testing on piero, i should probably test on pi 4

**Comment by patdelaney** [comment]
So is she using a virtual matrix or playing MP4's??

Pat

**Comment by derwin12** [comment]
She has the virtaul matrix defined but trying to play .avi and .mp4.
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=243886#p1488488

**Comment by derwin12** [comment]
Should / would uncommenting #hdmi_safe=1 in the config.txt be the fix? I think we tried this with another user but could it be this?

**Comment by patdelaney** [comment]
It looks like we have a regression. It doesn;t appear to be working right
on PiZero pr Pi4

**Comment by dkulp** [comment]
Fixed on master
