### ISSUE TITLE
Add command to insert playlist if not already playing that playlist

### ISSUE THREAD

**Issue by joeharrison714** [FalconChristmas/fpp#842]
**Is your feature request related to a problem? Please describe.**
I am looking for the easiest way to "Insert Playlist Immediate" but only if it is not playing.

**Describe the solution you'd like**
Would be great if there were a command for added for this

**Describe alternatives you've considered**
So far I tried creating a script based on the `CheckIfPlaying.sh` script but had issues

**Additional context**
Essentially looking to replicate this xSchedule function
<img width="579" alt="Screen Shot 2020-10-23 at 5 40 47 PM" src="https://user-images.githubusercontent.com/7193254/97056427-fe22db00-1556-11eb-9927-47d7481c506f.png">

**Comment by ghormann** [comment]
This is fairly easy to script with the Rest API.  I use it with node.js very effectively. 

1. Call http://localhost/api/fppd/status 
1. Check the results. if current_playlist.count == 0 then nothing is playing. 
1. If nothing is playing call http://localhost/api/playlist/" + playlist + "/start

**Comment by joeharrison714** [comment]
Thanks. I clarified the title in that the playlist should only start if that specific playlist is not already running. I was able to get a script working to do it but still think it would be a nice enhancement to have a built-in command

**Comment by dkulp** [comment]
I added a "If No Running" flag to all the Insert/Start playlist things.  Code is on master branch if you would like to try testing it out.

**Comment by joeharrison714** [comment]
@dkulp I tested a multitude of scenarios and everything worked as expected. thank you!!
