### ISSUE TITLE
Add fbset -s command to Troubleshooting commands entry

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#843]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but something noce for us to use for Troubleshooting,

**Describe the solution you'd like**
Add fbset -s command to the Troubleshooting commands report.
Title of Section: Video Output
Sample output:
mode "1824x984"
    geometry 1824 984 1824 984 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode

**Describe alternatives you've considered**
this could be done manually, but it's probably easy to implement

**Comment by ghormann** [comment]
Implemented in  7464c38969a99b20b411026d6f2de7d644fdff20

Tested with 
1) Dev box: (vm)  (Worked)
2) Raspberry Pi (worked)
3) BBB gives a warning about the FrameBuffer device not being present.   (I think this is acceptable).
