### ISSUE TITLE
Scheduled Priorites seem to be broken in 4.0

### ISSUE THREAD

**Issue by SmAsH-jl** [FalconChristmas/fpp#844]
https://github.com/FalconChristmas/fpp/issues/665
as per this issue we discussed scheduled priorities being implemented, I used them last year and it worked great!

This year they don't seem to be working. the topmost schedule never interrupts the lower priorities schedule. 

Is there something i am doing incorrectly?

Thanks

**Comment by ghormann** [comment]
Dan has pushed a588f265338dae3c302d4bb4daaf0f09e56ac03e in an attempt to fix this.

**Comment by SmAsH-jl** [comment]
Tested in the latest master, Still does not appear to work.

It looks like it tries. but the 2nd playlist just takes over right away, but there is a blip on the screen at the time it's supposed to happen.

If i set 2nd priority playlist type to gracefully stop. it does say gracefully stopping but then starts right up again and plays through without every triggering the 1st playlist in the list.

**Comment by dkulp** [comment]
This is implemented on master.   Will be in 4.4
