### ISSUE TITLE
Enhancement: Add a "TAIL" button to the File Manager Logs screen

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#848]
**Is your feature request related to a problem? Please describe.**
no problem, just a nice enhancement.  

**Describe the solution you'd like**
Typically when looking at log files one goes to the end to see the most recent entries.  Log files can be large, especially when debugging. The Linux TAIL command is very useful for this.   I often use SSH and TAIL to look at the logs.  But it would be really nice and handy if the FPP File Manager window had a TAIL button to go along with the VIEW button.   View opens a relatively small window at the start of the log file.  Scrolling to the bottom every time can be tedious... especially with the relatively small window and a large log file full of debugging info.   TAIL would provide a quick and convenient view of the most recent (end) entries in the log files.

**Describe alternatives you've considered**
1.  log in with SSH and use TAIL at the command line
2.  continue to use the existing VIEW button and scroll to bottom of file every time.

**Additional context**
I'm assuming this is relatively simple to implement.   Not needed if its more complicated to do.

**Comment by ghormann** [comment]
@MarkA75160   Note, this is already implemented on Troubleshooting page.   I agree it would still be convent here but just sharing for awareness.

**Comment by MarkA75160** [comment]
Thanks Greg,  yeah I saw it in there too, but going there to see it is more tedious that scrolling the the bottom of the VIEW window :)  It would be really, really cool if we could do "tail -f" in the browser window, but I didn't want to be greedy.   lol
    On Wednesday, October 28, 2020, 04:31:08 PM CDT, Greg Hormann <notifications@github.com> wrote:  
 
 


@MarkA75160 Note, this is already implemented on Troubleshooting page. I agree it would still be convent here but just sharing for awareness.

**Comment by ghormann** [comment]
I started working on the patch to add it. Looks semi easy given the current design.
