### ISSUE TITLE
Enhancement: show E1.31 bridge in multisync

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#850]
Wondering if the process that generates data for multisync details can query and return information about E1.31 bridges.

I can see Sandevices controllers like E681's and E6804's (in the multisync page and the APIresponse) so it doesn't seem to much of a stretch to ask for this non falcon controller also.  Obviously I'm not looking for any more information than the sandevices controllers can respond with (online when polled, firmware version, ip) which I assume is just some regex to identify the data (although I recognize there could be custom data in the firmware for the other controllers).

After looking at the multisync code I see it seems to pull this from fppd so I cannot just add this myself (thought originally it may have been in the php code which I could have tackled).

Here is the relevant html returned from one of my bridges:
`<HTML><HEAD><TITLE>DIYLEDExpress E1.31 Bridge Configuration Page</TITLE></HEAD>
<BODY>
<style>table,td{text-align:center;}th{padding:10px;padding-top:0px;padding-bottom:0px;}</style><H2><CENTER>DIYLEDExpress E1.31 Bridge Configuration Page</CENTER></H2><HR><H4><CENTER>By <a href="mailto:dlovely@diyledexpress.com?Subject=E1.31%20Bridge">Dave Lovely</a></CENTER></H4><form action='A' method='get'><input type='submit'value='Refresh'></form>Firmware Rev: 4.02<PRE><table border='1'><form action='D' method='get'><tr><th>IP Mode</th><th>IP Address</th><th>Subnet Mask</th><th>Gateway</th><th>MAC Address</th><th>Mode</th><th>Timeout</th></tr><tr><td><input type='radio' name='N' value='0'        > DHCP      <br><input type='radio' name='N' value='1' checked> Static    <br></td><td><input type='text' name='A' size='3' maxlength='3' value='192'          ><input type='text' name='B' size='3' maxlength='3' value='168'          ><input type='text' name='C' size='3' maxlength='3' value='10'           ><input type='text' name='D' size='3' maxlength='3' value='10'           ></td><td><input type='text' name='E' size='3' maxlength='3' value='255'          ><input type='text' name='F' size='3' maxlength='3' value='255'          ><input type='text' name='G' size='3' maxlength='3' value='255'          ><input type='text' name='H' size='3' maxlength='3' value='0'            ></td><td><input type='text' name='I' size='3' maxlength='3' value='192'          ><input type='text' name='J' size='3' maxlength='3' value='168'          ><input type='text' name='K' size='3' maxlength='3' value='10'           ><input type='text' name='L' size='3' maxlength='3' value='1'            ></td><td>00:04:A3:91:B5:13</td><td><input type='radio' name='M' value='0'        > Multicast <br><input type='radio' name='M' value='1' checked> Unicast   <br></td><td><input type='text' name='P' size='2' maxlength='2' value='0'            ></td></tr></table><br><input type='submit'value='Update System Settings'></form>`

**Comment by cpinkham** [comment]
Can you save the HTML to a file and attach that here so we can have an example to test against?  We should be able to then add a function with the appropriate regex to detect and pull out the firmware version.

**Comment by cpinkham** [comment]
Closed in fe304edf51
