### ISSUE TITLE
Network wireless settings should obscure password

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#851]
**Is your feature request related to a problem? Please describe.**
The PSK (password) for the wireless network is always shown in clear text.  There is no way to obscure it.  When using zoom for trouble shooting it would be nice if this password wasn't in full display. 

**Describe the solution you'd like**
Reapply the same solution used for the overall UI password.   By default, the UI password is obscured but there is checkbox to show the password if desired.   (Could also switch to display it when cursor is present). 

Something like this: 

![image](https://user-images.githubusercontent.com/24968726/97784217-4d7a9400-1b73-11eb-90f8-7c5a6abffe67.png)

**Comment by dkulp** [comment]
I pushed something to master that I think implements this.  Can you take a look?

**Comment by ghormann** [comment]
Thanks Dan.  Looks like you beat me to fix this. :-) 

I tested 6986279d02ef98427a77da21a0eeb7569e4d3ed5 and it works well.
