### ISSUE TITLE
Enabling test pattern on K32A-B from FPP 4.2+ with a string that has non RGB affects all others after.

### ISSUE THREAD

**Issue by Dansthunder** [FalconChristmas/fpp#852]
When enabling test mode from FPP, and for example, output 21 has GRB defined, and outputs 22, and beyond are all standard RGB, they won't blink in the standard RGB pattern.   They blink yellow & blue instead of red / green / blue.  The test page obviously doesn't care / listen whatever is on the BBB output page, defining the port which has the strip with the odd ball color output, which is fine I suppose for that one string, but I have 40 outputs, and it then affects everything after that.   Sequences play fine, just the test pattern does not.  I understand that the RGB setting on the test page overwrites whats on the BBB output page -- until it hits a non RGB setting on BBB outputs, then all bets are off.  One port wrong, messes up the rest.   I make sure to define RGB in xlights to force RGB for every output after the GRB strip.   This happens up to version 4.3.1 GIT 723687f 
![2020-11-02 11_00_43-FPP - K32A-B](https://user-images.githubusercontent.com/14242408/97902442-d96af800-1cfa-11eb-961f-c32703902086.png)

**Comment by darylc** [comment]
no response
