### ISSUE TITLE
Add the ability to scan for available SSID's to connect to

### ISSUE THREAD

**Issue by Padre653** [FalconChristmas/fpp#853]
Good day, 
Is it possible to add the ability to scan for available SSID's to connect the WLAN0 to under the Network page? I find a lot of issues in Zoom relate to users miss spelling, forgetting they used capital letters or can't remember what their SSID is.

Thanks for looking!

**Comment by MarkA75160** [comment]
Its already in there.  Was added a couple updates ago.  What version are you running?

**Comment by Padre653** [comment]
My apologies then. I'm running 4.3.1 and did not notice that feature. I will obviously need to look again.

**Comment by Padre653** [comment]
Found it, the only issue I see is if you are using an SSID with a space in the name, you only see the 1st word of the SSID

**Comment by dkulp** [comment]
SSID with space is a separate issue.... This issue is already implemented.
