### ISSUE TITLE
Enhancement: Ability to Bulk Change Mode via Multisync Menu

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#857]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be helpful for those of us with multiple FPP instances to be able to bulk change the FPPD mode via the multisync menu.  I'm asking for additional options of (Remote, Master, Standalone, and Bridge) to the action menu on the bottom right of the view.

![image](https://user-images.githubusercontent.com/3765696/98010045-de43b080-1dbb-11eb-907f-2594df252251.png)

**Describe alternatives you've considered**
Manually changing each FPP instance using the WebUI.  I have not researched API calls.

**Additional context**
None

**Comment by MarkA75160** [comment]
Shutdown and Reboot (different from FPPD Restart) would be nice additions to that list as well.
