### ISSUE TITLE
Unable to run app as subprocess from Scripts

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#858]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: FPP 4.3 running on BBB with Kulp K16 hat

**Describe the bug and Steps to reproduce**: 

I use the MP3 streamer script from the repository.  I have for the last 2 years and previously once I ran the script, it would continue to stream the audio from the source until I terminated the process by using the second script also in the repository.  Looking at the script, it runs mpg123 with the "&" at the end to make it run as a sub-process outside the script.  This worked great previous to using 4.x.  Now in 4.x the process doesn't seem to start as a sub-process and it appears a script will timeout after 30 minutes, and when that happens, the mpg123 is then terminated also.

Also, as note, mpg123 use to be included with the image, in 4.x I have to terminal in and install it manually.

**Expected behavior**: 
mpg123 should continue to run until terminated by the second script.  

**Additional context**: 
None

**Additional Attachments**
Please include the log files. To create the file:
Nothing to see in the log files from what I can tell.  I can upload if requested.

**Comment by dkulp** [comment]
Use of mpg123 is really deprecated... Is there anyway you could test with "cvlc" (which is installed already) and see if that changes anything?

**Comment by chrkov** [comment]
I just tested with cvlc and that seems to fix the issue.

Thanks!

**Comment by patdelaney** [comment]
did you try running with "sudo" in the command line
