### ISSUE TITLE
BBB String Save Failed when '&' in string Description

### ISSUE THREAD

**Issue by Cboehm00** [FalconChristmas/fpp#859]
I'm using a F40D-PB

When adding BBB Strings I've found that upon save I get the error "Save Failed" and I immediately lose all of my string data.  I narrowed it down to having at least one special character in the description (&).  
Example:  Garage & Window  will cause this problem,  changing it to "Garage And Window" rectifies the problem.
I'm not sure if  any other special characters cause the error.  

FPP 4.3.1

**Comment by dkulp** [comment]
Fixed
