### ISSUE TITLE
4.3.1 fpp stops

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#860]
Tried uploading sequence and models through fpp connect get the error in pic and fpp stops. Can't get fpp to restart by running update or fppos. I have to reimage. Tried running xlights 40&46 and fpp 4.2 & 4.3.1 no luck
![20201105_204521](https://user-images.githubusercontent.com/10238767/98323167-d304a680-1fae-11eb-817b-3f90651764fc.jpg)

**Comment by 1991mustang50** [comment]
Only does it when uploading models via fpp connect. I can upload models via controller tab with upload output button.

**Comment by ghormann** [comment]
You would need to downlaod and attach the logs for anyone to try and debug.  We have seen this in the past when xLights uploads an invalid model.

**Comment by dkulp** [comment]
Actually, a packaged sequence from xLights would also be great as I can see what xLights is trying to upload.  My "gut feeling" is a wacky character in a model name, but it could be a number of things.

**Comment by 1991mustang50** [comment]
[
[test2020xmasfppuploadfail.zip](https://github.com/FalconChristmas/fpp/files/5502240/test2020xmasfppuploadfail.zip)
](url)

here you go! sorry if its something stupid but i dont see it
