### ISSUE TITLE
Controller data not updating using FPP Connect from xLights

### ISSUE THREAD

**Issue by neowolfwitch** [FalconChristmas/fpp#862]
xLights v. 2020.46
FPP v. 4.4

(Not sure if this was happening prior to these.)

xLights automatically manages my Kulp controller. I use FPP Connect with "Models" checked and "UDP Out" set to "All" to upload any changes to FPP. This has worked great for over a month, until now...

Controller information (ports and channels) is not propagating anymore. If I make any changes to my props in xLights- I have to manually modify channels/controller ports in FPP. FPP Connect isn't even propagating brightness and gamma settings anymore.

**Comment by neowolfwitch** [comment]
I am able to update my channels using the "Bulk Controller Upload" option, but this used to be done as part of "FPP Connect", unless I'm crazy, which is possible. 👍

**Comment by BrannonDaisey** [comment]
I am having the same issue! if possible please let me know how you fixed it

**Comment by neowolfwitch** [comment]
I haven’t. “Bulk Controller Upload” doesn’t seem to be working consistently either. I’ve pretty much given up on xLights managing things for now. ☹️

**Comment by bigwavedave42** [comment]
FPP Connect won't push the configuration.  FPP Connect pushes Models, Sequences, and Media.  When you click on the controller, you should see in the bottom right: 

![image](https://user-images.githubusercontent.com/11801385/100258480-fd85b780-2efb-11eb-993f-6a0a8b9e3e63.png)

You would want to click "Upload Input" and "Upload Output" to push controller info.  This assumes  you've already used the visualizer button to layout models on your controller ports.

If the Upload Input and Upload Output are not showing, then you probably don't have the controller set as being controlled by xLights.

**Comment by bigwavedave42** [comment]
Looked at this a little more, and I think this is what you are referring to, from a Kulp side:

(xlights manual screenshot:
![image](https://user-images.githubusercontent.com/11801385/100260075-d9c37100-2efd-11eb-8b9d-6f4c79902ceb.png)

So, I'd make sure that those checkboxes are checked.  If it still isn't working, this would probably need to be reported by you at the xLights issue page:
https://github.com/smeighan/xLights/issues

My prior comment was the way you have to upload to F16s, F48s, etc.  I hadn't experienced the FPP connect uploading configs to a Kulp.  Sorry for the confusion.

**Comment by darylc** [comment]
this looks good to close too
