### ISSUE TITLE
Feature Request - auto config for a large

### ISSUE THREAD

**Issue by gergmchairy** [FalconChristmas/fpp#863]
Hi Folks,

When building a new matrix its a bit tedious and prone to user error to go through each & every panel to set the output & row numbering.
A simple button to set output & panel # starting top right (from the front) would be well recieved.
Thanks.

Greg

**Comment by gergmchairy** [comment]
Hi Folks,

When building a new matrix its a bit tedious and prone to user error to go trhough each & every panel to set the output & row numbering.
A simple button to set output & panel # starting top right (from the front) would be well recieved.
Thanks.

Greg

**Comment by tbistr69** [comment]
And to go a few steps further, have the panels defined in Xlights and include in the upload configuration to further reduce user input error.

**Comment by cpinkham** [comment]
An Auto-layout button was added in bae71dd139f
