### ISSUE TITLE
Blank Screen on Startup does not appear to be working

### ISSUE THREAD

**Issue by licensed2hench** [FalconChristmas/fpp#864]
**FPP Version and Hardware**: 
FPP Version: v4.4-1-gd5a419b1
Platform: Raspberry Pi (Pi 3 Model B+)
FPP OS Build: v4.3
Status Display: 128x32 I2C (SSD1306)

**Describe the bug and Steps to reproduce**: 
"Blank screen on startup" screensaver option does not appear to be working?
The FPP Status screen remains persistent on the HDMI output regardless if the" Blank screen on startup" option is selected or not. (reboot after each change of option)
The FPP Status screen is visible on the HDMI output between payback of video files in a playlist

**Expected behavior**: 
From the instructions: "The screen blanking will turn the text console off after one minute so that it does not show through when you are not playing a video" 
This does not appear to be happening? Or is this a different setting?

**Additional context**: 
This issue was occurring with version 4.3 and earlier builds of 4.4
A 128x32 I2C (SSD1306) Status Display is in use, (Disabling it seem to have no effect).

**Additional Attachments**
[FPP_Logs_20201110.0150.zip](https://github.com/FalconChristmas/fpp/files/5514251/FPP_Logs_20201110.0150.zip)

**Comment by patdelaney** [comment]
this is working on Master branch .... I can test on 4.4 release image.

Do you have force HDMI checked?

Pat

**Comment by patdelaney** [comment]
I just tested on Pi-Zero with 4.4 and it works as expected.  I also just tested a FRESH image and it works (on PiZero) the PiZero has an OLED.

**Comment by licensed2hench** [comment]
Forced HDMI is checked. 
I will check with a fresh image and see if the issue persists.

**Comment by licensed2hench** [comment]
I found the issue - I was using the Pi-Kiosk version.
Switching to the main Pi version fixed the issue.
Thanks!
(I assume that it is working as intended and Kiosk mode overrides the screen saver?)

**Comment by patdelaney** [comment]
The Non Kiosk image works as expected
