### ISSUE TITLE
Reenable SoftPWM for GPIOs that do not support hardware PWM

### ISSUE THREAD

**Issue by rudybrian** [FalconChristmas/fpp#867]
**Is your feature request related to a problem? Please describe.**

The change introduced with 3fa5d807fbd5f39f002649d6717dd96f2e2cde58 disabled the ability to use SoftPWM on Pi GPIOs and PiFace outputs that do not have hardware PWM capability. Use of GPIOs for software PWM allows low speed PWM control of fans and other peripherals while leaving the hardware PWM ports available to drive pixels that have more stringent timing requirements. By disabling the SoftPWM functionality that had been present in FPP v1.8-v3.6.2, it disallows the concurrent use of pixel strings such as via the Falcon PiCap and fan controllers such as https://github.com/rudybrian/PID_Fan_Control .

**Describe the solution you'd like**

When assigning PWM mode to a GPIO, if the GPIO is not a hardware PWM capable pin, use SoftPWM instead.

**Describe alternatives you've considered**

I am currently stuck on FPP 3.6.2 as I have many Pi-based controllers that require SoftPWM to control the speed of enclosure cooling fans, and without this functionality the enclosures will overheat.

**Comment by rudybrian** [comment]
Since the legacy softPWM solution really only solves for the Pi, it probably makes sense to develop a solution for monitorable+stand-alone I2C fan controllers like the MAX31760 and develop a corresponding plugin that would extend support to BB/PB-based hardware as well.

**Comment by rudybrian** [comment]
Update: I picked up a couple Mikroe Fan 2 Click boards to do some development with and have started working on a Python class to interface with the MAX31760 https://github.com/rudybrian/MAX31760-Python

**Comment by rudybrian** [comment]
My [MAX31760-Python module](https://github.com/rudybrian/MAX31760-Python) is now functionally complete, so I'll be starting on a plugin that will give the end user an option to use hardware PWM (on Pi only, and only if the ports are not already in use for driving pixel data) or one or more MAX31760 for fan control.

**Comment by patdelaney** [comment]
Good work Brian

**Comment by SonnyJim** [comment]
This has become an issue for me after upgrading FPP.  Before I could use any pin via SoftPWM to drive my dumb RGB strip and driving my pixels via RPIWS281X.

Now I'm restricted to hardware PWM pins, I don't have enough to drive one RPIWS281X and R,G, B.  There is indeed 5 hardware PWM pins available, but unfortunately two of them get used for RPIWS281X.  I am unable to disable the second RPIWS281X output so I'm kinda stuck.

Is it likely SoftPWM will be readded?  Or maybe the possibility of turning off the second RPIWS281X output to free it up for use?

**Comment by SonnyJim** [comment]
Is there any progress with this?  I'd love to update to the latest FPP this year, but unfortunately I'm still stuck on v3.6 due to what's described as above.

**Comment by dkulp** [comment]
This is not likely to be implement, definitely not any time soon.  If you need PWM, you really should get something that can do PWM in hardware.  A PCA9685 based board (well supported by FPP on the Pi and BBB) is $8 on Amazon.

**Comment by SonnyJim** [comment]
You know what, I actually have one of those kicking around and just didn't think (or read the thread properly!).

Thanks for the suggestion, I think this issue can be closed now. (and I can finally update my ancient fpp!).
