### ISSUE TITLE
Unable to trigger events from script

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#869]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: FPP 4.4 on Pi3B+

**Describe the bug and Steps to reproduce**: 
Trying to trigger and event from a script.   Using the outlined format of 'fpp -t EventName"

Event works fine when triggered from the GUI.  But from script of CMD prompt, it does nothing.

Tried renaming event also to have no spaces and it continued to not work.

**Expected behavior**: 
Event triggers

**Additional context**: 
None

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
[FPP_Logs_20201116.1355.zip](https://github.com/FalconChristmas/fpp/files/5546694/FPP_Logs_20201116.1355.zip)
![Run](https://user-images.githubusercontent.com/57808614/99260693-5741ff80-27e1-11eb-9966-b04df4d65a67.JPG)
![Events](https://user-images.githubusercontent.com/57808614/99260696-57da9600-27e1-11eb-835c-5e4285300c96.JPG)

**Comment by cpinkham** [comment]
The EVENTNAME is actually the MAJORID_MINORID with leading zeros in front of the numbers if they are single-digit.  The following command works correctly on my system:

fpp -t 03_04

I'm going to push a commit which changes the help output to say eventid instead of eventname and hopefully clarify it a little more for other users.

**Comment by chrkov** [comment]
Ok.  I was trying to do it by name and that was not working for me.



Sent from my T-Mobile 4G LTE Device



-------- Original message --------
