### ISSUE TITLE
Trigger fseq effects from script

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#870]
Add ability to trigger a .fseq effect using the fpp -e

**Comment by darylc** [comment]
Shouldn't this be done via the FPP API these days?

**Comment by cpinkham** [comment]
This can be accomplished via the Effect Start and Effect Stop FPP Commands accessible through the REST API or using "fpp -C 'Effect Start" via the command line.

for more info, see "fpp -h" and look for the FPP Command help at the bottom of  http://YourFPPSystemIP/apihelp.php
