### ISSUE TITLE
Pop-up Calendar Inaccurate

### ISSUE THREAD

**Issue by mr-davemcknight** [FalconChristmas/fpp#871]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 4.4 running on a RPI 3B+

Setting up Scheduler for the current year, I noticed that when clicking on a date field I get a pop-up calendar as expected. However, the calendar displayed does not match the current year.  Although November 17th is on a Tuesday, the calendar displays it as Sunday. 

![image](https://user-images.githubusercontent.com/30195184/99396652-01885880-28b0-11eb-92d1-418a0230584a.png)

When I select 11/17/2020 from the pop-up it populates the date box with 2019-11-17. Nov 17 WAS on a Sunday in 2019. I was able to enter the correct year in the date box manually.

**Comment by tbistr69** [comment]
I have also noticed that this calendar popup only happens in the first line boxes. If I add more lines, they will not pop up when i click the fields.
