### ISSUE TITLE
RPiZeroW not booting

### ISSUE THREAD

**Issue by ioscanner** [FalconChristmas/fpp#874]
**FPP Version and Hardware**: 
FPP 4.5 on RPiZeroW with PI-28D+ 

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. I can boot the image on Pi 3 and 4.  But on Zero it starts to boot and then just stops doing anything.  No logs nothing on the screen. The system never boots and nothing is on the screen.
2. I have tested many times.  I got it to boot twice.  I am not sure why booted twice. I can boot over and over on the Pi 3b+ and pi 4, but it will not boot on the ZeroW.

**Expected behavior**: 
I expected the system to boot.  I have tested on 3 brand new RPiZeroWH models all with the same result.

**Additional Attachments**
Please include the log files. To create the file:
Can't get to boot on the RPiZeroWH.

**Comment by libby2cm** [comment]
Fwiw, I upgraded all 9 of the zero w's I'm running (along with 9 pb's and a rpi 4) and all went fine.  They were all fresh imaged from 4.4 a couple weeks ago, so if your os base is old, maybe that induced your issues.

**Comment by ioscanner** [comment]
I am using the latest code base as of today. Could it be the power is not enough to run the PI zero. It is strange I can power the zero with the power cord and it works just fine. When I try to pass power from the pi-28D+ the unit will not boot. Is there a configuration option or something I am missing?

J
