### ISSUE TITLE
Scheduler "Stop Gracefully After Loop"  does not complete the loop

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#876]
**FPP Version and Hardware**: 

FPP Version:	v4.5.1
Platform:	Raspberry Pi (Pi 3 Model B+)
FPP OS Build:	v4.4
OS Version:	Raspbian GNU/Linux 10 (buster)
Hardware Serial Number:	00000000694845bd
Kernel Version:	5.4.72-v7+

**Describe the bug and Steps to reproduce**: 
On FPP main status page"
Select a Playlist with multiple (more than one) entries and set to "Repeat"
Start the playlist (click on "Play")
While a sequence is playing, click on "Stop After Loop"
The current sequence finishes and then FPP jumps to the Lead-out section without finishing the full loop.
It is essentially behaving the same as "Graceful Stop" instead of the expected "Graceful Stop After Loop"

**Expected behavior**: 
It is expected to continue playing though all the songs in the list before jumping into the Lead-Out section 

**Additional context**: 
CaptianMurdoch has confirmed he also sees it and provided this additional detail:

the problem appears to be in the FPP Command itself, it isn't grabbing the 'after loop' flag and passing it through to the Playlist code.   Dan added that FPP Command and may notice the issue before I do, otherwise I can look at it.  Basically, the UI calls a REST API endpoint which in turn calls a FPP Command passing a 'true' arg to stop after the loop.  The 'true' arg isn't making it to the Command processing code though, and it calls the Playlist StopGracefully() function with a false instead of true so it stops after the current item not after the current loop

**Additional Attachments**
zipped logs 

![image](https://user-images.githubusercontent.com/57245161/100390155-0f975100-2ff5-11eb-9b1d-546269247a80.png)
[FPP_Logs_20201126.2023.zip](https://github.com/FalconChristmas/fpp/files/5604903/FPP_Logs_20201126.2023.zip)

**Comment by cpinkham** [comment]
Fixed in f362b6ffca01b3
