### ISSUE TITLE
Remote FSEQ Effect Start stops sequence from playing

### ISSUE THREAD

**Issue by TechplexEngineer** [FalconChristmas/fpp#879]
**FPP Version and Hardware**: 
|  hostname  |    sbc   |   version      |
|------------|--------|-------------|
|  fpp            |    pi4     |  v4.0-beta1  |
| renard01    |  pi3b+  | v4.4             |
| pixels         | BBB      | v4.0-beta2  |

<img width="1311" alt="Screen Shot 2020-11-27 at 9 24 31 AM" src="https://user-images.githubusercontent.com/175873/100458821-66069d00-3092-11eb-9209-a176f6d18e3f.png">

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Master FPP, create events to turn on and off static lights. Be sure to check loop and background. <img width="1190" alt="Screen Shot 2020-11-27 at 9 25 12 AM" src="https://user-images.githubusercontent.com/175873/100458898-8afb1000-3092-11eb-9520-ecf5ac65ef86.png">
2. Add trigger events to the playlist lead-in and lead-out
<img width="1190" alt="Screen Shot 2020-11-27 at 9 25 12 AM" src="https://user-images.githubusercontent.com/175873/100459050-c72e7080-3092-11eb-9243-5b480862e72e.png">
3. Start the playlist
4. Notice on the remote FPP (where the effect was started), only the static background channel works.

**Expected behavior**: 
Since the FSEQ effect is selected as background, the sequence should take priority.

**Additional Attachments**
[master FPP_Logs_20201127.1415.zip](https://github.com/FalconChristmas/fpp/files/5608263/master.FPP_Logs_20201127.1415.zip)

[renard01 FPP_Logs_20201127.1415.zip](https://github.com/FalconChristmas/fpp/files/5608262/renard01.FPP_Logs_20201127.1415.zip)

[pixels FPP_Logs_20201127.1416.zip](https://github.com/FalconChristmas/fpp/files/5608267/pixels.FPP_Logs_20201127.1416.zip)

**Comment by TechplexEngineer** [comment]
Maybe this is expected behavior. It seems that If I use ESEQ rather than FSEQ the background checkbors works properly

**Comment by bigwavedave42** [comment]
I use the ESEQ and it has been working ok on v4.4.  I think ESEQ is the intended format for background effects.

**Comment by darylc** [comment]
this looks good to close?
