### ISSUE TITLE
Matrix Tools getting "stuck" in enabled state 

### ISSUE THREAD

**Issue by denniskuntz** [FalconChristmas/fpp#884]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP 4.51 on Pi4. Note I updated to this from 4.3.x in hopes it would fix the issue.

**Describe the bug and Steps to reproduce**: 
I use the Twilio Control Texting plugin along with the Matrix Message, MessageQueue, and Matrix Tools plugins. Seems like the Matrix Tools plugin gets enabled every time but as often as maybe 1 in 3 times the Matrix Tools do not get set back to disabled after a text is displayed. This results in the Matrix remaining blank after a text has finished displaying. When this issue occurs I can go in to Matrix tools and switch the state to disabled from enabled and the .fseq that is playing shows again. Not sure which plugin is responsible for the enabling/disabling Matrix Tools state. I did look at some of the logs and didn't see anything that stood out related to this issue but hopefully I just was looking in the wrong place. Also I think logging levels may be broken for at least some of these plugins as it didn't seem to make any difference in logging when I changed the logging level earlier this year trying to track down another issue I was having.
 
**Expected behavior**: 

After every text is finished displaying Matrix Tools should get set back to disabled and then the Matrix goes back to displaying the scheduled .fseq file that shows the number to text and other show info. 
 

**Additional context**: 
Reverted to my 2.x image I took from my sd card last year for now.
[FPP_Logs_20201127.1341.zip](https://github.com/FalconChristmas/fpp/files/5609364/FPP_Logs_20201127.1341.zip)

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by patdelaney** [comment]
Contact me Tuesday about this I'm trying to troubleshoot and issue with someone else as well

**Comment by denniskuntz** [comment]
I posted in the forum and Cjaqua helped me revert a change that seemed to have caused this. He also came up with a fix for another issue we discovered where messages were not actually getting queued and were dropped.

https://falconchristmas.com/forum/index.php/topic,13544.0.html

**Comment by darylc** [comment]
@patdelaney Did this get sorted out?

**Comment by patdelaney** [comment]
the matrix plugin is no longer getting stuck ON it turns off when the message is finished.

**Comment by denniskuntz** [comment]
I put in a couple tickets last year. I am out of town with only my phone. My memory is fuzzy but both issues got resolved. Not sure the fixes were incorporated into new downloads for both though. 


Sent from Yahoo Mail for iPhone


On Saturday, June 19, 2021, 10:02 PM, darylc ***@***.***> wrote:




@patdelaney Did this get sorted out?
