### ISSUE TITLE
Every event firing when sequence is playing

### ISSUE THREAD

**Issue by jcrossbdn** [FalconChristmas/fpp#887]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 4.5.1 running on Pi 3b+

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
When playing a sequence I noticed my projectors keeped turning on and off every 10-15 seconds.  I looked at the FPPD logs and noticed that when a sequence is running the logs are filling up with "events.cpp:216: Unable to load event x_x".  I confirmed with a network trace that the events are actually being called as my events call an external API.  I don't have events triggering in my xlights sequence and they are only supposed to be used in preshow and postshow to turn on and off the projectors.  Logs show that basically every combination of event is being called.

**Expected behavior**: 
Triggering of events should only be done when requested.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20201128.2225.zip](https://github.com/FalconChristmas/fpp/files/5611312/FPP_Logs_20201128.2225.zip)

**Comment by darylc** [comment]
@jcrossbdn It is possible to tie events to channels in your sequence. If you've accidentally done that it would explain what you are seeing.   Can you confirm that the Major/Minor fields on the events page are empty?

**Comment by jcrossbdn** [comment]
oh my, not sure when that happened but you are 100% correct.  I dug through everything and looked at those but it didn't stand out to me as an issue.  Chalk this issue up to error code ID-10-T.
Thanks!
