### ISSUE TITLE
Scheduler will start then immediately set show to stopping gracefully 

### ISSUE THREAD

**Issue by jaredkaczynski** [FalconChristmas/fpp#888]
**FPP Version and Hardware**: 
FPP 4.5.1 on PocketBeagle K40D-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Create schedule 1 with Sun-Thurs with 2020-01-01 start 2025-12-31 end and 1715 start 2100 end
2. Create schedule 2 with Fri-Sat with 2020-01-01 start 2025-12-31 end and 1700 start 2100 end
3. Start show on Saturday and it will start then go to gracefully stopping immediately

I also started and stopped the show mid schedule period and it would correctly start and show the proper start and end time but still go to gracefully stopping immediately. 

**Expected behavior**: 
I would expect it to run the show fully on Saturday instead of stopping it

**Additional context**: 
Changing the order so schedule 2 was instead schedule 1 fixed this for some reason

Logs are attached

[FPP_Logs_20201128.2335.zip](https://github.com/FalconChristmas/fpp/files/5611395/FPP_Logs_20201128.2335.zip)

**Comment by RyanAD** [comment]
@jaredkaczynski I'm having the same issue on an RPI4. Will try your workaround and see if that works.

**Comment by rkpalmer** [comment]
Same issue tonight as well.

**Comment by enjohnson** [comment]
And me as well.  spent 2 hours trying to figure out what was going on.  Gave up and started playlist manually.  Will try changing the order in the scheduler after visitors move on

**Comment by marciuliani** [comment]
Same issue for me as well - even rebooted and restarted FPP - my lead in would play then stop gracefully and play my lead out.

I had to start the playlist manually as well

**Comment by jaredkaczynski** [comment]
Okay, so I think I see why it does this and why we only saw this today. My guess is everyone here has different schedules for Friday and or Saturday with earlier starts? than the Sunday schedule.

The logic here I think would have this result.

https://github.com/FalconChristmas/fpp/blob/4a7993af5fef8421482a5f1868deb74da24f2083/src/Scheduler.cpp#L682-L696

I did a test where I made another schedule for Saturday with a start of 23-24 and it started then stopped with this Stopping Gracefully issue. Adding an additional schedule for Saturday with a start of 23:30 and end of 24 caused the first one from 23-24 to run as normal without graceful stopping.

This was while keeping the previous schedules from 17-21 as well. Still digging though on the specifics.

**Comment by marciuliani** [comment]
I do actually have multiple playlists throughout the week and they all start the same time but run Sun-Tues, Wed-Thurs, Fri-Sat.

**Comment by skydiveguy** [comment]
This happened to me as well. Only have 2 things scheduled and one playlist per schedule.
v4.4.1
Schedule 1: A "countdown" sequence starting at 17:49:59 runs for 10 minutes then gracefully stops.
Schedule 2: Main show with all my sequences starts at 18:00:00 until 22:00:00 on repeat and gracefully stop.
This didnt happen in any testing and worked fine the first night (Friday) but last night (Saturday) it finished the first scheduled item (countdown) and started the second (main show)... at the end of the first sequence in main show, it restarted the same first sequence in that playlist.
Stopping the scheduled playlist and starting it manually resolved the issue but it needed to be stopped manually instead of stoping per my schedule.

**Comment by patdelaney** [comment]
In all these reports is the playlist in question, in the last line of the schedule list page?

**Comment by marciuliani** [comment]
In my case it was yes.On Nov 29, 2020 10:15 AM, patdelaney <notifications@github.com> wrote:
In all these reports is the playlist in question, in the last line of the schedule list page?

**Comment by enjohnson** [comment]
yes for me as well.
first schedule line was Sunday - Thursday  1730 - 2200  2nd and last schedule line was Friday - Saturday 1730 - 2300
fix was to make active schedule the first line in the schedule UI

**Comment by rkpalmer** [comment]
> In all these reports is the playlist in question, in the last line of the schedule list page?

Yes for me as well.

**Comment by skydiveguy** [comment]
> In all these reports is the playlist in question, in the last line of the schedule list page?

Yes, the main playlist is located below the 1st playlist.
I will move it up and see if that resolved the issue today.

While this makes sense, what doesnt make sense is the fact that it just happened out of the blue when it was working fine for many days before when there was no update to the FPP main or remote (I dont update my FPP once the show is live unless there is a problem  that needs to be fixed)

**Comment by jaredkaczynski** [comment]
> While this makes sense, what doesnt make sense is the fact that it just happened out of the blue when it was working fine for many days before when there was no update to the FPP main or remote (I dont update my FPP once the show is live unless there is a problem that needs to be fixed)

Did you run the schedule last weekend as well or only this weekend? I am assuming everyone here only started the schedule this week and was on the 4.4 with priority scheduling.

**Comment by patdelaney** [comment]
The temporary work around is move it in the scheduler list. so it's not the last entry. if you only have one entry create a "fake" entry for next year and put that at the bottom of the list.

**Comment by jaredkaczynski** [comment]
> The temporary work around is move it in the scheduler list. so it's not the last entry. if you only have one entry create a "fake" entry for next year and put that at the bottom of the list.

Does it have to just not be the last entry? I did a bit of testing last night and I don't think it's related to being the last one. I think if you added a dummy do nothing sequence at the end of Saturday night it would fix the issue as well. I will do more testing later once I'm home though.

**Comment by pkbott** [comment]
Mine is not the last file in the list and still had an issue like above last night.  Played fine my opening night (Friday) and then Saturday only played through once and shutdown since I had a shutdown command originally in it.

![Screen Shot 2020-11-29 at 12 40 26 PM](https://user-images.githubusercontent.com/55835882/100549296-1b2a8800-3240-11eb-98b5-9965731f3cc9.png)

**Comment by pkbott** [comment]
Definitely issues with the scheduler as my show didn’t even start tonight. Tried Renaming playlists With no strange characters just used underscore between words and no luck either.  Had no issues prior to multiple playlists.

**Comment by patdelaney** [comment]
they are testing a fix right now

**Comment by darylc** [comment]
Looks like there are some commits in master related to this now.

**Comment by cpinkham** [comment]
If anyone else is running master, can you confirm the fix works for you with the original schedule layout?  The patch fixed the issue in my test cases, but I want a bit more confirmation before merging back to v4.5 and v4.4 branches.

**Comment by marciuliani** [comment]
Oddly - I changed the order of the playlists as someone mentioned and all worked well tonight.  It ran through my lead in, ran my playlist - i'm just waiting for the graceful end and lead out at the end of the schedule for tonight.

**Comment by marciuliani** [comment]
My show is currently running until 9:15 EST.  I am more than happy to apply patch after the show if you could provide some instructions on how to do it.

**Comment by cpinkham** [comment]
This should have been closed by the referenced commit.  patch has been merged to v4.4 and v4.5 branches.
