### ISSUE TITLE
Syntax error : redirection unexpected

### ISSUE THREAD

**Issue by tripishadow** [FalconChristmas/fpp#889]
Hi, I have this problem, and I don't know how to continue the installation manually. 

![16066532693358047349335897895234](https://user-images.githubusercontent.com/74878096/100541971-afe4b400-3247-11eb-8451-59f90a856d65.jpg)
 

Thanks

**Comment by dkulp** [comment]
the script needs to be set executable and run directly:

chmod +x FPP_Install.sh
./FPP_Install.sh
