### ISSUE TITLE
No MQTT entry in the Playlist selection

### ISSUE THREAD

**Issue by Medel** [FalconChristmas/fpp#890]
FPP 4.4 running on BBB*

There is no MQTT entry in the playlist selection.
The Broker Host has connected

[FPP_Logs_20201129.1815.zip](https://github.com/FalconChristmas/fpp/files/5612608/FPP_Logs_20201129.1815.zip)
![Screenshot_20201129_190915](https://user-images.githubusercontent.com/3252272/100550038-54321f00-3277-11eb-9b38-4e652d879ef7.png)

**Comment by dkulp** [comment]
Check in the "FPP Command" list.  There should be MQTT things in there if MQTT is connected.

**Comment by Medel** [comment]
I created MQTT Commands in Status/Control -> Events. Trigger Event works but no entry in the playlist selection

**Comment by Medel** [comment]
OK I found the solution. Playlist selection -> FPP Commands -> MQTT
