### ISSUE TITLE
Don't run FPP 

### ISSUE THREAD

**Issue by tripishadow** [FalconChristmas/fpp#891]
Hi again. I do the installation and all goes OK. I reboot the orange pi, but now I have a new problem. On the photo is the problem.
![IMG_20201129_193218](https://user-images.githubusercontent.com/74878096/100552439-7af85180-3287-11eb-8a5c-062b328daee0.jpg) 
![IMG_20201129_193149](https://user-images.githubusercontent.com/74878096/100552493-d591ad80-3287-11eb-9dd4-0b1e155d3856.jpg)

 When I goes into the ip of the falcon player shows a page from apache server. 
![IMG_20201129_193334](https://user-images.githubusercontent.com/74878096/100552448-88add700-3287-11eb-86b4-99b7cc11ad0a.jpg)

I show on the other photo. It says that is missing something on the script. What I do wrong?? How I can solve?
Thanks

**Comment by cpinkham** [comment]
This is a question better suited for the forum but we haven't tested on the OrangePi recently.  You need to look at the FPP_Install.log file and see if you can find any install errors.  if /opt/fpp/scripts/common doesn't exist then it sounds like it couldn't even clone the git repository which might point to a DNS issue or possibly that you didn't have the OrangePi on the network at the time you ran the install script.
