### ISSUE TITLE
4.5.1 Scheduler issue

### ISSUE THREAD

**Issue by PixelPowerUSA** [FalconChristmas/fpp#892]
I'm a long time xschedule user but am testing fpp master as a show player this year. Had an issue with 4.5.1. The playlist will be fine initially then the second time around it'll stop in the middle of a song and go back to the beginning. No special characters in either the sequence or mp3. Tried master branch and the same thing, and its not song specific. Downgraded to Version: v4.4-3-gf09e1877 and it works fine. I didnt have time to copy logs, was scrambling to get the show running. Sounds like an issue with the scheduler.

**Comment by cpinkham** [comment]
In the middle of a song or in the middle of a playlist?   If it is in the middle of a song, it sounds like fppd is possibly crashing.  Check the fppd.log in the Logs tab of the FPP File Manager and see if there are any errors listed at the end of the log file.

**Comment by PixelPowerUSA** [comment]
Would the log still be there? I downgraded to 4.4 a couple of days ago and
my show's been running flawlessly since then.

Brian Roberson / 772-519-1338

**Comment by cpinkham** [comment]
fppd.log should still exist, but you would need to scroll through the log to find the time frame where the issue happened.

**Comment by PixelPowerUSA** [comment]
Here is the portion of the fppd.log that applies to this is on 12/6/2020 using 4.5.1
[FPPD log 12-06-2020.txt](https://github.com/FalconChristmas/fpp/files/5649975/FPPD.log.12-06-2020.txt)

**Comment by ghormann** [comment]
Interesting message in the logs. 

```
common.cpp:665: JSON File /home/fpp/media/playlists/(null).json does not exist
2020-12-06 18:54:59.248 (20770) playlist/Playlist.cpp:230: Error loading /home/fpp/media/playlists/(null).json

```

**Comment by cpinkham** [comment]
@PixelPowerUSA can you confirm the playlist exists and is editable?  If it does, can you set your Log Level to Debug and turn on the Playlist log mask and reproduce the issue so we can see what is happening inside the playlist code at the time.

**Comment by PixelPowerUSA** [comment]
Sure, but I've downgraded to 4.4.3 and works fine. Do I need to go back to
4.5.1 to accomplish this task? I will if needed.

Brian Roberson / 772-519-1338

**Comment by cpinkham** [comment]
Are you still using the same schedule or did you edit it?  I'm curious how the player was told to play an empty filename.

**Comment by PixelPowerUSA** [comment]
I'm using the same schedule. Everything's the same, merely downgraded the
version.

Brian Roberson / 772-519-1338

**Comment by cpinkham** [comment]
ok, thanks. In order for us to debug further, we'll likely need you to be on the v4.5 branch and collect the fppd.log file with Debug level logging turned on for at least the Scheduler and Playlist log masks.  Just update the ticket with the fppd.log once you have a chance to test and we'll take a look.  Thanks.

**Comment by PixelPowerUSA** [comment]
After further review I found the culprit. Even 4.6 didn't fix the issue so i looked at all the logs. 6 months ago I added the Remote-Falcon plugin to review but never got around to it. When i finally looked at the FPPD Stop log it looks like the the remote-falcon plugin was trying to stop the fppd around 6:15. From that point on it was fighting my active playlist causing the constant restarts. Today I removed the plugin and all is well. Thanks for all the effort trying to solve my issue. Cheers! 
[fppd_stop.log](https://github.com/FalconChristmas/fpp/files/5712911/fppd_stop.log)

**Comment by patdelaney** [comment]
I believe that this is the 2nd time I've heard about issues with remote
Falcon. I believe even if you uninstall it you need to reboot once to have
it completely removed because I believe that there was still a process
running after the uninstall.

**Comment by PixelPowerUSA** [comment]
Yes, I did remove and reboot. All is well as it has been running since
5:45pm with no issues. I've been through the playlist 3 times.

Brian Roberson / 772-519-1338
