### ISSUE TITLE
Matrix stuck not going blank

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#893]
Running 4.5.1 with 4.4os on kulp bbb matrix board. I play a 30 second sequence on loop and for past 3 mornings it still displays on one of the messages in the sequence after schedule time. The status shows idle like it's post too. Takes reboot to get rid off it. Had this setup for 3 years this is a first. I do have blank between sequences selected. It happens on both matrix signs I am running both logs attached 
[FPP_Logs_20201130.1242.zip](https://github.com/FalconChristmas/fpp/files/5616139/FPP_Logs_20201130.1242.zip)
[FPP_Logs_20201130.1241.zip](https://github.com/FalconChristmas/fpp/files/5616142/FPP_Logs_20201130.1241.zip)

**Comment by darylc** [comment]
@1991mustang50 Is this still an issue in more recent versions?

**Comment by 1991mustang50** [comment]
Yes it does on 5.4. I have been getting by just running sequences that has off on the matrix. So no biggie for me but if you would like I can try to run it tomorrow and pull logs again.

**Comment by ghormann** [comment]
If you add a command for "lights off" to the Lead Out of the play list, I think it will "workaround" the problem.    I've seen this too with 5.4, but it isn't reproduceable on demand.
