### ISSUE TITLE
Increase MQTT username and password length

### ISSUE THREAD

**Issue by cwoolum** [FalconChristmas/fpp#894]
**Is your feature request related to a problem? Please describe.**
To use MQTT with Azure IOT Hub, a long username and password is needed to authenticate. 

An example username is `contoso.azure-devices.net/MyDevice01/?api-version=2018-06-30`.

An example password is `SharedAccessSignature sr={your hub name}.azure-devices.net%2Fdevices%2FMyDevice01%2Fapi-version%3D2016-11-14&sig=vSgHBMUG.....Ntg%3d&se=1456481802`.

**Describe the solution you'd like**
The UI (and probably backend) limits the username length to 32. I would like to increase this to 100 if possible.
The UI (and probably backend) limits the password length to 32. I would like to increase this to 300 if possible.

**Describe alternatives you've considered**
There are no alternatives. This is a hard limit by Azure IOT.

**Additional context**

**Comment by ghormann** [comment]
@cwoolum  This has been fixed in master and will be included in a future release.    I tested with a password of 107 characters, but it should work p to 300.  It is possible that some special characters will still cause problems, but % appeared fine.

**Comment by cwoolum** [comment]
Thanks!
