### ISSUE TITLE
Time won't sync to proper local time

### ISSUE THREAD

**Issue by wvpt** [FalconChristmas/fpp#897]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
*FPP 4.5.1 running on Pi*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to FPP setting
2. Click on Time
3. The drop down menus are not populated. I enabled NTP and used time.google.com with no success. We are in EST time zone but it is in GMT. I tried hitting the find time zone but that does not work either. I also set time manually but it reverted back to GMT. I am able to get out to internet from the Pi. It performed an update this morning for me.

I tried a power cycle.
[FPP_Logs_20201202.1154.zip](https://github.com/FalconChristmas/fpp/files/5629063/FPP_Logs_20201202.1154.zip)

**Expected behavior**: 
Expected current time to be set in FPP

**Additional context**: 

**Additional Attachments** LOG FILE ATTACHED
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by patdelaney** [comment]
Can you provide a screen shot. I can't reproduce this issue. 
![image](https://user-images.githubusercontent.com/8147459/100872112-ee0bee80-3466-11eb-800d-7135a109909d.png)

I would suggest backing up your config, then Help -> About -> upgrade FPP to get it to "rebuild"

**Comment by wvpt** [comment]
I did the upgrade with no change. As I said it seem like all the drop down menus have nothing in them.
![Screen Shot 2020-12-02 at 7 33 42 AM](https://user-images.githubusercontent.com/54814143/100873255-0123bc00-3471-11eb-88c6-5b13a695c1f5.png)

**Comment by patdelaney** [comment]
I didn't realize this was on a Mac. I have an old macbook Pro I can try it there.

**Comment by wvpt** [comment]
That would be great. Still having problems. My show also seems to be lagging some now too. I am using 4 nodemcu devices. It was working great before I upgraded to V4. Any suggestions.

**Comment by neowolfwitch** [comment]
Just my .02- two of my FPPs lost their DNS settings, and I was unable to set it in the GUI. Because of this- they couldn't update OR sync their times via NTP. This on v4.5.1-3 as well.

I manually set DNS to 1.1.1.1 in /etc/resolv.conf and was able to update to 4.5.1-4. I don't know if the DNS issue is fixed (it isn't in the changelog), but I'm not restarting my FPPs until tomorrow. (Show is running now.)

**Comment by darylc** [comment]
@wvpt do you still need help here?

**Comment by ghormann** [comment]
Closing.  No response in 8 days.   Also, unable to reproduce.
