### ISSUE TITLE
FPP stutters while playing 40 fps FSEQ

### ISSUE THREAD

**Issue by CursedDog19** [FalconChristmas/fpp#899]
My display stutters when playing sequences. I used FPP last year and this did not happen. Very hard to watch, unusable.

**Comment by darylc** [comment]
Please provide further information

**Comment by CursedDog19** [comment]
I play a playlist with fpp and I see occasional stuttering. My setup has an F16V3 and 2 LOR controllers on its serial ports. Sequences sent to FPP (version 4.5) OTA with FPP connect in xlights (2020.51), FSEQ V2 Sparze/xstd.

**Comment by darylc** [comment]
Have you tried troubleshooting your problem via the xlights zoom room?  github issues are more for software bugs than user support.

**Comment by darylc** [comment]
this looks good to close
