### ISSUE TITLE
 v4.x-master-628-gb238358e - P10/Colorlight stopped working in middle of show till reboot

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#903]
So I looked at my house fortunately around 9:30 watching the show and all of a sudden one of my P10 screens just stopped working, I went upstairs and rebooted it and the color light and it kicked back in, I attached the log files and it looks like around 21:36 it either freaks out or just disconnects from the color light, not too sure what happened but have been running this software and FSEQ file for a week with no issue and it just happened tonight.   

3 21:35:28 MATRIX1 ntpd[690]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {RX} 0 packets 0 bytes
Dec  3 21:36:13 MATRIX1 kernel: [644637.794607] ax88179_178a 1-1.1.2:1.0 eth0: ax88179 - Link status is: 0
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {TX} 960389180 packets 3193220669 bytes
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {update} flags 36867 <UP>
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {newlink} index 3 address D8:EB:97:B9:6A:D2 mtu 1500
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {newlink} index 3 operstate 2 <DOWN>
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Withdrawing address record for 169.254.248.5 on eth0.
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Leaving mDNS multicast group on interface eth0.IPv4 with address 169.254.248.5.
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Interface eth0.IPv4 no longer relevant for mDNS.
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Withdrawing address record for fe80::daeb:97ff:feb9:6ad2 on eth0.
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::daeb:97ff:feb9:6ad2.
Dec  3 21:36:13 MATRIX1 avahi-daemon[378]: Interface eth0.IPv6 no longer relevant for mDNS.
Dec  3 21:36:13 MATRIX1 kernel: [644637.923027] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {del} address 169.254.248.5/16 label eth0
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {del} route 169.254.0.0 gw 0.0.0.0 scope 253 <LINK>
Dec  3 21:36:13 MATRIX1 connmand[621]: eth0 {del} route fe80:: gw :: scope 0 <UNIVERSE>
Dec  3 21:36:15 MATRIX1 ntpd[690]: Deleting interface #30 eth0, fe80::daeb:97ff:feb9:6ad2%3#123, interface stats: received=0, sent=0, dropped=0, active_time=18216 secs
Dec  3 21:36:15 MATRIX1 ntpd[690]: Deleting interface #31 eth0, 169.254.248.5#123, interface stats: received=0, sent=0, dropped=0, active_time=18177 secs
Dec  3 21:36:17 MATRIX1 ntpd[690]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Dec  3 21:36:18 MATRIX1 ntpd[690]: error resolving pool 1.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Dec  3 21:36:19 MATRIX1 kernel: [644643.938606] ax88179_178a 1-1.1.2:1.0 eth0: ax88179 - Link status is: 1
Dec  3 21:36:19 MATRIX1 kernel: [644643.947518] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {add} route fe80:: gw :: scope 0 <UNIVERSE>
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {RX} 0 packets 0 bytes
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {TX} 960389180 packets 3193220669 bytes
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {update} flags 102467 <UP,RUNNING,LOWER_UP>
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {newlink} index 3 address D8:EB:97:B9:6A:D2 mtu 1500
Dec  3 21:36:19 MATRIX1 connmand[621]: eth0 {newlink} index 3 operstate 6 <UP>
Dec  3 21:36:21 MATRIX1 avahi-daemon[378]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::daeb:97ff:feb9:6ad2.
Dec  3 21:36:21 MATRIX1 avahi-daemon[378]: New relevant interface eth0.IPv6 for mDNS.
Dec  3 21:36:21 MATRIX1 avahi-daemon[378]: Registering new address record for fe80::daeb:97ff:feb9:6ad2 on eth0.*.
Dec  3 21:36:22 MATRIX1 ntpd[690]: Listen normally on 32 eth0 [fe80::daeb:97ff:feb9:6ad2%3]:123
Dec  3 21:36:22 MATRIX1 ntpd[690]: new interface(s) found: waking up resolver
Dec  3 21:36:25 MATRIX1 ntpd[690]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Dec  3 21:36:35 MATRIX1 ntpd[690]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Dec  3 21:37:00 MATRIX1 avahi-daemon[378]: Joining mDNS multicast group on interface eth0.IPv4 with address 169.254.69.72

[FPP_Logs_20201204.zip](https://github.com/FalconChristmas/fpp/files/5640402/FPP_Logs_20201204.zip)

**Comment by cpinkham** [comment]
If I'm reading that correctly, it looks like it lost link.  Did the colorlight perhaps lose power or do you possibly have a bad cable going between the Pi and colorlight?  I don't know how resilient the colorlight channel output is to losing the connection, I've never tried that.  Guess that's something else for the ToDo list since my P10 matrices are also driven by a colorlight.

Dec 3 21:36:13 MATRIX1 kernel: [644637.794607] ax88179_178a 1-1.1.2:1.0 eth0: ax88179 - Link status is: 0

**Comment by bchiaino** [comment]
that's all i saw that made sense too, the Colorlight has been great for years, the cable i tested with a cable tester and it looks good, the only thing left is the USB to ethernet adaptor and the Pi

**Comment by darylc** [comment]
this looks good to close
