### ISSUE TITLE
FPP adding static route that breaks DNS resolution

### ISSUE THREAD

**Issue by jgarvas** [FalconChristmas/fpp#905]
I'm running Version: v4.4 because I don't want to upgrade now that my show is live.   I currently have my show setup as follows:  

eth0: 192.168.1.225/24 (home network)
          default gw:  192.168.1.1
eth1:  192.168.2.15/24 (show network)
          default gw:  left blank or with 192.168.1.1 still breaks

eth0 is a cat5 wired to the home network
eth1 is a cat5 wired directly to my Falcon F48 that I am shutting off and turning back on before show time.
eth1 is a USB -> ethernet adapter, eth0 is the onboard NIC.

The underlying problem is the DNS servers manually defined (say 1.1.1.1 or 8.8.8.8) are creating a bogus static host route in the routing table, breaking DNS resolution and anything that relies upon DNS resolution.   My FPP is using remote falcon, smart things to control outlets, and after hours music.  Each of those plugins is broken when the DNS resolution fails.

When DNS is defined as 1.1.1.1 this route keeps appearing in the routing table pointed at the ethernet interface of the show network instead of the home network:

> $ netstat -rn
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
> 0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eth0
> **1.1.1.1         192.168.1.1     255.255.255.255 UGH       0 0          0 eth1.     <====**
> 192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
> **192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth1      <====**
> 192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
> 192.168.2.0     0.0.0.0         255.255.255.0   U         0 0          0 eth1
> 192.168.7.0     0.0.0.0         255.255.255.0   U         0 0          0 usb0

This route makes no sense because neither 1.1.1.1 nor 192.168.1.1 can be reached via eth1. If I delete that route, I can immediately begin pinging 1.1.1.1.   I'm also no sure why there is a 192.168.1.1 host route pointing at both eth0 and eth1 now?

> fpp@FPP:/var/log $ ping -c1 1.1.1.1
> PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
> From 192.168.2.15 icmp_seq=1 Destination Host Unreachable
> 
> --- 1.1.1.1 ping statistics ---
> 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
> 
> fpp@FPP:/var/log $ sudo route del 1.1.1.1
> fpp@FPP:/var/log $ ping -c1 1.1.1.1
> PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
> 64 bytes from 1.1.1.1: icmp_seq=1 ttl=54 time=17.7 ms
> 
> --- 1.1.1.1 ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 17.712/17.712/17.712/0.000 ms

Originally, I had my show network on eth0 and my home network on eth1 and the problem existed in the exact opposite direction.   I switched it around to this to see if making eth0 the show network would at least make the route appear on the right network interface, but it does not.

The reason this becomes a big challenge to overcome is I am using timed smart plugs to power everything in my show but the FPP off, and then I turn it on 15 minutes before show time.  Since the cable plugged into the FPP show network interface is a direct link to the Falcon 48 the FPP sees the show network interface come back online and re-applies the routes that break everything 15 minutes before show time:

**Falcon 48 (and eth0 show network) down:**

> fpp@FPP:/var/log $ netstat -rn
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
> 0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eth0
> 192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
> 192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
> 192.168.7.0     0.0.0.0         255.255.255.0   U         0 0          0 usb0

**Turn on the Falcon 48 power:**

> Dec  5 16:20:01 FPP CRON[643]: (fpp) CMD (/usr/bin/php /home/fpp/media/plugins/fpp-after-hours/cronMonitorStream.php >/dev/null 2>&1)
> Dec  5 16:20:06 FPP kernel: [372616.966161] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
> Dec  5 16:20:06 FPP connmand[653]: eth1 {add} route fe80:: gw :: scope 0 <UNIVERSE>
> Dec  5 16:20:06 FPP connmand[653]: eth1 {RX} 3998125 packets 3665913916 bytes
> Dec  5 16:20:06 FPP connmand[653]: eth1 {TX} 2350029 packets 216859625 bytes
> Dec  5 16:20:06 FPP connmand[653]: eth1 {update} flags 102467 <UP,RUNNING,LOWER_UP>
> Dec  5 16:20:06 FPP connmand[653]: eth1 {newlink} index 4 address 00:00:00:06:7E:CC mtu 1500
> Dec  5 16:20:06 FPP connmand[653]: eth1 {newlink} index 4 operstate 6 <UP>
> Dec  5 16:20:06 FPP avahi-daemon[384]: Joining mDNS multicast group on interface eth1.IPv4 with address 192.168.2.15.
> Dec  5 16:20:06 FPP avahi-daemon[384]: New relevant interface eth1.IPv4 for mDNS.
> Dec  5 16:20:06 FPP avahi-daemon[384]: Registering new address record for 192.168.2.15 on eth1.IPv4.
> Dec  5 16:20:06 FPP connmand[653]: eth1 {add} address 192.168.2.15/24 label eth1 family 2
> Dec  5 16:20:06 FPP kernel: [372616.971043] asix 1-1.1.3:1.0 eth1: link up, 100Mbps, full-duplex, lpa 0x4DE1
> Dec  5 16:20:06 FPP connmand[653]: eth1 {add} route 192.168.2.0 gw 0.0.0.0 scope 253 <LINK>
> Dec  5 16:20:06 FPP connmand[653]: eth1 {add} route 192.168.1.1 gw 0.0.0.0 scope 253 <LINK>
> Dec  5 16:20:06 FPP connmand[653]: eth1 {add} route 1.1.1.1 gw 192.168.1.1 scope 0 <UNIVERSE>
> Dec  5 16:20:07 FPP ntpd[733]: Listen normally on 38 eth1 192.168.2.15:123
> Dec  5 16:20:07 FPP ntpd[733]: bind(25) AF_INET6 fe80::200:ff:fe06:7ecc%4#123 flags 0x11 failed: Cannot assign requested address
> Dec  5 16:20:07 FPP ntpd[733]: unable to create socket on eth1 (39) for fe80::200:ff:fe06:7ecc%4#123
> Dec  5 16:20:07 FPP ntpd[733]: failed to init interface for address fe80::200:ff:fe06:7ecc%4
> Dec  5 16:20:07 FPP ntpd[733]: new interface(s) found: waking up resolver
> Dec  5 16:20:08 FPP avahi-daemon[384]: Joining mDNS multicast group on interface eth1.IPv6 with address fe80::200:ff:fe06:7ecc.
> Dec  5 16:20:08 FPP avahi-daemon[384]: New relevant interface eth1.IPv6 for mDNS.
> Dec  5 16:20:08 FPP avahi-daemon[384]: Registering new address record for fe80::200:ff:fe06:7ecc on eth1.*.
> Dec  5 16:20:09 FPP ntpd[733]: Listen normally on 40 eth1 [fe80::200:ff:fe06:7ecc%4]:123
> Dec  5 16:20:09 FPP ntpd[733]: new interface(s) found: waking up resolver
> Dec  5 16:20:17 FPP connmand[653]: IPv4 online check failed for 0x741438 Wired
> 

**resulting route table:**

> $ netstat -rn
> Kernel IP routing table
> Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
> 0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eth0
> **1.1.1.1         192.168.1.1     255.255.255.255 UGH       0 0          0 eth1      <=====**
> 192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
> **192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth1       <=====**
> 192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0      
> 192.168.2.0     0.0.0.0         255.255.255.0   U         0 0          0 eth1
> 192.168.7.0     0.0.0.0         255.255.255.0   U         0 0          0 usb0
> fpp@FPP:/var/log $ 

Why is it adding a 192.168.1.1 host route to eth1 let alone the static 1.1.1.1 route?  It's entirely unnecessary?

**Comment by dkulp** [comment]
Any chance you can flip to master branch and see if it still occurs.  I made a change in one of the script that I think will fix this, but I'd like someone that can reproduce it to verify.   (UI tag in settings, set ui level to developer.   Go to developer tab, select master from git branch drop down, wait a bit, reboot.)

**Comment by darylc** [comment]
@jgarvas Have you had a chance to test the potential fix yet?

**Comment by jgarvas** [comment]
I can’t remember what happened but it quit occurring for me before ever
applying the fix.
