### ISSUE TITLE
Watchdog feature

### ISSUE THREAD

**Issue by chrkov** [FalconChristmas/fpp#906]
**Is your feature request related to a problem? Please describe.**
Wireless sometimes acts weird and will disconnect.  Rebooting via the OLED display or power cycle will bring the unit back

**Describe the solution you'd like**
A watchdog feature that can ping an IP address (Gateway or custom) that would be able to reboot the device if x number of failures happen

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bigwavedave42** [comment]
In the Script Repository (FPP -> Content Setup -> Script Repository Browser) there is a "fppWatcher" and "fppWatcherStart".  Perhaps you could extend those or copy/edit one of those to do something similar. 

Those scripts were trying to solve when the fpp daemon would stop running unexpectedly, and have it restart.  That has largely been solved in evolution of the project.  Regardless, it might be a starting point for a solution to your problem.   It actually created some problems, at times, as I recall.  

Honestly, the better fix is to solve your wireless issue.  While you aren't alone in having this problem, it is usually the sign of a problem elsewhere (AP placement, channel congestion nearby, USB wireless, small power supplies, etc)

**Comment by darylc** [comment]
This looks good to close?

**Comment by ghormann** [comment]
No reply in 8 days.  Closing.
