### ISSUE TITLE
Won't output to Kulp8PB with output misconfiguration

### ISSUE THREAD

**Issue by thekameleon** [FalconChristmas/fpp#910]
FPP 4.5.1 on BBB running with Kulp8PB.

I was messing around with my configuration and I had specified a zig zag.  Later on while messing around I removed the nodes and accidentally left the ZigZag count at 64.  I got a message that BBB48String would not initialize see the log file on the status page.  Under Info I saw nothing so I set it to debug and rebooted.  I found an error that led me to my misconfiguration.  It said the following:

2020-12-05 16:43:57.998 (2784) channeloutput/PixelString.cpp:258: Invalid PixelString Config vs.zigZag > vs.pixelCount

This led me to go look and fix the issue.  Then everything worked as it should have.  My ask is to make this error more apparent.  Either a message or warning during the saving to show that the configuration is wrong.
[fppd.log](https://github.com/FalconChristmas/fpp/files/5649524/fppd.log)

**Comment by darylc** [comment]
@thekameleon is this still a problem in fpp 6.3?

**Comment by thekameleon** [comment]
Give me a few days to recreate the test case. I will let you know.

**Comment by thekameleon** [comment]
I tested this out on 6.3 by setting a port to 0 pixels with a zip zag of 20, saves, reset fppd. No error messages or unexpected behavior. I think this issue can be closed. Thanks for looking into it.
