### ISSUE TITLE
Better Document: fpp scheduler odd - even

### ISSUE THREAD

**Issue by JeremyDrossinis** [FalconChristmas/fpp#912]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to 'content setup > scheduler
2. set days to even, set a playlist and click save
repeat of odd days
3. go to status control 
4. the odd day playlist will play if the day is even, and if the day is odd the even day play list will play

**Expected behavior**: 
would expect the reverse to happen

on odd days ie 1,3,5,7,9 the odd play list to play
and on even days 2,4,6,8,10 the even play list to play

**Additional context**: 

**Additional Attachments**
![image](https://user-images.githubusercontent.com/34740950/101348369-a4e0f200-38df-11eb-90ae-8d5696dd7cb7.png)
![image](https://user-images.githubusercontent.com/34740950/101348390-ab6f6980-38df-11eb-9c7d-885729123a65.png)

Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
[FPP_Logs_20201207.1158.zip](https://github.com/FalconChristmas/fpp/files/5652480/FPP_Logs_20201207.1158.zip)

3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by cpinkham** [comment]
Closing ticket as the odd/even behavior was described in the forum post.  The Odd/Even is not based on the day of the week or month or year, it is odd/even starting at July 15, 2013, the day of the first commit to the FPP code repository.  This was done so that it did not have two odd days in a row on the 7th and first days of the week or on months that have 31 days going into the next month, etc..

**Comment by darylc** [comment]
@cpinkham had a user in the zoom room confused by this, can we do something to clarify the behavior in the gui?

**Comment by ghormann** [comment]
Also confusion on forum today....

**Comment by ghormann** [comment]
Just add a fourth note to the bottom of the page?

**Comment by darylc** [comment]
@ghormann better than nothing
