### ISSUE TITLE
Test mode ports sometimes turning off randomly

### ISSUE THREAD

**Issue by tielur** [FalconChristmas/fpp#913]
**FPP Version and Hardware**: 
FPP 4.5 on Raspberry Pi 3

**Describe the bug and Steps to reproduce**: 
1. Selecting a subset of ports on the test page will sometimes turn on/off random ports when you refresh the browser

**Expected behavior**: 
I would expected the ports that I turned on to stay on and the ports that are off to stay off between browser refreshes

**Additional Attachments**
Here's a video that displays that behavior

https://www.youtube.com/watch?v=rjlCM7kxyrs

**Comment by patdelaney** [comment]
Tyler - I will forward your report to David Pitts. He is the Falcon Controller software guy. This issue tracker is for Falcon Pi Player not Falcon controllers. :-)  I am going to close this ticket,

**Comment by tielur** [comment]
@patdelaney oops my bad! 🤦

**Comment by tielur** [comment]
@patdelaney is the controller open source that I can open this issue on?

**Comment by patdelaney** [comment]
No worries

**Comment by patdelaney** [comment]
I don;t think it's opensource, but I'm looking for the issue tracker  I'll
send the link if I find it

**Comment by darylc** [comment]
@tielur This is a bug that was fixed in verison 2.59, grab it from pixelcontroller.com

**Comment by patdelaney** [comment]
Ty Daryl
