### ISSUE TITLE
Raspberry Pi DNS Issues - Keeps resetting to Localhost.

### ISSUE THREAD

**Issue by neowolfwitch** [FalconChristmas/fpp#915]
**FPP Version and Hardware**: 
v4.5.1-5-g1f787185 on Raspberry Pi

On reboot- DNS settings in /etc/resolv.conf are set to 127.0.0.1 (localhost).
At this point updates and NTP no-longer work. The time will be wrong, messing up any scheduled actions.

**Describe the bug and Steps to reproduce**: 
In FPP Network settings- enter:
DNS Server Mode: Manual
DNS Server 1: 1.1.1.1
DNS Server 2: 8.8.8.8

Click [Update DNS] button.
Click [Restart DNS] button.

Verify DNS settings are in /etc/resolv.conf.

Reboot FPP.

cat /etc/resolv.conf
nameserver 127.0.0.1

So- I have to manually set the nameservers in resolv.conf every time I reboot one of my Raspberry Pi FPPs.

**Expected behavior**: 
DNS changes saved in FPP should be persistent across reboots. It should not be necessary to manually update DNS on every boot.

**Additional context**: 
This only appears to affect Raspberry Pis. I have two BBB FPP installs that do not suffer from this issue.

**Additional Attachments**
Not sure if they will be helpful at all, but I am attaching log files as-requested.
[FPP_Logs_20201208.1513.zip](https://github.com/FalconChristmas/fpp/files/5660060/FPP_Logs_20201208.1513.zip)

**Comment by neowolfwitch** [comment]
I'm still seeing this behavior in 4.6.

**Comment by neowolfwitch** [comment]
I'm adding a video that illustrates the problem...

[Rpi FPP DNS Issue.mp4.zip](https://github.com/FalconChristmas/fpp/files/5711246/Rpi.FPP.DNS.Issue.mp4.zip)

**Comment by dkulp** [comment]
I have no idea what you did to mess up your system, but the /etc/resolve.conf file should NOT have a "Generated with resolveconf" line in it.   We only use connman so the first line should be "# Generated by Connection Manager".   I'd strongly suggest reflashing or at least re-do the OS with the fppos update method to try and get it back into a proper state.

**Comment by neowolfwitch** [comment]
Daniel-

I have two Pis doing the same thing. These were both clean-flashed with FPP 4.5 (FPP-v4.5-Pi.img). It was a full release, and the file I have is dated Nov. 23, 2020. I have only updated both Pis using the update functionality in FPP. I had a similar issue that I reported earlier with FPP 4.5.1-3, but it seemed to be fixed in 4.5.1-4. It came back again in 4.5.1-5.  

It's possible some specific build(s) that hit Github broke them, but I haven't done anything to otherwise mess with these. The only thing I have done is edit resolv.conf every time I reboot them and see that it has been changed to localhost again.

**Comment by neowolfwitch** [comment]
Per your comment, I am going to go ahead and run the fppos update to see if that resolves this.

**Comment by dkulp** [comment]
The other thing to check is to make sure /etc/resolv.conf is a proper sym-link over to /var/run/connman/resolv.conf.     I'm wondering if your manual editing of that file has caused connman to unlink it. 

`lrwxrwxrwx   1 root root      28 Sep  2 23:01 resolv.conf -> /var/run/connman/resolv.conf`

**Comment by neowolfwitch** [comment]
I'm only updating one of the Pis for now, so I checked the other. It's still linked. Screen grab attached...
![Screen Shot 2020-12-17 at 1 05 15 PM](https://user-images.githubusercontent.com/68392802/102531879-b4430680-4068-11eb-9354-0ed551be191d.png)

You weren't kidding about FPPOS taking a LONG time. It's been sitting on "usr/share/gdb/python/gdb/printer/" for at least 5 minutes now. (Unless it's actually done and just stuck.)

**Comment by dkulp** [comment]
If it's stuck on a single file for more than a few minutes, it's likely done.  Just reboot it.

**Comment by neowolfwitch** [comment]
Okay, after running the FPPOS update, I can confirm that /etc/resolv.conf now says:
![Screen Shot 2020-12-17 at 1 19 51 PM](https://user-images.githubusercontent.com/68392802/102533514-24528c00-406b-11eb-802f-a94a7f4f3d7b.png)
I've rebooted several times. So hopefully this is resolved. :)

**Comment by neowolfwitch** [comment]
...and, the problem is back!
I'm wondering if something is wrong with the GIT upgrade process. Here is all I did...
After updating FPPOS I rebooted three times and verified that DNS was correct.
I ran the upgrade to build "acc671a" from the About page:
![Screen Shot 2020-12-17 at 1 25 41 PM](https://user-images.githubusercontent.com/68392802/102534132-e73ac980-406b-11eb-89f4-424d6ae6c016.png)
I rebooted, and now I've got this again...
![Screen Shot 2020-12-17 at 1 31 11 PM](https://user-images.githubusercontent.com/68392802/102534296-2537ed80-406c-11eb-87e6-f2df7fbc4d76.png)

**Comment by neowolfwitch** [comment]
Attaching logs...
[FPP_Logs_20201217.1932.zip](https://github.com/FalconChristmas/fpp/files/5711731/FPP_Logs_20201217.1932.zip)

**Comment by dkulp** [comment]
Do you have the Tethering mode set to "Enabled"?   I think I may have figured out what's triggering it.....

**Comment by neowolfwitch** [comment]
It's "Enabled with no connection." Here is my whole network config screen:
![Screen Shot 2020-12-17 at 1 54 22 PM](https://user-images.githubusercontent.com/68392802/102536598-75fd1580-406f-11eb-93a2-26977e59abd8.png)
I'm not using WIFI at all, only ETH0 if that is a factor.

**Comment by dkulp** [comment]
Can you do whatever you need to to get the latest (4.6-10). It should then tell you to reboot.  Not 100% sure this will fix your specific case, but it fixes the exact same symptom if tethering mode is set to enabled.

**Comment by neowolfwitch** [comment]
I think that did it!
I upgraded to 4.6-10 (9b4890d), and rebooted as-prompted.
After rebooting I immediately set my DNS to 1.1.1.1 and 8.8.8.8 again. I didn’t change anything else in the Network settings.
Instead of surfacing the [Restart DNS] button, it just prompted for a reboot again. So I rebooted.
The DNS settings are still valid. I have since rebooted twice, set DNS again, and rebooted twice, and the DNS settings have remained correct.

**Comment by nmiller0113** [comment]
Following along on this, just out of interest, but isn't tethering enabled by default? I swore it was, even if there wasn't a wireless device connected.

**Comment by neowolfwitch** [comment]
Yes- it’s enabled by default.

**Comment by darylc** [comment]
This looks good to close now.
