### ISSUE TITLE
unexpected end of file in /opt/fpp/www/config.php on line 488

### ISSUE THREAD

**Issue by ChZeman** [FalconChristmas/fpp#918]
I'm getting a blank web page when trying to access FPP. I found the following in the error log:

 PHP Parse error:  syntax error, unexpected end of file in /opt/fpp/www/config.php on line 488

The file seems to compare with that's on git. Any ideas? This is version 3.5.6. I'd like to upgrade from the web interface or command line if possible. I'd rather not have to re-image the Pi.

Thank you,
Chris

**Comment by cpinkham** [comment]
This is a question more suited for the forum than a bug report, but you can manually update from  your v3.5.6 to v3.6 using the following commands after ssh-ing to the Pi/BBB.

sudo su - root
cd /opt/fpp/
git reset --hard HEAD
git pull
git checkout v3.6
git pull
/opt/fpp/scripts/upgrade_config
cd /opt/fpp/src/
make clean
make -j 4

Then exit and restart fppd via the web UI or reboot the system using the web UI or "shutdown -r now" from the CLI.

Once on v3.6, you can stay there or look at upgrading to v4.x using a fppos image file upgrade.  Look at the new release posts on the forum for more info on this.

**Comment by ChZeman** [comment]
Thank you. I'll check the forums. I followed your instructions and have the same error, only now it's complaining that the file is too short at 526 lines.
