### ISSUE TITLE
BBB Black High CPU on Tune to sign

### ISSUE THREAD

**Issue by galluccib** [FalconChristmas/fpp#919]
Running a P5 3x3 tune to sign that pretty much just says "tune to xx.xx" and noticed the CPU is hanging around 80% most the time.

BeagleBone Black
FPP Version: | v4.5.1-6-gb03cf1c0

via top...

 5954 root      20   0  214164  36948  18732 S  78.1   7.5   7:16.91 fppd 

Logs attached.
[FPP_Logs_20201211.0049.zip](https://github.com/FalconChristmas/fpp/files/5676440/FPP_Logs_20201211.0049.zip)

**Comment by galluccib** [comment]
Forgot to add.. Prior on 3.6 same setup was fine.... Noticed it today after upgrading to 4.5.

**Comment by darylc** [comment]
is this actually causing a problem?

Have you checked that nothing is misconfigured to send it unwanted ddp or e1.31 packets?

**Comment by galluccib** [comment]
Noticed the scrolling lags for a few secs and then fine... Something else I just noticed after upgrading to 4.5.1.. When in bridge mode I notice on universe 64 it starts taking errors and gets much worst has it goes on. If I run something within the 64 universes see zero issues. Update below..

Universe	Start Address	Packets	Bytes	Errors
1	1	4708	2401080	0
2	511	4708	2401080	0
3	1021	4708	2401080	0
4	1531	4708	2401080	0
5	2041	4708	2401080	0
6	2551	4708	2401080	0
7	3061	4708	2401080	0
8	3571	4708	2401080	0
9	4081	4708	2401080	0
10	4591	4708	2401080	0
11	5101	4708	2401080	0
12	5611	4708	2401080	0
13	6121	4708	2401080	0
14	6631	4708	2401080	0
15	7141	4708	2401080	0
16	7651	4708	2401080	0
17	8161	4708	2401080	0
18	8671	4708	2401080	0
19	9181	4708	2401080	0
20	9691	4708	2401080	0
21	10201	4708	2401080	0
22	10711	4708	2401080	0
23	11221	4708	2401080	0
24	11731	4708	2401080	0
25	12241	4708	2401080	0
26	12751	4708	2401080	0
27	13261	4708	2401080	0
28	13771	4708	2401080	0
29	14281	4708	2401080	0
30	14791	4708	2401080	0
31	15301	4708	2401080	0
32	15811	4708	2401080	0
33	16321	4708	2401080	0
34	16831	4708	2401080	0
35	17341	4708	2401080	0
36	17851	4708	2401080	0
37	18361	4708	2401080	0
38	18871	4708	2401080	0
39	19381	4708	2401080	0
40	19891	4708	2401080	0
41	20401	4708	2401080	0
42	20911	4708	2401080	0
43	21421	4708	2401080	0
44	21931	4708	2401080	0
45	22441	4708	2401080	0
46	22951	4708	2401080	0
47	23461	4708	2401080	0
48	23971	4708	2401080	0
49	24481	4708	2401080	0
50	24991	4708	2401080	0
51	25501	4708	2401080	0
52	26011	4708	2401080	0
53	26521	4708	2401080	0
54	27031	4708	2401080	0
55	27541	4708	2401080	0
56	28051	4708	2401080	0
57	28561	4708	2401080	0
58	29071	4708	2401080	0
59	29581	4708	2401080	0
60	30091	4708	2401080	0
61	30601	4708	2401080	0
62	31111	4708	2401080	0
63	31621	4708	2401080	0
64	32131	4703	2398530	5
65	32641	4701	2397510	7
66	33151	4699	2396490	9
67	33661	4697	2395470	10
68	34171	4695	2394450	12
69	34681	4695	2394450	12
70	35191	4694	2393940	13
71	35701	4692	2392920	15
72	36211	4689	2391390	18
73	36721	4691	2392410	17
74	37231	4690	2391900	18
75	37741	4689	2391390	19
76	38251	4685	2389350	23
77	38761	4685	2389350	23
78	39271	4680	2386800	28
79	39781	4674	2383740	34
80	40291	4674	2383740	34
81	40801	4672	2382720	36
82	41311	4669	2381190	39
83	41821	4670	2381700	38
84	42331	4669	2381190	38
85	42841	4666	2379660	41
86	43351	4667	2380170	40
87	43861	4668	2380680	39
88	44371	4666	2379660	41
89	44881	4663	2378130	44
90	45391	4665	2379150	42
91	45901	4662	2377620	44
92	46411	4663	2378130	43
93	46921	4663	2378130	43
94	47431	4659	2376090	47
95	47941	4658	2375580	48
96	48451	4658	2375580	48
97	48961	4654	2373540	52
98	49471	4652	2372520	54
99	49981	4652	2372520	54
100	50491	4644	2368440	62
101	51001	4627	2359770	78
102	51511	4580	2335800	122
103	52021	4477	2283270	209
104	52531	4360	2223600	305
105	53041	4258	2171580	388
106	53551	4161	2122110	451
107	54061	4122	2102220	481
108	54571	4076	2078760	516
109	55081	4039	2059890	539
110	55591	3998	2038980	568
111	56101	3961	2020110	597
112	56611	0	0	0
113	57121	0	0	0
114	57631	0	0	0
115	58141	0	0	0
116	58651	0	0	0
117	59161	0	0	0
118	59671	0	0	0
119	60181	0	0	0
120	60691	0	0	0
121	61201	0	0	0
122	61711	0	0	0
123	62221	0	0	0
124	62731	0	0	0
125	63241	0	0	0
126	63751	0	0	0
127	64261	0	0	0
128	64771	0	0	0
129	65281	0	0	0
130	65791	0	0	0
131	66301	0	0	0
132	66811	0	0	0
133	67321	0	0	0
134	67831	0	0	0
135	68341	0	0	0
136	68851	0	0	0

**Comment by darylc** [comment]
This is a configuration error rather than a bug.

Your log files indicate slow output.

You have UDP outputs configured here to send 49981 channels to the network via multicast.   That is likely killing your network especially if you are using wifi (I can't easily tell from the upload) and also causing your input errors.

If you deconfigure that (you will need to stop telling xlights to reconfigure it too) you should be all good.

**Comment by darylc** [comment]
@ghormann Can you close this one please?
