### ISSUE TITLE
Add ability to choose Log Level per category

### ISSUE THREAD

**Issue by MarkA75160** [FalconChristmas/fpp#920]
**Is your feature request related to a problem? Please describe.**
No problem, just an enhancement to help with troubleshooting

**Describe the solution you'd like**
Currently, changing the Log Level (Warn, Info, Debug, etc.) changes that level of logging for ALL selected categories.  For example if you enable Debug level then you get debug info for all selected categories even if you're only interested in one.  You can disable logging for other categories but then you get NO logging for those.

I would like to be able to get Debug logging for one or more categories while still getting Info logging for others.  For example, while troubleshooting Media Playback issues it would be helpful to enable Debug for Media Outputs and Info for Multisync, Playlist, and Scheduler.  Having DEBUG level on all three at the same time clutters the logs and is harder to sift through while troubleshooting.

**Describe alternatives you've considered**
leave as is and export full debug log to spreadsheet and filter the entries.

**Additional context**
Something like this (just an example, could be done differently)
![image](https://user-images.githubusercontent.com/57245161/101939977-6717ee00-3bab-11eb-8c55-3d68a0d8eca4.png)

**Comment by ghormann** [comment]
There is still some more clean up here
1. Allow --log-level to have a detailed version: debug:schedule,player;excess:mqtt  (Keep existing functionally too though.) 
2. Fully remove --log-mask
3. Restore --log-level back to  execlp() on restart.  Use detailed version
4. Add "Set all to" button on Settings UI.

**Comment by ghormann** [comment]
all subtask completed as of 2c05eb61e4116885a9079e7ad384be3f836121a7
