### ISSUE TITLE
Wireless Instabilities

### ISSUE THREAD

**Issue by dotModded** [FalconChristmas/fpp#922]
Running 4.4 image updated to v4.5.1-7-gfac2b2e0 on a Raspberry Pi 3+

I am planning set the wlan0 interface to connect to a private wifi subnet for control. For testing I've connected to my main network with a static IP. I'm installing this in an area not accessable to cat5e and would like purely wireless control.

On a fresh install, I connected via wireless tether. Connected to the web ui. In the falcon ui I set up the network interface. Rebooted the device, and connected to it over the main network to the set static IP. If I restart the device without a full loss of power, I can continue to connect and modify as expected. However when a PROLONGED full power loss occurs, I am no longer able to connect to the web ui. I'm still able to ping out to the gateway and internet from CLI, I'm just unable to connect to the panel. If I ping fpp.local on the pi it reports the subnet ip (192.168.7.2) leading me to believe it's always setting the webserver to use eth0 instead of the wlan0.

The EXTREMELY odd behavior is when I connect the eth0 adapter to a wired connection. It immediately starts working. If I unplug the wired connection. It becomes accessable over wlan0 like it did on initial setup. 

Info from digging around in shell. Restarting fpp by running fpp -r does not fix this problem, restarting the apache2 service also does not solve this problem. Netstat reports fppd as dgram and is not connected on port 24805 shown below.

I checked all of the logs in ~/media/logs (as I can't get into the web ui) the only error presented is LS can't access interface.e* (expected as no configuration is saved, when configured the same connection behavior is present, just without the error.

https://i.imgur.com/AxoO0oL.png

https://i.imgur.com/uv5kH9D.jpeg

https://i.imgur.com/cYr8wNd.png

https://i.imgur.com/K3ibwVQ.png

https://i.imgur.com/MKckG11.jpeg

https://i.imgur.com/VWQgS31.jpg

https://i.imgur.com/vGZ1ajN.jpg

**Comment by patdelaney** [comment]
do you have time to jump on a zoom call with me

**Comment by dotModded** [comment]
Yeah! If you could do discord it would be easier for me, if not I can do zoom no problem. Discord is @dotModded#3004 or email me at dotmodded@gmail.com and we can set something up. I appreciate it!

**Comment by ghormann** [comment]
@patdelaney  @dotModded  Is this something that requires an open bug ticket or has the issue been resolved?

**Comment by ghormann** [comment]
Closing as no followup since 2020.
