### ISSUE TITLE
Playlist Randomize feature randomizes too often?

### ISSUE THREAD

**Issue by rjhodge** [FalconChristmas/fpp#925]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP: v4.x-master-734-g59a2f391, OS: v4.2, Hardware: Pi 4

**Describe the bug and Steps to reproduce**: 
On a playlist that has randomize turned on once per load randomizes at times when you least expect it.
First Reproduction Method:
1. Go to Status/Control -> Status Page
2. Select a playlist from the drop down that has randomize once per load turned on.
3. Notice that the playlist is already randomized and pay attention to the order
4. Select a song from the playlist and hit play.
5. Notice that the song you selected is not the one playing and the playlist has been rerandomized

Second Reproduction Method:
1. Start a playlist playing that has randomize once per load turned on
2. Using Big Buttons or directly via the API insert a playlist to play
3. Use the command Insert Playlist After Current
4. After new playlist is finished the prior playlist restarts at the correct numeric position
5. Notice however the playlist has been rerandomized to a new order

**Expected behavior**: 
1. For the first reproduction method the playlist should maintain the order that was first loaded and not rerandomize the playlist when selecting and playing an item. This first scenario may not be an issue as the playlist may not actually be loaded at this time, so not sure what the expected behavior should be.
2. For the second reproduction method the original playlist should reload the original list and resume where it left off and not rerandomize the list.

**Additional context**: 
None

**Additional Attachments**
[FPP_Logs_20201215.1634.zip](https://github.com/FalconChristmas/fpp/files/5697215/FPP_Logs_20201215.1634.zip)

None

**Comment by cpinkham** [comment]
For issue 1, I will have to add some logic to not randomize if the user passed in a starting position.

For 2, I'm not seeing how this could happen in the code so will have to try to reproduce it.  Was the inserted playlist a song that took a while to play or something that happened real quick like just a command or starting an effect?

**Comment by rjhodge** [comment]
Let me try and reproduce again. But basically everyone in the cove has access to Big Buttons to insert a song they want next. For every song we have a playlist set up that has one song in the Main section. Then when the play list restarts it randomizes. Let me see if I can get a video of it happening.

**Comment by cpinkham** [comment]
Thanks, I will try to reproduce tonight if I can and get a fix into v4.6 if I can find something wrong with inserted playlists and randomization.

**Comment by rjhodge** [comment]
Nevermind about the second issue. Definitely is not a problem sorry about that.

**Comment by rjhodge** [comment]
Well I tried to upload the video but can't seem to get it small enough to show problem 1. Anyways I'll pay attention tonight when the show is running and try and confirm that the second issue isn't a problem

**Comment by cpinkham** [comment]
OK, thanks for confirmation on part 2.  I'll look at part 1.

**Comment by cpinkham** [comment]
Part 1 is fixed by 93578ac57d7 in master and also merged to v4.6.
