### ISSUE TITLE
DMX RGB devices flash after going through upgrade process

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#926]
Regardless of whether an update is available, if I use the Upgrade FPP button and let it run through the process, at the end my DMX RGB devices flash blue every second or so. The way I correct it is by rebooting the FPP. Here is a [video of it](https://drive.google.com/file/d/1oX0gU0tMbjRNNQoWlrsXNd2sWGSM5tjN/view?usp=sharing), and I've also attached the logs before and after (prior to rebooting and resolving it) pressing the Upgrade FPP button, in case that helps. I can reproduce this every time. There is something in the upgrade process triggering this behavior. Nothing else operates out of the ordinary on this F32B Kulp Controller and after rebooting sequences and the DMX RGB devices play perfectly. I've only seen this since version 4 that I can recall as it wasn't happening last year on whatever the latest version was at Christmas, with the exact same equipment.

**FPP Version and Hardware**: 
FPP 4.6 on a BBB with a Kulp F32B attached. This didn't happen last year on versions prior to 4.x, and has happened ever since I did the initial fresh install of 4.4.

**Describe the bug and Steps to reproduce**: 
In the description

**Expected behavior**: 
Nothing should be flashing following the Upgrade FPP process

[After_FPP_Logs_20201215.2113.zip](https://github.com/FalconChristmas/fpp/files/5698695/After_FPP_Logs_20201215.2113.zip)
[Before_FPP_Logs_20201215.2109.zip](https://github.com/FalconChristmas/fpp/files/5698696/Before_FPP_Logs_20201215.2109.zip)

**Comment by patdelaney** [comment]
Nathan can you attach a screenshot of the Channeloutputs screen

**Comment by nmiller0113** [comment]
<img width="547" alt="Screen Shot 2020-12-15 at 1 52 48 PM" src="https://user-images.githubusercontent.com/1048868/102277254-da3ba000-3edc-11eb-85fd-172848385809.png">

Sure thing, there you go!

**Comment by patdelaney** [comment]
For the first test: I user a Pi with a Pi cap and a DMX dimmer connected. upgrade from 4.5 to 4.6 and after fpp restarted DMX data was was present but no channels  1-4 were lighting up.  I will now test on BBB with F8.

Nathan do you have always transmit channel  data checked?
![image](https://user-images.githubusercontent.com/8147459/102278002-aec1b100-3eee-11eb-9b4a-3aaa276c4445.png)

**Comment by nmiller0113** [comment]
@patdelaney I do not. I don't even have the Advanced UI exposed, but I did look just to confirm it wasn't set and it is not. Some additional context, these are the LOR floods connected directly to the DMX interface on the F32, and each flood is on its own port/pair of wires off of the same serial interface. Just to re-iterate in case it was missed previously. This was connected exactly the same to the exact same controller, on the exact same port last year. The only thing that changed this year was the FPP version. This only happens if I press the Upgrade FPP button. It's somewhere in the process that triggers it. A reboot clears it right up. Thanks!

**Comment by patdelaney** [comment]
After speaking with one of the developers, this is a known issue. It's been a low priority as the team has been fixing issues that directly impact a user's show. The work around that you stated is the official work around for now. Thank you for filing the bug, now it will have better visibility.

**Comment by nmiller0113** [comment]
@patdelaney, great to hear I'm not going crazy and happy to have reported it for tracking purposes. Most definitely not urgent :)

**Comment by patdelaney** [comment]
This may be fixed

**Comment by darylc** [comment]
FPP Team decided to close this, it may be fixed but if it is not they will not try to.
