### ISSUE TITLE
Lights on smart receiver come on after cold boot

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#927]
I reported this [in the forum](http://falconchristmas.com/forum/index.php/topic,13647.0.html) as well but I thought I'd add a bug to track it. It's not an urgent issue and it's not impacting performance or usability.

I have one F32 with 3 smart receivers connected to 41-44. Everything works as it should and I'm not having any issues. What I'm seeing is the first pixel of every string connected to the receivers turns on (white) after a shutdown/power off/power on cycle. This does not happen on a reboot when power is not removed for any period of time. I thought it may be related to it being a remote so I set it to standalone, but it gets worse that way. In standalone it turns the first four pixels on. I can reproduce both behaviors consistently and have even swapped controllers and receivers. Seems like it is only something that happens after a cold boot. Another thing to note is that it happens after FPP starts, not right when you power it back on. The only thing that clears it is sending data to the pixels and then stopping it. Then all behaves normal from there.

**FPP Version and Hardware**: 
FPP 4.6 on a BBB with a Kulp F32B attached. Though this has happened on every version I've upgraded from since 4.4. I'm not sure before that as it didn't happen on any 3.x versions last year and I started with 4.4 this year.

**Expected behavior**: 
No lights come on after a cold boot.

I've attached logs from it after a cold boot before I sent any data to clear out the white lights.

[FPP_Logs_20201215.2137.zip](https://github.com/FalconChristmas/fpp/files/5699564/FPP_Logs_20201215.2137.zip)

**Comment by darylc** [comment]
@patdelaney do you have any ability to test this?

**Comment by patdelaney** [comment]
I don't have a F32B in the "one of Everything Lab" (hint @dkulp ) but I was able to test the scenario with F8-PB. I did notice that when a smart receiver is connected to a F48 the 4 status lights on the smart receiver light up the F48 is sending data. When I connect the smart receiver to one of the outputs on F8-PB the 4 data lights do not light up. If I put FPP into display testing mode, then the 4 status lights turn on. Is this correct behavior?

**Back to the test:** 
I can reproduce the observed behavior with a smart receiver that is powered off the same power supply as the F8-PB. If I shut FPP down gracefully, and when it's off unplug the power supply. (let the led's on the board go dark before plugging back in) Then apply power, the 1st pixel will light up, but once FPPD starts it goes out. When FPPD is restarted at some point it sends out a brief signal, I see the data lights on the smart receiver turn on and then off and then the first pixel is goes off.

A smart receiver that is powered from a different power supply that does not get shut down when the FPP  PS is off does not have the first pixel lit.

@nmiller0113 are the smart receivers powered from the same Power supply as the FPP?

**Comment by darylc** [comment]
@patdelaney Thanks - any chance you can confirm if the same thing happens on super old versions as reported?

**Comment by darylc** [comment]
My understanding is that fpp doesn't output any pixel outputs until a sequence is playing, so if for whatever reason a receiver decides to light up pixels then they will stay on until a sequence (or something else that causes fpp to output pixels to start).  This is different to the other pixel controllers out there which tend to output pixel data on all ports at all times even if nothing is happening.

**Comment by nmiller0113** [comment]
@darylc @patdelaney, my apologies for missing your response to this so long ago. I no longer have the F32 and have moved to the K128 which works great!
