### ISSUE TITLE
Issue saving VirtualMatrix settings on 4.6

### ISSUE THREAD

**Issue by rudybrian** [FalconChristmas/fpp#931]
**FPP Version and Hardware**: 
Pi4 running FPP v4.6-6-g7978055a

**Describe the bug and Steps to reproduce**: 
Add a virtual matrix with a channel count above 20000. An error pops up when you attempt to save per the attached image. The settings do not save if this occurs.

**Expected behavior**: 
Virtual matrix should allow resolutions with an effective channel count upwards of 20k

**Additional context**: 
Reported in the Zoom room this evening. Seems to have started happening with 4.6, but hadn't been observed on 4.4.

**Additional Attachments**
Please see attached image.

![fpp1 6-virtualmatrix-bug](https://user-images.githubusercontent.com/6729532/102456721-786f5900-3ff6-11eb-813d-b091d4faac00.png)

**Comment by dkulp** [comment]
Resolved

**Comment by TedZ58** [comment]
I just wrote the image v4.6 to my brand new Rpi4, and I am getting the same message about the 20000 channel count.

**Comment by ghormann** [comment]
GO to about.php and do an update.  

Looking at github, The fix (b5f24ac4c0f27687fd9e698b094c96a4d5e43cbc) was pushed to the 4.6 branch after the 4.6 images was made.

**Comment by TedZ58** [comment]
I tried that. It can't connect with github.
