### ISSUE TITLE
Remote Video Playback Laggy In VLC 

### ISSUE THREAD

**Issue by vvvteddybearvvv** [FalconChristmas/fpp#932]
Version Info |  
FPP Version: | v4.x-master-737-g23bf3298
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v4.4
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 100000009b4965df
Kernel Version: | 5.4.72-v7l+
Local Git Version: | 23bf329

**Describe the bug and Steps to reproduce**: 
When Playing .MP4 Files on a remote  video is laggy  and or choppy on the HDMI output.

**Expected behavior**: 
Video to play smoothy and be in sync with the Master

**Additional context**: 
Tested this on the latest version the we thought fixed this.. Issue is not fixed Can recreate on Multiple RPI's and HW Revisions IE Pi 2 Pi 3 Pi 4.

**Additional Attachments**

[fppd.log.1.zip](https://github.com/FalconChristmas/fpp/files/5712234/fppd.log.1.zip)

5. Attach to this ticket.

**Comment by cpinkham** [comment]
Please update to the latest v4.6 version and see if the problem persists.  We have made a couple changes that are helping with sync in our testing.

**Comment by ghormann** [comment]
@vvvteddybearvvv  Did this help address the problem?

**Comment by darylc** [comment]
lets close this given the lack of responses from the OP

**Comment by vvvteddybearvvv** [comment]
It never fixed the problem. But I just rolled back to and old version for
the season as the show was too important

**Comment by ghormann** [comment]
Closing as 5.0 includes a whole new version of vlc player.    If this does come back in 5.0, please let us know.
