### ISSUE TITLE
DMX Output requires Channel Output to be 512

### ISSUE THREAD

**Issue by jollylinux** [FalconChristmas/fpp#933]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.5 running on Raspberry Pi*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Output Settings
2. Trying to setup DMX-Pro output for Raspberry Pi using DMX Dongle
3. When the Channel Count is set to the actual number of channels I was trying to use (i.e. 12), the DMX Dongle was receiving data, but was not sending the correct data - none of the DMX lights lit up
4. When I changed the channel count to the default 512, it output correctly

**Expected behavior**: 
I believe there is a bug that requires the channel count for DMX output to be 512 instead of a manually set amount.

![image](https://user-images.githubusercontent.com/31421653/102703495-c372b180-422c-11eb-9a9b-851698f2d1e6.png)

**Comment by dkulp** [comment]
This MAY be an issue with the dongle of the dmx device...  I know the LOR stuff will not work at all if the channel count is under 16.  If you upload  configuration from xLights, we have a min of 16 for that reason.

**Comment by patdelaney** [comment]
I will see if I can reproduce this in the lab. (if I have the smae dongle)
Which DMX dongle are you using?  
Based on your description are you trying to use DMX channels 1-12?
What type of DMX device are you trying to connect to?

**Comment by jollylinux** [comment]
I am using the DMXKing Dongle connected to the USB port of the Raspberry Pi.  It is outputting DMX data to a generic RGB 12-output board.  When the Channel is set to anything other than 512, I do see the DMX dongle blinking as if it is pushing data, but the board indicates no data is received for channels 1-12.

The board was able to work using the test output on XLights just fine, which is what led me to change the channels back to 512 and it start working again.

**Comment by ihbar** [comment]
Hi
I have a Enttec DMX Pro and one old Raspberry.  I can perform a test and have a look if it helps.  Just let me know. 
Stephane

**Comment by darylc** [comment]
@jollylinux Can you confirm if your dongle works in other software when sending it less than 512 channels?  Eg outputting from xlights directly?

**Comment by jollylinux** [comment]
It does. When I used the dongle with xlights, I did not have to make this
change.

**Comment by bloojoop** [comment]
I am experiencing similar issue (and I have had two zoom room users with similar issue) but using dmx-open.  I have raspberry pi 3b+ and 3b, I have tried both a falcon picap, and a generic usb rs485 device.  I have both a 30 port rgb controller (https://www.aliexpress.com/item/4000768368535.html) as well as a 12 channel rgb controller (https://www.amazon.com/gp/product/B07BVLXWD9/ref=ppx_yo_dt_b_asin_image_o05_s00?ie=UTF8&psc=1).  I can use a non-fpp device and configure for 12 channel, or 30 channel, or however many channels I need and everything works.  If I use fpp (I have tried with 5.3.1 and 5.4.1, I have to configure for 37 channels for it to output and work.  If I configure it for 36 (or less) it wont work.  I can repeat this at anytime if anyone wants logs or other details.

**Comment by cpinkham** [comment]
> ... using dmx-open ...  I can use a non-fpp device and configure for 12 channel, or 30 channel, or however many channels I need and everything works.

I do not have a DMX Pro dongle to test with, but for your DMX-Open issue I am wondering if your non-FPP devices are always sending full 510 or 512 channel packets while FPP is sending a smaller packet and the controller isn't accepting it.  I tested FPP with a PiCap configured as DMX-Open set to 3 channels only and connected this to a 3-channel dumb RGB controller and the controller lights up the RGB lights correctly when I turn on channel test mode in FPP.

**Comment by bloojoop** [comment]
Hey Chris, thanks for the response.  I think this is dmx controller/fixture
specific.  I now am in possession of a different controller and don't have
any issues defining the small channel count.  The other controllers I was
messing with (27channel dumb rgb), need like 37 channels sent from fpp ....
odd number I know. I am now reasonably confident that, in my case, this is
not FPP specific but dmx controller specific. It was interesting that with
a non-fpp device, it worked but like you mention, it may have been sending
a full universe of data. I honestly consider my issue closed.

**Comment by patdelaney** [comment]
WE can't do it in FPP.

**Comment by patdelaney** [comment]
WE can't do it in FPP.
