### ISSUE TITLE
Allow wled effects brought in either through plug in or native 

### ISSUE THREAD

**Issue by TechTurtleTube** [FalconChristmas/fpp#935]
**Is your feature request related to a problem? Please describe.**
NO
_____________________________________________________________________________________________________________
**Describe the solution you'd like**

I know alot of ppl coming from the smart home community buying kulp boards to control over home assistant 
and dont wanna create effects in xlights and the push to controller 

i would like to have the overylays for each port 200 pixels each till user uploads and changes it 
I would like a way to trigger wled effects over the pixel overlays in fpp .. read the pixel count and render the effect on the strings 
i have looked into doing this myself but idk enough about code and dont know where to start 
i know alot of ppl that would love to see this added

i think the perfect spot in the fpp settings would be in the effects  menu and also be able to be called during playlist 

they are using his boards bec they can be used wifi and in a small box and has a external antenna compared to the esp they have been using 
these ppl are wanting leds up year round not just show season including me where the k4 or k8 fit perfect for this use case i included a link to the github so some one that knows what they are doing can help 

https://github.com/Aircoookie/WLED
__________________________________________________________________________________________________________________ 
**Describe alternatives you've considered**

wled effects is what im really wanting natively but if you need to do it through plugin thats cool two 
but even the fast led lib would be cool to add there 
 
_____________________________________________________________________________________________________________________
**Additional context**

@cpinkham idk if you could help here with your  @HA knowledge

**Comment by SmAsH-jl** [comment]
Agreed this is something that is needed and will sell more boards. some kind of generic effects (wLED/FastLED libraryts ) 
out of the box across string ports. PI or BBB or any cape for that matter. With the ports defaulting to single strand model with 100-200 pixels. Please please please this would help so much for all kinds of applications.. plug and play for people that just want a better controller than and ESP based device. Thanks FPP team!

**Comment by bhheath** [comment]
I so agree this would be a great feature.

**Comment by dkulp** [comment]
There are really two parts to this request:
1) Allow (possibly optionally) the ability to automatically create overlay models from various things that are configured as output.   This would include things like VirtualMatrices, Panel matrices, string ports, etc....

2) Expand the list of effects that can be applied to the overlay models.  We currently only have color fades and bars.  The intention was to add a bunch more, just haven't gotten to it.

**Comment by foamflyer** [comment]
I too feel that these would be great features. I find that the effects WLED has are in some ways better than what xLights has to offer

**Comment by Snipercaine** [comment]
I have no idea how to make it happen, but I would love the ease of selecting effects and colors that WLED has paired with the speed and dependability of the Kulp/FPP controllers.

**Comment by libby2cm** [comment]
FPP and wled have different purposes.. seems odd to try and combine them.  Being able to have independently channeled overlays would be interesting though, somehow incorporating an alpha layer in the channel data..

**Comment by TechTurtleTube** [comment]
> FPP and wled have different purposes.. seems odd to try and combine them. Being able to have independently channeled overlays would be interesting though, somehow incorporating an alpha layer in the channel data..

yes correct but i along with a good amount of ppl use fpp for outdoor flood, house lights, during off season with fpp and home assistant it would be nice to throw random effects up rather , then having to preplan it create and upload  you can turn them off and on and change color and thats amazing .. we would also like to see some kind of effects added .

i no nothing about coding and been trying for 4 months to try but cant wrap my head around it so i figured it was time to reach out to the community .. i understand if its way to much work and doent happen .. just planting the seed

**Comment by bcarriveau** [comment]
man i would love to see Aircookie's effects in here, even if it was a plug in!!! :-)

**Comment by mjasithrive** [comment]
I would love to see this also!

**Comment by bryan34w** [comment]
Yes!

**Comment by andiburt1978** [comment]
> > FPP and wled have different purposes.. seems odd to try and combine them. Being able to have independently channeled overlays would be interesting though, somehow incorporating an alpha layer in the channel data..
> 
> yes correct but i along with a good amount of ppl use fpp for outdoor flood, house lights, during off season with fpp and home assistant it would be nice to throw random effects up rather , then having to preplan it create and upload you can turn them off and on and change color and thats amazing .. we would also like to see some kind of effects added .
> 
> i no nothing about coding and been trying for 4 months to try but cant wrap my head around it so i figured it was time to reach out to the community .. i understand if its way to much work and doent happen .. just planting the seed

I have this now.
Out of holiday season I run various animations on the lights and can control via home assistant (start, stop, next,prev and effect/playlist)

If you can set up FPP and a Falcon or similar pixel controller you can do the same.
I

**Comment by TechTurtleTube** [comment]
Yea i can do the same via script but thats still with creating the effect and playlist 

Esppixelstick stick and wled  u can tun effects with or without xlights

Those simple times when family goes can u make them do this ... or family get together 

Not hang on let me go create that in xlights really quick and make a button in ha

**Comment by TechTurtleTube** [comment]
Opps phone mishap didnt mean to close and open

**Comment by SmAsH-jl** [comment]
> > > FPP and wled have different purposes.. seems odd to try and combine them. Being able to have independently channeled overlays would be interesting though, somehow incorporating an alpha layer in the channel data..
> > 
> > 
> > yes correct but i along with a good amount of ppl use fpp for outdoor flood, house lights, during off season with fpp and home assistant it would be nice to throw random effects up rather , then having to preplan it create and upload you can turn them off and on and change color and thats amazing .. we would also like to see some kind of effects added .
> > i no nothing about coding and been trying for 4 months to try but cant wrap my head around it so i figured it was time to reach out to the community .. i understand if its way to much work and doent happen .. just planting the seed
> 
> I have this now.
> Out of holiday season I run various animations on the lights and can control via home assistant (start, stop, next,prev and effect/playlist)
> 
> If you can set up FPP and a Falcon or similar pixel controller you can do the same.
> I

The Goal here is to have a set of preset effects baked into FPP.. allowing out of the box, or quick dynamic effects on your ports, (model agnostic, treat each port as a 200 count single strand model for this purpose until we tell the controllers otherwise. ) 

This would allow plug and play for people just wanting fancy roof line effects without needing to touch xlights..., if they do want to dig deeper after that, xlights or other sequencing software would be waiting.

In the end, I believe this will benefit the community in getting people into some beefier/more robust hardware than wLED devices typically offer and get them on the right path to pixels. (aka would sell more boards from all vendors as FPP out of the box could do fun, fancy, themed effects. )

The barrier for entry would be vastly shrunk if not removed entirely.

Big Picture. 

Eventually, I would love to see something evolve into a nice easy section where you can see all the populated models currently part of the configuration ( whether that's a full on xlights layout, or just a simple 200 count per port by default is no matter. )

then be able to select each one individually or group models together (a simple check box beside each model)

for groups, don't generate a matrix of the models still treat each model as single strands for these built in effects for ease of implementation,

Finally a drop down to select a running effect. maybe a "built in effects" on/off toggle. per model/port and/or all running "built in" effects with a multisync packet to also tell remotes about an all off. ( separate but not superseded by the real all lights off or current effects commands. ) This would give us controll with fpp commands, scripts, playlists, schedule, mqtt etc etc et.. 

Consider this should  all be separate from current effects/background effects engine/framework where we define our tune too signs and things.  this should really be defined/re-defined as overlay effects...

**Comment by 808Myk** [comment]
I see great benefits for this to happen

**Comment by Roboman2582** [comment]
I agree. I would love the preset effects. I think this is a must! I have an older Holiday Coro controller and it has some cool preset in the test mode as well. Great idea guys

**Comment by rixound** [comment]
This would be a great hybrid solution for the project I'm working on with permanently installed whole room lighting all based on addressable pixel strips with 6,000+ pixels. The limitation currently is that you can send E1.31 data from xLights / FPP to a device running WLED  firmware so you have the ability to run built in effects to a strip or even sound reactive mode AND programmed sequences.  This dynamite combination does not yet exist for the great hardware in the Christmas LED space. One of the best boards in this area is the Dig-quad. These are only limited by the fact that it is wifi only (based on esp32) which would be a stretch if you were trying to sync several WLED boards. With a large number of pixels the "Christmas" boards would provide for a larger installation on a dedicated differential long range network for example. I would emphatically agree that this would be cool and something worth supporting.

**Comment by CaffeinatedFunctionality** [comment]
Oh no! Why is this closed? This would be incredible! I hope there is a solution or plugin for this eventually

**Comment by TechTurtleTube** [comment]
> Oh no! Why is this closed? This would be incredible! I hope there is a solution or plugin for this eventually

this has been added to the master branch already as fpp commands . you will need to flip over to master branch , and use the new fpp command button to trigger the a effect .. they are listed as wled_(effect name)

**Comment by CaffeinatedFunctionality** [comment]
Thank you!

**Comment by rsrubberducky** [comment]
"you will need to flip over to master branch" where would i see that?

**Comment by ghormann** [comment]
Watch around minute 27 of this video. https://youtu.be/8Cmy6-haWlo

**Comment by rsrubberducky** [comment]
Oh ok thank you very much

**Comment by CaffeinatedFunctionality** [comment]
I upgraded to master but I don't see any of the wled commands under the fpp command button

⁣Get BlueMail for Android ​

**Comment by SmAsH-jl** [comment]
Stop by our discord we can help you live.. It's a bit of a process at the
moment.

https://discord.gg/bMpr82GX

**Comment by MagicMountainMan** [comment]
I am also interested in how to trigger the effects but don't see wled commands.

**Comment by TechTurtleTube** [comment]
You have to move over to master branch
Then you can use it as effect

**Comment by MagicMountainMan** [comment]
According to the Developer Settings, I'm on the master branch already. ![Screenshot_20210618-114946.png](https://user-images.githubusercontent.com/52861182/122604818-6a44d880-d02b-11eb-8025-65fbf4fbbe70.png)

**Comment by dkulp** [comment]
Have you created a PixelOverlayModel with the layout and channel range that you need?   The WLED effects operate on the PixelOverlayModels so if one isn't available, they won't appear.

**Comment by MagicMountainMan** [comment]
Yes I already had pixel overlay models created. I'm just an idiot though and didn't realize the command was `overlay model effect` and not just `effect start`. So now I do see all of the WLED effects. Sorry for though trouble.

**Comment by SmAsH-jl** [comment]
I still think we need a better way to manage and setup wled effects. Some
sort of live Gui we can use to control effects on the fly would be nice.

**Comment by TechTurtleTube** [comment]
We do need a gui I agree but I don't have the knowledge to do so and dan helped tons in getting the effects to work 

On master branch they are there and I will post screen shoots later on how to control them 

But @dkulp I would also like to see them in the preset options idk what that space is really planned for but that seems like a good spot for a gui for the command .. but once again this is if u or another dev have time ..

**Comment by TechTurtleTube** [comment]
![Screenshot_20210619-134300_Chrome.jpg](https://user-images.githubusercontent.com/54298835/122651093-9c763900-d104-11eb-9a14-6d43799832c9.jpg)

**Comment by TechTurtleTube** [comment]
![Screenshot_20210619-134306_Chrome.jpg](https://user-images.githubusercontent.com/54298835/122651108-ac8e1880-d104-11eb-8e08-acb2c7031cf2.jpg)
