### ISSUE TITLE
Convert Bridge mode from being a separate FPP Mode to an on/off checkbox

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#936]
The goal here is to optionally allow FPP to receive bridge mode data while running in normal standalone/master player mode.  Rather than switching modes, bridge mode would be enabled via a checkbox.  Incoming bridged data would be merged with data for any playing sequence, the same as we can currently merge in test mode, etc. data with bridge mode data.

**Comment by ihbar** [comment]
Hello
For me switching the mode is quite convenient : I have one sequence in the playlist, running 24/24. When I need to edit it, I switch to bridge mode, and I am not disturbed by the default sequence. After updating the sequence, I switch back on player.
It would be nice to have both options : change mode or merge bridge data in player. Thanks

**Comment by ghormann** [comment]
I'm thinking a drop down. 
1. Ignore bridge data
2. Merge bridge data
3. Only bridge data.

Merging would be like an overlay.

**Comment by cpinkham** [comment]
With the new feature you wouldn’t need to switch at all.  If playing a sequence, the sequence would play on the lights.  If sending e1.31 from xLights then that data would be bridged to the lights.  If playing a sequence and sending E1.31, the E1.31 data would take precedence for the channels in the E1.31 data.  You will be able to disable bridge functionality if desired or disable individual lines in the network channel input screen.

Chris

**Comment by cpinkham** [comment]
There shouldn’t be a need for Only Bridge, if you want only bridge then don’t play a local sequence.  If you want only local then disable bridge input with the checkbox or disable the individual inputs.

Chris

**Comment by ihbar** [comment]
If the E131.1 takes precedence on the local sequence, it is even better for me. Thanks for your clarification Chris :-)
Stephane

**Comment by darylc** [comment]
@ghormann We can close this one now that bridge mode is gone.

**Comment by ghormann** [comment]
Thanks Dan for the good work on this one.

**Comment by patdelaney** [comment]
So to be clear, is there a check box or is this just the default behavior?  If e1.31 comes in it takes precedence?
