### ISSUE TITLE
FPP not sending MQTT playlist message when Remote Falcon plugin control ends

### ISSUE THREAD

**Issue by robbiet76** [FalconChristmas/fpp#939]
When a song is picked by a viewer using the Remote Falcon plugin, FPP sends an MQTT message indicating that the playlist has changed via topic "falcon/player/FPP/playlist/name/status".  However, when voting ends and the playlist returns to the regularly scheduled show, a new message is not being sent to indicate that the playlist has changed back.

**Comment by ghormann** [comment]
7d5cb653e45222c524cc1e67816421e6f79728c1 should fix this.
