### ISSUE TITLE
Convert scheduler to use time_t instead of weeklySeconds

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#941]
This partial rewrite is already underway.  The Scheduler is being converted to use time_t for scheduling instead of weeklySeconds which has required lots of workarounds in the code.

Along with this mode, a couple other changes are being worked on:
- addition of a Player class to sit between the Scheduler and Playlist.  The eventual goal is to allow multiple concurrent playlists to be running, so right now this class is mainly a pass-through middleman, but it does have some smarts built into it already.  The new Player is the one responsible for stopping scheduled playlists instead of the scheduler.  Some things which interact with the scheduler will not interact with the Player instead.  This brings us one step closer to being able to totally disable the scheduler by not instantiating a Scheduler instance and allowing scheduling to be done via a plugin or outside entity.
- The scheduler is being updated to be a runner of FPP Commands in addition to starting playlists.  This will allow the user to run  scheduled FPP Commands while a playlist is running.  Instead of having to have a Time Branch item in a playlist to change the brightness or lower the volume, the user will be able to put these FPP Commands right into the schedule and they will execute at exactly the desired time instead of when the playlist gets to a certain item.

**Comment by cpinkham** [comment]
This is under development but I missed a few commit messages.

References:
30368cfef2cf4aeaf3d0ab0e33a0922755f11596
dea064a7f921add52aad96c4c8efbf2604497911
39ed1eec55762ea73c3d16a3d1a60605fdec871e
284d7c8bdd03dd6a9001fdedb852de48b44bde61
1fae361cbb40a0d52a749941b942d6d500396b4a

**Comment by ghormann** [comment]
@cpinkham  Can this be closed?  I think this is feature complete.

**Comment by cpinkham** [comment]
Closing this ticket.
