### ISSUE TITLE
Convert remaining fppxml.php commands to REST API endpoints

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#944]
To facilitate creation of a new UI and standardize things, we need to convert the remaining commands in fppxml.php to REST API endpoints and update the existing UI to use the new endpoints.  Some commands may not be in use anymore and may be removed if they are no longer used by the existing UI.

When looking at this, we should look to see if existing API endpoints can be used to replace other fppjson.php calls, for instance some configs can be loaded and saved using the /api/configfile/:FileName rather than separate endpoints.

**Comment by dkulp** [comment]
This will require some coordination with xLights before final removal as fppxml is used to restart fppd as well as move the fseq files after the upload.

**Comment by ghormann** [comment]
I'll take this. I'll start a page on the wiki documenting the current endpoints leaking them to the Target endpoints and also noting which ones I believe are used externally or for multi-sync purposes and need to be preserved for a while.

**Comment by ghormann** [comment]
Changes documented at https://github.com/FalconChristmas/fpp/wiki/FPP-5.0-API-Migration

**Comment by ghormann** [comment]
All methods, except those needed by xLights or Multisync have been moved.

**Comment by ghormann** [comment]
All but those needed for multisync or fpp upload have been moved.   Closing.
