### ISSUE TITLE
Convert remaining fppjson.php commands to REST API endpoints

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#945]
To facilitate creation of a new UI and standardize things, we need to convert the remaining commands in fppjson.php to REST API endpoints and update the existing UI to use the new endpoints.  Some commands may not be in use anymore and may be removed if they are no longer used by the existing UI.

When looking at this, we should look to see if existing API endpoints can be used to replace other fppjson.php calls, for instance some configs can be loaded and saved using the /api/configfile/:FileName rather than separate endpoints.

**Comment by dkulp** [comment]
This will require some coordination with both xLights and the ESPixelStick code.   xLights uses the fppjson stuff extensively as part of the discovery process as well as various parts of FPP Connect.   The ESPixelStick v4 firmware mimics FPP by implementing several of the fppjson functions.

**Comment by ghormann** [comment]
Changes documented at https://github.com/FalconChristmas/fpp/wiki/FPP-5.0-API-Migration

**Comment by dkulp** [comment]
This is now done.  fppjson is gone in FPP7
