### ISSUE TITLE
Remote Host: pick list in File Copy Backup/Restore tab should not list NON FPP devices

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#946]
# Please answer the following:
**Version:** v4.x-master-774-g4dbfbe25 (master branch) on Pi 3

**Describe the bug and Steps to reproduce**: 
Go to Status/Control -> FPP Backup
Click on File Copy Backup Tab
Copy Type: Backup to Remote FPP Backups Directory
Click the Dropdown list for remote hosts
The list contains non FPP devices discovered as well. In the example there are ESP Pixel Sticks and Falcon Controllers.
They should be filtered out of the list

**Expected behavior**: 
We should just see FPP devices ONLY

**Additional Attachments**
![image](https://user-images.githubusercontent.com/8147459/103570257-644ca800-4e8e-11eb-80c4-cbba8e74d728.png)

**Comment by ghormann** [comment]
Similar problem also exists on about.php for **FPP Upgrade Source** field.

**Comment by patdelaney** [comment]
tested correct, pick list is filtered
