### ISSUE TITLE
external trigger

### ISSUE THREAD

**Issue by hmrickhoff** [FalconChristmas/fpp#948]
in advanced... i have never used falcon player before. i have sth. in my mind what i want to realize.

is it somehow possible to make an external trigger to start a show? Via webhook or sth?
i want my z wave motiondetector connected to openHAB3 trigger a special sequence once.
any ideas how this can be achieved?

**Comment by ghormann** [comment]
You have multiple options.  
1) The rest API: /api/playlist/:PlaylistName/start is a good method
2) MQTT is another option.   https://github.com/FalconChristmas/fpp/blob/master/docs/MQTT.txt  Something like playlist/${PLAYLISTNAME}/start

In general, it is better to ask these kind of questions on the forum or facebook. Many more people to help there.
