### ISSUE TITLE
FPP v5.0 ChangeLog

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#950]
FPP v5.0 ChangeLog

# Enhancements
* User Interface
  * HTML and CSS facelift of FPP User Interface to make it more modern and mobile friendly.
* Scheduler
  * Rewritten Scheduler to optimize how the internal list of scheduled items is stored.
  * Added ability to schedule FPP Commands and have them run while a playlist is already running.
  * Added ability to schedule .fseq Sequence files
  * Allow setting Schedule start/end times to Dusk/Dawn in addition to Sunrise/Sunset.
  * New 'View Schedule' interface to view a timeline of the currently loaded schedule.
  * New 'Clone' button to the Scheduler UI to make copying schedule entries easier.
* Player and Playlists
  * Add 'Notes' field to all playlist entries to allow the user to add documentation to an item if needed.
  * Add a new PlaylistEntryBranch condition to check the cached payload of a received MQTT topic.
  * Allow Next/Prev commands to work inside the LeadIn and LeadOut sections of a playlist.
* FPP Commands
  * Add new Command Presets to replace Events.  Command Presets may be user named or may use internal preset names which are automatically triggered when certain actions occur with FPP.
  * Add ability to run a FPP Command from any page in the UI.
  * Add wildcard ability to Effect Stop FPP Command and ability to pass in multiple effect names in CSV list.
  * Allow selecting multiple models when running Overlay Model FPP Commands
* Channel Outputs
  * New Philips KiNet Channel Output
* General
  * Added Initial Setup page to allow users to quickly configure a set of most often used settings.
  * Added optional statistics reporting to allow FPP Developers to get better visibility into how FPP is being used.
  * Enhanced logging support to allow setting different log levels for different log facilities.
  * Added System boot date/time and fppd uptime to About page.
  * Add .asoundrc for dmix software mixing to allow other external audio to be playing while fppd is also playing.
  * Display a warning if audio is being output to the dummy audio device.
  * Send FPPD Warnings out via MQTT
  * When building fppd, only download CCache if file has changed.
  * Add new +3/-3 buttons to adjust channel test mode end channel up/down by 3 for testing pixels one at a time.

# Other Changes
* Move MultiSync UI Auto Refresh button to top of page to match other auto refreshing tables in UI.
* Disabled MQTT retain flag by default and add retain option to MQTT FPP Command to allow re-enabling.
* Removed support for upgrading from old CSV schedule format used in FPP v2.x and prior.
* Removed unused PlaylistEntryChannelTest code (was never in the UI)
* Keep fppd running while updating versions and do a quick restart once new version is ready.
* Remove unused Line number in schedule editor UI
* Update Channel Output help page to point to library developer documentation on pinouts used by RGBMatrix LED panel output on the Pi.
* Events MultiSync packets, mqtt topics, and API calls have been removed as Events code has been removed in favor of Command Presets.

# Bug Fixes
* Fix off-by-1 issue with Start Channel on Effects page.
* Sort the effects list returned by the /api/effects REST API call.  This fixes several UI sorting issues.
* Removed unused legacy socket command packet count from Remote status UI.
* Updated timing on Remotes to give them longer before blanking on their own.
* Fix scheduler date range issue where the next playlist listed could be incorrect in some circumstances.
* Only show FPP systems as backup destinations
* PlaylistEntryURL fixes, add a 2-second connect timeout and prevent blocking if URL call times out.
* Re-publish Playlist name upon playlist resume after completing an inserted playlist.
* Fixed crash in PlaylistEntryBranch.
* Fix MQTT topic to set playlist sectionPosition (was selectionPosition)
* Fixed label on LOR Enhanced unit start channel
* Multiple JavaScript errors fixed
* Fixed use of Next/Prev buttons when playlist is not set to repeat
* Fix Multicast/MultiSync FPP Commands when using IPs instead of hostnames
* Fix incorrect 'Not Found' error in playlist UI when sequence metadata can't be queried
* Fix seed used when randomizing playlists and starting at a random position in a playlist.
* Fixed name of sectionPosition MQTT topic
* Fixed MAX7219 LED matrix channel output and added support for 3 channels per pixel.

**Comment by darylc** [comment]
5.0 was released a while back.
