### ISSUE TITLE
Add support for Channel Output Plugins

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#951]
Update Plugin C++ API to add a OutputChannelData(unsigned char *seqData) method and update Channel Outputs UI to allow plugins to add their own tabs to configure their output or inject themselves into the existing 'other' tab.

If we can get this working, we can add back the Triks-C output as a plugin.   https://falconchristmas.com/forum/index.php/topic,13997.0

**Comment by w-corbello** [comment]
Any forward progress with this? Thank you.

**Comment by cpinkham** [comment]
I have the fppd part of the plugin working, now I need to add a way for a plugin to hook into the Channel Output config UI.  The preference is for a Channel Output Plugin to have its output configured there rather than on a separate plugin config page.

**Comment by adamcoulombe** [comment]
I am wondering if we could add dropdown to output rows where a plugin(s) is available, then open a modal to configure settings for that plugin. Would something like that work?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/469038/148565195-718af065-37b9-4257-95e3-e8abf9177922.gif)

**Comment by cpinkham** [comment]
This ability was added by Dan in eb5450b805.  It may need work for an actual FPP Plugin to provide a channel output, but the core is there now.  Closing this until the need arises.
