### ISSUE TITLE
No Network with FPP-v4.6-BBB image on a BBG

### ISSUE THREAD

**Issue by JerryPlak** [FalconChristmas/fpp#954]
got no No Network with FPP-v4.6-BBB image on a BBG  I end up going back to FPP-v4.5-BBB image then updated to Version: v4.6-13-g839c605a.

**Comment by ghormann** [comment]
I'm gong to close this issue old issue.  This has not been a wildly reported problem on 4.6.  

Current focus is on 5.0.
