### ISSUE TITLE
MQTT Event Trigger Not working on Master

### ISSUE THREAD

**Issue by jazakzewski** [FalconChristmas/fpp#956]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

 v4.x-master-849-g95ccb370 (master branch)  running on BBB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

Publishing MQTT topic to trigger an event fails to load event. Have tried different payload formats with no success.

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

Event should be triggered

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20210128.2003.zip](https://github.com/FalconChristmas/fpp/files/5889736/FPP_Logs_20210128.2003.zip)

![image](https://user-images.githubusercontent.com/58450237/106192449-32bbb980-617a-11eb-8d94-5848eafb495b.png)

**Comment by cpinkham** [comment]
Use 01_02, the numbers have to be padded to 2 digits.

**Comment by jazakzewski** [comment]
Thanks Chris!
