### ISSUE TITLE
FPP behind FPP Proxy: AJAX using Absolute URLs

### ISSUE THREAD

**Issue by jnovack** [FalconChristmas/fpp#958]
**FPP Version and Hardware**: v4.6.1 (doesn't matter)

**Describe the bug and Steps to reproduce**: 
Accessing FPP behind an FPP-Proxy has Ajax issues.  This usually occurs with Kulps or other FPPs behind an FPP Proxy since they use FPP as well. 

It seems that some ajax requests are absolute urls to `/` and others are relative.

If they are relative, they work; however, absolute ajax requests show me the information from the Proxy, NOT the proxied server.

Most notably, the query to get the ip address at the top is incorrect. 

You can see in the screenshot below, I'm on the downstream Kulp, but it has queried `/fppjson.php` which gets the proxy's `fppjson.php`, and thus returns the proxy's IP information.  Note the IP address.

![image](https://user-images.githubusercontent.com/387006/106637401-a3831d00-6550-11eb-9dc8-1c6da270ed48.png)

**Expected behavior**: 
Relative URLs all around to support the method that FPP proxies connections to downstream devices.

**Additional context**: 
Hopefully this gets seen before the NewUI is complete!

This is the correct header for the Kulp device.  Note the IP address information.
![image](https://user-images.githubusercontent.com/387006/106638104-7edb7500-6551-11eb-9a0e-b98669b6b558.png)

**Comment by ghormann** [comment]
I'm in the process of replacing all calls to fppjson.php for 5.0 with new REST endpoints.  I will correct this when updating that endpoint.  If you notice others please list them in the ticket.

**Comment by jnovack** [comment]
Unfortunately, I did not find this myself, so I cannot continue testing. While in the zoom room, I recognized the incongruity and knew immediately it was a relative vs absolute issue (a lesser developer would lie right here and say they've never done this. ;)).

I suppose you could bring up a nginx container with a config to proxy to fpp while testing under a directory under root, and then just tail all your 404s.

**Comment by jnovack** [comment]
While we're on the topic, a tangent to be aware of is double proxying.  
![image](https://user-images.githubusercontent.com/387006/106735045-bbef4800-65e1-11eb-9d59-534266ac86f5.png)

We've seen a more than one or two designs from the Zoom Room that have this layout, where the Show Network is proxied through an FPP (`FPP-Master`), and an FPP (`FPP-Remote`) is wireless to the Show Network because of distance.  In this case, 172.16.0.202 is double proxied from the Xlights.

**Comment by patdelaney** [comment]
@jnovack Can you validate (test) and move to done if this solves yur request?
