### ISSUE TITLE
Volume Issues

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#96]
Currently the volume control only works on "PCM" which isn't necessarily the name of the audio device when we custom-configure something using the /root/.asoundrc file.  With the VastFMT as the audio source, the audio isn't changeable via the UI currently.

**Comment by ihbar** [comment]
Hello
This seems to be a very old ticket, and from the last comment of 2014, it is not a bug anymore. I think we should close it. (Just to clean the list)
Any opinion ?
Stephane
