### ISSUE TITLE
Move code that displays lists of wifi SIDS to REST API

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#960]
Today it is possible to easily mistype a SID when configuring wifi.   We should allow for the user to scan available SIDs and select from the list.  (This should not replace the ability to type one in.)

**Comment by dkulp** [comment]
It already does this.

**Comment by dkulp** [comment]
<img width="616" alt="Screen Shot 2021-02-03 at 7 13 16 PM" src="https://user-images.githubusercontent.com/91569/106825949-e1b53500-6653-11eb-8bf1-4ac3a47b920b.png">

**Comment by ghormann** [comment]
Oh, that is funny....  It wasn't doing it on my box until I disabled Lastpass.    I'll change this to refactor the code and move it out of networkconfig.php to an endpoint

**Comment by ghormann** [comment]
Fixed in newui branch.

**Comment by patdelaney** [comment]
yes it is there and works
