### ISSUE TITLE
Remote Status Page not intuitive

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp#961]
**Is your feature request related to a problem? Please describe.**

When you are running in Master/Remote and the remote does not have the .fseq file for a sequence that the Master is playing, there is no indication or error and the status on the Remote states, "Waiting for MultiSync commands" If you are looking at this, it would indicate that there was a communication problem between the Master and Remote when the problem is actually a missing file.

**Describe the solution you'd like**

What about something more informative like:
For the Remote Status message show the "Syncing to Master"  message (Maybe in Red?) 

On the Sequence Filename show the file that is supposed to be playing along with an indicator that the file is missing. Something like  "(Missing) Baby Shark.fseq" again in red?

**Describe alternatives you've considered**

**Additional context**

**Comment by darylc** [comment]
@Poporacer how about something like "Waiting for Player to initiate sequence"

**Comment by Poporacer** [comment]
That doesn't really describe the problem, the player **has** initiated the sequence, the problem is that the Remote doesn't have the sequence stored. To a user, it looks like it is a communication issue because the Remote will show "Waiting for MultiSync commands" I think the error could be a little better defined?

**Comment by darylc** [comment]
Got it, sorry misread the issue.

**Comment by cpinkham** [comment]
We might be able to leverage the WarningHolder somehow to add a warning to the UI that the master tried to play something but the remote doesn't have the file.  We would want to be able to dismiss it though, because some users don't have all files everywhere and they don't want to be warned about it.

**Comment by darylc** [comment]
Added Warnings, player times out after 30 seconds as you're likely seeing those as you press play,  remote times out after 10 minutes (as you're less likely to see those).  We can tune these times and add options to disable these if they get too annoying for people who deliberately have missing fseq files. Right now its more important to have the warning for those who are genuinely missing them.
