### ISSUE TITLE
Add Statistics API for about.php or a different page.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#965]
Add an API that returns basic usage monitoring information that could be lavage on the client side to compute some basic statistics.   This would include.
* CPU Usage
* System Load (1/5/15)
* Memory Usage
* Network Consumption
* Disk I/O
* Disk utilization

**Comment by jnovack** [comment]
Unless this page is designed to be static, I think websockets to funnel statistics for something like this is better than an API call every X seconds.

You don't want to be in a scaling situation where you opened 2x browser windows and now have double the load.

**Comment by patdelaney** [comment]
no fix
