### ISSUE TITLE
Add "Health Check" page

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#970]
We should have a health check page that runs automatic diagnostics of some of the most common problems to reduce the amount of human traffic spent looking at issues.    This would be much more simpler than the current troubleshooting page as it would  preform checks and provide some basic recommendations when issues are discovered.   Example checks to include would be.

1) Is the internet reachable.  (ping 8.8.8.8) (DONE)
2) Is DNS working (lookup github.com) (DONE)
3) Is FPPD running (DONE)
4) Is the File System full (DONE)
5) Is the clock set to a reasonable time (What is reasonable given FPP is used world-wide?)
6) Is the network over utilized
7) Is the scheduler disabled (master/standalone) (DONE)
8) Is

**Comment by jnovack** [comment]
I completed the "clock set to a reasonable time".  I set it for 100 milliseconds.  I imagine this should be changed to "more reasonable". 

https://github.com/FalconChristmas/fpp/blob/a85ae2aaf9be3c704ee732ff841f6a84a84b4dea/scripts/healthCheck#L180

If the device is on the internet, and time is set manually, it should throw a flag (unless you are REAAAAALLLY good at clicking the time).

**Comment by jnovack** [comment]
```
fpp@FPP-DEV:~ $ time ping -c 1 -q github.com | grep "Name or service not known"

real	0m4.462s
user	0m0.026s
sys	0m0.010s
```

This takes an unnecessarily long time.  Why is dig or nslookup not on the image? :/

**Comment by jnovack** [comment]
> 6. Is the network over utilized

How necessary is this?  It's really only valid when it's playing a show unless we're tracking metrics over time.  How often is this metric useful when running healthcheck?

**Comment by cpinkham** [comment]
root@rpi6:~# time ping -c 1 -q github.com | grep "Name or service not
known"
real	0m0.047suser	0m0.029ssys	0m0.018s
Must be something on your end.  This is on a Pi 2.  dig and nslookup
aren't included in the default OS install and we haven't installed them
because we don't normally need them.

**Comment by ghormann** [comment]
healthCheck.php has been implemented.    Closing.

**Comment by patdelaney** [comment]
Tested and confirmed
