### ISSUE TITLE
Add Ability to delete multiple Pixel Overlay Models

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#972]
**Is your feature request related to a problem? Please describe.**
For those with a lot of props it would be great to be able to multi-select and delete the models.

**Describe the solution you'd like**
Could check boxes be added in order to select props to be deleted.
Also add buttons to select or clear all of the check boxes.

**Comment by ghormann** [comment]
Implemented in 5.0 :  Demo of how to do it 
https://www.youtube.com/watch?v=8ZBmxpTeCVU
