### ISSUE TITLE
UI Overlaps in odd way with new UI - Schedule button on main page

### ISSUE THREAD

**Issue by bigwavedave42** [FalconChristmas/fpp#977]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP v5.x-master-1-g24e59c2c (master branch) on Docker
Chrome: Version 88.0.4324.190 (Official Build) (64-bit)
Windows 10

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Main Status Page
2. Shrink Page
3. Really wide browser window works fine, and also when much narrower.  There is a middle ground where it does and odd overlap.

**Expected behavior**: 
Button wouldn't overlap the text.

**Additional context**: 
No schedule is defined, at all.  This is likely rare... at least in production.

**Additional Attachments**

When not in an OK state:
![image](https://user-images.githubusercontent.com/11801385/109243348-9e9d3c00-7791-11eb-825a-eebc5a7765e3.png)

Wider is OK:
![image](https://user-images.githubusercontent.com/11801385/109243269-7e6d7d00-7791-11eb-8720-162e84dba289.png)

Narrow is OK:
![image](https://user-images.githubusercontent.com/11801385/109243392-b1b00c00-7791-11eb-88ef-a8c6bf257aed.png)

**Comment by adamcoulombe** [comment]
Should be fixed by https://github.com/FalconChristmas/fpp/commit/c17ecbf097cfc557af258171daba08e3519b6d16

Also. This issue was already being tracked in https://github.com/FalconChristmas/fpp/issues/962
