### ISSUE TITLE
FPP v5.0 - Multisync not restarting FPPD when changing Standalone/Master/Remote/Bridge

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#978]
# Please answer the following:
Software on all - 5.x-master-41-g8aa20959
Multisync running from Raspberry Pi 3b+

Remotes are BBB and Raspberry Pi2 boards

**Describe the bug and Steps to reproduce**: 
Go to Status/Control - Multisync
Select any remote device to be changed.
Next in the "Action for selected systems" dropdown select Set to; Standalone, Master, Remote or Bridge
Click run. 

**Expected behavior**: 
All devices will set to selected Standalone, Master, Remote, or Bridge.
All devices will restart FPPD

When checking any remote none of the devices have actually restarted FPPD.
Also when viewing the remotes they do not show that a restart is needed.

** Note **
When trying to restart FPPD through Multisync it functions as intended.

Added logs incase they will be of assistance
[FPP_Logs_20210301.0027.zip](https://github.com/FalconChristmas/fpp/files/6058484/FPP_Logs_20210301.0027.zip)

**Comment by ghormann** [comment]
After the changes to have only Player and Remote, this appears to be working fine.   I'm going to close this issue.   If you can still reproduce it on v5.x-master-374 or higher, reply back.
