### ISSUE TITLE
Password protection bypassed when using Dataplicity

### ISSUE THREAD

**Issue by gergmchairy** [FalconChristmas/fpp#980]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 4.6.1 on Pi 4

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
When using Dataplicity.com as a remote acess mechanism, password security doesnt work - there is no requirement to enter a username / password.

**Expected behavior**: 
I expected the username/password dialogue (which still works if i access the pi locally)

**Comment by ghormann** [comment]
We don't require passwords on the local host (127.0.0.1) interface to allow for local API calls. Wormhole seems to place an agent on your machine and redirect the traffic though 127.0.0.1.      

>> Wormhole forwards any webservice that is listening on the loopback interface (127.0.0.1) port 80 on your device. What this means is that to have a working web service on your Pi using wormhole, the wider world does not require direct access to port 80 on your Pi.
--  https://docs.dataplicity.com/docs/securing-wormhole-enabled-web-servers

On your pi, you can remove the "Require local" line from /home/fpp/media/config/.htaccess, but I *suspect this will break a few things*.     For sure it breaks stats collection in 5.0.  It looks like some of the code that does FPPD restart and multisync also depends on this rule.
