### ISSUE TITLE
Stable Docker Tag

### ISSUE THREAD

**Issue by grivers3** [FalconChristmas/fpp#982]
**Is your feature request related to a problem? Please describe.**
I am using Watchtower to automatically update my Docker container. It is updated nightly when the image tag is set to "Latest" or nothing. If I set the image tag  "4.6...", it will never be updated in the future. 

**Describe the solution you'd like**
Add a tag named "Stable" for official releases.

**Comment by jnovack** [comment]
My suggestion is to utilize [semver](https://semver.org) for our versioning.

This can be accomplished with a series of Docker Hub hooks, and automatic builds.

I currently have a reference repository which does this for a few of my multi-arch builds (such as my wildly popular [jnovack/autossh](https://hub.docker.com/r/jnovack/autossh) repository): https://github.com/jnovack/docker-multi-arch-hooks

The goal would be to tag releases and would update all semantic versioned related releases.

![image](https://user-images.githubusercontent.com/387006/110664336-4f91d680-8195-11eb-9d36-cbd8fc30ab6c.png)

-------

As the practice goes, pulling the tag `:1` of your container, should always pull the most up-to-date release in the v1 version, be it v1.3.1 or v1.99.99. If you wanted v1.0.0 specifically, best practices means you should grab `:1.0.0`. However, if a user always wants v1.2 and all patches of v1.2 (e.g. v1.2.4, v1.2.219), but never v1.3, the user MUST download `:1.2`. If someone always wants the latest version, they download :latest.

For best practices on Docker Hub, when you push a patch (x.x.PATCH) version of your container, you SHOULD be updating the major (MAJOR.x.x) and minor (x.MINOR.x) versions of your release to point to this new build. Additionally, when pushing a new minor release, you SHOULD be updating the major container version.

When you tag and push v1.2.3 of your repository, these scripts will create a new tag, `:1.2.3`, for your container. It will also automatically update `:1.2` and `:1` for you to this build. Keeping all releases up to date.

**Comment by darylc** [comment]
The FPP development team discussed this issue, and believes that stable tags are generally being tagged (although 6.1 was missed I'm told)
