### ISSUE TITLE
Docker image (master) failing to restart fppd : unrecognized option '--config-file'

### ISSUE THREAD

**Issue by bigwavedave42** [FalconChristmas/fpp#983]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Docker v5.x-master-122-ga42e6742 (master branch)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Update to capture Master
2. Rebuild
3. error seen:
Building FPP on 'Debian' platform
make: log4cpp-config: Command not found
nice: cannot set niceness: Permission denied
sudo: dmidecode: command not found
/opt/fpp/src/fppd: unrecognized option '--config-file'

Looking at recent changes, I see fppd.c had a change in 0d7a6e5 which seems to have removed "--config-file"

**Expected behavior**: 
I expect fppd would restart cleanly.

**Additional context**: 
Did a fresh pull of the docker container, expecting that something could have been messed up in the local copy, but seeing the same behavior

Then tested with an entirely fresh container and fresh config directory, to ensure it wasn't something from my normal testing config or plugins.

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
[FPP_Logs_20210319.2121.zip](https://github.com/FalconChristmas/fpp/files/6174098/FPP_Logs_20210319.2121.zip)

**Comment by ghormann** [comment]
I've reproduced it.   I'll try and fix it.

**Comment by bigwavedave42** [comment]
Looks like this file still explicitly calls --config-file:
scripts/fppd_start

**Comment by bigwavedave42** [comment]
Also noticing that "src/fppd.c" still lists it as a valid argument, although all the guts were seemingly removed.

**Comment by ghormann** [comment]
Pushed a fix.  Starts up fine now if i build the container on my dev box.   In 30 minutes or so the official image should be updated.
