### ISSUE TITLE
Settings that are children of another parent setting are not being hidden when the parent is disabled

### ISSUE THREAD

**Issue by rudybrian** [FalconChristmas/fpp#985]
**FPP Version and Hardware**: 
v5.x-master-131-g123cdf2e (master branch)

**Describe the bug and Steps to reproduce**: 
1. Go to Status/Control->FPP Settings
2. Click on the NTP tab
3. Deselect _Enable NTP_
4. The _NTP Server_ entry file is not hidden

**Expected behavior**: 
Per the settings configuration in _www/settings.json_, the _ntpServer_ setting is a child of the _ntp_ setting and should be hidden if the _ntp_ setting is not enabled (as it had done since 4.0)

**Additional context**: 
It would appear that some of the changes related to the new UI broke this on master.

**Comment by adamcoulombe** [comment]
As far as the NTP setting is concerned, it seems to be working fine on my end, although it does seem to take a few seconds for the setting to take effect , then hide the child settings. I'm not exactly sure why this particular setting is slow. 
![NTP setting](https://i.ibb.co/hm0537c/2021-03-25-21-09-47.gif)

I have noted though, the child settings under email are in fact not show/hiding.

**Comment by adamcoulombe** [comment]
I've added a progress indicator to make it more clear that something is happening when that checkbox is clicked. I think maybe it was just taking a very long time to submit, so it appears as if the child settings aren't being toggled.

**Comment by rudybrian** [comment]
Thanks @adamcoulombe, I guess I wasn't being patient enough, and good catch on the e-mail child settings. I noticed the odd entry for _emailserver_ in _www/settings.json_ but wasn't sure if it was intentional.
