### ISSUE TITLE
sequence->SingleStepSequenceBack() is broken

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#986]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
**FPP Version and Hardware**: 
v5.x-master-137-gb7845ee9 (master branch) -- Any hardware

**Describe the bug and Steps to reproduce**: 
1. Open the testing page (sequence tab)
2. Start a sequence
3. Pause the sequence
4. Click the "Step back" button.   (Multiple times is fine).  Notice that it doesn't actually step back even though Step Forward works fine. 

**Expected behavior**: 
Ideally Step Back should work just like Step Forward, or it should be removed from the UI.

It looks to me like the problem is actually in ReadSequenceData(), but I've not figure out enough about how Frame Caching works to confirm this is fixable.

**Comment by darylc** [comment]
Bigger issues to make the sequence testing page to work with remotes
