### ISSUE TITLE
Improper handling of the special characters in SSID and PSK in FPP 5

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#988]
FPP version: v5.x-master-157-gceee4369 (master branch)

Issue #553  (Improper handling of the special characters in PSK and SSID) came back in FPP 5 - see the screenshot below
![image](https://user-images.githubusercontent.com/19923088/114631892-77d88d80-9c8b-11eb-83d4-e0a0009626e9.png)

Needless to say, that it can't connect to WiFi.

**Comment by ghormann** [comment]
Should be fixed in latest master.

**Comment by Vlad-Star** [comment]
Confirmed, Thank you @ghormann for the quick fix!
