### ISSUE TITLE
FPP UI - No Delete button on "PI Pixel String" tab

### ISSUE THREAD

**Issue by Vlad-Star** [FalconChristmas/fpp#989]
FPP Version: | 5.x-master-167-g33aa0fd0
Platform: | Raspberry Pi (PiZero W)
FPP OS Build: | v4.4
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 0000000062af9175
Kernel Version: | 5.4.72+
System Boot Time: | 2021-04-25 15:09:53
fppd Uptime: | 03:12
Local Git Version: | 33aa0fd ChangeLog
Remote Git Version: | 33aa0fd

I've added two entries to Input/Output Setup -> Channel Outputs -> PI Pixel Strings tab, but there is no way to delete them. Delete button is not there. Not browser- or hardware-dependent (I tried Firefox/Chrome browsers, and Zero W/Pi 3B+ boards). See the screenshot below.

![image](https://user-images.githubusercontent.com/19923088/115997063-aa4d8900-a5af-11eb-9e7e-02b21abd2d09.png)

**Comment by adamcoulombe** [comment]
Thanks, this was ported from the old UI, which as far as I can tell did not have a delete button? 

I think @dkulp mentioned he wanted this tab to be more like the BBB strings, but I don't think that tab has a delete button either, since the outputs are typically configure by the capes.

**Comment by Vlad-Star** [comment]
@adamcoulombe you are right, I still have one RPi under FPP 4.4 and don't see Delete button there. Regardless, I think this is still a bug when you can't delete something that you just added (like me, to the wrong Pi). :)

**Comment by dkulp** [comment]
Page has been re-written to act like the BBB's page.
