### ISSUE TITLE
Auto-update (without reboot)

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#99]
Per request, we should add the update check to the header (stored in session data so we don't hit github with every page load), and a way to update periodically without rebooting, or we could simply force a reboot at a certain time which would accomplish the same thing.

http://falconchristmas.com/forum/index.php/topic,1002.0.html

Things to look out for with the auto-update:
- Whether it's configured to auto updated (duh!)
- If a show is going to start within a reasonable amount of time following the reboot/update.

**Comment by cpinkham** [comment]
We disable auto update now by default, since most users prefer to consciously upgrade.  Closing this ticket as a "probably won't do".
