### ISSUE TITLE
🚨 Potential OS Command Injection (CWE-78)

### ISSUE THREAD

**Issue by huntr-helper** [FalconChristmas/fpp#992]
👋 Hello, @cpinkham, @dkulp, @Materdaddy - a potential critical severity OS Command Injection (CWE-78) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-FalconChristmas/fpp** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by ghormann** [comment]
Fixed by 4c10baaf9c1cabee4be9de787af739771c6b320d

Found fix in  https://github.com/hitisec/fpp.git  and tested locally.

**Comment by hitisec** [comment]
Hi @huntr-helper @ghormann @dkulp @Materdaddy @hedrickbt @JamieSlome can you confirm the vuln on https://huntr.dev/bounties/1-other-FalconChristmas/fpp please? I saw you applied the changes proposed on https://github.com/418sec/fpp/pull/1 via https://github.com/FalconChristmas/fpp/commit/4c10baaf9c1cabee4be9de787af739771c6b320d but dont merge the PR.
Regards
