### ISSUE TITLE
BBB Audio - Fix BBB .asoundrc issue

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#996]
**FPP Version and Hardware**: 

**Describe the bug and Steps to reproduce**: 
Audio help. Fresh install of 4.6.1 onto a BBB K16-A-B. Using an FM Transmitter but not getting any audio.
Had some help last Christmas from Patrick Delaney deleting some files but had to keep doing that after each nightly shutdown.
Getting ready for Memorial Day and can't get any sound.

We deleted the /root/.asoundrc file, restarted fppd and then audio works. If the user reboots the BBB then that file is recreated.

Reported by Alex BB on Facebook group.

**Comment by cybercop23** [comment]
Looking at the logs....
/var/log/messages...
May 23 21:32:11 FPP kernel: [   48.385531] davinci-mcasp 48038000.mcasp: Sample-rate is off by 400 PPM

Timestamp of offending file.... 
-rw-r--r-- 1 root root 199 2021-05-23 21:32:10.955335092 -0400 /root/.asoundrc

**Comment by darylc** [comment]
@patdelaney I assume this is so old no action is required?
