### ISSUE TITLE
Panneau p3 64/64

### ISSUE THREAD

**Issue by lassauce** [FalconChristmas/fpp#998]
hello I just bought p3 64/64 panel May I realized that the rasberry did not take it into account will it be possible to make a 64/64 function thank you

**Comment by lassauce** [comment]
can you incorporate an update for 64/64 panels

**Comment by darylc** [comment]
@lassauce 

FPP will probably already supports them (depending on the exact hardware you are trying to use), just the GUI does not.

you can edit the underlying json file that the front end gui creates to use 64/64 panels already. I'm sure I've seen a post describing exactly how to do this if you don't understand on falconchristmas.com in the past.
