### ISSUE TITLE
Potential Security Vulnerabilities

### ISSUE THREAD

**Issue by zer0h-bb** [FalconChristmas/fpp#999]
Hello @ghormann, multiple flaws were found in your repository and were reported to huntr.dev, please check these reports :
- https://huntr.dev/bounties/2-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/3-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/4-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/5-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/6-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/7-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/8-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/9-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/10-other-FalconChristmas/fpp/

Best regards,

**Comment by ghormann** [comment]
Tracking status: _(will update over time)_

- https://huntr.dev/bounties/2-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/3-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/4-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/5-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/6-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/7-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/8-other-FalconChristmas/fpp/
- https://huntr.dev/bounties/9-other-FalconChristmas/fpp/ - Won't fix anytime soon.  (10 is a bigger issue)
- https://huntr.dev/bounties/10-other-FalconChristmas/fpp/ - Fixed

**Comment by zer0h-bb** [comment]
Can I report other vulnerabilities here ? Like
https://huntr.dev/bounties/11-other-FalconChristmas/fpp/

**Comment by ghormann** [comment]
> Can I report other vulnerabilities here ? Like
> https://huntr.dev/bounties/11-other-FalconChristmas/fpp/
> https://huntr.dev/bounties/12-other-FalconChristmas/fpp/

Would greatly prefer if you provided PRs that fixed the issues.  (You are more likely to get credit on huntr faster that way.)   I'm sure there are a larger number of issues your scripts can identify given the history and age of this code base and that the software almost always runs on private networks. (With a limited dev team, all volunteers,  we don't prioritize argument sanitizing issues unless a working patch is also provided. ) 

Short creating PRs, adding them to this single thread (this one) is preferred but don't expect quick action.

**Comment by ghormann** [comment]
Addressed 2-14 minus 9.
